### ISSUE TITLE
send_resolved:true not take effect when I setup two email addresses.

### ISSUE THREAD

**Issue by smallfish01** [prometheus/alertmanager#1002]
Hi Support,
When I setup two emails in my simply.yml and enable send_resolved, I just received the resolved email in my second email (smallfish@abc.com).
My simply.yml configurations as below:

receivers:
- name: 'default-receiver'
  email_configs:
  - to: '18927374488@189.cn'
  - to: 'smallfish@abc.com'
    html: '{{ template "email.html" .  }}'
    send_resolved: true
And I check http://localhost:9093/#/status:
- name: default-receiver
  email_configs:
  - send_resolved: false
    to: 118927374488@189.cn
    from: sys-admin@abc.com
    smarthost: smtp.abc.com:587

When I change my second emall (smallfish@abc.com) to the first, I cannot receive resolved email in smallfish@abc.com but I can receive resolved email in 18927374488@189.cn .

Thank you very much!
    auth_username: sys-admin@abc.com
    auth_password: <secret>
    auth_secret: null
    auth_identity: ""
    headers:
      From: smallfish@abc.com
      Subject: '{{ template "email.default.subject" . }}'
      To: 18927374488@189.cn
    html: '{{ template "email.default.html" . }}'
    require_tls: true
  - send_resolved: true
    to: smallfish@abc.com

**Comment by stuartnelson3** [comment]
`email_configs` only supports a single `to` field.

https://prometheus.io/docs/alerting/configuration/#<email_config>

**Comment by stuartnelson3** [comment]
To expand: You can comma separate the email names.

**Comment by smallfish01** [comment]
The issue has been fixed. I found I need setup send_resolved: true for every email address, such as:
name: 'default-receiver'
email_configs:

    to: '18927374488@189.cn'
    html: '{{ template "email.html" . }}'
    send_resolved: true
    to: 'smallfish@abc.com'
    send_resolved: true
