### ISSUE TITLE
panic on amtool on linux amd64

### ISSUE THREAD

**Issue by caarlos0** [prometheus/alertmanager#1019]
I wired amtool to my configs repo CI so I can check that my config is always valid, but, when running, I get this:

```console
$ amtool check-config ./modules/prometheus/files/etc/alertmanager/config.yml
panic: runtime error: invalid memory address or nil pointer dereference
--
  | [signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x86adf9]
  |  
  | goroutine 1 [running]:
  | github.com/prometheus/alertmanager/cli.init.5()
  | /go/src/github.com/prometheus/alertmanager/cli/silence_add.go:60 +0x49
  | github.com/prometheus/alertmanager/cli.init()
  | <autogenerated>:1 +0x1e9
  | main.init()
  | <autogenerated>:1 +0x44
```

On my macOS, same version of amtool against the same file works as expected.

**Comment by stuartnelson3** [comment]
https://github.com/prometheus/alertmanager/pull/1031 should fix this issue

**Comment by iksaif** [comment]
Could you run with https://github.com/prometheus/alertmanager/pull/1031 and send us the error ? I'm curious to know that triggers this.

**Comment by caarlos0** [comment]
@iksaif kind of hard to test it, since it was happening on travis-ci... but looking at the patch it makes sense that this would no longer be an issue...
