### ISSUE TITLE
Alertmanager mesh should support IPv6

### ISSUE THREAD

**Issue by mpalmer** [prometheus/alertmanager#1022]
At present, the `mesh.listen-address` command line flag only accepts an IPv4 address; attempting to request it listen on `IN6ADDR_ANY` (`::`) by specifying `-mesh.listen-address='[::]:6783'` (which works for everything else written in Go that wants a listen address) results in this:

```
panic: address ::: no suitable address found

goroutine 1 [running]:
github.com/prometheus/alertmanager/vendor/github.com/weaveworks/mesh.(*Router).listenTCP(0xc4200ca2a0)
        /go/src/github.com/prometheus/alertmanager/vendor/github.com/weaveworks/mesh/router.go:104 +0x10a
github.com/prometheus/alertmanager/vendor/github.com/weaveworks/mesh.(*Router).Start(0xc4200ca2a0)
        /go/src/github.com/prometheus/alertmanager/vendor/github.com/weaveworks/mesh/router.go:87 +0x2b
main.main()
        /go/src/github.com/prometheus/alertmanager/cmd/alertmanager/main.go:184 +0x2071
```

I'm aware that the problem is, in fact, inside `weaveworks/mesh`, and I've opened PR weaveworks/mesh#80 to get the most obvious IPv4isms removed from there.  I'm opening this issue so that the user-facing problem can be tracked, and a new version of mesh vendored once it is fixed.

**Comment by simonpasquier** [comment]
I think this can be closed since we have moved from mesh to [memberlist](https://github.com/hashicorp/memberlist) and the latter supports IPv6 (I've tested quickly that it works as expected).

cc @stuartnelson3

**Comment by vtolstov** [comment]
@simonpasquier can you provide link to description why this moving happened? (i'm only interests to read)

**Comment by simonpasquier** [comment]
@vtolstov https://github.com/prometheus/alertmanager/issues/1200 has some information. AIUI the mesh library had some limitations (like IPv6) and it was slow/hard to get it fixed. On the other hand, memberlist is widely used and very mature.

**Comment by vtolstov** [comment]
thanks!

**Comment by simonpasquier** [comment]
This issue relates to the old mesh library which has been since replaced so I'm going to close it. In case the latest AlertManager release doesn't support IPv6, feel free to open a new issue.
