### ISSUE TITLE
Negative matchers for routing and inhibition

### ISSUE THREAD

**Issue by beorn7** [prometheus/alertmanager#1023]
Currently, we use matchers at two different places in the config:

1. For the routing tree:
```
# A set of equality matchers an alert has to fulfill to match the node.
match:
  [ <labelname>: <labelvalue>, ... ]

# A set of regex-matchers an alert has to fulfill to match the node.
match_re:
  [ <labelname>: <regex>, ... ]
```
2. For inhibition rules:
```
# Matchers that have to be fulfilled in the alerts to be muted.
target_match:
  [ <labelname>: <labelvalue>, ... ]
target_match_re:
  [ <labelname>: <regex>, ... ]

# Matchers for which one or more alerts have to exist for the
# inhibition to take effect.
source_match:
  [ <labelname>: <labelvalue>, ... ]
source_match_re:
  [ <labelname>: <regex>, ... ]
```

Negative matching comes in handy in various situations. Since the RE2 library doesn't support straight-forward negative matching (e.g. `(?!re)`) as part of the regexp syntax, I see two ways of implementing them:

1. Add a `not_match` clause for each case. This is straight forward but increases the number of config options:
```
# Routing:
match:
  [ <labelname>: <labelvalue>, ... ]
not_match:
  [ <labelname>: <labelvalue>, ... ]
match_re:
  [ <labelname>: <regex>, ... ]
not_match_re:
  [ <labelname>: <regex>, ... ]

# Inhibition:
target_match:
  [ <labelname>: <labelvalue>, ... ]
target_not_match:
  [ <labelname>: <labelvalue>, ... ]
target_match_re:
  [ <labelname>: <regex>, ... ]
target_not_match_re:
  [ <labelname>: <regex>, ... ]
source_match:
  [ <labelname>: <labelvalue>, ... ]
source_not_match:
  [ <labelname>: <labelvalue>, ... ]
source_match_re:
  [ <labelname>: <regex>, ... ]
source_not_match_re:
  [ <labelname>: <regex>, ... ]
```
2. A possibly more elegant solution, which would even _reduce_ the number of config options, is to use the Promethean style matchers like we already do in the Alertmanager UI. The new config options could be used side-by-side with the old ones for a while for a smooth transition:
```
# Routing:
matchers:
  [ - <string>, ...  ]

# Inhibition:
target_matchers:
  [ - <string>, ...  ]
source_matchers:
  [ - <string>, ...  ]
```

Examples for the matcher strings: `'foo="bar"'` `'foo!="bar'` `'service=~"my-team.*"'` `'alertname!~"NodeDown|HostNotResponding"'`

**Comment by fabxc** [comment]
:+1: I'm in favour of using the well-known Prometheus matcher encoding.

**Comment by brian-brazil** [comment]
> Negative matching comes in handy in various situations.

I wonder whether this is something we actually need, I think what we have already largely covers this. Are there use cases other than users wanting to exclude specific named alerts from inhibition (which I think is a poor way to solve that particular problem, labels are saner)?

For example if you want to make an exception to a route with a negative matcher, then you could instead put a route with the exception before the main route.



Saying that, I do find the current `_re` a bit ugly. Escaping might be a concern if we used PromQL matchers.

**Comment by eugenekropotkin** [comment]
A negative matching will be useful for this case: two receivers, one for full flow, another one for partial alerts flow (dev becomes as semi-prod, for example - just to change routes to try it as prod)
A negative comparison can be "not recommended", but it very useful and exists in almost any programming language. I think, carefully written, it will not decrease alerting performance.
I can try to write first part :)

**Comment by brian-brazil** [comment]
You don't need a negative matcher for that, in fact it'd just complicate things. That is handled easily by two routes.

**Comment by eugenekropotkin** [comment]
Of course, I'm able to do my task by the way of adding more routes.... But with negative matching I can't shoot my leg by incorrect routes order, and rules will be more simple. 
Just think about, it's not complex, just a "not"-wrap on match - 20-30 lines of code, and no more.

**Comment by RichiH** [comment]
@brian-brazil How might escaping become an issue in this case?

As we're stumbling in similar issues, I would also be in favor of @beorn7 's second suggestion.

**Comment by brian-brazil** [comment]
> How might escaping become an issue in this case?

PromQL matchers use quotes.

> As we're stumbling in similar issues

Have you considered multiple routes?

**Comment by jolson490** [comment]
FWIW I would love to see this implemented.

My use case: I have clusters `sandbox`, `dev`, `test`, & `prod`. Whenever `KubeDeploymentReplicasMismatch` fires in any cluster other than `sandbox`, I'd like to send a notification to a certain Slack channel. 
 * Someone please correct me if I'm missing something, but currently for the `match_re` I believe I have to specify `cluster: (dev|test|prod)` (and as new clusters are created I'll need to remember to update that line).
 * But once this GH issue is implemented, I could do something like `cluster != "sandbox"`.

**Comment by ankitjain87** [comment]
+1 Even I would love to see this feature implemented.

I have a similar requirement as @jolson490, but in my case, I have multiple labels condition and I don't want to send alert for a specific type.

```
- match_re:
    cluster: dev|test|prod
    alertname: NodeHighMemoryUsage
```
So if I could do something like ` alertname: !NodeHighMemoryUsage` that will be great. I cannot keep all the alert names because they are too many, so simple negative matcher is best for this type scenario.

**Comment by kranjcec** [comment]
Hi,

Are there any plans for resolving this issue?

Without negative matchers I can't find a solution to use cases like this: We have 50 teams, and every team handles their alerts. When a data center goes down (e.g., because of network problems), we want to inhibit all alerts except for teams Team_1234567890 and Team_ABCDEFGHIJ.

Thanks.

**Comment by roidelapluie** [comment]
> Hi,
> 
> Are there any plans for resolving this issue?
> 
> Without negative matchers I can't find a solution to use cases like this: We have 50 teams, and every team handles their alerts. When a data center goes down (e.g., because of network problems), we want to inhibit all alerts except for teams Team_1234567890 and Team_ABCDEFGHIJ.
> 
> Thanks.

You could use prometheus alerts_relabel_configs:

- source_labels: [team]
  regex: Team_1234567890|Team_ABCDEFGHIJ
  target_labels: dc_team_alert
  replacement: "yes"

and inhibit

match_target:
   dc_team_alert: ""

**Comment by beorn7** [comment]
Just for the record: I'm in favor of my 2nd suggestion in the OP. (o:

I'd propose a PR if I had time for it. But since I don't, perhaps we can do a better job encouraging a contribution from someone in the wider community? It would be helpful to come to a clear message here which route we would like to go. @simonpasquier as the maintainer of AM, your preference has a particular weight. Could you lead the way so that we can come to a consensus?

(And FYI @brancz : I could imagine the lack of clarity on issues like this one is one of the reasons for a failure to attract contributions.)

**Comment by roidelapluie** [comment]
> Just for the record: I'm in favor of my 2nd suggestion in the OP. (o:

Then I'd like to amend it to add '{}' between the matchers for clarity, and don't use a list anymore. That would be prometheus-y:

'{level="critical",team=~".*oncall"}'

**Comment by kranjcec** [comment]
...
> > Without negative matchers I can't find a solution to use cases like this: We have 50 teams, and every team handles their alerts. When a data center goes down (e.g., because of network problems), we want to inhibit all alerts except for teams Team_1234567890 and Team_ABCDEFGHIJ.
...
> 
> You could use prometheus
> 
> ```
> alerts_relabel_configs:
> - source_labels: [team]
>   regex: Team_1234567890|Team_ABCDEFGHIJ
>   target_labels: dc_team_alert
>   replacement: "yes"
> ```

Thank you.

It looks like that is a solution to my problem :-)

BTW There are some typos:
```
alerting:
  alert_relabel_configs:
  - source_labels: [team]
    regex: Team_1234567890|Team_ABCDEFGHIJ
    target_label: dc_team_alert
    replacement: "yes"
```

**Comment by ankon** [comment]
As input for the discussion: my use-case for which I found this issue is a system where I have a service watching all other services _and itself_. I want to inhibit alerts when other services are "failing" if the alert is also triggered for the watching service itself. The thinking here is that if an alert is triggered for the watcher, it likely explains why all the other alerts are appearing.

```yaml
    - source_match:
        alertname: ServiceNotProcessingCommands
        service: watch-service
      target_match:
        alertname: ServiceNotProcessingCommands
```

I think this will work without negative matchers (because a inhibition rule shouldn't apply to itself), but the documentation also advises against relying on that behavior, and I would find an explicit "target_not_match: { service: keepalive-service }" easier to u nderstand.

(If there are "best practices" for this case that I should be using, please feel absolutely encouraged to tell me so! :) )

**Comment by beorn7** [comment]
> Then I'd like to amend it to add '{}' between the matchers for clarity, and don't use a list anymore. That would be prometheus-y:
>
> '{level="critical",team=~".*oncall"}'

I'm not sure if there is so much to gain from mimicking PromQL syntax more than needed. We are, after all, still within a YAML file, so I would like a repetition of something still be modeled by a YAML list. If we pushed it all into what is an opaque string from the perspective of YAML, we make it artificially hard to process for config management systems (e.g. you want to add a matcher with Jsonnet or something).

Yaml quoting rules are benign enough that both of the following is valid without nesting the quoting:

```Yaml
matchers:
  - level!='critical'
  - team=~'.*oncall'
```

```Yaml 
matchers: [ level!='critical', team=~'.*oncall' ]
```

For the only benefit of replacing Yaml-style square brackets with PromQL-style curly braces, we would add a requirement to explicitly nested quoting and the inability to inspect the list on the YAML (Jsonnet, etc.) level.

Also note that in the Alertmanager UI, we just put those matchers as separate items next to each other, which again tells us there is no real need to goose-chase after PromQL-esque syntax:

![image](https://user-images.githubusercontent.com/5609886/100932241-db87c880-34eb-11eb-910d-8235f2bef830.png)

I would even argue, putting the matchers in a YAML list is more consistent with how the Alertmanager UI works.

**Comment by beorn7** [comment]
Note that the parsing for the various matchers is already in the codebase because it is already used for the UI.

**Comment by aSquare14** [comment]
I'd like to work on this !

**Comment by aSquare14** [comment]
This is the PR(https://github.com/prometheus/alertmanager/pull/2434) that I opened for this issue. While it is still a work in progress and I need to fix things. Could someone please take a look and let me know if my approach is correct.

**Comment by beorn7** [comment]
@aSquare14 and I just looked at the existing parsing code for the UI together. Turns out it will parse any of the following:

`foo="bar"`, `{foo="bar"}`, `foo="bar", dings="bums"`,  `{foo="bar", dings="bums"}`

Since we'll just reuse that parsing code, we'll implicitly allow all of the above, plus specifying multiple matchers as items in a YAML list (so that you can combine matchers on the YAML level as discussed above).

In this way, all preferences expressed in this issue should be accommodated.

**Comment by Teriand** [comment]
i used matchers for block replacement:
```
  routes:
  - match:
      stand: test-agents
    receiver: mtsit_devstandsupport
  - match:
      zone: infrastructure
    receiver: mtsit-infrastructure
```

to

```
  routes:
  - matchers:
      - stand = test-agents
      - zone = infrastructure
    receiver: mtsit_devstandsupport
```

But its dont work:
```
May 06 11:56:10 prometheus-01.msk.mts.ru alertmanager[126337]: level=info ts=2021-05-06T08:56:10.202Z caller=coordinator.go:126 component=configuration msg="Completed loading of configuration file" file=/opt/prometheus/etc/alertmanager/am.yml
May 06 11:56:10 prometheus-01.msk.mts.ru alertmanager[126337]: level=info ts=2021-05-06T08:56:10.208Z caller=main.go:406 component=configuration msg="skipping creation of receiver not referenced by any route" receiver=mtsit-infrastructure
```

Can add any working example in doc with routes section?

**Comment by asquare14** [comment]
Here the link to the doc https://github.com/prometheus/alertmanager/blob/master/docs/configuration.md
Here is a sample of how it should work with routes https://github.com/prometheus/alertmanager/blob/master/dispatch/route_test.go#L386
Could you please check again after referring these.

**Comment by Teriand** [comment]
Examples in https://github.com/prometheus/alertmanager/blob/master/dispatch/route_test.go#L386 very good.
I double check my config, change mistake and it work like magic!

**Comment by beorn7** [comment]
It's also on the website: https://prometheus.io/docs/alerting/0.22/configuration/#matcher

(Once 0.22 is released, it will be under "latest".)

**Comment by beorn7** [comment]
I think we can close this, with the documentation in place.
