### ISSUE TITLE
Make matchers and labels in silence view and pre-view selectable

### ISSUE THREAD

**Issue by beorn7** [prometheus/alertmanager#1027]
If you view a particular silence (e.g. http://alertmanager/#/silences/<some-hash>), the matchers of the silence and the labels of the silenced alerts are not selectable. That would be handy (as you can copy&paste them somewhere else). They are not UI elements of other kind (as was the problem with the alert view, where labels were also buttons, clickable to add them to the current filter), so it should be quite easy to make them selectable.

@w0rm ?

**Comment by stuartnelson3** [comment]
Closed by #1030

**Comment by w0rm** [comment]
@beorn7 sorry I'm on vacation until tomorrow. @stuartnelson3 thanks for fixing this!

**Comment by w0rm** [comment]
Actually closing this issue.
