### ISSUE TITLE
Opening silence link in new tab doesn't work as expected.

### ISSUE THREAD

**Issue by beorn7** [prometheus/alertmanager#1029]
It's often desirable to keep the current view of alerts in the current browser tab/window and open something like the silence creation window in a new tab. However, if I middle-click or right-click-open-in-new-tab of the "Silence" link of an alert, the silence fields in the new tab are completely empty and not pre-populated as expected.

**Comment by stuartnelson3** [comment]
We populate the form with information in the original window, and don't transmit it within the URL (for example).

@w0rm @mxinden I'm sure we had this discussion, but I can't remember why we decided to not encode the new silence in the URL. Anyone remember? We could potentially drop the `keep=1` variable and encode the information in the URL, and any values in the URL will be put into the correct places on the silence form.

**Comment by mxinden** [comment]
@stuartnelson3 Sorry, I don't remember this discussion either. Encoding the *about to be created* silence in the URL sounds like a great solution.

**Comment by w0rm** [comment]
If we encode form fields in the URL, does it have to update if the fields change?

**Comment by stuartnelson3** [comment]
if it's not difficult, then yes, that would be good. if it's difficult, then maybe we just consume the values initially to populate the form, but then clear them.

**Comment by w0rm** [comment]
@stuartnelson3 perhaps could be done via a redirect, we send a user to a location that parses the silence from the query string, populates the form and clears the location.

**Comment by stuartnelson3** [comment]
sounds fine to me
