### ISSUE TITLE
race in gossip

### ISSUE THREAD

**Issue by brancz** [prometheus/alertmanager#1037]
After some further testing, the go race detector has found possibly multiple races in the gossip protocol.

As the race detector was very elaborate with its output on this find, I put it in a gist, rather than including it here in the issue.

https://gist.github.com/brancz/db2b2a8a3a60617c07ceee84e5e0b445

@fabxc @stuartnelson3

**Comment by stuartnelson3** [comment]
this is really interesting, this is the first time you've encountered this ? I think SC has been running HA alertmanager for at least 6 months.

**Comment by stuartnelson3** [comment]
I'm gone all weekend, but could potentially look at this next week. @brancz are you working on this / have plans to work on this soon?

**Comment by brancz** [comment]
I think I’ve found the core of this issue, but the Fox involves non trivial changes across the code base. My suspicion is that we’re not locking the gossipdata object properly. As we’re always locking around it instead of in methods bound to it, it’s extremely hard to reason about what’s happening in the first place.

**Comment by leoluk** [comment]
I'm looking forward to use alertmanager HA in production, but this issue is still present, correct?

**Comment by brancz** [comment]
This is currently present, but I'm going to tackle this issue this or next week.
