### ISSUE TITLE
send_resolved should not be configured in receiver config.

### ISSUE THREAD

**Issue by berlinsaint** [prometheus/alertmanager#1044]
In my opinion, alertmanager can be a single component running. Now prometheus mainly do the monitoring things and alerts about the metrics . it is obviously that alermanager do the good job.
In some case about logging monitor, when some errors occur, and then passed to the alertmanager and alert, but this logging error isn't a constant event, not like metrics monitor , if we configure a receiver with "send_resolved :true" and, after the timeout it will send a resolved alert. if we don't configure it ,other metric alerts can't send resloved alert.
so i think the send_resolve should be configured in route block , the same as group_by,gour_interval. what do you think?

**Comment by brian-brazil** [comment]
Whether sending resolved makes sense depends on the notifier. For example it is spammy for email/slack, but not so for Pagerduty. This it needs to be configured per notifier.
