### ISSUE TITLE
Unable to template hipchat and email in config

### ISSUE THREAD

**Issue by EcHoOfInSaNiTy** [prometheus/alertmanager#1048]
**What did you do?**
Added email address and hipchat rooms and tokens into time series data so I can automatically route alerts without having to statically update the config file. Everything works as intended except for when it comes to the receivers labelled 'team'
**What did you expect to see?**
I expected to see alerts go to the receivers labelled teams email and hipchat
**What did you see instead? Under which circumstances?**
I get an error saying that there is no to address found, and a 404 error from hipchat because the values are empty
**Environment**

* System information:

	insert output of `uname -srm` here

* Alertmanager version:

	insert output of `alertmanager -version` here

* Prometheus version:

	insert output of `prometheus -version` here (if relevant to the issue)

* Alertmanager configuration file:
    global:
      # ResolveTimeout is the time after which an alert is declared resolved
      # if it has not been updated.
      resolve_timeout: 5m

      # The smarthost and SMTP sender used for mail notifications.
      smtp_smarthost: 'myhost'
      smtp_from: 'random@gmail.com'
      smtp_require_tls: false
      # smtp_auth_username: 'foo@bar.com'
      # smtp_auth_password: 'barfoo'

      # # The auth token for Hipchat.
      hipchat_auth_token: 'notmytoken'
      # # Alternative host for Hipchat.
      hipchat_url: 'myhipchaturl'

    # # The directory from which notification templates are read.
    templates:
    - '/etc/alertmanager-templates/*.tmpl'

    # The root route on which each incoming alert enters.
    route:

      # The labels by which incoming alerts are grouped together. For example,
      # multiple alerts coming in for cluster=A and alertname=LatencyHigh would
      # be batched into a single group.

      group_by: [email_to, hipchat_room_id, hipchat_token, alertname, cluster]

      # When a new group of alerts is created by an incoming alert, wait at
      # least 'group_wait' to send the initial notification.
      # This way ensures that you get multiple alerts for the same group that start
      # firing shortly after another are batched together on the first
      # notification.

      group_wait: 30s

      # When the first notification was sent, wait 'group_interval' to send a batch
      # of new alerts that started firing for that group.
      group_interval: 5m

      # If an alert has successfully been sent, wait 'repeat_interval' to
      # resend them.

      #repeat_interval: 1m
      repeat_interval: 15m

      # A default receiver

      # If an alert isn't caught by a route, send it to default.
      receiver: team

      # All the above attributes are inherited by all child routes and can
      # overwritten on each.

      # The child route trees.
      routes:
      - match_re:
          service: ^(this|thing)$
          receiver: team
        group_by: [alertname, cluster]
        routes:
        - match:
            severity: warning
          receiver: email_router
          group_by: [email_to]
          routes:
          - match:
              severity: critical
            receiver: hipchat_router
            group_by: [hipchat_room_id, hipchat_token]

    receivers:
    - name: team
      email_configs:
      - to: 'me@gmail.com, you@gmail.com, us@gmail.com'
        from: "random@gmail,com"
      hipchat_configs:
      - room_id: '1337'
        auth_token: 'notarealtoken'
    - name: email_router
      email_configs:
      - to: "{{ .GroupLabels.email_to }}"
        from: "random@gmail.com"
    - name: hipchat_router
      hipchat_configs:
      - room_id: "{{ .GroupLabels.hipchat_room_id }}"
        auth_token: "{{ .GroupLabels.hipchat_token }}"
```

* Prometheus configuration file:
```
insert configuration here (if relevant to the issue)
```

* Logs:
```
insert Prometheus and Alertmanager logs relevant to the issue here
```

**Comment by brian-brazil** [comment]
I think you took https://www.robustperception.io/using-labels-to-direct-email-notifications/ a little too literally, make sure you adjust it for hipchat.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
