### ISSUE TITLE
UI: Negative filtering filters out empty/missing labels.

### ISSUE THREAD

**Issue by beorn7** [prometheus/alertmanager#1060]
**What did you do?**

Filtered in the UI for alerts with unequality matcher: `foo!="bar"`

**What did you expect to see?**

I still want to see alerts that do not have a `foo` label at all, as "missing label" implies "label with empty label value", and `foo=""` clearly fulfills `foo!="bar"`.

**What did you see instead? Under which circumstances?**

An alert without `foo` label was not displayed with above filter.

**Environment**

* Alertmanager version:

0.9.1

**Comment by stuartnelson3** [comment]
Ah, this wouldn't have been the expected behavior for me. When filtering by a label `foo!="bar"`, I would expect to be returned timeseries with a label foo, but that label not equalling bar.

Your expectation is consistent with prometheus, so it makes sense to fix this in alertmanager.

**Comment by beorn7** [comment]
Indeed, we should definitely keep the semantics consistent throughout the Prometheus stack. Empty label and no label has to be semantically equivalent.
