### ISSUE TITLE
Pushover: Resolved alerts are sent as emergency alerts

### ISSUE THREAD

**Issue by Luzifer** [prometheus/alertmanager#107]
This is a follow-up from #90:

> Well, now that you made me look at it again, I wonder whether "resolved" notifications should not be emergencies :) (@juliusv)

Confirmed, this totally should be the case! Shocked me a little bit to receive three new emergency notifications after the first bunch… xD

![2015-08-01-22 45 39](https://cloud.githubusercontent.com/assets/20142/9023876/6c3a52e6-38b0-11e5-8403-7e1f6d9e68e3.png)

**Comment by juliusv** [comment]
@Luzifer Wanna send a fix? :)
