### ISSUE TITLE
Have way to do reporting on alertmanager information

### ISSUE THREAD

**Issue by pdf** [prometheus/alertmanager#108]
Currently there's no way to report from prometheus on the silenced state of alerts.  I propose exposing alerts via the `/metrics` endpoint as `alertmanager_alerts` or similar.  At a minimum, the series should include the labels as passed from prometheus, as well as an additional bool label for `silenced`, and the current value.

The use-case is to allow consoles displaying alerts to take into consideration the silenced state.  I could probably implement this, but I'm concerned that it might be wasted effort with a rewrite in the wings.

Refs prometheus/prometheus#966

**Comment by brian-brazil** [comment]
I'm not sure about creating a loop like that in the system, especially in the case where there's multiple alertmanagers, as it may lead to unreliability and blowup of timseries. What exact use are you expecting from these consoles?

**Comment by fabxc** [comment]
Those time series would require a degree of consistency which is not aligned with alertmanagers long-term goal of being a distributed AP system.

I am also curious about the problem you want to solve – there might be a better solution

**Comment by pdf** [comment]
We mainly just want to report on alerts, but omit those that are silenced.  Being able to see when alerts were silenced is also valuable information though.

**Comment by matthiasr** [comment]
@brian-brazil I'm not too concerned about this loop, the Prometheus->AM interaction is very different from the AM->Prometheus one. Also, whether they even scrape this way or have a meta-monitor that ingests this information is up to the user. What potential for timeseries blowup do you see, aside from alerting on alerts alerting?

@fabxc but if there is inconsistency, we'd want to know, and thus need metrics metrics metrics.

We have metrics for "this alert is firing" in Prometheus but no way of determining whether it is silenced. I think making this accessible as a metric is the logical way.

**Comment by fabxc** [comment]
@matthiasr this only works if we have replicated metrics per AM so we can actually see the differences. I was assuming we were looking at a single metric for the whole AM setup in which we would only get artifacts.
One could certainly think about this again.
Currently a bit wary about all the upcoming feature requests for AM for which we don't have any priority or structure in place.

**Comment by brian-brazil** [comment]
> What potential for timeseries blowup do you see, aside from alerting on alerts alerting?

Alerting on alerts could cause a positive feedback loop, taking out the system. This information doesn't belong on the alertmanager /metrics, as it's not information about the alertmanager in the same way the mysqld_exporter doesn't export all the data from the database.

> We have metrics for "this alert is firing" in Prometheus but no way of determining whether it is silenced. I think making this accessible as a metric is the logical way.

I think whatever use case there is for that is better handled within the alertmanager itself, prometheus shouldn't generally know about silences as that's not it's concern.

**Comment by pdf** [comment]
> Alerting on alerts could cause a positive feedback loop, taking out the system.

Sure, I guess it's possible for someone to shoot themselves in the foot, but I don't really see that this should be a blocker.  I could probably find a bunch of ways to create a feedback loop if I tried hard enough.

> it's not information about the alertmanager in the same way the mysqld_exporter doesn't export all the data from the database

I'm not sure this is a sensible comparison at all.  The data in the MySQL database generally doesn't have significant value as a metric for the operational state of your environment, but what's alerting, and whether it was planned or someone's already aware of it, certainly is.

> I think whatever use case there is for that is better handled within the alertmanager itself, prometheus shouldn't generally know about silences as that's not it's concern.

This isn't about making Prometheus 'know' about silences - this is about getting the data about what alerts are firing, and whether they're silenced, into the time series database, so that this information can be reported on.  I also don't like the language, "whatever the use case there is for that" - it suggests out-of-hand dismissal.

Avoiding data silos is a major reason for deploying systems like these, but you seem to be suggesting for some reason that alertmanager _must_ be one, which doesn't make any sense to me at all.

**Comment by brian-brazil** [comment]
> I'm not sure this is a sensible comparison at all.

It comes from experience. There are more than a few people who effectively want to dump significant chunks of their databases into their monitoring as they're monitoring the data rather than the system. Such data does not belong on /metrics, that doesn't preclude it coming out via some other endpoint.

Prometheus in general is not a logging system, and isn't designed for an event logging use case.

> this is about getting the data about what alerts are firing, and whether they're silenced, into the time series database, so that this information can be reported on.

Ah, a reporting use. Maybe we should be looking at logging in the alertmanager, currently there's the generic webhook.

> Avoiding data silos is a major reason for deploying systems like these, but you seem to be suggesting for some reason that alertmanager must be one, which doesn't make any sense to me at all.

My primary concern is that our users will be able to build and maintain a reliable monitoring system. Features like you propose require careful consideration, as it's not much of a jump from that to having the alertmanager as a critical dependency for alerting or otherwise making the system overly complicated and ultimately failing to serve the needs of our users. We need to keep in mind all ways that users may deploy the system and if the feature makes sense on balance.

**Comment by juliusv** [comment]
@pdf Yep, Alertmanager definitely shouldn't be a data silo. I don't feel too strongly about having this information in `/metrics` or not (though I see the ways this could go wrong), but then it will definitely be available through another API endpoint.

Just be aware that at the moment our priority is more about rearchitecting Alertmanager as a whole (basically a rewrite), so this might take a while to get implemented.

**Comment by pdf** [comment]
Yeah, I'm not really fussed what endpoint it's available on, but I definitely think it should be available somewhere.  And having the alerts (plus silence status) available as a time-series makes for easy querying and correlation against other metrics.  Seeing as we already have an equivalent in `ALERTS` (sans-silences), this doesn't seem like an unreasonable desire.

Probably an opportune time to hash various stuff like this out while the redesign is happening.

**Comment by wrouesnel** [comment]
Getting a time series of alerts and notifications in some way is fairly important. I pretty routinely get asked to give a list of all alerts over some time period. But its definitely event data more then metrics. What's needed is the ability to write it to logs, sql or something like influx.

**Comment by brian-brazil** [comment]
It looks like we're going to have some form of logging solution.

**Comment by mattbostock** [comment]
@brian-brazil @fabxc: I'd like to be able to see a metric that reports the number of firing alerts in AlertManager (not details of which alerts, rather a gauge that counts all alerts). Would a PR be accepted that added metrics similar to the following:

```
alertmanager_alerts_firing
alertmanager_alerts_silenced
alertmanager_alerts_inhibited
```

So `alertmanager_alerts_firing - alertmanager_alerts_silenced - alertmanager_alerts_inhibited` would give the number of alerts that AlertManager currently knows about that would have sent a notification.

**Comment by fabxc** [comment]
Yes, that would be accepted. That probably collides with the current semantics though. We only determine inhibition/silencing at notification time. So these metrics would, just as the UI bits showing this, basically always be stale.

It's probably still be better than nothing. I think if you hook into the `types.Marker` you could hack it in there. Long-term we want to solve the problem better in general.

You probably want this to be `alertmanager_alerts_total` rather than `alertmanager_alerts_firing` though as it is the default. Similar as in requests, where you count `requests_total` and `request_errors_total` rather than `requests_successes_total` and `request_errors_total`.

**Comment by stuartnelson3** [comment]
Closed by https://github.com/prometheus/alertmanager/commit/bff889b4
