### ISSUE TITLE
Error in silences page

### ISSUE THREAD

**Issue by davidkarlsen** [prometheus/alertmanager#1092]
After upgrading to v0.10.0, I get 
active/pending/expired all say "Unexpected response from api: Expecting a List at _.data but instead got: null" when visiting:
http://myhostname:9093/#/silences

**Comment by josedonizetti** [comment]
Hey, @davidkarlsen there's a PR https://github.com/prometheus/alertmanager/pull/1090 to address it. Thanks for feedback.

**Comment by stuartnelson3** [comment]
Closed by #1090
