### ISSUE TITLE
Official docker image

### ISSUE THREAD

**Issue by vaibhavsood** [prometheus/alertmanager#1106]
Hi,

Want to check if there is a docker image for alertmanager which is a official docker image? I could not find one under dockerhub official images https://hub.docker.com/explore/

If not, want to check if there is any plan to add an official configmap-reload image to dockerhub? https://docs.docker.com/docker-hub/official_repos/#how-do-i-create-a-new-official-repository,

Also want to check if it makes sense to make alertmanager an official image based on the subjective considerations from the link

**What did you do?**

**What did you expect to see?**

**What did you see instead? Under which circumstances?**

**Environment**

* System information:

	insert output of `uname -srm` here

* Alertmanager version:

	insert output of `alertmanager -version` here

* Prometheus version:

	insert output of `prometheus -version` here (if relevant to the issue)

* Alertmanager configuration file:
```
insert configuration here
```

* Prometheus configuration file:
```
insert configuration here (if relevant to the issue)
```

* Logs:
```
insert Prometheus and Alertmanager logs relevant to the issue here
```

**Comment by sdurrheimer** [comment]
@vaibhavsood Officiel docker images are on quay.io : [README.md](https://github.com/prometheus/alertmanager#docker-images)

**Comment by vaibhavsood** [comment]
Thanks @sdurrheimer! Had a couple of queries

1) Are these docker images multi-arch (running on non-x86 platforms like ppc64le)?

2) If not, is there any plan to make them so? 

Dockerhub has a way to build multi-arch images https://github.com/docker-library/official-images#multiple-architectures, but since these images are hosted on quay.io not sure ways to do it there

**Comment by sdurrheimer** [comment]
@vaibhavsood Not yet, I haven't got the time to look at this lately.

**Comment by vielmetti** [comment]
@sdurrheimer - any update or plans to look at multi-arch Docker images?  It's been about a year since this issue closed, wondering if you're open to reconsidering.

**Comment by simonpasquier** [comment]
@vielmetti the canonical issue is https://github.com/prometheus/promu/issues/89.
