### ISSUE TITLE
Add Auto-Submitted: auto-generated header to email notifications

### ISSUE THREAD

**Issue by randomvariable** [prometheus/alertmanager#1111]
**What did you expect to see?**
In order to play nicely with email systems, it is best practice to set the following header:

`Auto-Submitted: auto-generated` as per [RFC 8384](https://tools.ietf.org/search/rfc3834).

This reduces the possibility of email loops and storms on some email systems.

**Comment by stuartnelson3** [comment]
Looking at https://tools.ietf.org/search/rfc3834#section-5.2, I'm wondering about the meaning of "direct responses to other messages". 

```
-  MUST NOT be used on a message issued in direct response to another
      message
```

While the alertmanager message is being generated, it is directly in response to messages sent by Prometheus. Perhaps someone with more experience could help understand how to interpret this.

@brian-brazil @SuperQ

**Comment by brian-brazil** [comment]
I'd presume that "message" here means email.

What I'd wonder here if this would cause issues with some ticketing systems etc. which use these to (incorrectly) filter out undesirable messages, for which the user depends on the return "ticket created" message to go somewhere.

**Comment by randomvariable** [comment]
They must mean email.
The concern about ticket flows is valid though. I've just googled a few I've used in the past (OTRS, BMC Remedy), and you can match on that header. However, with FreshDesk, new ticket notifications will be suppressed in the presence of "auto-" values. https://support.freshdesk.com/facebook/support/discussions/topics/1279/page/last

So we should feature flag this. Which way round should the default be?

**Comment by brian-brazil** [comment]
> However, with FreshDesk, new ticket notifications will be suppressed in the presence of "auto-" values. 

That's only the notifications, not the creation of the ticket.

I personally would prefer that we don't end up with N different configuration options for various email headers, but rather hardcode some headers that make sense and allow users to add more.

**Comment by LuboVarga** [comment]
Just to note, I have seen configuration solution like this:
```
  - name: 'prometheus-alerts-uncategorized'
    email_configs:
      - send_resolved: false
        to: 'prometheus-uncategorized@example.com'
        headers: {'Auto-Submitted':'auto-generated'}
```

**Comment by roidelapluie** [comment]
Given that:
1. It can be added by configuration
2. It could break existing users
3. Making it "not mandatory" would complexify the configuration

I think we can close this ; as it is more a configuration management issue.

**Comment by simonpasquier** [comment]
I agree with @roidelapluie, it can already be supported by Alertmanager today hence there's no need to change the current behavior.

**Comment by randomvariable** [comment]
> FWIW, it's not RFC 8384 but [RFC 3834](https://datatracker.ietf.org/doc/html/rfc3834)

thx, sometimes i'm known to type properly.
