### ISSUE TITLE
amtool accessible in docker image for alertmanager 

### ISSUE THREAD

**Issue by ajuszczak** [prometheus/alertmanager#1119]
**What did you do?**

I'd like to be able to use `amtool` within alert manager docker image to be able to verify configuration passed to docker image before I will push it to Nexus.

```
> docker run -it --entrypoint=amtool prom/alertmanager:latest
```

**What did you expect to see?**
Help message returned by amtool script.

**What did you see instead? Under which circumstances?**

Error, which says that specific command doesn't exist.
```
docker: Error response from daemon: oci runtime error: container_linux.go:265: starting container process caused "exec: \"amtool\": stat amtool: no such file or directory".
```

Please note that this is actually done right now in Prometheus image:
```
> docker run -it --entrypoint=promtool prom/prometheus:latest
usage: promtool <command> [<args>]

Available commands:
  check-config     validate configuration files for correctness
  check-metrics    validate metrics for correctness
  check-rules      validate rule files for correctness
  help             prints this help text
  version          print the version of this binary
```
**Environment**

* System information:

Linux 4.9.49-moby x86_64

* Alertmanager version:

alertmanager, version 0.11.0 (branch: HEAD, revision:     30dd0426c08b6479d9a26259ea5efd63bc1ee273)
  build user:       root@3e103e3fc918
  build date:       20171116-17:43:56
  go version:       go1.9.2

**Comment by Arnold1** [comment]
im also interested, is there a way to login to the running alertmanager container?
