### ISSUE TITLE
log.format flag missing since 0.10.0

### ISSUE THREAD

**Issue by omadawn** [prometheus/alertmanager#1128]
**What did you do?**
Tried to upgrade to 0.10.0

**What did you expect to see?**
Alertmanager to run

**What did you see instead? Under which circumstances?**
Alertmanager failed to start with the error
flag provided but not defined: -log.format

**Environment**

* System information:
I confirmed this on two platforms:

Linux 3.10.0-514.26.1.el7.x86_64 x86_64
Darwin 16.7.0 x86_64

* Alertmanager version:

alertmanager, version 0.11.0 (branch: HEAD, revision: 30dd0426c08b6479d9a26259ea5efd63bc1ee273)
  build user:       root@3e103e3fc918
  build date:       20171116-17:43:56
  go version:       go1.9.2

* Prometheus version:
NA

* Alertmanager configuration file:
I have verified that log.format does not show up in the output of -h starting in version 0.10.0. This happens with or without a configuration file.

* Prometheus configuration file:
NA

* Logs:
Dec 04 10:16:27 default-base-rhel7.vagrantup.com alertmanager[15205]: flag provided but not defined: -log.format
Dec 04 10:16:27 default-base-rhel7.vagrantup.com alertmanager[15205]: Usage of /usr/local/heimdall/alertmanager/alertmanager:
Dec 04 10:16:27 default-base-rhel7.vagrantup.com alertmanager[15205]: -config.file string
Dec 04 10:16:27 default-base-rhel7.vagrantup.com alertmanager[15205]: Alertmanager configuration file name. (default "alertmanager.ym
Dec 04 10:16:27 default-base-rhel7.vagrantup.com alertmanager[15205]: -data.retention duration
Dec 04 10:16:27 default-base-rhel7.vagrantup.com alertmanager[15205]: How long to keep data for. (default 120h0m0s)
Dec 04 10:16:27 default-base-rhel7.vagrantup.com alertmanager[15205]: -log.level value
Dec 04 10:16:27 default-base-rhel7.vagrantup.com alertmanager[15205]: Only log messages with the given severity or above. One of: [de
<truncated>

I checked the output of -h back until I found it again.

$ ./alertmanager-0.11.0.darwin-amd64/alertmanager -h
Usage of ./alertmanager-0.11.0.darwin-amd64/alertmanager:
  -config.file string
    	Alertmanager configuration file name. (default "alertmanager.yml")
  -data.retention duration
    	How long to keep data for. (default 120h0m0s)
  -log.level value
    	Only log messages with the given severity or above. One of: [debug, info, warn, error] (default info)
<truncated>

$ ./alertmanager -h
Usage of ./alertmanager:
  -config.file string
    	Alertmanager configuration file name. (default "alertmanager.yml")
  -data.retention duration
    	How long to keep data for. (default 120h0m0s)
  -log.level value
    	Only log messages with the given severity or above. One of: [debug, info, warn, error] (default info)
<truncated>

$ ./alertmanager-0.9.1.darwin-amd64/alertmanager -h
Usage of ./alertmanager-0.9.1.darwin-amd64/alertmanager:
  -config.file string
    	Alertmanager configuration file name. (default "alertmanager.yml")
  -data.retention duration
    	How long to keep data for. (default 120h0m0s)
  -log.format value
    	Set the log target and format. Example: "logger:syslog?appname=bob&local=7" or "logger:stdout?json=true" (default "logger:stderr")
  -log.level value
    	Only log messages with the given severity or above. Valid levels: [debug, info, warn, error, fatal] (default "info")
<truncated>

**Comment by josedonizetti** [comment]
This was lost in the migration to go-kit/log. @juliusv does it make sense to add back? or is there another way to configure it? Prometheus is not supporting the flag as well (after the migration)

**Comment by brian-brazil** [comment]
The removal was intentional. Can you explain why you want this?

**Comment by omadawn** [comment]
Because I prefer to be able to deal with text based logs without having to redirect stdout/stderr in a service or use journalctl and I didn't realize it was intentional (I didn't see anything in the release notes about it. Please let me know if there was and I was looking in the wrong place.)

Digging into journald a bit it looks like I can get everything I want with that system so I agree with ditching it. Closing this issue.
