### ISSUE TITLE
Alertmanager Duration ui incorrectly calculated

### ISSUE THREAD

**Issue by stuartnelson3** [prometheus/alertmanager#1130]
**What did you do?**

Set a silence's start time after its end time

**What did you expect to see?**

the ui to either indicate that it is invalid, or not to update the duration

**What did you see instead? Under which circumstances?**

See picture:
![screenshot-2017-12-8 alertmanager](https://user-images.githubusercontent.com/1398104/33759163-9c89a2b6-dc01-11e7-9de2-ca5831405d07.png)

**Environment**

* System information:
Firefox Developer

* Alertmanager version:
0.11

**Comment by w0rm** [comment]
@stuartnelson3 good find, thanks for reporting this!

**Comment by w0rm** [comment]
I could not find a better solution than validating all time fields together, also noticed that we would parse the time even when it is empty

![silence](https://user-images.githubusercontent.com/43472/33788252-7a040112-dc71-11e7-9d02-c28687077441.gif)
