### ISSUE TITLE
Installation of amtool fails with go compiler error

### ISSUE THREAD

**Issue by nre-ableton** [prometheus/alertmanager#1142]
When attempting to install `amtool` via `go get`, I encounter the following error:

> github.com/prometheus/alertmanager/vendor/github.com/weaveworks/mesh
> ../go/src/github.com/prometheus/alertmanager/vendor/github.com/weaveworks/mesh/token_bucket.go:33: undefined: time.Until

`go version` reports `go version go1.7.4 linux/amd64`. I don't know much about `go` or the architecture of `amtool`, but looking at the error it seems that this is emitted from a third-party framework. Could it be that `amtool` simply needs to bump the version of this framework to one that includes a fix for this?

**Comment by stuartnelson3** [comment]
The easiest thing to do is to download a precompiled binary from our releases page: https://github.com/prometheus/alertmanager/releases

`time.Until` was added in go 1.8: https://golang.org/doc/go1.8#time

Your current version doesn't have this function, unfortunately.
