### ISSUE TITLE
Feature request: inhibit_rule per receiver

### ISSUE THREAD

**Issue by oleg-glushak** [prometheus/alertmanager#1143]
It would be nice to have this feature. 
Use case:

We use Alerta (via webhook_config) as alerts dashboard and Slack (via slack_config) to get notifications.
We have two alert rules in Prometheus:
1. Host is down. Label Severity: Warning
2. More then 10 hosts are down. Label Severity: Critical.

And we have inhibit_rule where we're muting Warning alerts when Critical one are fired to avoid spam in Slack channel. But it Alerta we don't want to have this Critical alert, but want to have many Warning alerts, each as a separate row in table.

What we configured works fine for Slack (we only get single notifications when many hosts are down at the same time), but in Alerta sometimes alerts stay forever because Alerta don't get 'resolved' state for the alert, because it was muted by inhibit_rule.

**Comment by brian-brazil** [comment]
You want #180. This doesn't make sense per-receiver, all logic of that sort is around routing.
