### ISSUE TITLE
Data race in api.Update()

### ISSUE THREAD

**Issue by stuartnelson3** [prometheus/alertmanager#1157]
**Environment**

* System information:

	`Linux 3.13.0-135-generic x86_64`

* Alertmanager version:
https://github.com/prometheus/alertmanager/commit/8b8642935aa4426d955329ad5012eaab29bd0075, with `-alerts.gc-interval=60s`

* Logs:
```
==================
WARNING: DATA RACE
Write at 0x00c4201e0418 by goroutine 99:
  github.com/prometheus/alertmanager/api.(*API).Update()
      /home/stuart/src/github.com/prometheus/alertmanager/api/api.go:145 +0x95
  main.main.func8()
      /home/stuart/src/github.com/prometheus/alertmanager/cmd/alertmanager/main.go:313 +0x456
  main.main.func9()
      /home/stuart/src/github.com/prometheus/alertmanager/cmd/alertmanager/main.go:387 +0x68

Previous read at 0x00c4201e0418 by goroutine 1959:
  [failed to restore the stack]

Goroutine 99 (running) created at:
  main.main()
      /home/stuart/src/github.com/prometheus/alertmanager/cmd/alertmanager/main.go:380 +0x2587

Goroutine 1959 (finished) created at:
  net/http.(*Server).Serve()
      /usr/local/go/src/net/http/server.go:2720 +0x37c
  net/http.(*Server).ListenAndServe()
      /usr/local/go/src/net/http/server.go:2636 +0xc7
  net/http.ListenAndServe()
      /usr/local/go/src/net/http/server.go:2882 +0xfe
  main.listen()
      /home/stuart/src/github.com/prometheus/alertmanager/cmd/alertmanager/main.go:501 +0x5f
==================
```
@brancz 

EDIT:
The config is being refreshed every 10min, which would be the source of this race.

**Comment by stuartnelson3** [comment]
failed to restore the stack unfortunately -.-

**Comment by stuartnelson3** [comment]
doesn't seem like such a show-stopper..

**Comment by brancz** [comment]
There is also not a lot we can do without the other stack trace, but you're probably right about the severity. My guess is that within the API one of the three fields being set are read without acquiring the mutex.

**Comment by stuartnelson3** [comment]
probably https://github.com/prometheus/alertmanager/blob/master/api/api.go#L471

**Comment by brancz** [comment]
Maybe not the only one, but definitely a candidate. I would suggest to "load" the field in the beginning of the function and just surround that with the mutex lock - just so we don't lock for the entire function.

**Comment by stuartnelson3** [comment]
fixed by https://github.com/prometheus/alertmanager/pull/1158
