### ISSUE TITLE
UI non-responsive when typing into silence filter bar

### ISSUE THREAD

**Issue by stuartnelson3** [prometheus/alertmanager#1160]
**What did you do?**
Was typing text into the silence filter bar. There were 10,000 silences rendered on the screen.
**What did you expect to see?**
The text to smoothly be entered into the filter bar
**What did you see instead? Under which circumstances?**
Long lag between pressing the button and it appearing in the text field
**Environment**

* System information:

	firefox developer

* Alertmanager version:

	v0.12.0

While some folks will say this is an indication that we should be paginating, I think a separate issue is that (apparently) the entire UI is being re-rendered on each keypress, which it shouldn't be.

To recreate:

1. Start alertmanager locally.
2. Load 10,000 silences:
```
for i in (seq 1 10000); ./amtool silence add -c 'test' -e '1h' --alertmanager.url 'http://localhost:9093' 'node=bar'$i; end
```
3. Go to the silence page in the UI and type something

@w0rm , can you confirm that it's the UI being re-rendered?

**Comment by w0rm** [comment]
@stuartnelson3 is this a dupe of #981?

**Comment by stuartnelson3** [comment]
ah, yes it is
