### ISSUE TITLE
Need help on Prometheus/Alertmanager email customizing on Subject and labels.

### ISSUE THREAD

**Issue by vsknov** [prometheus/alertmanager#1169]
Hi All,
I have configured Prometheus and Alertmanager in my environment and based on the Prometheus/Alertmanager configuration i am receiving notification mails from Alertmanager to my mail id.

Prometheus configuration:-
container.rules config:
#Alert If Container's Memory Usage exceeds 2 GB
ALERT container_memory_usage_bytes
  IF container_memory_usage_bytes{image=~"cri-registry:4777/harmony/criimages.*"} > 2000000000
  FOR 30s
  LABELS { severity = "warning" }
  ANNOTATIONS {
      summary = "{{ $labels.image}} Container memory usage exceeds 2 GB",
      value = "{{$value}}",
      description = "Container memory Usage exceeds on the following containers {{ $labels.instance}} with ID {{$labels.id}}.",
  }

Alertmanager configuration:-
# The smarthost and SMTP sender used for mail notifications.
global:
  smtp_smarthost: '10.x.x.x:25'
  smtp_from: 'QAAWS_Env_Monitoring@cognizant.com'

# The root route on which each incoming alert enters.
# The root route must not have any matchers as it is the entry point for all alerts.
route:
  receiver: 'mail'

#Send the Mail Notifications to below receiver.
receivers:
- name: 'mail'
  email_configs:
  - to: 'Sarava@cts.com'
    send_resolved: true
    require_tls: false

Received mails based on the above configuration.

Issue:- Need to customize the notification mails (Subject/Labels).

Subject:- 
[FIRING:2] container_memory_usage_bytes (ipsec true io.rancher.stack_service.name=${stack_name}/${service_name} hostgroup=Group1 hostname=Server1 io.rancher.service.primary.launch.config Base-cadvisor-2:8080 cadvisor QAAWS-CRI-Monitoring warning)

Labels:-

View in AlertManager
--
[2] Firing
Labels   alertname = container_memory_usage_bytes   container_label_io_rancher_cni_network = ipsec   container_label_io_rancher_cni_wait = true   container_label_io_rancher_container_ip    container_label_io_rancher_container_mac_address = 02:57:08:c9:9b:4e   container_label_io_rancher_container_name = Run-elasticsearch1-1   container_label_io_rancher_container_uuid =   48947a58-7935-44ab-a6b5-12331a1f512b   container_label_io_rancher_project_name = Run   container_label_io_rancher_project_service_name = Run/elasticsearch1   container_label_io_rancher_scheduler_affinity_container_label_ne =   io.rancher.stack_service.name=${stack_name}/${service_name}   container_label_io_rancher_scheduler_affinity_host_label = hostgroup=Group1   container_label_io_rancher_scheduler_affinity_host_label_soft =   hostname=Server1   container_label_io_rancher_service_deployment_unit =   7d6c42cf-60c6-461a-9ae8-15dc44d6c1cd   container_label_io_rancher_service_launch_config =   io.rancher.service.primary.launch.config   container_label_io_rancher_stack_name = Run   container_label_io_rancher_stack_service_name = Run/elasticsearch1   container_label_maintainer = adar@cts.com   id = /docker/8438963e9463032bc10a7091a32af356d8a6f32d961c3d5fd4fc1ab90d603073   image = cri-registry:4777/harmony/criimages:cri-Elasticsearch.Rel1.5-00   instance = Base-cadvisor-2:8080   job = cadvisor   monitor = QAAWS-CRI-Monitoring   name = r-Run-elasticsearch1-1-48947a58   severity = warning   Annotations   description = Container memory Usage exceeds on the following containers   Base-cadvisor-2:8080 with ID /docker/8438963e9463032bc10a7091a32af356d8a6f32d961c3d5fd4fc1ab90d603073.   summary = cri-registry:4777/harmony/criimages:cri-Elasticsearch.Rel1.5-00   Container memory usage exceeds 2 GB   value = 2.854391808e+09   Source

Can you please help on customizing the subject and labels.

Regards
Saravanan

**Comment by vsknov** [comment]
Can anyone please help on this issue?

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by vsknov** [comment]
Thanks for your valuable info 👍
