### ISSUE TITLE
UI: silence's expire button always expires the last silence in list (not the one the button is clicked for)

### ISSUE THREAD

**Issue by pborzenkov** [prometheus/alertmanager#1170]
**What did you do?**
Go to "Silences" view, "Active" tab. Click "Expire" button on the first silence on the list.

**What did you expect to see?**
The first silence got expired.

**What did you see instead? Under which circumstances?**
The last silence onlist got expired. It always happens when there is more than 1 silence on the list.

**Environment**

* System information:

Chrome 63, MacOS 10.13.2

* Alertmanager version:

alertmanager, version 0.12.0 (branch: HEAD, revision: fc33cc78036f82ef8d4734c197a96f7cb6c952a3)
  build user:       root@c9169eb10d06
  build date:       20171215-14:13:20
  go version:       go1.9.2

**Comment by niravpat** [comment]
I am seeing this too. I am able to reproduce this easily on windows 7 64 bit with [0.12.0](https://github.com/prometheus/alertmanager/releases/tag/v0.12.0). There seems to be a bug somewhere in the UI code that always calls `DELETE api/v1/silence` api with the last silence id. Using the api directly works fine.

**Comment by w0rm** [comment]
Thanks for reporting this! I'm working on the fix.

**Comment by niravpat** [comment]
thank you for the prompt fix. I tested it and it's working as expected now.

**Comment by mitchellrj** [comment]
When do you think the next release might be cut with this in it? :)

**Comment by stuartnelson3** [comment]
It's been just shy of a month since the last release, but there's definitely plenty that's been added (https://github.com/prometheus/alertmanager/compare/v0.12.0...master). I'm waiting on some final documentation updates for https://github.com/prometheus/alertmanager/pull/1190 and then there'll be a new release. Hopefully within the week.
