### ISSUE TITLE
Add an option to list recently expired silences

### ISSUE THREAD

**Issue by tbregolin** [prometheus/alertmanager#1176]
When an alert pops up it's often useful to check the recently expired silences. The work-around to do that right now is something like: "amtool silence query --expired --within 1s", then look towards the bottom of the big dump of expired silences.

The following PR adds an "--expired-within" option to list **only** the silences that have expired within Xs/m/w/y etc:

https://github.com/prometheus/alertmanager/pull/1175

Example: "amtool silence query --expired-within 30m" will show only the silences that have expired within the last half hour.

**Comment by stuartnelson3** [comment]
closed by #1190
