### ISSUE TITLE
grouping of alerts issues validating rules failing

### ISSUE THREAD

**Issue by Cornell123** [prometheus/alertmanager#1179]
**What did you do?**
cat node_memory_test.rules 
groups:
- name: node_memory_test.rules
  rules:
  - alert: Test_Instance_Memory_Utilisation
    expr: ((node_memory_MemTotal - node_memory_MemFree + node_memory_Buffers - node_memory_Cached ) / (node_memory_MemTotal)) * 100 > 85
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: "Instance {{ $labels.instance }} Memory high alert"
      description: "{{ $labels.instance }} of job {{ $labels.job }}"

**What did you expect to see?**
sanity on success for checking rules 
promtool check-rules /etc/prometheus/rules/*
Checking /etc/prometheus/rules/node_memory_test.rules

**What did you see instead? Under which circumstances?**

./promtool check-rules /etc/prometheus/rules/*
Checking /etc/prometheus/rules/node_memory_test.rules
  FAILED: parse error at line 2, char 2: unexpected <op:-> in record statement, expected "="

**Environment**
Ubuntu envirnoment
* System information:

	insert output of `uname -srm` here
Linux 3.13.0-128-generic x86_64

* Alertmanager version:

	insert output of `alertmanager -version` here
./alertmanager  --version
alertmanager, version 0.5.1 (branch: master, revision: 0ea1cac51e6a620ec09d053f0484b97932b5c902)
* Prometheus version:

	insert output of `prometheus -version` here (if relevant to the issue)
./prometheus --version
prometheus, version 1.7.0 (branch: master, revision: bfa37c8ee39d11078662dce16c162a61dccf616c)
  build user:       root@7a6329cc02bb
  build date:       20170607-09:43:48
  go version:       go1.8.3

* Alertmanager configuration file:
```
insert configuration here
```

* Prometheus configuration file:
```
insert configuration here (if relevant to the issue)
```

* Logs:
```
insert Prometheus and Alertmanager logs relevant to the issue here
```

**Comment by Cornell123** [comment]
Hi , Found the reason.. As am using 1.7X version of prometheus causing this issue. Do i have a way to group the alert rules in this version. Rather writing it down single rule for the same.

**Comment by brian-brazil** [comment]
Those are Prometheus 2.0 style rules, and this is the Alertmanager repository.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
