### ISSUE TITLE
amtool no longer takes duration units greater than hours

### ISSUE THREAD

**Issue by sinkingpoint** [prometheus/alertmanager#1183]
**What did you do?**

    amtool silence add -e 1w -c 'Testing' instance=somethingthatdoesntexist

**What did you expect to see?**

A silence being created

**What did you see instead? Under which circumstances?**

    amtool: error: time: unknown unit w in duration 1w

We believe this is a regression introduced by https://github.com/prometheus/alertmanager/pull/976 which changes the type of the cli arguments. Before this commit we took Strings and them parsed to them to Durations (The internal model, not the std lib one) ourselves. This PR instead takes std lib Durations which, according to [the docs](https://golang.org/pkg/time/#ParseDuration) only support units up to hours. 

Considering it's reasonably common to want to silence an alert for a day, or a week, or more, having to convert this into hours is tedious.

**Comment by stuartnelson3** [comment]
It should be fairly easy to re-introduce the behavior again -- take the durations as a string, and parse. Sorry for the regression!

**Comment by sinkingpoint** [comment]
Hah. No problem - that was a monster PR to review! I'll probably throw something together tomorrow London time, if this hasn't been picked up by then.

**Comment by stuartnelson3** [comment]
No worries, I got it
