### ISSUE TITLE
Amtool: `check-config` fails with "required flag --alertmanager.url not provided"

### ISSUE THREAD

**Issue by Dominik-K** [prometheus/alertmanager#1187]
**What did you do?**
`docker run --rm -v $(pwd):/src --entrypoint=amtool prom/alertmanager:master check-config /src/alertmanager.yml` 

**What did you expect to see?**
```
Checking '/src/alertmanager.yml'  SUCCESS
Found 0 templates:
```

Works with `docker run --rm -v $(pwd):/src --entrypoint=amtool prom/alertmanager:v0.12.0 check-config /src/alertmanager.yml`, but with additional line:
```
failed to get the current user, specify one with --author: user: Current not implemented on linux/amd64
```
**What did you see instead? Under which circumstances?**
`amtool: error: required flag --alertmanager.url not provided`

**Environment**

* System information: Darwin 15.6.0 x86_64
* Amtool version: Current master ([7b787dab057](https://github.com/prometheus/alertmanager/commit/7b787dab057a556bbc805335ba74af5aa861d785))

**Comment by stuartnelson3** [comment]
You need to supply a config file, or supply the flag

```
docker run --rm -v (pwd):/src -v $HOME/.config:/root/.config --entrypoint=amtool prom/alertmanager:master check-config /src/alertmanager.yml
```
```
# cat ~/.config/amtool/config.yml
alertmanager.url: http://localhost:9093
author: stn
require-comment: true
output: simple
```

**Comment by Dominik-K** [comment]
@stuartnelson3 Why does `amtool check-config` need `alertmanager.url`? Does it now need to talk to an Alertmanager instance to check the Alertmanager config?

**Comment by stuartnelson3** [comment]
It does not, it's an unintentional consequence of the move to a new flag parsing library. You can follow https://github.com/prometheus/alertmanager/issues/1199.
