### ISSUE TITLE
Add Help to TabList in the navigation

### ISSUE THREAD

**Issue by metalmatze** [prometheus/alertmanager#1192]
When looking at the Prometheus UI there's a "Help" button in the top navigation bar.
I propose to add the same for the Alertmanager and link to https://prometheus.io/docs/alerting/alertmanager/. This is also referenced in the README.md.

For me personally, it's always harder to find the Alertmanager docs compared to the Prometheus docs, thus I would make use of it quite frequently.

I quickly looked at the elm source code, but I don't have the time to start adding that button right now. Thoughts?

**Comment by stuartnelson3** [comment]
sounds cool to me. @w0rm ? :)
