### ISSUE TITLE
Replace weaveworks/mesh

### ISSUE THREAD

**Issue by Gouthamve** [prometheus/alertmanager#1200]
Quoting @brancz :

> It's effectively unmaintained, and we have various known problems; initial investigation shows hashicorp/memberlist might be a good candidate, as it has many similar primitives in its library

**Comment by brancz** [comment]
I've started this, but it's in a very very early stage.

**Comment by brb** [comment]
Out of curiosity, could you link to problems you encountered with weaveworks/mesh? Thanks.

**Comment by simonpasquier** [comment]
FWIW this is closed by #1232.

**Comment by brancz** [comment]
@simonpasquier thanks for catching, yes!

**Comment by cstyan** [comment]
the GSoC page still lists this as a project: https://github.com/cncf/soc#replace-weaveworksmesh

**Comment by brancz** [comment]
Thanks for noticing @cstyan! I opened a PR to remove it.
