### ISSUE TITLE
Why download package without default file template/default.tmpl

### ISSUE THREAD

**Issue by songjiayang** [prometheus/alertmanager#1203]
**What did you do?**
Config alertmanager with stmp options.

**What did you expect to see?**
The unzip package should contains the default template file `template/default.tmpl`.

**What did you see instead? Under which circumstances?**
not yet.

**Environment**

* Alertmanager version: 0.13.0

Then the default config file can be
```
templates: 
- './template/*.tmpl'
```

If we change to this, as a starter  they can use email template without downloading any file.

It's look better, right?

**Comment by stuartnelson3** [comment]
The default template is compiled into the binary, so that users do not need to include it in the config.
