### ISSUE TITLE
OpsGenie Integration uses wrong 'close' endpoint

### ISSUE THREAD

**Issue by jbarratt** [prometheus/alertmanager#121]
When an alert is opened *or* closed, OpsGenie uses the same endpoint.

Set here: https://github.com/prometheus/alertmanager/blob/master/manager/notifier.go#L89
Used here: https://github.com/prometheus/alertmanager/blob/master/manager/notifier.go#L671

However, the [docs](https://www.opsgenie.com/docs/web-api/alert-api#closeAlertRequest) say that for opening and closing one should use different endpoints.

Open: https://api.opsgenie.com/v1/json/alert/
Close: https://api.opsgenie.com/v1/json/alert/close

This is causing errors when attempting to close, and means OpsGenie notifications must be manually closed.

```
level=info msg="Sent OpsGenie notification: 3df913c5cc5fbd74: HTTP 400: {"code":3,"error":
"DiscardableValidationException[Can not validate alert. Reason: Property [message] cannot be empty.]; nested: FieldValidationException[Property [message] cannot be empty.]; "}"
 file=notifier.go line=685 
```

**Comment by jbarratt** [comment]
I have a tentative fix for this issue. Since I'm new to go, I'm having someone else give me some feedback before I kick over a PR.

**Comment by miekg** [comment]
Did you sent the PR, happy to review it (should be relatively small I think)

**Comment by jbarratt** [comment]
I didn't yet. Unit tests worked, but testing it 'for real' and it doesn't seem to. I'll send it over when I can verify that it really really works. Here's the [in process branch](https://github.com/prometheus/alertmanager/compare/master...jbarratt:opsgenie_endpoint_fix) in my fork.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [alertmanager] OpsGenie Integra..." ]
>I didn't yet. Unit tests worked, but testing it 'for real' and it doesn't seem to. I'll send it over when I can verify that it really really works. Here's the [in process branch](https://github.com/prometheus/alertmanager/compare/master...jbarratt:opsgenie_endpoint_fix) in my fork.

Looking at that branch and OpsGenie's docs, it should work. What happens if you
use an Id?

/Miek

--
Miek Gieben

**Comment by amorken** [comment]
Sorry, I didn't spot this issue and @jbarratt's branch before I send my PR over in #124. Anyway, looking at jbarratt's branch, I can't see anything wrong with it - it does pretty much the same thing as I do in #124, and I've seen #124 work fine when deployed here - alerts are created and closed in OpsGenie as they should be.

**Comment by juliusv** [comment]
Ah yes, noticed that too. I'm fine with either, but I prefer how https://github.com/prometheus/alertmanager/compare/master...jbarratt:opsgenie_endpoint_fix tests for the expected endpoint directly in the HTTP handler. Maybe adopt that?

**Comment by amorken** [comment]
Sure, can do. =)

**Comment by jbarratt** [comment]
I verified that this works for me. I think this can be closed.

**Comment by brian-brazil** [comment]
Great!
