### ISSUE TITLE
Make Slack notification's mrkdwn_in configurable

### ISSUE THREAD

**Issue by gustav-b** [prometheus/alertmanager#1220]
Slack's webhook API allows passing the `mrkdwn_in` attribute for specifying which fields that contain markdown. In Alertmanager's [current implementation](https://github.com/prometheus/alertmanager/blob/94bef6419f92107423c839855487c062a6eba5db/notify/impl.go#L664) this attribute value is hard-coded to `{"fallback", "pretext", "text"}`. This is somewhat limiting as Slack supports markdown rendering for more attributes than these – for example in `title` and `fields`.

I believe this attribute should be configurable via `SlackConfig` like the other ones (it can still default to the current value).

**Comment by kskewes** [comment]
This is the link to API docs: https://api.slack.com/docs/message-formatting#message_formatting

**Comment by asherf** [comment]
I gave this a try:
https://github.com/prometheus/alertmanager/pull/1967
