### ISSUE TITLE
if the alertmanager support the alerts to the https webhook endpoints

### ISSUE THREAD

**Issue by Silence2012** [prometheus/alertmanager#1226]
I am planing to send some kind of alert to an https webhook endpoints, How should I add the authentication token in the configuration file.

**Comment by simonpasquier** [comment]
This is being addressed by #1222.

**Comment by simonpasquier** [comment]
It is now available in the master branch and in [v0.15.0-rc.0](https://github.com/prometheus/alertmanager/releases/tag/v0.15.0-rc.0) if you want to test.
