### ISSUE TITLE
Prometheus not abl to send alert request to alert manager.

### ISSUE THREAD

**Issue by taragurung** [prometheus/alertmanager#1227]
Why exactly am I getting this. when visiting the api/v1/ links its working and giving the response. But why exactly do we get this error.
`
`prometheus_1     | level=error ts=2018-02-06T10:36:55.344497837Z caller=notifier.go:454 component=notifier alertmanager=http://X.X.X.X:9093/api/v1/alerts count=0 msg="Error sending alert" err="Post http://X.X.X.X:9093/api/v1/alerts: dial tcp X.X.X.X:9093: getsockopt: no route to host"``

**Alert rule is working fine and showing the instance is down when the instance are down.** 

What I am expecting next is sending the alert message to alertmanager which is not

**Comment by simonpasquier** [comment]
Your Prometheus instance can't connect to the AlertManager's address and it looks like an IP routing issue.
