### ISSUE TITLE
Query inhibitions from amtool

### ISSUE THREAD

**Issue by sevagh** [prometheus/alertmanager#1248]
**What did you do?**

I had some alerts not being routed. I used `amtool silence query` to find current silences, but via the web UI when I checked the `[ ] Inhbitions` box I was able to see that my query was inhibited.

It would be nice if there was `amtool inhibition query` to see current inhibition status. Is this possible, a planned feature, etc.?

* Alertmanager version:

	0.13.0

**Comment by stuartnelson3** [comment]
adding a `State` column to the extended output would be cool:

```
# ./amtool alert query 'alertname="HighErrorRate"' -o extended
Alertname               Starts At                Summary                        State
HighErrorRate           2018-05-03 14:51:19 UTC  server is serving many errors  Silenced
```

or a flag `--state=STATE`, so you could do

```
# ./amtool alert --state=inhibited
```

Nothing has been planned, but it would be a welcome addition.

**Comment by Kellel** [comment]
Usually when I want all the information from an alert I use the `json` output  and then use jq to find what I want. 

As far as the arguments for getting this information we have the following 
```
  -i, --inhibited               Show inhibited alerts
  -s, --silenced                Show silenced alerts
  -a, --active                  Show active alerts
  -u, --unprocessed             Show unprocessed alerts
```

As far as what they should be, I kinda agree that we should probably just be able to specify `--state='active'` or something.

That being said I regularly use unsee and it has a pretty cool syntax where you can say something like `@state=active alertname=HighErrorRate` where matchers with the `@` symbol are special and can match receivers and status. This would be quite a bit harder to implement, but it does feel pretty nice.

**Comment by simonpasquier** [comment]
Closing this issue since it's possible to filter alerts by state. I've opened https://github.com/prometheus/alertmanager/issues/2204 to add the ability to view the state of alerts with the CLI.
