### ISSUE TITLE
Add Alertmanager status "/metrics".

### ISSUE THREAD

**Issue by m4rcc** [prometheus/alertmanager#1249]
I just upgraded Alertmanager to latest version ( 0.14.0). I am using a MESH of 3 Alertmanagers which are receiving  alert data from 2xPrometheus. I saw in the newer version the "/metrics" endpoint has been implemented with lots of metrics available but i do not see the most important metric ( my opinion ) that is the Alertmanager status :   "alertmanager_up  1"  or "alertmanager_up  0" so that i can implement an alert in Alertmanager to monitor Alertmanager :) which should work fine when we have multiple Alertmanagers. 

Is there such a thing and i missed it? 
For the old version i was using "curl localhost:9095/api/v1/alerts" to check if my Alertmanager is still up or down.

**Comment by roidelapluie** [comment]
hello

The up metrics are available at the prometheus level, as meta metrics added to evey jobs.

Look for up{job="alertmanager"} == 0

**Comment by m4rcc** [comment]
hello,

Thank you for the fast reply, unfortunately i am having Prometheus 1.7.1 and i am using only the "-alertmanager.url" to link Prometheus to Alertmanagers. Prometheus update was next in line after Alertmanager, i will check that metric after i update Prometheus also. I am assuming that now there is a bidirectional flow between Prometheus and Alertmanagers.

**Comment by roidelapluie** [comment]
What you should do is adding alertmanager as a prometheus job. Then you get the up metric.
