### ISSUE TITLE
Please switch to fsnotify.v1 API

### ISSUE THREAD

**Issue by rhertzog** [prometheus/alertmanager#125]
Hello,

alertmanager still uses the fsnotify.v0 API which has been deprecated. It would be nice if it could be ported to fsnotify.v1.

See https://github.com/go-fsnotify/fsnotify for the status of both API and https://godoc.org/gopkg.in/fsnotify.v1 for the doc of the new API.

Thank you!

**Comment by juliusv** [comment]
@rhertzog Thanks for pointing this out! However, we'll likely not adjust this in the existing Alertmanager anymore, and the rewrite which is currently being planned will not have file listeners anymore (only reload by `SIGHUP`). So I'll close this issue in the expectation that the problem will go away by itself...
