### ISSUE TITLE
panic: no valid network interfaces

### ISSUE THREAD

**Issue by dup2** [prometheus/alertmanager#1250]
Switching from 0.12 to 0.14 does not work on systems that do not provide a hardware MAC address (i.e. OpenVZ hypervisor). 

This is related to #582 but seems to be a regression from changing to kingpin which evaluates the default value for --mesh.peer-id which enforces a hardware MAC and panics.

**This same behaviour is also observed when `--mesh.peer-id 21:71:25:12:67:32` is provided** and thus the argument has a value - the default is still evaluated and the application bails out.

Enforcing something in the default value evaluation is too early IMHO, the check should be done later when all arguments are evaluated and (when no mesh.peer-id is provided) the hardware MAC can not be read.

**What did you do?**

Run `alertmanager -h`

**What did you expect to see?**

A general help information

**What did you see instead? Under which circumstances?**

```
panic: no valid network interfaces

goroutine 1 [running]:
main.mustHardwareAddr(0x9a8ac0, 0xc420184ed0)
	/go/src/github.com/prometheus/alertmanager/cmd/alertmanager/main.go:575 +0x13d
github.com/prometheus/alertmanager/vendor/github.com/alecthomas/kingpin.(*Clause).String(...)
	/go/src/github.com/prometheus/alertmanager/cmd/alertmanager/main.go:123
main.main()
	/go/src/github.com/prometheus/alertmanager/cmd/alertmanager/main.go:123 +0x132b

```
**Environment**

* System information:

	Linux 2.6.32-26-pve x86_64  (proxmox, openvz container)

* Alertmanager version:

	Version 0.14.0 / linux-amd64

**Comment by stuartnelson3** [comment]
That code has been replaced in master -- there are no `--mesh.*` flags, they've been replaced by `--cluster.*` flags.

Looking at the code, it seems that the offending function isn't being executed anywhere (and should be deleted).

Fixed by #1232
