### ISSUE TITLE
Recreate silence loses matchers

### ISSUE THREAD

**Issue by zeisss** [prometheus/alertmanager#1252]
**What did you do?**

1. Create a silence with some dummy matchers
2. Wait for it to expire
3. Navigate to expired silence list
4. Click recreate

NOTE: The URL does not contain any parameters, it's just `http://localhost:9093/#/silences/new?filter=`

**What did you expect to see?**

A form prefilled with the matchers from the previous silence

**What did you see instead? Under which circumstances?**

An empty form with no matchers.

**Environment**

Raspberry PI, Alertmanager 0.14.0
Mac OS X, Current HEAD of Github

* System information:

```
$ uname -srm
Darwin 15.6.0 x86_64
```

* Alertmanager version:

0.14.0 as well as HEAD

* Alertmanager configuration file: Sample from README

---

The bug seems to be here: https://github.com/prometheus/alertmanager/blob/master/ui/app/src/Views/SilenceList/SilenceView.elm#L107
I tried fixing it myself, but my Elm is severly lacking :D

**Comment by stuartnelson3** [comment]
fixed by https://github.com/prometheus/alertmanager/pull/1270
