### ISSUE TITLE
Update HA docs

### ISSUE THREAD

**Issue by brancz** [prometheus/alertmanager#1275]
The [Alertmanager HA docs](https://github.com/prometheus/alertmanager#high-availability) are outdated due to the move from mesh to memberlist as flags have changed due to those changes. Beyond that it would probably be good if we add a section in the docs on HA on prometheus.io .

@stuartnelson3 @fabxc 

cc @starsdeep

**Comment by mxinden** [comment]
With #1277 merged and the link on Prometheus.io to the updated README this seems fixed to me.

@jamtur01 Thanks for your help!

@brancz Please reopen in case I am missing something.
