### ISSUE TITLE
merge broadcast errors with unexpected EOF

### ISSUE THREAD

**Issue by simonpasquier** [prometheus/alertmanager#1282]
**What did you do?**

Run a pair of AlertManager instances with roughly 100 firing alerts.

**What did you expect to see?**

No error.

**What did you see instead? Under which circumstances?**

Lots of errors in the log.

```
level=warn ts=2018-03-14T10:13:11.703192872Z caller=cluster.go:390 component=cluster msg="merge broadcast" err="unexpected EOF"
level=warn ts=2018-03-14T10:13:11.703246445Z caller=cluster.go:390 component=cluster msg="merge broadcast" err="unexpected EOF"
level=warn ts=2018-03-14T10:13:11.703287939Z caller=cluster.go:390 component=cluster msg="merge broadcast" err="unexpected EOF"
level=warn ts=2018-03-14T10:13:11.703339886Z caller=cluster.go:390 component=cluster msg="merge broadcast" err="unexpected EOF"
level=warn ts=2018-03-14T10:13:11.703393101Z caller=cluster.go:390 component=cluster msg="merge broadcast" err="unexpected EOF"
level=warn ts=2018-03-14T10:13:11.703470403Z caller=cluster.go:390 component=cluster msg="merge broadcast" err="unexpected EOF"
level=warn ts=2018-03-14T10:13:11.947824283Z caller=cluster.go:390 component=cluster msg="merge broadcast" err="unexpected EOF"
level=warn ts=2018-03-14T10:13:11.947908212Z caller=cluster.go:390 component=cluster msg="merge broadcast" err="unexpected EOF"
level=warn ts=2018-03-14T10:13:11.94795236Z caller=cluster.go:390 component=cluster msg="merge broadcast" err="unexpected EOF"
level=warn ts=2018-03-14T10:13:11.947979244Z caller=cluster.go:390 component=cluster msg="merge broadcast" err="unexpected EOF"
level=warn ts=2018-03-14T10:13:11.948006597Z caller=cluster.go:390 component=cluster msg="merge broadcast" err="unexpected EOF"
level=warn ts=2018-03-14T10:13:11.948049514Z caller=cluster.go:390 component=cluster msg="merge broadcast" err="unexpected EOF"
level=warn ts=2018-03-14T10:13:11.948083034Z caller=cluster.go:390 component=cluster msg="merge broadcast" err="unexpected EOF"
```

**Environment**

* System information:

Linux 4.15.7-300.fc27.x86_64 x86_64

* Alertmanager version:

alertmanager, version 0.15.0-rc.0 (branch: master, revision: d63c25a8559f0ea208e2aff78b32923b0b56975f)
  build user:       simon@simon-laptop
  build date:       20180314-09:39:30
  go version:       go1.10

* Prometheus version:

not relevant

* Alertmanager configuration file:

Will add later

* Prometheus configuration file:

Will add later

* Logs:

See above.

**Comment by simonpasquier** [comment]
I'm investigating the issue and managed to trigger the panic but I don't understand how to reproduce it yet. It seems to happen when lots of alerts are firing (I'm testing with 2000 alerts).

**Comment by simonpasquier** [comment]
My investigation discovered 2 problems:
1. gossip and push/pull intervals are swapped meaning that the peers ask for push/pull (eg full state) synchronization every 200ms while individual messages were gossiped every 1m. This is what #1284 fixes.
1. Update messages are not encoded the same way as full-state messages. This explains the `merge broadcast` errors on the receiver side. The result is that update messages aren't replicated across nodes. In quiet conditions, the first issue (full state being synchronized every 200ms) hides this problem but once you throw more alerts to AlertManager triggering many notifications, the full state sync takes more and more time. Also with #1284 applied, this second issue becomes obvious.

I'll send an updated PR today (hopefully).

**Comment by stuartnelson3** [comment]
Awesome, ping me when it's been updated
