### ISSUE TITLE
Enhance http_config.proxy_url to support HA with multiple proxies

### ISSUE THREAD

**Issue by jolson490** [prometheus/alertmanager#1294]
There's a new [http_config configuration option](https://github.com/prometheus/docs/blob/master/content/docs/alerting/configuration.md#http_config) which was introduced in [v0.15.0-rc.0](https://github.com/prometheus/alertmanager/releases/tag/v0.15.0-rc.0).

Would someone please consider somehow enhancing `http_config.proxy_url` to support the use case of running multiple/HA alertmanager pods/instances among two different AZs, where each AZ has its own proxy? 

Reference info:
 * https://github.com/prometheus/alertmanager/tree/v0.14.0#high-availability
 * https://github.com/coreos/prometheus-operator/blob/v0.17.0/Documentation/high-availability.md

To further explain my dilemma (if there's some other solution to my problem, please let me know)...

[kube-prometheus/manifests/alertmanager.yaml](https://github.com/coreos/prometheus-operator/blob/v0.17.0/contrib/kube-prometheus/manifests/alertmanager/alertmanager.yaml) specifies "replicas: 3".

Suppose I'm running kube-prometheus on an AWS cluster that has 2 agent/worker nodes (I'll call them "node 1" and "node 2") - e.g. one node in `us-east-1a` and the other in `us-east-1b`. 1 or 2 of the alertmanager pods will be started on node 1, and the other 1-2 alertmanager pod(s) on node 2.
In my situation, the proxy URL is different depending on which AZ a given node is in (I'll call it "proxy 1" for one of the AZs, and "proxy 2" for the other AZ).
The way `http_config` is currently implemented, I can only specify a single URL for the `proxy_url`. But I'd like to have a way to say "here's the proxy URL I want alertmanager to use for AZ a, and here's the other URL for b, and I'd like you (alertmanager) to handle it from here".

What I've currently resorted to is to:
 * To simply the next bullet: change (my own copy of) the aforementioned `alertmanager.yaml` snippet to "replicas: 1", thus disabling HA for alertmanager.
 * After running [kube-prometheus/self-hosted-deploy](https://github.com/coreos/prometheus-operator/blob/v0.17.0/contrib/kube-prometheus/hack/cluster-monitoring/self-hosted-deploy), I run some `kubectl get pod` and `aws ec2 describe-instances` commands to determine the AZ that the node is in that the single alertmanager pod got started on - and then I know which of my two proxy URLs to specify for `http_config.proxy_url`.
 * Though this isn't foolproof - I think I'll need to create a custom jenkins job (scheduled to run regularly) to check (for each of my given clusters) if K8s moved the alertmanager pod to the other node (in which case I then need to somehow tell alertmanager to start using the other proxy).

Any suggestions would be greatly appreciated. thanks!

**Alertmanager version:**

```
$ docker run --rm quay.io/prometheus/alertmanager:v0.15.0-rc.0 --version
alertmanager, version 0.15.0-rc.0 (branch: HEAD, revision: 68122e7005958df611baec01b316355a6f408bae)
  build user:       root@46262c45c129
  build date:       20180228-11:57:18
  go version:       go1.10
```

**Alertmanager configuration file:**

```
global:
  hipchat_auth_token: <sanitized>

  # (Note that hipchat_api_url has a default value of "https://api.hipchat.com/")

  # Note that the underlying impl of `proxy_url` seems to (do something at least equivalent to) setting/exporting the 'http_proxy' & 'https_proxy' environment variables, which is sufficient - alertmanager
  # doesn't also need 'no_proxy' set (the only things we need alertmanager to be able to reach the internet for is "https://api.hipchat.com/" and PagerDuty).
  http_config:
    proxy_url: <the URL of my proxy for either AZ a or b>

route:
  group_by: ['alertname', 'cluster']

  group_wait: 2s
  group_interval: 5m
  repeat_interval: 12h

  receiver: default-receiver

receivers:
- name: default-receiver
  hipchat_configs:
  - room_id: <sanitized>
    message_format: html
    notify: true
  pagerduty_configs:
  - service_key: <sanitized>
```

**Comment by brian-brazil** [comment]
That's not how HTTP proxies are generally used, it's expected that you'd at most have a single local proxy that could handle all requests.

**Comment by FUSAKLA** [comment]
Maybe I'm missing something out but you could create external name with the same name in both DC but at every dc it would poit to the DC specific proxy url and alertma ager would get just the name of the external name service?

**Comment by brian-brazil** [comment]
Yes, that would be a more normal approach.

**Comment by tomplus** [comment]
You can also create 2x statefulset with one replica, pinned to different zones and with zone-aware configuration. This approach will be less elastic than the operator, but should work.

IMO this feature is not related to the AlertManager, it's the prometheus-operator's responsibility.

**Comment by brian-brazil** [comment]
> IMO this feature is not related to the AlertManager, it's the prometheus-operator's responsibility.

That wouldn't help.

This is an odd network setup which is out of scope to support. If you need it I'd suggest implementing a proxy which can deal with this.
