### ISSUE TITLE
Populate regex checkbox when recreating silence

### ISSUE THREAD

**Issue by zemek** [prometheus/alertmanager#1299]
In 0.15.0.rc1

When recreating a silence that used regexes, the regex checkbox is always left unchecked. 

It would be nice to populate the regex box accordingly when recreating silences.

**Comment by stuartnelson3** [comment]
@w0rm did we support this previously?

**Comment by dhallam** [comment]
I experience the same issue. My expectation would be that all of the Matcher config, including the regex flag, would be copied into the recreated silence - otherwise it renders the entire Matcher useless.

**Comment by lachlancooper** [comment]
This was fixed in #1697.

**Comment by simonpasquier** [comment]
Thanks @lachlancooper!
