### ISSUE TITLE
tag release version in docker repo

### ISSUE THREAD

**Issue by a86c6f7964** [prometheus/alertmanager#130]
I think that it would be better to be able to specify a specific version that I want to run of alert manager rather than just using `docker run prom/alertmanager` something like `docker run prom/alertmanager:0.0.4` 

Nice to have would be having MAJOR and MINOR tags as well, so that I can commit to running something like 0.0.X or 0.X.X

**Comment by juliusv** [comment]
Definitely! We already do versioned tags for the Prometheus server now, but need to integrate that into the release process for all components at some point (bummer that the Docker hub doesn't seem to have an API for that, so always needs a manual tagging step).

I just created tags for 0.0.4 and 0.0.3 and triggered a build.

How would your suggestion about MAJOR and MINOR tags work exactly? Do you mean something like Dockerfile tag names `0.4.x` that we'd always update to the latest 0.4.x version and analogously for the major and patch versions?

**Comment by a86c6f7964** [comment]
Cool. I would recommend doing it exactly the same way that https://hub.docker.com/_/python/ and https://hub.docker.com/_/elasticsearch/ do it. Where you can see they have things like 1.7.2 and 1.7 and 1 where 1.7 gets updated to 1.7.3 if they release that and 1 gets updated to 1.8.1 if something like that gets released.

**Comment by juliusv** [comment]
Sounds like a good practice. I did that for Prometheus and Alertmanager for now. What troubles me is that this doesn't seem to be automatable via the Docker Hub API yet. That means manual work and potential for errors or forgetting it. Still, I will document this in the release instructions.

**Comment by fabxc** [comment]
This was done a while ago.
