### ISSUE TITLE
env http_proxy stopped working

### ISSUE THREAD

**Issue by tomplus** [prometheus/alertmanager#1300]
**What did you do?**

Upgrade Alertmanager from version to 0.12.0 to 0.15.0-rc.0.

**What did you expect to see?**

In my previous configuration I exported the environment variable (`http_proxy`) to send alerts. It doesn't work in latest version, there is a new option `global/http_config/proxy_url` which does the same job.

Can you confirm it ? For me it was the breaking change so it's worth to mention about in release notes,

Thanks

**Comment by brian-brazil** [comment]
You can now configure proxies from the configuration file. The environment was never part of our API.

**Comment by tomplus** [comment]
Sure, but a small notice costs nothing but can save somebody's time.

**Comment by tzz** [comment]
@brian-brazil related: does the `HTTPS_PROXY` have an analogue in the configuration file? As of now, setting `global/http_config/proxy_url` doesn't seem to set it correctly, for OpsGenie at least:

```
Apr 13 17:38:57 hostnamehere alertmanager[66535]: level=error ts=2018-04-13T21:38:57.337971224Z caller=dispatch.go:266 component=dispatcher msg="Notify for alerts failed" num_alerts=1 err="Post https://api.opsgenie.com/v2/alerts: proxyconnect tcp: tls: oversized record received with length 20527"
```

I can open a new issue if this is unexpected or broken behavior. Currently it makes OpsGenie unusable through a proxy for us.
