### ISSUE TITLE
JFYI: Outdated Dockerfile at docker hub

### ISSUE THREAD

**Issue by lexfrei** [prometheus/alertmanager#1303]
Hello!
You got outdated dockerfile at docker hub.
https://hub.docker.com/r/prom/alertmanager/~/dockerfile/
JFYI, feel free to close this issue.

**Comment by simonpasquier** [comment]
It is a dupe of https://github.com/docker/hub-feedback/issues/1847. Unfortunately we got no update from the project :disappointed:
