### ISSUE TITLE
Combine with k8s use alertmanager alarm but not receive mail

### ISSUE THREAD

**Issue by jiananjiang** [prometheus/alertmanager#1325]
I used the v0.7.1 version of alertmanager，and yaml file is as follows :

kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager
  namespace: monitoring
data:
  config.yml: |-
    global:
      resolve_timeout: 5m
      smtp_smarthost: 'smtp.163.com:25'
      smtp_from: '15966631019@163.com'
      smtp_auth_username: '15966631019@163.com'
      smtp_auth_password: '×××'
    templates:
    - '/etc/alertmanager-templates/*.tmpl' 
    route:
      group_by: ['alertname']
      group_wait: 30m
      group_interval: 5m
      repeat_interval: 15m
      receiver: email
    receivers:
    - name: 'email'
      email_configs:
      - to: '236243194@qq.com'   

and prometheus is linking to alertmanager,
![alert](https://user-images.githubusercontent.com/30279340/38790847-74ac5876-4176-11e8-889a-8f7f9980aa37.png)

And I see the docker logs of alertmanager ：

time="2018-04-16T01:10:53Z" level=info msg="running maintenance" component=silences source="silence.go:232" 
time="2018-04-16T01:10:53Z" level=info msg="running maintenance" component=nflog source="nflog.go:286" 
time="2018-04-16T01:10:53Z" level=info msg="maintenance done" component=silences duration=76.185碌s source="silence.go:249" 
time="2018-04-16T01:10:53Z" level=info msg="maintenance done" component=nflog duration=151.248碌s source="nflog.go:303" 
time="2018-04-16T01:12:01Z" level=error msg="Error on notify: dial tcp: lookup smtp.163.com on 10.254.0.2:53: read udp 172.30.57.7:21162->10.254.0.2:53: i/o timeout" source="notify.go:283" 
time="2018-04-16T01:12:01Z" level=error msg="Notify for 17 alerts failed: dial tcp: lookup smtp.163.com on 10.254.0.2:53: read udp 172.30.57.7:21162->10.254.0.2:53: i/o timeout" source="dispatch.go:261" 
time="2018-04-16T01:17:21Z" level=error msg="Error on notify: dial tcp: lookup smtp.163.com on 10.254.0.2:53: read udp 172.30.57.7:50296->10.254.0.2:53: i/o timeout" source="notify.go:283" 
time="2018-04-16T01:17:21Z" level=error msg="Notify for 17 alerts failed: dial tcp: lookup smtp.163.com on 10.254.0.2:53: read udp 172.30.57.7:50296->10.254.0.2:53: i/o timeout" source="dispatch.go:261" 
time="2018-04-16T01:22:41Z" level=error msg="Error on notify: dial tcp: lookup smtp.163.com on 10.254.0.2:53: read udp 172.30.57.7:20159->10.254.0.2:53: i/o timeout" source="notify.go:283" 
time="2018-04-16T01:22:41Z" level=error msg="Notify for 17 alerts failed: dial tcp: lookup smtp.163.com on 10.254.0.2:53: read udp 172.30.57.7:20159->10.254.0.2:53: i/o timeout" source="dispatch.go:261" 

can you tell me what should I do ?

**Comment by mxinden** [comment]
@jiananjiang are you able to resolve `163.com` inside the container?

What is the reason for using `v0.7.1` instead of `v0.14.0`?

**Comment by jiananjiang** [comment]
@mxinden thanks! I have solved this problem and replaced it with the latest version。
