### ISSUE TITLE
amtool doesn't depend on a stable version of kingpin

### ISSUE THREAD

**Issue by simonpasquier** [prometheus/alertmanager#1328]
`amtool` depends on a version of the kingpin package (commit [75c6058](https://github.com/alecthomas/kingpin/commit/75c60582c55399763d53eeb59078d63d3616f58c) to be precise) that isn't the [current stable](https://gopkg.in/alecthomas/kingpin.v2) version (v2).

It has at least 2 drawbacks:
* Package maintainers' life gets harder.
* There's no guarantee on the API stability outside of v1/v2 so updating the `kingpin` package might break the build (and in fact it does currently).

The (only?) reason for using the "unstable" version is that `amtool` already supported reading its configuration from YAML files before moving to kingpin but `v2` kingpin didn't offer this out-of-the-box (more details [here](https://github.com/prometheus/alertmanager/pull/976#discussion_r157977731)).

**Comment by TheTincho** [comment]
One more thing: this has broken the `--help-man` functionality to generate man pages automatically. This contradicts `cmd/amtool/README.md`
