### ISSUE TITLE
hipchat room_id as string or int32

### ISSUE THREAD

**Issue by triggity** [prometheus/alertmanager#133]
hipchat room_id's can be the integer number of the room or its string name. https://www.hipchat.com/docs/apiv2/method/send_message

currently, the configuration only allows for int32 room id's.
https://github.com/prometheus/alertmanager/blob/216d9dd46792f7a97ace168e1b1ba92c2509310e/config/config.proto#L48

any way we can change this?

**Comment by juliusv** [comment]
Since the HipChat API defines that as a string, I think it's fine to file a PR that changes that config field to string type and uses that instead of int32.

**Comment by 0x46616c6b** [comment]
With the new implementation it is an string. See the [new documentation](https://github.com/prometheus/docs/blob/amdoc/content/docs/alerting/configuration.md#hipchat-receiver-hipchat_config). Also new is the usage of the [Room Notification API](https://www.hipchat.com/docs/apiv2/method/send_room_notification) from Hipchat.

**Comment by triggity** [comment]
Thanks for the update!
