### ISSUE TITLE
Custom email template not working; sends out emtpy mail

### ISSUE THREAD

**Issue by krdineshbny** [prometheus/alertmanager#1332]
I am trying to create a new custom template and getting empty mails due to it.
I have cloned the default.tmpl file and modified it according to my need and named it as test.tmpl. Also, changed the email.default.html within it to my needs and named as emailtest.html

I have added below in my alertmanager configuration file
templates:
- "/etc/alertmanager/template/*.tmpl"
- "/etc/alertmanager/template/test.tmpl"

- name: "Testreceiver"
  email_configs:
  - to: "dinesh@test.com"
    require_tls: false
    headers:
      subject: "{{ .GroupLabels.alertname }} - {{ .GroupLabels.emailsubject }}"
    html: '{{ template "emailtest.html" . }}'

Alertmanager version: 0.15.0-rc.1

Error message states template file not found

level=error ts=2018-04-19T15:10:10.854708548Z caller=dispatch.go:266 component=dispatcher msg="Notify for alerts failed" num_alerts=1 err="cancelling notify retry for \"email\" due to unrecoverable error: parsing to addresses: mail: expected comma; cancelling notify retry for \"email\" due to unrecoverable error: executing email html template: html/template::1:12: no such template \"emailtest.html\""

Screenshot of test.tmpl is included.
![image](https://user-images.githubusercontent.com/38421692/39001162-48f6dd6a-4413-11e8-8849-37d100cfd894.png)

Kindly advise.

**Comment by stuartnelson3** [comment]
This is a usage question, and is better directed to the users mailing list prometheus-users@googlegroups.com
