### ISSUE TITLE
Specify OpsGenie responders

### ISSUE THREAD

**Issue by zemek** [prometheus/alertmanager#1342]
It looks like right now we can only set `teams:` in the OpsGenie config. The OpsGenie API says that the `responders` field supports "Teams, users, escalations and schedules" https://docs.opsgenie.com/docs/alert-api

It would be useful to be able to send alerts to a specific schedule within a team, rather than just team itself

**Comment by pasali** [comment]
+1 for this feature.

**Comment by simonpasquier** [comment]
Comparing the OpsGenie documentation and the AlertManager code, it seems that the OpsGenie API has changed a bit (again?).

The [documentation](https://docs.opsgenie.com/docs/alert-api#section-create-alert) states that the JSON object for creating an alert can contain a `responders` field (and the `teams` field is undocumented):

```json
{
    ...
    "responders":[
        {
            "name":"NOC",
            "type":"team"
        },
        {
            "username":"trinity@opsgenie.com",
            "type":"user"
        },
        {
            "name":"Nightwatch Escalation",
            "type":"escalation"
        },
        {
            "name":"First Responders Schedule",
            "type":"schedule"
        }
    ]
}
```

The AlertManager code uses the `teams` field though:

https://github.com/prometheus/alertmanager/blob/ec2cc57d28b66590b2429b03fdba068eae32b17a/notify/impl.go#L985-L995

@iksaif @Tom-Fawcett or anybody with OpsGenie access wanting to have a look?

**Comment by zemek** [comment]
we might submit a PR for this at the end of the month or so if no one has started working on this

**Comment by vitaliiko** [comment]
We need this feature as well

**Comment by bwplotka** [comment]
+1 happy to make a PR

**Comment by bwplotka** [comment]
unless @zemek you have something

**Comment by zemek** [comment]
@bwplotka been too busy so haven't actually done anything on this :( feel free to make a PR!
