### ISSUE TITLE
"mkdir data/: permission denied" while starting alert manager service in centos7

### ISSUE THREAD

**Issue by karthik101** [prometheus/alertmanager#1343]
Getting "mkdir data/: permission denied" for alertmanger while starting the service, but has normal start if called with binary:

$ /usr/local/bin/alertmanager --config.file="/etc/prometheus/alertmanager.yml"
level=info ts=2018-04-26T16:11:37.801802604Z caller=main.go:136 msg="Starting Alertmanager" version="(version=0.14.0, branch=HEAD, revision=30af4d051b37ce817ea7e35b56c57a0e2ec9dbb0)"
level=info ts=2018-04-26T16:11:37.801882941Z caller=main.go:137 build_context="(go=go1.9.2, user=root@37b6a49ebba9, date=20180213-08:16:42)"
level=info ts=2018-04-26T16:11:37.802950788Z caller=main.go:275 msg="Loading configuration file" file=/etc/prometheus/alertmanager.yml
level=info ts=2018-04-26T16:11:37.808208271Z caller=main.go:350 msg=Listening address=:9093

**Here's the error log:**

Apr 26 12:04:40 host-I12931 alertmanager[15761]: level=info ts=2018-04-26T16:04:40.100186828Z caller=main.go:136 msg="Starting Alertmanager" version="(version=0.14.0, branch=HEAD, revision=30af4d051b37ce817ea7e35b56c57a0e2ec9dbb0)"
Apr 26 12:04:40 host-I12931 alertmanager[15761]: level=info ts=2018-04-26T16:04:40.100314849Z caller=main.go:137 build_context="(go=go1.9.2, user=root@37b6a49ebba9, date=20180213-08:16:42)"
Apr 26 12:04:40 host-I12931 alertmanager[15761]: level=error ts=2018-04-26T16:04:40.100351694Z caller=main.go:141 msg="Unable to create data directory" err="mkdir data/: permission denied"
Apr 26 12:04:40 host-I12931 systemd[1]: alertmanager.service: main process exited, code=exited, status=1/FAILURE
Apr 26 12:04:40 host-I12931 systemd[1]: Unit alertmanager.service entered failed state.
Apr 26 12:04:40 host-I12931 systemd[1]: alertmanager.service failed.
Apr 26 12:04:40 host-I12931 systemd[1]: alertmanager.service holdoff time over, scheduling restart.
Apr 26 12:04:40 host-I12931 systemd[1]: start request repeated too quickly for alertmanager.service
-- Subject: Unit alertmanager.service has failed
-- Unit alertmanager.service has failed.
Apr 26 12:04:40 host-I12931 systemd[1]: Unit alertmanager.service entered failed state.
Apr 26 12:04:40 host-I12931 systemd[1]: alertmanager.service failed.

**Versions:**

alertmanager, version 0.14.0 
prometheus, version 2.2.1 

**systemd service file :**

[Unit]
Description=Prometheus Alert Manager service
After=network.target auditd.service

[Service]
Type=simple
User=prometheus
ExecStart=/usr/local/bin/alertmanager --config.file="/etc/prometheus/alertmanager.yml"
Restart=always

[Install]
WantedBy=default.target

**alertmanager.yml :** 

global:
    smtp_smarthost: 'email-smtp.us-west-2.amazonaws.com:587'
    smtp_from: 'Alertmanager <alertmanager@example.com>'
    smtp_auth_username: 'FILLMEIN'
    smtp_auth_password: 'FILLMEIN'

templates:
- '/etc/alertmanager/template/*.tmpl'

route:
  receiver: 'team-X-mails'

receivers:
- name: 'team-X-mails'
  email_configs:
  - to: 'alertme@example.com'

**Comment by simonpasquier** [comment]
This is a problem with your systemd unit service that doesn't set the working directory. You might want to look at https://www.freedesktop.org/software/systemd/man/systemd.exec.html#WorkingDirectory=

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
