### ISSUE TITLE
Investigate flaky WeChat test

### ISSUE THREAD

**Issue by stuartnelson3** [prometheus/alertmanager#1348]
```
--- FAIL: TestWechat (127.93s)
	Error Trace:	impl_test.go:312
	Error:		Should be false
```

Figure out why this test is intermittently failing on CI.

**Comment by simonpasquier** [comment]
Just tried to reproduce it on my local machine with additional trace and I got this:

```
--- FAIL: TestWechat (131.95s)
        impl_test.go:313: Get https://qyapi.weixin.qq.com/cgi-bin/gettoken?corpid=invalidCorpID&corpsecret=invalidSecret: dial tcp 203.205.128.203:443: connect: connection timed out
        Error Trace:    impl_test.go:315
        Error:          Should be false
```

So the unit test is hitting the public Wechat endpoint which isn't good at all. I would remove the unit test since no other receiver hits the real endpoints in the tests. WDYT?

**Comment by stuartnelson3** [comment]
urg we're making a request to a live service ..
