### ISSUE TITLE
Emails are not encoded properly

### ISSUE THREAD

**Issue by hasso** [prometheus/alertmanager#135]
If alert summary and/or description contains non-ascii symbols, it breaks emails.

* There is no content type headers in email and most of mail clients don't use UTF-8 by default - the message body is broken in most of mail clients.
* If non-ascii symbols will end up in email subject, it's even worse. All headers (including subject) need to be encoded properly and if they are not, various sanity checks in mail transport (including virus and spam scanners) could throw these mails away. For example Amavis complains here:

``BAD HEADER Non-encoded 8-bit data (char C3 hex) in message header 'Subject'``

**Comment by fabxc** [comment]
Thanks for the report. I considered that in the rewrite of Alertmanager.

**Comment by brian-brazil** [comment]
This will be correctly handled in the alertmanager templating for all headers.

**Comment by brian-brazil** [comment]
This is be handled correctly in the new alertmanager, which is currently in alpha.
