### ISSUE TITLE
Slack notification not sent - {{$labels.name}} returns <no value>

### ISSUE THREAD

**Issue by trompx** [prometheus/alertmanager#136]
Hello,

I run alertmanager 0.0.4 in a docker (version 1.8.1) container. I tried to setup slack notification but although alerts appear on the UI, nothing is sent.

I /bin/sh in the image, installed curl to test if I could send a notification and it works so no network problem.

Second problem, I have the following alert :
```
ALERT MysqlDown
IF my_condition
FOR 5s
  WITH {
    severity="page"
  }
  SUMMARY "{{$labels.name}} at {{$labels.instance}} is down"
  DESCRIPTION "{{$labels.name}} at {{$labels.instance}} has been down for more than 5 seconds."
```

but on the alertmanager I get :
```
<no value> at <no value> is down
```

Let me know if I can provide more info.

**Comment by juliusv** [comment]
@trompx Do you see the Alertmanager logging any errors about sending the Slack messages? The log output would be interesting.

As for your case of `<no value> at <no value> is down`, that means you are referring to labels (`name` and `instance`) which are not present in the result data of `my_expression`. You can try pasting `my_expression` into the expression browser - does it output those labels? Most likely you are not preserving them in some aggregation (use the `by` clause) if the original source data has them.

**Comment by trompx** [comment]
Hello @juliusv,

Thanks for taking the time to try to help!

It appeared that I had network problems, I was getting the error :
```
Oct 17 00:09:03 test docker/23449d5ae225[943]: time="2015-10-17T00:09:03Z" level=info msg="Recomputing notification outputs (active alerts have changed)" file=manager.go line=398
Oct 17 00:09:03 test docker/23449d5ae225[943]: time="2015-10-17T00:09:03Z" level=info msg="Sent 1 notifications" file=manager.go line=353
Oct 17 00:09:13 test docker/23449d5ae225[943]: time="2015-10-17T00:09:13Z" level=error msg="Error sending Slack notification: Post https://hooks.slack.com/services/xxx/xxx: net/http: request canceled while waiting for connection" file=notifier.go line=775
```
After deleting ```--iptables=false``` in my docker options, the notification was sending successfully, at least after I corrected a second problem, I had set a wrong channel name. The documentation was a bit misleading here http://prometheus.io/docs/alerting/alertmanager/. Maybe you could add a # like :
```
notification_config {
  name: "alertmanager_slack"
  slack_config {
    webhook_url: "webhookurl"
    channel: "#channelname" instead of "channelname"
  }
}
```

Concerning the <no value>, I was using a condition alert like :
```
IF absent(((time() - container_last_seen{name="container-name"}) < 5)) FOR 15s
```
thus was returning no data. I got rid of absent and switch < for > and the problem was solved.

**Comment by mysterytree** [comment]
Hi  I'm new in  prometheus 
some question in alertmanage .
I want to monitor a container if it is down  but don't know how to write the config.
can you show me the example

**Comment by mysterytree** [comment]
Tanks a lot

**Comment by mysterytree** [comment]
I got the same error and "thus was returning no data"  really help me thanks a lot
