### ISSUE TITLE
AM is using an unreleased version of the client library

### ISSUE THREAD

**Issue by NightTsarina** [prometheus/alertmanager#1373]
Hi,

As i continue to prepare a new package of AM for Debian, I have found another issue: it does not compile with the latest release of client_golang.

At this stage I don't know if I should package HEAD of client_golang, as I fear breaking other users of the library, or try to patch AM to use the older version. Does anybody know if the changes in the library are fully backwards-compatible?

In any case, it seems very counter-intuitive that the client lib has a release process, but its sister projects are ignoring it.

**Comment by brian-brazil** [comment]
Per https://github.com/prometheus/client_golang/issues/344 that library does not have a formal release process, and you should use master. It sounds like we should get the AM on the newer version.

@beorn7

**Comment by TheTincho** [comment]
Thanks @brian-brazil, I had missed that, and was misled by the existence of older releases.

I will see of updating the package for client_golang, hopefully I won t break the rest of the ecosystem :/

BTW, AM is already using a fairly recent commit, according to vendor.json.

**Comment by beorn7** [comment]
Yes, just pin to a recent commit for now. There are still many moving parts. In June, we should be ready with that 0.9 "release" which is planned to be something meaningful to pin to (including 0.9.x to get bugfixes), while the next iteration will be pretty breaking.

**Comment by roidelapluie** [comment]
This has been fixed: https://github.com/prometheus/alertmanager/blob/8e861c646bf67599a1704fc843c6a94d519ce312/go.mod#L24
