### ISSUE TITLE
Redirect to 404 page after creating silence

### ISSUE THREAD

**Issue by metalmatze** [prometheus/alertmanager#1377]
**What did you do?**
I clicked on an alert to silence it, filled out the form and clicked on creating the silence. After that the alert manager straight redirects to a 404 page. If I wait for a few seconds and reload I then can see the silence. 

**What did you expect to see?**
After creating the silence I expect to see the silence overview page.

**What did you see instead? Under which circumstances?**
Yellow 404 page. 

**Environment**

* System information:

	`Linux 4.4.111+ x86_64`

* Alertmanager version:

```
alertmanager, version 0.15.0-rc.2 (branch: release-0.15, revision: 206c0646bed5e9f8ddf4428d842abcba6f23619b)
  build user:       root@5285d01e408b
  build date:       20180507-20:11:51
  go version:       go1.10.1
```

* Logs:

Nothing in the Alertmanager logs outside of the normal maintenance logs.

**Comment by mxinden** [comment]
@metalmatze Whats the URL of the 404 page?

**Comment by metalmatze** [comment]
The UUID of the silence.

I think that @gouthamve and I just found the "problem". I'm running 3 alertmanagers behind nginx. So obviously this is happening because I create the silence in one and get redirect to the next where the state didn't gossip that quickly.

Sorry for the noise... :sweat_smile:

**Comment by phoerious** [comment]
Same issue here. I think this should definitely be fixed in the Alertmanager. All instances communicate with each other, so why are they unable to handle this case. If anything, they should at least redirect back to the main page and not show a 404 error.

**Comment by sahmad-d2x** [comment]
Context : https://github.com/prometheus/alertmanager/issues/1377
