### ISSUE TITLE
Cannot recieve Alertmanager emails 

### ISSUE THREAD

**Issue by unnisathyarajan** [prometheus/alertmanager#1390]
Hi, I am not receiving the email from alertmanager. Currently using alertmanager v 0.14.0 in docker container with AWS SES service to send out emails. There is no warnings/ debug info I could get from the docker logs by using the following command:

$docker logs -f alertmanager
level=info ts=2018-05-20T11:02:20.086925484Z caller=main.go:137 build_context="(go=go1.9.2, user=root@37b6a49ebba9, date=20180213-08:16:42)"
level=info ts=2018-05-20T11:02:20.087308387Z caller=main.go:275 msg="Loading configuration file" file=/etc/alertmanager/config.yml
level=info ts=2018-05-20T11:02:20.093055231Z caller=main.go:350 msg=Listening address=:9093
level=info ts=2018-05-20T11:17:20.087239069Z caller=nflog.go:293 component=nflog msg="Running maintenance"
level=info ts=2018-05-20T11:17:20.08737407Z caller=silence.go:269 component=silences msg="Running maintenance"

The SES service is tested via command line and I could receive emails.

The Slack configuration works, however, it is not sending out resolved notifications even though I had set the send_resolved to true.

Contents of config.yml:

global:
templates: 
- '/etc/alertmanager/template/*.tmpl'
route:
  group_by: ['name']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h 
  receiver: first-level-notifiers 
  routes:
receivers:
- name: 'first-level-notifiers'
  email_configs:
  - to: 'unnisathya88@gmail.com'
    send_resolved: true
    from: 'admin@prometheus.example.com'
    smarthost: 'email-smtp.eu-west-1.amazonaws.com:25'
    auth_username: 'ADDDDDDDDDDDDDDDDDDQ'
    auth_password: 'ADDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDq'
  slack_configs:
  - api_url: https://hooks.slack.com/services/AAAAAAAAAAAAAAAAAAA
    send_resolved: true
    channel: '#prometheus-alerts'

Please advice!!

Thanks in advance.

**Comment by kotaldav-revolgy** [comment]
Glad your shared your solution, if founded..
