### ISSUE TITLE
"Bad Matcher Format" when using a comma in a matcher value

### ISSUE THREAD

**Issue by iksaif** [prometheus/alertmanager#1393]
```
curl http://localhost/api/v1/alerts?silenced=false&inhibited=false&filter=tags%3D%22gum%2Clatency%22
{"status":"error","errorType":"bad_data","error":"bad matcher format"}
```

Note: trying to match `tags="gum,latency"` using the UI does the same thing.

I used 0.14 and 0.15.0-rc.1.

**Comment by simonpasquier** [comment]
Confirmed, the problem is in the `pkg/parse` code.

https://github.com/prometheus/alertmanager/blob/bf0db5b989695798ff5ebfaffd19f2f3110a73d6/pkg/parse/parse.go#L30-L37

**Comment by simonpasquier** [comment]
@iksaif i've submitted #1395
