### ISSUE TITLE
wechat newline error

### ISSUE THREAD

**Issue by steinliber** [prometheus/alertmanager#1397]
**What did you do?**
use prometheus wechat send alert newline can't take effert
this is what i get 

>  [FIRING:2] PodCpuAlmostArriveLimit (monitoring/k8s service critical)
Pod prometheus-k8s-1 cpu arrive 3.7096932174325294 of limit within the 10 minutes\nPod prometheus-k8s-0 cpu arrive 3.264032788148153 of limit within the 10 minutes\n 

the \n can't be encoded

**What did you expect to see?**
\n take effert

**Comment by stuartnelson3** [comment]
This is a usage question, and would be better addressed by the community at prometheus-users@googlegroups.com.
