### ISSUE TITLE
alertmanger doesn't send mail when alert.

### ISSUE THREAD

**Issue by djooee** [prometheus/alertmanager#1398]
This is my simple.yml in alertmanger:
global:
   resolve_timeout: 5m
  smtp_from: test@test.com
  smtp_smarthost: 'smtp.test.com:25'
  smtp_require_tls: true
  pagerduty_url: https://events.pagerduty.com/v2/enqueue
  hipchat_api_url: https://api.hipchat.com/
  opsgenie_api_url: https://api.opsgenie.com/
  wechat_api_url: https://qyapi.weixin.qq.com/cgi-bin/
  victorops_api_url: https://alert.victorops.com/integrations/generic/20131114/alert/

route:
  receiver: aaa
group_by: alertname
group_wait: 30s
group_interval: 5m
repeat_interval: 3h

receivers:
  name: aaa
  email_configs:
    send_resolved: false
    to: exemple@exemple.com
    from: test@test.com
    smarthost: smtp.test.com:25
    headers:
    From: test@test.com
    Subject: '{{ template "email.default.subject" . }}'
    To: exemple@exemple.com
    html: '{{ template "email.default.html" . }}'
    require_tls: true
    webhook_configs:
    send_resolved: true
    url: http://********
    templates: []

but alertmanger doesn't send mail when alert.
thanks

**Comment by stuartnelson3** [comment]
This does not follow the provided template, and gives no clues as to how we may help you.
