### ISSUE TITLE
Change routing_key config in VictorOps config to be a template string instead of string

### ISSUE THREAD

**Issue by pvdvreede** [prometheus/alertmanager#1404]
I note from the docs (https://prometheus.io/docs/alerting/configuration/#%3Cvictorops_config%3E) that the `routing_key` config is just a `string`. 

I was wondering if its possible to make this a `tmpl_string` so that people can change which key an alert is routed to by putting a label on the alert with that team's routing key. This would allow us to have teams self manage their notifications without my central team having to add new route configs for each team which is a lot of duplication where the only difference is the routing key.

Is this something that would be considered? If so I am happy to do a PR if someone could just point at the area of code I would need to change...

Many thanks.

**Comment by brian-brazil** [comment]
It is already templated, the docs are out of date. Would you like to send a PR to fix the docs? It's the 'docs' repo.

**Comment by pvdvreede** [comment]
Cool, thanks I have done the PR and will add the DCO sign off tomorrow.

**Comment by brian-brazil** [comment]
Great!
