### ISSUE TITLE
Expose Alert severity metric

### ISSUE THREAD

**Issue by VR6Pete** [prometheus/alertmanager#1413]
When building dashboards it would be useful if I could filter the severity from alert manager metrics. 

Critical = 10
Warning = 5 

Currently I do this using Prometheus datasource but unfortunately does not know what alerts are silenced therefore my dashboards are reporting inaccurate statistics. 

If the alert severity was exposed in the alert manager metrics then I can configure grafana to look at the pdometheus alert manager datasource as opposed to Prometheus. 

This feels like a bit of a gap / disconnect between Prometheus and alert manager. 

Thanks. 

Pete

**Comment by brancz** [comment]
Thanks for opening this issue! A problem I'm seeing about this is that the `severity` label, or in fact any label is just a convention, so it's difficult to expose metrics like this. I see the use for this though.

Maybe someone has an idea how to do this in a generic or completely different way to achieve the same result. Maybe @brian-brazil has a trick up his sleeve?

**Comment by brian-brazil** [comment]
This sort of thing doesn't belong on /metrics, as it's not about AM performance.

Even given that, doing it generically would be hard. It sounds in this case like the right solution is someone to write an AM data source for Grafana.

**Comment by brancz** [comment]
I recall @davkal was thinking of an Alertmanager datasource in Grafana, that seems like a reasonable solution to me.

**Comment by roidelapluie** [comment]
https://grafana.com/plugins/camptocamp-prometheus-alertmanager-datasource/installation

**Comment by brancz** [comment]
@roidelapluie neat, thanks! I had not known about this plugin.

**Comment by roidelapluie** [comment]
Yes and you have the annotations too

**Comment by VR6Pete** [comment]
Yes there is a data source for Alert Manager and I have tried using that but was not able to filter on severity :)

**Comment by brancz** [comment]
Well that just sounds like the plugin should be extended to support the full capability of the Alertmanager API :) (I have yet to try it out, so I don’t know what is and what’s not possible)

**Comment by VR6Pete** [comment]
Looks like the plugin has recently been updated to bring back severity labels, but cannot see that I can pull back the number of silenced alerts - I have raised an issue with the plugin author.

**Comment by roidelapluie** [comment]
But .. on the other hand we have ALERTS in prometheus. Which is not about prom performance. Why can't we expost ALERTS in here, with 3 metrics:

alerts_processed
alerts_unprocessed

**Comment by brian-brazil** [comment]
ALERTS is not on Prometheus's /metrics. I'm not sure what you're proposing.

**Comment by roidelapluie** [comment]
it that inserted directly in the prometheus DB? oh that is a surprise for me.

**Comment by simonpasquier** [comment]
@VR6Pete it seems that using the AlertManager datasource for Grafana fulfills your requirements and there's no reason to expose alert counters on arbitrary labels.
If so can you close the issue?

**Comment by VR6Pete** [comment]
Leave a comment
