### ISSUE TITLE
amtool: support adding alerts

### ISSUE THREAD

**Issue by stuartnelson3** [prometheus/alertmanager#1417]
It would be nice if `amtool` supported adding alerts.

The syntax is difficult though, as we need two lists of key-value pairs: the alert's labels, and its annotations.

An potential example, trying to be consistent with `amtool silence add`:

```
amtool alert add SomeAlertName node=bar severity=critical \
  --annotation=summary='this is the summary' \
  --annotation=runbook='http://runbook.biz'
```
The first argument, if not in the form `key=value`, is assumed to be the alert's name, with each following key-value pair making up the labels. Annotations are added by explicitly adding the `--annotation=` flag.

This is really verbose. I think it would be useful to add alerts via `amtool`, but am wondering if the community has ideas on how it should look.

Additionally, there should be support for resolving the alert. Maybe just `--resolve` flag to resolve immediately, or do we want to support setting an arbitrary time to resolve the alert? `--resolve=<date>`?

**Comment by matthiasr** [comment]
I think using flags for the annotation is fine.

For resolving (immediately), that's a separate action that I would expect under a separate command. ("Please `add --resolve` this" sounds weird).

When an alert is created, how long would it normally take to resolve by itself? How would you implement `--resolve=<date>`?

**Comment by stuartnelson3** [comment]
>When an alert is created, how long would it normally take to resolve by itself?

By default, when an alert is sent from prometheus -> alertmanager, it has an empty `EndsAt` field, which indicates that the alert will auto-resolve after `resolve_timeout`, which is set in the AM config. The auto-resolve is reset timer is reset each time the alert is re-sent by prometheus. Typically this is on the order of a few minutes, with prometheus resending the alerts based on its evaluation interval (typically a minute or less). Prometheus will only set `EndsAt` if the alert has stopped firing.

>How would you implement --resolve=<date>?

Setting the `EndsAt` field on the incoming alert takes care of that. If that field is empty on ingestion, it is set to `time.Now() + resolve_timeout`.

**Comment by brian-brazil** [comment]
> Prometheus will only set EndsAt if the alert has stopped firing.

This is something we should be changing, we should always send an EndsAt as only Prometheus knows the eval_interval.

**Comment by stuartnelson3** [comment]
>This is something we should be changing, we should always send an EndsAt as only Prometheus knows the eval_interval.

That sounds great, I had been wanting to set `resolve_timeout` for different receivers (because we have some servers with long evaluation intervals). Is this something that just needs someone to open a PR?

**Comment by matthiasr** [comment]
So amtool should also set EndsAt in any case? What would a reasonable time
be for a manually created alert?

FWIW, I like --ends-at=… more clear than --resolve=… because it's clear
that it expects an absolute time.

**Comment by brian-brazil** [comment]
For this particular tool given it's raw API access I'd not set an EndsAt unless the user specifically asks for one.

**Comment by bobmshannon** [comment]
Agreed that this would be useful. Is anyone actively working on this? If not, I can take it.
