### ISSUE TITLE
use go generate and not xxd

### ISSUE THREAD

**Issue by vtolstov** [prometheus/alertmanager#142]
I dont have xxd package on my distro, and as i see build requires go 1.5 , so may be force to use go generate to embed data ?

**Comment by fabxc** [comment]
Our conversation on the mailing list was regarding the new alpha version in the `dev` branch. For that one you only need the go tool.

Would be good to make sure whether you want to work on the current version or the new one.

Generally, you don't necessarily need `xxd` for the current one either if you do not want to modify the UI.

**Comment by vtolstov** [comment]
Thanks!

**Comment by vtolstov** [comment]
I'm try to modify my telegram notifier for dev branch
