### ISSUE TITLE
Alerts from webhook carrying confusing "status" for alerts

### ISSUE THREAD

**Issue by komal-SkyNET** [prometheus/alertmanager#1423]
**What did you do?**
Capturing alerts from webhook receiver. 

**What did you expect to see?**
Each alert and it's corresponding status(firing or resolved) in the JSON.

**What did you see instead? Under which circumstances?**
There is an alert status for the group in the JSON that says "firing" but there are alerts in the JSON in the list that actually have status of resolved. Observed JSON structure attached.

**Environment*/* System information:
Running in docker inside Kubernetes.

* Alertmanager version:
tag: v0.9.1

* Prometheus version:
tag: v1.8.1

* Logs:
Alert received on webhook:

{"receiver":"def-recv",
"status":"firing",
"alerts":[ {"status":"firing","labels":{"alertname":""}},{"status":"resolved","labels":{"alertname":""}}]
}

**Comment by komal-SkyNET** [comment]
Why is an overall status for the JSON needed when each alert is specifying it's status?

**Comment by komal-SkyNET** [comment]
Why is an overall status for the JSON needed when each alert is specifying it's status?

**Comment by mxinden** [comment]
@komal-SkyNET If a single alert in an alertgroup is firing, the entire group is firing. You can find the implementation of this logic [here](https://github.com/prometheus/alertmanager/blob/master/vendor/github.com/prometheus/common/model/alert.go#L77). This is by design, to quickly see the overall status of an alertgroup.

> Why is an overall status for the JSON needed when each alert is specifying it's status?

I guess you could see this as duplicate (not normalized)  information. I think it is simply to offload some work for the clients to calculate the overall group status.

For future questions directly related to Alertmanager, you can open up issues on github.com/prometheus/alertmanager right away. This way others with similar questions might be able to find answers quicker.

Let me know if this is of any help?

**Comment by komal-SkyNET** [comment]
Thanks! That makes sense since alerts in prometheus are driven by alert-groups. (by default grouped by: alertname). But then also, I guess it could be redundant if send_resolved flag is set to false; then every alert notification itself is essentially a "firing" event.

**Comment by vietthang207** [comment]
Hi all, I notice a discrepancy between the email receiver and webhook receiver. 
When prometheus send a group that contains several alerts of the same type, some are firing, some are resolved, the email show clearly which one is resolved, which one is firing. Meanwhile, in the json send to webhook, there's only one global status (which is firing as there are at least 1 firing alert).
@mxinden Why don't we add this status variable for each alerts? I think we can keeps the global group status if it is really needed to offload some work for the clients.

**Comment by mxinden** [comment]
> Why don't we add this status variable for each alerts?

@vietthang207 I am not quite sure I understand your question correctly. As you can see from the sample payload of a webhook below, we do add the status to each individual alert.

```json
{                                                                                                                            
    "receiver": "web\\.hook",                                                                                                                    
    "status": "firing",                                                                                                                          
    "alerts": [                                                                                                                                  
        {                                                                                                                                          
            "status": "firing",                                                                                                                      
            "labels": {                                                                                                                              
                "alertname": "DiskRunningFull",                                                                                                        
                "dev": "sda1",                                                                                                                         
                "instance": "example1"                                                                                                                 
            },                                                                                                                                       
            "annotations": {                                                                                                                         
                "info": "The disk sda1 is running full",                                                                                               
                "summary": "please check the instance example1"                                                                                        
            },                                                                                                                                       
            "startsAt": "2019-05-10T11:30:25.265992972+02:00",                                                                                       
            "endsAt": "0001-01-01T00:00:00Z",                                                                                                        
            "generatorURL": ""                                                                                                                       
        }
    ]
}
```

**Comment by vietthang207** [comment]
Sorry @mxinden, I just have time to upgrade prometheus to 2.11.1 and alert manager to 0.18.0. Here is the json received by my telegram bot:

```
{
  "alerts": [
    {
      "annotations": {
        "description": "Service \"apis.service\" of instance \"127.0.0.1:9099\" has been down for more than 5 minutes.",
        "displayUnit": "",
        "handlers": "@princeOfMacedon @princeOfMacedon ",
        "reported_by": "prometheus",
        "summary": "Service apis.service of instance 127.0.0.1:9099 down"
      },
      "endsAt": "0001-01-01T00:00:00Z",
      "generatorURL": "http://prometheus.local/graph?g0.expr=node_systemd_unit_state%7Bname%3D%22apis.service%22%2Cstate%3D%22active%22%7D+%3D%3D+0&g0.tab=1",
      "labels": {
        "alertname": "HardwareError_ServiceDown",
        "instance": "127.0.0.1:9099",
        "job": "prometheus",
        "name": "apis.service",
        "severity": "emergency",
        "state": "active"
      },
      "startsAt": "2019-07-26T06:54:59.752369975Z"
    }
  ],
  "commonAnnotations": {
    "description": "Service \"apis.service\" of instance \"127.0.0.1:9099\" has been down for more than 5 minutes.",
    "displayUnit": "",
    "handlers": "@princeOfMacedon @princeOfMacedon ",
    "reported_by": "prometheus",
    "summary": "Service apis.service of instance 127.0.0.1:9099 down"
  },
  "commonLabels": {
    "alertname": "HardwareError_ServiceDown",
    "instance": "127.0.0.1:9099",
    "job": "prometheus",
    "name": "apis.service",
    "severity": "emergency",
    "state": "active"
  },
  "externalURL": "http://prometheus.local",
  "groupKey": 0,
  "groupLabels": {
    "alertname": "HardwareError_ServiceDown",
    "instance": "127.0.0.1:9099",
    "name": "apis.service"
  },
  "receiver": "default_alert_telegram_receiver",
  "status": "firing",
  "version": 0
}
```

There is no status field for each alert. Is there something wrong with my config? Where can I find your sample payload?

**Comment by simonpasquier** [comment]
@vietthang207 IIUC telegram-bot is depending on an [old version](https://github.com/metalmatze/alertmanager-bot/blob/0.4.0/go.mod#L75) of AlertManager (v0.9.1 to be precise) so it doesn't  deserialize all the JSON fields.

Pinging @metalmatze too.
