### ISSUE TITLE
Alertmanager links are lost when using OAuth redirects

### ISSUE THREAD

**Issue by sjparkinson** [prometheus/alertmanager#1424]
**What did you do?**

Setup OAuth in a reverse proxy to secure Alertmanager.

**What did you expect to see?**

Alertmanager links would be preserved when redirected through the OAuth redirection-based flow.

**What did you see instead? Under which circumstances?**

The anchor element of Alertmanagers links are not visible to the reverse proxy and so are lost when redirecting through the OAuth flow.

**Environment**

* Alertmanager version: v0.14.0

**Comment by sjparkinson** [comment]
For example, if I visit a link, https://alertmanager/#/alerts?filter=%7Balertname%3D%22Target%20Unavailable%22%2C%20system%3D%22zabbix%22%7D, but I'm not logged into the OAuth provider, the reverse proxy cannot read the anchor from the request and so it's not included in the `redirect_uri` parameter of the OAuth request.

**Comment by brancz** [comment]
Are you sure this doesn't have anything to do with your oauth proxy? If you are using the bitly/oauth2_proxy then I can confidently say it's not a problem with the Alertmanager but with the proxy, as I have a pending pull request to fix this :slightly_smiling_face: (RE: https://github.com/bitly/oauth2_proxy/pull/483).

**Comment by sjparkinson** [comment]
Ah! That is exactly what we're trying out!

**Comment by sjparkinson** [comment]
I'll close this and watch that issue. Wonderful, thank you!
