### ISSUE TITLE
using pagerduty and event rule filters. resolve events lost due to lack of context/payload

### ISSUE THREAD

**Issue by stuart-warren** [prometheus/alertmanager#1440]
**What did you do?**
Tried to use alertmanager with pagerduty and their new event rule filters, filtering events on custom details and routing to a specific service.

**What did you expect to see?**
triggers and resolve events getting routed to a specific pagerduty service

**What did you see instead? Under which circumstances?**
triggers sent to service successfully, resolve events not picked up by event rule filter and lost

**Environment**

* Alertmanager version:

	0.14.0

I can see that you only add payload to the event when its a trigger event, this is lost for resolve event and therefore can't use to filter those events to the same service.

https://github.com/prometheus/alertmanager/blob/387e684faa6a79261490f10faf309093f9c3bed1/notify/impl.go#L489-L507

Any reason not to provide a merge request removing this if statement?

This documentation seems to suggest that parts of the payload are required when sent to the events v2 endpoint: 

https://v2.developer.pagerduty.com/v2/docs/send-an-event-events-api-v2

**Comment by stuart-warren** [comment]
cc: @mikebryant

**Comment by simonpasquier** [comment]
> Any reason not to provide a merge request removing this if statement?

Also cc @scarvel8 who committed the initial support for PagerDuty v2 API.

**Comment by mikebryant** [comment]
Testing with https://v2.developer.pagerduty.com/v2/docs/send-an-event-events-api-v2, sending a resolve event including all the payload fields seems to have the desired effect.

**Comment by scarvel8** [comment]
Looks good to me, I don't see any issue with removing the if statement and including the payload in other trigger types from reviewing the documentation

**Comment by stuart-warren** [comment]
We got notification that PagerDuty have made a change to how their API resolves events:

(PagerDuty Support)Aug 1, 05:58 PDT
Hi Mike, Thanks for your patience while we worked on this. Our engineering team has made an update that should now allow resolve events that are sent with only a dedup_key to resolve alerts through global event rules.

So it looks like this issue is no longer necessary

Looks like it was closed already :)
