### ISSUE TITLE
Sending alerts to OpsGenie fail with unexpected status code 422

### ISSUE THREAD

**Issue by ajardan** [prometheus/alertmanager#1443]
**What did you do?**

Configured OpsGenie receiver like this:

```
- name: OpsGenieOperations
  opsgenie_configs:
  - api_key: $OPSGENIE_API_KEY
    teams: Infrastructure
```
**What did you expect to see?**

Receive notifications in opsgenie

**What did you see instead? Under which circumstances?**

An error occurred:

```
level=error ts=2018-06-29T06:06:50.920889089Z caller=dispatch.go:279 component=dispatcher msg="Notify for alerts failed" num_alerts=1 err="cancelling notify retry for \"opsgenie\" due to unrecoverable error: unexpected status code 422"
```

**Environment**

* System information:

	insert output of `uname -srm` here

* Alertmanager version:

```
alertmanager, version 0.15.0 (branch: HEAD, revision: 462c969d85cf1a473587754d55e4a3c4a2abc63c)
  build user:       root@bec9939eb862
  build date:       20180622-11:58:41
  go version:       go1.10.3
```
* Prometheus version:

```
prometheus, version 2.3.1 (branch: HEAD, revision: 188ca45bd85ce843071e768d855722a9d9dabe03)
  build user:       root@82ef94f1b8f7
  build date:       20180619-15:56:22
  go version:       go1.10.3
```
* Alertmanager configuration file:
```
insert configuration here
```

* Prometheus configuration file:
```
insert configuration here (if relevant to the issue)
```

* Logs:
```
insert Prometheus and Alertmanager logs relevant to the issue here
```

**Comment by simonpasquier** [comment]
Can you start AlertManager with the `--log.level=debug` argument and share the full logs? Also I presume that you've replaced `$OPSGENIE_API_KEY` by your real API key value.

**Comment by ajardan** [comment]
@simonpasquier I also presumed, but in the end it looks like docker configs do not support templating in such an easy way. I specified the key directly, and it works fine, so I am closing. Sorry for the hassle !

**Comment by simonpasquier** [comment]
@ajardan no problem and thanks for closing the issue!

**Comment by mxinden** [comment]
> PS: Should the error reporting be improved, since it would be super easy to figure out what went wrong with a proper error?

@ajardan do I understand correctly that you had a misconfigured api key? In that case, did the [error handling](https://github.com/prometheus/alertmanager/blob/master/notify/impl.go#L1017-L1020) not give you any feedback?

In any case, contributions for better error feedback are always very welcome.

**Comment by mxinden** [comment]
> But since I am not a very good developer, I am not sure I can contribute much, at least not yet :/

I am more than happy to help. Let us know and thanks for the feedback.

**Comment by Zebradil** [comment]
Recently I bumped into a situation when templating error led to silently failing alert sending.
However, it was shown on debug log level. What about changing the log level of templating errors to make them somehow more visible? I'd say, it's a non-critical error or at least a warning.

**Comment by simonpasquier** [comment]
@Zebradil which version are you using? Any templating error should be logged at the error level.

**Comment by Zebradil** [comment]
@simonpasquier Thanks for the quick reply.
I'm using version `0.17.0`. I've checked this with the latest docker image (which contains version `0.19.0`) — all good, there are error messages in case of templating errors.
So, I just need to update my alertmanager.
