### ISSUE TITLE
gossip takes one pushPull interval to settle

### ISSUE THREAD

**Issue by iksaif** [prometheus/alertmanager#1457]
**What did you do?**

Started an alertmanager cluster.

**What did you expect to see?**

Silences synchronized after a few seconds.

**What did you see instead? Under which circumstances?**

Silences synchronized after >30s

**Details**

When a node joins the memberlist, it does a pushPull, but at this time alertmanager hasn't registered the nflog and silence listeners, so the initially received data is lost and will be received again only once another initiates a new pushPull (between 0s and 1m by default). This doesn't work well with the current settle code that expects the pushPull to happen during the join.

https://github.com/prometheus/alertmanager/pull/1456 fixes that.

**Comment by simonpasquier** [comment]
Closed by #1456
