### ISSUE TITLE
trying to add one more routes to different channel on slack

### ISSUE THREAD

**Issue by roiromanoclick** [prometheus/alertmanager#1459]
Hi,

Im trying to forward all sisense alerts to different channel on slack, and it is not working im still geting alerts to the main channel. what i miss? please assit me :)
this is my yml:

[yml.txt](https://github.com/prometheus/alertmanager/files/2166979/yml.txt)

**Comment by simonpasquier** [comment]
Thanks for your report. It looks as if this is actually a question about usage and not development.

To make your question, and all replies, easier to find, we suggest you move this over to our [user mailing list](https://groups.google.com/forum/#!forum/prometheus-users), which you can also search. If you prefer more interactive help, join or our [IRC channel](https://webchat.freenode.net/?randomnick=1&channels=prometheus), #prometheus on irc.freenode.net. Please be aware that our IRC channel has no logs, is not searchable, and that people might not answer quickly if they are busy or asleep. If in doubt, you should choose the mailing list.

**Comment by mxinden** [comment]
Closing here. @roiromanoclick let us know if we missed something.
