### ISSUE TITLE
Alertmanager fails to create slack posts, if channel name contains spaces

### ISSUE THREAD

**Issue by TimoL** [prometheus/alertmanager#1460]
**What did you do?**

Configured ``channel`` in ``slack_configs`` with name ``Team ABC``:

    receivers:
      - name: team-abc
        slack_configs:
          - api_url: <webhook to Mattermost>
            channel: 'Team ABC'

**What did you expect to see?**

message posted in Mattermost channel "Team ABC".

**What did you see instead? Under which circumstances?**

No message in Mattermost, instead errors in Alertmanager logs:

    level=error ts=2018-07-08T21:25:12.077586206Z caller=dispatch.go:279 component=dispatcher msg="Notify for alerts failed" num_alerts=1 err="cancelling notify retry for \"slack\" due to unrecoverable error: unexpected status code 404"

**Environment**

(using docker image ``prom/alertmanager:v0.15.0``, running in OpenShift)

* System information:

	  $ uname -srm
	  Linux 3.10.0-693.21.1.el7.x86_64 x86_64

* Alertmanager version:

	  $ alertmanager --version
	  alertmanager, version 0.15.0 (branch: HEAD, revision: 462c969d85cf1a473587754d55e4a3c4a2abc63c)
	    build user:       root@bec9939eb862
	    build date:       20180622-11:58:41
	    go version:       go1.10.3

**Comment by stuartnelson3** [comment]
Thanks for reporting this!

**Comment by ealexhaywood** [comment]
+1.  Confirmed this is the case.

As a workaround, you can replace whitespaces with hyphens `-`.

**Comment by TimoL** [comment]
thanks @ealexhaywood, using hyphen as workaround.

**Comment by simonpasquier** [comment]
Yep, there's a wider issue that almost none of the notifier URL parameters (except for webhook) are validated/escaped properly. That should be a global fix IMO.

**Comment by TimoL** [comment]
Thanks for fixing this so fast!
