### ISSUE TITLE
Custom parameters not working in slack_config like icon_url etc.

### ISSUE THREAD

**Issue by mprzygrodzki** [prometheus/alertmanager#1473]
Hello,
I would like to customize my alertmanager deployment, and so far everything works great, notifications are sent correctly via AlertManager to my slack channel, but i've found that there are some cool things which may be customized like image on the left side of the alert, username etc. I've added icon_url & username parameters but they seems to not working. Custom icon is not showing at all and also username doesn't change - here's output from my values, as this is templated by Helm chart.

Prometheus version 2.2.1
Alertmanager version 0.14

```
    - name: 'myname'
      slack_configs:
      - channel: '#alerts'
        username: 'Alerting System'
        icon_url: 'https://i.imgur.com/BeNCJG5.png'
        title: '[{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] Prometheus Event Notification'
        text: >-
            {{ range .Alerts }}
               *Alert:* {{ .Annotations.summary }} - `{{ .Labels.severity }}`
              *Description:* {{ .Annotations.description }}
              *Graph:* <{{ .GeneratorURL }}|:chart_with_upwards_trend:> *Runbook:* <{{ .Annotations.runbook }}|:spiral_note_pad:>
              *Details:*
              {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
              {{ end }}
            {{ end }}
        send_resolved: true
```

Any ideas how to solve or what i'm missing here ?

**Comment by simonpasquier** [comment]
Lets have the discussion on the mailing list first...

**Comment by mprzygrodzki** [comment]
@simonpasquier - you're correct - i've recreated webhook and now everyhting works as i've added my custom image for bot during creation - but so far i was convinced that this might be related to AM configuration - closing the topic.

**Comment by travisgroth** [comment]
Shouldn't this stay open?  It sounds like icon_url should be removed as an option.  It isn't functioning as expected and isn't likely to due to the behavior of the PD api.
