### ISSUE TITLE
AlertManager times out when waiting for cluster being settled

### ISSUE THREAD

**Issue by simonpasquier** [prometheus/alertmanager#1477]
Reported here: https://groups.google.com/d/msg/prometheus-users/F6kkVMJa35c/RYzjVwkvBQAJ

#1456 ([code](https://github.com/prometheus/alertmanager/pull/1456/files#diff-8384a3585ec4c1c107e75631ddadeab5R273)) introduced a regression in v0.15.1: `Settle()` always times out after 1 minute because the check interval itself is 10min. It means that AlertManager will always wait 1 minute before sending alerts.

**Comment by roidelapluie** [comment]
Indeed the  gossip does not settle at boot (according to logs) even if the nodes are perfectly capable of talking to each other.
