### ISSUE TITLE
Replace go-bindata

### ISSUE THREAD

**Issue by simonpasquier** [prometheus/alertmanager#1487]
See https://github.com/prometheus/prometheus/issues/2411#issuecomment-404445255 and https://github.com/prometheus/prometheus/pull/4430

TL;DR `go-bindata` isn't maintained anymore and needs to be replaced by an equivalent project in better shape.

**Comment by stuartnelson3** [comment]
Looks good.

I would prefer to not commit the `go generate`'d files, but I don't have a super strong opinion on this.

**Comment by roidelapluie** [comment]
As we commit the vendor, I think it is better to commit the generated files. It ensures that everyone who clones the repo can build the same alertmanager.
