### ISSUE TITLE
How to display/print metric values in html template

### ISSUE THREAD

**Issue by b82** [prometheus/alertmanager#1488]
Hi,

I'm trying to find a way to display/print **metric** values in **html email template** (using golang template of course), but I can't figure out how to do this. Is it possible to do this or I need to create a separated file for custom functions?

I've already tried to print out the metric inside the html template with:
_{{ printf node_memory_MemTotal_bytes }}_, and the same inside the file .yml in alertmanager's rules in annotations part but without result.

Any suggestions is very appreciated, 
thanks

**Comment by tnTano** [comment]
+1, i'm searching for the same things...

**Comment by stuartnelson3** [comment]
This is a usage question, and should be asked on the mailing list prometheus-users@googlegroups.com, where multiple people could benefit.

The template reference documentation is available on the prometheus website: https://prometheus.io/docs/alerting/notifications/

**Comment by simonpasquier** [comment]
This has been answered here: https://groups.google.com/d/msg/prometheus-users/fLURp1-tZqY/vIBq11M-CAAJ
