### ISSUE TITLE
make fails due to unformatted code

### ISSUE THREAD

**Issue by discordianfish** [prometheus/alertmanager#1504]
Master as of now:

```
$ make
>> checking code style
! gofmt -d $(find . -path ./vendor -prune -o -name '*.go' -print) | grep '^'
diff -u ./ui/bindata.go.orig ./ui/bindata.go
--- ./ui/bindata.go.orig	2018-08-06 13:36:19.809656858 +0200
+++ ./ui/bindata.go	2018-08-06 13:36:19.809656858 +0200
@@ -392,9 +392,9 @@
 
 // _bindata is a table, holding each asset generator, mapped to its name.
 var _bindata = map[string]func() (*asset, error){
-	"ui/app/script.js":                                                  uiAppScriptJs,
-	"ui/app/index.html":                                                 uiAppIndexHtml,
-	"ui/app/favicon.ico":                                                uiAppFaviconIco,
+	"ui/app/script.js":   uiAppScriptJs,
+	"ui/app/index.html":  uiAppIndexHtml,
+	"ui/app/favicon.ico": uiAppFaviconIco,
 	"ui/app/lib/bootstrap-4.0.0-alpha.6-dist/css/bootstrap.min.css":     uiAppLibBootstrap400Alpha6DistCssBootstrapMinCss,
 	"ui/app/lib/bootstrap-4.0.0-alpha.6-dist/css/bootstrap.min.css.map": uiAppLibBootstrap400Alpha6DistCssBootstrapMinCssMap,
 	"ui/app/lib/font-awesome-4.7.0/css/font-awesome.css":                uiAppLibFontAwesome470CssFontAwesomeCss,
Makefile.common:45: recipe for target 'style' failed
make: *** [style] Error 1
```

This isn't uncovered by CI since CI isn't running `make`. Is there a reason it doesn't?

**Comment by simonpasquier** [comment]
Which Go version? It doesn't fail for me with go1.10.3. The check is executed by TravisCI (but not Circle CI):
https://travis-ci.org/prometheus/alertmanager/builds/412627785#L579

**Comment by juliusv** [comment]
The latest Go version has a different `gofmt` output, and they say in their docs that they don't recommend putting `gofmt` into CI tests because the exact formatting can change over time.

I'm not sure what to do because we also want to ensure that someone formatted their Go code at all. Maybe we should enforce using the `gofmt` from the latest Go release? That would also ensure that files don't flip-flop back and forth between people with different Go versions.

**Comment by simonpasquier** [comment]
I think the current situation is mostly ok. We build AlertManager/Prometheus/... with the latest stable Go version (unless it introduces a regression, eg node_exporter). Whenever Go 1.11 is released, someone will update the CI pipelines accordingly and run `gofmt` as part of the PR (and if it's forgotten, Travis CI will catch it).
Am I missing something?

**Comment by juliusv** [comment]
@simonpasquier That sounds ok to me, the missing bit would be clarifying better to people that a specific Go version's `gofmt` is needed. In the CI error output, and/or beforehand elsewhere.
