### ISSUE TITLE
Add error counter for failing notifications

### ISSUE THREAD

**Issue by discordianfish** [prometheus/alertmanager#1505]
**What did you do?**
Create a notifier config with syntax errors.

**What did you expect to see?**
An error counter gettting increased.

**What did you see instead? Under which circumstances?**
The notifier fails without a way to monitor it's health.

**Environment**

* Alertmanager version:

	current master build

* Logs:
```
level=error ts=2018-08-06T12:47:06.1542157Z caller=notify.go:332 component=dispatcher msg="Error on notify" err="cancelling notify retry for \"slack\" due to unrecoverable error: template: :1:4: executing \"\" at <reReplaceAll>: wrong number of args for reReplaceAll: want 3 got 6"
```

**Comment by stuartnelson3** [comment]
This should be available via `alertmanager_notifications_failed_total`. Is it not present/not working?

**Comment by discordianfish** [comment]
Hrmm I must have missed that. Not sure it gets incremented when the template rendering fails though? But possible I just missed this completley. Going to close this for now and re-open if there is actually an issue.
