### ISSUE TITLE
Remove alert_groups from alertmanager

### ISSUE THREAD

**Issue by stuartnelson3** [prometheus/alertmanager#1508]
I remember it being mentioned that we don't want to use this anymore, and as far as I can tell it is exposed via api but the neither the UI or the amtool use it. I also didn't see it mentioned in the proposal of the v2 api.

Is this something we can remove?

removal would be the opposite of http://petstore.swagger.io/?url=https://raw.githubusercontent.com/mxinden/alertmanager/apiv2/api/v2/openapi.yaml

@simonpasquier @mxinden

**Comment by simonpasquier** [comment]
I thought about it but should probably check with @TheTincho

**Comment by mxinden** [comment]
Are you talking about the [`alerts/groups`](https://github.com/prometheus/alertmanager/blob/master/api/api.go#L245) function?

As far as I remember this was used in the old Angular UI, but was not needed anymore with the ELM rewrite. I have not included it in the API v2 Proposal for that reason.

Whats the reasoning for removing it now? I would suggest removing it along with the entire API v2, once v2 is merged and a two of minor releases passed.

> I thought about it but should probably check with @TheTincho

As far as I know Debian simply removes the UI, thereby it is also not dependant on this endpoint, right?

**Comment by simonpasquier** [comment]
>>    I thought about it but should probably check with @TheTincho 

> As far as I know Debian simply removes the UI, thereby it is also not dependant on this endpoint, right?

I seem to recall that there was a tentative effort to retrofit the old UI in Debian (and thus depend on `/api/v1/alerts/groups`) but I might be wrong. 

Assuming there's no opposition, I would be in favor of removing `alerts/groups` now.

**Comment by TheTincho** [comment]
Hey all, sorry for the late reply.

Like Stuart says, currently Debian ships no UI.

I wanted to retrofit the old UI, but I had understood that the API had changed so much it was not possible anymore, so I did not try in the end. I think it does not make sense to keep this, if we manage to finally prepare an UI, this will be just another thing to fix.

Thanks for checking!
