### ISSUE TITLE
Notifier for HipChat broken in Alertmanager 0.15.1 

### ISSUE THREAD

**Issue by andrekully** [prometheus/alertmanager#1515]
**What did you do?**
running AM v0.15.1 to test 

**What did you expect to see?**
The request URL towards HipChat server (on premise) as in 0.15.0:
POST /v2/room/0000/notification?auth_token=xxxxxxxxxXXXXXXXXXXxxxxxxxxxXXXXXXXXXXXX HTTP/1.1

**What did you see instead? Under which circumstances?**
Request in 0.15.1:
POST /v2/room/0000/notification%3Fauth_token=xxxxxxxxxXXXXXXXXXXxxxxxxxxxXXXXXXXXXXXX HTTP/1.1
-->> which results in a HTTP 404 response code from HipChat server

it seems that this behaviour is caused by changing the url typed as string to url.URL

changing as follows in _notify/impl.go_ did fix the issue 
```
-       apiURL.Path += fmt.Sprintf("v2/room/%s/notification?auth_token=%s", roomid, n.conf.AuthToken)
+       apiURL.Path += fmt.Sprintf("v2/room/%s/notification", roomid)
+       q := apiURL.Query()
+       q.Set("auth_token", fmt.Sprintf("%s", n.conf.AuthToken))
+       apiURL.RawQuery = q.Encode()

```

**Comment by stuartnelson3** [comment]
@simonpasquier Looks like the `?` introducing the query string is being escaped as part of the Path

**Comment by mxinden** [comment]
Thanks a lot @andrekully for the detailed bug report!

The new release contains the fix: https://github.com/prometheus/alertmanager/releases/tag/v0.15.2

**Comment by wenfei3** [comment]
补充一下截图：这是我的阿里云的监控，部署jumpserver是在8月中旬，可以很明显看到从21号开始，CPU的使用率飙升，然后一直没有降下来，从21号开始，每天都会出现几次jumpserver卡死的情况。
![image](https://user-images.githubusercontent.com/25998180/44504955-53da6f00-a6d1-11e8-91a8-2937f6b8b19b.png)
不知道是什么原因导致CPU使用率突然飙升？如果有需要，我可以提供更多的日志或者截图。

下面是coco的进程
```
ps -ef|grep 21701
root     21701     1 29 8月14 ?       2-14:18:28 python3 ./cocod start -d
```

```
sudo strace -c -p 21701
strace: Process 21701 attached
strace: [ Process PID=21701 runs in x32 mode. ]
strace: [ Process PID=21701 runs in 64 bit mode. ]
^Cstrace: Process 21701 detached
% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ----------------
 78.25    4.490581           3   1720817           epoll_wait
 13.58    0.779465           4    207910           epoll_ctl
  6.34    0.363850           3    103970    103938 recvfrom
  1.40    0.080129          10      8177        17 readlink
  0.20    0.011698          23       517           read
  0.07    0.004067         107        38           getdents
  0.03    0.001665           6       289           lseek
  0.03    0.001658          10       170           open
  0.03    0.001458           7       206           close
  0.02    0.001140           5       221           fstat
  0.01    0.000827          24        34        17 connect
  0.01    0.000821           5       170       153 ioctl
  0.01    0.000737           9        85        34 stat
  0.01    0.000572          15        39           sendto
  0.00    0.000144           8        19           openat
  0.00    0.000086           5        17           getsockopt
  0.00    0.000072           4        17           socket
  0.00    0.000039           2        17           setsockopt
------ ----------- ----------- --------- --------- ----------------
100.00    5.739009               2042713    104159 total
```
不太清楚epoll_wait和epoll_ctl是用来做什么的，有人了解吗？
