### ISSUE TITLE
How to separate the style of alert message of resovled message?

### ISSUE THREAD

**Issue by tangxuye** [prometheus/alertmanager#1523]
**What did you do?**
I have written  a .tmpl file and configured it in the alertmanager config file. 

**What did you expect to see?**
 Show me the alert message and the resoveld message  with the .tmpl file style by wechat when the monitoring target exception was occurred or recovered.

**What did you see instead? Under which circumstances?**
Both alarm and restore alerts use the same file style. I mean the message style is whitout some string words such as "Firing" or "Resovled". It doesn't look like very intuitive.

**Environment**
Prometheus Server
Alertmanager
Sql Exporter
Wechat

* System information:

	Linux 3.10.0-514.26.2.el7.x86_64 x86_64

* Alertmanager version:

   0.15.1 

* Prometheus version:

   2.3.2

* Alertmanager configuration file:
1.alertmanage.yml
2.demo.tmpl
insert configuration here
alertmanage.yml:
global:
  resolve_timeout: 5m

templates:
  - 'demo.tmpl'

route:
  group_by: ['alertname']
  group_wait: 15s
  group_interval: 20s
  repeat_interval: 4h
  receiver: 'wechat'
  routes:
  - receiver: 'wechat'
    group_by: [team]
    group_wait: 15s
    group_interval: 1m
    repeat_interval: 3h
    continue: false
    match:
      team: handdeduct
  - receiver: 'wechat'
    group_by: [team]
    group_wait: 15s
    group_interval: 1m
    repeat_interval: 3h
    continue: false
    match:
      team: autodeduct
  - receiver: 'wechat'
    group_by: [team]
 group_wait: 15s
    group_interval: 1m
    repeat_interval: 3h
    continue: false
    match:
      team: proactive
  - receiver: 'wechat'
    group_by: [team]
    group_wait: 15s
    group_interval: 1m
    repeat_interval: 3h
    continue: false
    match:
      team: autopay

receivers:
- name: 'wechat'
  wechat_configs:
  - corp_id: '12345'
    to_user: '@all'
    agent_id: '007'
    api_secret: 'abcd12345'
    send_resolved: true

demo.tmpl:

{{ define "wechat.default.message" }}
{{ range .Alerts }}
告警级别：{{ .Labels.severity }}
告警类型：{{ .Labels.alertname }}
故障主机: {{ .Labels.instance }}
告警主题: {{ .Annotations.summary }}
告警详情: {{ .Annotations.description }}
触发时间: {{ .StartsAt.Format "2006-01-02 15:04:05" }}
{{ end }}
{{ end }}

Quzi:How to configure the alertmanager.yml file to separate the style of alert message and resovled message? Is there any methods about the config file?

**Comment by jianguangshao** [comment]
最后这个你怎么解决的？
