### ISSUE TITLE
Upgrade frontend to elm 0.19

### ISSUE THREAD

**Issue by stuartnelson3** [prometheus/alertmanager#1524]
A new version of elm was just released:

https://github.com/elm/compiler/blob/master/upgrade-docs/0.19.md

**Comment by w0rm** [comment]
@stuartnelson3 shall we pair on this? Otherwise I can do this myself, should be pretty straightforward.

**Comment by stuartnelson3** [comment]
I'm off in the USA until mid september. I would love to pair on it, but it would have to be remote (or wait for me to be back in Berlin).

**Comment by w0rm** [comment]
Oh, and I'm off in Japan starting mid September. Let's find an overlapping slot to do this remotely, I'll contact with my availability.
