### ISSUE TITLE
how to config routes  repeat_interval 

### ISSUE THREAD

**Issue by YUNZHONGTAN** [prometheus/alertmanager#1534]
I want config routes repeat_interval, like this:

route:
     group_by: ['alertname', 'instance']
     group_wait: 30s
     group_interval: 1m
     repeat_interval: 10m 
     receiver: 'web.hook'
    
     routes:
         - match:
                severity: info
           repeat_interval: 5m          **#  i want config a repeat_interval for severity: info.  how config ?**   
           receiver: "test@email.com"

**Comment by mxinden** [comment]
@YUNZHONGTAN please gives us more details. You can find some guidance in our issue template: https://github.com/prometheus/alertmanager/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by YUNZHONGTAN** [comment]
hi:
    excuse me, my english is not good. I am configing the alertmanager config.
I want to configure different repeat alarm cycles when match different labels.

**Comment by YUNZHONGTAN** [comment]
hi：
    thanks, i had resolved it
