### ISSUE TITLE
How did you draw this image? I wanna know drawing tool.

### ISSUE THREAD

**Issue by davidmgkang** [prometheus/alertmanager#1535]
![2018-08-29 8 00 47](https://user-images.githubusercontent.com/16799504/44783736-412ad300-abc6-11e8-95ec-4b6ed83a1872.png)

**Comment by simonpasquier** [comment]
It seems that it was draw.io (see https://github.com/prometheus/alertmanager/pull/1394).

I'm closing it for now. If you have further questions, please use our [user mailing list](https://groups.google.com/forum/#!forum/prometheus-users), which you can also search.
