### ISSUE TITLE
unable to create silences with custom label matchers

### ISSUE THREAD

**Issue by TimSimmons** [prometheus/alertmanager#1545]
**What did you do?**

Attempted to create a silence with a custom label match using the :heavy_plus_sign: button on http://localhost:9093/#/silences/new (or using the :wastebasket: button on a pre-filled silence).

**What did you expect to see?**

The label match appear (or disappear).

**What did you see instead? Under which circumstances?**

I was redirected (but not an HTTP redirect, as far as I can discern from Chrome devtools) to `http://localhost:9093`, probably the `/` root of the tree. Making it so that I can not make my silence.

I recompiled before https://github.com/prometheus/alertmanager/commit/e768371a3917bf0f5dbe8dd326cf3f35a6bc26b0
landed and did not have any issues.

**Environment**

* System information:

	`Linux 4.15.0-29-generic x86_64`

* Alertmanager version:

I compiled with `make build` on go1.11 outside of my `$GOPATH` (using Go modules) on revision 460b7a72fcb03f990eb5a7df7b2ea1fba7572dec (master as of Sept 11)
```
$ ./alertmanager --version
alertmanager, version  (branch: , revision: )
  build user:       
  build date:       
  go version:       go1.11
```

**Comment by stuartnelson3** [comment]
I can confirm this behavior on latest HEAD

**Comment by mxinden** [comment]
@TimSimmons thanks for reporting!
