### ISSUE TITLE
Basic Authentication for Alertmanager

### ISSUE THREAD

**Issue by navyabairi** [prometheus/alertmanager#1549]
Hello,

I've deployed prometheus, Alertmanager on a GKE cluster. As Prometheus doesn't provide any authentication support, and as per the docs, I tried to use a reverse proxy, I configured it, but it isn't working as expected.
Is there any update coming up for the prometheus or Alertmanager that provides the authentication for the users?

**Comment by metalmatze** [comment]
As far as I know there are no plans to add authentication to Alertmanager.

**Comment by simonpasquier** [comment]
Please see https://prometheus.io/docs/guides/basic-auth/ which explains how to setup a reverse proxy in front of Prometheus for basic authentication. The same instructions should work for AlertManager too. If not feel free to reopen the issue.
