### ISSUE TITLE
Add InsecureSkipVerify option to SMTP config

### ISSUE THREAD

**Issue by dkalashnik** [prometheus/alertmanager#1554]
For now Alertmanagers' config is a lack of that option and that leads to requirement to create some smtp relay or disable TLS with self-signed cert.

**Comment by simonpasquier** [comment]
Hi Dima! IIUC this should be fixed by https://github.com/prometheus/alertmanager/pull/1528. Can you confirm?

**Comment by dkalashnik** [comment]
Hi Simon, yes, that should work, thanks, will wait for the next release =)

**Comment by candlerb** [comment]
I think it would still be useful to have a global `smtp_tls_config`.  Otherwise you need to set tls_config under every receiver's email_configs section.
