### ISSUE TITLE
Throw error when no auth mechanism is matched

### ISSUE THREAD

**Issue by danielkucera** [prometheus/alertmanager#1555]
https://github.com/prometheus/alertmanager/blob/d5b8e1028695866d52abd36fcf1973b1fdc9c807/notify/impl.go#L254

In case we are asked to auth and no auth mechanism matched and returned from function, we should return error saying something like: "No mechanism matched server offer: 250-AUTH NTLM"

**Comment by mxinden** [comment]
Great catch @danielkucera. Would you like to propose a PR for that?

**Comment by danielkucera** [comment]
I have no env to test this so I would propose someone else to develop this...
