### ISSUE TITLE
[slack] message attachment actions implementation incomplete

### ISSUE THREAD

**Issue by auhlig** [prometheus/alertmanager#1556]
**What did you do?**

Tried to attach action buttons to slack message as per https://api.slack.com/docs/message-buttons.
Slack considers the following attachments[].actions configuration valid, however the alertmanager doesn't:
```
{
...
"attachments": [
  ...
  "actions": [
    {
      "name": "<name>",
      "text": "<text>",
      "type": "<type>",
      "value": "<value"
    }
    ...
  ]
]
}
```

The current implementation of the [SlackAction](https://github.com/prometheus/alertmanager/blob/master/config/notifiers.go#L236-L241) allows only buttons with links.
I propose to extend this with the `name`, `value` attributes and make configuring these too as well as the `url` parameter optional as both configuration are valid actions as per above cited slack documentation.

**What did you expect to see?**

Buttons attached to slack message

**What did you see instead? Under which circumstances?**

Alertmanager refused to load configuration as the [SlackAction.URL parameter] (https://github.com/prometheus/alertmanager/blob/master/config/notifiers.go#L239) is missing: `FAILED: missing value in Slack url configuration`

**Environment**
* Alertmanager version: v0.15.2

**Comment by simonpasquier** [comment]
Looks like (once again) the Slack API isn't particularly consistent. https://api.slack.com/docs/message-attachments#action_fields says:

```
Action fields

All fields are required when using link buttons unless noted.

    type - String - Provide button to tell Slack you want to render a button.
    text - String - A UTF-8 string label for this button. Be brief but descriptive and actionable.
    url - String - The fully qualified http or https URL to deliver users to. Invalid URLs will result in a message posted with the button omitted .
    style - String - Optional - Setting to primary turns the button green and indicates the best forward action to take. Providing danger turns the button red and indicates it some kind of destructive action. Use sparingly. Be default, buttons will use the UI's default text color.
```

**Comment by auhlig** [comment]
Yeah. Both actions seem to be valid - either with `url` or with `name` and `value`. 
I could come up with a PR to add these if you like @simonpasquier.

**Comment by simonpasquier** [comment]
@auhlig no problem for a PR. The main issue with Slack (and other SaaS-based notifiers) is that there is little that we can do for testing and making sure it won't break other users' setups...
