### ISSUE TITLE
Need user sign on

### ISSUE THREAD

**Issue by franchev** [prometheus/alertmanager#1558]
Could there be a way to require users to login when they access the alertmanager page? If possible, could this be Active directory integrated as well.

Thank you.

**Comment by mxinden** [comment]
Hi @franchev,

this is a non-goal of the project itself, but you can solve it via custom proxies in front of Alertmanager.

You can find more info here: https://prometheus.io/docs/operating/security/#authentication-authorization-and-encryption

I am closing here for now. Feel free to reopen in case you have further questions.
