### ISSUE TITLE
Recreating silence should auto-fill comment with previous comment

### ISSUE THREAD

**Issue by stuartnelson3** [prometheus/alertmanager#1566]
If a silence expires but needs to be extended (e.g. maintenance is taking longer than expected, priorities shift and an issue causing an alert has not been resolved), the current `recreate` button blanks out the comment when going to the silence page. It would be nice to copy over the previous message.

**Comment by mikkelbu** [comment]
Looks like this should be closed by #1927

**Comment by simonpasquier** [comment]
Yes, thanks!
