### ISSUE TITLE
Feature request: add metrics around the handling of alerts

### ISSUE THREAD

**Issue by apuchitnis** [prometheus/alertmanager#1569]
**What did you do?**

I went to the `/metrics` path on alertmanager.

**What did you expect to see?**

This is a feature request: I would like to see metrics around the handling of alerts. For example, the number of times a given alert had been received by an alertmanger receiver, and handled by a specific route. This will allow me to get statistics around how many times an alert has fired, so that I can better understand the behaviour of alerts that alertmanager recevies.

I had a look around docs, issues, user guides etc, and unfortunately could not find anything relevant. If I'm missing something obvious, my apologies, and please let me know!

Edit: I'm happy to work on a PR for this if this is indeed a good suggestion. Just let me know :)

**Comment by simonpasquier** [comment]
There is virtually no limit to the cardinality of the alert name which doesn't make it a good candidate as a metric's label. The same goes for group names. See also https://github.com/prometheus/alertmanager/pull/1335 where similar concerns were discussed.

If you're looking for alerts history, you would be better to send the notifications to [Elasticsearch](https://github.com/cloudflare/alertmanager2es) or another datastore (even a simple webhook logging to a file might be sufficient).

**Comment by simonpasquier** [comment]
I assume that subscription = receiver.

> I mostly want to realise that a given subscription (or perhaps even subscription-type) is not delivering currently, to trigger an investigation.

`alertmanager_notifications_failed_total` and `alertmanager_notification_latency_seconds_count` are your friends. This query detects receivers that fail for 10% of the notifications.

```
rate(alertmanager_notifications_failed_total[1m]) / rate(alertmanager_notification_latency_seconds_count[1m]) * 100 > 10
```

> Alternatively - is there a way to test alertmanager subscriptions?

You can use the `amtool alert add` command that can fire/resolve a made-up alert.

There's also https://prometheus.io/webtools/alerting/routing-tree-editor/

**Comment by FUSAKLA** [comment]
For testing of routes to receivers you can also look at this
https://github.com/prometheus/alertmanager#routes

**Comment by apuchitnis** [comment]
Thanks for the suggestions folks. However, these all solve a different problem to what I'd like: testing if receivers are working correctly, rather than giving me statistics about alerts.

Regarding cardinality (@simonpasquier and @stuartnelson3):
> There is virtually no limit to the cardinality of the alert name which doesn't make it a good candidate as a metric's label. The same goes for group names. See also #1335 where similar concerns were discussed.
In my deployment of alertmanager we do not have a large number of alerts, I'd estimate O(100) or so. I'd like to be able to opt in (perhaps via a flag, with a sensible default) to export these metrics, because I know that this is unlikely to impact my deployment.

WDYT, would you satisfied with this opt-in behaviour?

**Comment by simonpasquier** [comment]
For every new feature that gets included to AlertManager, we need to carefully balance between its relevance for the community as a whole and the additional maintenance/operational overhead. And I'm not sure that this particular case is compelling enough.

If you really want to experiment, you could write an exporter that would receive webhook notifications from AlertManager and compute the metrics for you.

**Comment by apuchitnis** [comment]
> And I'm not sure that this particular case is compelling enough.

I would actually disagree here. I would consider statistics on alerts to be a very useful, almost key, feature of any alert manager. For example,
* Uber's equivalent has this https://eng.uber.com/on-call-dashboard
* as does Victor Ops https://victorops.com/incident-analysis-reporting
* and OpsGenie https://docs.opsgenie.com/docs/calculations-for-team-reports

I think other users of alertmanager would also find this useful.

> For every new feature that gets included to AlertManager, we need to carefully balance between its relevance for the community as a whole and the additional maintenance/operational overhead

The operational and maintenance overhead of this feature shouldn't be large I think, just a few files exporting prometheus metrics (which we already do in this codebase).

**Comment by simonpasquier** [comment]
@apuchitnis I don't think we can compare AlertManager with the products you've quoted. AlertManager's [goals](https://prometheus.io/docs/alerting/alertmanager) are grouping, suppressing and dispatching of alerts. This is already a big chunk of work to keep the maintainers busy.

To go back the initial topic, any metric addition/modification is evaluated following the Prometheus best practices, and in particular the recommendation to [not overuse labels](https://prometheus.io/docs/practices/instrumentation/#do-not-overuse-labels). And even if what you are proposing is controlled by an opt-in flag, it is still against what we recommend.

**Comment by apuchitnis** [comment]
Thanks for the discussion @simonpasquier, from what I understand, alertmanager is not aiming to solve this problem. I'll take a look at other solutions.

**Comment by simonpasquier** [comment]
Thanks for your understanding @apuchitnis!

**Comment by bwplotka** [comment]
Seems like one workaround is https://github.com/cloudflare/alertmanager2es for elastic search (:
