### ISSUE TITLE
amtool matcher groups don't work as documented

### ISSUE THREAD

**Issue by bitfehler** [prometheus/alertmanager#1570]
When using more than one matcher group in `amtool query`, according to the documentation, the first one is assumed to be the `alertname` value if it does not contain `=` or `=~`. In fact, the documentation (`amtool alert query -h`) gives this example and explanation:
```
amtool alert query foo node=bar

  If alertname is omitted and the first argument does not contain a '=' or a
  '=~' then it will be assumed to be the value of the alertname pair.
```
However, this doesn't work if using more than one matcher group:

* One matcher group works as advertised:
```
$ amtool alert query SomeAlertName
Alertname  Starts At  Summary 
```
 * Additional matcher groups break this behaviour:
```
$ amtool alert query SomeAlertName instance=foo
amtool: error: bad matcher format: SomeAlertName (code: 400)
```
 * Making the alertname explicit makes it works again:
```
$ amtool alert query alertname=SomeAlertName instance=foo
Alertname  Starts At  Summary
```

**What did you do?**
`$ amtool alert query SomeAlertName instance=foo`

**What did you expect to see?**
`Alertname  Starts At  Summary`, exit code 0

**What did you see instead? Under which circumstances?**
`amtool: error: bad matcher format: SomeAlertName (code: 400)`, exit code != 0, always

**Environment**
Linux x86_64

* System information:

	Linux 4.18.10-arch1-1-ARCH x86_64

* Alertmanager version:
```
$ amtool --version
amtool, version 0.15.2 (branch: HEAD, revision: d19fae3bae451940b8470abb680cfdd59bfa7cfa)
  build user:       root@3101e5b68a55
  build date:       20180814-10:53:39
  go version:       go1.10.3
```

**Comment by stuartnelson3** [comment]
Thanks for the report!
