### ISSUE TITLE
Alerts with constant value getting closed and reopen after upgrade to v0.15.1

### ISSUE THREAD

**Issue by shirpx** [prometheus/alertmanager#1576]
I upgraded alertmanager from version v0.14.0 to version v0.15.1.
in the new version alerts with constant value keeps getting closed and reopen with no reason while they should stay open until solved like it does in the old version.

alert showing firing while its getting closed and reopen and closed again all the time:
![alert showing firing all the time not resolved](https://user-images.githubusercontent.com/33197846/46581504-8f8f8500-ca42-11e8-893d-130e56d912f8.png)

alert query had static value:
![alert had static value](https://user-images.githubusercontent.com/33197846/46581520-c9608b80-ca42-11e8-9f8c-57187320eeb7.png)

example of the alert getting resolved with no reason(happens all the time):
![alert getting resolved with no reason](https://user-images.githubusercontent.com/33197846/46581492-77b80100-ca42-11e8-93a8-2cf09132a74f.png)

example of the alert getting retriggered again(happens all the time):
![alert getting retriggered again](https://user-images.githubusercontent.com/33197846/46581502-8999a400-ca42-11e8-9e97-a390970beccc.png)

alertmanager configuration:

--config.file=/alertmanager.conf 
--log.level debug
--cluster.peer-timeout 35s 
--cluster.listen-address host_ip:9094
--cluster.advertise-address host_ip:9094
--cluster.peer peer_ip:9094

in the alertmanager routes i have that conf:
  group_by: ['instance','consumergroup','alertname']
  group_wait: 30s
  group_interval: 5m

the cluster itself shows as ready in the ui all the time and all the peers are connected.

in the logs of the alertmanager i see that (over and over again):
level=debug ts=2018-10-07T10:28:15.444945943Z caller=dispatch.go:201 component=dispatcher msg="Received alert" alert=KAFKA_CONSUMER_LAG_UNASSIGNED_PARTITION[bbbe8f2][resolved]
level=debug ts=2018-10-07T10:28:15.444972195Z caller=dispatch.go:201 component=dispatcher msg="Received alert" alert=KAFKA_CONSUMER_LAG_UNASSIGNED_PARTITION[cad7701][active]
level=debug ts=2018-10-07T10:28:15.444996498Z caller=dispatch.go:201 component=dispatcher msg="Received alert" alert=KAFKA_CONSUMER_LAG_UNASSIGNED_PARTITION[208cda2][resolved]
level=debug ts=2018-10-07T10:28:15.445035436Z caller=dispatch.go:201 component=dispatcher msg="Received alert" alert=KAFKA_CONSUMER_LAG_UNASSIGNED_PARTITION[f3627e4][active]

i see that from time to time on the peers:
level=debug ts=2018-10-07T10:33:12.833340741Z caller=cluster.go:287 component=cluster memberlist="2018/10/07 10:33:12 [DEBUG] memberlist: Initiating push/pull sync with: 54.183.76.5:9094\n"
level=debug ts=2018-10-07T10:33:12.872997175Z caller=cluster.go:389 component=cluster msg=reconnect result=success peer= addr=54.183.76.5:9094

and can't see any errors or disconnection logs

the prometheus (version 2.3.1) has all the alertmanagers configured like that:
alerting:
  alertmanagers:
  - static_configs:
      - targets:
        - alertmanager_host_ip:9093

plus it's important to mention it's not only happening on that specific alert (more than one alert acting like that)

**Comment by simonpasquier** [comment]
Discussion follows here https://groups.google.com/d/msg/prometheus-developers/kyLTdh7zTtk/L1xzXJvpAwAJ
