### ISSUE TITLE
feature-request: configuration over rest api

### ISSUE THREAD

**Issue by ezraroi** [prometheus/alertmanager#1577]
We would like to be able to re configure alert manager without the need to have some kind of an agent on the machine that can re generate the configuration file when needed.

If we could send the new conflagration content as the body of the `reload` request it could be great

**Comment by stuartnelson3** [comment]
I believe this is something that we explicitly don't want to allow. It makes it harder to track config changes, and why those changes were introduced. If the alertmanager is for some reason brought down and back up, then it will load the config file on disk anyway.

**Comment by simonpasquier** [comment]
This isn't something that is supported by any of the Prometheus projects and has been rejected before for Prometheus itself (see https://github.com/prometheus/prometheus/issues/1972). There is very little chance for AlertManager to be an exception.

**Comment by ezraroi** [comment]
Thanks, I understand this.
We are trying to create a self service system for our developers and such capability for alert manager and prometheus could make this task easier

**Comment by simonpasquier** [comment]
If you're on Kubernetes, I would encourage you to look at https://github.com/coreos/prometheus-operator

**Comment by ezraroi** [comment]
Thanks, will look. We are using nomad

**Comment by ezraroi** [comment]
Thanks, will look. We are using nomad

**Comment by simonpasquier** [comment]
https://www.nomadproject.io/guides/operations/consul-integration/index.html#dynamic-configuration might be what you're looking for?

**Comment by ezraroi** [comment]
Yes, thank you
