### ISSUE TITLE
silencer "recreate" does not remember matching with "regex"

### ISSUE THREAD

**Issue by liuzhen** [prometheus/alertmanager#1584]
What did you do?

receate an expired "silencer" with matching of 'regex'

What did you expect to see?
the to be created new silencer have all the properties derived from the old one, including the checked 'regex'

What did you see instead? Under which circumstances?

the 'regex' checkbox is cleared within the matching rule

**Comment by simonpasquier** [comment]
Thanks for reporting!

**Comment by dhallam** [comment]
Previously reported in #1299

**Comment by simonpasquier** [comment]
Closing then as it is a duplicate.
