### ISSUE TITLE
Running as non-root

### ISSUE THREAD

**Issue by InsidersByte** [prometheus/alertmanager#1585]
Does alertmanager need to run as root by default?

It looks like it was changed a while back to use the user `nobody` like [prometheus](https://github.com/prometheus/prometheus/blob/master/Dockerfile#L14) in this [pr](https://github.com/prometheus/alertmanager/pull/41) after it was raised in this [issue](https://github.com/prometheus/alertmanager/issues/39).

Looking back at the history is was removed after the Dockerfile was [deleted](https://github.com/prometheus/alertmanager/commit/84c7af965276fa31f8683b913090aa9cc085db89#diff-3254677a7917c6c01f55212f86c57fbf) and [readded](https://github.com/prometheus/alertmanager/commit/d80fd2690298710d866afe6f1cb6455ebe48b177#diff-3254677a7917c6c01f55212f86c57fbf).

**Comment by simonpasquier** [comment]
> Does alertmanager need to run as root by default?

No. @stuartnelson3 @mxinden WDYT about switching to the `nobody` user for the container image? AFAICT the [revert](https://github.com/prometheus/alertmanager/commit/d80fd2690298710d866afe6f1cb6455ebe48b177#diff-3254677a7917c6c01f55212f86c57fbf) wasn't intentional.

**Comment by stuartnelson3** [comment]
Sounds fine to me, but the default data dir will probably have to change https://github.com/prometheus/alertmanager/blob/master/Dockerfile#L13

**Comment by mxinden** [comment]
Running as nobody sounds great to me.

Instead of chaning the default data dir I would suggest to stay [consistent with Prometheus](https://github.com/prometheus/prometheus/blob/master/Dockerfile#L12) and do:

```Dockerfile
RUN mkdir -p /prometheus && \
    chown -R nobody:nogroup etc/alertmanager /alertmanager
```

Does that sound good to you @stuartnelson3? 

@InsidersByte would you like to follow up with a pull request?

**Comment by InsidersByte** [comment]
sure @mxinden. Here's the [pr](https://github.com/prometheus/alertmanager/pull/1586)

**Comment by stuartnelson3** [comment]
👍 for consistency, thanks @mxinden !
