### ISSUE TITLE
Alertmanager to BMC

### ISSUE THREAD

**Issue by IanJ87** [prometheus/alertmanager#1595]
Hi,
Is there any integration with Alertmanager and BMC (apart from webhook_config, which is incompatible with BMC’s webook) that will work or any planned please?

Thanks

**Comment by simonpasquier** [comment]
In the short/mid term, the project doesn't accept new receivers as explained in the [documentation](https://prometheus.io/docs/alerting/configuration/#%3Creceiver%3E). The webhook receiver is meant for integrating with systems that aren't supported: an intermediary service receives notification payload from AlertManager and translates the information for the 3rd-party system.

```
AlertManager -----> Intermediary service ----> 3rd-party system
```

I couldn't find any integration for BMC but you can have a look at the existing [https://prometheus.io/docs/operating/integrations/#alertmanager-webhook-receiver](integrations) for inspiration and write your own.

I'm closing it for now. If you have further questions, please use our [user mailing list](https://groups.google.com/forum/#!forum/prometheus-users), which you can also search.
