### ISSUE TITLE
Manage Expired alerts in alertmanager

### ISSUE THREAD

**Issue by raja-gola** [prometheus/alertmanager#1597]
UseCase:
Alert setup: I have setup an alert for high memory usage of pod, which sends an alert if the memory usage of pod reaches 95%.

It works fine i.e it sends an alert as expected. But what happens is, the pod gets restarted (as it reaches 100% limit). So after that, we are expecting a resolved alert as  the memory usage has come down, which never happens.

So the alert in firing state is gone. It's expired. How to proceed in that case

**Comment by stuartnelson3** [comment]
This is a usage question, which should be sent to the mailing list prometheus-users@googlegroups.com. This gives your question (and its answer) the opportunity to reach a wider audience.
