### ISSUE TITLE
Add option to customize alias field for opsgenie alerts

### ISSUE THREAD

**Issue by primeroz** [prometheus/alertmanager#1598]
OpsGenie deduplicate messages based on the Alert [alias](https://docs.opsgenie.com/docs/alert-api#section-create-alert). 

This alias is currently calculated by hashing the "GroupLabels" with sha256 [here](https://github.com/prometheus/alertmanager/blob/b63b5600741b07795e50cedf8818a853bacc5f76/notify/impl.go#L1175)

In my scenario i have multiple Alertmanager sources ( for multiple kubernetes clusters ) using a single integration on the OpsGenie side with a common set of prometheus rules and alertmanager routing configuration.
 
Two alerts on two different clusters sharing the same set of GroupLabels produce the same ALIAS sha256 and as such they are treated as the same alert on opsgenie and deduplicated , even if they are coming from different clusters.

My current workaround is to add a static label to every group_by that include the Kubernetes ClusterId but that is not ideal since that is something i have to do for every route i ship to opsgenie

**Proposal**

Would it make sense to add a single configuration field to the opsgenie receiver configuration to add a static extra seed for the hashing function that generate this alias ? 
This way , by leveraging templates when creating the alertmanager configuration, it would be possible to differentiate the same alert between different alertmanager sources

**Comment by brian-brazil** [comment]
> My current workaround is to add a static label to every group_by that include the Kubernetes ClusterId but that is not ideal since that is something i have to do for every route i ship to opsgenie

This is how grouping works in the alertmanager, and what you suggest would not work as the alerts would still be in the same group and thus the same notification. group_by is the right way to handle this.

**Comment by simonpasquier** [comment]
> Adding a "CLUSTER=ID" label to every single group_by ( a label that is the same for every single alert alertmanager will see since is pushed as an externallabel by prometheus) is a workaround

Using `external_labels` is the right thing to do here.

**Comment by primeroz** [comment]
@simonpasquier i am using external_labels , from prometheus to alertmanager. How does that change the alias generated by alertmanager ?

**Comment by simonpasquier** [comment]
I just meant to say that in any case, you have to define somewhere the key that differentiate your clusters and what you describe as a workaround is the normal way to go as long as your "group by" parameter includes this external label (eg `group_by: ['service', 'severity', 'alertname', 'clusterid']`).

**Comment by primeroz** [comment]
yeah that is what i am doing, but it seems quite a workaround  ... also , and maybe this is something i am doing wrong, i tend to have quite a few sub-routes, around 30 of them, to do different grouping for different rules. in each of them i had to add the clusterid as well ... just to change the alias produced by the code for my opsgenie alert.

I am just wondering if this is the correct behavior to hardcode the way the alias is generated with no other way to customize it than to mangle with all group_by in the config.

**Comment by pawadski** [comment]
+1. I am using OpsGenie and control over the Alias field would be appreciated. I understand that Alertmanager is supposed to deduplicate alerts for me, but I would like to see this implemented as it is a critical part of the OpsGenie API.

**Comment by jvdspeare** [comment]
+1 This is currently blocking some key functionality with OpsGenie.

**Comment by pawadski** [comment]
I have created this simplistic proxy script in Python3.5 to enable customization of this as a workaround: https://github.com/pawadski/alertmanager-opsgenie-proxy

This way we can, for the time being, customize alias fields.

**Comment by GMartinez-Sisti** [comment]
After checking this thread and a little further I managed to fix this with external labels.

These helped a lot in my case:
- https://groups.google.com/forum/#!topic/prometheus-users/koI1GrAS0lg
- https://github.com/coreos/prometheus-operator/issues/455

I added this to prometheus config (I'm using custom prometheus-operator in k8s):
```yaml
externalLabels:
    cluster: ${KOPS_CLUSTER_NAME}
    env: ${KOPS_CLUSTER_ENV}
```

And in Alert Manager config added this:
```yaml
route:
  group_by:
    - job
    - alertname
    - service
```

And now the alerts have the cluster and env in the alias, making them unique by cluster.

Hope it helps.

**Comment by primeroz** [comment]
I did open this case and hit it again ... i believe though that the solution provided by https://github.com/prometheus/alertmanager/issues/1598#issuecomment-473527548  is good enough.

I propose to close this issue but maybe add the info to the documentation for the opsgenie receiver with the example from the comment above to avoid people keep hitting the same issue ?

**Comment by simonpasquier** [comment]
@primeroz closing for now then. I don't think that the [reference documentation](https://prometheus.io/docs/alerting/configuration/) isn't the proper place for such details.

**Comment by juliandm** [comment]
@GMartinez-Sisti You mentioned that alerts have the cluster and env in the alias, but you only added env into the group_by statement. Did you forget to put cluster there?

**Comment by GMartinez-Sisti** [comment]
> @GMartinez-Sisti You mentioned that alerts have the cluster and env in the alias, but you only added env into the group_by statement. Did you forget to put cluster there?

If you have multiple clusters per env you should add it to the `group_by`. Otherwise, if it is a 1:1 relation (env<>clusters) you can skip it. In any case,  the `cluster` label will be available in the event, it just won't be used to group alerts on the former.

**Comment by marwaneldib** [comment]
@GMartinez-Sisti How did you verify the alias had in fact `cluster` worked on the opsgenie side?

**Comment by GMartinez-Sisti** [comment]
> @GMartinez-Sisti How did you verify the alias had in fact `cluster` on the opsgenie side?

Sorry @marwaneldib, but I don't have the access to that infra anymore and can't remember the context reply to this 😅.
