### ISSUE TITLE
need documentation on how to use template secret

### ISSUE THREAD

**Issue by reachlin** [prometheus/alertmanager#1600]
It's not clear how to put encrypted key into alertmanger config for PagerDuty. I see we can use template for the key in the doc. 

```
# The PagerDuty integration key (when using PagerDuty integration type `Prometheus`).
service_key: <tmpl_secret>
```
and a sample,
https://github.com/prometheus/alertmanager/blob/b63b5600741b07795e50cedf8818a853bacc5f76/doc/examples/simple.yml#L118

But it's still not clear what are these and where they are from:
`- service_key: <team-DB-key>`

**Comment by simonpasquier** [comment]
A secret string is a string that is hidden when displayed in the AlertManager UI while a template string is expanded using the Go templating engine. The simplest thing to do is to put your service key as-is in place of `<team-DB-key>`.

I'm closing it for now. If you have further questions, please use our [user mailing list](https://groups.google.com/forum/#!forum/prometheus-users), which you can also search.
