### ISSUE TITLE
Alertmanager `data.retention` does not understand units > h

### ISSUE THREAD

**Issue by vsliouniaev** [prometheus/alertmanager#1605]
**What did you do?**
`alertmanager --data.retention=7d`

**What did you expect to see?**
Alertmanager should be able to interpret the standard ms, s, m, d, h, y specifications for data retention and start up.

**What did you see instead? Under which circumstances?**
```
alertmanager: error: time: unknown unit d in duration 7d, try --help
```
**Environment**

* System information:
`Linux 4.4.0-17134-Microsoft x86_64`

* Alertmanager version:
```
alertmanager, version 0.15.2 (branch: HEAD, revision: d19fae3bae451940b8470abb680cfdd59bfa7cfa)
  build user:       root@3101e5b68a55
  build date:       20180814-10:53:39
  go version:       go1.10.3
```
* Logs:
```
alertmanager: error: time: unknown unit d in duration 7d, try --help
```

**Comment by stuartnelson3** [comment]
The flag parsing library we're using, kingpin, uses the stdlib duration parser. The golang duration parser doesn't support time units larger than an hour.

https://golang.org/pkg/time/#ParseDuration

**Comment by shubhamc183** [comment]
Hi, @vsliouniaev just wondering what does `alertmanager --data.retention` actually mean?

I am under the impression that the alertmanager is a stateless application!

**Comment by simonpasquier** [comment]
@shubhamc183 Alertmanager stores state about silences and notification logs.

**Comment by AndrewwHummer** [comment]
Just FYI: Data Retention does not affect Silences with longer duration than the data retention period.
