### ISSUE TITLE
Getting an error from slack 

### ISSUE THREAD

**Issue by eyaldavid** [prometheus/alertmanager#1606]
**What did you do?**

created local HA cluster of AlertManager with 3 nodes and trying to send alerts to slack

**What did you expect to see?**

alerts on slack

**What did you see instead? Under which circumstances?**

error message inside the  console output
15:54:47 a1 | level=debug ts=2018-11-04T13:54:47.881882Z caller=notify.go:669 component=dispatcher msg="**Notify attempt failed" attempt=1 integration=slack receiver=slack_general err="unexpected status code 404"**
15:54:47 a1 | level=error ts=2018-11-04T13:54:47.881963Z caller=notify.go:332 component=dispatcher msg=**"Error on notify" err="cancelling notify retry for \"slack\" due to unrecoverable error: unexpected status code 404"**
15:54:47 a1 | level=error ts=2018-11-04T13:54:47.882024Z caller=dispatch.go:183 component=dispatcher **msg="Notify for alerts failed" num_alerts=4 err="cancelling notify retry for \"slack\" due to unrecoverable error: unexpected status code 404"**
**Environment**
Alert manager -  I ran the procfile from within the repository and run it on my mac 
Prometheus  - local last version from github on my mac as well 
Slack - created test chanel which succeeded to deliver messages to it with curl
* System information:

	Darwin

* Alertmanager version:

	alertmanager, version 0.15.2 (branch: master, revision:    0d94ec22683a3dcdcdd0517641b7d7a589f3f6a1)
  build user:       eydavid@xxxxxxxxx
  build date:       20181028-14:07:38
  go version:       go1.11.1

* Prometheus version:

	prometheus, version 2.5.0-rc.0 (branch: master, revision: fe0f0da6b3b7a9d1c325108cc1fc9c084804aa21)
  build user:       eydavid@xxxxxxx
  build date:       20181029-07:58:47
  go version:       go1.11.1

* Alertmanager configuration file:
```
alertmanager.yml

route:
  group_by: [cluster]
  # If an alert isn't caught by a route, send it slack.
  receiver: slack_general
        
receivers:
- name: slack_general
  slack_configs:
    - api_url: "https://hooks.slack.com/services/XXXXXXXX"
      channel: testalertmgr
      send_resolved: true
      username: myname
      text: "stam test"
```

* Prometheus configuration file:
```
prometheus.yml

# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - localhost:9093
      - localhost:9094
      - localhost:9095

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
    - "alert.rules"
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
    - targets: ['localhost:9090']

```

* Logs:
```
6:05:02 a2 | level=error ts=2018-11-04T14:05:02.813967Z caller=notify.go:332 component=dispatcher msg="Error on notify" err="cancelling notify retry for \"slack\" due to unrecoverable error: unexpected status code 404"
16:05:02 a2 | level=error ts=2018-11-04T14:05:02.814026Z caller=dispatch.go:183 component=dispatcher msg="Notify for alerts failed" num_alerts=4 err="cancelling notify retry for \"slack\" due to unrecoverable error: unexpected status code 404"
16:05:06 a3 | level=debug ts=2018-11-04T14:05:06.94053Z caller=cluster.go:287 component=cluster memberlist="2018/11/04 16:05:06 [DEBUG] memberlist: Initiating push/pull sync with: 127.0.0.1:8002\n"
16:05:06 a2 | level=debug ts=2018-11-04T14:05:06.940681Z caller=cluster.go:287 component=cluster memberlist="2018/11/04 16:05:06 [DEBUG] memberlist: Stream connection from=127.0.0.1:61651\n"
16:05:17 a3 | level=debug ts=2018-11-04T14:05:17.814063Z caller=notify.go:669 component=dispatcher msg="Notify attempt failed" attempt=1 integration=slack receiver=slack_general err="unexpected status code 404"
16:05:17 a3 | level=error ts=2018-11-04T14:05:17.814139Z caller=notify.go:332 component=dispatcher msg="Error on notify" err="cancelling notify retry for \"slack\" due to unrecoverable error: unexpected status code 404"
16:05:17 a3 | level=error ts=2018-11-04T14:05:17.814225Z caller=dispatch.go:183 component=dispatcher msg="Notify for alerts failed" num_alerts=4 err="cancelling notify retry for \"slack\" due to unrecoverable error: unexpected status code 404"
```

**Comment by simonpasquier** [comment]
A 404 code indicates that the URL isn't valid. Are you sure about your `api_url`?

**Comment by sylr** [comment]
I had this today, it was because the api_url was configured to post in a specific channel which was different from the one defined in the alertmanager configuration.

**Comment by simonpasquier** [comment]
This problem should be alleviated by #1655.
