### ISSUE TITLE
Support Prometheus standard time formats in silence creation

### ISSUE THREAD

**Issue by grobie** [prometheus/alertmanager#1615]
Prometheus supports relative time options like `y` and `w` which would be quite helpful to use when creating silences.

https://github.com/prometheus/common/blob/0b1957f9d949dfa3084171a6ec5642b38055276a/model/time.go#L192-L205

**Comment by simonpasquier** [comment]
It is for the UI, right?

**Comment by stuartnelson3** [comment]
Yeah, in the silence creation form in the UI

**Comment by stuartnelson3** [comment]
I am cool supporting `w`, but as a project alertmanager wants to discourage "eternal silences". It's still possible if users want to do it, but a month (`4w`) seems to me like the upper bound on how long something should be silenced.
