### ISSUE TITLE
Sending to invalid slack channel only gives 404 with no user data

### ISSUE THREAD

**Issue by SteveGoodenough** [prometheus/alertmanager#1616]
If you try to send an alert to an unknown slack channel the error does not give anymore information than "error: unexpected status code 404"

**What did you do?**
We have a number of slack channels (using a multi-tenant k8s cluster) so our receiver has the following:
``
channel: '{{ printf "topic-svc-%.11s" (index (index .Alerts 0).Labels "namespace") }}'
``
(the %.11s to ensure the channel name fits within the 21 character limit)

**What did you expect to see?**
As the channel name is programmatically generated it would be useful to see the whole 404 message (assuming it would show the generated channel name) or for the error to give more information on what channel the alert was going to.

**What did you see instead? Under which circumstances?**
The alert never reaches the user

You only see "error: unexpected status code 404" in the log

e.g.
``
alertmanager-k8s-0 alertmanager level=error ts=2018-11-09T15:36:28.937308263Z caller=dispatch.go:280 component=dispatcher msg="Notify for alerts failed" num_alerts=1 err="cancelling notify retry for \"slack\" due to unrecoverable error: unexpected status code 404"
``

**Comment by simonpasquier** [comment]
This is similar to #1540 and #1541. In general, I think we should be careful about what we store (eg logging the request might contain sensitive date) but I agree that getting useful information helps a lot. The Slack documentation provides [details](https://api.slack.com/incoming-webhooks#handling_errors) about the returned payload and I suggest that it gets added to the returned error.
