### ISSUE TITLE
Alertmanager not GC'ing silences

### ISSUE THREAD

**Issue by stuartnelson3** [prometheus/alertmanager#1624]
**What did you do?**

Checked the "expired" tab on the silences page, and saw silences going back 2 months in time. The alertmanager cluster is using the default retention time, `120h`.

**What did you expect to see?**

Expired silences for the last `120h`.

**What did you see instead? Under which circumstances?**

Expired silences for the last 2 months.

**Environment**

* System information:

	`Linux 4.4.10+soundcloud x86_64`

* Alertmanager version:

	`0.15.3`

* Logs:
Unfortunately, we don't have much logging or metrics around this.

**Comment by simonpasquier** [comment]
Hmm, tested with a short retention period (1h) and it worked well for me.

**Comment by stuartnelson3** [comment]
Weird. I feel like we addressed this once before. Was this in a clustered setup?

**Comment by simonpasquier** [comment]
Ah no it was a single instance...

**Comment by stuartnelson3** [comment]
It seems to have GC'd the 2 month+ old silences when I started looking into why it wasn't GC'ing them. Closing.

**Comment by stuartnelson3** [comment]
It seems they came back.

**Comment by mxinden** [comment]
@stuartnelson3 how big is the cluster? Are you able to add a Prometheus instance scraping it so we can watch it over time?

**Comment by stuartnelson3** [comment]
three nodes, it's been scraped the entire time:

![image](https://user-images.githubusercontent.com/1398104/48782427-78e57a80-ecde-11e8-831f-badf44df8746.png)

There are expired silences going back to `2018-09-13`, despite `--data.retention` being set to `72h`. I changed it from the default to see if that had any effect, which it doesn't seem to have.
