### ISSUE TITLE
amtool config routes command not available

### ISSUE THREAD

**Issue by peergynt** [prometheus/alertmanager#1628]
The amtool routes visualization feature does not seem to be available. The **routes** command is not even recognized.

**amtool --version**
amtool, version 0.15.3 (branch: HEAD, revision: d4a7697cc90f8bce62efe7c44b63b542578ec0a1)
  build user:       root@4ecc17c53d26
  build date:       20181109-15:40:48
  go version:       go1.11.2

**amtool config routes --help**
amtool: error: unexpected routes

**Comment by simonpasquier** [comment]
The command will be available in the next release of AlertManager. But I think you should be able to use `amtool` from master against a 0.15.3 AlertManager.
