### ISSUE TITLE
There is no errors in log but I cannot receive message in we chat

### ISSUE THREAD

**Issue by SFHfeihong** [prometheus/alertmanager#1645]
prometheus version:  2.1.0
alertmanager version: 0.15.1

my config:
global:
  wechat_api_url: 'https://qyapi.weixin.qq.com/cgi-bin/'
route:
  receiver: 'yanfa'
  group_by: ['alertname']
  continue: false
  group_wait:      30s
  group_interval:  5m
  repeat_interval: 3h

  routes:
  - receiver: 'yanfa'
    group_wait: 30s
    match:
      status: 'red'
receivers:
- name: 'yanfa'
  wechat_configs:
  - send_resolved: true
    to_party: '3'
    to_user: '@all'
    agent_id: '1000002'
    corp_id: 'ww363e483f6ea626df'
    api_secret: 'SjbTV**************prHN0mjip-VsxRAwutUf-NRgY'

I visit http://*.*.*.*:9093/#/status, I get the following result:

![qq 20181130174216](https://user-images.githubusercontent.com/27404167/49281384-6120aa00-f4c7-11e8-830d-670590e89a79.png)

Is it right? I cannot receive message in we chat.

**Comment by simonpasquier** [comment]
Thanks for your report. It looks as if this is actually a question about usage and not development.

To make your question, and all replies, easier to find, we suggest you move this over to our [user mailing list](https://groups.google.com/forum/#!forum/prometheus-users), which you can also search. If you prefer more interactive help, join or our [IRC channel](https://webchat.freenode.net/?randomnick=1&channels=prometheus), #prometheus on irc.freenode.net. Please be aware that our IRC channel has no logs, is not searchable, and that people might not answer quickly if they are busy or asleep. If in doubt, you should choose the mailing list.

Once your questions have been answered, please add a short line pointing to relevant replies in case anyone stumbles here via a search engine in the future.
