### ISSUE TITLE
Reload doesn't detect change in proxy_url settings

### ISSUE THREAD

**Issue by dwagon** [prometheus/alertmanager#1649]
**What did you do?**
Removed the proxy_url setting and reloaded via the API

**What did you expect to see?**
proxy_url settings to no longer be there.

**What did you see instead? Under which circumstances?**
No change in proxy_url existence.

Changing the config and hitting the /-/reload endpoint; it will detect a change to the details (IP or port) but if I comment the proxy_url line out - it will not detect that. Nor will it detect adding a proxy_url if there wasn't one there before.

A full restart changes the settings appropriately.

**Environment**

* System information:

Darwin 17.7.0 x86_64
Linux 3.10.0-862.3.3.el7.x86_64 x86_64

* Alertmanager version:
```
  alertmanager, version 0.15.2 (branch: HEAD, revision:d19fae3bae451940b8470abb680cfdd59bfa7cfa)
  build user:       root@3101e5b68a55
  build date:       20180814-10:55:04
  go version:       go1.10.3
```
* Prometheus version:

	Not relevant

* Alertmanager configuration file:
```
---
global:
  http_config:
    proxy_url: http://127.0.0.1:5432
```

* Prometheus configuration file:
```
Not relevent
```

* Logs:
When reloading there are no errors in the logs:
```
level=info ts=2018-12-04T00:04:29.178120962Z caller=main.go:322 msg="Loading configuration file" file=alertmanager.yml
```

**Comment by simonpasquier** [comment]
I can reproduce the bug on the master branch too.

**Comment by geekodour** [comment]
@simonpasquier i'd like to work on this as my first contribution. I am looking into https://github.com/prometheus/alertmanager/blob/master/cmd/alertmanager/main.go#L334 now.

**Comment by simonpasquier** [comment]
@geekodour I've dug into the issue and the problem is here:

https://github.com/prometheus/alertmanager/blob/ac058957e7eeeeec0d88fed3090b1a01811ac3bf/config/config.go#L218-L223

`DefaultGlobalConfig` is defined here:

https://github.com/prometheus/alertmanager/blob/ac058957e7eeeeec0d88fed3090b1a01811ac3bf/config/config.go#L423-L434

Since it is a global variable, `*DefaultGlobalConfig.HTTPConfig` is overwritten when the YAML configuration is un-marshaled. If `http_config:` is empty or missing from the global configuration, the last non-empty value is kept.

**Comment by geekodour** [comment]
@dwagon I am able to reproduce the first part about commenting but the following works for me.
> Nor will it detect adding a proxy_url if there wasn't one there before.

```yaml
---
templates:
.
.
other_configs:
```
start alertmanager, change configurations to:
```yaml
---
global:
  http_config:
    proxy_url: http://127.0.0.1:5432
templates:
.
.
other_configs:
```
use api/SIGHUP to reload alertmanager, changes are reflected.
I tried this on master, will check on `v0.15.2`
