### ISSUE TITLE
Alert manager is showing alerts on UI, but unable to forward to SMTP.

### ISSUE THREAD

**Issue by chintaman** [prometheus/alertmanager#1650]
Issue : Alert manager is showing alerts on UI, shows pending, then firing states, but unable to forward to SMTP server. I am not getting emails.

Configured alertmanager.yml with SMTP server and port info.
Updated  smtp_smarthost:   ,     smtp_from:  ,   smtp_hello:   properly.
- Now expecting email for detected alert, which can be observed in UI as well.

I am seeing error log as below: 
level=error ts=2018-12-05T12:22:14.25346737Z caller=dispatch.go:280 component=dispatcher msg="Notify for alerts failed" num_alerts=2 err="short response: * OK [CAPABILITY IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE STARTTLS LOGINDISABLED] Dovecot ready."
(SMTP as well as IMAP both ports I have tried separately.)
	uname -srm
Linux 3.10.0- el7.x86_64 x86_64
alertmanager --version
alertmanager, version 0.15.2 (branch: HEAD, revision: d19fae3bae451940b8470abb680cfdd59bfa7cfa)
  build user:       root@3101e5b68a55
  build date:       20180814-10:53:39
  go version:       go1.10.3
prometheus -version
prometheus, version 2.4.3 (branch: HEAD, revision: 167a4b4e73a8eca8df648d2d2043e21bdb9a7449)
  build user:       root@1e42b46043e9
  build date:       20181004-08:42:02
  go version:       go1.11.1

How to resolve this issue ?

**Comment by geekodour** [comment]
try setting `require_tls:` to `false`
https://prometheus.io/docs/alerting/configuration/#%3Cemail_config%3E

**Comment by chintaman** [comment]
Yes, That has resolved this issue. 
I was about to post the same, after lot of try, and getting this resolved yesterday, meanwhile you have commented the right thing. !  Still thank you for mentioning that.
I saw default rule picked up by Prometheus in UI, and found require_tls value was picked up as true, (default), as it was not defined in config.

**Comment by chintaman** [comment]
Resolved.!
