### ISSUE TITLE
Support for --log.format=json

### ISSUE THREAD

**Issue by kfdm** [prometheus/alertmanager#1657]
Related to #1128 and prometheus/prometheus#4876 it should be reasonably? easy to update the prometheus/common package to support the same `--log.format=json`

I imagine this is already too late for 0.16.0 but perhaps this can go in the next version.

I can try to give this PR a try myself, but my go is weak so if someone gets to it before I do, that would also work :)

**Comment by simonpasquier** [comment]
Closed by #1658
