### ISSUE TITLE
amtool config show can't unmarshal response

### ISSUE THREAD

**Issue by stuartnelson3** [prometheus/alertmanager#1659]
**What did you do?**
Attempted to use `amtool config show` against a remote alertmanager
**What did you expect to see?**
A successful output
**What did you see instead? Under which circumstances?**
`unsupported scheme "" for URL`
**Environment**

* Alertmanager version:

	`0.16.0-alpha.0`

I would guess it has something to do with our API migration

**Comment by stuartnelson3** [comment]
It appears to have occurred in ce2f2ac380a259c9cc45446b2a67b5361bf5c4b0

**Comment by simonpasquier** [comment]
See https://github.com/prometheus/alertmanager/pull/1663
