### ISSUE TITLE
Status endpoint outputs unexpected config

### ISSUE THREAD

**Issue by stuartnelson3** [prometheus/alertmanager#1662]
**What did you do?**
A config matching what was used to start the server
**What did you expect to see?**
Duplicated `group_by` and `GroupBy`/`groupby` fields (depends on configJSON or configYAML), and an incorrectly unmarshalled `GroupByAll`/`groupbyall`.
**What did you see instead? Under which circumstances?**
No duplicated group_by, and `group_by_all` properly formatted
**Environment**

* Alertmanager version:

	v0.16.0-alpha.0

**Comment by geekodour** [comment]
@stuartnelson3 can you share the config? I haven't tried v0.16.0-alpha.0, I'd like to look into it.
I don't see why something that used to start the server before should now incorrectly unmarshal `groupbyall` as you expect.

I haven't been following the work done in v0.15.0-alphs.0

**Comment by mxinden** [comment]
> **What did you expect to see?**
Duplicated group_by and GroupBy/groupby fields (depends on configJSON or configYAML), and an incorrectly unmarshalled GroupByAll/groupbyall.
**What did you see instead? Under which circumstances?**
No duplicated group_by, and group_by_all properly formatted

You mixed up "What did you expect to see" with "not expect to see", right?

**Comment by stuartnelson3** [comment]
@geekodour the re-marshaling of the config resulted in `groupbyall` and `groupby` being written out, which are two internal fields that we don't need to expose to the user.
