### ISSUE TITLE
why the inhibit_rules does not take effect?

### ISSUE THREAD

**Issue by 249510573** [prometheus/alertmanager#1671]
why the following  inhibit_rules does not take effect?

- alert: InstanceDown
     expr: up == 0
     for: 2m
     labels:
       team: node
       severity: critical 
       target: "{{$labels.service}}"
     annotations:
       summary: "{{$labels.instance}}: has been down"
       description: "{{$labels.instance}}: job {{$labels.job}} has been down "
       value: "{{ $value }}"
 - alert: consul_exporter_health_up
    expr: consul_health_service_status{status="passing"} == 0
    for1m
    labels:
      serverity: warning
      target: "{{$labels.service_name}}"
    annotations: 
      summary: "服务{{$labels.service_name}}: heath checking has not passsing"
      description: "服务监控检查"

 the  inhibit_rules as follows:
inhibit_rules:
  - source_match:
      alert: 'InstanceDown'
      severity: 'critical'
    target_match:
      alert: 'consul_exporter_health_up'
      severity: 'warning'
    equal: ['target']

the alarm as follows:
alertname="InstanceDown" dc="dc1" instance="10.221.103.141:9100" job="consul_node_exporter" port="9100" server="10.221.103.141" service="node-exporter" service_port="9100" severity="critical" target="node-exporter" team="node"                                                                                                                         description="10.221.103.141:9100: job consul_node_exporter has been down " summary="10.221.103.141:9100: has been down" value="0"  2018-12-18 07:33:18 UTC  2018-12-18 07:37:33 UTC  http://559f8ce91b41:9090/graph?g0.expr=up+%3D%3D+0&g0.tab=1    
                                                    
alertname="consul_exporter_health_up" check="service:node-exporter" dc="dc1" instance="10.221.103.141:9107" job="consul_node_exporter" node="sihua" port="9107" server="10.221.103.141" serverity="warning" service="consul-exporter" service_id="node-exporter" service_name="node-exporter" service_port="9107" status="passing" target="node-exporter"  description="服务监控检查" summary="服务node-exporter: heath checking has not passsing"                                                    2018-12-18 07:33:19 UTC  2018-12-18 07:37:34 UTC  http://559f8ce91b41:9090/graph?g0.expr=consul_health_service_status%7Bstatus%3D%22passing%22%7D+%3D%3D+0&g0.tab=1

**Comment by simonpasquier** [comment]
Can you run the AlertManager with `--log.level=debug` and share logs?
Please also provide the AlertManager &Prometheus configurations and versions.

**Comment by 249510573** [comment]
i hava send a email to spasquie@redhat.com. thanks

**Comment by simonpasquier** [comment]
You've got a typo, it should be `alertname` rather than `alert`:

```yaml
  - source_match:
      alertname: 'InstanceDown'
      severity: 'critical'
    target_match:
      alertname: 'consul_exporter_health_up'
      severity: 'warning'
    equal: ['target']
```

**Comment by beorn7** [comment]
Note that the display might be lagging, see #979 . But you should not get any notifications sent out for an inhibited alert.

**Comment by 249510573** [comment]
what can I do?  config a small group_interval? 

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'email'

receivers:
  - name: 'email'
    email_configs:
    - to: 'XXXX' 
      html: '{{ template "test.html" . }}'
      headers: { Subject: "[WARN] 报警邮件"}
   
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: 
      - NodeMemoryUsage
  
  - source_match:
      alertname: 'InstanceDown'
      severity: 'critical'
    target_match:
      alertname: 'consul_exporter_health_up'
      severity: 'warning'
    equal: ['target']

**Comment by beorn7** [comment]
Or wait until group_interval has passed. However, a flapping alert might show up anyways.

But you can also just check if a notification was sent out. In your case, check if you ever see an email that should have been inhibited.

**Comment by stuartnelson3** [comment]
This is a support question. As explicitly stated in the Issue template, this should be directed to our mailing list prometheus-users@googlegroups.com, where more people can benefit from the question, as well as provide possible solutions.

**Comment by JasonYLong** [comment]
inhibit_rules:
- source_match:
    alertname: 'InstanceDown'
    severity: 'critical'
  target_match:
    alertname: 'consul_exporter_health_up'
    severity: 'warning'
  equal: ['alertname','instance']

This works for me.
