### ISSUE TITLE
Need to configure alert manager to store historical data

### ISSUE THREAD

**Issue by suresh1006** [prometheus/alertmanager#1677]
I need to configure alert manager in a way that it can capture and store historical data.kindly let me know if there is a solution to implement this or any other possible way to achieve this

**Comment by simonpasquier** [comment]
https://github.com/cloudflare/alertmanager2es might be what you're looking for. Other integration mechanisms are listed in the documentation: https://prometheus.io/docs/operating/integrations/#alertmanager-webhook-receiver

I'm closing it for now. If you have further questions, please use our [user mailing list](https://groups.google.com/forum/#!forum/prometheus-users), which you can also search.
