### ISSUE TITLE
alert rule schema can be customized

### ISSUE THREAD

**Issue by lm123** [prometheus/alertmanager#1680]
**What did you do?**
Against the following alert rule：

- alert: NodeCPUUsageMinor
    expr: 100 - avg by (instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100 > 70
    for: 0s
    labels:
      severity: MINOR
      name: CPUExceedThreshold
      text: Usage of CPU is greater than the threshold value
      id: 3001203
      eventType: 11
      probableCause: 351
      key: MOC004
      source: CPRO

We want to make sure that some fields in labels section be mandatory, so on the side of alertmanager, we like to check the validation of HTTP POST request whether these mandatory fields are contained or not. 

So our proposal is liking as below:
   Based on the common library prometheus/common/alert (https://github.com/prometheus/common/blob/master/model/alert.go ), one new class, liking customizedAlert inheriting from alert, which can add some schema checking, is developed. And adopting this new class in Alertmanager code.

Can you evaluate the above approach is right direction? And the new code developed by us can be acceptable by community?

**What did you expect to see?**

**What did you see instead? Under which circumstances?**

**Environment**

* System information:

	insert output of `uname -srm` here

* Alertmanager version:

	insert output of `alertmanager --version` here

* Prometheus version:

	insert output of `prometheus -version` here (if relevant to the issue)

* Alertmanager configuration file:
```
insert configuration here
```

* Prometheus configuration file:
```
insert configuration here (if relevant to the issue)
```

* Logs:
```
insert Prometheus and Alertmanager logs relevant to the issue here
```

**Comment by brian-brazil** [comment]
A better way of approaching this would be pre-submit checks on your Prometheus rules files.

**Comment by roidelapluie** [comment]
Hello,

We have a tool in house that is doing pre check (with ansible validate: parameter.)

I do not think that this should be alertmanager's job.

**Comment by stuartnelson3** [comment]
As stated by the others, it makes sense to have the validation done when writing the rules files. If the validation is done in alertmanager, the incorrect alert format will only be detected when the alert is firing. Validating as a pre-check will catch any issues immediately, instead of at an indeterminate time (and when you probably want to be notified).
