### ISSUE TITLE
How do you set up alert rules using helm?

### ISSUE THREAD

**Issue by PatSheaFalcon** [prometheus/alertmanager#1681]
I am deploying prometheus using helm. How can I add and modify alert rules using prometheus with helm?

**Comment by juliusv** [comment]
Hi, please note that our issue template states:

> Please do *NOT* ask usage questions in Github issues.
>
> If your issue is not a feature request or bug report use:
> https://groups.google.com/forum/#!forum/prometheus-users. If
> you are unsure whether you hit a bug, search and ask in the
> mailing list first.
>
> You can find more information at: https://prometheus.io/community/

Please be aware though that this seems to be a question not about Alertmanager itself, but about how to deploy it using Helm. Unfortunately, this will depend on the exact Helm chart you are using, and we (Prometheus team) have little or no involvement with Helm charts for Prometheus/Alertmanager.
