### ISSUE TITLE
Allow negative (re) matching in silences

### ISSUE THREAD

**Issue by juliusv** [prometheus/alertmanager#1682]
Similar to https://github.com/prometheus/alertmanager/issues/1023, but for silences.

Currently you can only have `=` and `=~` matchers in silences. I recently wanted to silence all jobs from a given Prometheus server *except* for some specific ones, and being able to do a negative regex match would have been useful there, especially since RE2 doesn't support negative lookaheads.

**Comment by geekodour** [comment]
Hi @juliusv I'd like to work on this, if it's not a high priority issue.
Will implementing `!~` is what we want here, so that the command could work?
```
$ amtool silence add job !~".+exporter" instance="someinstance"
```

**Comment by juliusv** [comment]
@geekodour Awesome!

I was actually talking about the web UI, but then of course `amtool` should support it as well. I haven't talked to any of the Alertmanager maintainers yet whether there is a fundamental reason why we don't support this yet (can't think of any), but this would probably be good to check first.

**Comment by roidelapluie** [comment]
I think getting it implemented at the UI level will be difficult and plenty of discussions, whereas getting it done at amtool level should be straightforward.

**Comment by stuartnelson3** [comment]
>I haven't talked to any of the Alertmanager maintainers yet whether there is a fundamental reason why we don't support this yet (can't think of any), but this would probably be good to check first.

I think this is most likely an artifact of the original implementation, which only supported direct or regex matches.

Adding this to `amtool` should be straightforward, as we already have the `!~` and `!=` concept from prometheus. How to handle this in the ui would (to me) be more a question of what makes most sense for selecting it. Maybe a simple dropdown is enough?

**Comment by juliusv** [comment]
@stuartnelson3 A `==` / `!=` / `=~` / `!~` dropdown between the label name and label value would make sense to me as a first step. Then you could get rid of the regex checkbox to the right.

**Comment by geekodour** [comment]
@juliusv working on this PR
It seems the following documented syntax does not work too:
https://github.com/prometheus/alertmanager/blob/cfc0d9c55882dd501ec881ebe4606cf8d78bf8b6/cli/silence_add.go#L61-L64

will it be fine if add this into the same PR?

**Comment by stuartnelson3** [comment]
bah, it appears that got dropped at some point. I added it back to `amtool alert query` in https://github.com/prometheus/alertmanager/pull/1575.

It should (hopefully) a quick change, I guess just make sure it's in a separate commit in the PR.

**Comment by geekodour** [comment]
@stuartnelson3 

I added it(will send the PR soon), but I think the following documentation does not match with the use:
(this part is repeated in multiple files)
https://github.com/prometheus/alertmanager/blob/cfc0d9c55882dd501ec881ebe4606cf8d78bf8b6/cli/silence_add.go#L63-L64

the following align with the documentation:
```
$ ./amtool silence query foo
is same as
$ ./amtool silence query alertname=foo

and

$ ./amtool silence query ~foo
is same as
$ ./amtool silence query alertname=~foo
```
the following does **not** align with the documentation:
```
$ ./amtool silence query =~foo
amtool: error: bad matcher format: alertname==~foo

and

$ ./amtool silence query =foo
amtool: error: bad matcher format: alertname==foo
```
So, even if the first argument does contain `=` or `~=` it will be assumed to be the value of the alertname pair. Also there is no check for if `alertname` pair is present or not.

I think the correct documentation will be:
```
If the first argument does not contain a key then it will be assumed to
be the value of the alertname pair. 
```

**Comment by geekodour** [comment]
@juliusv 
I think for adding negative (re) matching in silences the proto files will need changes. I tried generating the proto files, but it generates a lot of new things in the generated file.

I just wanted to add two new enum values. I am using the protoc version 3.5.1 I've no experience with protocol buffer but I guess the files generated should have been similar except minor changes.

is this correct?

https://github.com/prometheus/alertmanager/blob/7078333202f37577d2549aa7e223f6eb98a2d9d1/cli/utils.go#L159-L173

https://github.com/prometheus/alertmanager/blob/7078333202f37577d2549aa7e223f6eb98a2d9d1/types/match.go#L27-L33

https://github.com/prometheus/alertmanager/blob/7078333202f37577d2549aa7e223f6eb98a2d9d1/api/v1/api.go#L706-L710

https://github.com/prometheus/alertmanager/blob/7078333202f37577d2549aa7e223f6eb98a2d9d1/silence/silencepb/silence.proto#L14-L20

**Comment by geekodour** [comment]
@juliusv I used `make proto` the diff after running `make proto` looks like this: http://dpaste.com/2Z03ET4

**Comment by juliusv** [comment]
@geekodour Hmm, this is what the diff looks like for me when I don't change anything else in Alertmanager: https://gist.github.com/juliusv/033a489a93c118be9184457c44b9cc63

I installed protoc 3.5.1 from https://github.com/protocolbuffers/protobuf/releases/tag/v3.5.1 and used that... not sure where the extra `XXX` methods and fields are coming from in your case, or whether they would even be a problem, but best to minimize changes of course.

**Comment by geekodour** [comment]
@juliusv the different output of `make proto` should be fixed by #1707 once it gets merged, can continue working on this.

**Comment by juliusv** [comment]
@geekodour That one is merged now, sounds good!

**Comment by geekodour** [comment]
@juliusv I've added this to amtool but facing some issues with elm ui, once I resolve that will send the PR.

**Comment by mxinden** [comment]
@geekodour let me know if you need help with elm.

**Comment by QuentinBisson** [comment]
Is there any feature missing that prevents the crafting of a new 0.22.0 release of alertmanager supporting negative matching in silences that I could help with?

**Comment by beorn7** [comment]
Oops. This issue was auto-closed, but it should not have. Reopening…

**Comment by beorn7** [comment]
In [a review comment](https://github.com/prometheus/alertmanager/pull/2456#issuecomment-764601932), I enumerated what's still missing. To summarize, while the "backend" supports silences with negative matchers now, we still have to amend the following "frontend" components:
1. The web UI (requires to code Elm).
2. The v2 API (to actually create and retrieve silences with negative matchers).
3. `amtool` (to handle silences with negative matchers with this tool).

Help is appreciated, but whoever wants to help should probably first talk to @vladimiroff because I suspect he is already working on the items above.

**Comment by vladimiroff** [comment]
Sorry, got carried away. I suspect most of that work outlined above could be cherry-picked from #2448 as `labels.Matcher` is not **that** different from the now deleted `types.Matcher`. Especially when it comes to the API.

I will try to allocate some time for it and prepare a PR tomorrow. You should be fairly suspicious about my changes in the UI there, though. Did the bare minimal to pass the CI checks and nothing more than that. Help there would be highly appreciated.

**Comment by beorn7** [comment]
Great. Looking forward to the PR.

I would imagine the silence selectors should look similar in the UI to the filters we have right now on the alerts page (they use the same `labels.Matcher` behind the scenes).

Also note that, ideally, we want old deep links to still work. (Many users have created tooling that creates a link sending you to the "create silence" page with all fields filled in.)

**Comment by beorn7** [comment]
Got again auto-closed but still not quite done.

We still need the UI part to be done, now in @w0rm's able hands.

**Comment by w0rm** [comment]
@beorn7 didn't take too long to implement 😛  

I went through different scenarios and ensuring that the form is populated correctly. But another pair of 👀 to check the UI would be helpful! The affected scenarios are:

* creating from a link
* creating from the alerts page
* updating an existing silence
* recreating an expired silence
* validation behavior — two cases, when creating with empty matchers, and when there is an incomplete matcher in the input field.

**Comment by QuentinBisson** [comment]
Thanks @w0rm @vladimiroff and @beorn7 for pushing this PR forward 🎉

**Comment by QuentinBisson** [comment]
@beorn7 do you know if there is a plan to release 0.22 to release this?

**Comment by roidelapluie** [comment]
We are working on the last pull request, https://github.com/prometheus/alertmanager/pull/2481 then we can bootstrap a release.

**Comment by QuentinBisson** [comment]
Thank you @roidelapluie

**Comment by QuentinBisson** [comment]
@roidelapluie now that https://github.com/prometheus/alertmanager/pull/2481 is merged, would it make sense to bootstrap 0.22 or is there some other PR that needs to be worked on that I could help with?

**Comment by roidelapluie** [comment]
The acceptance tests are failing with go1.16. This is now the last thing in the way.

```
~/dev/alertmanager/test/with_api_v2/acceptance $ go test . -run TestRetry -count 1
```

**Comment by QuentinBisson** [comment]
I did got it running fine on my machine using go1.16.3 linux/amd64

Is it failing for a specific golang version?

**Comment by QuentinBisson** [comment]
I have it running locally using go1.16.3.linux-amd64
For which go version is it failing so I could try to help the investigation?

**Comment by roidelapluie** [comment]
It is flapping, you need to run multiple times to see the failure.

**Comment by bilalcaliskan** [comment]
is it possible to add that negative match silence over Alertmanager UI or i must use amtool instead?

**Comment by roidelapluie** [comment]
It is possible with the UI.

**Comment by oalimerko** [comment]
using amtool v0.22 i am able to use negative re-matching,so i can mute all alerts except "test" using this command

`amtool silence add alertname!="test" --alertmanager.url http://127.0.0.1:9093/ -c test -d 2h`

Can i achive the same thing via API Call?This is how my payload looks like:

`  curl -X 'POST' 'https://'$url'/alertmanager/api/v2/silences' \
   -H 'Authorization: Basic *' \
   -H 'accept: application/json' \
   -H 'Content-Type: application/json' \
   -d '{
     "matchers": [
       {
        "name": "alertname",
        "value": "what should i put here?", 
        "isRegex": true
       }
     ],
     "startsAt": "'$StartTime'",
     "endsAt": "'$EndTime'",
     "createdBy": "Pipelines",
     "comment": "This Silence was created automatically by Pipelines via AM API."
    }'`

**Comment by juliusv** [comment]
@oalimerko `amtool` also just uses the same API. If I execute your `amtool` command line and look at what it sends on the wire, I get this JSON object:

```json
{"comment":"test","createdBy":"julius","endsAt":"2022-05-21T20:40:50.004Z","matchers":[{"isEqual":false,"isRegex":false,"name":"alertname","value":"test"}],"startsAt":"2022-05-21T18:40:50.004Z"}
```

**Comment by oalimerko** [comment]
@juliusv how can i look what this `amtool` command sends?

`amtool silence query --alertmanager.url http://127.0.0.1:9093/`

`amtool` shows only active silence in AM which is good.API Call shows all silences(actice + expired).I was thinking what payload does `amtool` sends for filtering the result

**Comment by juliusv** [comment]
> how can i look what this amtool command sends?

I used the open-source packet sniffer [Wireshark](https://www.wireshark.org/) for that and sniffed on the `lo` interface while running `amtool` against a localhost Alertmanager.
