### ISSUE TITLE
AlertManager still send alerts when prometheus crashed

### ISSUE THREAD

**Issue by beijiaxu** [prometheus/alertmanager#1690]
**What did you do?**
When prometheus service crashed, AlertManager will send alerts to my system, such as alert instance state with up metric

**What did you expect to see?**
I don't want AlertManager to send alerts when prometheus is crashed, for my several instances were still running well.

**What did you see instead? Under which circumstances?**

**Environment**

* System information:

	insert output of `uname -srm` here

* Alertmanager version:

	0.15.2
* Prometheus version:

	2.1.0

**Comment by simonpasquier** [comment]
I'm not sure to understand what is your problem. You are free to define whatever alerts make sense for you.

I'm closing it for now. If you have further questions, please use our [user mailing list](https://groups.google.com/forum/#!forum/prometheus-users), which you can also search.
