### ISSUE TITLE
Recreating a silence unchecks "Regex" checkboxes

### ISSUE THREAD

**Issue by beorn7** [prometheus/alertmanager#1695]
**What did you do?**

Recreated an expired silence with a regexp matcher.

**What did you expect to see?**

A recreated silence with regexp matchers.

**What did you see instead? Under which circumstances?**

All the "Regex" checkboxes that should be checked are unchecked.

**Environment**

* System information:

	Linux 4.4.10+soundcloud x86_64

* Alertmanager version:

	alertmanager, version 0.15.2 (branch: HEAD, revision: d19fae3bae451940b8470abb680cfdd59bfa7cfa)
	  build user:       root@3101e5b68a55
	  build date:       20180814-10:53:39
	  go version:       go1.10.3

**Comment by stuartnelson3** [comment]
Confirmed. The issue appears to be that we're turning the matchers from a silence into a list of name/value tuples, and then assuming that it is a direct match:

https://github.com/prometheus/alertmanager/blob/7ff1a618c63da83ad8dd6cbb2dea70aae6680c65/ui/app/src/Views/SilenceList/SilenceView.elm#L104-L105
https://github.com/prometheus/alertmanager/blob/7ff1a618c63da83ad8dd6cbb2dea70aae6680c65/ui/app/src/Views/SilenceForm/Parsing.elm#L14

Should be fairly easy to fix this.

**Comment by beorn7** [comment]
Verified that this is fixed in 0.16.0-beta.0
