### ISSUE TITLE
PagerDuty 400 BadRequest for Alerts with len(summary)>1024

### ISSUE THREAD

**Issue by sbueringer** [prometheus/alertmanager#1700]
**What did you do?**
Alert with too long description was pushed to Alertmanager.

**What did you expect to see?**
Alert should have been pushed to PagerDuty.

**What did you see instead? Under which circumstances?**
We got 400 BadRequest (log: "unexpected status code 400").

Hi,
we had an issue with our Alerts which are routed from Prometheus to Alertmanager to Pagerduty. We used a template for the summary field, which in some cases lead to summaries with more than 1024 characters, which isn't supported by PagerDuty (https://v2.developer.pagerduty.com/docs/send-an-event-events-api-v2). Unfortunatley, this wasn't directly visible to us and can only be detected by monitoring the Alertmanager log file. The result was that we just missed the Alerts.

I think it would be a good idea to trim the summary to 1024 characters (e.g. like this https://github.com/c445/alertmanager/blob/2808c2851995a0db7e57d9b8f5bc5fbd986514f9/notify/impl.go#L526-L539) before sending the Alert to Pagerduty. Also I think it would be nice to have a few debug log statements in this area, because there was no way without changing the source code & recompiling to find out the response body from Pagerduty.

If it's ok for you, I can open a PR to address this issue.

**Comment by stuartnelson3** [comment]
Opening a PR sounds great, looking forward to it!

**Comment by gouthamve** [comment]
We're still seeing this on `0.17.0`:
```
level=error ts=2019-06-10T14:52:29.294545153Z caller=notify.go:339 component=dispatcher msg="Error on notify" err="cancelling notify retry for \"pagerduty\" due to unrecoverable error: Event object is invalid: Description is too long (maximum is 1024 characters)"
```

Not sure what's wrong though. Can we reopen?

**Comment by simonpasquier** [comment]
@gouthamve got non-ASCII characters in the description?

**Comment by stuartnelson3** [comment]
The docs only say "characters", so I'm not sure if they actually mean "bytes". I'm guessing they mean "bytes", if we're running into this issue still. Guess we should include tests for all these trim functions we're adding.

**Comment by simonpasquier** [comment]
Hmm, I tried to reproduce (it happens that you can post to the PagerDuty API with any random routing key and get a 200 if the payload is valid!) but couldn't. When I modify the code to not truncate the description field at 1024 characters, the Pager Duty API returns the same error as you pasted.

**Comment by simonpasquier** [comment]
Ah you're probably using the v1 API @gouthamve, right?
