### ISSUE TITLE
Inconsistency in generation of .proto files

### ISSUE THREAD

**Issue by geekodour** [prometheus/alertmanager#1702]
I tried generating `.proto` files using `make proto`

It generated files with a lot of differences as discussed in #1682 and the helpful top comment also got removed. (gist attached)

As alertmanager uses the gogo/protobuf implementation, 

from the gogo/protobuf readme
```
protoc-gen-gogofast (same as gofast, but imports gogoprotobuf)
protoc-gen-gogofaster (same as gogofast, without XXX_unrecognized, less pointer fields)
protoc-gen-gogoslick (same as gogofaster, but with generated string, gostring and equal methods)
```
and `genproto.sh` uses `gogofast`
https://github.com/prometheus/alertmanager/blob/dba283edd0d05c6a295b6b5c63bc1bb692f7683d/scripts/genproto.sh#L30

so it is supposed to generate the `XXX_unrecognized` when using `gogofast` but the files in `master` do not show any `XXX_unrecognized` 

**What did you do?**
```
- Install protoc`v3.5.1`
- go install github.com/gogo/protobuf/protoc-gen-gogo
- go install github.com/gogo/protobuf/protoc-gen-gogofast
- go get github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway
- go get golang.org/x/tools/cmd/goimports
```

I even tried installing downto `v0.4` of gogo/protobuf for `protoc-gen-gogo` 

**What did you expect to see?**
What @juliusv generated,
diff: https://gist.github.com/juliusv/033a489a93c118be9184457c44b9cc63

**What did you see instead? Under which circumstances?**
`make proto`
diff: https://gist.github.com/geekodour/52ae6d8283996b88c064526f97aafdcf

**Environment**
* System information:
Linux 4.13.9-300.fc27.x86_64 x86_64
* Alertmanager version:
master

cc: @fabxc @juliusv

**Comment by simonpasquier** [comment]
This is because `scripts/genproto.sh` doesn't lock down the versions of its dependencies. Eventually we need to implement the same mechanism as https://github.com/prometheus/prometheus/pull/5075.
