### ISSUE TITLE
APIv2 openapi.yaml does not match implementation

### ISSUE THREAD

**Issue by bjornl** [prometheus/alertmanager#1703]
The API definition for interface Silence->Post in the Swagger OpenAPI definition file api/v2/openapi.yaml is missing "status": { "state": "active" }

I don't know if this is intentional, but currently the implementation in master branch does not work together with the autogenerated API stubs from openapi.yaml

**What did you do?**

Used a Swagger OpenAPI API generator to create API call from the OpenAPI definition file.

http://petstore.swagger.io/

**What did you expect to see?**

Working API call to create new Silence using the v2 API, like a curl API-call command.

**What did you see instead? Under which circumstances?**

400 response code failure from AlertManager.

**Environment**

Official Docker image daily build of master branch.

Branch: master
BuildDate: 20190109-10:09:42
BuildUser: root@2932cc93399d
GoVersion: go1.11.4
Revision: dba283edd0d05c6a295b6b5c63bc1bb692f7683d
Version: 0.16.0-alpha.0

* System information:

Kubernetes v1.11.2

* Alertmanager version:

master dba283edd0d05c6a295b6b5c63bc1bb692f7683d

**Comment by mxinden** [comment]
Hi @bjornl,

Thanks for testing the new API.

The silence state is based on the start and end time. This is probably best explained with the following go snipped:

https://github.com/prometheus/alertmanager/blob/dba283edd0d05c6a295b6b5c63bc1bb692f7683d/types/types.go#L397-L406

Hence there should be no reason why you would provide both start, end and state, as the latter is based on the former.

Is this of any help for you?

**Comment by bjornl** [comment]
Yes, you are right, my bad. I did test API injection of this silence the previous week and then it did fail for me. Today it is working correctly as it should. Close this ticket.

```
curl -H  "accept: application/json" -H  "Content-Type: application/json" http://kube1:32002/api/v2/silences -d '{
      "matchers": [
        {
          "name": "alername1",
          "value": ".*",
          "isRegex": true
        }
      ],
      "startsAt": "2019-01-13T22:12:33.533330795Z",
      "endsAt": "2019-01-23T23:11:44.603Z",
      "createdBy": "example",
      "comment": "Example"
}'
```
