### ISSUE TITLE
Don't force .generatorURL to open the "Console" tab

### ISSUE THREAD

**Issue by lilred** [prometheus/alertmanager#1715]
**What did you do?**

I have a Slack integration that uses `{{ .GeneratorURL }}` to link to a graph.

**What did you expect to see?**

I expected the relevant URL to lend itself to appending parameters, for example adding `&g0.tab=0` to link to the "Graph" tab in the Prometheus web interface.

**What did you see instead? Under which circumstances?**

The generated URL has `&g0.tab=1` at the end of it. It's not possible to override that by adding another parameter after.

**Environment**

* System information:

`Linux 3.10.0-862.14.4.el7.x86_64 x86_64`

* Alertmanager version:

```
alertmanager, version 0.15.1 (branch: HEAD, revision: 8397de1830f154535a31150f9262da0072d8725d)
  build user:       root@efde7f9485ae
  build date:       20180712-18:25:27
  go version:       go1.10.3
```

* Prometheus version:

```
prometheus, version 2.4.0 (branch: HEAD, revision: 068eaa5dbfce6c08f3d05d3d3c0bfd96267cfed2)
  build user:       root@d84c15ea5e93
  build date:       20180911-10:46:37
  go version:       go1.10.3
```

**Comment by simonpasquier** [comment]
`GeneratorURL` isn't created by AlertManager so https://github.com/prometheus/prometheus/pull/5115 is more relevant. As a workaround, you could modify it in the receiver template:

```
... {{ .GeneratorURL | reReplaceAll "&g0.tab=1$" "&g0.tab=0" }} ...
```

I'm closing it for now. If you have further questions, please use our [user mailing list](https://groups.google.com/forum/#!forum/prometheus-users), which you can also search.

**Comment by roidelapluie** [comment]
Note that in general we should avoid opening the graph panel, especially if the query is huge, getting the last hour could crash Prometheus.
