### ISSUE TITLE
Add receiver label to alertmanager_notifications_* metrics

### ISSUE THREAD

**Issue by dkalashnik** [prometheus/alertmanager#1720]
Hi.

In our configuration we are using multiple receivers per couple of integrations. Mainly webhook. But from the alertmanager_notifications_* metrics we can't define exact receiver.
It would be helpful to have `receiver` label among with `integration`.

**Comment by mxinden** [comment]
The only issue I can see with this is the cardinality explosion for people with many receivers. What are thoughts by others?

**Comment by brian-brazil** [comment]
Yes, that's exactly why we didn't add this label. There could be thousands.

**Comment by simonpasquier** [comment]
Hi Dima! Closing this issue as it could potentially lead to cardinality explosion.
