### ISSUE TITLE
Limit number of concurrent GET API requests

### ISSUE THREAD

**Issue by beorn7** [prometheus/alertmanager#1723]
Expensive API calls could easily take out Alertmanager. 

Scenario: Everything is on fire, millions of alerts, and hundreds of engineers in the company want to look at the AM UI. The default landing page returns all the alerts (which is kind of an issue on its own), leading to an extreme load to server the UI.

The most important task of AM is to deliver alerts. Thus, it makes sense to limit the number of concurrently processed API request. It should have a reasonable default, and it should be configurable. We have similar things in place for the Prometheus server. Studying those can server as a source of inspiration. (Although I doubt we want to queue API requests (like we queue PromQL queries). Instead, just return a 503 with a meaningful errar message.)

This becomes even more pressing if we update the silenced/inhibited state upon API calls as suggested in #979 .

**Comment by beorn7** [comment]
Yes, this is meant to be the inquiry part, and not the "production path". I made this explicit in the title.

**Comment by jdelvecchio** [comment]
>  It should have a reasonable default, and it should be configurable
What's it default and how is it configurable ? I don't see any reference to this new parameter on the documentation here https://prometheus.io/docs/alerting/configuration/

Currently experiencing issues with the limit and would like to be able to configure it

**Comment by beorn7** [comment]
It's a command line flag, try `alertmanager --help`.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a closed(!) GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
