### ISSUE TITLE
Prometheus alertmanager binary for s390x

### ISSUE THREAD

**Issue by Nayana-ibm** [prometheus/alertmanager#1735]
I could see there are binaries available for Prometheus and Prometheus node exporter for s390x arch .
Is there any plan to upload binary for alertmanager? 
Link: https://prometheus.io/download/

**Comment by mxinden** [comment]
I think there was no demand for `s390x` so far. If there are no objections by others feel free to create a pull request adding `linux/s390x` to the `.promu.yml` of this project (See [example](https://github.com/prometheus/prometheus/blob/master/.promu.yml#L53)).

Support for `s390x` would be on a best effort basis.

**Comment by Nayana-ibm** [comment]
@mxinden Thanks for quick response. Will work on this and create a pull request
