### ISSUE TITLE
Alert Manager text mail not working

### ISSUE THREAD

**Issue by mmuehlbeyer** [prometheus/alertmanager#1737]
Hi,

Alert Manager does not send plaint text mails.
even if everything is configured as described in the docs.

Kind regards,
Michael

**Comment by simonpasquier** [comment]
Please provide more details like AlertManager version, configuration and logs.

**Comment by mmuehlbeyer** [comment]
config is like
alertmanager.yml:
[...]
templates:
- '/etc/alertmanager/*.tmpl'

route:
  group_by: ['instance', 'severity']
  group_wait: 30s
  group_interval: 15s
  repeat_interval: 500s
  receiver: team-tvd

receivers:
  - name: 'team-tvd'
    email_configs:
      - to: 'a...@test.com
        text: '{{ template "email.cloud.text" . }}'

cloud.tmpl
{{ define "email.gmdm.text" }}
{{"\"just a plaintext mail \""}}
{{ end }}

**Comment by mmuehlbeyer** [comment]
alertmanager version is 0.16.0

**Comment by mmuehlbeyer** [comment]
sorry copy issue  

cloud.tmpl
{{ define "email.cloud.text" }}
{{"\"just a plaintext mail \""}}
{{ end }}

**Comment by mmuehlbeyer** [comment]
hi, 
fixed by myself 
[...]
html: null
text: '{{ template "email.cloud.text" . }}'
[...]
did the trick
