### ISSUE TITLE
yaml Marshal/Unmarshal adds regexp anchors

### ISSUE THREAD

**Issue by miekg** [prometheus/alertmanager#1753]
If you use the go library `github.com/prometheus/alertmanager/config` and then read in the configuration using `LoadFile` and then write it out again, the regular expressions are anchored. This means you can not faithfully write back the original file contents.

Example:
~~~
route:
    receiver: 'sre:bla:foo'
    routes:
        - receiver: 'sre:bla:foo-mail'
          match_re:
            job: 'sre:bla:bar-.*'
~~~

becomes via a `LoadFile` and `Marshal`:

~~~
route:
  receiver: sre:bla:foo
  routes:
  - receiver: sre:bla:foo-mail
    match_re:
      job: ^(?:sre:bla:bar-.*)$
~~~

The version used is: `b63b5600741b07795e50cedf8818a853bacc5f76`.

Now when *alertmanager* reads this ouput again; it will *again* add these anchors.

Is this WAI? Or can I prepare a PR to not add these anchors when reading/writing out these configs.

**Comment by miekg** [comment]
yes, `config.go` has
~~~
// UnmarshalYAML implements the yaml.Unmarshaler interface.
func (re *Regexp) UnmarshalYAML(unmarshal func(interface{}) error) error {
        var s string
        if err := unmarshal(&s); err != nil {
                return err
        }
        regex, err := regexp.Compile("^(?:" + s + ")$")
        if err != nil {
                return err
        }
        re.Regexp = regex
        return nil
}

// MarshalYAML implements the yaml.Marshaler interface.
func (re Regexp) MarshalYAML() (interface{}, error) {
        if re.Regexp != nil {
                return re.String(), nil
        }
        return nil, nil
}
~~~
Where `return re.String()` needs to be make slighty smarter I think. Maybe as lame as:
~~~
return re.String()[4:len(re.String())-2]
~~~

**Comment by mxinden** [comment]
> If you use the go library `github.com/prometheus/alertmanager/config`

In general this is not intended to be used as a library. It should have probably better been placed into an [`internal`](https://docs.google.com/document/d/1e8kOo3r51b2BWtTs_1uADIA5djfXhPT36s6eHVRIvaU/edit#!) folder.

This does not mean we do not accept any contributions, just that we can not give any stability guarantees.

Before talking about technical solutions, would you mind elaborating on your use case a bit more?

**Comment by miekg** [comment]
> Before talking about technical solutions, would you mind elaborating on your use case a bit more?

We're running a system that takes other people's alertmanager.yaml's, syntax checks them (hence the use of this library) and output a larger, merged alertmanager.yaml.

I can treat the yaml as a blackbox or implement a minimal structure to parse it, but it seems better to use the official code, so any format upgrades are (somewhat) automatic. 

This all works pretty well, except for the `match_re` output.

**Comment by simonpasquier** [comment]
Side-note: some fields are declared as `Secret` so the unmarshaled -> marshaled data isn't exactly the same as the raw YAML. But I guess you're mostly concerned with the `routes` configuration that don't contain secret data (yet?).

**Comment by miekg** [comment]
Indeed. This is all considered public and limited in what can be configured.

**Comment by simonpasquier** [comment]
@mxinden and @stuartnelson3 have the final word but the request looks reasonable to me.
Regarding the implementation, we can use the same technique as in [`github.com/prometheus/prometheus/pkg/relabel`](https://github.com/prometheus/prometheus/blob/37e35f9e0cb3ea4452fec8dcf5f26cdedcc16b4c/pkg/relabel/relabel.go#L131-L168)

**Comment by miekg** [comment]
Ok, that makes sense. I'll prepare a PR; we can discuss merging that (nor not).

As a fallback I can fork the code and just change it for my use-case.

**Comment by miekg** [comment]
` service_key: <secret>` is biting here as well, but that obviously begs the question if you should put those things in version control at all
