### ISSUE TITLE
Prometheus in IPv6 Kubernetes environment (too many colons in address)

### ISSUE THREAD

**Issue by lefranco6910** [prometheus/alertmanager#1756]
**What did you do?**

Prometheus deployment in an IPv6 Kubernetes environment

**What did you expect to see?**

All pods up and running

**What did you see instead? Under which circumstances?**

root@k8s-1:~# kubectl get pods
NAME                                             READY   STATUS             RESTARTS   AGE
network-utils                                    1/1     Running            0          15h
prometheus-alertmanager-59b955578d-9sgmv         1/2     CrashLoopBackOff   8          18m
prometheus-kube-state-metrics-68cfd7cbd9-cjb8d   1/1     Running            0          18m
prometheus-node-exporter-k7c22                   1/1     Running            0          18m
prometheus-pushgateway-c69c6db-6ckwp             1/1     Running            0          18m
prometheus-server-7889d59bc6-rq224               2/2     Running            0          18m

**Environment**

* System information:

	root@k8s-1:~# uname -srm
        Linux 4.15.0-45-generic x86_64

* Alertmanager version:

    root@k8s-2:~# docker image ls | grep alert
    prom/alertmanager                       v0.15.3             ed72e25b3d20        3 months ago        34.5MB

* Prometheus version:

    root@k8s-2:~# docker image ls | grep prom
    prom/prometheus                         v2.6.1              5517f7057e72        3 weeks ago         97.8MB
    prom/node-exporter                      v0.17.0             b3e7f67a1480        2 months ago        21MB
    prom/alertmanager                       v0.15.3             ed72e25b3d20        3 months ago        34.5MB
    prom/pushgateway                        v0.6.0              3a612a2371e5        3 months ago        16.5MB

* Alertmanager configuration file:
```
N/A
```

* Prometheus configuration file:
```
N/A
```

* Logs:
```
root@k8s-1:~# kubectl logs prometheus-alertmanager-59b955578d-9sgmv prometheus-alertmanager
    level=info ts=2019-02-12T18:49:54.825102019Z caller=main.go:174 msg="Starting Alertmanager" version="(version=0.15.3, branch=HEAD, revision=d4a7697cc90f8bce62efe7c44b63b542578ec0a1)"
    level=info ts=2019-02-12T18:49:54.825166364Z caller=main.go:175 build_context="(go=go1.11.2, user=root@4ecc17c53d26, date=20181109-15:40:48)"
    level=error ts=2019-02-12T18:49:54.825192019Z caller=main.go:199 msg="unable to initialize gossip mesh" err="invalid advertise address: address fd00:acdc::112:6783: too many colons in address"
```

**Comment by lefranco6910** [comment]
Apparently, the software works better after modifying the Helm charts for IPv6 addressing. This is a workaround, not a fix:

root@k8s-1:~/tmp/prometheus/templates# grep cluster.adver *
alertmanager-deployment.yaml:            - --cluster.advertise-address=[$(POD_IP)]:6783
alertmanager-statefulset.yaml:            - --cluster.advertise-address=[$(POD_IP)]:6783

root@k8s-1:~# kubectl get pods
NAME                                             READY   STATUS    RESTARTS   AGE
prometheus-alertmanager-7c5586b978-kcfj6         2/2     Running   0          3m27s
prometheus-kube-state-metrics-68cfd7cbd9-7xvpp   1/1     Running   1          3m27s
prometheus-node-exporter-6q9j5                   1/1     Running   0          3m27s
prometheus-pushgateway-c69c6db-2ngpb             1/1     Running   0          3m27s
prometheus-server-7889d59bc6-xklsc               2/2     Running   0          3m27s

root@k8s-1:~# kubectl logs prometheus-alertmanager-7c5586b978-kcfj6 prometheus-alertmanager
level=info ts=2019-02-12T19:16:59.996586381Z caller=main.go:174 msg="Starting Alertmanager" version="(version=0.15.3, branch=HEAD, revision=d4a7697cc90f8bce62efe7c44b63b542578ec0a1)"
level=info ts=2019-02-12T19:16:59.996648911Z caller=main.go:175 build_context="(go=go1.11.2, user=root@4ecc17c53d26, date=20181109-15:40:48)"
level=info ts=2019-02-12T19:16:59.999005479Z caller=main.go:322 msg="Loading configuration file" file=/etc/config/alertmanager.yml
level=info ts=2019-02-12T19:17:00.00122966Z caller=cluster.go:570 component=cluster msg="Waiting for gossip to settle..." interval=2s
level=info ts=2019-02-12T19:17:00.003411708Z caller=main.go:398 msg=Listening address=:9093
level=info ts=2019-02-12T19:17:02.001496606Z caller=cluster.go:595 component=cluster msg="gossip not settled" polls=0 before=0 now=1 elapsed=2.000134742s
level=info ts=2019-02-12T19:17:10.002215815Z caller=cluster.go:587 component=cluster msg="gossip settled; proceeding" elapsed=10.000876165s

**Comment by simonpasquier** [comment]
It looks like a problem with the Helm chart then? From the Go [documentation](https://golang.org/pkg/net/#Dial):

> If the host is a literal IPv6 address it must be enclosed in square brackets, as in "[2001:db8::1]:80" or "[fe80::1%zone]:80"

**Comment by lefranco6910** [comment]
Sorry. I forgot to reply. Yes, it appears the Helm charts need to find a way to support both IPv4 and IPv6. The problem is not software related. Thanks!
