### ISSUE TITLE
Resolution causes email when an alert is removed from a group

### ISSUE THREAD

**Issue by roidelapluie** [prometheus/alertmanager#1758]
**What did you do?**

- Create an alert , use send_resolved: no
- Add a second alert in the group
- the two alerts are sent in the same mail
- solve one of the alerts

**What did you expect to see?**

- I should have received one mail with the original alerts

**What did you see instead? Under which circumstances?**

- I received 2 mails:
- one mail with two alerts
- another mail with only the remaining alert

**Environment**

* Alertmanager version:

alertmanager, version 0.16.0 (branch: HEAD, revision: 73bdd966e0055f3b828340ade3ef1f3a38169cdc)
  build user:       root@fbea1f55d584
  build date:       20190121-12:58:06
  go version:       go1.11.4

**Comment by brian-brazil** [comment]
To be clear, this was at the group_interval not the repeat_interval?

**Comment by roidelapluie** [comment]
Yes

**Comment by roidelapluie** [comment]
Okay this is not a bug. Actually the event occured twice in a short interval, and the second time only one alert was firing.

**Comment by roidelapluie** [comment]
Sorry :)
