### ISSUE TITLE
custom email template not looping through .Labels.SortedPairs

### ISSUE THREAD

**Issue by CharanBR** [prometheus/alertmanager#1762]
**What did you do?**
using custom email template for one of the receiver like below.
- name: 'servicedesk'
  email_configs:
  - to: 'charan314@gmail.com'
    headers: { 'emailto': servicedesk, 'Subject': 'ALERT TO SRE'}
    html: '{{ template "servicedesk.html" }}'

Template only has some html tags and below lines (% is for service desk to auto translate to an incident)
%CUSTOMER=cmdctr
%CATEGORY=Alert.SRE
%SUMMARY= Alert From Kubernetes
%STATUS=Open
%GROUP=SRE
%DESCRIPTION=
{{ range .Alerts.Firing }}
  {{ range .Labels.SortedPairs }}
    {{ .Name }}, {{ .Value}}
  {{ end }}
{{ end }}
**What did you expect to see?**
receive custom notification with about fields
**What did you see instead? Under which circumstances?**
The description field is empty. I still get the default email template and I can see all the relevant details in them.
**Environment**

* System information:

	Linux 3.10.0-957.1.3.el7.x86_64 x86_64

* Alertmanager version:

  alertmanager, version 0.15.2 (branch: , revision: )
  build user:       mockbuild@x86-037.build.eng.bos.redhat.com
  build date:       20181203-06:10:44
  go version:       go1.10.3

* Prometheus version:

  prometheus, version 2.3.2 (branch: , revision: )
  build user:       mockbuild@x86-037.build.eng.bos.redhat.com
  build date:       20181203-06:09:17
  go version:       go1.10.3

* Alertmanager configuration file:
```
insert configuration here
```

* Prometheus configuration file:
```
insert configuration here (if relevant to the issue)
```

* Logs:
```
insert Prometheus and Alertmanager logs relevant to the issue here
```

**Comment by simonpasquier** [comment]
Could you paste the configuration from the /status page? Could you share the logs too?

**Comment by CharanBR** [comment]
I ran another test today with/without template and I can replicate the issue. This is what happens
.Alerts.Firing is empty if I have a template (like .tmpl file)
It works if I define the template within alertmanager.yaml config file within `html:` key

global:
  resolve_timeout: 5m
  http_config: {}
  smtp_from: myalerts@gmail.com
  smtp_hello: localhost
  smtp_smarthost: gmail.com:25
  pagerduty_url: https://events.pagerduty.com/v2/enqueue
  hipchat_api_url: https://api.hipchat.com/
  opsgenie_api_url: https://api.opsgenie.com/
  wechat_api_url: https://qyapi.weixin.qq.com/cgi-bin/
  victorops_api_url: https://alert.victorops.com/integrations/generic/20131114/alert/
route:
  receiver: email-receiver
  group_by:
  - alertname
  - cluster
  - service
  routes:
  - routes:
    - match_re:
        alertname: ^(?:^(ECOM.*)$)$
      routes:
      - receiver: ecom-servicedesk
        continue: true
        repeat_interval: 52w
      - receiver: ecom-receiver
    - routes:
      - receiver: deadmansswitch
        match:
          alertname: DeadMansSwitch
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1d
inhibit_rules:
- source_match:
    severity: critical
  target_match:
    severity: warning
  equal:
  - alertname
  - cluster
  - service
receivers:
- name: deadmansswitch
- name: email-receiver
  email_configs:
  - send_resolved: true
    to: charan314@gmail.com
    from: myalerts@gmail.com
    hello: localhost
    smarthost: gmail.com:25
    headers:
      Emailto: spe-email
      From: myalerts@gmail.com
      Subject: '{{ template "email.default.subject" . }}'
      To: charan314@gmail.com
    html: '{{ template "email.default.html" . }}'
    require_tls: false
- name: ecom-receiver
  email_configs:
  - send_resolved: true
    to: charan314@gmail.com
    from: myalerts@gmail.com
    hello: localhost
    smarthost: gmail.com:25
    headers:
      Emailto: ecom-engg
      From: myalerts@gmail.com
      Subject: '{{ template "email.default.subject" . }}'
      To: charan314@gmail.com
    html: '{{ template "email.default.html" . }}'
    require_tls: false
- name: ecom-servicedesk
  email_configs:
  - send_resolved: false
    to: charan314@gmail.com
    from: myalerts@gmail.com
    hello: localhost
    smarthost: gmail.com:25
    headers:
      Emailto: ecom-servicedesk
      From: myalerts@gmail.com
      Subject: IN
      To: charan314@gmail.com
    html: '{{ template "ecom.servicedesk.html" }}'
    require_tls: false
templates:
- /etc/alertmanager/config/*.tmpl

**Comment by roidelapluie** [comment]
You miss a "." after the template file. `{{ template "ecom.servicedesk.html" . }}`

**Comment by CharanBR** [comment]
yup missing "." seems to be the problem.

**Comment by nvn227** [comment]
How are you storing this teplate file.

- /etc/alertmanager/config/*.tmpl
