### ISSUE TITLE
Feature request: Silence policies

### ISSUE THREAD

**Issue by sinkingpoint** [prometheus/alertmanager#1769]
As a person who manages a relatively large alertmanager deployment, we have lots of users, all of whom can add silences with reckless abandon. Humans being humans, some of these silences go wrong and end up silencing more than was intended. What I would like to do it define a set of policies that are enforced by alertmanager when adding a silence, not unlike git commit policies. This could allow us to enforce things like proper user settings, proper comments (e.g. all silences must be linked to a JIRA ticket), and the above example - not to broad etc.

In effect, I want to be able to have alertmanager run a set of defined scripts on every silence, with those scripts being able to accept or reject the silence from being applied

**Comment by brian-brazil** [comment]
Authorization and business rules are considered out of scope for the alertmanager. If you want to do this, I'd suggest running a proxy in front of the alertmanager.

**Comment by johnskopis** [comment]
My thinking is that this kind of thing belongs in a middleware. I can certainly appreciate not wanting to complicate alertmanager though. 

Would you be open to a very small change that adds a flag `presubmit-middleware-service`? When set, a very simple middleware would make a grpc request to the service and accept or reject the request based on the response.

**Comment by simonpasquier** [comment]
@johnskopis I don't think that Alertmanager calling an external service when processing an API request is a good idea. If you really need, it shouldn't be too hard to write a proxy that would sit in front of Alertmanager and do the sanitization/authorization (especially since the Alertmanager v2 API has an Open API specification).
