### ISSUE TITLE
Silences sorting in 0.16.1 is not consistent

### ISSUE THREAD

**Issue by nodakai** [prometheus/alertmanager#1781]
**What did you do?**
https://my-alertmgr.example/#/silences
Reload
Reload
Reload...

**What did you see instead? Under which circumstances?**
It's annoying to see silences don't follow a consistent ordering
_Cf._ #812 

**Environment**

* System information:

Linux x86_64

* Alertmanager version:

```
Version Information
Branch:
HEAD
BuildDate:
20190131-15:05:40
BuildUser:
root@3000aa3a06c5
GoVersion:
go1.11.5
Revision:
571caec278be1f0dbadfdf5effd0bbea16562cfc
Version:
0.16.1
```

**Comment by nodakai** [comment]
Just an idea, but it might be nice if we can sort silences by the number of affected alerts

**Comment by pgier** [comment]
@nodakai, can you verify that #1786 fixes the issue?

**Comment by nodakai** [comment]
@pgier Hmm it's a bit difficult to build and install your branch for our system under monitoring...
