### ISSUE TITLE
Api v2: comma no longer allowed in get parameter

### ISSUE THREAD

**Issue by roidelapluie** [prometheus/alertmanager#1783]
**What did you do?**

- Run an empty alertmanager
- Open http://127.0.0.1:9093/api/v2/alerts?silenced=true&inhibited=false&filter=recipient%3Dops%2Fticket%2Cmgmt%2Fsms

**What did you expect to see?**

The query to succeed

**What did you see instead? Under which circumstances?**

Error 400 + "bad matcher format: mgmt/sms"

**Environment**

* System information:

	2 different Linux distros

* Alertmanager version:

```
alertmanager, version 0.16.1 (branch: HEAD, revision: 571caec278be1f0dbadfdf5effd0bbea16562cfc)                                           
  build user:       root@3000aa3a06c5
  build date:       20190131-15:05:40
  go version:       go1.11.5
```

* Alertmanager configuration file:
default

**Comment by mxinden** [comment]
`filter` is defined as a comma separated list: https://github.com/prometheus/alertmanager/blob/master/api/v2/openapi.yaml#L57 thereby your comma is interpreted as an item delimiter. I am not quite sure how to change that. I am happy for suggestions.

**Comment by roidelapluie** [comment]
It did work in v1 :(

Can we accept filter[]= instead for lists?

**Comment by roidelapluie** [comment]
But it means that anyone with , in labels will be impacted.

**Comment by roidelapluie** [comment]
@simonpasquier component/api please

**Comment by roidelapluie** [comment]
@mxinden explode = true might help

**Comment by roidelapluie** [comment]
Because we are using v2, we need:

`collectionFormat: multi`

What do you think of switching to that?

**Comment by roidelapluie** [comment]
Note: https://github.com/prometheus/alertmanager/issues/1393 I am not the only one using commas in label values

**Comment by simonpasquier** [comment]
> Because we are using openapi v2, we need:
> collectionFormat: multi
> What do you think of switching to that?

I came to the same conclusion after reading through the code yesterday...
