### ISSUE TITLE
unable to get mails even client is down

### ISSUE THREAD

**Issue by Dheerajit77** [prometheus/alertmanager#1785]
**What did you do?**

**What did you expect to see?**

**What did you see instead? Under which circumstances?**

**Environment**

* System information:

	insert output of `uname -srm` here

* Alertmanager version:

	insert output of `alertmanager --version` here

* Prometheus version:

	insert output of `prometheus -version` here (if relevant to the issue)

* Alertmanager configuration file:
```
insert configuration here
```

* Prometheus configuration file:
```
insert configuration here (if relevant to the issue)
```

* Logs:
```
insert Prometheus and Alertmanager logs relevant to the issue here
```

**Comment by mxinden** [comment]
Hi there,

We would need a bit more information to help you. In addition this sounds like a usage question which would be best asked on https://groups.google.com/forum/#!forum/prometheus-users

I am closing here, feel free to reopen.
