### ISSUE TITLE
CORS POST method not allowed in API v1

### ISSUE THREAD

**Issue by xdrop** [prometheus/alertmanager#1793]
I'm using Karma which runs on a different domain to Alertmanager and due to the nature of cross-origin requests silences can't be submitted from Karma. (The browser blocks the request)

Is there any reason `POST` is not permitted as an allowed method? Can it be change to include `POST`? (happy to submit a PR for it)
https://github.com/prometheus/alertmanager/blob/c637ca1a6e48cd57c6aee6d8ebf9b24ba484e4cd/api/v1/api.go#L46

**Comment by stuartnelson3** [comment]
Hm, I can't remember. If we're supporting DELETE it seems like POST would also be fine.

@mxinden @simonpasquier any idea why we never added POST?

**Comment by simonpasquier** [comment]
Hmm, I don't know and seems to predate my involvement in the project :smirk:

**Comment by xdrop** [comment]
Sounds good 🙂. PR #1796 submitted

**Comment by mxinden** [comment]
Fixed by https://github.com/prometheus/alertmanager/pull/1796.
