### ISSUE TITLE
opsgenie: Move from not supported  `team` field  to `responders` for alert routing.

### ISSUE THREAD

**Issue by bwplotka** [prometheus/alertmanager#1818]
* Alertmanager version:

	`v0.16.1`

Essentially we used to configure Opsgenie receiver with a `Team` string: https://github.com/prometheus/alertmanager/blob/master/config/notifiers.go#L451

And this is recommended (and only) way to specify the exact Opsgenie team in Alertmananger's receiver: [example](https://www.robustperception.io/using-opsgenie-with-the-alertmanager)

However, teams are not identified by `team`  names in Opsgenie (maybe they used to?)

They are identified by `responder` field: https://docs.opsgenie.com/docs/alert-api#section-create-alert

Which can contain `name` or `id` of the team: https://docs.opsgenie.com/docs/team-api#section-get-team

If you look closely there is literally NO `team` field anymore. So this field is most likely not supported (is used to be?) Is it ignored? It's definitely not documented. I think it works? kind of? looks like it's meant to be deprecated.

We recently had an incident where team renames caused Opsgenie routing to ignore alerts, so we assume it works it's just really bad as `team string` is now display name only. 

IMO this defines Acceptance Criteria: (edited)

* AM user should be able to use official way of referencing exact team for Opsgenie Create alert API: Rename sent field to`responders` from `teams`.
* Allow to reference teams by IDs not only names.

Would you accept PR to fix this?

**Comment by ivan-valkov** [comment]
It looks like we allow for the proper responders format - https://github.com/prometheus/alertmanager/blob/89b0ff05743dbedfdfa8d2433c58ba4d5ddf7202/notify/impl.go#L964

But the fields is still called `teams` not `responders`:
https://github.com/prometheus/alertmanager/blob/89b0ff05743dbedfdfa8d2433c58ba4d5ddf7202/notify/impl.go#L880

**Comment by simonpasquier** [comment]
It seems this was overlooked when switching from the OpsGenie v1 API to v2 (#1061) and it somehow works by accident:
https://docs.opsgenie.com/docs/migration-guide-for-alert-rest-api#section-4-responders-field

**Comment by simonpasquier** [comment]
Also related to #1342

**Comment by bwplotka** [comment]
I am happy to fix this if you are ok with this @simonpasquier

**Comment by simonpasquier** [comment]
@bwplotka sure go ahead. You're more than qualified, especially as an OpsGenie user :smile:

**Comment by arnarg** [comment]
Is there any progress on this?

**Comment by bwplotka** [comment]
Not ): Sorry. Will try to contribute something today/tomorrow. It is on my TODO list.

**Comment by bwplotka** [comment]
https://github.com/prometheus/alertmanager/pull/1863

**Comment by bwplotka** [comment]
We use it already on production, works well :+1:

**Comment by bwplotka** [comment]
Shared `bplotka/alertmanager:v0.17-588b4dd17` docker image if anyone wants to have it before release. @arnarg
