### ISSUE TITLE
alertmanager_cluster_failed_peers reports 1 continuously after pod is respawned

### ISSUE THREAD

**Issue by swapzero** [prometheus/alertmanager#1820]
**What did you do?**
Tested the functionality of `alertmanager_cluster_failed_peers` metric as follows:
- opened a port forward to one of the two alertmanager pods (2 replicas deployment)
- started a loop running `curl http://localhost:9093/metrics` (metric was reporting 0)
- deleted the other pod in the deployment
- watched `alertmanager_cluster_failed_peers` since the `delete` moment to when the second pod was running again...and beyond
Result:
`alertmanager_cluster_failed_peers` stays at 1 value forever

**What did you expect to see?**
Since `alertmanager_cluster_failed_peers` is gauge I would have expected to be back to 0 once the second pod was respawned.

**What did you see instead? Under which circumstances?**
`alertmanager_cluster_failed_peers` continuously reports 1 although the second pod was up and running

**Environment**
Azure Kubernetes (AKS)

* Alertmanager version:
alertmanager, version 0.16.0 (branch: HEAD, revision: 73bdd966e0055f3b828340ade3ef1f3a38169cdc)
  build user:       root@fbea1f55d584
  build date:       20190121-12:58:06
  go version:       go1.11.4

**Comment by simonpasquier** [comment]
Please share the AlertManager logs. Also what are the flags passed to AlertManager?
Also note that AlertManager will try to reconnect to a lost peer before giving up, the duration is governed by `--cluster.reconnect-timeout` which is 6 hours by default.

**Comment by stuartnelson3** [comment]
This is expected behavior. When a peer is removed, alertmanager will try to reconnect to it for 6 hours before giving up (which will decrement the counter).

https://github.com/prometheus/alertmanager/blob/master/cluster/cluster.go#L366

deleting the pod will cause a new one to be scheduled by kubernetes, but the cluster sees them as two unique cluster members.

**Comment by swapzero** [comment]
Well, yes, you're right. But I wouldn't have opened this if I knew about the option. Could you please add it here: https://github.com/prometheus/alertmanager#high-availability ?
