### ISSUE TITLE
Alertmanager does not update JIRA ticket on successive alarms

### ISSUE THREAD

**Issue by dhbarman** [prometheus/alertmanager#1824]
**What did you do?**

We manually generated an alert to AlertManager. We made sure that a JIRA ticket got created. 
After the alert expired (after default 5mins) from AM console, we manually created another alarm with the **same content/body/labels**  after 5 mins. But the JIRA ticket did not get updated.

**What did you expect to see?**

We expected JIRA ticket to get updated (update time should have been modified)

**What did you see instead? Under which circumstances?**

No change in the update time. 

**Environment**

* System information:

	Linux 4.1.12-124.23.1.el7uek.x86_64 x86_64

* Alertmanager version:

	0.14.0

* Alertmanager configuration file:

* Logs:

**Comment by stuartnelson3** [comment]
Alertmanager does not have a jira integration. I'm guessing the jira ticket is being created by a webhook receiver?

**Comment by stuartnelson3** [comment]
The logic of how your webhook interacts with jira is out of the scope of alertmanager, I don't think there's any way we can help you here.
