### ISSUE TITLE
AlertManager crashing due to pager duty alert

### ISSUE THREAD

**Issue by cuthbe** [prometheus/alertmanager#1828]
I have alertmanager running but alerts are not going into pager duty. I see the following in the logs

level=debug ts=2019-04-08T17:29:32.81456097Z caller=notify.go:670 component=dispatcher msg="Notify attempt failed" attempt=1 integration=pagerduty receiver=pagerduty err="unexpected status code 400"
level=error ts=2019-04-08T17:29:32.814742975Z caller=notify.go:332 component=dispatcher msg="Error on notify" err="cancelling notify retry for \"pagerduty\" due to unrecoverable error: unexpected status code 400"
level=error ts=2019-04-08T17:29:32.814767344Z caller=dispatch.go:177 component=dispatcher msg="Notify for alerts failed" num_alerts=2 err="cancelling notify retry for \"pagerduty\" due to unrecoverable error: unexpected status code 400"
level=info ts=2019-04-08T17:29:35.540648774Z caller=main.go:467 msg="Received SIGTERM, exiting gracefully..."
level=debug ts=2019-04-08T17:29:35.540795025Z caller=nflog.go:334 component=nflog msg="Running maintenance"

The last line looks like something just kills the process.

Versions

alertmanager, version 0.16.2 (branch: HEAD, revision: 308b7620642dc147794e6686a3f94d1b6fc8ef4d)
  build user:       root@1e9a48272b38
  build date:       20190405-12:27:40
  go version:       go1.11.6

prometheus, version 2.8.1 (branch: HEAD, revision: 4d60eb36dcbed725fcac5b27018574118f12fffb)
  build user:       root@bfdd6a22a683
  build date:       20190328-18:04:08
  go version:       go1.11.6

AlertManager config

global:
  resolve_timeout: 5s
route:
  group_by: ['instance', 'severity']
  group_wait: 2s
  group_interval: 30s
  repeat_interval: 30s
  receiver: pagerduty
  routes:
  - match:
      alertname: InstanceDown
    receiver: pagerduty

receivers:
- name: pagerduty
  pagerduty_configs:
  - send_resolved: true
    routing_key: "key"
    description: "{{ .CommonAnnotations.description }}"
    severity: '{{ if .CommonLabels.severity }}{{ .CommonLabels.severity | toLower }}{{ else }}critical{{ end }}'

templates:
- templates/*.tmpl

How do I debug to see what it is sending to pager duty?

**Comment by cuthbe** [comment]
Turns out this was the description. I think maybe debug should log the entire pager duty msg.

**Comment by simonpasquier** [comment]
>  The last line looks like something just kills the process.

Something/someone sent a `SIGTERM` signal to the process ("`Received SIGTERM`") which I believe has nothing to do with your PagerDuty issue. https://github.com/prometheus/alertmanager/pull/1812 should ease the troubleshooting as the message returned by the PagerDuty will be printed in the logs.

**Comment by cuthbe** [comment]
This issue is back. 

level=debug ts=2019-04-29T14:19:28.718338806Z caller=notify.go:670 component=dispatcher msg="Notify attempt failed" attempt=1 integration=pagerduty receiver=pagerduty err="unexpected status code 400"
level=error ts=2019-04-29T14:19:28.718453084Z caller=notify.go:332 component=dispatcher msg="Error on notify" err="cancelling notify retry for \"pagerduty\" due to unrecoverable error: unexpected status code 400"
level=error ts=2019-04-29T14:19:28.718474924Z caller=dispatch.go:177 component=dispatcher msg="Notify for alerts failed" num_alerts=3 err="cancelling notify retry for \"pagerduty\" due to unrecoverable error: unexpected status code 400"

Not sure how do debug this when we can't see the message or any data. We are missing alerts I think because of it

**Comment by simonpasquier** [comment]
You need to trim down the description field so it fits under 1024 chars.
