### ISSUE TITLE
Cannot group by a field that contains a period

### ISSUE THREAD

**Issue by buroa** [prometheus/alertmanager#1839]
Not sure why... but it's rather annoying.

A lot of fields in Elasticsearch contain periods, much like host.name.keyword: whatever.com.

**Comment by brian-brazil** [comment]
Periods aren't valid in Prometheus label names, so these shouldn't be making it to the alertmanager in the first place.

**Comment by buroa** [comment]
Ok. Grafana by default sends alerts with periods. I will convert them to underscores.

**Comment by brian-brazil** [comment]
Does the alertmanager accept those alerts, or return an error?

**Comment by buroa** [comment]
I'm testing once I finish building the source, but it should? Is that not correct regex?

**Comment by brian-brazil** [comment]
We probably should be rejecting those, or offering some indication that things aren't right.

**Comment by buroa** [comment]
So if send a key of host_name_keyword and a value of whatever.com, Alertmanager will reject it? I know it rejects with periods but how crazy is this regex? If it also rejects underscores, I will just rewrite the source and build it.

**Comment by brian-brazil** [comment]
That should be accepted, values can be full UTF-8.

If the alertmanager isn't rejecting label names with periods, then that's something to be improved.

**Comment by buroa** [comment]
Yes, that's correct. I tested converting the periods to underscores and Alertmanager happily took them. Thanks :)
