### ISSUE TITLE
AlertManager allows creating invalid silences

### ISSUE THREAD

**Issue by dmarkhas** [prometheus/alertmanager#1841]
**What did you do?**

- Create new silence
- Add matcher with a value that contains an illegal character (comma)

**What did you expect to see?**

An error indicating that the silence is invalid

**What did you see instead? Under which circumstances?**

The silence is created with no errors. When inspecting the silence via the UI, we receive 400 Bad Request error on the call to /alerts with filter. The response body says "bad matcher format". No alerts are silenced.

**Environment**

Using the Docker image, 0.16.2

This seems like a bug to me, since AlertManager allows a user to create a silence with illegal matchers and does not indicate that there is a problem.

**Comment by dmarkhas** [comment]
Actually looks like alerts do get silenced (not sure why I thought they weren't) so the issue is only viewing the alerts affected by the silence.

**Comment by simonpasquier** [comment]
This is fixed by https://github.com/prometheus/alertmanager/pull/1788 and will be available in v0.17 (whenever it is ready).

**Comment by simonpasquier** [comment]
Closing as a duplicate. Feel free to re-open with more details if it doesn't match your view.
