### ISSUE TITLE
No visual indication of alerts being inhibited in UI

### ISSUE THREAD

**Issue by brian-brazil** [prometheus/alertmanager#1851]
If you look at an inhibited alert (while inhibited is ticked) there is no way to distinguish it from a non-inhibited alert in the UI. I believe this is due to #1698, as while there is an icon for silenced alerts there is not one for inhibited.

**Comment by jritchieBAE** [comment]
@brian-brazil I've taken a look at this issue, and implemented a fix that adds an icon to inhibited alerts when they are shown in the list. I'll open a pull request and reference this issue.
