### ISSUE TITLE
why send resloved when there is no alert fring

### ISSUE THREAD

**Issue by gjpei2** [prometheus/alertmanager#1859]
hello 
i meet some questions when i use alertmanager 
1、i sometimes receive two resloved message,this problem describe is in this issues https://github.com/prometheus/alertmanager/issues/1845
2、when i have lots of alert fring,i often receive many resloved message that there is no alert 
relatived to

i am looking forward to your reply
thanks!

**Comment by gjpei2** [comment]
prometheus configuration:
global:
scrape_interval: 15s
evaluation_interval: 15s

alertmanager configuration:
route:
group_by: ['alertname','cluster','service','instance']
group_wait: 60s
group_interval: 5m
repeat_interval: 3h
receiver: gjpei
routes:
- receiver: 'k8s_2s'
group_interval: 5m
match:
severity: page
and my rule is like :

name: 2s_pod_restart_monitor
rules:
- alert: Aiaas_PodRestart
expr: changes(kube_pod_container_status_restarts_total{namespace="default"}[5m])>0
for: 25s
labels:
severity: k8s_2s
annotations:
summary: "pod {{$labels.pod}} is restarting，value is {{ $value }}！"

**Comment by stuartnelson3** [comment]
As per the issue template, this is a usage question. Please send your question to prometheus-users@googlegroups.com, where other users can answer and benefit.
