### ISSUE TITLE
Prometheus send email of resolve alerts with custom subject

### ISSUE THREAD

**Issue by nalin95** [prometheus/alertmanager#1872]
I need to send prometheus alerts using emails to my statuspage.io page. So when i'm sending those alert emails i need to change the subject, for that I 've used email template. So my problem is i want to send resolve alerts email also with custom subject. Is there anyway to do that?

**Comment by simonpasquier** [comment]
Thanks for your report. It looks as if this is actually a question about usage and not development.

To make your question, and all replies, easier to find, we suggest you move this over to our [user mailing list](https://groups.google.com/forum/#!forum/prometheus-users), which you can also search. If you prefer more interactive help, join or our [IRC channel](https://webchat.freenode.net/?randomnick=1&channels=prometheus), #prometheus on irc.freenode.net. Please be aware that our IRC channel has no logs, is not searchable, and that people might not answer quickly if they are busy or asleep. If in doubt, you should choose the mailing list.

Once your questions have been answered, please add a short line pointing to relevant replies in case anyone stumbles here via a search engine in the future.
