### ISSUE TITLE
Precompiled binaries missing for alertmanager 0.17.0 on prometheus.io

### ISSUE THREAD

**Issue by drewandersen** [prometheus/alertmanager#1874]
![image](https://user-images.githubusercontent.com/2484277/57091496-362cc300-6cbe-11e9-8da6-76acc6f871eb.png)

**Comment by stuartnelson3** [comment]
Thanks for pointing this out. There seems to be permissions issues for releasing the binaries, I hope to have this resolved soon.

**Comment by prymitive** [comment]
Docker images also seems to be missing
https://quay.io/repository/prometheus/alertmanager?tab=tags
https://hub.docker.com/r/prom/alertmanager/tags

**Comment by prymitive** [comment]
Docker images are on quay and docker hub, thanks!

**Comment by stuartnelson3** [comment]
binaries are images are up, closing this issue
