### ISSUE TITLE
duplicate alert groups returned by api

### ISSUE THREAD

**Issue by stuartnelson3** [prometheus/alertmanager#1875]
**What did you do?**

view the alert list page via the ui

**What did you expect to see?**

non-duplicated alert groups

**What did you see instead? Under which circumstances?**

some alert groups are duplicated. i'm not sure why yet.

**Environment**

* System information:

	insert output of `uname -srm` here

* Alertmanager version:

	0.17.0

Of the 110 currently active alert groups at soundcloud, only 2 of the groups are duplicated (for a total of 4 groups being returned from the api, when only 2 of them should be). The groups appear to be perfectly duplicated.

**Comment by stuartnelson3** [comment]
This might be an artifact of that particular group's configuration. It only affects a single team. I'm thinking there might be some race condition in creating the groups internal to alertmanager when the routes are configured in a certain way. This would also explain why they have been seeing duplicate messages.

**Comment by taisph** [comment]
We currently see a duplicated alert in the UI with 0.17.0 but not with amtool alert query. Clicking "+ Info" on either expands both alerts in the UI. Not sure if it is the same issue.

**Comment by psalaberria002** [comment]
I also see duplicate groups. Version 0.18.

![Screen Shot 2019-07-10 at 01 04 42](https://user-images.githubusercontent.com/2410564/60928743-ca169e80-a2ae-11e9-962e-2a4e69523e7b.png)

**Comment by simonpasquier** [comment]
I can reproduce as well. It happens when I configure routes with the same `group_by` and `continue: true`. I'll dig into it...

**Comment by simonpasquier** [comment]
https://github.com/prometheus/alertmanager/pull/1964 has fixed the problem on the API v2 side but there's still a glitch in the UI: when several groups have the same group labels, clicking on the +/- button will expand/collapse all of them.

![screencast](https://user-images.githubusercontent.com/2587585/63594843-d1241280-c5b7-11e9-822a-c77b31fddec1.gif)

**Comment by simonpasquier** [comment]
Closed by #2012 and #1964
