### ISSUE TITLE
"Edit silence" needs to delete old silence from display

### ISSUE THREAD

**Issue by beorn7** [prometheus/alertmanager#188]
"Edit silence" in fact does not edit a silence but deletes the old one and creates a new one. That's fine.

But the old silence stays displayed until the silence page is refreshed.

I assume that's purely a display issue, so we might only need to delete the old silence from the DOM.

**Comment by a86c6f7964** [comment]
maybe would be nice to have the button not say "create" as well. I feel like it should say "update" instead. Since it actually is creating and deleting something maybe it could say "replace"?

**Comment by grobie** [comment]
This behavior is now even worse in the latest release v0.4.1. Updating a silence will create a new one without deleting the current one. I'll take a look tomorrow.
