### ISSUE TITLE
Prometheus Custom metrics for AKS cluster monitoring and Alerting

### ISSUE THREAD

**Issue by lavanyaanbuatgmaildotcom** [prometheus/alertmanager#1895]
Version Details:
Azure Kubernetes server 
Client Version:1.11.2
Server Version:1.10.8

Installation Procedure:
Installed Prometheus to monitor the AKS cluster:
helm install --name=prometheus --namespace=monitoring stable/prometheus

I am looking to generate an alert for AKS cluster:
1. Pod status other then Running  .i.e.Pods health — instances ready, status, restarts, age
2. Number of container per pod and its status
3. Port configurations on the pod
4. Node Status other then Ready
5. Deployments status — desired, current, up-to-date, available, age

I have checked the metrics related to pod and containers in the kubernetes Dashboard. But i did not get these details. Please assist what metrics to use to generate these alerts

Is there a way we can directly query the etcd DB in AKS cluster to get the details?

**Comment by simonpasquier** [comment]
Thanks for your report. It looks as if this is actually a question about usage and not development.

To make your question, and all replies, easier to find, we suggest you move this over to our [user mailing list](https://groups.google.com/forum/#!forum/prometheus-users), which you can also search. If you prefer more interactive help, join or our [IRC channel](https://webchat.freenode.net/?randomnick=1&channels=prometheus), #prometheus on irc.freenode.net. Please be aware that our IRC channel has no logs, is not searchable, and that people might not answer quickly if they are busy or asleep. If in doubt, you should choose the mailing list.

Once your questions have been answered, please add a short line pointing to relevant replies in case anyone stumbles here via a search engine in the future.
