### ISSUE TITLE
Add check that at least one silence matcher matches non-empty

### ISSUE THREAD

**Issue by brian-brazil** [prometheus/alertmanager#1897]
To avoid accidentally silencing everything, I propose that similar to PromQL selectors that we check that one matcher matches non-empty. Those who explicitly want to silence everything can still match on `alertname="~.+"`

**Comment by roidelapluie** [comment]
`alertname=~".+"`

**Comment by qoops-1** [comment]
I would like to help with this one

**Comment by simonpasquier** [comment]
@qoops-1 feel free to submit a PR.

**Comment by cmarincia** [comment]
How to silence all alerts at once? This is actually frustrating.
