### ISSUE TITLE
receive more resovled alerts 

### ISSUE THREAD

**Issue by gaopeiliang** [prometheus/alertmanager#1899]
**What did you do?**
I used one prometheus + one alertmanager,   I used web_hook to receive alert  wich config send_resovled=true ,  I group alert by [alertname] with alertmanager ,, 

---- now -----
alerting A, and B with same alertname , will aggre to one same group , and we will receive two alerts with A and B in one group ...
-----  resovled A -----
we receive A resovled + B fireing with one group ...
------ resovled B -----
we receive A resovled + B resovled with one group ..

A in resovled status have notify two times .. 
 
**What did you expect to see?**
resovled alerts only notify one times ...

**Environment**
msg="Starting Prometheus" version="(version=2.3.1, branch=HEAD, revision=188ca45bd85ce843071e768d855722a9d9dabe03)"

"Starting Alertmanager" version="(version=0.17.0, branch=HEAD, revision=c7551cd75c414dc81df027f691e2eb21d4fd85b2)"

* System information:

	Linux 4.14.2-1.el7.elrepo.x86_64 x86_64

* Alertmanager version:

    "Starting Alertmanager" version="(version=0.17.0, branch=HEAD, revision=c7551cd75c414dc81df027f691e2eb21d4fd85b2)"

* Prometheus version:

	msg="Starting Prometheus" version="(version=2.3.1, branch=HEAD, revision=188ca45bd85ce843071e768d855722a9d9dabe03)"

* Alertmanager configuration file:
```
route:
  group_wait: 30s
  group_interval: 2m
  repeat_interval: 1h
  receiver: 'web.hook'
  routes:
  - receiver: "web.hook"
    group_by: ['alertname']

receivers:
- name: 'web.hook'
  webhook_configs:
  - url: 'http://127.0.0.1:5000/'
    send_resolved: true

```

* Prometheus configuration file:
```
evaluation_interval: 15s
```

* Logs:
```

level=debug ts=2019-05-24T09:11:59.892918319Z caller=dispatch.go:104 component=dispatcher msg="Received alert" alert=Up_X[f74ac2b][active]
level=debug ts=2019-05-24T09:12:04.895477437Z caller=dispatch.go:430 component=dispatcher aggrGroup="{}/{}:{alertname=\"Up_X\"}" msg=flushing alerts="[Up_X[1c420c8][active] Up_X[f74ac2b][active]]"
level=debug ts=2019-05-24T09:12:14.895696458Z caller=dispatch.go:430 component=dispatcher aggrGroup="{}/{}:{alertname=\"Up_X\"}" msg=flushing alerts="[Up_X[1c420c8][active] Up_X[f74ac2b][active]]"
level=debug ts=2019-05-24T09:12:24.895791988Z caller=dispatch.go:430 component=dispatcher aggrGroup="{}/{}:{alertname=\"Up_X\"}" msg=flushing alerts="[Up_X[1c420c8][active] Up_X[f74ac2b][active]]"
level=debug ts=2019-05-24T09:12:29.892993724Z caller=dispatch.go:104 component=dispatcher msg="Received alert" alert=Up_X[f74ac2b][resolved]
level=debug ts=2019-05-24T09:12:29.893078874Z caller=dispatch.go:104 component=dispatcher msg="Received alert" alert=Up_X[1c420c8][active]
level=debug ts=2019-05-24T09:12:34.895937979Z caller=dispatch.go:430 component=dispatcher aggrGroup="{}/{}:{alertname=\"Up_X\"}" msg=flushing alerts="[Up_X[1c420c8][active] Up_X[f74ac2b][resolved]]"
level=debug ts=2019-05-24T09:12:44.896074336Z caller=dispatch.go:430 component=dispatcher aggrGroup="{}/{}:{alertname=\"Up_X\"}" msg=flushing alerts=[Up_X[1c420c8][active]]
level=debug ts=2019-05-24T09:12:54.896234988Z caller=dispatch.go:430 component=dispatcher aggrGroup="{}/{}:{alertname=\"Up_X\"}" msg=flushing alerts=[Up_X[1c420c8][active]]
level=debug ts=2019-05-24T09:12:59.892589108Z caller=dispatch.go:104 component=dispatcher msg="Received alert" alert=Up_X[f74ac2b][resolved]
level=debug ts=2019-05-24T09:12:59.892662224Z caller=dispatch.go:104 component=dispatcher msg="Received alert" alert=Up_X[1c420c8][resolved]
level=debug ts=2019-05-24T09:13:04.896429733Z caller=dispatch.go:430 component=dispatcher aggrGroup="{}/{}:{alertname=\"Up_X\"}" msg=flushing alerts="[Up_X[1c420c8][resolved] Up_X[f74ac2b][resolved]]"
level=debug ts=2019-05-24T09:13:29.89261524Z caller=dispatch.go:104 component=dispatcher msg="Received alert" alert=Up_X[f74ac2b][resolved]
level=debug ts=2019-05-24T09:13:29.892743794Z caller=dispatch.go:104 component=dispatcher msg="Received alert" alert=Up_X[1c420c8][resolved]
level=debug ts=2019-05-24T09:13:29.89292306Z caller=dispatch.go:430 component=dispatcher aggrGroup="{}/{}:{alertname=\"Up_X\"}" msg=flushing alerts="[Up_X[1c420c8][resolved] Up_X[f74ac2b][resolved]]"
level=debug ts=2019-05-24T09:13:59.892637931Z caller=dispatch.go:104 component=dispatcher msg="Received alert" alert=Up_X[f74ac2b][resolved]
level=debug ts=2019-05-24T09:13:59.892738305Z caller=dispatch.go:104 component=dispatcher msg="Received alert" alert=Up_X[1c420c8][resolved]
level=debug ts=2019-05-24T09:13:59.892908239Z caller=dispatch.go:430 component=dispatcher aggrGroup="{}/{}:{alertname=\"Up_X\"}" msg=flushing alerts="[Up_X[1c420c8][resolved] Up_X[f74ac2b][resolved]]"
level=debug ts=2019-05-24T09:14:29.892758225Z caller=dispatch.go:104 component=dispatcher msg="Received alert" alert=Up_X[f74ac2b][resolved]
level=debug ts=2019-05-24T09:14:29.892894369Z caller=dispatch.go:104 component=dispatcher msg="Received alert" alert=Up_X[1c420c8][resolved]
level=debug ts=2019-05-24T09:14:29.893051539Z caller=dispatch.go:430 component=dispatcher aggrGroup="{}/{}:{alertname=\"Up_X\"}" msg=flushing alerts="[Up_X[1c420c8][resolved] Up_X[f74ac2b][resolved]]"
level=debug ts=2019-05-24T09:14:59.892578036Z caller=dispatch.go:104 component=dispatcher msg="Received alert" alert=Up_X[f74ac2b][resolved]
```

**Comment by gaopeiliang** [comment]
`{'alerts': [{'annotations': {'summary': 'up notify 0'},
             'endsAt': '0001-01-01T00:00:00Z',
             'generatorURL': 'http://aly-hb2e-test-40-70.mljr.com:9090/graph?g0.expr=up%7Bjob%3D~%22run_script%7Cpushgateway%22%7D+%21%3D+1&g0.tab=1',
             'labels': {'alertname': 'Up_X',
                        'instance': '10.10.40.71:9092',
                        'job': 'pushgateway',
                        'slabel': 'test1',
                        'wlabel': 'test3'},
             'startsAt': '2019-05-24T17:11:59.891078356+08:00',
             'status': 'firing'},
            {'annotations': {'summary': 'up notify 0'},
             'endsAt': '0001-01-01T00:00:00Z',
             'generatorURL': 'http://aly-hb2e-test-40-70.mljr.com:9090/graph?g0.expr=up%7Bjob%3D~%22run_script%7Cpushgateway%22%7D+%21%3D+1&g0.tab=1',
             'labels': {'alertname': 'Up_X',
                        'instance': '127.0.0.1:9469',
                        'job': 'run_script',
                        'slabel': 'test1',
                        'wlabel': 'test3'},
             'startsAt': '2019-05-24T17:09:29.891078356+08:00',
             'status': 'firing'}],
 'commonAnnotations': {'summary': 'up notify 0'},
 'commonLabels': {'alertname': 'Up_X', 'slabel': 'test1', 'wlabel': 'test3'},
 'externalURL': 'http://aly-hb2e-test-40-70.mljr.com:9093',
 'groupKey': '{}/{}:{alertname="Up_X"}',
 'groupLabels': {'alertname': 'Up_X'},
 'receiver': 'web\\.hook',
 'status': 'firing',
 'version': '4'}
'--------------------------------------------------------------------'



{'alerts': [{'annotations': {'summary': 'up notify 0'},
             'endsAt': '0001-01-01T00:00:00Z',
             'generatorURL': 'http://aly-hb2e-test-40-70.mljr.com:9090/graph?g0.expr=up%7Bjob%3D~%22run_script%7Cpushgateway%22%7D+%21%3D+1&g0.tab=1',
             'labels': {'alertname': 'Up_X',
                        'instance': '10.10.40.71:9092',
                        'job': 'pushgateway',
                        'slabel': 'test1',
                        'wlabel': 'test3'},
             'startsAt': '2019-05-24T17:11:59.891078356+08:00',
             'status': 'firing'},
            {'annotations': {'summary': 'up notify 0'},
             'endsAt': '2019-05-24T17:12:29.891078356+08:00',
             'generatorURL': 'http://aly-hb2e-test-40-70.mljr.com:9090/graph?g0.expr=up%7Bjob%3D~%22run_script%7Cpushgateway%22%7D+%21%3D+1&g0.tab=1',
             'labels': {'alertname': 'Up_X',
                        'instance': '127.0.0.1:9469',
                        'job': 'run_script',
                        'slabel': 'test1',
                        'wlabel': 'test3'},
             'startsAt': '2019-05-24T17:09:29.891078356+08:00',
             'status': 'resolved'}],
 'commonAnnotations': {'summary': 'up notify 0'},
 'commonLabels': {'alertname': 'Up_X', 'slabel': 'test1', 'wlabel': 'test3'},
 'externalURL': 'http://aly-hb2e-test-40-70.mljr.com:9093',
 'groupKey': '{}/{}:{alertname="Up_X"}',
 'groupLabels': {'alertname': 'Up_X'},
 'receiver': 'web\\.hook',
 'status': 'firing',
 'version': '4'}
'--------------------------------------------------------------------'















{'alerts': [{'annotations': {'summary': 'up notify 0'},
             'endsAt': '2019-05-24T17:12:59.891078356+08:00',
             'generatorURL': 'http://aly-hb2e-test-40-70.mljr.com:9090/graph?g0.expr=up%7Bjob%3D~%22run_script%7Cpushgateway%22%7D+%21%3D+1&g0.tab=1',
             'labels': {'alertname': 'Up_X',
                        'instance': '10.10.40.71:9092',
                        'job': 'pushgateway',
                        'slabel': 'test1',
                        'wlabel': 'test3'},
             'startsAt': '2019-05-24T17:11:59.891078356+08:00',
             'status': 'resolved'},
            {'annotations': {'summary': 'up notify 0'},
             'endsAt': '2019-05-24T17:12:29.891078356+08:00',
             'generatorURL': 'http://aly-hb2e-test-40-70.mljr.com:9090/graph?g0.expr=up%7Bjob%3D~%22run_script%7Cpushgateway%22%7D+%21%3D+1&g0.tab=1',
             'labels': {'alertname': 'Up_X',
                        'instance': '127.0.0.1:9469',
                        'job': 'run_script',
                        'slabel': 'test1',
                        'wlabel': 'test3'},
             'startsAt': '2019-05-24T17:09:29.891078356+08:00',
             'status': 'resolved'}],
 'commonAnnotations': {'summary': 'up notify 0'},
 'commonLabels': {'alertname': 'Up_X', 'slabel': 'test1', 'wlabel': 'test3'},
 'externalURL': 'http://aly-hb2e-test-40-70.mljr.com:9093',
 'groupKey': '{}/{}:{alertname="Up_X"}',
 'groupLabels': {'alertname': 'Up_X'},
 'receiver': 'web\\.hook',
 'status': 'resolved',
 'version': '4'}
'--------------------------------------------------------------------'

`

**Comment by gaopeiliang** [comment]
with latest version prometheus ...  I found  --rules.alert.resend-delay=1m ..  
with alertmanager config 
```
  group_wait: 10s
  group_interval: 40s   ( < --rules.alert.resend-delay )
  repeat_interval: 1h

it is correct .......  we receive only one resovled 
```
```
  group_wait: 10s
  group_interval: 5m   ( > --rules.alert.resend-delay )
  repeat_interval: 1h

 we also receive more resovled 
```


```
prometheus, version 2.9.2 (branch: HEAD, revision: d3245f15022551c6fc8281766ea62db4d71e2747)
  build user:       root@1d43b6951e8f
  build date:       20190424-15:32:31
  go version:       go1.12.4
```

**Comment by simonpasquier** [comment]
It is working as expected: AlertManager notifies with the full list of alerts including the ones that are already resolved. Only when all alerts of a group are resolved, it should stop to notify again.
