### ISSUE TITLE
Make the effect of silences more obvious in realtime

### ISSUE THREAD

**Issue by beorn7** [prometheus/alertmanager#190]
Currently, you add a silence, and then you have to wait for the next group interval to see what actually got silenced.

Ideally, there is a "preview" button to check what alerts _would_ be silenced if I created the silence right now. Then, the current alerts who will be properly silenced on the next group evaluation, should be marked as silenced right after creating the silence.

I guess that means an "out of band" extra run of the just created silence (with the same to be done for the "preview").

**Comment by fabxc** [comment]
For adding a silence this requires a pass over the existing alerts, so far so O(N).
When deleting silence we now have to check the alerts silenced by the deleted silence and whether they are now silenced by another one – O(NM). Unless we constantly keep state about all silences affecting an alert.

All possible in general. Doing it in a clean and scalable way is more difficult. Needs some careful consideration. We'll want to avoid persisting that information at the cost of recomputing it all on each reload. We always have to keep in mind that every feature at some point must be working in a distributed setup.

**Comment by matthiasr** [comment]
I think even in a large organization the total number of silences and active alerts will be on the order of thousands, not millions. I don't think O(N) is an issue until long after N becomes too big to display in a browser. If need be, just stop after the few thousand, it's not going to be helpful for a preview anymore.

If deletion becomes a problem, it can move into the background again.

I don't think we need to be afraid of O(N) just on principle.

**Comment by brian-brazil** [comment]
I'd expect silences to be on the order of thousands, but alerts could easily hit the millions.

**Comment by fabxc** [comment]
It's a totally reasonable feature and possible I would say. Just saying we have to be careful to not implement features (in a way) that cannot a scale.

**Comment by beorn7** [comment]
Since this is a pure display issue, it can be done best-effort (i.e. don't do it if the alertmanager is too busy already).

WRT O(NM): Fundamentally, we only need to do what we would do every 5min anyway, just out of band and only affecting display? Or am I misunderstanding something?

**Comment by grobie** [comment]
:+1: kind of confusing. Until we settled on a solution, what about showing a warning after creating a silence like "It can take up to xxx seconds until the silence becomes visible in the UI"?

**Comment by stuartnelson3** [comment]
Silence previews were added as part of the frontend rewrite

**Comment by beorn7** [comment]
Note that there is still the related #979 .

**Comment by stuartnelson3** [comment]
noted
