### ISSUE TITLE
Expose alert fingerprint in notification template

### ISSUE THREAD

**Issue by dmarkhas** [prometheus/alertmanager#1903]
Currently the following information is available to the notification template:

```
// Alert holds one alert for notification templates.
type Alert struct {
	Status       string    `json:"status"`
	Labels       KV        `json:"labels"`
	Annotations  KV        `json:"annotations"`
	StartsAt     time.Time `json:"startsAt"`
	EndsAt       time.Time `json:"endsAt"`
	GeneratorURL string    `json:"generatorURL"`
}
```

It would be useful for us to have the fingerprint of the alert as well, for various downstream systems.

**Comment by simonpasquier** [comment]
Can you provide more details about why you'd need this? Which integration do you use?

**Comment by dmarkhas** [comment]
We have a downstream system that collects all alerts, where it is important to be able to pinpoint a specific alert by some sort of id since we store the alerts history. Currently that system uses a hash of the labels that is calculated internally.
We want to enhance the email template to contain a link to that system that would reference the exact alert instance that is firing - currently we have to pass all of the labels, so it would've been easier if we could just use the fingerprint value (which the downstream system also has, but does not currently use).

**Comment by simonpasquier** [comment]
Thanks for the detailed information. It doesn't seem unreasonable to me to expose the fingerprint to the templates. @stuartnelson3, what do you think?

Also does your downstream system receive the alerts from the webhook or does it get them by polling the AlertManager's API?

**Comment by dmarkhas** [comment]
It does both actually, there are actions that are taken for each alert fired and there is a periodic process that pulls all firing alerts.
I'm not sure if the webhook payload contains the fingerprint, but if it doesn't it would be nice if it is added to it as well :)

**Comment by roidelapluie** [comment]
note: we do fingerprint downstream but based on common labels + start date.

**Comment by stuartnelson3** [comment]
Adding the fingerprint sounds good to me. We currently send the fingerprint via the API, and there are plans to add an endpoint to query a single alert/alertgroup by fingerprint.
