### ISSUE TITLE
amtool no longer honors -r (receiver) command-line flag

### ISSUE THREAD

**Issue by bva** [prometheus/alertmanager#1906]
**What did you do?**

amtool alert query -r my-receiver -a

**What did you expect to see?**

All active alerts filtered by receiver attribute

**What did you see instead? Under which circumstances?**

All active alerts

* Alertmanager version:

alertmanager, version 0.17.0 (branch: HEAD, revision: c7551cd75c414dc81df027f691e2eb21d4fd85b2)
  build user:       root@932a86a52b76
  build date:       20190503-09:10:07
  go version:       go1.12.4

amtool, version 0.17.0 (branch: HEAD, revision: c7551cd75c414dc81df027f691e2eb21d4fd85b2)
  build user:       root@932a86a52b76
  build date:       20190503-09:10:07
  go version:       go1.12.4

* Logs:
Straced invocation of alertmanager's API, it does not have receiver= query parameter:

```
strace ./amtool alert query -r my-receiver -a 2>&1|grep v2
write(3, "GET /api/v2/alerts?active=true&inhibited=false&silenced=false&unprocessed=false HTTP/1.1\r\nHost: ...\r\nUser-Agent: Go-http-clien"..., 208) = 208

```

**Comment by simonpasquier** [comment]
Thanks for reporting! I've quickly looked at the code and it was probably dropped during #1798.
