### ISSUE TITLE
Template email not replacing external and generator URL

### ISSUE THREAD

**Issue by rahulraykor** [prometheus/alertmanager#1912]
**What did you do?**
In the compose I set up:
command:
- '--web.external-url=localhost:9093'
But still in the email I am getting docker ID and the port, which I guess is default behavior.

**What did you expect to see?**
I want my email to have correct Alert Manager and source addresses.

* Alertmanager version:

	Latest from docker

* Prometheus version:

	Latest from docker

**Comment by simonpasquier** [comment]
Which version of AlertManager do you run? Can you share your AlertManager configuration?

**Comment by simonpasquier** [comment]
You should set `--web.external-url=http://localhost:9093`. The `html/template` package [escapes](https://golang.org/pkg/html/template/#hdr-Contexts) any URL with protocol other than `http`, `https` or `mailto`. `localhost:9093` is interpreted as the `localhost` scheme so it is replaced by `#ZgotmplZ`.
