### ISSUE TITLE
amtool silence query -q fail to return silence id

### ISSUE THREAD

**Issue by r0bj** [prometheus/alertmanager#1917]
**What did you do?**

```
$ amtool silence add instance=test
d384fb5f-52de-4be2-8f69-d2d3f11dd0ad
```

```
$ amtool silence query -q instance=test
0xc000501df0
```

Note: instead of propoer silence id `d384fb5f-52de-4be2-8f69-d2d3f11dd0ad` there is some string `0xc000501df0`

Query without `-q` parameter works fine:
```
# amtool silence query instance=test
ID                                    Matchers       Ends At                  Created By  Comment
d384fb5f-52de-4be2-8f69-d2d3f11dd0ad  instance=test  2019-06-09 20:40:43 UTC  user
```

**What did you expect to see?**

```
$ amtool silence query -q instance=test
d384fb5f-52de-4be2-8f69-d2d3f11dd0ad
```

**What did you see instead? Under which circumstances?**

```
$ amtool silence query -q instance=test
0xc000501df0
```

**Environment**

* System information:

	insert output of `uname -srm` here

* Alertmanager version:

	0.17.0

* Prometheus version:

	2.10.0

**Comment by stuartnelson3** [comment]
Thanks for reporting! It was a quick fix and has already been merged.
