### ISSUE TITLE
Display: Double quotes for label values

### ISSUE THREAD

**Issue by beorn7** [prometheus/alertmanager#192]
The new AM displays label values in single quotes. For copy&paste into Prometheus expressions, it would be much more handy to have double quotes.

**Comment by fabxc** [comment]
In which case is this more handy?

**Comment by beorn7** [comment]
As said: " For copy&paste into Prometheus expressions." Which part of that is not obviously useful?

**Comment by fabxc** [comment]
Prometheus accepts ` and ' and " as valid quotes.

**Comment by beorn7** [comment]
Oooops... I guess that's a "TIL". (And makes me kind of sad... The text format only supports double quotes, which is a discrepancy that could have been avoided.)

**Comment by fabxc** [comment]
That has been around for quite a while. Originially introduced to avoid escaping madness in console templates I think.

**Comment by brian-brazil** [comment]
We probably should try to be consistent in how we render it anyway.

**Comment by beorn7** [comment]
I'd prefer to render double quotes consistently, but I feel less strongly about as before, when I thought single quotes would not be legal PromQL.
