### ISSUE TITLE
Remove HipChat notifier after June 30th, 2020

### ISSUE THREAD

**Issue by simonpasquier** [prometheus/alertmanager#1930]
HipChat is EOL and the last product will be discontinued by  June 30th, 2020.
https://www.atlassian.com/partnerships/slack/faq#faq-e812d374-fc30-4eda-855a-ac4756450d6f

**Comment by brian-brazil** [comment]
Did you mean 2020?

**Comment by simonpasquier** [comment]
Indeed :eyeglasses:

**Comment by simonpasquier** [comment]
Closed by #2281
