### ISSUE TITLE
template/default.tmpl and template/email.tmpl are out of sync

### ISSUE THREAD

**Issue by cretz** [prometheus/alertmanager#1939]
Presumably there is some premailer or inline-styler used to build `template/default.tmpl`'s `email.default.html` value from `template/email.html`. However, from a cursory glance, it appears out of sync on https://github.com/prometheus/alertmanager/pull/1475. Specifically that PR didn't update the default template HTML.

Are they out of sync by intention? What tool is used to generate the inline-style versioned? I came across this when working with my own templates.

**Comment by stuartnelson3** [comment]
I'm not sure, to be honest. I don't know what tool was used to generate the inline-style version.

**Comment by simonpasquier** [comment]
I dug into this and couldn't find any reference in the project's history. But [premailer](https://pypi.org/project/premailer/) seems to fit the needs.

**Comment by cretz** [comment]
I just had to do this for another thing recently and found https://automattic.github.io/juice/ to be the best wrt clean HTML output.

**Comment by simonpasquier** [comment]
@cretz thanks for the link! I mentioned `premailer` because it has a CLI and may allow us to check at CI time that there's no discrepancy between `template/default.tmpl` and `template/email.tmpl`.

**Comment by haraldkoch** [comment]
Well, this explains why the pretty template in `template/email.html` doesn't match what's actually being sent by the alert manager... I was very confused!
