### ISSUE TITLE
The slack message send all the time and can't stop 

### ISSUE THREAD

**Issue by mysterytree** [prometheus/alertmanager#195]
I want to monitor the container if it start and send a message to slack once.
So I wirte the rules like this :

ALERT StartContainer
  IF time()-container_start_time_seconds < 20
  WITH {
    job="cadvisor"
  }
  SUMMARY "Instance {{$labels.name}} start"
  DESCRIPTION "{{$labels.instance}} of job {{$labels.job}}  start,id: {{$labels.id}}"

I removed the "FOR"  sentences but it still send message to slack every minutes.

**Comment by mysterytree** [comment]
I just want get the message one time .What should it do ? Thanks a lot

**Comment by fabxc** [comment]
If the alert is continuously firing, it is send to AM on every evaluation interval. The AM handles how often a notification about the same alert is repeated and can be configured with the `group_wait` and `repeat_interval` parameters for each route.

https://github.com/prometheus/docs/blob/amdoc/content/docs/alerting/configuration.md

That particular alert should only fire initially for the same container. With the 0.16 Prometheus version the alert will be considered firing for another 5 minutes. You should generally not get another notification if `repeat_interval` > 5m.
