### ISSUE TITLE
Alert Manager SMTP Config-field route not found in type config.plain

### ISSUE THREAD

**Issue by Diarrass** [prometheus/alertmanager#1956]
I am new to prometheus.
I am setting up Alert manager to get email notification. the alerts are firing but i am not receiving mails beccause of my alertmanager.yml file.

this is how the file looks [like:](https://pastebin.com/YqtCxWC3)

and this is the error message I get when i check the config.

 FAILED: parsing YAML file /etc/alertmanager/alertmanager.yml: yaml: unmarshal errors:
  line 1: field route not found in type config.plain
  line 5: field receivers not found in type config.plain

alertmanager version is 0.17.0

alertmanager --version
alertmanager, version 0.17.0 (branch: HEAD, revision: c7551cd75c414dc81df027f691e2eb21d4fd85b2)
  build user:       root@932a86a52b76
  build date:       20190503-09:10:07
  go version:       go1.12.4

**Comment by simonpasquier** [comment]
The discussion is happening here: https://groups.google.com/d/msg/prometheus-users/vm3iEHUkGDk/U1m9sguQCgAJ

It can be reopened in case it is proven to be a real bug (which is unlikely).

**Comment by Diarrass** [comment]
I am the one you openened the discussion over there. I thought I would have more success here

**Comment by simonpasquier** [comment]
Having one discussion venue is easier to deal with and the users mailing list is exactly for this kind of question.
