### ISSUE TITLE
Deduplicate alerts with multiple receivers when viewing All receivers

### ISSUE THREAD

**Issue by comicmuse** [prometheus/alertmanager#1961]
My alerts go to multiple receivers. In 0.18.0, when I look at the default landing page on the alertmanager, with grouping on, I see a group for each receiver (though the receiver is not actually on the user interface). 

I would expect only to see one instance of each alert when viewing All receivers. 

![am](https://user-images.githubusercontent.com/14880722/61114582-86778c80-a488-11e9-9225-84ebc45b71e5.png)

**Comment by simonpasquier** [comment]
Thanks for reporting! It looks very similar to #1959 and #1875.

**Comment by simonpasquier** [comment]
For completeness, could you share your AlertManager configuration?

**Comment by comicmuse** [comment]
Yeah, definitely looks like #1875 . Sorry - I should have found that one. 

Redacted alertmanager.yml attached.
[alertmanager.txt](https://github.com/prometheus/alertmanager/files/3386002/alertmanager.txt)

**Comment by comicmuse** [comment]
BTW, the reason I determined it was related to recievers was when I explicitly choose a Receiver from the dropdown, I no longer see the duplicates. (also ticking "Enable Custom Groups" removes the duplicates, for some reason)

**Comment by simonpasquier** [comment]
I'm closing it for now as we can follow up on the other issues.

> ticking "Enable Custom Groups" removes the duplicates, for some reason

This is because it falls back to the pre-v0.18 view which calls `/api/v2/alerts` instead of `/api/v2/alerts/groups`. The latter is buggy when you have routes that group on the same set of label names.
