### ISSUE TITLE
Any way to know the history of alerts?

### ISSUE THREAD

**Issue by YaoZengzeng** [prometheus/alertmanager#1976]
As far as I know, if the alert is resolved, it will be GCed after a while. And for the same alert, if it is resent multiple times, it will be aggregated.

So any good advice if I want know the history of alerts, including all of the alerts (resolved and firing) and how many times the same alert is emitted.

Maybe I could configure the alertmanager notify to the webhook server and persist alerts in it. But if I configure silence or inhibit, then the webhook server will not get all the original alerts.

**Comment by simonpasquier** [comment]
If you really want to keep a track of all the alerts then the best option is to have Prometheus sending the alerts to an external service that will store them elsewhere.

I'm closing it for now. If you have further questions, please use our [user mailing list](https://groups.google.com/forum/#!forum/prometheus-users), which you can also search.
