### ISSUE TITLE
can she support slience alerts on particular period(s)

### ISSUE THREAD

**Issue by sipherhern** [prometheus/alertmanager#1978]
**What did you do?**
I'm using alertmanager to send alerts to wechat.
**What did you expect to see?**
I want to slience some alerts on sleeping time or very early morning
**What did you see instead? Under which circumstances?**
I receivce many alerts on my bed time only to find it's a normal fluctuation at night. It's not right to adjust at rules because it works fine at day time.
But rightnow alertmanager only support silence the alerts for a long period time, I have to set the slience every day if doing what I said. It's very bad experience.

**Environment**

* System information:

	insert output of `uname -srm` here

* Alertmanager version:

	insert output of `alertmanager --version` here

* Prometheus version:

	insert output of `prometheus -version` here (if relevant to the issue)

* Alertmanager configuration file:
```
insert configuration here
```

* Prometheus configuration file:
```
insert configuration here (if relevant to the issue)
```

* Logs:
```
insert Prometheus and Alertmanager logs relevant to the issue here
```

**Comment by simonpasquier** [comment]
This is similar to https://github.com/prometheus/alertmanager/issues/876. AlertManager doesn't support this directly but there are various alternatives described in the linked issue.

I'm closing it for now. If you have further questions, please use our [user mailing list](https://groups.google.com/forum/#!forum/prometheus-users), which you can also search.
