### ISSUE TITLE
Feature Request: Set send_resolved on alert by alert basis

### ISSUE THREAD

**Issue by ChrisCooney** [prometheus/alertmanager#1995]
At the moment, Alert Manager supports configuring whether resolved alerts are sent on a receiver by receiver basis. This means that, for example our pager_duty receiver, can either globally send resolved or not. This is highly undesirable and doesn't make a great deal of sense.

Semantically, it makes much more sense to support the `send_resolved` flag on the `alert` itself, rather than forcing uses to create multiple receivers that are otherwise identical.

**Comment by simonpasquier** [comment]
Can you share more about your use case/configuration? AlertManager works on alert groups so I guess that you meant `group of alerts` rather than `alert`.

**Comment by ChrisCooney** [comment]
Apologies - yes group of alerts makes sense.

My use case is the following. Let's say we have a pager duty receiver that we redirect all of our page level events to. For some issues (i.e API 5xx errors), we're okay with those resolving themselves in pagerduty. If the API isn't erroring any more, there's nothing for anyone to do.

For others, for example messages that were unable to be processed from a mission critical queue, we want to ensure someone is woken up. Let's say we have an alert based on the following expression:

```
expr: max(increase(activemq_queue_size{queueName="my_important_queue"}[1m])) > 1
```

It is possible for things to sit in this queue while they're being resolved, so we can't use a straight up count. We need to use the rate that messages are being enqueued by. If we get messages for 1 minute, then nothing for 1 minute, a send_resolved will be issued. This means pager duty will be resolved and the issue won't be escalated. 

This means we have two alerts. Both going to pagerduty. One alert we're happy to resolve itself, another we don't want to resolve itself. In the case of pagerduty, issues resolving themselves breaks the escalation policies that we have in place.

Does that make more sense?

**Comment by brian-brazil** [comment]
This is something that can be handled by multiple receivers, so I don't
think we should add this complexity for the sake of a niche use case.
Generally I'd recommend avoiding resolved notifications altogether.

**Comment by ChrisCooney** [comment]
Does it not seem odd though that you'd need multiple receivers for this though?

I also don't think this is particularly niche. You want some alerts to resolve themselves, you want others to not resolve themselves.

Fair enough on the feedback, thanks for letting me know.

**Comment by brian-brazil** [comment]
> Does it not seem odd though that you'd need multiple receivers for this though?

Not really, the use case is quite odd. Whether resolved notification can make sense really depends on whether the other end is capable of handling them sanely. So for example if you had some alerts say going to slack and a system capable of using resolved notifications, you'd not want them going to slack (they're just spam) but to the other system.

Also https://www.robustperception.io/running-into-burning-buildings-because-the-fire-alarm-stopped

**Comment by ChrisCooney** [comment]
I doubt we're gonna completely agree (article did give me a good laugh though). We'll take a look at our config and update. Thanks for taking the time to chat 👍
