### ISSUE TITLE
Configuration errors are not reliably logged on startup

### ISSUE THREAD

**Issue by pdf** [prometheus/alertmanager#200]
Calling `os.Exit()` exits the application immediately, without running deferred functions, so configuration errors are not reliably logged.

**Comment by stuartnelson3** [comment]
Config errors are reported by the deferred func within `reload`, after which `os.Exit()` is called.

https://github.com/prometheus/alertmanager/blob/b95b328/cmd/alertmanager/main.go#L300-L309
