### ISSUE TITLE
obsolete code?

### ISSUE THREAD

**Issue by johncming** [prometheus/alertmanager#2003]
It's not in use  that [*restapi.Server](https://godoc.org/github.com/prometheus/alertmanager/api/v2/restapi#Server) .

Is it obsolete code? Or for other purposes. If it is an obsolete code, can it be removed?

Thanks.

**Comment by metalmatze** [comment]
All of that is generated with go-swagger. Only parts of that generated code are used indeed, but it also doesn't hurt to have it in there IMHO.
