### ISSUE TITLE
Receivers API endpoint could expose more than names

### ISSUE THREAD

**Issue by roidelapluie** [prometheus/alertmanager#2006]
I think we could expose more of the receivers configuration than just names.

To get receivers config now, I will need to parse the blob(!) in the /api/v2/status endpoint.

**What did you do?**

GET /api/v2/receivers

**What did you expect to see?**

Receivers config (without secrets)

**What did you see instead? Under which circumstances?**

Receivers names

**Comment by simonpasquier** [comment]
I suppose you have a specific use case in mind? Mapping the full configuration of receivers to the API would be tedious so I think we need a good rationale first.

**Comment by roidelapluie** [comment]
AM has the knowledge about every customer we have. I am interested in getting emails and webhooks urls.

**Comment by brian-brazil** [comment]
Parsing the YAML is probably the easiest way to get that.
