### ISSUE TITLE
Silence creation is broken when using the grammarly extension

### ISSUE THREAD

**Issue by tivvit** [prometheus/alertmanager#2010]
This is probably an issue with Grammarly, but I thought it is better to let others know.

Grammarly for Chrome
Version
14.926.5955

alertmanager: 0.18.0

What happened?
When I try to create silence preview button does not work. The whole web GUI is broken (i.e. silence creation block is present on the alerts tab).

After disabling Grammarly extension everything works as expected

**Comment by simonpasquier** [comment]
It would probably better be directed to Grammarly. We understand that you want to make AlertManager's users aware of it (appreciated!) but it looks like there is little we can do.

**Comment by stephenreddek** [comment]
@simonpasquier I think this can be mitigated by disabling grammarly on each textarea per https://github.com/elm/html/issues/44#issuecomment-534665947 ? Would you accept a PR that does that?

**Comment by simonpasquier** [comment]
I'll defer to @stuartnelson3 and @w0rm whether this is ok or not.

**Comment by w0rm** [comment]
@stephenreddek solution looks good to me!

**Comment by simonpasquier** [comment]
Given that we had the issue reported twice already (#2010 and https://github.com/prometheus/alertmanager/issues/2022), I think it is worth having this change.

**Comment by w0rm** [comment]
Fixed in #2061
