### ISSUE TITLE
[bug] "New silence" doesn't close

### ISSUE THREAD

**Issue by paulfantom** [prometheus/alertmanager#2022]
**What did you do?**

Created new silence from firing alert

**What did you expect to see?**

"New Silence" part of view closed after hitting the "Create" button

**What did you see instead? Under which circumstances?**

"New Silence" didn't close and appears on all windows.

**Environment**

* System information:

	insert output of `uname -srm` here
	official docker container

* Alertmanager version:

	insert output of `alertmanager --version` here
	0.19.0

* Prometheus version:

	insert output of `prometheus -version` here (if relevant to the issue)
	0.12.0

* Alertmanager configuration file:
```
default one
```

* Prometheus configuration file:
```
not relevant
```

* Logs:
```

```

Snapshots:

Alerts view:

![Screenshot_20190905_124346](https://user-images.githubusercontent.com/3531758/64335312-d7b08200-cfda-11e9-90e2-c9da1cd840d3.jpg)

Silences view:

![Screenshot_20190905_124108](https://user-images.githubusercontent.com/3531758/64335541-50afd980-cfdb-11e9-8a7b-1fcce36be329.jpg)

**Comment by stuartnelson3** [comment]
I tried this a couple times and couldn't reproduce.

What browser are you using? Can you clear your cache?

**Comment by paulfantom** [comment]
Figured it out. Seems like a combination of chrome + grammarly extension is causing this.

**Comment by simonpasquier** [comment]
FWIW it had also been mentioned in https://github.com/prometheus/alertmanager/issues/2010
