### ISSUE TITLE
APIs: V2 API responses are inconsistent between internal/public/cluster IP/alertmanager UI

### ISSUE THREAD

**Issue by benjaminhuo** [prometheus/alertmanager#2023]
**What did you do?**
I've setup an alertmanager cluster (3 instances) using prometheus operator. 
To access the alertmanager-main service, I've changed it to NodePort and port foward a public ip  to this nodeport to access the svc from anywhere.

![Snip20190906_52](https://user-images.githubusercontent.com/18525465/64399799-66390800-d09c-11e9-9e6d-57275ded64c8.png)

And I'm using alertmanager v2 api to send custom alert to alertmanager.
There are some issues I found during my test:

- If the alert creation request is sent via public ip & port, the new alert can be retrieved using the same public ip & port , but cannot be retrieved using private IP & port and vice versa. 

For example, a new alert is created using v2 api like below:
```shell
curl -X POST "http://139.198.xx.xx:19093/api/v2/alerts" -H "accept: application/json" -H "Content-Type: application/json" -d "[{ \"startsAt\": \"2019-09-04T06:15:10.310Z\", \"annotations\": {\"message\": \"test1\", \"runbook_url\": \"test2\"}, \"labels\": {\"alertname\":\"testalert2\", \"job\": \"testjob2\", \"namespace\": \"testtest\", \"deployment\": \"testdeploy\", \"pod\": \"testpod\",\"prometheus\": \"monitoring/k8s\"},\"generatorURL\": \"http://sampleurl\"}]"
```

It can be retrived using the same public ip & port
```shell
curl -X GET "http://139.198.xx.xx:19093/api/v2/alerts?filter=alertname%3D%22testalert2%22" -H "accept: application/json"

[{"annotations":{"message":"test1","runbook_url":"test2"},"endsAt":"2019-09-06T03:34:34.060Z","fingerprint":"e61a1872f479833b","receivers":[{"name":"test"}],"startsAt":"2019-09-04T06:15:10.310Z","status":{"inhibitedBy":[],"silencedBy":[],"state":"active"},"updatedAt":"2019-09-06T03:29:34.060Z","generatorURL":"http://sampleurl","labels":{"alertname":"testalert","deployment":"testdeploy","job":"testjob","namespace":"testtest","pod":"testpod","prometheus":"monitoring/k8s"}}]
```

But cannot be retrieved via private ip&port
```shell
curl -X GET "http://192.168.11.12:32267/api/v2/alerts?filter=alertname%3D%22testalert2%22" -H "accept: application/json"
```
The situation is similar when I use cluster address(alertmanager-main.monitoring.svc) to do alert creation and retrieve.

- The second problem is that the new alert created by v2 API cannot be see from the alertmanager ui most of the time, and can only be found occasionally. While I can receive alert notification firing&resolved email correctly every time.

http://139.198.xx.xx:19093/#/alerts?silenced=false&inhibited=false&filter=%7Balertname%3D%22testalert%22%7D
![Snip20190906_55](https://user-images.githubusercontent.com/18525465/64401801-232f6280-d0a5-11e9-9356-3997b7a9d15e.png)

**What did you expect to see?**
New alert created using v2 api can be retrieved by any ip&port, and can be seen on the alertmanager ui everytime.

**Environment**

![Snip20190906_56](https://user-images.githubusercontent.com/18525465/64401913-9c2eba00-d0a5-11e9-9472-1c4b5c7770fc.png)

* Alertmanager configuration file:
![Snip20190906_58](https://user-images.githubusercontent.com/18525465/64403128-0e090280-d0aa-11e9-97ed-a43334a42203.png)

* Logs:
no error in log

**Comment by simonpasquier** [comment]
Alerts aren't replicated across the instances of the cluster, only silences and notification logs are. You need to send alerts to all AlertManager instances.

**Comment by benjaminhuo** [comment]
> Alerts aren't replicated across the instances of the cluster, only silences and notification logs are. You need to send alerts to all AlertManager instances.

@simonpasquier  Thanks very much for the quick response, I'll test it out following your suggestions. My question is if I send alerts to all alertmanager instances, will I receive multiple notifications?

**Comment by simonpasquier** [comment]
No the clustering should take care of de-duplicating the notifications.

**Comment by benjaminhuo** [comment]
Thank very much for the help and tips
