### ISSUE TITLE
404 Page Not Found in AlertManager Web UI

### ISSUE THREAD

**Issue by kaizen1** [prometheus/alertmanager#2025]
**What did you do?**
Prometheus 2.12.0 / 2019-08-17 and AlertManager  0.19.0 / 2019-09-03 are running fine. 

From debug log at startup I can see Prometheus is using V1 api to send alerts to AlertManager. I can curl AlertManager and get all alerts. 

But when I open the web ui to AlertManager I get 404 page not found for many GET request resources such as:

/alertmanager/api/v2/receivers

NOTE: when I change the URL from V2 to V1, I receive what looks like a good response:

{"status":"success","data":["alert-team"]}

* Alertmanager version:

alertmanager, version 0.19.0 (branch: HEAD, revision: 7aa5d19fea3f58e3d27dbdeb0f2883037168914a)
  build user:       root@587d0268f963
  build date:       20190903-15:01:40
  go version:       go1.12.8

* Prometheus version:

prometheus, version 2.12.0 (branch: HEAD, revision: 43acd0e2e93f9f70c49b2267efa0124f1e759e86)
  build user:       root@7a9dbdbe0cc7
  build date:       20190818-13:53:16
  go version:       go1.12.8

**Comment by simonpasquier** [comment]
`/alertmanager/api/v2/receivers` tells me that you have a reverse proxy in front of AlertManager. You probably miss some configuration to make it work properly (check the `--web.external-url` and `--web.route-prefix` flags).

I'm closing it for now. If you have further questions, please use our [user mailing list](https://groups.google.com/forum/#!forum/prometheus-users), which you can also search.

**Comment by kaizen1** [comment]
Thanks that hint helped. For those who may need these service start parameters to run behind a reverse proxy, these worked for me on alertmanager and prometheus server.

--web.external-url="https://mysite.com/alertmanager/" \
--web.listen-address=:9093 \
