### ISSUE TITLE
Add Simple (200 OK) Health Check Endpoint

### ISSUE THREAD

**Issue by kaizen1** [prometheus/alertmanager#2034]
Feature Request:

Add an http endpoint where we can do a simple 200 OK health check.
Many of us run behind a reverse proxy. We're forced to hack around with regex now for health checking. It's not working that well behind HAProxy. 

For example, 10.128.0.4:9093/ 

Should return 200 OK to denote the server is up.

**Comment by stuartnelson3** [comment]
What do you mean by "hack around"?

The status page would work for a simple health check.

**Comment by simonpasquier** [comment]
The `/-/healthy` and `/-/ready` endpoints already exist. They both return 200 OK when the service is ready to serve HTTP requests.

**Comment by stuartnelson3** [comment]
Ah! I remembered adding those, but didn't see them when looking through the api v1 impl. My bad :)

**Comment by kaizen1** [comment]
Great! I'll use them. Thanks.... I was regexing the 404 page not found as "healthy". That's what I meant by hacking around.

**Comment by kaizen1** [comment]
Thanks but in version 0.19.0 / 2019-09-03, those paths return 404 page not found.

**Comment by simonpasquier** [comment]
> In version 0.19.0 / 2019-09-03, those paths return 404 page not found.

Not for me.

**Comment by kaizen1** [comment]
So why don't you document this very basic feature on your GitHub page so other people can run into this same problem I'm having?

**Comment by mxinden** [comment]
@kaizen1 do you want to prepare a pull reuqest to add documentation to prometheus.io/docs.  https://github.com/prometheus/prometheus/pull/5737 should be a good sample, but I guess this pull request would need to point at https://github.com/prometheus/docs/tree/master/content/docs/alerting directly.

**Comment by kaizen1** [comment]
I couldn't get the suggested URLs to return 200 OK, so I can't document an unknown solution. That was kind of the point of my question.

**Comment by simonpasquier** [comment]
@kaizen1 can you follow up on the [user mailing list](https://groups.google.com/forum/#!forum/prometheus-users) with the details of your setup (configuration, logs, version, ...) and the exact response from AlertManager?

**Comment by kaizen1** [comment]
I'm not on the user mailing list. Here's the info requested. Alertmanager is running fine and sending alerts thru PagerDuty. The /ready endpoint is giving 404 page not found. Expected result is 200 OK

Linux 4.15.0-1037-gcp x86_64

alertmanager, version 0.19.0 (branch: HEAD, revision: 7aa5d19fea3f58e3d27dbdeb0f2883037168914a)
  build user:       root@587d0268f963
  build date:       20190903-15:01:40
  go version:       go1.12.8

alertmanage.yml

# The smarthost and SMTP sender used for mail notifications.
templates: 
- '/etc/alertmanager/template/*.tmpl'

# The root route on which each incoming alert enters.
route:
  # The labels by which incoming alerts are grouped together. For example,
  # multiple alerts coming in for cluster=A and alertname=LatencyHigh would
  # be batched into a single group.
  #
  # To aggregate by all possible labels use '...' as the sole label name.
  # This effectively disables aggregation entirely, passing through all
  # alerts as-is. This is unlikely to be what you want, unless you have
  # a very low alert volume or your upstream notification system performs
  # its own grouping. Example: group_by: [...]
  group_by: ['alertname', 'instance']

  # When a new group of alerts is created by an incoming alert, wait at
  # least 'group_wait' to send the initial notification.
  # This way ensures that you get multiple alerts for the same group that start
  # firing shortly after another are batched together on the first 
  # notification.
  group_wait: 15s

  # When the first notification was sent, wait 'group_interval' to send a batch
  # of new alerts that started firing for that group.
  group_interval: 5m

  # If an alert has successfully been sent, wait 'repeat_interval' to
  # resend them.
  repeat_interval: 3h 

  # A default receiver
  receiver: pager

  # All the above attributes are inherited by all child routes and can 
  # overwritten on each.
  routes:
  - match:
      severity: critical
      receiver: pager
  - match:
      severity: pager
      receiver: pager
  
receivers:
- name: 'pager'
  pagerduty_configs:
  - routing_key: myroutingkey

************************************
curl http://10.128.0.22:9093/alertmanager/
RESULT:

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>Alertmanager</title>
    </head>
    <body>
        <script>
            // If there is no trailing slash at the end of the path in the url,
            // add one. This ensures assets like script.js are loaded properly
            if (location.pathname.substr(-1) != '/') {
                location.pathname = location.pathname + '/';
                console.log('added slash');
            }
        </script>
        <script src="script.js"></script>
        <script>
            var app = Elm.Main.init({
                flags: {
                    production: true,
                    defaultCreator: localStorage.getItem('defaultCreator'),
                    groupExpandAll: JSON.parse(localStorage.getItem('groupExpandAll'))
                }
            });
            app.ports.persistDefaultCreator.subscribe(function(name) {
                localStorage.setItem('defaultCreator', name);
            });
            app.ports.persistGroupExpandAll.subscribe(function(expanded) {
                localStorage.setItem('groupExpandAll', JSON.stringify(expanded));
            });
        </script>
    </body>
</html>

************************

curl http://10.128.0.22:9093/ready
RESULT:
404 page not found

**************************
curl http://10.128.0.22:9093/ready/
RESULT:
404 page not found

LOGS: note I replace some ids with "a_very_long_id" to de-identify the data

_TRANSPORT=stdout
    PRIORITY=6
    SYSLOG_FACILITY=3
    SYSLOG_IDENTIFIER=alertmanager
    _UID=1003
    _GID=1004
    _COMM=alertmanager
    _EXE=/usr/local/bin/alertmanager
    _CMDLINE=/usr/local/bin/alertmanager --config.file=/etc/alertmanager/alertmanager.yml --web.external-url=https://mysite.com/alertmanager/ --web.liste
n-address=:9093 --log.level=debug --cluster.listen-address=
    _CAP_EFFECTIVE=0
    _SELINUX_CONTEXT=unconfined
    _SYSTEMD_CGROUP=/system.slice/alertmanager.service
    _SYSTEMD_UNIT=alertmanager.service
    _SYSTEMD_SLICE=system.slice
    _MACHINE_ID=a_very_long_id
    _HOSTNAME=alert-manager
    _STREAM_ID=a_very_long_id
    _PID=606
    _SYSTEMD_INVOCATION_ID=a_very_long_id
    _BOOT_ID=a_very_long_id

**Comment by simonpasquier** [comment]
It's `/-/ready` not `/ready`.

**Comment by kaizen1** [comment]
I had already tried /-/ready same error as previously reported.
Also tried /-/ready/ same error as previously reported.
I've lost interest in this game of ping pong.

**Comment by simonpasquier** [comment]
> can you follow up on the user mailing list with the details of your setup (configuration, logs, version, ...) and the exact response from AlertManager?

The mailing list is the appropriate venue for usage questions.
