### ISSUE TITLE
Document the /-/ready and /-/healthy endpoints

### ISSUE THREAD

**Issue by simonpasquier** [prometheus/alertmanager#2039]
From https://github.com/prometheus/alertmanager/issues/2034#issuecomment-532687607

We need to document the `/-/ready` `/-/healthy` probes.

prometheus/prometheus#5737 should be a good sample, but the pull request would need to point at https://github.com/prometheus/docs/tree/master/content/docs/alerting directly.

**Comment by MIBc** [comment]
I'd like to resolve it

**Comment by souvikhaldar** [comment]
Why is this issue still open?

**Comment by simonpasquier** [comment]
Because the PR didn't have the correct keyword to close this issue...
