### ISSUE TITLE
How to calculate EndsAt and StartsAt time difference?

### ISSUE THREAD

**Issue by goldstrike77** [prometheus/alertmanager#2041]
I want to show the recovery duration time in the alarm.
Like this for examples:

Start: Wed, 11 Sep 2019 17:39:18 CST
End:  Wed, 12 Sep 2019 18:04:48 CST
Duration: 25.01H

Is there any way to calculate the time difference from EndsAt and StartsAt? I know that it's impossible to calculate in a go template, is it possible to calculate in other places such as receivers?

**Comment by roidelapluie** [comment]
Thanks for your report. It looks as if this is actually a question about usage and not development.

To make your question, and all replies, easier to find, we suggest you move this over to our [user mailing list](https://groups.google.com/forum/#!forum/prometheus-users), which you can also search. If you prefer more interactive help, join or our [IRC channel](https://webchat.freenode.org/?channels=prometheus), #prometheus on irc.freenode.net. Please be aware that our IRC channel has no logs, is not searchable, and that people might not answer quickly if they are busy or asleep. If in doubt, you should choose the mailing list.

If you think this is not purely a support question, feel free to comment in here or take the underlying issues to our [developer mailing list](https://groups.google.com/forum/#!forum/prometheus-developers).

Once your questions have been answered, please add a short line pointing to relevant replies in case anyone stumbles here via a search engine in the future.

All that being said, in your specific case, you can do that in go template:

```
duration: {{(.EndsAt.Sub .StartsAt).Truncate 1000000000}}
```

**Comment by goldstrike77** [comment]
amazing and effective

Thanks very much.
