### ISSUE TITLE
amtool changes alertmanager.url flag from https to http

### ISSUE THREAD

**Issue by yershalom** [prometheus/alertmanager#2047]
**What did you do?**
`amtool --alertmanager.url=https://alertmanager.example.com silence query --within 8h`

**What did you expect to see?**
All of the silences with expiration in 8 hours.

**What did you see instead? Under which circumstances?**
`amtool: error: Get http://alertmanager.example.com/api/v2/silences: context deadline exceeded`

**Environment**
prod

* System information:

`Darwin 18.7.0 x86_64`

* Alertmanager version:

`0.19.0`

* Prometheus version:

`v2.12.0`

* Alertmanager configuration file:
```
Not relevant
```

* Logs:
```
No logs
```

**Comment by simonpasquier** [comment]
Not sure what happens for you. On my machine, the https scheme is honored:

```
docker run --entrypoint /bin/amtool --rm -ti prom/alertmanager:v0.19.0  --alertmanager.url=https://alertmanager.example.com silence query --within 8h
amtool: error: Get https://alertmanager.example.com/api/v2/silences: dial tcp: lookup alertmanager.example.com on 8.8.8.8:53: no such host
```

**Comment by yershalom** [comment]
Thanks, I'll check things again...
