### ISSUE TITLE
Alarm history information storage problem

### ISSUE THREAD

**Issue by qixiang-liu** [prometheus/alertmanager#2049]
I have an idea to store the alarm events of the alertmanager for a specified period of time, and then use the api interface to get all the data. Then you can display, count, and analyze the data.
I think the current webhook method is not very friendly and can only push real-time data.

**Comment by simonpasquier** [comment]
Can you provide more details about your use case and what the limitations with the webhook receiver? 
I'm not sure whether you're talking about alerts sent by Prometheus or notifications sent by Alertmanager.

**Comment by simonpasquier** [comment]
Closing for now. Feel free to reopen with more details.
