### ISSUE TITLE
Mail notifications require STARTTLS even when the mail server doesn't support STARTTLS.

### ISSUE THREAD

**Issue by lyda** [prometheus/alertmanager#205]
So this is kind of annoying.  Commit bb47752e requires STARTLS in all instances. Even when there's no auth. And even when the host is localhost.

I think it's all well and good to have secure comms, but I think it's also nice if a little common sense is involved.

Connections to port 25 on localhost probably don't need to be encrypted for instance. Perhaps a few flags in this area could help. Instead of hard-coding one person's notions of security in the code, some flags could allow users to make up their own mind.

Just a thought. :)

**Comment by stapelberg** [comment]
With #266, whether STARTTLS is required is configurable, so I think this issue can be closed.
