### ISSUE TITLE
individual alerts within "alertname = XXX" are not sorted

### ISSUE THREAD

**Issue by jamessanford** [prometheus/alertmanager#206]
With `alertname=test1` and three firing instances, every time I click the `AlertManager` banner , the order of the instances changes

Initial list:
![try1](https://cloud.githubusercontent.com/assets/1072753/12046021/15bf1ea4-ae64-11e5-961f-64190242db24.png)

On reload:

![try2](https://cloud.githubusercontent.com/assets/1072753/12046025/1a7ea93c-ae64-11e5-8a5b-b3afd450f36a.png)

**Comment by fabxc** [comment]
Thanks for reporting.
We should have a consistent order served by the API.

**Comment by mxinden** [comment]
Closing in favour of #812. @jamessanford please feel free to reopen.
