### ISSUE TITLE
Confuse about result notify with Slack!

### ISSUE THREAD

**Issue by chithanh89** [prometheus/alertmanager#2062]
**What did you do?**
I use alertmanager and rules of prometheus to notifi disk space to Slack channel.
**What did you expect to see?**
I expect to see same result of alert but i get a little different between host.
**What did you see instead? Under which circumstances?**
i get a little different between host.The host show full description and other host dont show anything in description.
**Environment**

* System information:
Ubuntu 16.04
	
* Alertmanager version:
0.17.0
	
* Prometheus version:
2.9.2
	insert output of `prometheus -version` here (if relevant to the issue)

* Alertmanager configuration file:
```global:
  slack_api_url: "https://hooks.slack.com/services/xxx"

route:
  group_by: ['instance', 'severity']
  group_wait: 30s
  group_interval: 5m
  receiver: 'alert-team'
  repeat_interval: 1h
  routes:
  - match:
      alertname: InstanceDown,HighCpuLoad,OutOfMemory,DiskSpace<60,DiskSpace<10

receivers:
- name: 'alert-team'
  slack_configs:
  - channel: "test-grafana"
    text: "summary: {{ .CommonAnnotations.summary }}\ndescription: {{ .CommonAnnotations.description }}"

```

* Prometheus configuration file:

![Selection_036](https://user-images.githubusercontent.com/11780091/66385426-aa486100-e9ea-11e9-9586-03a1ac495fe3.png)

* Logs:

![Selection_035](https://user-images.githubusercontent.com/11780091/66385445-b2080580-e9ea-11e9-841c-b2253bfd1745.png)

**Comment by simonpasquier** [comment]
This is working as expected as you're using the default Slack notification templates which shows only labels and annotations common across all alerts. The first notification message has more details because it contains only one alert.

**Comment by chithanh89** [comment]
@simonpasquier Tks so much, i understand.Have a nice day!
