### ISSUE TITLE
can't send message

### ISSUE THREAD

**Issue by swift201905** [prometheus/alertmanager#2065]
level=info ts=2019-10-10T15:17:00.709763456Z caller=bot.go:252 component=telegram msg="failed to process message" err="dropped message from forbidden sender" sender_id=860716746 sender_username=helloworldzz
level=info ts=2019-10-10T15:17:07.768582611Z caller=bot.go:252 component=telegram msg="failed to process message" err="dropped message from forbidden sender" sender_id=860716746 sender_username=helloworldzz
level=info ts=2019-10-10T15:17:25.033567143Z caller=bot.go:252 component=telegram msg="failed to process message" err="dropped message from forbidden sender" sender_id=860716746 sender_username=helloworldzz
level=info ts=2019-10-10T15:17:50.618377735Z caller=bot.go:252 component=telegram msg="failed to process message" err="dropped message from forbidden sender" sender_id=860716746 sender_username=helloworldzz
level=info ts=2019-10-10T15:18:00.656415154Z caller=bot.go:252 component=telegram msg="failed to process message" err="dropped message from forbidden sender" sender_id=860716746 sender_username=helloworldzz
level=info ts=2019-10-10T15:18:08.709905391Z caller=bot.go:252 component=telegram msg="failed to process message" err="dropped message from forbidden sender" sender_id=860716746 sender_username=helloworldzz
level=error ts=2019-10-10T14:07:24.571005078Z caller=bot.go:277 component=telegram msg="failed to get chat list from store" err="Key not found in store"
level=error ts=2019-10-10T14:07:44.534650949Z caller=bot.go:277 component=telegram msg="failed to get chat list from store" err="Key not found in store"

**Comment by swift201905** [comment]
ok

**Comment by simonpasquier** [comment]
Thanks @metalmatze :+1:
