### ISSUE TITLE
query - 2 Receivers in yml and i would like to use send request to one of the receivers using proxy?

### ISSUE THREAD

**Issue by pkvel01** [prometheus/alertmanager#2067]
Query on Alertmmanager.yml

I have 2 receivers in my alertmanager.yml and i wanted all my request to use proxy only for one of the receivers is it feasible ?

**Comment by stuartnelson3** [comment]
This is a usage question, which would be better directed to our user mailing list prometheus-users@googlegroups.com, where more people could benefit from this knowledge.
