### ISSUE TITLE
Slack messages can't send urls as markup

### ISSUE THREAD

**Issue by dmclain** [prometheus/alertmanager#207]
When I create a configuration that tries to do formatting of the `text` field like so:

    slack_configs:
        - text: "{{ range .Alerts }}*{{ .Annotations.description }}*<{{ .Annotations.generatorURL }}|View in Prometheus>\n{{ end }}"
          ...

The json that is sent to sentry escapes the `<` and `>` characters.

    "text":"*my alert's description*\u0026lt;http://prometheus:9090/graph#%5B%7B%22expr%22%3A%22node_filesystem_avail%20%2F%20node_filesystem_size%20%3C%200.5%20and%20node_filesystem_avail%20%2F%20-delta%28node_filesystem_avail%5B1d%5D%29%20%3E%200%20%3C%207%22%2C%22tab%22%3A0%7D%5D|View in Prometheus\u003e\n"

I believe this is because the json encoder object in the standard library makes the decision for the programmer to always escape those characters. (see https://golang.org/pkg/encoding/json/#Marshal and https://github.com/golang/go/issues/8592) 

For the slack notifier to support sending links as anything other than the full url (which would be useful for sending generatorURL) either a different method of converting to json or a second pass that unescapes those values will be necessary.

**Comment by fabxc** [comment]
It's really a shame that the `encoding/json` enforces this with no option to turn it off.
Seems like a post-processing step on the raw JSON that undos it is the only way – not really pretty.

**Comment by brian-brazil** [comment]
Have you filed a bug with Slack about this? It's likely that all other Go slack clients are affected, so they will probably want to fix this bug on their end.

**Comment by tisinno** [comment]
I think the problem is that the text field is not allowing markup. After adding the text field to this line:
		MrkdwnIn:  []string{"fallback", "pretext", "text"},
in notify/impl.go I can send markup and urls

**Comment by brian-brazil** [comment]
This still sounds like a bug in Slack if it can't handle escaped characters in json strings.

**Comment by tisinno** [comment]
the doc is a bit ambiguous to me but I think escaping < > & is actually required for slack api, see https://api.slack.com/docs/formatting. Here it seems to have used some unicode escaping as well, but apparently that doesn't matter, after allowing markup for the "text" field using the following in a template shows up fine in slack client: <http://github.com|TEST URL>

**Comment by fabxc** [comment]
So #240 will essentially fix this without post-processing the JSON?

**Comment by tisinno** [comment]
That change is the same as what I did (adding the field for allowing markup) and then tested with a slack formatted url as mentioned before in a template and it comes across fine in the slack client (displays a link "TEST URL" that when clicked opens the url).

**Comment by fabxc** [comment]
Great, thanks!
