### ISSUE TITLE
Slack incorrect URL encoding, using &quot; instead of %22

### ISSUE THREAD

**Issue by username1222** [prometheus/alertmanager#2070]
Alertmanager version 0.18.0
I've tested this on multiple machines, using different browsers.

I'm not sure whether this is an issue in Slack or Alertmanager, but here we go.

*Description*
I've created a "template to build silence URLs", for the silence button in Slack, see config below.

The silence button is properly shown and is created in Slack.

*Issue*
The URL redirects me to:
https://alertmanager.example.com/#/silences/new?filter=%7Bbutton_label%3D&quot;<snip>

The page opens, but with no silencer arguments filled in, making the silencer button broken.

**The issue here is that "&quote;" is used for httpd encoding**. This is incorrect, it should be *%22* to parse quotes.

When I click on the silence button with 'open in new tab', the correct page shows, because then it directs me to: https://alertmanager.example.com/#/silences/new?filter=%7Bbutton_label%3D%22<snip>

Can someone fix this in the Slack API or anywhere?

The alertmanager config
```yaml
    # This builds the silence URL.  We exclude the alertname in the range
    # to avoid the issue of having trailing comma separator (%2C) at the end
    # of the generated URL
    {{ define "__alert_silence_link" -}}
      {{ template ".ExternalURL" }}/#/silences/new?filter=%7B
      {{- range .SortedPairs -}}
        {{- if not (eq .Name "alertname") -}}
          {{- .Name }}%3D"{{- reReplaceAll " +" "%20" .Value -}}"%2C%20
        {{- end -}}
      {{- end -}}
      alertname%3D"{{ reReplaceAll " +" "%20" .alertname }}"%7D
    {{- end }}

    {{ define "__subject" }}{{ .Alerts.Firing | len }}{{ if .CommonLabels.severity }} {{ .CommonLabels.severity }}{{ end }}{{ if gt (.Alerts.Firing | len) 1 }} alerts{{ else }} alert{{ end }}{{ end }}
    {{ define "__description" }}{{ if .Annotations.description }}*Description:* {{ .Annotations.description }}{{ else }}{{ end }}{{ end }}

    {{ define "__text_alert_list" }}{{ range . }}Labels:
    {{ range .Labels.SortedPairs }} - {{ .Name }} = {{ .Value }}
    {{ end }}Annotations:
    {{ range .Annotations.SortedPairs }} - {{ .Name }} = {{ .Value }}
    {{ end }}Source: {{ .GeneratorURL }}
    {{ end }}{{ end }}

    {{ define "slack.default.title" }}{{ template "__subject" . }}{{ end }}
    {{ define ".ExternalURL" }}https://alertmanager.example.com{{ end }}
```

**Comment by brian-brazil** [comment]
That's a text template, so the issue is likely on Slack's end.

**Comment by username1222** [comment]
That's what I thought. I've contacted Slack Support. Hope they will fix it.

Thanks for taking your time!

**Comment by basroovers** [comment]
Not sure if Slack has fixed the issue, but after some tuning and basically replacing some double quotes with %22 I got it to work.

```
{{ define "__alert_silence_link" -}}
    {{ .ExternalURL }}/#/silences/new?filter=%7B
    {{- range .CommonLabels.SortedPairs -}}
        {{- if ne .Name "alertname" -}}
            {{- .Name }}%3D%22{{- reReplaceAll " +" "%20" .Value -}}%22%2C%20
        {{- end -}}
    {{- end -}}
    alertname%3D%22{{ reReplaceAll " +" "%20" .CommonLabels.alertname }}%22%7D
{{- end }}
```

**Comment by urusha** [comment]
> Not sure if Slack has fixed the issue, but after some tuning and basically replacing some double quotes with %22 I got it to work.
> 
> ```
> {{ define "__alert_silence_link" -}}
>     {{ .ExternalURL }}/#/silences/new?filter=%7B
>     {{- range .CommonLabels.SortedPairs -}}
>         {{- if ne .Name "alertname" -}}
>             {{- .Name }}%3D%22{{- reReplaceAll " +" "%20" .Value -}}%22%2C%20
>         {{- end -}}
>     {{- end -}}
>     alertname%3D%22{{ reReplaceAll " +" "%20" .CommonLabels.alertname }}%22%7D
> {{- end }}
> ```

Additional fix for `%` in a label value:
```
{{ define "__alert_silence_link" -}}
    {{ .ExternalURL }}/#/silences/new?filter=%7B
    {{- range .CommonLabels.SortedPairs -}}
        {{- if ne .Name "alertname" -}}
            {{- .Name }}%3D%22{{- reReplaceAll "%" "%25" .Value | reReplaceAll " +" "%20" -}}%22%2C%20
        {{- end -}}
    {{- end -}}
    alertname%3D%22{{ reReplaceAll "%" "%25" .CommonLabels.alertname | reReplaceAll " +" "%20" }}%22%7D
{{- end }}
