### ISSUE TITLE
Unexpected status code 400

### ISSUE THREAD

**Issue by s4kharitonov** [prometheus/alertmanager#2071]
**What did you do?**
I'm trying to send notifications from AlertManager to Zoom via Webhook Receiver Zoom running via docker (if need i can send link to github this third-party integration)

**What did you expect to see?**
Messages was successfully received

**What did you see instead? Under which circumstances?**
Message was successfully received, but in logs got: unexpected status code 400 and messages repeat every 5 minutes (if setting group_interval to 30 seconds messages will be repeated every 30 seconds)

**Environment**

* System information:

	Linux 4.15.0-65-generic x86_64

* Alertmanager version:

	version 0.19.0

* Prometheus version:

	version 2.12.0

* Alertmanager configuration file:
```
lobal:
  smtp_smarthost: '***'
  smtp_from: '***'
  smtp_auth_username: ***'
  smtp_auth_password: '***'

templates:
- '/etc/alertmanager/template/*.tmpl'

route:
  group_by: ['instance']
  group_wait: 5s
  group_interval: 5m
  repeat_interval: 24h
  receiver: webhook
  routes:
  - match:
      severity: critical
    receiver: webhook
  - match:
      severity: warning
    receiver: email



receivers:
- name: webhook
  webhook_configs:
  - url: http://internal-ip:8080

- name: email
  email_configs:
  - to: '***'
    send_resolved: true
```

* Prometheus configuration file:
```
# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - ip:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - "system.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # Prometheus
  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
    - targets:
      - ip:9090

  # Node_exporter (check system metrics)
  - job_name: 'system'
    static_configs:
    - targets:
      - ip:9100

```

* Logs:
```
Oct 16 14:28:41 alertmanager[24998]: level=debug ts=2019-10-16T14:28:41.032Z caller=dispatch.go:104 component=dispatcher msg="Received alert" alert=test_alert[36716b7][active]
Oct 16 14:28:46 alertmanager[24998]: level=debug ts=2019-10-16T14:28:46.033Z caller=dispatch.go:432 component=dispatcher aggrGroup="{}/{severity=\"critical\"}:{}" msg=flushing alerts=[test_alert[36716b7][active]]
Oct 16 14:28:46 alertmanager[24998]: level=debug ts=2019-10-16T14:28:46.263Z caller=notify.go:667 component=dispatcher msg="Notify attempt failed" attempt=1 integration=webhook receiver=webhook err="unexpected status code 400: http://ip:8080"
Oct 16 14:28:46 alertmanager[24998]: level=error ts=2019-10-16T14:28:46.263Z caller=notify.go:372 component=dispatcher msg="Error on notify" err="cancelling notify retry for \"webhook\" due to unrecoverable error: unexpected status code 400: http://ip:8080" context_err=null
Oct 16 14:28:46 alertmanager[24998]: level=error ts=2019-10-16T14:28:46.263Z caller=dispatch.go:266 component=dispatcher msg="Notify for alerts failed" num_alerts=1 err="cancelling notify retry for \"webhook\" due to unrecoverable error: unexpected status code 400: http://ip:8080"
```

* Docker Logs:
```
2019-10-16T14:28:46.036Z server:director 86018e83-e2d6-412b-b076-cf5510c9237d: POST / at 1571236126036
got 1 alerts, start processing.
2019-10-16T14:28:46.036Z server:extract-stage 86018e83-e2d6-412b-b076-cf5510c9237d: finish request extraction
2019-10-16T14:28:46.036Z server:relay-stage 86018e83-e2d6-412b-b076-cf5510c9237d: processing relay request (zoom-im) - POST https://inbots.zoom.us/incoming/hook/token?format=full
handle response of [req-86018e83-e2d6-412b-b076-cf5510c9237d] - 200
 "OK"
2019-10-16T14:28:46.262Z server:relay-stage 86018e83-e2d6-412b-b076-cf5510c9237d: finish request relay
2019-10-16T14:28:46.262Z server:response-stage 86018e83-e2d6-412b-b076-cf5510c9237d: finish response composing
2019-10-16T14:28:46.262Z server:director 86018e83-e2d6-412b-b076-cf5510c9237d: done in 226 ms
```

I know that there is no native support for this chat, but could you tell me which way it is worth looking to solve this problem, any suggestions? Taking into account the fact that I receive messages from alertmanager in zoom chat [https://imgur.com/a/PNOKbxo](url)

**Comment by simonpasquier** [comment]
I'm afraid that there's nothing to be done from Alertmanager's point of view. If the webhook service returns 400, it means for Alertmanager that the request wasn't successful so it will retry on the next group interval. You'll have to fix the webhook service.

I'm closing it for now. If you have further questions, please use our [user mailing list](https://groups.google.com/forum/#!forum/prometheus-users), which you can also search.

**Comment by s4kharitonov** [comment]
@simonpasquier How to send http code from webhook to alertmanager?  In my case, messages are sent and in the docker log I see that it returns 200

**Comment by simonpasquier** [comment]
There's something else happening then because Alertmanager logs say `unexpected status code 400: http://ip:8080`.

**Comment by s4kharitonov** [comment]
@simonpasquier I understand and see this, but how do I correctly transfer the status of successful delivery to alertmanager? How should alertmanager understand that the message was sent successfully, how and where is it checked?

**Comment by simonpasquier** [comment]
See here

https://github.com/prometheus/alertmanager/blob/cb10f277c1fddae7bf722af0d745fdab96168290/notify/webhook/webhook.go#L57-L62

And

https://github.com/prometheus/alertmanager/blob/cb10f277c1fddae7bf722af0d745fdab96168290/notify/util.go#L165-L196
