### ISSUE TITLE
Only first silencer filter from UI is respected

### ISSUE THREAD

**Issue by Scott8440** [prometheus/alertmanager#2073]
**What did you do?**

- Used UI (http://alertmanager-host/#/silences) to view silencers.
- Create silencer with matcher: string="string"
- Add filter string="string" in filter text field.
  - Silencer is listed as expected
- Add filters test="test", string="string" in filter text field
  - No silencer is listed (as expected)
- Add filters string="string", test="test"
  - The previously created silencer is listed (Unexpected)

**What did you expect to see?**
- Expected to see the silencer listed only when it matched all filters provided in the search box

**What did you see instead? Under which circumstances?**
- Silencer was listed when it matched the first filter in the search box, ignoring all following filters

**System information:**
Darwin 18.7.0 x86_64

**Alertmanager version:**
alertmanager, version 0.19.0 (branch: HEAD, revision: 7aa5d19fea3f58e3d27dbdeb0f2883037168914a)
  build user:       root@587d0268f963
  build date:       20190903-15:04:14
  go version:       go1.12.8

**Comment by simonpasquier** [comment]
Thanks for spotting this! I've submitted #2075.
