### ISSUE TITLE
Notify for alerts failed because of context deadline exceeded

### ISSUE THREAD

**Issue by vishnu-vardhan-reddy** [prometheus/alertmanager#2095]
We upgraded alertmanager from v0.14 to v0.16.

Configuration Chnages ::
1. Changed HA configuration (mesh to cluster).
2. Added proxy_url in http_config with our proxy.

Alertmanager is failing to send slack go1.11.13, following error we can see in logs.

* System information:

	Oracle Linux Server release 7.4

* Alertmanager version:

	v0.16 ( GoVersion - go1.11.13)

* Prometheus version:

	v2.2.0 ( GoVersion - go1.10.1)

Log Messages
level=error ts=2019-11-05T09:55:38.377773199Z caller=notify.go:332 component=dispatcher msg="Error on notify" err="Post https://hooks.slack.com/services/XXXX/XXXX/XXXX: context deadline exceeded"
level=error ts=2019-11-05T09:55:38.377861637Z caller=dispatch.go:177 component=dispatcher msg="Notify for alerts failed" num_alerts=1 err="Post https://hooks.slack.com/services/XXXX/XXXX/XXXX: context deadline exceeded"

Do we need to change any other configuration in this upgrade?

**Comment by simonpasquier** [comment]
Thanks for your report. It looks as if this is actually a question about usage and not development. The `context deadline exceeded` message means that Alertmanager can't connect to the Slack API. Given that you use a proxy, I would check there.

To make your question, and all replies, easier to find, we suggest you move this over to our [user mailing list](https://groups.google.com/forum/#!forum/prometheus-users), which you can also search. If you prefer more interactive help, join or our [IRC channel](https://webchat.freenode.net/?randomnick=1&channels=prometheus), #prometheus on irc.freenode.net. Please be aware that our IRC channel has no logs, is not searchable, and that people might not answer quickly if they are busy or asleep. If in doubt, you should choose the mailing list.

Once your questions have been answered, please add a short line pointing to relevant replies in case anyone stumbles here via a search engine in the future.
