### ISSUE TITLE
find all metrics

### ISSUE THREAD

**Issue by FunkyYang** [prometheus/alertmanager#2097]
I install alertmanager online today.and I use grafana dashboard for alertmanager (grafana dashboard id:9578).
then I install this dashboard .find all data is missing.I view the labels `alertmanager_build_info{instance=~"$instance"}`.
and I view alertmanager metrics at http://localhost:9093/metrics . there is no alertmanager_build_info labels which is hold instance info in it.
I wonder why ?

**Comment by simonpasquier** [comment]
The `alertmanager_build_info` metric is present in Alertmanager v0.19.0 at least, not sure which version you're using.

I'm closing it for now. If you have further questions, please use our [user mailing list](https://groups.google.com/forum/#!forum/prometheus-users), which you can also search.

**Comment by innoag** [comment]
same issue i found out /metrics but missing alertmanager_build_info for $instance

alertmanager, version 0.25.0 (branch: HEAD, revision: 258fab7cdd551f2cf251ed0348f0ad7289aee789)
  build user:       root@abe866dd5717
  build date:       20221222-14:51:36
  go version:       go1.19.4
  platform:         linux/amd64

<hostname>:9063/metrics info
...
alertmanager_build_info{branch="HEAD",goversion="go1.19.4",revision="258fab7cdd551f2cf251ed0348f0ad7289aee789",version="0.25.0"} 1
