### ISSUE TITLE
Multiple alertrules.yml is work?

### ISSUE THREAD

**Issue by Yuanyp8** [prometheus/alertmanager#2100]
# config
rule_files:
- /opt/prometheus/current/alert_rules/*.yml

# note
Write an alertrules. Yml for each server to see if this works

**Comment by simonpasquier** [comment]
This is a question for Prometheus but yes Prometheus configuration supports the definition of rule files using wildcard search. See https://prometheus.io/docs/prometheus/latest/configuration/configuration/.

I'm closing it for now. If you have further questions, please use our [user mailing list](https://groups.google.com/forum/#!forum/prometheus-users), which you can also search.
