### ISSUE TITLE
Slack Integration does not respect rate limiting

### ISSUE THREAD

**Issue by gavk34** [prometheus/alertmanager#2111]
**What did you do?**
Starting seeing the following errors in AlertManager

```
level=error ts=2019-11-21T09:02:58.967Z caller=notify.go:372 component=dispatcher msg="Error on notify" err="cancelling notify retry for \"slack\" due to unrecoverable error: unexpected status code 429: {\"retry_after\":1,\"ok\":false,\"error\":\"rate_limited\"}" context_err=null
level=error ts=2019-11-21T09:02:58.967Z caller=dispatch.go:266 component=dispatcher msg="Notify for alerts failed" num_alerts=2 err="cancelling notify retry for \"slack\" due to unrecoverable error: unexpected status code 429: {\"retry_after\":1,\"ok\":false,\"error\":\"rate_limited\"}"
```

**What did you expect to see?**
I would expect the dispatcher to respect the `retry_after` and try later rather than failing

**What did you see instead? Under which circumstances?**
Increase volume of alerts triggered

**Environment**

* System information:

	Docker container

* Alertmanager version:

	v0.19.0

* Prometheus version:

	N/A

* Alertmanager configuration file:
N/A - contains confidential information

* Prometheus configuration file:
N/A

* Logs:
```
level=error ts=2019-11-21T09:02:58.967Z caller=notify.go:372 component=dispatcher msg="Error on notify" err="cancelling notify retry for \"slack\" due to unrecoverable error: unexpected status code 429: {\"retry_after\":1,\"ok\":false,\"error\":\"rate_limited\"}" context_err=null
level=error ts=2019-11-21T09:02:58.967Z caller=dispatch.go:266 component=dispatcher msg="Notify for alerts failed" num_alerts=2 err="cancelling notify retry for \"slack\" due to unrecoverable error: unexpected status code 429: {\"retry_after\":1,\"ok\":false,\"error\":\"rate_limited\"}"
```

**Comment by roidelapluie** [comment]
Alertmanager has its internal retry mechanism. Using a value provided by upstream would have bad effects on high availability as you could get multiple times the same notification.

**Comment by gavk34** [comment]
@roidelapluie If that is the case it might be good to ignore such errors in `alertmanager_notifications_failed_total` as they are triggering alerts for us, even though as you say AlertManager is able to handle this scenario internally.

**Comment by roidelapluie** [comment]
Mmh wait. No you are right, alertmanager will not retry 4XX errors.

**Comment by roidelapluie** [comment]
See #2112

**Comment by gavk34** [comment]
@roidelapluie @simonpasquier Thanks for the quick fix guys! 👍

**Comment by gavk34** [comment]
@roidelapluie @simonpasquier Any idea when the next AlertManager release is going to be? I see Prometheus got updated this month, but AlertManager hasn't seen an update since September. Thanks

**Comment by simonpasquier** [comment]
I'm planning a new release soon (eg this week probably). As you noticed, it's been almost 3 months since the last one.

**Comment by simonpasquier** [comment]
https://github.com/prometheus/alertmanager/releases/tag/v0.20.0-rc.0 is ready to test :smiley:

**Comment by vvxxvvxx** [comment]
encounter the similar issue using vmalertmanager v0.24.0 https://github.com/prometheus/alertmanager/issues/3189
