### ISSUE TITLE
Allow alertmanager to be run behind a reverse proxy

### ISSUE THREAD

**Issue by grobie** [prometheus/alertmanager#212]
The `-web.external-url` flag is no longer respected when loading assets. It's no  longer possible to run alertmanager behind a reverse proxy.

**Comment by a86c6f7964** [comment]
FYI I just did https://github.com/novilabs/alertmanager/commit/50937b09100abcc1d28f933baa38e2b22aa0ef01 to be able to use a prefix path of ```/alerts``` and run it behind my reverse proxy. It seems to be working well. I do not know a way to pass it through as configuration to the html and js files though. If anybody wants to know what files would need to be touched.

**Comment by hryamzik** [comment]
```-web.external-url``` does seem to be broken (again?). @grobie, any comments on this?

**Comment by grobie** [comment]
It never got fixed so far unfortunately. Pull requests very welcome, I think all core contributors are very overworked right now.

**Comment by juliusv** [comment]
Just looking at it, I got it almost working, except for one thing: the `index.html` is a static HTML page (not a Go template), so we can't inject the path prefix into it to fix up the JS and CSS asset links. Should we serve the web pages (at least `index.html`) through the Go template engine, like we do in Prometheus?

**Comment by fabxc** [comment]
Without a closer look – that doesn't seem like something that should depend on passing through a template engine.
If it comes with complexity I cannot think of right now, sure – it doesn't have a relevant overhead.

**Comment by juliusv** [comment]
@fabxc True. The alternative is to make all the paths between the assets relative. Trying that out now, it seems to work. It would mean that one has to be careful to not introduce any absolute paths anywhere, ever. But requiring a path prefix everywhere in the HTML+JS would have the same problem. Should I go for relative paths then?

**Comment by fabxc** [comment]
Sure, it's not that many files and won't change frequently.

**Comment by mrwacky42** [comment]
+1 to relative paths.

**Comment by juliusv** [comment]
Cool. Fix is out in https://github.com/prometheus/alertmanager/pull/289/files.

**Comment by sdwerwed** [comment]
I made it work like this (`--web.external-url` not `-web.external-url`)
`/usr/local/bin/alertmanager --config.file /etc/alertmanager/alertmanager.yml --web.external-url=http://example.com:9093/alertmanager` then add to nginx `location /alertmanager {proxy_pass http:localhost:9093/;}`
