### ISSUE TITLE
Webhook Notifier 429 Handling

### ISSUE THREAD

**Issue by justinwatkinson** [prometheus/alertmanager#2121]
**What did you do?**

Instrumented a webhook receiver to receive Alertmanager payloads to forward to a 3rd party system.

**What did you expect to see?**

When the destination webhook returns a 429 error, the retry logic with back-off should be applied.

**What did you see instead? Under which circumstances?**

429 is treated the same as a 404 or other client error, which does longer retries (10 sec according to my local tests).

**Environment**

* System information:

Linux 4.15.0-54-generic x86_64

* Alertmanager version:

Master (89db9090177c13e1ee5e72ae81e1713a6288a637) & 0.19.0

* Prometheus version:

N/A

* Alertmanager configuration file:
```
global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'web.hook'
receivers:
- name: 'web.hook'
  webhook_configs:
  - url: 'http://127.0.0.1:9001/'

```

* Prometheus configuration file:
N/A

* Logs:
```
level=error ts=2019-11-30T03:20:43.832Z caller=notify.go:372 component=dispatcher msg="Error on notify" err="unexpected status code 429: http://127.0.0.1:9001/" context_err="context deadline exceeded"
level=error ts=2019-11-30T03:20:43.832Z caller=dispatch.go:301 component=dispatcher msg="Notify for alerts failed" num_alerts=1 err="unexpected status code 429: http://127.0.0.1:9001/"
level=error ts=2019-11-30T03:20:53.833Z caller=notify.go:372 component=dispatcher msg="Error on notify" err="Post http://127.0.0.1:9001/: dial tcp 127.0.0.1:9001: connect: connection refused" context_err="context deadline exceeded"
level=error ts=2019-11-30T03:20:53.833Z caller=dispatch.go:301 component=dispatcher msg="Notify for alerts failed" num_alerts=1 err="Post http://127.0.0.1:9001/: dial tcp 127.0.0.1:9001: connect: connection refused"
```

**Sample 429 Code**
```
package main

import (
	"log"
	"net/http"
)

func handler(rw http.ResponseWriter, r *http.Request) {
	log.Println("Received call")
	rw.WriteHeader(http.StatusTooManyRequests)
}

func main() {
	http.HandleFunc("/", handler)
	http.ListenAndServe(":9001", nil)
}
```

Sample Logs from http server
```
2019/11/29 21:19:34 Received call
2019/11/29 21:19:44 Received call
2019/11/29 21:19:54 Received call
```

Sample Logs when adding 429 to retry (same as 5xx):
```2019/11/29 21:20:33 Received call
2019/11/29 21:20:34 Received call
2019/11/29 21:20:34 Received call
2019/11/29 21:20:35 Received call
2019/11/29 21:20:37 Received call
2019/11/29 21:20:39 Received call
2019/11/29 21:20:42 Received call
2019/11/29 21:20:43 Received call
2019/11/29 21:20:44 Received call
2019/11/29 21:20:45 Received call
2019/11/29 21:20:46 Received call
2019/11/29 21:20:48 Received call
```

**Comment by roidelapluie** [comment]
I think we could just implement 429 for all the notifiers, what do you
think Simon?

Le sam. 30 nov. 2019 à 04:29, Justin Watkinson <notifications@github.com> a
écrit :

**Comment by simonpasquier** [comment]
I think we shouldn't retry forcefully as it can do more harm than good.

Looking at the various integrations, some of them provide hints on how you should retry once you're rate-limited:
*  [OpsGenie](https://docs.opsgenie.com/docs/api-rate-limiting#section-handling-throttles-and-request-delays)
* [Slack](https://api.slack.com/docs/rate-limits#headers)
* [PagerDuty](https://v2.developer.pagerduty.com/docs/rate-limiting)
* [PushOver](https://pushover.net/api#limits)

[VictorOps](https://help.victorops.com/knowledge-base/api/) doesn't provide much details and I can't understand the WeChat API documentation.

So I'd say: apply retry guidelines when known and when unknown (webhook, VictorOps, WeChat), we should retry with backoff.

**Comment by justinwatkinson** [comment]
I like the above approach myself.  Try to be correct and within spec.  Probably doesn't change often enough.  What are the thoughts on something like PagerDuty waiting a minute to retry, that seems like a long time.

**Comment by brian-brazil** [comment]
If you want the alertmanager to retry, change the receiver to send back a 5xx. 4xx means not to retry.

**Comment by justinwatkinson** [comment]
This is how I worked around the issue.  Based on PR comments, looks like there's nothing left to pursue at this time.
