### ISSUE TITLE
alert "invalid" counter has a mistake

### ISSUE THREAD

**Issue by meichuntao** [prometheus/alertmanager#2123]
https://github.com/prometheus/alertmanager/blob/b783cf8e60a7363c3fa4294b53d6cdf87190ada9/api/metrics/metrics.go#L54

I  think that is a mistake
it should be
func (a *Alerts) Invalid() prometheus.Counter { return a.invalid}

**Comment by simonpasquier** [comment]
Nice catch! Do you want to submit a PR for this?

**Comment by meichuntao** [comment]
No,I don't want to submit a PR for some reason.
Can someone help me to submit a PR to fix it?

**Comment by simonpasquier** [comment]
Not sure about your answer @meichuntao but the change is easy: it means replacing ` a.firing` by `a.invalid` at this [line](https://github.com/prometheus/alertmanager/blob/b783cf8e60a7363c3fa4294b53d6cdf87190ada9/api/metrics/metrics.go#L54).

If you're unsure how to submit your contribution, check those links:
https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/working-with-forks
https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork


When committing your changes, don't forget to sign the commit:
 
```
git commit api/metrics/metrics.go -s -m "Fix typo"
```

**Comment by meichuntao** [comment]
ok,thanks.
I  have already submit a PR for this.
