### ISSUE TITLE
Silence Alerts using api v1

### ISSUE THREAD

**Issue by addy3494** [prometheus/alertmanager#2127]
**What did you do?**

curl -H "Content-Type: application/json" -X POST -d '{"endsAt": "2019-12-04T08:35:54.713Z","matchers": [{"isRegex": false,"name": "alertname","value": "Instance Down"},{"isRegex": false,"name": "instance","value": "Instance"},{"isRegex": false,"name": "job","value": "Env"}],"Comment": "ALERT-SILENCE","createdBy": "Team"}' http://10.20.210.345:9093/api/v1/silences

**What did you expect to see?**
want to trigger with Duration and not startsAt or endsAt

Referred - https://github.com/prometheus/alertmanager/blob/master/template/template_test.go
cant find a way to use api with duration

**Comment by simonpasquier** [comment]
The `startsAt` and `endsAt` fields are mandatory. Note that the API v1 is deprecated and you should probably look at the [v2 API](https://github.com/prometheus/alertmanager#api) which has an Open API specification.

I'm closing it for now. If you have further questions, please use our [user mailing list](https://groups.google.com/forum/#!forum/prometheus-users), which you can also search.
