### ISSUE TITLE
emails being queued with Azure Sendgrid

### ISSUE THREAD

**Issue by gbecki** [prometheus/alertmanager#2138]
Hello
I'm currently using a Azure's Sendgrid account to handle my notifications, but the emails is being queued and the logs don't show why even with debug mode.   

Alertmanager version is: 0.20.0-rc.0 (tried 0.19.0 too)

Here is my configuration:

	global:
	  resolve_timeout: 5m
	  http_config: {}
	  smtp_from: alertmanager@smtp.sendgrid.net
	  smtp_hello: localhost
	  smtp_smarthost: smtp.sendgrid.net:587
	  smtp_auth_username: azure_5c531bc5bc4fd1aae66c3d0432200d8f@azure.com
	  smtp_auth_password: <secret>
	  smtp_auth_identity: azure_5c531bc5bc4fd1aae66c3d0432200d8f@azure.com
	  smtp_require_tls: true
	  pagerduty_url: https://events.pagerduty.com/v2/enqueue
	  hipchat_api_url: https://api.hipchat.com/
	  opsgenie_api_url: https://api.opsgenie.com/
	  wechat_api_url: https://qyapi.weixin.qq.com/cgi-bin/
	  victorops_api_url: https://alert.victorops.com/integrations/generic/20131114/alert/
	route:
	  receiver: equipe_monitoramento
	  group_by:
	  - alertname
	  - cliente
	  routes:
	  - receiver: buraco_negro
	    match:
	      severity: warning
	  group_wait: 30s
	  group_interval: 10m
	  repeat_interval: 6h
	inhibit_rules:
	- source_match:
	    severity: critical
	  target_match:
	    severity: high
	  equal:
	  - alertname
	  - instance
	- source_match:
	    severity: high
	  target_match:
	    severity: warning
	  equal:
	  - alertname
	  - instance
	receivers:
	- name: buraco_negro
	- name: equipe_monitoramento
	  email_configs:
	  - send_resolved: true
	    to: beckiguilherme@gmail.com
	    from: alertmanager@smtp.sendgrid.net
	    hello: localhost
	    smarthost: smtp.sendgrid.net:587
	    auth_username: azure_5c531bc5bc4fd1aae66c3d0432200d8f@azure.com
	    auth_password: <secret>
	    auth_identity: azure_5c531bc5bc4fd1aae66c3d0432200d8f@azure.com
	    headers:
	      From: alertmanager@smtp.sendgrid.net
	      Subject: '{{ template "email.default.subject" . }}'
	      To: beckiguilherme@gmail.com
	    html: '{{ template "email.default.html" . }}'
	    require_tls: true
	    tls_config:
	      insecure_skip_verify: true
	templates:
	- /etc/alertmanager/template/*.tmpl	

Please let me know if i missing some configuration bits.
Thank you

**Comment by simonpasquier** [comment]
Thanks for your report. It looks as if this is actually a question about usage and not development.

To make your question, and all replies, easier to find, we suggest you move this over to our [user mailing list](https://groups.google.com/forum/#!forum/prometheus-users), which you can also search. If you prefer more interactive help, join or our [IRC channel](https://webchat.freenode.net/?randomnick=1&channels=prometheus), #prometheus on irc.freenode.net. Please be aware that our IRC channel has no logs, is not searchable, and that people might not answer quickly if they are busy or asleep. If in doubt, you should choose the mailing list.

Once your questions have been answered, please add a short line pointing to relevant replies in case anyone stumbles here via a search engine in the future.
