### ISSUE TITLE
How to do when I want to update my alert rule frequently from different users?

### ISSUE THREAD

**Issue by readygodom** [prometheus/alertmanager#2144]
I know that if I want to add or modify an alert rule, I can modify the 'alerts.yml'.
Such as:
    - alert: example
        expr: >-
          ceph_pool_stats_write_bytes_sec{name="service-1"} >  70000000.0
        for: 3m
        labels:
          route: "email"
          severity: "warning"
          service: "example-1"
        annotations:
          description: "This is an example."
          summary: "This is an example."

 But a case is when the alert rules would be modified by different users, I do not think it is a good strategy that modifying a single 'alert.yml' file. Any other strategy can be offered?

**Comment by simonpasquier** [comment]
Thanks for your report. It looks as if this is actually a question about usage and not development.

To make your question, and all replies, easier to find, we suggest you move this over to our [user mailing list](https://groups.google.com/forum/#!forum/prometheus-users), which you can also search. If you prefer more interactive help, join or our [IRC channel](https://webchat.freenode.net/?randomnick=1&channels=prometheus), #prometheus on irc.freenode.net. Please be aware that our IRC channel has no logs, is not searchable, and that people might not answer quickly if they are busy or asleep. If in doubt, you should choose the mailing list.

Once your questions have been answered, please add a short line pointing to relevant replies in case anyone stumbles here via a search engine in the future.
