### ISSUE TITLE
amtool: error: strconv.ParseBool: parsing "0.20.0": invalid syntax

### ISSUE THREAD

**Issue by OGKevin** [prometheus/alertmanager#2160]
**What did you do?**
```
/workdir # amtool check-config /tmp/am-check.yaml
amtool: error: strconv.ParseBool: parsing "0.20.0": invalid syntax
```
```
/workdir # amtool check-config
amtool: error: strconv.ParseBool: parsing "0.20.0": invalid syntax
```
```
/workdir # cat /tmp/am-check.yaml | grep "0.20.0"
/workdir #
```

```
/workdir # amtool check-config this-file-does-not-exist.yaml
amtool: error: strconv.ParseBool: parsing "0.20.0": invalid syntax
```

**What did you expect to see?**
If my AM config is valid or not
**What did you see instead? Under which circumstances?**
An error message saying that it could not parse a bool. Most likely it tries to parse the version number as bool. But A quick reading of the code and i could not find the faulty code.
**Environment**

* System information:

	`Linux 4.9.184-linuxkit x86_64`

* Alertmanager version:

```
/workdir # amtool --version
amtool, version 0.20.0 (branch: HEAD, revision: f74be0400a6243d10bb53812d6fa408ad71ff32d)
  build user:       root@00c3106655f8
  build date:       20191211-14:13:14
  go version:       go1.13.5
```

**Comment by FUSAKLA** [comment]
Hi, I tested it on the exact revision and everything seems to be working fine.
Do you happen to use the amtool config? Anything in `$HOME/.config/amtool/config.yml` or `/etc/amtool/config.yml` files?

**Comment by OGKevin** [comment]
@FUSAKLA 

```
/ # ls $HOME/.config/amtool/config.yml
ls: cannot access '/root/.config/amtool/config.yml': No such file or directory
/ # ls /etc/amtool/config.yml
ls: cannot access '/etc/amtool/config.yml': No such file or directory
/ #
```

```
/ # cat /proc/version
Linux version 4.9.184-linuxkit (root@a8c33e955a82) (gcc version 8.3.0 (Alpine 8.3.0) ) #1 SMP Tue Jul 2 22:58:16 UTC 2019
/ #
```

The base image of this docker container is `google/cloud-sdk:alpine` 

The way amtool is then installed:

```
/ # export AMTOOL_VERSION=0.20.0
/ # curl -fsSLo alertmanager.tar.gz https://github.com/prometheus/alertmanager/releases/download/v$AMTOOL_VERSION/alertmanager-$AMTOOL_VERSION.linux-amd64.tar.gz && \
        tar -xvf alertmanager.tar.gz alertmanager-$AMTOOL_VERSION.linux-amd64/amtool && \
        mv alertmanager-$AMTOOL_VERSION.linux-amd64/amtool /usr/local/bin/ && \
        rm -rf alertmanager.tar.gz alertmanager-$AMTOOL_VERSION.linux-amd64 && \
        chown root:root /usr/local/bin/amtool && \
        chmod 0755 /usr/local/bin/amtool && \
        amtool --version 
```

and then 

```
/ # amtool check-config
amtool: error: strconv.ParseBool: parsing "0.20.0": invalid syntax
```

**Comment by FUSAKLA** [comment]
Hmm ok it does not happen with amtool in the official docker image nor with own built amtool.

But it happens with every prebuilt binary from releases assets not just with the 0.20.0
Interesting, I wonder how the build differs. Will take a look.

**Comment by simonpasquier** [comment]
This is a side-effect of setting the `AMTOOL_VERSION` environment variable. kingpin (the CLI library) sees the variable and understands it as `--version 0.20.0`. If you unset `AMTOOL_VERSION`, it should work.

**Comment by brian-brazil** [comment]
Can we disable all of that? We should be consistent with this in all binaries.

**Comment by simonpasquier** [comment]
I wanted to dig into the history why it's this way but yes I also think that it should be removed.

**Comment by OGKevin** [comment]
@simonpasquier nice find! I can confirm 😊.

I scrolled through the code again to see how AM uses kinpin but i could not quickly see how/where kingpin reads this env var. Mind pointing out the faulty code? 

https://github.com/alecthomas/kingpin/blob/58b63589c076f22b08ef3aee66e730e382321278/app.go#L263-L272

Seems to be where version gets parsed as a bool which is weird, but still dont see a mention of env vars 🤔

**Comment by simonpasquier** [comment]
The call is here:

https://github.com/prometheus/alertmanager/blob/04ca50712575584666754d2245f70a66e2009ccd/cli/root.go#L92

**Comment by OGKevin** [comment]
Yea was about to comment that. Ran the debugger and found it indeed. This leads to 

```
func envarTransform(name string) string {
	return strings.ToUpper(envarTransformRegexp.ReplaceAllString(name, "_"))
}

```

getting callend in kingpin which results in `AMTOOL_VERSION`

**Comment by OGKevin** [comment]
Ah i understand tho whole problem now 😅  its being parsed as bool because a bool flag is the nicest way to get `--version` to work as a flag without having to specify anything explicit. Interesting approach with an interesting side affect.

**Comment by FUSAKLA** [comment]
Cool, I wasn't aware of that function of kingpin either TIL :)

**Comment by OGKevin** [comment]
@brian-brazil Do you want me to create pull request to disable the default env vars functionality ? Or what is the plan here?

**Comment by brian-brazil** [comment]
That appears to be the plan, so please go ahead.

**Comment by OGKevin** [comment]
so what is stopping this mr from getting 👀 did i miss something ?
