### ISSUE TITLE
feature request: notification pipeline extension

### ISSUE THREAD

**Issue by alburthoffman** [prometheus/alertmanager#2163]
**Background**
There is a case that we want to persist all alerts as events in our database. In current alert manager model, this will need users to define webhook to do that. This is almost undoable because if users want to define their own webhook service.

**Feature Description**
Assume there is an extension point in alert manager notification pipeline, which allow us to plugin user defined command/code. then it would be easy to do this.

this extension point might be one stage in https://github.com/prometheus/alertmanager/blob/master/notify/notify.go#L264

It would be good if we can support cases like:

1. persist all alerts to other places
1. add a new integration like ServiceNow.
1. replace one integration like PagerDuty to use internal data for routing automatically

I would like to open the discussion here to gather rejections or supports. If doable, I can start preparing the PR for this feature.

**Comment by brian-brazil** [comment]
What exactly is it that the webhook wouldn't support? I believe it can do everything you list.

**Comment by alburthoffman** [comment]
let's say we use webhook to persist all alerts to our long term storage.
then user want to define their own webhook service.
In this case user defined webhook will override the webhook we defined in system, right?
So how does it support this persistent case?

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
