### ISSUE TITLE
Enforce 512KB event size limit for PagerDuty events

### ISSUE THREAD

**Issue by shamilpd** [prometheus/alertmanager#2178]
PagerDuty will soon start enforcing a 512 KB event size limit on both the V1 and V2 api (https://v2.developer.pagerduty.com/docs/events-api-v2). This limit has been mentioned in the documentation for a while but was not enforced.

We regularly receive events that breach this limit. After investigating we found that these large events are formed by giant text blobs from the `firing` and `resolving` fields (https://github.com/prometheus/alertmanager/blob/master/config/notifiers.go#L49-L50) in `details`. It appears that these fields can have the descriptions of an unbounded list of alerts. These lists can be viewed in the PagerDuty UI but it's not clear how valuable they are to the users when the list becomes very large (over a hundred).

We have a few proposals for fixing this issue:

1. The simplest option is to truncate the `firing` and `resolving` fields to 250KB each which will leave 12KB for the rest of the message.

2. Truncate `firing` to 500KB. If it needs less than 500KB, the rest is used for `resolving` (or reverse the order if `resolving` is deemed more important than `firing`). Basically we ensure that the space taken up by `firing` plus `resolving` doesn't exceed 500KB but without a hard boundary on each field.

3. The above two options have the possibility that the truncation can happen inside an alert description. If it's important to make sure that alert descriptions are always displayed in full, we can apply a limit on the number of alerts used to render `firing` and `resolving`. However, unless this limit is quite small, it won't do a good job of ensuring that the full message size is below 512KB because the size of alert descriptions can vary.

We prefer options one or two. Regardless of what option is chosen, there should also be a size check after the message is encoded into JSON. If other text fields are added to the message in the future, this check will make sure that overall message size is under 512KB.

**Comment by simonpasquier** [comment]
We already do this kind of limit checks at other places but AFAICT it's never been the case for the posted payload itself. We can't rely on the `firing` and `resolving` keys being present in the custom details as the user is able to change this from the configuration.
I'd rather check the size of the message to be posted. If it is above the 512KB limit, we replace the `Custom Details` field (which is likely the offender) with something like `{"warning": "custom details not included because otherwise the message would exceed the maximum size of 512KB."}`.

**Comment by shamilpd** [comment]
That sounds good to me! 
I will get started on a PR for this soon. 
Do you know when the next alertmanager release is planned to come out?

**Comment by roidelapluie** [comment]
There is no fixed planning at this stage as the repo is not hyper active.

**Comment by simonpasquier** [comment]
There's no established planning but I try to release a new version every 3 to 4 months even if there's not a lot of changes.

**Comment by simonpasquier** [comment]
Closed by #2225
