### ISSUE TITLE
Prometheus port 9090 Not Found

### ISSUE THREAD

**Issue by Daly123456** [prometheus/alertmanager#2180]
after setting up prometheus and working with black box exporter to verify ssl expiry i wanted to try node-exporter but i faced this problem :
Prometheus-server : failed
This commande:
telnet <ip-server> <port number> worked with port: 9100 9115 9117 9093 9094 but not with  9090
This is my prometheus.yml file : 
![image](https://user-images.githubusercontent.com/46686877/74220869-0250e600-4cb1-11ea-8214-345b9f962691.png)
![image](https://user-images.githubusercontent.com/46686877/74220935-2d3b3a00-4cb1-11ea-8ead-893342bebf2c.png)

**Comment by simonpasquier** [comment]
Thanks for your report. It looks as if this is actually a question about usage and not development.

To make your question, and all replies, easier to find, we suggest you move this over to our [user mailing list](https://groups.google.com/forum/#!forum/prometheus-users), which you can also search. If you prefer more interactive help, join or our [IRC channel](https://webchat.freenode.net/?randomnick=1&channels=prometheus), #prometheus on irc.freenode.net. Please be aware that our IRC channel has no logs, is not searchable, and that people might not answer quickly if they are busy or asleep. If in doubt, you should choose the mailing list.

Once your questions have been answered, please add a short line pointing to relevant replies in case anyone stumbles here via a search engine in the future.

**Comment by Daly123456** [comment]
simonpasquier you re not helping me :D

**Comment by simonpasquier** [comment]
Sorry but we don't use GitHub issues for troubleshooting user installations. Reach out on IRC or the mailing list and I'm sure you'll get help.
