### ISSUE TITLE
how to send email to more people in one receiver

### ISSUE THREAD

**Issue by ycwdaaaa** [prometheus/alertmanager#2186]
like below, I want to send mail to 2 people in one receiver, but it does not work:
  - name: 'sdp'
    email_configs:
      - require_tls: true
        to: ['panxin@4paradigm.com', 'jinkai@4paradigm.com']
        tls_config:
          insecure_skip_verify: true

**Comment by simonpasquier** [comment]
The `to` field is a string containing the list of addresses, not an array: `"panxin@4paradigm.com, jinkai@4paradigm.com"`.

I'm closing it for now. If you have further questions, please use our [user mailing list](https://groups.google.com/forum/#!forum/prometheus-users), which you can also search.
