### ISSUE TITLE
alias terms from ElasticSearch not recognized by alertmanager

### ISSUE THREAD

**Issue by balusarakesh** [prometheus/alertmanager#2189]
**What did you do?**
 - We imported the `monitoring-es-*` index from ELK  as a datasource to monitor our ELK cluster
 - I've created an alert for CPU usage on 4 nodes available (master and data nodes)
 - In the Query we have alias like this `CPU Usage - {{term source_node.name}}` which works fine in grafana as it is showing metrics for all the nodes.

**What did you expect to see?**
 - Alerts for individual nodes
**What did you see instead? Under which circumstances?**
 - Seeing the following error in alertmanager
```
level=error ts=2020-02-19T17:34:29.155Z caller=api.go:781 component=api version=v1 msg="API error" err="bad_data: \"source_node.name\" is not a valid label name"
level=error ts=2020-02-19T17:35:49.045Z caller=api.go:781 component=api version=v1 msg="API error" err="bad_data: \"source_node.name\" is not a valid label name"
level=error ts=2020-02-19T17:36:28.839Z caller=api.go:781 component=api version=v1 msg="API error" err="bad_data: \"source_node.name\" is not a valid label name"
```

**Environment**
 - kubernetes (prometheus operator)

* Alertmanager version:

```
/alertmanager $ alertmanager --version
alertmanager, version 0.18.0 (branch: HEAD, revision: 1ace0f76b7101cccc149d7298022df36039858ca)
  build user:       root@868685ed3ed0
  build date:       20190708-14:31:49
  go version:       go1.12.6
```

* Prometheus version:

`quay.io/prometheus/prometheus:v2.12.0`

* Alertmanager configuration file:
```
global:
  resolve_timeout: 5m
  slack_api_url: 'SLACK_URL_HERE'
route:
  group_by: ['cluster', 'alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
  receiver: 'slack-default'
  routes:
  - match:
      alertname: Watchdog
    repeat_interval: 120h
receivers:
- name: slack-default
  slack_configs:
  - channel: '#CHANNEL'
    title: |-
      [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }}
    text: >-
      {{ with index .Alerts 0 -}}
        :chart_with_upwards_trend: *<{{ .GeneratorURL }}|Graph>*
        {{- if .Labels.runbook }}   :notebook: *<{{ .Labels.runbook }}|Runbook>*{{ end }}
      {{ end }}
      *Alert details*:
      {{ range .Alerts -}}
        *Alert:* {{ .Annotations.title }}{{ if .Labels.severity }} - `{{ .Labels.severity }}`{{ end }}
      *Description:* {{ .Annotations.description }}
      *Details:*
        {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
        {{ end }}
      {{ end }}
    send_resolved: true
    username: k8s

```

**Comment by simonpasquier** [comment]
I'm not sure about what you're trying to do exactly but label names need to comply to the same rules as for Prometheus labels in particular `.` isn't an allowed character, see https://prometheus.io/docs/concepts/data_model/#metric-names-and-labels

I'm closing it for now. If you have further questions, please use our [user mailing list](https://groups.google.com/forum/#!forum/prometheus-users), which you can also search.
