### ISSUE TITLE
amtool should display the state of an alert (active, unprocessed, inhibited, silenced)

### ISSUE THREAD

**Issue by simonpasquier** [prometheus/alertmanager#2204]
From https://github.com/prometheus/alertmanager/issues/1248#issuecomment-386327062

> adding a State column to the extended output would be cool:

```
# ./amtool alert query -o extended -s -a  'alertname="HighErrorRate"'
Alertname               Starts At                Summary                        State
HighErrorRate           2018-05-03 14:51:19 UTC  server is serving many errors  Silenced
```

**Comment by Kellel** [comment]
Do we want to add this to the extended output or the simple output? The snippet looks like it's the simple output, but the request is for the extended output?

Perhaps it's worth doing a bit more of a deep dive around what really should go into the output? In every case I've seen the extended output is far too large to fit into any terminal anyway.

I've found in my own experience the most useful output for _me_ is the json output. Whenever I really need information I end up just piping the output into jq for mangling anyway.

**Comment by simonpasquier** [comment]
I've just copied the comment from @stuartnelson3 in the original issue but as I understand it, this was requested to be added to the extended output format.

**Comment by ffahri** [comment]
@simonpasquier hey created a pr for both output types, simple output a lot faster sometimes but added support for both simple and extended https://github.com/prometheus/alertmanager/pull/2324
