### ISSUE TITLE
prometheus alertmanager A second warning will be issued after activation

### ISSUE THREAD

**Issue by linhuisheng** [prometheus/alertmanager#2210]
I use two for high availability with prometheus and alertmanager ,I stop one prometheus and alertmanager , To trigger the alarm, success send to another normal prometheus and alertmanager, 5 minutes late, I start That prometheus and alertmanager then it will send a second alarm that has already been sent .

prometheus0_us1.yml:
[root@base prometheus_compose]# cat prometheus0_us1.yml 

global:

  scrape_interval: 15s

  evaluation_interval: 15s

  external_labels:

    cluster: us1

    replica: 0

# Alertmanager configuration

alerting:

  alertmanagers:

  - static_configs:

    - targets:

      - '192.168.0.108:9095'

      - '192.168.0.108:9096'

rule_files:

  - "/etc/rule/rule.yml"    # 告警规则文件

scrape_configs:

  - job_name: 'prometheus'

    static_configs:

      - targets: ['127.0.0.1:9091','127.0.0.1:9092']

  - job_name: 'sidecar'

    static_configs:

      - targets: ['127.0.0.1:19091','127.0.0.1:19092']

  - job_name: linux

    static_configs:

      - targets: ['192.168.0.108:9100']

        labels:

          instance: 192.168.0.108

[root@base prometheus_compose]# cat prometheus1_us1.yml 

global:

  scrape_interval: 15s

  evaluation_interval: 15s

  external_labels:

    cluster: us1

    replica: 1

# Alertmanager configuration

alerting:

  alertmanagers:

  - static_configs:

    - targets:

      - '192.168.0.108:9095'

      - '192.168.0.108:9096'

rule_files:

  - "/etc/rule/rule.yml"    # 告警规则文件

scrape_configs:

  - job_name: 'prometheus'

    static_configs:

      - targets: ['127.0.0.1:9091','127.0.0.1:9092']

  - job_name: 'sidecar'

    static_configs:

      - targets: ['127.0.0.1:19091','127.0.0.1:19092']

  - job_name: linux

    static_configs:

      - targets: ['192.168.0.108:9100']

        labels:

          instance: 192.168.0.108

[root@base prometheus_compose]# cat alertmanager/alert-test.yml 
global:
  resolve_timeout: 5m
  smtp_from: 'y6832969@163.com'
  smtp_smarthost: 'smtp.163.com:25'
  smtp_auth_username: 'y6832969@163.com'
  smtp_auth_password: 'y09250315'
  smtp_require_tls: false
templates:
  - 'template/email.tmpl'
route:
  group_by: ['cluster','alertname']
  group_wait: 30s
  group_interval: 5s
  repeat_interval: 3h
  receiver: 'webhook'
receivers:
- name: 'webhook'
  webhook_configs:
  - url: 'http://192.168.0.100:5000/send'
    send_resolved: true
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
docker run -d --net=host \
    -v $(pwd)/prometheus0_us1.yml:/etc/prometheus/prometheus.yml \
	-v $(pwd)/rule:/etc/rule \
    -v $(pwd)/prometheus0_us1_data:/prometheus \
    -u root \
    --name prometheus-0-us1 \
    prom/prometheus \
    --config.file=/etc/prometheus/prometheus.yml \
    --storage.tsdb.path=/prometheus \
    --web.listen-address=:9091 \
    --web.enable-lifecycle \
    --storage.tsdb.max-block-duration=5m \
    --storage.tsdb.min-block-duration=5m \
    --web.enable-admin-api && echo "Prometheus 0 US1 started"

docker run -d --net=host \
    -v $(pwd)/prometheus1_us1.yml:/etc/prometheus/prometheus.yml \
	-v $(pwd)/rule:/etc/rule \
    -v $(pwd)/prometheus1_us1_data:/prometheus \
    -u root \
    --name prometheus-1-us1 \
    prom/prometheus \
    --config.file=/etc/prometheus/prometheus.yml \
    --storage.tsdb.path=/prometheus \
    --web.listen-address=:9092 \
    --web.enable-lifecycle \
    --storage.tsdb.max-block-duration=5m \
    --storage.tsdb.min-block-duration=5m \
    --web.enable-admin-api && echo "Prometheus 1 US1 started"
docker run --name alertmanager01 \
 -v $(pwd)/alertmanager/alert-test.yml:/etc/alertmanager/alert-test.yml \
 -v $(pwd)/alertmanager/template:/etc/alertmanager/template \
 -d -p 9095:9095 \
 -p 8095:8095 \
 prom/alertmanager \
 --log.level=debug \
 --config.file=/etc/alertmanager/alert-test.yml \
 --web.listen-address=":9095" \
 --cluster.listen-address=":8095" \
 --cluster.peer="192.168.0.108:8096"

docker run --name alertmanager02 \
 -v $(pwd)/alertmanager/alert-test.yml:/etc/alertmanager/alert-test.yml \
 -v $(pwd)/alertmanager/template:/etc/alertmanager/template \
 -d -p 9096:9096 \
 -p 8096:8096 \
 prom/alertmanager \
 --log.level=debug \
 --config.file=/etc/alertmanager/alert-test.yml \
 --web.listen-address=":9096" \
 --cluster.listen-address=":8096" \
 --cluster.peer="192.168.0.108:8095"

please help me ,Thank You!

**Comment by simonpasquier** [comment]
It doesn't seem like you're sending the same labels from both Prometheus instances. You want to drop the `replica` label with `alert_relabel_configs`. Check https://www.robustperception.io/high-availability-prometheus-alerting-and-notification for more details.

I'm closing it for now. If you have further questions, please use our [user mailing list](https://groups.google.com/forum/#!forum/prometheus-users), which you can also search.

**Comment by linhuisheng** [comment]
> 似乎您没有从两个Prometheus实例发送相同的标签。您想使用删除`replica`标签`alert_relabel_configs`。查看https://www.robustperception.io/high-availability-prometheus-alerting-and-notification了解更多详细信息。
> 
> 我现在要关闭它。如果您还有其他疑问，请使用我们的[用户邮件列表](https://groups.google.com/forum/#!forum/prometheus-users)，您也可以搜索。

it not I use later:
[root@base prometheus_compose]# cat prometheus0.yml 
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    dc: europe1

alerting:
  alert_relabel_configs:
    - source_labels: [dc]
      regex: (.+)\d+
      target_label: dc
  alertmanagers:
  - static_configs:
    - targets:
      - 192.168.0.114:9093
      - 192.168.0.115:9093
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"
  - "rule.yml"


scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['192.168.0.114:9090','192.168.0.115:9090']
  - job_name: 'sidecar'
    static_configs:
      - targets: ['192.168.0.114:19090','192.168.0.115:19090']
  - job_name: linux
    static_configs:
      - targets: ['192.168.0.114:9100']
        labels:
          instance: 192.168.0.114
[root@base prometheus_compose]# cat prometheus1.yml 
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    dc: europe1

alerting:
  alert_relabel_configs:
    - source_labels: [dc]
      regex: (.+)\d+
      target_label: dc
  alertmanagers:
  - static_configs:
    - targets:
      - 192.168.0.114:9093
      - 192.168.0.115:9093
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"
  - "rule.yml"


scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['192.168.0.114:9090','192.168.0.115:9090']
  - job_name: 'sidecar'
    static_configs:
      - targets: ['192.168.0.114:19090','192.168.0.115:19090']
  - job_name: linux
    static_configs:
      - targets: ['192.168.0.114:9100']
        labels:
          instance: 192.168.0.114
[root@base prometheus_compose]# cat alertmanager/alert-test.yml 
global:
  resolve_timeout: 5m
  smtp_from: 'xxxxx@163.com'
  smtp_smarthost: 'smtp.163.com:25'
  smtp_auth_username: 'xxxxxx@163.com'
  smtp_auth_password: 'xxxxxxx'
  smtp_require_tls: false
templates:
  - 'template/email.tmpl'
route:
  group_by: ['alertname','dc']
  group_wait: 30s
  group_interval: 5s
  repeat_interval: 2h
  receiver: 'webhook'
receivers:
- name: 'webhook'
  webhook_configs:
  - url: 'http://192.168.0.104:5000/send'
    send_resolved: true
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
Then:
![QQ截图20200314003417](https://user-images.githubusercontent.com/8087304/76640890-a9b08980-658b-11ea-902b-b657e485ce07.png)
