### ISSUE TITLE
It doesn't seem like you're sending the same labels from both Prometheus instances. You want to drop the `replica` label with `alert_relabel_configs`. Check https://www.robustperception.io/high-availability-prometheus-alerting-and-notification for more details.

### ISSUE THREAD

**Issue by linhuisheng** [prometheus/alertmanager#2212]
It doesn't seem like you're sending the same labels from both Prometheus instances. You want to drop the `replica` label with `alert_relabel_configs`. Check https://www.robustperception.io/high-availability-prometheus-alerting-and-notification for more details.

I'm closing it for now. If you have further questions, please use our [user mailing list](https://groups.google.com/forum/#!forum/prometheus-users), which you can also search.

_Originally posted by @simonpasquier in https://github.com/prometheus/alertmanager/issues/2210#issuecomment-598770782_

I used that configuration, and I still resolved three when the recovery alarm goes off
[root@base prometheus_compose]# cat prometheus0.yml 
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    dc: europe1

alerting:
  alert_relabel_configs:
  - source_labels: [dc]
    regex: (.+)\d+
    target_label: dc
  alertmanagers:
  - static_configs:
    - targets:
      - 192.168.0.114:9093
      - 192.168.0.115:9093
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"
  - "rule.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['192.168.0.114:9090','192.168.0.115:9090']
  - job_name: 'sidecar'
    static_configs:
      - targets: ['192.168.0.114:19090','192.168.0.115:19090']
  - job_name: linux
    static_configs:
      - targets: ['192.168.0.114:9100']
        labels:
          instance: 192.168.0.114
[root@base prometheus_compose]# cat prometheus1.yml 
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    dc: europe2

alerting:
  alert_relabel_configs:
  - source_labels: [dc]
    regex: (.+)\d+
    target_label: dc
  alertmanagers:
  - static_configs:
    - targets:
      - 192.168.0.114:9093
      - 192.168.0.115:9093
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"
  - "rule.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['192.168.0.114:9090','192.168.0.115:9090']
  - job_name: 'sidecar'
    static_configs:
      - targets: ['192.168.0.114:19090','192.168.0.115:19090']
  - job_name: linux
    static_configs:
      - targets: ['192.168.0.114:9100']
        labels:
          instance: 192.168.0.114
alert-test.yml       .alert-test.yml.swp  template/            
[root@base prometheus_compose]# cat alertmanager/alert-test.yml 
global:
  resolve_timeout: 5m
  smtp_from: 'xxx@163.com'
  smtp_smarthost: 'smtp.163.com:25'
  smtp_auth_username: 'xxxx@163.com'
  smtp_auth_password: 'xxxxx'
  smtp_require_tls: false
templates:
  - 'template/email.tmpl'
route:
  group_by: ['alertname','dc']
  group_wait: 30s
  group_interval: 5s
  repeat_interval: 2h
  receiver: 'webhook'
receivers:
- name: 'webhook'
  webhook_configs:
  - url: 'http://192.168.0.104:5000/send'
    send_resolved: true
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']

**Comment by linhuisheng** [comment]
![2](https://user-images.githubusercontent.com/8087304/76643573-49701680-6590-11ea-8b82-d247d5d7201e.png)

**Comment by linhuisheng** [comment]
When the alarm is triggered, one is combined, but when the alarm is restored, three are issued

**Comment by simonpasquier** [comment]
Your `group_interval` value (5s) is too low (see also https://github.com/prometheus/alertmanager/issues/1550#issuecomment-483598607). Please follow up on the mailing list and IRC if you've got further questions.
