### ISSUE TITLE
Connect Keycloak to Alertmanager

### ISSUE THREAD

**Issue by nmizeb** [prometheus/alertmanager#2218]
Hello, 

There is a possibility to connect Keycloak to Alertmanager for authentification which are deployed in Kubernetes ? 
Thanks

**Comment by simonpasquier** [comment]
Not sure what you mean exactly. Do you want to authenticate users connecting to the Alertmanager UI with Keycloak?

**Comment by nmizeb** [comment]
> Not sure what you mean exactly. Do you want to authenticate users connecting to the Alertmanager UI with Keycloak?

Effectively, so i tried to use keycloak-gatekeeper in the alertmanagerSpec like this: 
alertmanagerSpec:
    containers:  
      - name: keycloak-gatekeeper
        args:
        - --discovery-url=https://kecloak-url/auth/realms/client1
        - --client-id=client-id-in-keycloak
        - --client-secret=id-client-secret
        - --listen=0.0.0.0:3000
        - --redirection-url=https://my-alertmanager-url       
        - --upstream-url=https://0.0.0.0:9093
        - --resources=uri=/*
        - --verbose=true
        image: quay.io/keycloak/keycloak-gatekeeper
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          protocol: TCP
And this, doesn't work. 
Btw, Is the arg "--redirection-url" correct ?

**Comment by simonpasquier** [comment]
This would be more a question for the Keycloak project then :smirk: I don't know much about keycloak-gatekeeper but as long as it works like any other reverse-proxy, it should be possible to put it in front of Alertmanager. There's a [guide](https://prometheus.io/docs/guides/basic-auth/) in the docs to deploy Nginx + Prometheus that you can use as an inspiration.

I'm closing it for now. If you have further questions, please use our [user mailing list](https://groups.google.com/forum/#!forum/prometheus-users), which you can also search.
