### ISSUE TITLE
I want to persist alert history. How can I do it?

### ISSUE THREAD

**Issue by readygodom** [prometheus/alertmanager#2223]
I have persist alert history by modifying the 'dispatch' code. Any other way in which can I persist alert history?

**Comment by paulfantom** [comment]
Alertmanager doesn't persist state, so it is not possible using only this tool. To preserve history you need to send alerts to some other system, for example by using webhooks.

**Comment by simonpasquier** [comment]
What @paulfantom says. Note that Alertmanager sends notifications (e.g. groups of alerts). You can check existing webhook receivers from the [documentation](https://prometheus.io/docs/operating/integrations/#alertmanager-webhook-receiver).

I'm closing it for now. If you have further questions, please use our [user mailing list](https://groups.google.com/forum/#!forum/prometheus-users), which you can also search.
