### ISSUE TITLE
Saving alerts in Database for further processing

### ISSUE THREAD

**Issue by Adarsh096** [prometheus/alertmanager#2224]
First of all I want to thank you and congratulate the Prometheus Team for such a successful product. 
I hope I'm not causing a lot of trouble but I really wanted to know about some other options to get the logs of all the alerts that are generated in a separate database.
I know that alertmanager has alertsnitch but what if I want it in a different database, is there a way to do that?
I read the earlier conversation on this topic too and I can remember that someone(probably @fabxc ) said that there is a internal log of all alerts and you guyz are working to provide it to the users too. If I could get some workarounds for my need then that would solve a issue of many other people too..

**Comment by hoffie** [comment]
Hi. Thanks for opening this issue. The Prometheus projects use Github issues mainly for bug reports. This issue rather sounds like a usage question, which may be better answered on the [prometheus-users mailing list](https://prometheus.io/community/).

As a first pointer regarding your question: Alertmanager supports webhooks and webhooks can be used to perform arbitrary actions with alerts. This obviously includes logging or storing in a database. alertsnitch also seems to use this interface.
See here for the actual config, the format of the payload and a link to known existing integrations: https://prometheus.io/docs/alerting/configuration/#webhook_config

**Comment by Adarsh096** [comment]
Thanks for the response @hoffie 
Sure I will take this issue there and continue discussion in prometheus user mailing list.
I'm closing it here..
