### ISSUE TITLE
Fingerprint is missing in v0.19.0 documentation

### ISSUE THREAD

**Issue by stevebail** [prometheus/alertmanager#2227]
The v0.19.0 Alertmanager now includes a fingerprint in the HTTP POST requests (webhooks) as follows:

{
  "version": "4",
  "groupKey": <string>,    // key identifying the group of alerts (e.g. to deduplicate)
  "status": "<resolved|firing>",
  "receiver": <string>,
  "groupLabels": <object>,
  "commonLabels": <object>,
  "commonAnnotations": <object>,
  "externalURL": <string>,  // backlink to the Alertmanager.
  "alerts": [
    {
      "status": "<resolved|firing>",
      "labels": <object>,
      "annotations": <object>,
      "startsAt": "<rfc3339>",
      "endsAt": "<rfc3339>",
      **"fingerprint": "<string>", // new in v0.19.0**
      "generatorURL": <string> // identifies the entity that caused the alert
    },
    ...
  ]
}

Please update documentation at the following links:
- https://prometheus.io/docs/alerting/configuration/#%3Cwebhook_config%3E
- https://prometheus.io/docs/alerting/notifications/

**Related Question: Is the fingerprint based on the alert labels or group labels?**

**Comment by mxinden** [comment]
@stevebail documentation is tracked here. I am sure the maintainers would appreciate a pull request.

> Related Question: Is the fingerprint based on the alert labels or group labels?

Function definition [here](https://github.com/prometheus/common/blob/master/model/alert.go#L48) should hel.

> It is equivalent to the fingerprint of the alert's label set.
