### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Adarsh096** [prometheus/alertmanager#2230]
Hie Developers,
Hope you all are doing great...
**What did you expect to see?**
I would like to see some arrangement where we can not only have predefined receivers but we can also have something like a subscriber model where any new service/device can starts receiving alerts as it would make alertmanager flexible and useful not just for DevOPs but literally as an alertmanager. 
I heard that kafka has something like this but there is not direct way to integrate it with kafka (to send alerts not metrics) and as a user of prometheus we would not want to hop to a http service just to put data to kakfa ( or any other platform supporting subscriber like model)

**Comment by paulfantom** [comment]
Changing the model in which alertmanager operates to a subscripion-based one would need a major overhaul of the codebase. I don't think this will happen as you can easily put a layer in front of alertmanager to handle such functionality. Such layer would need to receive webhooks from alertmanager and forward them to your pub/sub system of choice (ex. kafka).

**Comment by Adarsh096** [comment]
Hie Paul, I really appreciate the response...

I hope I'm not asking a silly question but, could you give sample code for what the layer may look like(coz from what I know kafka needs to have a producer to send any message as topic and its a lot of coding ) or you could point me in the right links and I would try to figure it out .
Regards 
Adarsh

**Comment by paulfantom** [comment]
I don't think there is any kafka receiver for alertmanager webhook right now. If you want to write one, I would suggest looking at other projects which are intended as alerting forwarders. The current list can be found at https://prometheus.io/docs/operating/integrations/#alertmanager-webhook-receiver

**Comment by Adarsh096** [comment]
yeah sure I will try to see for the alerts forwarders .. I think that concludes this issue so I'm closing this.
Thanks for your time.
