### ISSUE TITLE
How to modify Email template in Alertmanager container?

### ISSUE THREAD

**Issue by alexjuchina** [prometheus/alertmanager#2232]
I use docker container to run alertmanager, I can receive emails normally, everything is fine, but I cannot find where to modify email template. The "View in Alertmanager" button links in email is wrong, I want to change the hostname in it. 
So could you tell me what should I do if I want to modify email template ? I can't find the file below:

**html: '{{ template "email.default.html" . }}'**

**Comment by alexjuchina** [comment]
I tried to make file 'template/email.default.html'  or  'template/email.tmpl',  paste official content into them, both failed!   Alertmanager container does not use the files.

**Comment by hoffie** [comment]
The default source file lives here:
https://github.com/prometheus/alertmanager/blob/master/template/default.tmpl
It is built into the binary, so you won't find it in the filesystem.

If you want to provide custom templates, you will have to tell Alertmanager by setting the template [config option](https://prometheus.io/docs/alerting/configuration/#configuration-file) to a list of files/patterns.

The "View in Alertmanager" URLs should be generated automatically -- you would probably also want to look into adjusting (or adding) your `--web.external-url=WEB.EXTERNAL-URL` command line option.

If you have further questions, I suggest using the [prometheus-users mailing list](https://prometheus.io/community/) which is the intended forum for such questions. Github issues are used for bug reports in the Prometheus projects.

**Comment by simonpasquier** [comment]
@hoffie has provided the perfect answer (thanks!). I'm closing it for now.

**Comment by alexjuchina** [comment]
> The default source file lives here:
> https://github.com/prometheus/alertmanager/blob/master/template/default.tmpl
> It is built into the binary, so you won't find it in the filesystem.
> 
> If you want to provide custom templates, you will have to tell Alertmanager by setting the template [config option](https://prometheus.io/docs/alerting/configuration/#configuration-file) to a list of files/patterns.
> 
> The "View in Alertmanager" URLs should be generated automatically -- you would probably also want to look into adjusting (or adding) your `--web.external-url=WEB.EXTERNAL-URL` command line option.
> 
> If you have further questions, I suggest using the [prometheus-users mailing list](https://prometheus.io/community/) which is the intended forum for such questions. Github issues are used for bug reports in the Prometheus projects.

thank you very much, I have configured successfully. Really appreciate!

**Comment by jerryptl26** [comment]
Can anyone elaborate in detail to configure the template?

**Comment by TN801465** [comment]
kube-prometheus: how to add the Alert.StartsAt to alertmanager-secret.yaml
