### ISSUE TITLE
Alertmanager 422 response code when trying to match severity to priority having more than one alert

### ISSUE THREAD

**Issue by mshahmoradi** [prometheus/alertmanager#2234]
I tried to use something like the bellow line for opsgenie priority but when I have more than one alert, it does not work and I get 422 response.
```
priority: '{{ range .Alerts }}{{ if eq .Labels.severity "critical" }}P2{{ else }}P3{{ end }}{{ end }}'
```
 I was expecting to have an option  to set the highest severity in case of multiple alerts and convert it to one of opsgenie acceptable values

workaround for me was to prevent grouping by adding  group_by: ['...'] to the route.
another option is to remove priority from config file.

* Alertmanager version:
```
alertmanager, version 0.20.0 (branch: HEAD, revision: f74be0400a6243d10bb53812d6fa408ad71ff32d)
  build user:       root@00c3106655f8
  build date:       20191211-14:13:14
  go version:       go1.13.5

```
* Prometheus version:
```
prometheus, version 2.13.1 (branch: HEAD, revision: 6f92ce56053866194ae5937012c1bec40f1dd1d9)
  build user:       root@88e419aa1676
  build date:       20191017-13:15:01
  go version:       go1.13.1

```
* Logs:
```
level=error ts=XXX caller=notify.go:372 component=dispatcher msg="Error on notify" err="cancelling notify retry for \"opsgenie\" due to unrecoverable error: unexpected status code 422: {\"message\":\"Request body is not processable. Please check the errors.\",\"errors\":{\"priority\":\"should be one of [ P1, P2, P3, P4, P5 ]\"},\"took\":0.002,\"requestId\":\"[ID]\"}" context_err=null
```

**Comment by simonpasquier** [comment]
You need to group your alerts by `severity` and use `{{ if eq .GroupLabels.severity "critical" }}P2{{ ...`.

I'm closing it for now. If you have further questions, please use our [user mailing list](https://groups.google.com/forum/#!forum/prometheus-users), which you can also search.
