### ISSUE TITLE
How to delete or update rules according alertManager api ?

### ISSUE THREAD

**Issue by wuguanyu** [prometheus/alertmanager#2239]
r.Options("/*path", wrap(func(w http.ResponseWriter, r *http.Request) {}))

	r.Get("/status", wrap(api.status))
	r.Get("/receivers", wrap(api.receivers))

	r.Get("/alerts", wrap(api.listAlerts))
	r.Post("/alerts", wrap(api.addAlerts))

	r.Get("/silences", wrap(api.listSilences))
	r.Post("/silences", wrap(api.setSilence))
	r.Get("/silence/:sid", wrap(api.getSilence))
	r.Del("/silence/:sid", wrap(api.delSilence))

**Comment by wuguanyu** [comment]
I can't find api to delete or update rule in api_V1

**Comment by simonpasquier** [comment]
Rules are defined in Prometheus, not Alertmanager. If you're talking about alerts, see https://prometheus.io/docs/alerting/clients/.

I'm closing it for now. If you have further questions, please use our [user mailing list](https://groups.google.com/forum/#!forum/prometheus-users), which you can also search.

**Comment by wuguanyu** [comment]
> Rules are defined in Prometheus, not Alertmanager. If you're talking about alerts, see https://prometheus.io/docs/alerting/clients/.
> 
> I'm closing it for now. If you have further questions, please use our [user mailing list](https://groups.google.com/forum/#!forum/prometheus-users), which you can also search.

according to https://prometheus.io/docs/alerting/clients/ this api defined in alertManger

**Comment by simonpasquier** [comment]
For alerts, everything's explained in the aforementioned documentation. Alerts can't be deleted, there are either firing or resolved based on their end date.
