### ISSUE TITLE
I encounter a problem when making binary file.

### ISSUE THREAD

**Issue by readygodom** [prometheus/alertmanager#2240]
I encounter a problem when making binary file. It said error occurrs while executing step 'common-style' due to golang version mismatch. BUT, I CHECKED THE GOLANG VERSION , AND IT'S CORRECT.
---------SCREEN SHOT BELOW---------
![image](https://user-images.githubusercontent.com/44667568/80201685-115ff700-8657-11ea-8770-059be3e31c25.png)

---------------------------
I did not ever modify this 'Makefile.common'  script. And that, I executed make-file action a few days ago, IT SUCCESS. Miserable.

**Comment by readygodom** [comment]
...
diff -u ./config/config.go.orig ./config/config.go
--- ./config/config.go.orig	2020-04-24 18:07:38.734949796 +0800
+++ ./config/config.go	2020-04-24 18:07:38.734949796 +0800
@@ -24,8 +24,8 @@
 	"strings"
 	"time"
 
-	commoncfg "github.com/prometheus/common/config"
 	extconf "github.com/prometheus/alertmanager/ext/config"
+	commoncfg "github.com/prometheus/common/config"
 	"github.com/prometheus/common/model"
 	"gopkg.in/yaml.v2"
 )
@@ -219,12 +219,12 @@
 // Config is the top-level configuration for Alertmanager's config files.
 type Config struct {
 	DbInfo       *extconf.DbInfo `yaml:"db,omitempty" json:"db,omitempty"`
-	Prometheus   string         `yaml:"prometheus" json"prometheus"`
-	Global       *GlobalConfig  `yaml:"global,omitempty" json:"global,omitempty"`
-	Route        *Route         `yaml:"route,omitempty" json:"route,omitempty"`
-	InhibitRules []*InhibitRule `yaml:"inhibit_rules,omitempty" json:"inhibit_rules,omitempty"`
-	Receivers    []*Receiver    `yaml:"receivers,omitempty" json:"receivers,omitempty"`
-	Templates    []string       `yaml:"templates" json:"templates"`
+	Prometheus   string          `yaml:"prometheus" json"prometheus"`
+	Global       *GlobalConfig   `yaml:"global,omitempty" json:"global,omitempty"`
+	Route        *Route          `yaml:"route,omitempty" json:"route,omitempty"`
+	InhibitRules []*InhibitRule  `yaml:"inhibit_rules,omitempty" json:"inhibit_rules,omitempty"`
+	Receivers    []*Receiver     `yaml:"receivers,omitempty" json:"receivers,omitempty"`
+	Templates    []string        `yaml:"templates" json:"templates"`
 
 	// original is the input from which the config was parsed.
 	original string

Please ensure you are using go version go1.13.1 linux/arm64 for formatting code.
Makefile.common:116: recipe for target 'common-style' failed
make: *** [common-style] Error 1
root@master2:~/go/src/github.com/prometheus/alertmanager# go version
go version go1.13.1 linux/arm64

**Comment by simonpasquier** [comment]
`make build` should be enough to build the binary and it won't run extra checks.

I'm closing it for now. If you have further questions, please use our [user mailing list](https://groups.google.com/forum/#!forum/prometheus-users), which you can also search.
