### ISSUE TITLE
How to use api to create or update route and receiver?

### ISSUE THREAD

**Issue by cycwll** [prometheus/alertmanager#2242]
I use an alertmanager cluster, and necessary to add routes and receivers very frequently,  so that the users only receive the alarms they want.  As a result, I always have to manually modify the configuration file on multiple servers and reload it. Is there any way to optimize my current situation？
Thanks a lot.

**Comment by simonpasquier** [comment]
This is the way to do it. There are no plans to add any REST-like API for this task.

I'm closing it for now. If you have further questions, please use our [user mailing list](https://groups.google.com/forum/#!forum/prometheus-users), which you can also search.
