### ISSUE TITLE
[Silence] Define matcher with same name

### ISSUE THREAD

**Issue by Nexucis** [prometheus/alertmanager#2243]
Hello,

When you are creating a Silence with multiple matchers, the result (with no surprise) it's applying an **AND** between each matcher.

And that's ok until you are creating multiple matcher with the same name.

* Proposition 1:
It would be nice that instead of having an "AND" logic in that case, it did an **OR** (only between matcher that have the same name)

I know you can do it using the regexp instead, but it's just an idea of improvement.

* Proposition 2: 
An other way would be to prevent the possiblity to create multiple matcher with the same name. 

* Proposition 3:
A crazy thing would be to merge all matcher with the same name in a single one with the Matcher_Regexp to true

What do you think ?

**Comment by roidelapluie** [comment]
This would be a breaking change.

e.g. you could create a matcher:

env=prod
env=prod

That would be valid and silence prod alerts.

env=prod
env=acc

would be valid but not match anything.

I expect that this is used in the field. e.g. in scripts:

silence: env=dev env=${env}

to only silence dev environment for example.

For that reason, that would be a breaking change that would prevent the usage of a valid (even if not used a lot) feature.

**Comment by Nexucis** [comment]
Thanks for your answer :).

That's true I didn't think this behavior would be used. 
But even with the example you gave, I find it a bit weird to use it like that. I mean creating a silence with twice the same matcher but with different value. Since it won't match anything, it's a bit weird to want to create a silence that won't work, don't you think ? 

So yes, indeed it would be a breaking change for all propositions, but does it mean, it's a no go to do it even for a v1 ?

**Comment by roidelapluie** [comment]
As you state in your original message, the way to do this is by using regexes, so this is already possible and usually I think there should not be two ways to achieve the same goal.

**Comment by Nexucis** [comment]
ok, np :). Thanks for your answers !
