### ISSUE TITLE
Notification via Webhook does not support Authorization config

### ISSUE THREAD

**Issue by longkb** [prometheus/alertmanager#2246]
**What did you expect to see?**

I am trying to use Alert Manager to a webhook with `Basic Authorization`. However, as I can see from source code. The webhook does not support sending a HTTP request with Authorization field in its header. [[1]](https://github.com/prometheus/alertmanager/blob/master/notify/webhook/webhook.go#L100-L101)

So I would like to propose an additional config that enables the end user can send HTTP request to Webhook API via Authorization header.

**Environment**

* Alertmanager version:

	```

	$ ./alertmanager --version
	alertmanager, version 0.20.0 (branch: master, revision: 071818bdac7474b7c447a083dd2151606abc8951)
	build user:       longkb@longkb
	build date:       20200428-02:45:36
	go version:       go1.14.2
        ```

**Comment by paulfantom** [comment]
Basic auth is already supported via [`http_config`](https://prometheus.io/docs/alerting/configuration/#http_config) section of [webhook configuration](https://prometheus.io/docs/alerting/configuration/#webhook_config).

**Comment by longkb** [comment]
Thanks. I got it :)
