### ISSUE TITLE
Export alert from alertmanager to txt/json file

### ISSUE THREAD

**Issue by ihasnaoui** [prometheus/alertmanager#2252]
Hello,
I installed grafana / prometheus / alertmanager and I want to export all alerts sent by alertemanager in txt / json format
in fact we have another application that accepts alerts in txt / json format as input.

thanks ;)

**Comment by SAbdulRahuman** [comment]
You can use alert manager configuration https://prometheus.io/docs/alerting/configuration/

**Comment by ihasnaoui** [comment]
the goal is instead of sending an alert by email , alertmanager must generate a txt/json file containing this alert .
the file will be used in another plateform which requests as inputa file

**Comment by paulfantom** [comment]
For integrating other applications with alertmanager use [webhook receiver](https://prometheus.io/docs/alerting/configuration/#receiver). Possibly this will need a middleware application converting alertmanager payload into other format. Some of such applications are listed in [alertmanager integrations page](https://prometheus.io/docs/operating/integrations/#alertmanager-webhook-receiver).

Currently alertmanager is not accepting any new built-in integrations and recommended way is to use webhooks.

**Comment by SAbdulRahuman** [comment]
webhook generate default JSON data, is it possible to add new json fields(key/value) to the JSON by creating template.

**Comment by simonpasquier** [comment]
I'm closing it for now. If you have further questions, please use our [user mailing list](https://groups.google.com/forum/#!forum/prometheus-users), which you can also search.
