### ISSUE TITLE
Memory Alert value conversion

### ISSUE THREAD

**Issue by ankit82** [prometheus/alertmanager#2259]
We have setup an Alert on memory usage per container. it is working good. but we are not able to get actual usage value in format we are expecting. e.g. usage is shown as "7.073439744e+09" but we want it like "8.x GB".  is there any way to convert this in alert manager? please help

**Comment by simonpasquier** [comment]
The formatting needs to be done in your alerting rule. See [template functions](https://prometheus.io/docs/prometheus/latest/configuration/template_reference/#numbers) such as `humanize` and `humanize1024`.

I'm closing it for now. If you have further questions, please use our [user mailing list](https://groups.google.com/forum/#!forum/prometheus-users), which you can also search.
