### ISSUE TITLE
Alerts Auto Resolved while Telemetry missing

### ISSUE THREAD

**Issue by AshokRamasamy** [prometheus/alertmanager#2264]
We have been using Alert Manager version - version 0.18.0

We have an alert expression validates a condition continuously. Alerts are getting fired when the condition is met. For some reason, telemetry stops coming into Prometheus and the alert is getting auto resolved. This is misleading support engineers.

Could you please advise of how to overcome the auto resolve when Telemetry is missing?

**Comment by dgl** [comment]
This is Prometheus behaving as expected, it will evaluate the alerts, find no data and therefore they won't be firing. You can check this by looking at the `ALERTS` timeseries on your Prometheus instance, this shows the status of alerts before they even reach alertmanager.

How to fix this is more a Prometheus question, but see https://www.robustperception.io/absent-alerting-for-scraped-metrics for one idea and also look at the `absent()` function.

**Comment by arnavbose** [comment]
I have this scenario:

K_status != 3, trigger an alert. 
The alert gets triggered fine and when the value changes  back to 3, the alert resolves correctly as well.
The problem starts when it has already alerted based on K_status != 3 and then the telemetry goes missing. Now, it triggers a resolution, which is not correct. 

if I add a condition to check if the metric exists or not along with the main condition, will it alert and resolve correctly even when telemetry goes missing? Eg:

 K_status != 3 and on (port) K_status

So, it triggers an alert when both conditions satisfy. Now if telemetry goes missing, the 2nd condition will not satisfy, correct? So, in this case will the alert resolve?

**Comment by roidelapluie** [comment]
Thanks for your report. It looks as if this is actually a question about usage and not development.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by simonpasquier** [comment]
As alluded in the previous comments, you want a specific alert that fires when the telemetry stops.

**Comment by ankurnigam** [comment]
If this is default of prometheus , then it's bug . No telemetry cannot result in sending resolved notification.
