### ISSUE TITLE
It looks like a problem occurred when sending resolved notification.

### ISSUE THREAD

**Issue by readygodom** [prometheus/alertmanager#2265]
It looks like a problem occurred when notification sending, which alertmanager can not send resolved notification sometimes.
Retell that scene:
  I have set **only one** alert rule in prometheus before test.
  1.Prometheus send a firing alert to alertmanager, then alertmanager record this firing alert into a local memory storage area in nflog which is called 'resolvedAlerts'.
  2.Prometheus send firing alert as same as step 1 again, then alertmanager find entries from memory storage by using -n.nflog.Query(nflog.QGroupKey(gkey), nflog.QReceiver(n.recv))- method, and checked this firing alert will notify again. **After that, alertmanager nflog move this alert to 'resolvedAlerts'. Or, 'firingAlerts' and 'resolvedAlerts' are all cleaned up. I don't know why alertmanager do this. Maybe gossip??? But I settled only a local alertmanager in cluster.**
  3.Prometheus send resolved alert to alertmanager. Alertmanager find entries from memory storage like it did in step 2. Next, alertmanager find current firing in group is empty, so it find alerts in entries. BUT, firingAlerts is also empty due to what alertmanager did in step 2 do. So, alertmanager does not send this 'resolved alert'.
Code:
**notify.go**
func (n *DedupStage) needsUpdate

 ````
    // If we haven't notified about the alert group before, notify right away
	// unless we only have resolved alerts.
	if entry == nil {
		return len(firing) > 0
	}
    // Notify about all alerts being resolved.
	// This is done irrespective of the send_resolved flag to make sure that
	// the firing alerts are cleared from the notification log.
	if len(firing) == 0 {
		// If the current alert group and last notification contain no firing
		// alert, it means that some alerts have been fired and resolved during the
		// last interval. In this case, there is no need to notify the receiver
		// since it doesn't know about them.
		return len(entry.FiringAlerts) > 0
	}
````
Because of this block of code, function return as false, and then notification of 'resolved alert' in step 3 will not be sent.

**Comment by simonpasquier** [comment]
Which version of Alertmanager do you run? If it's before 0.20.0, you might be missing https://github.com/prometheus/alertmanager/pull/2040.

**Comment by readygodom** [comment]
Thank you. I am using version 0.18.0 now.
