### ISSUE TITLE
Error when cross-building alertmanager for windows

### ISSUE THREAD

**Issue by sdurrheimer** [prometheus/alertmanager#227]
Cross-building Alertmanager for windows is currently failing due to the following error:
```
# github.com/prometheus/alertmanager/vendor/github.com/prometheus/common/log

/go/src/github.com/prometheus/alertmanager/vendor/github.com/prometheus/common/log/syslog_formatter.go:15: undefined: syslog.Writer
```
After testing, it seems that it can be fixed by updating the `github.com/prometheus/common/log` vendor, but I don't know if it can breaks others things after updating it.

@fabxc

**Comment by fabxc** [comment]
Correct, thanks.
