### ISSUE TITLE
alertmanager container hase some error under mips64

### ISSUE THREAD

**Issue by zhangwenlong8911** [prometheus/alertmanager#2271]
**_### What did you do?_**
First run "make build"，in order to adaptation “mips64” I modify the Dockerfile
**_What did you expect to see?_**
I hope alertmanager container can normal operation under mips64 architecture
_**What did you see instead? Under which circumstances?**_
it shows some error 
#level=info ts=2020-05-29T09:53:40.605Z caller=main.go:231 msg="Starting Alertmanager" version="(version=0.20.0, branch=HEAD, revision=f74be0400a6243d10bb53812d6fa408ad71ff32d)"
#level=info ts=2020-05-29T09:53:40.606Z caller=main.go:232 build_context="(go=go1.13.6, user=root@bogon, date=20200529-07:00:14)"
#level=warn ts=2020-05-29T09:53:40.608Z caller=cluster.go:154 component=cluster err="couldn't deduce an advertise address: no private IP found, explicit advertise addr not provided"
#level=error ts=2020-05-29T09:53:40.611Z caller=main.go:256 msg="unable to initialize gossip mesh" err="create memberlist: Failed to get final advertise address: No private IP address #found, and explicit IP not provided"

This problem has been discussed in the community.[#1434](https://github.com/prometheus/alertmanager/issues/1434) It is said that the problem has been solved. However, this problem still exists in "MIPS64". Currently, it can be configured in the dockerfile "--cluster.advertise-Address=127.0.0.1:9093". Can I directly use patch to avoid problems in the source code
_**Environment**_
[root@os-kvm1 alertmanager]# uname -a
Linux os-kvm1 3.10.0-1127.8.2.el7.x86_64 \#1 SMP Tue May 12 16:57:42 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
_* System information:_
[root@os-kvm1 alertmanager]# uname -srm
Linux 3.10.0-1127.8.2.el7.x86_64 x86_64
_Alertmanager version:_
alertmanager-0.20.0
_* Prometheus version:_
prometheus-2.17.2

**Comment by hoffie** [comment]
> Can I directly use patch to avoid problems in the source code

Are you saying that you've got some patch or are you asking about one?
Do you have any hints that this issue would be mips-specific?

It seems like you already found out about `--cluster.advertise-address` (lowercase `a`). This fixes your issue, doesn't it?
I guess you always have to provide the option if there are only public or only loopback addresses (i.e. no private subnetz adresses such as 192.168.0.0/16).

This would also mean: There is no bug. :)

**Comment by simonpasquier** [comment]
Your issue doesn't seem to be related to MIPS64. As noted in the [README.md](https://github.com/prometheus/alertmanager/blob/master/README.md), `--cluster.advertise-address` is required if the instance doesn't have an IP address that is part of RFC 6980 with a default route.

I'm closing it for now. If you have further questions, please use our [user mailing list](https://groups.google.com/forum/#!forum/prometheus-users), which you can also search.

**Comment by zhangwenlong8911** [comment]
ok，thank you
