### ISSUE TITLE
alertmanager: no private IP found

### ISSUE THREAD

**Issue by hedeesa** [prometheus/alertmanager#2284]
I made a service for alertmanager, which is like this:
```[Unit]
Description=Alert Manager
Wants=network-online.target
After=network-online.target

[Service]
Type=simple
User=alertmanager
Group=alertmanager
ExecStart=/usr/local/bin/alertmanager \
  --config.file=/etc/alertmanager/alertmanager.yml \
  --storage.path=/data/alertmanager \ 
  --web.external-url http://public_ip_server:9093

Restart=always

[Install]
WantedBy=multi-user.target
```  
 
I get this error when i start the alermanager
```err="couldn't deduce an advertise address: no private IP found, explicit advertise addr not provided"```

no private IP has been configed on this server, but I set ```--web.external-url http://public_ip_server:9093``` , Why I still get this error?

**Comment by roidelapluie** [comment]
Thanks for your report. It looks as if this is actually a question about usage and not development.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by roidelapluie** [comment]
The cluster.advertise-address flag is required if the instance doesn't have an IP address that is part of RFC 6980 with a default route.

If running Alertmanager in high availability mode is not desired, setting --cluster.listen-address= prevents Alertmanager from listening to incoming peer requests.

**Comment by hedeesa** [comment]
yes.
It seems this label solve the problem
  --cluster.advertise-address="public-ip:9093"
thanks!
@roidelapluie

**Comment by roidelapluie** [comment]
Be aware that you should firewall it or use  --cluster.listen-address= to not use it because that port is not authenticated . If you just have one Alertmanager you should not use that port.

**Comment by hedeesa** [comment]
In Iptables I allowed just Prometheus IP to connect to port 9093, is it enough?

**Comment by roidelapluie** [comment]
On 06 Jun 12:54, Hedeesa wrote:
> In Iptables I allowed just Prometheus IP to connect to port 9093, is it enough? 
> 

Yes

> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/prometheus/alertmanager/issues/2284#issuecomment-640110272

-- 
 (o-    Julien Pivotto
 //\    Open-Source Consultant
 V_/_   Inuits - https://www.inuits.eu

**Comment by roidelapluie** [comment]
Edit: no because clustering uses another port. If you do not use it, use --cluster.listen-address=   [do not put anything after =]

**Comment by junmaqiang** [comment]
# Please teach me how to run it with docker and how to solve this problem

## run
```docker
docker run \
--name apisix-alertManager \
--network apisix \
--ip 177.17.7.45 \
-p 127.0.0.1:9045:9093 \
-v /alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml \
-d quay.io/prometheus/alertmanager
```

## error
```logs
2023-12-22 20:50:27 ts=2023-12-22T12:50:27.714Z caller=main.go:245 level=info msg="Starting Alertmanager" version="(version=0.26.0, branch=HEAD, revision=d7b4f0c7322e7151d6e3b1e31cbc15361e295d8d)"
2023-12-22 20:50:27 ts=2023-12-22T12:50:27.714Z caller=main.go:246 level=info build_context="(go=go1.20.7, platform=linux/amd64, user=root@df8d7debeef4, date=20230824-11:11:58, tags=netgo)"
2023-12-22 20:50:27 ts=2023-12-22T12:50:27.715Z caller=cluster.go:179 level=warn component=cluster err="couldn't deduce an advertise address: no private IP found, explicit advertise addr not provided"
2023-12-22 20:50:27 ts=2023-12-22T12:50:27.719Z caller=main.go:278 level=error msg="unable to initialize gossip mesh" err="create memberlist: Failed to get final advertise address: No private IP address found, and explicit IP not provided"
```
