### ISSUE TITLE
[feature request] add line number for cmd/amtool output

### ISSUE THREAD

**Issue by kenju** [prometheus/alertmanager#2306]
**What did you do?**

`amtool check-config`

```
amtool check-config --verbose alertmanager.yml
```

**What did you expect to see?**

Showing error message with line number would be great

**What did you see instead? Under which circumstances?**

```
Checking 'alertmanager.yml'  FAILED: unsupported scheme "" for URL

amtool: error: failed to validate 1 file(s)
```

**Environment**

* System information:

	Darwin 19.4.0 x86_64

* Alertmanager version: (this is the result of `amtool --version`)

	amtool, version  (branch: , revision: )
        build user:
        build date:
        go version:       go1.13.8

**Comment by kenju** [comment]
For example, this error happens when loading the config file.

https://github.com/prometheus/alertmanager/blob/a9d4a714943aa9b66145a43a5569e822dc2669b0/cli/check_config.go#L66-L72

Internally, it tries to `parseURL(s string)` but it fails with the error (in my case, it is because the string is an empty string and is not a valid URL schema). Those functions return `error` types.

https://github.com/prometheus/alertmanager/blob/a9d4a714943aa9b66145a43a5569e822dc2669b0/config/config.go#L86-L98

In order to pass along line numbers, I guess we should create a new struct as a wrapper for storing error context (e.g. line number, stack trace, file path, error itself, etc.). It'll require so many places to be changed for the current codebase.

What do you think?

**Comment by brian-brazil** [comment]
This would depend on switching to the YAML v3 library, which we're not sure is a good idea yet as it seems that re-marshalling configs requires duplicating our many many config structs.

**Comment by kenju** [comment]
> re-marshalling configs requires duplicating our many many config structs.

Yes that's what I am wondering so I've asked you before working on it.

> This would depend on switching to the YAML v3 library, 

It seems like v3 is now under active development 🚧  and the line number feature is still in discussion. 

- https://github.com/go-yaml/yaml/tree/v3
- https://github.com/go-yaml/yaml/issues/626

**Comment by brian-brazil** [comment]
The line numbers are there already with v3, the problem we're running in to is the re-marshalling if you use them.
