### ISSUE TITLE
Cant receive alerts when webhook is confgured for Google Hangouts

### ISSUE THREAD

**Issue by mitunmbj** [prometheus/alertmanager#2318]
global:
  resolve_timeout: 5m

route:
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1m
  receiver: 'hangouts-chat-webhook'

receivers:
  - name: 'hangouts-chat-webhook'
    webhook_configs:
    - url: https://chat.googleapis.com/v1/spaces/AAAA9496ngU/XXXXXXXXXXXXXXXXXXXXXXXXX

The above is my config file
I am not able to receive alerts please recahout if u guys can help

**Comment by simonpasquier** [comment]
You need a webhook service such as [alertmanager2hangoutschat](https://github.com/FortnoxAB/alertmanager2hangoutschat) that translates the Alertmanager notiification to a hangout message.

I'm closing it for now. If you have further questions, please use our [user mailing list](https://groups.google.com/forum/#!forum/prometheus-users), which you can also search.
