### ISSUE TITLE
Fingerprint id is missing on docs

### ISSUE THREAD

**Issue by marcusteixeira** [prometheus/alertmanager#2328]
In the last commit(#2308) in the documentation of the alert template, a reference to the fingerprint id was included. 

![image](https://user-images.githubusercontent.com/40602844/87947277-7a4de400-ca79-11ea-85b2-aa684d78f294.png)

When we look at the site, we can see that the last change on the page was not deployed.
![image](https://user-images.githubusercontent.com/40602844/87947210-5e4a4280-ca79-11ea-9476-3213b14dc30f.png)

Is the site deployed at each commit or only when a new release is delivered?

**Comment by marcusteixeira** [comment]
Is the site deployed at each commit or only when a new release is delivered?

**Comment by marcusteixeira** [comment]
@simonpasquier

**Comment by roidelapluie** [comment]
This is deployed on each release. You can select the release on a dropdown in the left.
