### ISSUE TITLE
Question : Do we have support for dynamic receiver configuration? 

### ISSUE THREAD

**Issue by raz08** [prometheus/alertmanager#2335]
Is there a mechanism to configure receivers and routes  through REST API or  through any other way in Alert manager?

**Comment by woraser** [comment]
Follow. It's necessary.

**Comment by raz08** [comment]
I didn't get @woraser

**Comment by simonpasquier** [comment]
There's not. It's an explicit design decision that Alertmanager can only be configured from files.

I'm closing it for now. If you have further questions, please use our [user mailing list](https://groups.google.com/forum/#!forum/prometheus-users), which you can also search.
