### ISSUE TITLE
Loading the example configuration file fails

### ISSUE THREAD

**Issue by bcandrea** [prometheus/alertmanager#234]
When starting the alertmanager with the simple.yml example configuration files, the application dies with the error 

    Loading configuration file failed: Undefined receiver "" used in route

Which can be fixed by adding a `receiver` key to the main route. Is this the expected behaviour (i.e. to enforce the existence of a catch-all receiver)?

**Comment by fabxc** [comment]
This was indeed wrong but has been fixed for a while.
