### ISSUE TITLE
Metrics-Endpoint returns 404

### ISSUE THREAD

**Issue by cherti** [prometheus/alertmanager#235]
The alertmanager's metrics-endpoint /metrics exposed via -web.listen-address returns a 404-error on http-request.

**Comment by fabxc** [comment]
Metrics were added after 0.1.0-beta1. What revision are you using.

**Comment by cherti** [comment]
The most recent pre-release. Building from git fixes this, you say, @fabxc?

alertmanager, version 0.1.0-beta1 (branch: master, revision: 26cfefd)
build date:       20160108-19:32:30

**Comment by cherti** [comment]
Works from HEAD, nevermind :)
