### ISSUE TITLE
Feature Request: More WebHook Channels

### ISSUE THREAD

**Issue by shockogit** [prometheus/alertmanager#2360]
**What did you do?** Setup alerts to fire to Cisco WebEx Teams Incoming WebHooks

**What did you expect to see?** An alert message in Cisco WebEx Teams

**What did you see instead? Under which circumstances?** Cisco WebEx teams rejected the POST due to message format

**Environment** Cisco WebEx Teams

I was actually using the AlertManager embedded in Red Hat OpenShift. It got me thinking though that it would be great to have a capability to send to other messaging apps. It seems like the WebHook payload for AlertManager is somewhat hardcoded.

**Comment by dswarbrick** [comment]
This kind of thing generally requires implementing an intermediate web hook which accepts the Alertmanager notification, and relays it in whatever custom / proprietary format is needed for the ultimate target of the notification.

There are numerous examples of such use cases available if you search a bit.

**Comment by simonpasquier** [comment]
What Daniel says, the canonical way to integrate Alertmanager with other systems is to write a custom webhook service.
