### ISSUE TITLE
How to send  "resolved" status to alerts by api

### ISSUE THREAD

**Issue by baturorkun** [prometheus/alertmanager#2366]
I can send "silence" to alerts by API. But I want to send "resolved" state to alerts by API. I could not find any endpoint?

**Comment by simonpasquier** [comment]
See https://prometheus.io/docs/alerting/latest/clients/. To "resolve" an alert, you'd have to set the `endsAt` field to a past value. 

I'm closing it for now. If you have further questions, please use our [user mailing list](https://groups.google.com/forum/#!forum/prometheus-users), which you can also search.

**Comment by sgpinkus** [comment]
I have a Q related to this. Linked doc states:

> Clients are expected to continuously re-send alerts as long as they are still active (usually on the order of 30 seconds to 3 minutes). Clients can push a list of alerts to Alertmanager via a POST request.

But if you send 1 alert event to the alertmanager API (without a `endsAt`) after what interval does alertmanager consider it no longer happening? Based on testing it appears to be 150s by default (?) but I can't find any discussion in docs about it. Is it configurable?

**Comment by simonpasquier** [comment]
@sgpinkus in this case, the global `resolve_timeout` parameter will be applied (see https://prometheus.io/docs/alerting/latest/configuration/).
