### ISSUE TITLE
On alertmanager templates,  how to use a literal on KV.Remove to remove a specific key?

### ISSUE THREAD

**Issue by framegrace** [prometheus/alertmanager#2367]
**What did you do?**

I want to remove a single key from the Common or Group Label templates when creating a template.

**What did you expect to see?**

I see the Remove function on KV accepts []string as a parameter, so I expected to be able to do something like 
{{ CommonLables.Remove  ["key1","key2"]  }}

Is there any way, to indicate a String literal in there? If not, I think it could be a good addition.

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by acarmel** [comment]
> **What did you do?**
> 
> I want to remove a single key from the Common or Group Label templates when creating a template.
> 
> **What did you expect to see?**
> 
> I see the Remove function on KV accepts []string as a parameter, so I expected to be able to do something like {{ CommonLables.Remove ["key1","key2"] }}. But anything I try returns errors. I've tried all common array and hash specifications and all sort of separators.
> 
> Is there any way, to indicate a String literal in there? If not, I think it could be a good addition.

I also struggled to get it to work and found this:
```
{{ CommonLables.Remove stringSlice "label_a" "label_b" "label_c" }}
```

https://prometheus.io/docs/alerting/latest/notifications/#functions
