### ISSUE TITLE
Prometheus AlertManger : Call script to send notification to Third Party Tool (BMC TrueSight) instead of Webhook

### ISSUE THREAD

**Issue by imvijaysingh** [prometheus/alertmanager#2381]
Hello Team,

I would like to setup my Prometheus AlertManager environment, 
We need to call script/binary to send alerts/notification to Third Party Monitoring Tool (e.g BMC True Sight)
Currently only webhook can able to send notification to TrueSight but my requirement to execute script/binary through Prometheus.

Please help...

Best,
Vijay

**Comment by simonpasquier** [comment]
I know of https://github.com/imgix/prometheus-am-executor which can receive notifications from Alertmanager and execute scripts accordingly. It isn't something we plan to support directly in Alertmanager though.

I'm closing it for now. If you have further questions, please use our [user mailing list](https://groups.google.com/forum/#!forum/prometheus-users), which you can also search.
