### ISSUE TITLE
Alertmanager Notify attempt failed, will retry later username and password not accepted

### ISSUE THREAD

**Issue by MohdRashid01** [prometheus/alertmanager#2386]
Hi All,

Actual my task is to monitor docker containers, cpu utilization and harddisk usage

I have installed grafana, prometheus and alertmanager in Hetzner Cloud VM.

And getting email notification like this that showing in metric but i need in Units like GB/MB for all docker containers
![image](https://user-images.githubusercontent.com/7812871/95169152-0e555f00-07d0-11eb-98df-cd4c7749db60.png)

But getting error that google or gmail app password is not accepted.

I have given correct username, email and password but still im getting error

Logs of alertmanager below level=warn ts=2020-09-30T13:25:50.041Z caller=notify.go:674 component=dispatcher receiver=slack integration=email[0] msg=“Notify attempt failed, will retry later” attempts=3 err="*email.loginAuth auth: 535 5.7.8 Username and Password not accepted. Learn more at\n5.7.8 https://support.google.com/mail/?p=BadCredentials m1sm194703lfr.32 

![image](https://user-images.githubusercontent.com/7812871/95168909-a6067d80-07cf-11eb-8b02-ec939e216d15.png)

![image](https://user-images.githubusercontent.com/7812871/95168942-b28ad600-07cf-11eb-80ff-6c2a1de0c22f.png)

but this same method are working in my local machine with same cred or different cred also

@farcaller @grobie @jamtur01 @logan @jjneely

**Comment by simonpasquier** [comment]
Unfortunately there's nothing more we can do than logging the server's response. I suggest that you contact the Google support instead.

I'm closing it for now. If you have further questions, please use our [user mailing list](https://groups.google.com/forum/#!forum/prometheus-users), which you can also search.

**Comment by lkokila** [comment]
This happens probably because Google is not allowing you to log in since it has flagged this sort of login as "less secure", so what you have to do is go to this link while you're logged in to your google account, and allow the access:

https://www.google.com/settings/security/lesssecureapps
