### ISSUE TITLE
[doc][typo] RFC 6980 Text and Link inconsistency in README.md

### ISSUE THREAD

**Issue by sakaia** [prometheus/alertmanager#2394]
README.md document has inconsistency for RFC 6980 Text and Link

```
[RFC 6980](https://tools.ietf.org/html/rfc6890)
```

It seems old issue.

[README.md: update HA section](https://github.com/prometheus/alertmanager/commit/47c84402af60e09d807e7d0a7cffbd3c6745fa5d)

**Comment by simonpasquier** [comment]
Closed by #2396
