### ISSUE TITLE
Giant buttons on mobile

### ISSUE THREAD

**Issue by smithy9901** [prometheus/alertmanager#2412]
Giant buttons on mobile, on a normal size desktop, can this be set up?
`    actions:
    - type: button
      text: 'Grafana'
      url: 'https://xxx.xxx.com/'`

<img width="344" alt="Снимок экрана 2020-11-04 в 12 40 09" src="https://user-images.githubusercontent.com/37003941/98094874-ea526f80-1e9a-11eb-9cf0-a874d804c602.png">

<img width="286" alt="Снимок экрана 2020-11-04 в 12 40 41" src="https://user-images.githubusercontent.com/37003941/98094929-f807f500-1e9a-11eb-8225-e8fce05c7cb8.png">

**Comment by paulfantom** [comment]
This seems like a slack issue and not alertmanager one. AFAIK button size is not customizable via slack message payload.

**Comment by simonpasquier** [comment]
As @paulfantom says, the problem should be reported to Slack directly.
