### ISSUE TITLE
Alert manager does not send Expect: 100-Continue header to webhook

### ISSUE THREAD

**Issue by poornima-repo** [prometheus/alertmanager#2425]
**What did you do?**

**What did you expect to see?**

**What did you see instead? Under which circumstances?**

**Environment**

* System information:

	insert output of `uname -srm` here

* Alertmanager version:

	insert output of `alertmanager --version` here (repeat for each alertmanager
	version in your cluster, if relevant to the issue)

* Prometheus version:

	insert output of `prometheus --version` here (repeat for each prometheus
	version in your cluster, if relevant to the issue)

* Alertmanager configuration file:
```
insert configuration here
```

* Prometheus configuration file:
```
insert configuration here (if relevant to the issue)
```

* Logs:
```
insert Prometheus and Alertmanager logs relevant to the issue here
```

**Comment by roidelapluie** [comment]
Why should it?

**Comment by poornima-repo** [comment]
Is there a way that I can send it since the webhook listener is expecting it ?

**Comment by roidelapluie** [comment]
Webhooks listeners are expected to be built for AM, which does not support this. It seems like a bug in the listener. This is not possible with alertmanager.

**Comment by simonpasquier** [comment]
The webhook receiver will consider replies with status code from 200 to 299 as successful, anything else is a failure.

I'm closing it for now. If you have further questions, please use our [user mailing list](https://groups.google.com/forum/#!forum/prometheus-users), which you can also search.
