### ISSUE TITLE
Consider allowing the use of annotations in other annotations

### ISSUE THREAD

**Issue by grobie** [prometheus/alertmanager#243]
There are alerts where the current value is not useful, for example `predict_linear(foo_current, 3600) > foo_max`. It's possible to run another expression during evaluation `{{ printf `foo_current{instance="%s"}` $labels.instance | query }}`. Using that in a description makes the description quickly unreadable.

Allowing evaluated annotations to be used in other annotations could help here

```
...
ANNOTATIONS {
  current = "{{ printf `foo_current{instance="%s"}"
  description = "The server has {{$annotations.current}} foos and will reach the maximum in less than 1h"
}
```

p.s. real world expressions will be a lot longer and thus harder to read.

**Comment by brian-brazil** [comment]
This a Prometheus feature request, not alertmanager.

I don't think this is something we should implement, as labels and annotations are unordered it'd require us to parse them and determine an ordering. Particularly with alerts where evaluation should be kept really low for reliability, we shouldn't be encouraging complex analysis and the sort of templating that requires abstractions like this.

**Comment by fabxc** [comment]
I agree that it needs ordering in the implementation. But it certainly
doesn't involve complex analysis or a remotely relevant performance impact.
