### ISSUE TITLE
HA for Alert-manager

### ISSUE THREAD

**Issue by mohanagandlla** [prometheus/alertmanager#2432]
Hi for the sake of HA in alert-manager I have deployed two instances and those two were successfully configured in promethus now my point is how to enable the gossip between those two instances and i have see some warn logs here

level=info ts=2020-12-08T05:04:57.578Z caller=main.go:216 msg="Starting Alertmanager" version="(version=0.21.0, branch=HEAD, revision=4c6c03ebfe1009c546e4d1e9b92c371d67c021d)"
level=info ts=2020-12-08T05:04:57.578Z caller=main.go:217 build_context="(go=go1.14.4, user=root@dee3592357f, date=20200617-08:54:02)"
level=warn ts=2020-12-08T05:04:57.593Z caller=cluster.go:228 component=cluster msg="failed to join cluster" err="1 error occurred:\n\t* Failed to resolve alertmanager-test-0.alertmanager-operated.depl.svc:9094: lookup alertmanager-test-0.alertmanager-operated.depl.svc on x.x.x.x:53: no such host\n\n"
level=info ts=2020-12-08T05:04:57.593Z caller=cluster.go:230 component=cluster msg="will retry joining cluster every 10s"
level=warn ts=2020-12-08T05:04:57.593Z caller=main.go:307 msg="unable to join gossip mesh" err="1 error occurred:\n\t* Failed to resolve alertmanager-test-0.alertmanager-operated.depl.svc:9094: lookup alertmanager-test-0.alertmanager-operated.depl.svc on x.x.x.x:53: no such host\n\n"
level=info ts=2020-12-08T05:04:57.593Z caller=cluster.go:623 component=cluster msg="Waiting for gossip to settle..." interval=2s
level=info ts=2020-12-08T05:04:57.614Z caller=coordinator.go:119 component=configuration msg="Loading configuration file" file=/etc/alertmanager/config/alertmanager.yaml
level=info ts=2020-12-08T05:04:57.614Z caller=coordinator.go:131 component=configuration msg="Completed loading of configuration file" file=/etc/alertmanager/config/alertmanager.yaml
level=info ts=2020-12-08T05:04:57.617Z caller=main.go:485 msg=Listening address=:9093
level=info ts=2020-12-08T05:04:59.594Z caller=cluster.go:648 component=cluster msg="gossip not settled" polls=0 before=0 now=1 elapsed=2.000220306s
level=info ts=2020-12-08T05:05:07.594Z caller=cluster.go:640 component=cluster msg="gossip settled; proceeding" elapsed=10.00090527s
level=warn ts=2020-12-08T05:05:13.057Z caller=cluster.go:438 component=cluster msg=refresh result=failure addr=alertmanager-test-0.alertmanager-operated.depl.svc:9094 err="1 error occurred:\n\t* Failed to resolve alertmanager-test-0.alertmanager-operated.depl.svc:9094: lookup alertmanager-test-0.alertmanager-operated.depl.svc on x.x.x.x:53: no such host\n\n"

**Comment by roidelapluie** [comment]
Thanks for your report. It looks as if this is actually a question about usage and not development.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
