### ISSUE TITLE
Add a counter for notify errors

### ISSUE THREAD

**Issue by Shadi** [prometheus/alertmanager#2436]
**What did you do?**

One of the receivers had a problem in the configuration, it was a valid prometheus yaml configuration but invalid pagerDuty config, the alerts were not being sent because of that, and we only discovered it by looking at the logs.

**What did you expect to see?**

If there is a counter for this then we can create an alert based on this counter to detect these issues.

**What did you see instead? Under which circumstances?**

Notifications were not sent and alerts were missed.

**Environment**

* Alertmanager version: `v0.20.0`

* Prometheus version:  `v2.22.1`

* Logs:
```
level=error ts=2020-12-17T13:26:43.345Z caller=dispatch.go:301 component=dispatcher msg="Notify for alerts failed" num_alerts=237 err="cancelling notify retry for \"pagerduty\" due to unrecoverable error: unexpected status code 400: Event object is invalid: Service key is the wrong length (should be 32 characters),Service key can't contain line feeds,Service key cannot contain non-alphanumeric characters.
```

I can create a PR and add a counter and increase it here when the context is not canceled : https://github.com/prometheus/alertmanager/blob/master/dispatch/dispatch.go#L309

**Comment by simonpasquier** [comment]
Yes there are metrics for this, it's `alertmanager_notifications_failed_total` and `alertmanager_notifications_total`.

I'm closing it for now. If you have further questions, please use our [user mailing list](https://groups.google.com/forum/#!forum/prometheus-users), which you can also search.
