### ISSUE TITLE
Alertmanager with class E IP addresses

### ISSUE THREAD

**Issue by sjmiller609** [prometheus/alertmanager#2438]
This could be considered a bug / edge case or a feature request, it's somewhere in between. Some enterprises use private networks outside of RFC 1918, for example Class E networks. These are necessary for enterprises that have exhausted or otherwise allocated all RFC 1918 address space. I would like for alertmanager to accept IP addressed like these.

**What did you do?**

Provision alertmanager on GKE using Class E, private pod IP addresses https://cloud.google.com/vpc/docs/vpc#valid-ranges

**What did you expect to see?**

Normal alertmanager, same as using RFC 1918 address space.

**What did you see instead? Under which circumstances?**

"No private IP address found, and explicit IP not provided"

**Environment**

GKE, host network using a normal, private subnet and pods and services using Class E. Using these IPs is the source of the issue.

![image](https://user-images.githubusercontent.com/7516283/102816176-91cc2880-439b-11eb-9cb6-564e110e60fe.png)

Alertmanager version 0.20.0

```
k get pods -o wide | grep alert
astro-alertmanager-0                                  0/1     CrashLoopBackOff   61         4h49m   240.1.0.142   gke-steven-active-steven-default-node-eba56e82-11nc   <none>           <none>
```
* Logs:

```
level=info ts=2020-12-21T19:41:02.158Z caller=main.go:231 msg="Starting Alertmanager" version="(version=0.20.0, branch=HEAD, revision=f74be0400a6243d10bb53812d6fa408ad71ff32d)"
level=info ts=2020-12-21T19:41:02.159Z caller=main.go:232 build_context="(go=go1.13.5, user=root@00c3106655f8, date=20191211-14:13:14)"
level=warn ts=2020-12-21T19:41:02.159Z caller=cluster.go:154 component=cluster err="couldn't deduce an advertise address: no private IP found, explicit advertise addr not provided"
level=error ts=2020-12-21T19:41:02.160Z caller=main.go:256 msg="unable to initialize gossip mesh" err="create memberlist: Failed to get final advertise address: No private IP address found, and explicit IP not provided"
```

**Comment by simonpasquier** [comment]
For now, Alertmanager mandates that you specify the advertised address if it can't deduce an address in a range covered by RFC 6890 (as mentioned in the README.md). You should be able to resolve this by getting the pod's IP address from the [downward API](https://kubernetes.io/docs/tasks/inject-data-application/environment-variable-expose-pod-information/#use-pod-fields-as-values-for-environment-variables) and binding the cluster listener to this address explicitly (e.g. `--cluster.advertise-address=$(POD_IP):9094`).

**Comment by sjmiller609** [comment]
Hi @simonpasquier thank you for your help, I will give this a shot.

**Comment by fhoda** [comment]
@simonpasquier , I am following up for @sjmiller609 . I have tried this and it works. Thank you.

**Comment by sjmiller609** [comment]
@simonpasquier Thanks for your tip. If I understand correctly, the point of checking if it's in RFC 6890 is in order to prevent users from accidentally serving on a public network. Unless you think that adding class E is reasonable and beneficial to add into accepted range (since they are not public IPs), I am fine with having this issue closed because there is an option that works. Thanks again for your help.
