### ISSUE TITLE
Flaky integration tests in CI

### ISSUE THREAD

**Issue by mucamaca** [prometheus/alertmanager#2453]
This was originally an email to the prometheus-developers@googlegroups.com mailing list, but since google wants me to be a group member and I refuse to make a google account just for that,I'm posting it here intact. Almost none of the standard fields required in the issue template are applicable.

Hi all,

I opened PR #2444  in the prometheus/alermanager repo on github about a
week ago. All but one automatic check that github performed were
successful - I forgot to sign off the commit. I amended the commit with
a signoff and force pushed. The sign-off check passed, but another check
(that previously succeeded) reported failure [ [link](https://app.circleci.com/pipelines/github/prometheus/alertmanager/1568/workflows/5fb43a61-e0c9-4a08-923d-7b80f5a3601d/jobs/7348) ]. Note that only a
single line was added to the commit message between those two runs of
the same check. I tried amending and force pushing again, thinking that
the failure might go away just like it came. And it turns out it did. So
I was left with all checks passed and a weird test failure that I don't
understand because I'm not familiar with alertmanager codebase at all.

Is this a known issue? Is someone more familiar going to look into this?

Anyway, thanks for making great software!

Regards,
Bor Groselj Simic

**Comment by mucamaca** [comment]
On another note, please consider migrating the mailing list to somewhere else. Having to own a google account for participation is a significant barrier to entry for many potential contributors and hosting the mailing list on a proprietary platform is not really in the spirit of FOSS.

**Comment by simonpasquier** [comment]
:wave: thanks for raising the issue. Yes the so-called integration tests are flaky with the current CI infra. If someone wants to have a look at it, feel free to do so :)

**Comment by gotjosh** [comment]
The link is dead and I was unable to find out what test is the actual flaky one - closing this.
