### ISSUE TITLE
Alert manager not recognizing Webhook response with only status line

### ISSUE THREAD

**Issue by poornima-repo** [prometheus/alertmanager#2457]
Hi Team,
I can see that alertmanager is not recognizing the webhook response with only status line. 
So it keeps sending repeated notifications.

What is the minimal response that alert manager expects from webhook ?

**Comment by hooten** [comment]
Hi @poornima-repo, I think that only a `2xx` response from the webhook receiver is necessary. 

The webhook notifier will retry if it [encounters an error when it POSTs](https://github.com/prometheus/alertmanager/blob/master/notify/webhook/webhook.go#L116), or if the [response status code is `5xx`](https://github.com/prometheus/alertmanager/blob/master/notify/util.go#L168) (the webhook retrier doesn't have any additional retry codes). Whereas [`2xx` responses are consider to always be successful](https://github.com/prometheus/alertmanager/blob/master/notify/util.go#L169). I hope this helps.

If you have further questions, I suggest using the [prometheus-users mailing list](https://prometheus.io/community/) which is the intended forum for such questions. Github issues are used for bug reports in the Prometheus projects.

**Comment by simonpasquier** [comment]
thanks @hooten for helping here! Yes the webhook receiver expects a 2xx response. Having said an empty response should be valid.
