### ISSUE TITLE
Remove Alertmanager API v1

### ISSUE THREAD

**Issue by simonpasquier** [prometheus/alertmanager#2469]
Alertmanager API v2 is available since v0.16.0 and it's probably fair to say that it's (at least) feature-equivalent to the API v1 since v0.19.0. At the time when v0.16.0 was released, the [CHANGELOG](https://github.com/prometheus/alertmanager/blob/master/CHANGELOG.md#0160--2019-01-17) stated that v1 would be removed in v0.18.0. Obviously it hasn't happened yet and this issue is to discuss if/when it should happen.

cc @roidelapluie @beorn7 

xref https://github.com/prometheus/prometheus/issues/8398

**Comment by beorn7** [comment]
Good to know that the API v1 removal had been announced long ago.

Yes, it would be great to retire v1 as soon as reasonably possible. It's existence caused us a lot of headache when adding new features.

**Comment by beorn7** [comment]
Also, let's remember to remove any json tags and json marshalling code that are not needed anymore after the removal (if that applies to any).

**Comment by gotjosh** [comment]
I'll be happy to take care of this.

**Comment by beorn7** [comment]
Great. Just note that we should coordinate this with https://github.com/prometheus/prometheus/issues/8398 , i.e. ideally we only remove the v1 API once Prometheus defaults to the v2 API to avoid friction.

**Comment by gotjosh** [comment]
Consensus was reached during the Alertmanger Working Group that we'll proceed with this but keep the `api/v1/alerts` endpoint as a redirect to the `api/v2/alerts` endpoint.
