### ISSUE TITLE
Allow filtering silences by creator

### ISSUE THREAD

**Issue by goek-han** [prometheus/alertmanager#2476]
**What did you do?**
I tried to filter silences which were created by me (to see if I forgot to expire them). As this didn't work, I tried to filter by the exact ID, which also didn't work. I asked in the Martrix channel 
https://matrix.to/#/!HaYTjhTxVqshXFkNfu:matrix.org$161244270149569UcYSG:matrix.org?via=matrix.org
and it seems this is not possible. 
I mean it could be that this is a strange use case.

**Environment**
Alertmanager version: 0.21

**Comment by hooten** [comment]
This issue is related to https://github.com/prometheus/alertmanager/issues/2410
