### ISSUE TITLE
Add more data to receiver object on /api/v2/receiver

### ISSUE THREAD

**Issue by metalmatze** [prometheus/alertmanager#2491]
**What did you do?**

I made a request to `/api/v2/receivers` and only saw and array with objects containing the receiver's names and that's it.

**What did you expect to see?**

I expect to see basically the array filled with objects containing all data that the Alertmanager has of receivers.
More specifically, I'm looking for `{"webhook_configs": {"url": "http://..."}}` for each receiver. 

Instead I now get the config from `/api/v2/status` and parse it to get the receivers full data...

**Environment**

* System information:

	Kubernetes

* Alertmanager version:

	0.21.0

* Prometheus version:

	2.23.0

Now I'm wondering if that's so sparse on purpose or if we can add this to the API endpoint. :)

**Comment by roidelapluie** [comment]
I don't think this is not possible since this could leak secrets.

**Comment by metalmatze** [comment]
Interesting. Yes, I suspected something along those lines. 
However, the config itself needs to be sanitized too, so generally speaking that should be possible with this too, shouldn't it? :thinking:

**Comment by roidelapluie** [comment]
We do not render the config as json but in a big text field in json.

**Comment by metalmatze** [comment]
Yep. Just used that part at it earlier. 
I think it should be possible to do something similar with these data types before handing them over to the swagger generated parts.
https://github.com/prometheus/alertmanager/blob/d57b2dcdeca9164d873fdba4c7129320db4a3cf6/config/config.go#L48-L68

For now I'm fine with just parsing the config YAML I get from the status API. I was just wondering if this would be accepted in general. :)

**Comment by roidelapluie** [comment]
At least not in the same API endpoint as this would be a breaking change.

Note that I also already considered doing this (parsing the yaml). I don't remember if I ended up really doing it.

**Comment by metalmatze** [comment]
I guess it works for me for now, so I don't have any hard feelings about this right now. Closing for now.
