### ISSUE TITLE
can't get alertmanger to sent mails through exchange server

### ISSUE THREAD

**Issue by mortenix** [prometheus/alertmanager#2507]
hi 
i am a total beginner with Prometheus, and alertmanager, 
I can't get alertmanager to send any mail alerts out, through our company´s exchange server using a relay account, i have also tried with a gmail server but doesn't work either. 
Is there anything i'm missing?  it seem's to be working fine until it says firing, and then i never receive any mails. Is there any way i can check if the program actually can access the mail account? or see where i fails
i have looked on multiple websites and the only thing i have found out, is that everybody is running a linux setup instead of windows like me :(
i am running the program on a virtual machine, with windows server 2016. the machine can ping and connect to the mail server, tested by sending mails with a simple powershell script.

**Environment**
windows server environment, with a microsoft exhange server
* System information:
	a virtual machine, windows server 2016 datacenter
* Alertmanager version:
version: 0.21.0

* Prometheus version:
version: 2.24.1

* Alertmanager configuration file:
global:
  resolve_timeout: 1m

route:
  group_by: [Alertname]
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  # Send all notifications to me.
  receiver: 'email_notification'

receivers:
- name: 'email_notification'
  email_configs:
  - to: ******.******@****.com
    from: smtp_relay@******.com
    smarthost: smtp.******.com:587
    smtp_auth_username: smtp_relay@******.com
    smtp_auth_password: ******
    send_resolved: true

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']insert configuration here

* Alert_rules configuration file:
groups:
 - name: alert_rules
   rules: 
   - alert: instanceDown
     expr: up == 0
     for: 1m
     labels:
       severity: "critical"
     annotations: 
       summary: "Endpoint  {{ $labels.instance }} down"
       description: "{{ $labels.instance }} of job {{ $labels.job }} has been down of for more than 1 minutes."
     
* Prometheus configuration file:

**Comment by obrienrobert** [comment]
@mortenix did you find a solution to this problem in the end? I'm hitting the same issue.

**Comment by chaofanx** [comment]
I have a similar problem, how did you solve it
