### ISSUE TITLE
Add dashboards for Alertmanager's mixin

### ISSUE THREAD

**Issue by ArthurSens** [prometheus/alertmanager#2529]
## Feature request

It would be lovely if Alertmanager's mixins could include two dashboards:

1. Alertmanager monitoring: To monitor Alertmanager itself, it would include metrics that are exposed by Alertmanager.
2. Alertmanager alerts: An informational dashboard that tells us what alerts are currently at the `firing` state, split by `severity`. For this one, I think it would be necessary to have [Alertmanager's Grafana Datasource plugin](https://grafana.com/grafana/plugins/camptocamp-prometheus-alertmanager-datasource/), so I'm not sure how viable it could be.

**Comment by beorn7** [comment]
Yeah, not sure either, if we should rely on a specific plugin in this mixin. The same is true for all other dashboards provided by mixins. Perhaps let's defer that to a possible native support for displaying alerts in Grafana.

About the general dashboards: Sure, that's something we should have eventually.

**Comment by ArthurSens** [comment]
> Perhaps let's defer that to a possible native support for displaying alerts in Grafana.

Sounds good to me :)

Regarding the dashboard that monitors Alertmanager itself, could we start with a plain JSON? Or do you prefer that we should already start using jsonnet+grafonnet?

**Comment by ArthurSens** [comment]
I've practiced a little bit with grafonnet-lib this last week. I think I'll have no problem creating the dashboard with jsonnet instead of plain JSON :)


> One might argue if jsonnet is the right way to do that, but since the alerts are already provided in jsonnet, I would do the same with dashboards, at least for now.

Well, the [mixin design document](https://docs.google.com/document/d/1A9xvzwqnFVSOZ5fD3blKODXfsat5fg6ZhnKu9LK3lB4/edit#heading=h.dnmfr1m23xfz) does suggest jsonnet above all other options, I don't see why not use jsonnet 🤷 

![image](https://user-images.githubusercontent.com/24193764/113762871-6c1b2300-96ef-11eb-93b6-254eadc5e57c.png)

**Comment by xkilian** [comment]
As long as it is explained how someone not using jssonnet can also benefit from these dashboards, this is all good. (Not everyone uses it.)
I would also like to point out that there has not been a release of alertmanager in alsmot a year and the most useful feature "time based muting" has finaly been merged. 
Is there something blocking release?
