### ISSUE TITLE
Add AlertManager to Pushover's apps|Integrations

### ISSUE THREAD

**Issue by DazWilkin** [prometheus/alertmanager#2596]
**What did you expect to see?**

Prometheus AlertManager listed as a Pushover application on Pushover's [Pushover-powered Applications & Plugins](https://pushover.net/apps)

**What did you see instead? Under which circumstances?**

Pushover integration is not listed as an integration on Pushover's site. The integration is well-documented by AlertManager and works well.

Listing the integration on Pushover's site increases visibility of Prometheus AlertManager (integration).

This listing request needs to be submitted by someone from the Prometheus AlertManager team as validation.

I received the following from Pushover when I asked why AlertManager is not listed:

<hr/>
From: Pushover Support <support@pushover.net>

Hi, someone from the project needs to submit a request to have the application listed with its official icon, URL, etc.

https://support.pushover.net/i36-getting-your-app-website-service-listed-on-pushover-s-public-applications-integrations-page

**Comment by roidelapluie** [comment]
This page is made for SAAS. In particular, we can not guarantee to follow all the rules with alertmanager:

```
For externally hosted services, you must use one API token per service/application and you are responsible for purchasing additional capacity as needed. You may not register multiple API token to get around our message limits and you may not request or host API tokens registered by end-users.
```

So, I can not commit to all those rules. Do they have another page for self-hosted software?

**Comment by roidelapluie** [comment]
I will see what I can do.

**Comment by roidelapluie** [comment]
Here is the message I tried to send:

> Hello,
>
> I would like to list Prometheus as an integration with Pushover.
>
> Our website is https://prometheus.io
> The documentation is at https://prometheus.io/docs/alerting/latest/configuration/#pushover_config
>
> We have Pushover support since 2016.
>
> You can pick the logo you want here: https://cncf-branding.netlify.app/projects/prometheus/
>
> The author is "The Prometheus developers".



When I clicked send, I got "The message looks like spam".

![spam](https://user-images.githubusercontent.com/291750/119545177-d0bf3980-bd92-11eb-88b8-996bd6c08aa8.png)


I unfortunately does not have infinite time to spend on this, so I have to close this ticket without proper resolution.

**Comment by DazWilkin** [comment]
Thanks @roidelapluie for trying!

Unless you object (?), I will forward this comment thread to the Pushover team to see whether they'll resolve this for us.

**Comment by jcs** [comment]
@roidelapluie Sorry for the overzealous spam filter.  I've manually added a new application for you which is now listed on https://pushover.net/apps

You can direct users to your cloning URL at https://pushover.net/apps/clone/prometheus which will make it easier to register for an API token.

Thanks for the initiative @DazWilkin

**Comment by roidelapluie** [comment]
Thank you @jcs and @DazWilkin! I will try the link and add it to the documentation.
