### ISSUE TITLE
CGO with Go 1.6 causes runtime panic

### ISSUE THREAD

**Issue by nikgrok** [prometheus/alertmanager#260]
Hey guys,

I am getting this error when I try to submit a new silence from the silences page. 

2016/03/02 09:23:42 http: panic serving 192.168.83.42:49303: runtime error: cgo argument has Go pointer to Go pointer
goroutine 4653 [running]:
net/http.(*conn).serve.func1(0xc8201c4f80)
	/usr/local/go/src/net/http/server.go:1389 +0xc1
panic(0xa03d80, 0xc820883de0)
	/usr/local/go/src/runtime/panic.go:426 +0x4e9
github.com/prometheus/alertmanager/vendor/github.com/mattn/go-sqlite3._cgoCheckPointer0(0x91e7a0, 0xc8200e74c4, 0x0, 0x0, 0x0, 0x8f28e0)
	github.com/prometheus/alertmanager/vendor/github.com/mattn/go-sqlite3/_obj/_cgo_gotypes.go:65 +0x4d
github.com/prometheus/alertmanager/vendor/github.com/mattn/go-sqlite3.(*SQLiteStmt).bind(0xc8201fb630, 0xc820180060, 0x6, 0x6, 0x0, 0x0)
	/root/go/src/github.com/prometheus/alertmanager/vendor/github.com/mattn/go-sqlite3/sqlite3.go:487 +0xa39
github.com/prometheus/alertmanager/vendor/github.com/mattn/go-sqlite3.(*SQLiteStmt).Exec(0xc8201fb630, 0xc820180060, 0x6, 0x6, 0x0, 0x0, 0x0, 0x0)
	/root/go/src/github.com/prometheus/alertmanager/vendor/github.com/mattn/go-sqlite3/sqlite3.go:519 +0x7b
github.com/prometheus/alertmanager/vendor/github.com/mattn/go-sqlite3.(*SQLiteConn).Exec(0xc8204c0140, 0xbc4340, 0x7a, 0xc820180060, 0x6, 0x6, 0x0, 0x0, 0x0, 0x0)
	/root/go/src/github.com/prometheus/alertmanager/vendor/github.com/mattn/go-sqlite3/sqlite3.go:198 +0x3b0
database/sql.(*Tx).Exec(0xc8201fb590, 0xbc4340, 0x7a, 0xc8205215c8, 0x6, 0x6, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/database/sql/sql.go:1381 +0x276
github.com/prometheus/alertmanager/provider/sqlite.(*Silences).Set(0xc82015e160, 0xc8200e73f0, 0x0, 0x0, 0x0)
	/root/go/src/github.com/prometheus/alertmanager/provider/sqlite/sqlite.go:584 +0x4f2
main.(*API).addSilence(0xc8200a0700, 0x7f68ca52acf0, 0xc8200443f8, 0xc8205fcc40)
	/root/go/src/github.com/prometheus/alertmanager/api.go:300 +0x258
main.(*API).(main.addSilence)-fm(0x7f68ca52acf0, 0xc8200443f8, 0xc8205fcc40)
	/root/go/src/github.com/prometheus/alertmanager/api.go:98 +0x3e
github.com/prometheus/alertmanager/vendor/github.com/prometheus/client_golang/prometheus.InstrumentHandlerFuncWithOpts.func1(0x7f68ca52ac18, 0xc82052f2b0, 0xc8205fcc40)
	/root/go/src/github.com/prometheus/alertmanager/vendor/github.com/prometheus/client_golang/prometheus/http.go:158 +0x336
github.com/prometheus/alertmanager/vendor/github.com/prometheus/common/route.handle.func1(0x7f68ca52ac18, 0xc82052f2b0, 0xc8205fcc40, 0x0, 0x0, 0x0)
	/root/go/src/github.com/prometheus/alertmanager/vendor/github.com/prometheus/common/route/route.go:49 +0x408
github.com/prometheus/alertmanager/vendor/github.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc82023ee40, 0x7f68ca52ac18, 0xc82052f2b0, 0xc8205fcc40)
	/root/go/src/github.com/prometheus/alertmanager/vendor/github.com/julienschmidt/httprouter/router.go:299 +0x193
github.com/prometheus/alertmanager/vendor/github.com/prometheus/common/route.(*Router).ServeHTTP(0xc820244500, 0x7f68ca52ac18, 0xc82052f2b0, 0xc8205fcc40)
	/root/go/src/github.com/prometheus/alertmanager/vendor/github.com/prometheus/common/route/route.go:107 +0x42
net/http.serverHandler.ServeHTTP(0xc820206000, 0x7f68ca52ac18, 0xc82052f2b0, 0xc8205fcc40)
	/usr/local/go/src/net/http/server.go:2081 +0x19e
net/http.(*conn).serve(0xc8201c4f80)
	/usr/local/go/src/net/http/server.go:1472 +0xf2e
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2137 +0x44e

**Comment by fabxc** [comment]
Any chance you built Alertmanager yourself with Go 1.6?

**Comment by nikgrok** [comment]
I just ran the go-get

**Comment by fabxc** [comment]
What's the output of when you run `go version`?

**Comment by nikgrok** [comment]
go version go1.6 linux/amd64

**Comment by fabxc** [comment]
The error sounds like it's coming from the new CGO features of go1.6.
It seems like it clashes with our CGO use for SQLite – I wasn't aware that the changes could brake something existing. 

There's nothing immediate we can do about it. Until I find time to look into it, I would recommend downloading our release tarballs. These are working fine.

https://github.com/prometheus/alertmanager/releases/tag/0.1.0

**Comment by juliusv** [comment]
Yeah, cgo got stricter with Go 1.6 (https://github.com/golang/go/issues/12416), but I don't see Alertmanager passing any pointers to the sqlite3 lib that contain pointers back to Go. Maybe it's the sqlite3 lib itself that is at fault, like here where it calls to cgo:

```go
    case []byte:
      var p *byte 
      if len(v) > 0 {                                                                          
        p = &v[0]                                                                              
      }
      rv = C._sqlite3_bind_blob(s.s, n, unsafe.Pointer(p), C.int(len(v)))
```

It's not clear to me yet where there is a Go pointer passed that points to another Go pointer, but my guess would be the `p`. I haven't studied it much further yet.

**Comment by stapelberg** [comment]
This issue is fixed with a newer go-sqlite3, see https://github.com/mattn/go-sqlite3/pull/267

I verified this using:

$ rm -rf vendor/github.com/mattn/go-sqlite3
$ cp -r $GOPATH/src/github.com/mattn/go-sqlite3 vendor/github.com/mattn/go-sqlite3
$ make build
$ make test

Not sure what your approach to vendoring is, otherwise I would have sent a PR.

**Comment by fabxc** [comment]
Cool, thanks for figuring that out.
We use `govendor` – I can do that quickly.

**Comment by stapelberg** [comment]
This is fixed with pull request #264 but wasn’t marked as such.

**Comment by fabxc** [comment]
Yes, still waiting for confirmation by @nikgrok

**Comment by nikgrok** [comment]
Working! Thanks guys

**Comment by fabxc** [comment]
Great, thanks.
