### ISSUE TITLE
Uncaught TypeError: Cannot read property 'elmFs' of undefined

### ISSUE THREAD

**Issue by PePoDev** [prometheus/alertmanager#2605]
After chrome upgrading to version 91.0.4472.77 (Official Build) (64-bit)

I got a blank screen in Chrome and seen the error `Uncaught TypeError: Cannot read property 'elmFs' of undefined` in console log, It works fine on firefox.

* System information:

> Linux 5.4.0-1048-aws x86_64

* Alertmanager version:

> alertmanager, version 0.21.0 (branch: HEAD, revision: 4c6c03ebfe21009c546e4d1e9b92c371d67c021d)
>  build user:       root@dee35927357f
>  build date:       20200617-08:54:02
>  go version:       go1.14.4

**Comment by roidelapluie** [comment]
cc @w0rm any idea on this one? Thanks!

@PePoDev can you reproduce this with 0.22.2?

**Comment by w0rm** [comment]
Hmm, from the top of my head, this could be browser extensions. @PePoDev could you try disabling extensions that could potentially modify the page?

**Comment by PePoDev** [comment]
Oh, crap!

I open in incognito mode and it's working!

After that, I try to disable the [last extension](https://chrome.google.com/webstore/detail/odm-pro-online-video-and/opjjpmhoiojifppkkcdabiobhakljdgm) that I have installed, and it's solved. Thanks.
