### ISSUE TITLE
Inhibit rules have serious timeout issues.

### ISSUE THREAD

**Issue by cherryblossomcom** [prometheus/alertmanager#2612]
**What did you do?**
I created an inhibit rule.

**What did you expect to see?**
Prerequisite: There are two alarms A and B that are continuously triggered.
1. Create a inhibit rule：A to suppress B, which can take effect in time.
2. When the inhibit rule is deleted, the B alarm can be issued in time.

**What did you see instead? Under which circumstances?**
Prerequisite: There are two continuously triggered alarms A and B, create a subscriber C: WeChat, create a route D: send two alarms A and B to C.
1. Create a inhibit rule A to suppress B, and B cannot be suppressed in the first few periods.
2. When the inhibit rule is deleted, the B alarm cannot be issued in time.

**Environment**
* System information:

	Linux 

* Alertmanager version:

	v0.22.2
![image](https://user-images.githubusercontent.com/85533713/121480656-e2911580-c9fd-11eb-932b-ccfadc267d47.png)

* Prometheus version:

	v2.24.1
![image](https://user-images.githubusercontent.com/85533713/121480594-d0af7280-c9fd-11eb-9e37-0883df34db25.png)

* Alertmanager configuration file:
![image](https://user-images.githubusercontent.com/85533713/121481211-7c58c280-c9fe-11eb-8b27-6281fdc0c295.png)
![image](https://user-images.githubusercontent.com/85533713/121481289-8f6b9280-c9fe-11eb-909e-98cd444bddfe.png)

* Prometheus configuration file:
![image](https://user-images.githubusercontent.com/85533713/121480801-0bb1a600-c9fe-11eb-803a-93d92c5d5138.png)
![image](https://user-images.githubusercontent.com/85533713/121480824-12d8b400-c9fe-11eb-914c-ad0b8a93cf88.png)

* Logs:
None

**Comment by beorn7** [comment]
Just to confirm: Are you changing the Alertmanager config by adding (and later removing) the inthibit rule?

If so: Do you send a SIGHUP after updating the config (or restart Alertmanager altogether)?

If so: How long after sending the SIGHUP does the inhibit rule become effective? How long does it take until the alert fires again?

**Comment by beorn7** [comment]
Hi @cherryblossomcom , have you closed this accidentally? If it was deliberate, it would be great for all of us to hear what the outcome was on your side.
