### ISSUE TITLE
Amtool: x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by aleksandr-vin** [prometheus/alertmanager#2652]
I'm calling `amtool` to contact Alertmanager with custom certificate on HTTPS.

```sh
amtool --alertmanager.url https://alertmanager.local/alertmanager alert
```

**What did you expect to see?**

List of alerts.

**What did you see instead? Under which circumstances?**

```sh
amtool: error: Get "https://alertmanager.local/alertmanager/api/v2/alerts?active=true&inhibited=false&silenced=false&unprocessed=false": x509: certificate signed by unknown authority
```

**Environment**

macOS

* System information:

	Darwin 19.6.0 x86_64

* Alertmanager version:

	0.21.0

**Comment by aleksandr-vin** [comment]
I don't see how to configure TLS options for amtool's api client.

**Comment by jan--f** [comment]
#2663 added the option `tls.insecure.skip.verify` and shoud be available in [version 0.23.0](https://github.com/prometheus/alertmanager/releases/tag/v0.23.0).

**Comment by frebib** [comment]
It would be useful to be able to configure TLS key/certificate/CA chain in amtool, much like other Prometheus-suite software https://prometheus.io/docs/prometheus/latest/configuration/configuration/#tls_config instead of bypassing the security deliberately.

**Comment by insider89** [comment]
Hey. I see that this was missed in 0.24 but present in 0.23, is it expected?
