### ISSUE TITLE
"silence is not valid" on webui when using regex

### ISSUE THREAD

**Issue by ahmadalli** [prometheus/alertmanager#2671]
**What did you do?**
I tried creating an alert with regex field like `app_kubernetes_io_instance=~"application-.+"`

**What did you expect to see?**

I expected alert to be created

**What did you see instead? Under which circumstances?**

I'm receiving `Could not submit the form, Silence is not yet valid.` error while the filed itself was green.
![image](https://user-images.githubusercontent.com/2167301/128374768-99d38653-dfd7-4ac1-906a-52e1bd86fc4a.png)

**Environment**

* System information:

```
Linux 5.4.0-77-generic x86_64
```

* Alertmanager version:

```
alertmanager, version 0.22.2 (branch: HEAD, revision: 44f8adc06af5101ad64bd8b9c8b18273f2922051)
  build user:       root@b595c7f32520
  build date:       20210602-07:50:37
  go version:       go1.16.4
  platform:         linux/amd64
```

* Prometheus version:

```
prometheus, version 2.28.1 (branch: HEAD, revision: b0944590a1c9a6b35dc5a696869f75f422b107a1)
  build user:       root@2915dd495090
  build date:       20210701-15:20:10
  go version:       go1.16.5
  platform:         linux/amd64
```

**Comment by roidelapluie** [comment]
Hello, you need to click the "+" button, but the field should indicate that you need to click it.

**Comment by ahmadalli** [comment]
Aha. I was clicking on create button by habit. 

> But the field should indicate that you need to click it.

Or the UI can add the written filter automatically

**Comment by silentpete** [comment]
This should be closed IMO, unless having a message post saying no filter criteria was added
