### ISSUE TITLE
UI bug: Dead alertmanager is not exposed in web UI

### ISSUE THREAD

**Issue by RichiH** [prometheus/alertmanager#268]
alertmanager died with https://github.com/prometheus/alertmanager/issues/267, but the web UI didn't give any indication of this fact.

Silences, Alerts, and Status showed the navigation, headings, etc but nothing else. Only when I saw Status was empty except for the headings "Build Info" and "Config", I realized something must wrong and then did I go to CLI on the host.

**Comment by mxinden** [comment]
@RichiH is this still relevant with the new UI?

**Comment by simonpasquier** [comment]
This can be closed. The new UI displays a "Network error" message. cc @stuartnelson3 

![image](https://user-images.githubusercontent.com/2587585/37523005-f9088f18-2925-11e8-925a-7afbd6fec0eb.png)
