### ISSUE TITLE
alertmanager: how to send mail notification with smtp server?

### ISSUE THREAD

**Issue by dannik1976** [prometheus/alertmanager#275]
Good morning friends, I need your help:
I have configured all successfuly, alertmanager takes notifications from prometheus but i would send e-mail alert notification. I have installed sendmail to test outgoing mail with my user and psw smtp and this test was successful.
Can you tell me what I have to write in alertmanager.conf (Actually my alertmanager.conf is empty) in email_configs section please?
if my smtp server is smtp.xxx.it 
if my user is xxx@xxx.it 
if my psw is xxx

I did not find any example about that.
Thanks in advance.

Daniele

**Comment by beorn7** [comment]
You have to configure alertmanager in `alertmanager.conf`.
See http://prometheus.io/docs/alerting/configuration/#email-receiver-<email_config>
ro configure the mail server and
http://prometheus.io/docs/alerting/configuration/#route-route to
configure the alert routing.

**Comment by dannik1976** [comment]
# The email address to send notifications to.
to: mymail@gmail.com
# The sender address.
from: I have to insert my smtp server? smtp.xxx.it?
# The SMTP host through which emails are sent.
smarthost: I must necessary configure a smarthost?

help please.
Thanks

**Comment by beorn7** [comment]
For "from", you use anything that makes sense as a sender address for alerts.
And yes, you must configure a smarthost.

Usually, both would be set in the global section as default values for all notifications.

Example:
```
global:
  smtp_smarthost: localhost:25
  smtp_from: alertmanager@example.com
```

**Comment by sjoerdmulder** [comment]
You have too use the 587 port and not 465; i found this out the hard-way and it is not documented at all but the underlying Go API says it in the docs: https://golang.org/pkg/net/smtp/#SendMail 

SendMail **connects** to the server at addr, switches to TLS **if possible**. 

_So SSL from the start doesn't work_
```
global:
  # The smarthost and SMTP sender used for mail notifications.
  smtp_smarthost: 'smtp.xxx.it:587'
  smtp_from: 'Alertmanager <alertmanager@example.org>'
```
Next you need to set 2 environment variables containing your user / passsword
```
SMTP_AUTH_USERNAME=xxx@xxx.it
SMTP_AUTH_PASSWORD=xxx
```
We use Sendgrid with this configuration

**Comment by grobie** [comment]
@sjoerdmulder Please have a look at https://github.com/prometheus/alertmanager/pull/266. The behavior around TLS has recently changed.

**Comment by fabxc** [comment]
The question is also addressed in #327.
The SMTP auth behavior recently changed with #308.

**Comment by j0nimost** [comment]
most guys forget to link prometheus to alertmanager. run prometheus like so:

`./prometheus -alertmanager.url http://localhost:9093` 
change the url according to your use.

**Comment by Murryy79** [comment]
How do I set custom subject line for email?
Thanks

**Comment by mxinden** [comment]
@Murryy79 Please open up usage questions in https://groups.google.com/forum/#!forum/prometheus-users.

**Comment by unnisathyarajan** [comment]
The same issue here, I am using alertmanager v0.14.0 in docker container and cannot receive email notifications. I am using AWS SES service and tested the service via sending emails via command line it worked fine.

The slack configuration works fine though, but it is not sending the resolved notification even though send_resolved is true. 


global:
templates: 
- '/etc/alertmanager/template/*.tmpl'
route:
  group_by: ['name']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h 
  receiver: first-level-notifiers 
  routes:
receivers:
- name: 'first-level-notifiers'
  email_configs:
  - to: 'unnisathya88@gmail.com'
    send_resolved: true
    from: 'admin@prometheus.example.com'
    smarthost: 'email-smtp.eu-west-1.amazonaws.com:25'
    auth_username: 'ADDDDDDDDDDDDDDDDDDQ'
    auth_password: 'ADDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDq'
  slack_configs:
  - api_url: https://hooks.slack.com/services/AAAAAAAAAAAAAAAAAAA
    send_resolved: true
    channel: '#prometheus-alerts'

Please advice!! 

Thanks in advance :)

**Comment by swapnilbarwat** [comment]
@unnisathyarajan did you find the solution for this? I am stuck at the same place.

**Comment by dojadop** [comment]
@swapnilbarwat @unnisathyarajan I was able to get this to work using port 587

**Comment by swapnilbarwat** [comment]
I missed this thread after my code got working. I was able to make it work using 465. Thanks for updating though.

**Comment by vrathore18** [comment]
@swapnilbarwat  @unnisathyarajan @dojadop : how did you fix the issue?

I am using below setting

- name: email-me
  email_configs:
  - to: vickyrathore1212@gmail.com
    from: ABC
    smarthost: email-smtp.us-east-1.amazonaws.com:587
    auth_username: "ABC"
    auth_password: "PASSWORD"

but I am getting error

msg="failed to close SMTP connection" err="tls: use of closed connection"

**Comment by swapnilbarwat** [comment]
Hey @vrathore18 - I ended up using AWS SES for notification. Here is my config:

receivers:
    - name: 'email_receiver'
      email_configs:
      - send_resolved: true
        to: <group_emaiol_id>
        from: <admin_email_id>
        smarthost: <aws-ses-notification>:25
        auth_username: <ses_username>
        auth_password: <ses_password>

This should work as 25 is open by default. But it looks like incompatible smtp connection in you case. Can you try telnet from your host first and then container. Connect to smtp on 587 and try sending EHLO <IP address of the SMTP server>. This should give you response if connection is successful.
