### ISSUE TITLE
Alert manager stops responding under production load

### ISSUE THREAD

**Issue by gfliker** [prometheus/alertmanager#276]
Hi,

We've recently migrated to the new AM (0.1.0) and the service stops responding under the load.
The load at hand is about 2500 firing alerts.
What we're seeing is the alerts endpoint does not ever load and after a while the service itself stops sending alerts.

Nothing is visible in the logs.

Before we revert to the previous version what can we do to debug and learn here.

Thx

**Comment by grobie** [comment]
I don't think we can expect sqlite to handle any bigger load. I've seen similar issues in our setup. I'd love to have a plugable database backend, so that users can choose to use PostgreSQL, MySQL, etc.

The other issue is the amount of data we sent to the frontend, that needs to be capped.

**Comment by fabxc** [comment]
That's roughly were I expected things to break down. SQLite is certainly no long term solution. Neither is any other *SQL in my opinion to be honest. I also don't want to get into the business of multiple backends. Especially not at this stage, but probably never. It comes with a lot of surface for bugs and had to predict variance in performance.

SQL also isn't a good fit for the general concerns we have and having well working storage seems superior to plugging a complex cache-everything layer in front of a database.

Currently investigating some options.

For now running multiple AMs that are fed by different Prometheus servers could be an option (of course no final solution).

**Comment by gfliker** [comment]
All of the above options pointing for us reverting back,
Mainly because even just on  Prometheus server can generate 700 alerts and im not sure it will handle that.
Also going multiple AMs in our setup means i need to manage silence, and state across to many servers.

What other options were talking about that can be leveraged in the short term ?

Many thanks

**Comment by mwitkow** [comment]
Having a backend for alertmanager alerts would be nice. Especially if you're running it on Kubernetes in ephemeral pods.

Can we add an isolation layer of interfaces for the backend?

**Comment by fabxc** [comment]
There's a simple set of interfaces abstracting the storage layer already: https://github.com/prometheus/alertmanager/blob/master/provider/provider.go

Something that implements these could replace SQLite.
Generally, I'm very much aware of the issue and working on a replacement as I find time but very wary to not throw in the next thing that "works for now".

**Comment by fabxc** [comment]
Performance issue should be fixed in 0.2.0. Please reopen if otherwise.
