### ISSUE TITLE
Upgrading Client Lib to API v2?

### ISSUE THREAD

**Issue by sinkingpoint** [prometheus/alertmanager#2762]
**What did you do?**

Used the client library in this repo (https://github.com/prometheus/alertmanager/blob/main/client/client.go)

**What did you expect to see?**

It use the v2 api

**What did you see instead? Under which circumstances?**

It's hardcoded to use the v1 api (https://github.com/prometheus/alertmanager/blob/main/client/client.go#L32)

Is this maintained? I note that it hasn't been touched in a year and a bit. Considering the expected deprecation of the v1 api we should probably update it or deprecate it along with the API (I would be in favour of the former)

**Comment by roidelapluie** [comment]
The v2 client is https://github.com/prometheus/alertmanager/blob/main/api/v2/client/alertmanager_client.go

**Comment by roidelapluie** [comment]
Would you send a PR to remove the v1 client?

**Comment by sinkingpoint** [comment]
Ah. Good to know. Yes sure
