### ISSUE TITLE
Feature Request: Add max_alerts to slack receiver

### ISSUE THREAD

**Issue by aned** [prometheus/alertmanager#2769]
We get a lot of `400s` errors when the alertmanager tries to push 20+ alerts at once to slack. 
It would be nice to have max_alerts feature, similar to what's implemented for webhook receiver: https://prometheus.io/docs/alerting/latest/configuration/#webhook_config

**Comment by roidelapluie** [comment]
is this 400s or 429? Where are the slack limits documented? Thanks!

**Comment by aned** [comment]
We got 400s. 
Slack limits: https://api.slack.com/rtm#real-time-messaging-rtm-api__limits
