### ISSUE TITLE
JSON validation in the config package

### ISSUE THREAD

**Issue by JohnnyQQQQ** [prometheus/alertmanager#2772]
I was wondering what the desired state of the JSON support for the configuration package would be. 

There is a very good support (including validation) for marshalling `Config` structs into and from YAML. Is it intentional that there is not as much validation for JSON? If not, would it be appreciated if it would be added?

**Comment by roidelapluie** [comment]
Thanks for reaching us.

It is intentional. Alertmanager is configured exclusively via YAML. I do not want to duplicate the validation code into json, because any json can be parsed with the yaml package anyway if you need that validation.
