### ISSUE TITLE
Running Alertmanager fails

### ISSUE THREAD

**Issue by mokshpooja** [prometheus/alertmanager#279]
I am new to the setup with Prometheus and Alertmanager. Getting this error when trying to start/run alertmanaget, any idea, what might be causing it?
 Error- 

```
root@ad0c1213aae8:/alertmanager# ./alertmanager
alertmanager, version 0.1.0 (branch: master, revision: 86148a3)
  build user:       bjoern@reasonableresolution
  build date:       20160223-15:38:27
  go version:       1.5.3
INFO[0000] Loading configuration file                    file=alertmanager.yml source=main.go:125
ERRO[0000] Loading configuration file failed: yaml: line 3: mapping values are not allowed in this context  file=alertmanager.yml source=main.go:128
```

My alertmanager.yml-

```
notification_config {
  name: "alertmanager_email"
  email_config {
  SMTP_AUTH_USERNAME = username@gmail.com
  SMTP_AUTH_PASSWORD = password
  to: receipent email
  from: username@gmail.com
  smarthost: smtp.gmail.com:587
  }
}

aggregation_rule {
  repeat_rate_seconds: 3600
  notification_config_name: "alertmanager_email"
}
```

**Comment by brian-brazil** [comment]
You're using an old-style config with a new alertmanager. See https://github.com/prometheus/alertmanager#example for a new-style config.

**Comment by kaihendry** [comment]
Could there please be a configuration that shows how to use SMTP_AUTH_USERNAME & SMTP_AUTH_SECRET env var?

https://groups.google.com/d/msg/prometheus-developers/JwkCCsE6ci0/pXplYRmaEgAJ

Like when one uses AWS SES? Not clear to me if this is CRAM or PLAIN or why I should even have to know this...

**Comment by fabxc** [comment]
Original issue was probably resolved.
The last one is addressed in #327

**Comment by kaihendry** [comment]
Thank you. Another example of a config is at https://github.com/kaihendry/pingprom/blob/master/alertmanager.yml#L3

**Comment by MohdRashid01** [comment]
Alertmanager is showing error Username and Password not accepted

 have installed prometheus in that i also install alertmanager for email notification into my gmail account

below is the error im getting i have given app password but still im getting error
level=warn ts=2020-09-30T13:25:50.041Z caller=notify.go:674 component=dispatcher receiver=slack integration=email[0] msg="Notify attempt failed, will retry later" attempts=3 err="*email.loginAuth auth: 535 5.7.8 Username and Password not accepted. Learn more at\n5.7.8 https://support.google.com/mail/?p=BadCredentials m1sm194703lfr.32 - gsmtp"


![image](https://user-images.githubusercontent.com/7812871/95068813-64b89400-0723-11eb-8e97-5ea841d1f731.png)

**Comment by MohdRashid01** [comment]
alertmanager.yml 
![image](https://user-images.githubusercontent.com/7812871/95069109-da246480-0723-11eb-9f71-8b4085686fb3.png)
