### ISSUE TITLE
matchers do not match when value is single-quoted

### ISSUE THREAD

**Issue by xkilian** [prometheus/alertmanager#2791]
**What did you do?**

Migrate match to matchers configuration.

**What did you expect to see?**

Matching equality or regex.

**What did you see instead? Under which circumstances?**

No match, no error.

**Environment**

* System information:

	Ubuntu Linux 18.04 LTE

* Alertmanager version:

	0.23

* Prometheus version:

	2.27.1

* Alertmanager configuration file:

This works:
```
    - matchers:
        - label = atlas-test
      receiver: day-incident
```

This doesn't:

```
    - matchers:
        - label = 'atlas-test'
      receiver: day-incident

```

* Prometheus configuration file:
```
N/A
```

* Logs:
```
N/A
```

**Comment by xkilian** [comment]
Not sure if this is related to #2766 .

**Comment by sinkingpoint** [comment]
I'd be curious why you expected this to work? Is there an example showing this working somewhere? It seems we already strip double quotes(https://github.com/prometheus/alertmanager/blob/e3fb99cc2d24330fdb81aa1d466c19b3de328b5b/pkg/labels/parse.go#L130), so I can see a principle of least surprise in stripping single quotes as well, but it would be a breaking change at this point. Not that Alertmanager is a 1.x yet, so breaking changes aren't that bad

**Comment by beorn7** [comment]
Matchers are documented [here](https://prometheus.io/docs/alerting/latest/configuration/#matcher). The documentation is very explicit about double quotes. Allowing single quotes would complicate the escaping even more, so not supporting single quotes is intentional.

Is there any value in supporting single quotes?

**Comment by xkilian** [comment]
Ah, thanks for the link to the documentation. 
As single-quotes use to work before matchers came along, it was my mistaken impression that they were supported. Thank you for the clarification. I am NOT proposing to add support for single-quotes, I just got caught when migrating my old route configurations to matchers.
