### ISSUE TITLE
Label name should be a string rather than regex in config.proto

### ISSUE THREAD

**Issue by brian-brazil** [prometheus/alertmanager#28]
Currently the label name is specified as a regex in the config for aggregation. I can't think of a sane label scheme where you'd want to aggregate based on label name rather than value, so I propose we offer `label` instead for simplicity.

**Comment by juliusv** [comment]
:+1: (probably won't get to this soon, but feel free to do it and announce it)

**Comment by brian-brazil** [comment]
This is obsolete with the new alertmanager.
