### ISSUE TITLE
Can there be a way to differentiate true failure vs failed, but worked on retry with alertmanager_notifications_failed_total?

### ISSUE THREAD

**Issue by stevenbeaullieu** [prometheus/alertmanager#2814]
We are using alertmanager_notifications_failed_total for an SLO on slack delivery in alertmanager.  Often we get initial failures that work after 1 or more retries.  Very rarely does a slack alert not work on a retry eventually.

Can there be a new total and failed notification metric that doesn't count every attempt for a notification, only a notification overall and only count a failure if it didn't work after retry?

I'm not sure of the current retry logic.  If it retries indefinitely on a 5XX response code that will have to be changed to give up in some reasonable amount of time.

Let's take a simple example.  Say you had 3 slack notifications A, B and C.  A worked first try, B worked on the 5th attempt and C didn't work within the threshold we will retry (arbitrarily say this was 100 failed attempts in 5 minutes?)

The new metrics would be:

alertmanager_unique_notifications_total{integration="slack"} 3
alertmanager_unique_notifications_failed_total{integration="slack"} 1

Whereas the old would be:

alertmanager_notifications_total{integration="slack"} 106
alertmanager_notifications_failed_total{integration="slack"} 104

Does that make sense and could this new metric be added?

**Comment by prashbnair** [comment]
alertmanager_notifications_failed_total will be 1 and alertmanager_notifications_requests_failed_total will be 104 as per the current implementation so there is no need for the new metrics.

**Comment by simonpasquier** [comment]
Closing since as @prashbnair commented already, the metrics are already there.
