### ISSUE TITLE
Support environment variable substitution in alertmanager's configuration files.

### ISSUE THREAD

**Issue by FuyuanChu** [prometheus/alertmanager#2818]
**What did you do?**

When integrating with Opsgenie, we need to write the api_key in the configuration file of alertmanager. It'll be ok if we store the manifest in a secure place. But currently, we are adopting `gitops` to manage our Kubernetes resources. So writing sensitive API keys in configurations is not secure anymore as the gitops repo is shared across developers and ops. The infosec team always challenges us about this.

As a common solution in our team, we introduced Vault + externalSecret to manage sensitive data and help us create k8s secret without knowing the secret value by ops.

With the injection secrets to pod as env variables, applications could read the secret value from environment variables.

**What did you expect to see?**

It would be better to support environment variable substitution in alertmanager's configuration files. On behalf of that, we can save our credentials in a secure vault. 

Thanks in advance.

**What did you see instead? Under which circumstances?**

Currently, we have to write sensitive credentials in alertmanagers' configuration files.

**Environment**

* System information:

	`Linux 5.4.129+ x86_64`

* Alertmanager version:

```
alertmanager, version 0.22.2 (branch: HEAD, revision: 44f8adc06af5101ad64bd8b9c8b18273f2922051)
  build user:       root@b595c7f32520
  build date:       20210602-07:50:37
  go version:       go1.16.4
  platform:         linux/amd64
```

* Prometheus version:

```
prometheus, version 2.28.1 (branch: HEAD, revision: b0944590a1c9a6b35dc5a696869f75f422b107a1)
  build user:       root@2915dd495090
  build date:       20210701-15:20:10
  go version:       go1.16.5
  platform:         linux/amd64
```

**Comment by johncming** [comment]
Save token by k8s secrets from env. Then use `opsgenie_api_key_file`.

**Comment by FuyuanChu** [comment]
@johncming Thanks, mate. That helps a lot.
