### ISSUE TITLE
Issue setting alertmanager to send the same alert to more than one receiver

### ISSUE THREAD

**Issue by CarlosTFSV** [prometheus/alertmanager#2830]
Good evening everybody.

My apologies if this has been already asked.

I have set the AlertManager to have three receivers:
Monitorizacion -> mailaddress1
Sistemas          -> mailaddress2
executer           -> webhook

I'm trying to set the alertmanager so it sends all alerts to both : 'Monitorización' and 'webhook' receivers.
Also, one particular alertname named 'HostOutOfMemory' should be notified to 'Sistemas' as well as to the previously mentioned two recievers. It should be recieved by all the receivers.

My final result is that the all alerts that are sent to the 'executer' receivert are not received by the 'Monitorizacion' receiver. In adition, the 'HostOutOfMemory' alert, is sent to the 'Sistemas' receiver, but not to 'Monitorización' and 'executer' .

Conclusion: The alerts that should be sent to at least two or three recievers are only sent to one out of three of them.

******************************
******************************
global:

  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: _'mailaddress1'_

route:
  receiver: 'executer'
  group_by: ['alertname', 'cluster']
  group_wait: 30s
  group_interval: 1m
  repeat_interval: 1m

  routes:

  - match:
      alertname: "*"
    receiver: executer
    continue: true

  - match:
      alertname: "*"
    receiver: Monitorizacion
    continue: true

 

  - match:
      alertname: HostOutOfMemory
    receiver: Sistemas
    continue: true

inhibit_rules:
- source_match:
    severity: 'critical'
  target_match:
    severity: 'warning'
  equal: ['alertname']

receivers:

- name: 'executer'
  webhook_configs:
  - url: 'http://192.168.0.60:8080/'
    send_resolved: true

- name: 'Monitorizacion'
  email_configs:
  - send_resolved: true
    to: 'mailaddress1'
    from: mailaddress1
    smarthost: smtp.gmail.com:587
    auth_username: "mailaddress1"
    auth_identity: "mailaddress1"
    auth_password: "XXXXXXXXXXXXXXXXXXXXXX"

- name: 'Sistemas'
  email_configs:
  - send_resolved: true
    to: 'mailaddress2'
    from: mailaddress1
    smarthost: smtp.gmail.com:587
    auth_username: "mailaddress1"
    auth_identity: "mailaddress1"
    auth_password: "XXXXXXXXXXXXXXXXXXXXXX"

******************************
******************************

My Prometheus, AlertManager and AMExecutor run in the same server:
Linux 4.18.0-326.el8.x86_64 x86_64    -> Is a CENTOS 8

alertmanager, version 0.23.0 (branch: HEAD, revision: 61046b17771a57cfd4c4a51be370ab930a4d7d54)
  build user:       root@e21a959be8d2
  build date:       20210825-10:48:55
  go version:       go1.16.7
  platform:         linux/amd64

  build user:       root@8175a7f5a043
  build date:       20220113-14:46:40
  go version:       go1.17.6
  platform:         linux/amd64

**Comment by hanjm** [comment]
Use 
```
- match_re:
     alertname: ".*"
``` 
to match all the alert.
The [visual editor](https://www.prometheus.io/webtools/alerting/routing-tree-editor) can assist in building routing trees.

**Comment by CarlosTFSV** [comment]
Thank you Han.
You saved me a lot of time. It work at the first try.
Thank you sir. :)

**Comment by CarlosTFSV** [comment]
Following the suggested syntax make it work
