### ISSUE TITLE
question about glibc

### ISSUE THREAD

**Issue by joeblew99** [prometheus/alertmanager#285]
Is this a dependency ? Its in the readme, but i just want to check.

**Comment by juliusv** [comment]
It's a build-time dependency, but not a run-time one.

```
$ ldd alertmanager
	not a dynamic executable
```

**Comment by juliusv** [comment]
Closing this as it seems answered. Please reopen if you have further questions!

**Comment by juliusv** [comment]
@joeblew99 I made a PR to clarify that: https://github.com/prometheus/alertmanager/pull/286

**Comment by joeblew99** [comment]
Ok thanks all. Loving Prometheus. Took 10 minutrs to deploy and config. Great stuff !!!
