### ISSUE TITLE
Feature Request: Support clock injection for testing and mocking.

### ISSUE THREAD

**Issue by joeblubaugh** [prometheus/alertmanager#2850]
In Grafana we [import some prometheus alertmanager libraries.](https://github.com/grafana/grafana/blob/93390b5a1ee430670ba1c7db7e06bbe80cd252f0/go.mod#L82)

When testing our usage of the alertmanager, it'd be convenient to be able to manipulate the clock. For example, silence maintenance happens on a time.Ticker, and silence expirations are based on real wall-clock time. If we could manipulate time, we can test Silence maintenance (we use a custom maintenance function) quickly in unit tests rather than waiting on real clock time.

In [the clock library,](https://pkg.go.dev/github.com/benbjohnson/clock) you create a clock.Clock interface - in real systems this is a wrapper around the time libraries, and during testing you use a MockClock to manipulate time.

Proposal: Depend on benbjohnson/clock and inject a clock.Clock any where a `time.Now()` or `time.Ticker` is used. The library is MIT-licensed.

There are 6 usages of time.Ticker and 43 appearances of time.Now, including in tests. It's not necessary to instantiate only a single clock.Clock and thread it down to all dependencies or anything like that. Clocks could be instantiated at the construction of the objects that make time calls.

(I would be willing to do this change if the proposal is acceptable)

**Comment by simonpasquier** [comment]
Would it be limited to the `silence` package? In `silence/silence_test.go`, we override the `time.Now()` function, it would make sense to have a cleaner way.

**Comment by joeblubaugh** [comment]
You could limit the scope very easily - instantiate a clock.Clock just before constructing the silences object, for example.

I think it would be good to be ambitious though. Anywhere that time factors into testing would benefit from a change like this.

**Comment by simonpasquier** [comment]
To be clear, I think it's an acceptable change :)

**Comment by joeblubaugh** [comment]
@simonpasquier Is there any process required to start work on this? I can periodically send PRs over time, referencing this issue.

**Comment by joeblubaugh** [comment]
@simonpasquier see the PR here: https://github.com/prometheus/alertmanager/issues/2850
