### ISSUE TITLE
Bug: PostableSilenceToProto Segfaults on Silences that pass validation.

### ISSUE THREAD

**Issue by joeblubaugh** [prometheus/alertmanager#2851]
**What did you do?** 
1. Created a PostableSilence, ps, with the Silence.Name field unset
2. Called ps.Validate(strfmt.NewRegistry()), which passed.
3. Called PostableSilenceToProto

**What did you expect to see?**
Either an error or a silencepd.Silence

**What did you see instead? Under which circumstances?**
A segfault when the Name field is accessed.

Proposed fix: Add Name validation on the api/v2 Silence type here: https://github.com/prometheus/alertmanager/blob/ec2f5f589402d8b45e327555d1330ce780354221/api/v2/models/silence.go#L58

**Comment by simonpasquier** [comment]
I guess you're talking about the Name field in the Matcher struct?
`api/v2/models/silence.go` is generated from the OpenAPI spec. IIUC whoever creates silences via the `models` package is responsible for ensuring that the object is valid.

**Comment by joeblubaugh** [comment]
Shouldn't the supplied validator ensure that the model is valid?

**Comment by joeblubaugh** [comment]
I'll follow up with go-swagger on this.
