### ISSUE TITLE
OpsGenie notifier fails if teams and tags is not provided

### ISSUE THREAD

**Issue by zwopiR** [prometheus/alertmanager#287]
the OpsGenie notifier fails with 
```
WARN[0034] Notify attempt 4 failed: templating error: template: : "" is an incomplete or empty template; defined templates are: "slack.default.titlelink", "hipchat.tmpl", "__subject", "slack.default.pretext", "slack.default.title", "pagerduty.default.description", "__description", "", "slack.default.username", "opsgenie.default.source", "__text_alert_list", "email.default.html", "opsgenie.description", "opsgenie.default.description", "pushover.default.title", "slack.default.fallback", "hipchat.default.message", "__alertmanagerURL", "pagerduty.default.client", "pagerduty.default.instances", "pushover.default.url", "slack.default.iconemoji", "slack.default.text", "pagerduty.default.clientURL", "opsgenie.tmpl", "hipchat.default.from", "hipchat.from", "__alertmanager", "hipchat.message", "pushover.default.message", "email.default.subject"  source=notify.go:193
^CINFO[0034] Received SIGTERM, exiting gracefully...       source=main.go:206
```
if the config item `teams` and/or `tags` is not provided.
In notify/impl.go (https://github.com/prometheus/alertmanager/blob/master/notify/impl.go#L670) `ExecuteTextString` is called on the values Teams/Tags which are initialized to nil, if the config params are not specified resulting the above template error.

I would provide a PR, but don't know what solution to pick:

- make team and tags mandatory: I thinks this is not suitable for all OpsGenie users, since teams and tags can be configured too within OpsGenie (in the API integration)
- provide default values: not suitable too, since alertmanager can't know the team names
- don't send the teams and tags key/value pairs in the call to OpsGenie API if they are not provided: probably the best idea, but I don't know how

Any ideas?

**Comment by brian-brazil** [comment]
@sebzz

**Comment by zwopiR** [comment]
ah - it duplicates https://github.com/prometheus/alertmanager/pull/281
