### ISSUE TITLE
Enable Discussions for the alertmanager repo

### ISSUE THREAD

**Issue by gotjosh** [prometheus/alertmanager#2882]
We [have(1)](https://github.com/prometheus/alertmanager/issues/2868) [a(2)](https://github.com/prometheus/alertmanager/issues/2854) [number(3)](https://github.com/prometheus/alertmanager/issues/2857) of issues that look more like feature requests than actual issues.

In an attempt to reduce noise and prioritise work better could we follow the same Prometheus model for discussions so that we can start encouraging folks to upvote the features they'd like to see the most in the Alertmanager?

See https://github.com/prometheus/prometheus/discussions for the current Prometheus model. The only change I'd suggest is that instead of "ideas" we have a more explicit approach and use "feature requests".

**Comment by gotjosh** [comment]
As an alternative, if the general consensus is that scanning the GH discussions might be more a best-effort thing we could simply define a feature request template like

![image](https://user-images.githubusercontent.com/231583/162488211-95b8897b-1432-42c4-bd43-8cd549717291.png)

**Comment by RichiH** [comment]
I opened the Discussions thing for this repo.

**Comment by RichiH** [comment]
Should I move this issue to discussions? It seems more like a feature request than an actual issue :p

**Comment by gotjosh** [comment]
Thanks @RichiH !
