### ISSUE TITLE
Can't send alerting email

### ISSUE THREAD

**Issue by R3habDroid** [prometheus/alertmanager#2889]
In alertmanager.yml,I tried
 `smtp_require_tls: false` in global and `insecure_skip_verify: true` in receivers,

both of them failed with:
```
level=error ts=2022-04-12T07:11:19.061Z 
caller=dispatch.go:354 
component=dispatcher 
msg="Notify for alerts failed" 
default/email[0]: notify retry canceled after 8 attempts: establish TLS connection to server: x509: certificate signed by unknown authority"
```

**Comment by woniuzhang** [comment]
Please check the port of smtp,it shouled be 25.

**Comment by SuperQ** [comment]
For questions/help/support please use our [community](https://prometheus.io/community/) channels. There are more people available to potentially respond to your request and the whole community can benefit from the answers provided.
