### ISSUE TITLE
repeat_interval max value

### ISSUE THREAD

**Issue by hansungg** [prometheus/alertmanager#2890]
Prometheus is running in a Kubernetes environment and started with a Helm chart.
Prometheus version v2.26.0
Alertmanager version v.0.21.0

------------------------
I want to know the max time of the below values.

`repeat_interval`

I want to maximize the amount of time the same alarm repeats.

It's not even in the Alertmanager documentation.
I desperately need your help.

**Comment by rgroothuijsen** [comment]
There is no maximum value in the code. There is only a warning that the repeat interval should not be set higher than the data retention period, which is 120 hours by default, but that is also configurable.

**Comment by gotjosh** [comment]
@rgroothuijsen is correct here. You need to make sure your `repeat_interval` is less than your `data.retention` - you'll get a warning from the alertmanager when this happens as well.

https://github.com/prometheus/alertmanager/blob/a6d10bd5bc3f651e0ca04d47b981ed66e85a09a6/cmd/alertmanager/main.go#L487-L495

The reasoning here is that once your alert is old enough that it matches the retention period we'll remove it from the alertmanager internals and thus any new occurrences of the alert are considered a new alert and would fire.

**Comment by gotjosh** [comment]
If you have any other questions of this nature, please refer to the [mailing list](https://groups.google.com/g/prometheus-users). 

@roidelapluie You can close this issue.

**Comment by hansungg** [comment]
hello.
Thank you for your kind reply.

We will close the issue.
