### ISSUE TITLE
Feature: Support multipart mail

### ISSUE THREAD

**Issue by RichiH** [prometheus/alertmanager#290]
@fabxc as per IRC

**Comment by RichiH** [comment]
When this is touched, supporting custom headers would also make sense.

**Comment by brian-brazil** [comment]
Custom headers are already supported.

**Comment by RichiH** [comment]
For documentation if anyone finds this issue: https://prometheus.io/docs/alerting/configuration/#email_config

**Comment by doctorlector** [comment]
That documentation for creating e-mail custom templates isn't very helpful at all.

**Comment by brian-brazil** [comment]
Text parts are support these days.
