### ISSUE TITLE
Doesn't handle -web.external-url correctly

### ISSUE THREAD

**Issue by karora** [prometheus/alertmanager#292]
Looks like a simple error in extURL in main.go:

```
diff --git a/main.go b/main.go
index b9035c3..b99b037 100644
--- a/main.go
+++ b/main.go
@@ -233,7 +233,7 @@ func extURL(s string) (*url.URL, error) {
                if err != nil {
                        return nil, err
                }
-               _, port, err := net.SplitHostPort(*listenAddress)
+               _, port, err := net.SplitHostPort(*externalURL)
                if err != nil {
                        return nil, err
                }

```

**Comment by brian-brazil** [comment]
That logic looks correct to me, as it's the fallback if an external url isn't provided. Are you sure you're running the very latest alertmanager? This logic was fixed only a few days ago.

**Comment by karora** [comment]
Yes, in order to fix the issue (which I am experiencing) I pulled the latest code from this repository about two hours ago, made the one-line change, and after that the option worked correctly (and consistently with the same option for prometheus).

The use of *listenAddress just seems wrong - the default value for that is ":9093", and there is no way to add additional path onto it.

The description for externalURL, on the other hand, is "The URL under which Alertmanager is externally reachable (for example, if Alertmanager is served via a reverse proxy). Used for generating relative and absolute links back to Alertmanager itself. If the URL has a path portion, it will be used to prefix all HTTP endpoints served by Alertmanager. If omitted, relevant URL components will be derived automatically." - the Path part of which is exactly what is needed in this routine.

**Comment by karora** [comment]
Actually thinking further, it's possible I was not using the latest code, because the image I actually saw the issue on, was a docker image from yesterday, rather than something built without applying this change.  I shall check further...

**Comment by karora** [comment]
Yep, rebuilding without my change also works, so looks like I have an old docker image.  Thanks :-)
