### ISSUE TITLE
Alertmanager timezone setting

### ISSUE THREAD

**Issue by Jessimon** [prometheus/alertmanager#2931]
Hello Alertmanagers,

I have the following setup:
Grafana 8.5.2 running on the local system.
Alertmanager 0.23 running in docker.

Both the local system and the docker OS timezone are set to Europe/Brussels.
Grafana logs show the correct local time.
Alertmanager logs shows the UTC time.

The issue is that the Alerts are generated by Grafana unified alerting and are then send to Alertmanager to handle the notification.
Currently when an alert is send from Grafana unified alerting we get a resolved message after `group_interval` from the Alertmanager even if that alert is not resolved.

Is there a way to change the Alertmanager timezone?
I did look in the documentation without success.

Thanks for the help.

**Comment by b8kings0ga** [comment]
why close this
