### ISSUE TITLE
Cant set data.maintenance-interval param

### ISSUE THREAD

**Issue by deepminimal** [prometheus/alertmanager#2939]
**What did you do?**
I want to set param data.maintenance-interval

**What did you expect to see?**
accepted param

**What did you see instead? Under which circumstances?**
```
./alertmanager --data.maintenance-interval=10m
alertmanager: error: unknown long flag '--data.maintenance-interval', try --help
```
**Environment**
prod
* System information:
Linux 3.10.0-1127.8.2.el7.x86_64 x86_64
* Alertmanager version:
```
alertmanager, version 0.24.0 (branch: HEAD, revision: f484b17fa3c583ed1b2c8bbcec20ba1db2aa5f11)
  build user:       root@265f14f5c6fc
  build date:       20220325-09:31:33
  go version:       go1.17.8
  platform:         linux/amd64
```

**Comment by roidelapluie** [comment]
I can't reproduce this.

**Comment by gotjosh** [comment]
I could @roidelapluie.

0.24 (as described in https://github.com/prometheus/alertmanager/commits/release-0.24) doesn't include https://github.com/prometheus/alertmanager/commit/dd63d04a579fe8540a0c1eda4a75bbb134f50672.

@deepminimal that change is only in master but I presume you're using the binary.

**Comment by roidelapluie** [comment]
Oooh indeed, I did not realize it was new.

**Comment by gotjosh** [comment]
Running the version command against the latest binary on arm64 gives me:

```
🙇 (prod-us-east-0) ~> ./alertmanager --version                      
alertmanager, version 0.24.0 (branch: HEAD, revision: f484b17fa3c583ed1b2c8bbcec20ba1db2aa5f11)
  build user:       root@8fd670bfea94
  build date:       20220325-09:26:50
  go version:       go1.17.8
  platform:         darwin/arm64
```

Which makes yours.

**Comment by deepminimal** [comment]
@gotjosh you are right, i can go to the main branch. 
I understand everything, thanks!
