### ISSUE TITLE
resolved_timeout I need to increase from default '5m' to '4h'

### ISSUE THREAD

**Issue by billyurs** [prometheus/alertmanager#2945]
I have my configuration something like this
global:
  resolve_timeout: 4h
  http_config:
    follow_redirects: true
route:
  receiver: slack
  continue: false
  routes:
  - receiver: scalar-value-alert-receiver
    match_re:
      tenant: .*
    continue: true
    repeat_interval: 1h
  repeat_interval: 1h
receivers:
- name: scalar-value-alert-receiver
  webhook_configs:
  - send_resolved: false
    http_config:
      follow_redirects: true
    url: <host>/api/wireless/alert
    max_alerts: 0
templates:
- /etc/config/templates.d/*.tmpl

I have been watching in alert manager, I can tell it is getting auto resolved in '5m', even though there is no change in value at prometheues end,

Please help me on it

**Comment by alexweav** [comment]
Hi, I think you'll need to handle this from the Prometheus side. Basically, `resolve_timeout` only affects alerts which do not have an `endsAt` set. If whatever generated the alerts is populating `endsAt`, it has no effect.

Check the note here:
https://prometheus.io/docs/alerting/latest/configuration/#configuration-file

> ResolveTimeout is the default value used by alertmanager if the alert does not include EndsAt

More specifically -

> # This has no impact on alerts from Prometheus, as they always include EndsAt.

FYI @gotjosh

**Comment by simonpasquier** [comment]
@alexweav is 100% correct. `resolve_timeout` isn't applicable when the alerts come from Prometheus.
