### ISSUE TITLE
How to send unique incident_key to PagerDuty for each alert rule

### ISSUE THREAD

**Issue by nickvth** [prometheus/alertmanager#298]
Missing some documentation

How to send unique incident_key to PagerDuty for each alert?

**Comment by brian-brazil** [comment]
This is done automatically for you, there's no configuration required.

We use a unique hash per alert group.

**Comment by nickvth** [comment]
Is every alert rule in prometheus automatically a group in alert manager? 

ALERT service_down
  IF consul_health_service_status == 0
  FOR 6m
  LABELS {severity="critical"}
  ANNOTATIONS {description="{{$labels.node}} of job {{$labels.job}} has been down for more than 6 minutes.", summary="Service {{$labels.node}} down"}

I have multiple services in consul, when there are multiple services down in consul, alert manager is sending the same incident key to PagerDuty. Is there a solution for this scenario?

**Comment by matthiasr** [comment]
The `group_by` [Alertmanager configuration](https://prometheus.io/docs/alerting/configuration/) allows you to group by labels other than the alertname.

**Comment by nickvth** [comment]
group_by label fixed it for me, thanks!!

**Comment by jmg011** [comment]
@brian-brazil Hi Brian, is there a way to exclude incident_key from the payload completely? I have one integration where I want to send repeat alerts even when the payload is exactly same, but the integration deduplicates events by default if the incident_key is same. If there is a way to exclude incident_key for certain alerts, this will solve a problem for us without requesting any changes to the integration.
