### ISSUE TITLE
Support for config api

### ISSUE THREAD

**Issue by mvaught02** [prometheus/alertmanager#3018]
Alertmanager is driven primarily by a set of config(s) that's currently read from a yaml. The request here is to enable support to manage and update all aspects of the configuration via a config api.

This should also support updating changes to the config when running in a cluster. This is where this request potentially has the most value since today there is no good way to update the config unless you go to each cluster member and add/update your config files

**Comment by mvaught02** [comment]
This could be somewhat related to #2756

**Comment by simonpasquier** [comment]
duplicate
