### ISSUE TITLE
Config reload causes notifications of new alerts within a group (doesn't respect group_interval)

### ISSUE THREAD

**Issue by andrejbranch** [prometheus/alertmanager#3037]
**What did you do?**
- Setup alertmanager and add group by alertname and long group_interval 
- Send an alert and get notified
- Send another alert with the same alertname but different other labels 
- No alert is sent due to group_interval not being hit
- Send a post reload request to alertmanager
- Another notification is sent

**What did you expect to see?**
Group interval should be respected even when config is reloaded

**What did you see instead? Under which circumstances?**
Group interval is not respected when reloading config

* Alertmanager version:
v0.24.0

This seems to be caused because reload restarts the alerting group and restarts the group interval here https://github.com/prometheus/alertmanager/blob/main/dispatch/dispatch.go#L434

And if there are any changes in the group subset this returns true https://github.com/prometheus/alertmanager/blob/main/notify/notify.go#L570 causing a notification

**Comment by zecke** [comment]
Sounds like a dup of #2492

**Comment by andrejbranch** [comment]
yes it does thanks
