### ISSUE TITLE
Simpler example

### ISSUE THREAD

**Issue by kaihendry** [prometheus/alertmanager#305]
Thought the https://github.com/prometheus/alertmanager/blob/master/doc/examples/simple.yml example was a little complex. What is the bare minimum to send to `admin@example.com`?

Also I am looking confused to where the alert.rules live now. e.g. https://github.com/kaihendry/pingprom/blob/master/prometheus/alert.rules is the old syntax?

https://prometheus.io/docs/alerting/rules/ could really do with an example.

**Comment by juliusv** [comment]
Yes, that's the old syntax. Hmm, there *are* two examples on the page you mentioned? (https://prometheus.io/docs/alerting/rules/)

Maybe you mean an AM config example on https://prometheus.io/docs/alerting/configuration/, in which case I totally agree.

And yes, it'd be great to provider an even more minimal example config. The `simple.yml` has a bunch of bells and whistles already.

**Comment by kaihendry** [comment]
Just checked in a hopefully simpler version here... https://github.com/kaihendry/pingprom/blob/master/alertmanager.yml

Still need to test & grok some things but my setup at work works well.

**Comment by mxinden** [comment]
I will close here in favour of #484. @kaihendry please feel free to reopen. PRs improving documentation and example configuration are always very welcome!

**Comment by kaihendry** [comment]
I do find https://github.com/prometheus/alertmanager/blob/master/examples/ha/alertmanager.yaml a bit hard to read. It could be better commented and I don't quite understand https://github.com/prometheus/alertmanager/blob/250bd35c9722ae3986a1a98ba92486b24260b830/examples/ha/alertmanager.yaml#L19

**Comment by mxinden** [comment]
> Inhibition rules allow to mute a set of alerts given that another alert is firing. We use this to mute any warning-level notifications if the same alert is  already critical.

Example scenario: Two alerts come in. One has label `severity: 'critical'` and one has label `severity: 'warning'`, but other than that, they are equal in the labels `alertname`, `dev` and `instance` (`equal: ['alertname', 'dev', 'instance']`). In this case the second alert (`severity: 'warning'`) is inhibited (ignored).

@kaihendry Let me know if this answers your question. If it doesn't please ask further! In addition, could you create a PR to extend the documentation on the `alertmanager/examples/ha/alertmanager.yaml` file?
