### ISSUE TITLE
Feature Request: Truncate messages with fewer characters.

### ISSUE THREAD

**Issue by joeblubaugh** [prometheus/alertmanager#3050]
Alertmanager truncates messages using three full stops (U+002E): `...`. We could instead truncate with a single ellipsis (U+2026) `…`, freeing up two additional characters for the message contents.

https://github.com/prometheus/alertmanager/blob/c732372d7d3be49198398d34753080459f01749e/notify/util.go#L93

**Comment by joeblubaugh** [comment]
(I'm happy to submit the PR)

**Comment by yanksyoon** [comment]
Hi @joeblubaugh, I'm trying to familiarize with the codebase, would you mind if I work on it if this request gets approved? :)

**Comment by joeblubaugh** [comment]
Sounds great!

**Comment by simonpasquier** [comment]
sounds good to me

**Comment by simonpasquier** [comment]
Closed by #3072
