### ISSUE TITLE
`Config` struct marshalling inconsistent

### ISSUE THREAD

**Issue by fornellas** [prometheus/alertmanager#3058]
**What did you do?**

I'm using the [`Config` struct](https://pkg.go.dev/github.com/prometheus/alertmanager/config#Config) to generate a templated configuration and then marshall it with [`yaml.Marshal`](https://pkg.go.dev/gopkg.in/yaml.v3#Marshal).

**What did you expect to see?**

For the marshalled file to be fully working.

**What did you see instead? Under which circumstances?**

Any `Config` nested [`Secret`](https://pkg.go.dev/github.com/prometheus/alertmanager/config#Secret) or [`SecretURL`](https://pkg.go.dev/github.com/prometheus/alertmanager/config#SecretURL) are marshalled unconditionally to [`<secret>`](https://github.com/prometheus/alertmanager/blob/v0.24.0/config/config.go#L37), essentially making the generated configuration broken. In order to use this configuration, I'd need to first marshall it from `Config`, then patch all secrets... which is far from ideal.

I traced this functionality to [this PR](https://github.com/prometheus/alertmanager/pull/174) from late 2015, but unfortunately, the PR contains no context on **why** the changes were made (@fabxc , do you remember?). My educated guess here, is that the `Config` struct was being marshalled and then printed somewhere unsafe (eg: log lines), and instead of fixing the offending code that was leaking secrets, the marshalling interface of `Config` was made... "safe", but functionally broken.

The root of the problem seems to be that, the marshal interface [`Mmarshaler`](https://pkg.go.dev/gopkg.in/yaml.v3#Mmarshaler) / [`Unmarshaler`](https://pkg.go.dev/gopkg.in/yaml.v3#Unmarshaler), when inconsistently implemented, yields unexpected results, essentially breaking expected functionality: the case here.

My suggestion here would be to:

- Restore marshalling to actually work (expected behavior).
- Implement some interface to **opt-in** a sanitized marshall, eg:
  - `Config.SanitizedMarshallYaml`, which, if a secret, then outputs `<secret>`.
  - A module level flag `SanitizeMarshall`, which when set to `true`, makes marshall output `<secret>` to secrets.
- Fix whatever code that was spitting secrets where they should not to use this new sanitized marshall interface.

I'm willing to cut a PR to fix this, as it would be a much saner solution, than what I have now in code, which is to... "patch all secrets after `Config` has been marshalled". It is just a matter of deciding the best way forward.

**Environment**

* Alertmanager version:

	v0.23.1 (though I believe any version since [this PR](https://github.com/prometheus/alertmanager/pull/174) merged in 2015 is affected).

**Comment by roidelapluie** [comment]
We do not support marshalling configurations.

The reason is that Prometheus never renders secrets back, via API or web interface. By marshalling them to `<secret>` we make sure there are no leaks possible.

https://prometheus.io/docs/operating/security/

**Comment by fornellas** [comment]
@roidelapluie I acknowledge the use cases for Prometheus, where you'd want to be able to marshall the configuration, but hide secrets. However, we have **another** use case here: programmatically generate AlertManager configuration. We can certainly do so without relying on AlertManager public `Config` struct definitions, but using AlertManager struct, gives us a lot of validation on what we are doing, which would be a big benefit.

@roidelapluie would you be open to the idea of a module level flag such as `UnsafeMarshall`, that defaults to `false`, and for use cases where we need to serialize the `Config` with passwords, we set this value to `true`? Implementing this should be a simple PR I can cut. Doing so should NOT break any existing Prometheus rationale about "hiding secrets by default", while enabling other use cases that rely on serialization.

**Comment by roidelapluie** [comment]
I am not open to this. We usually recommend using your own struct for this, and keep our codebase away from these risks.

**Comment by roidelapluie** [comment]
But you could send an email to prometheus-developers mailing list to gather more feedback around your idea, I am not alone to decide here.

**Comment by fornellas** [comment]
> We usually recommend using your own struct for this

this would mean essentially copy / pasting 99% of config.go... and changing the secret... this does not seem reasonable to me.

**Comment by roidelapluie** [comment]
Why don't you just use go.work to replace with a fork of common?

**Comment by fornellas** [comment]
@roidelapluie forking is always an option, though IMHO it would be much nicer if we could patch a couple of lines upstream, and support `Config` serialization from upstream directly.

**Comment by hsyed-dojo** [comment]
@roidelapluie could you help us understand the reasoning behind the current stance. 

> The reason is that Prometheus never renders secrets back, via API or web interface. By marshalling them to <secret> we make sure there are no leaks possible.

Putting field masking in serialization logic and making it configurable is quite a standard pattern in system design. 

What are the consequences of making it configurable with masking opted in by default ? 

(last question before mailing list)

**Comment by roidelapluie** [comment]
> What are the consequences of making it configurable with masking opted in by default ?
> 
> (last question before mailing list)

This is a burden (code we don't use) we have to carry and maintain upstream and a risk that it subtly changes, exposing secrets by accident, or that this specific code path can be enabled in some way in one of our products, maliciously or accidentaly.
