### ISSUE TITLE
Make start of week configurable

### ISSUE THREAD

**Issue by leahoswald** [prometheus/alertmanager#3073]
**What did you do?**
Configure a silence and use the calendar to select a time range.

**What did you expect to see?**
As I'm from Europe I would've expected the week to start on Monday. And if Sunday is the default I would've expected a config option to change that.

**What did you see instead? Under which circumstances?**

The weeks started on Sunday.

* Alertmanager version: 0.23.0

**Comment by w0rm** [comment]
Closed via https://github.com/prometheus/alertmanager/pull/3093

**Comment by leahoswald** [comment]
tanks ;)
