### ISSUE TITLE
Test alert receivers in Alert Manager

### ISSUE THREAD

**Issue by SandhyaSaravana** [prometheus/alertmanager#3086]
I would like to implement some automated testing to validate my alert receivers are working or not. Sometimes the password for email receiver will change, so the alerts will not come. 

I want to validate whether my alert reciver is working or not in a programmatic way. 
I found we can use the API to create an alert. But it just creating an alert and returns the status as `success` even the SMTP password is wrong. 

Any better way to test it?

**Comment by gotjosh** [comment]
I believe this is a duplicate of #2845, let's keep the conversation focus there as I believe that should solve your use-case.
