### ISSUE TITLE
using an unknown template makes AM flood your $alerttarget

### ISSUE THREAD

**Issue by cherti** [prometheus/alertmanager#311]
##### Problem:
When specifying an unknown template at least to the "html"-field of a receiver makes AM flood the receiver's inbox with mails where the according field (in case of " html:" the mail body) is empty.

##### Steps to reproduce:
use e.g. `html: '{{ email.shinanigans.html }}'` in a receiver-block and provoke an alert for that receiver.

@fabxc

**Comment by cherti** [comment]
## Problem diagnosis
When sending out alerts, Prometheus tries sending the alert and if that fails with an error, it tries again with exponential backoff. Unfortunately, an error that can cause this is, besides others, the use of a nonexistent template, which (at least for mail) results in AM flooding the receivers inbox by repeatedly trying (and succeeding) sending mails. This has primarily been tested for mail, but might occur as well for other notification types.

## Basic idea for fixing
There are two options to fix this: 
1) fall back onto the default template when a template is not found
2) Check upon loading of the config that all templates in use are actually found

`2` was attempted in https://github.com/prometheus/alertmanager/pull/347 and considered to not be feasable, therefore `1` would be the preferrable way.

**Comment by fabxc** [comment]
Thanks for the analysis and sorry for this issue going a bit stale.

 We should definitely fall back to the default and look again into whether we can do some load-time checks at least.

 @brancz is also working on a way to differentiate between retry and non-retry errors to make such flooding problems disappear in general.

**Comment by cherti** [comment]
Staleness happens. I basically just copied over the analysis from the PR to close that one and focus that information at one point for tidying up.

Differentiating between retry- and non-retry-errors sounds very attractive indeed.

There is one place in the code (that I currently don't find on-spot because the line-reference is a little useless half a year later due to advancing development of the codebase^^) where the expenontial backoff is triggered and the "template not found"-error is handled the same way like "network not there" causing the flooding.

The problem should not be limited to Mail, but to everything templated in general.

**Comment by fabxc** [comment]
Yes, we currently treat all errors the same. This also causes problems with spamming integrations when we received a 4xx response. We'll change it so each integration indicates upwards whether the error can be resolved via retry.

**Comment by brancz** [comment]
The PR for this should be out soon-ish. It won't retry anymore if there are templating issues, so it should fix the described problem.
