### ISSUE TITLE
Alertmanager sending old alerts based on old rule

### ISSUE THREAD

**Issue by rahulghanate** [prometheus/alertmanager#312]
Hi,

I have a setup where Prometheus server sends alerts to alertmanager.
And alertmanager sends those alerts to a webhook written by me.
The webhook here cuts tickets in OTRS based on alert content and also sends HTML email with Amazon SES.

The problem I am facing is,
I have alert_x_1 defined in prometheus, which started generating alerts and emailed to me along with a ticket in my queue at OTRS. The alert defined in prometheus alert_x_1 has email address and queue configured in ANNOTATIONS, which were read by my webhook for sending emails and cutting tickets.
Now I have modified alert_x_1 with different email address and queue name. But I am still getting the alerts with the old email address and queue.

Initially, I have set the "resolve_timeout" to 7 days, as I did not wanted to auto close the OTRS after 5 minutes and they should be resolved only when the data is improved in Prometheus.
Now I do not have any way to clean those old alerts with old email+queue details and generate only new ones.
Again I have set "resolve_timeout" to 5 minutes, so it can at least clear those old alerts, but they are not getting cleared even after some time.

I want this to be considered as a Bug as it alertmanager keeps using old definition of alert_x_1, which it shouldn't
And a feature request will be to delete alert DB/States at alertmanager.

Thanks

Sorry for earlier incomplete add of the issue.

**Comment by fabxc** [comment]
We need some more explanation on this. Can you include the alerts, configs,
and describe the chain of events?

**Comment by rahulghanate** [comment]
To explicitly send the RESOLVED notification, I have cleaned Prometheus data associated with the alerts rules. 
So now I have received RESOLVED emails after some time but have received to both old email address and new email addresses.

But I do not want remove data from Prometheus for marking it resolved. We need some way to clean alerts states in alertmanager or do a fresh-start in case alert rules(expression, annotations) are changed but names are used as earlier.

**Comment by fabxc** [comment]
Ah, at the time of my comment your first message just had the title and "Hi".

Your resolve timeout should probably stay at around 5 minutes. It's a timeout, not an alert duration configuration. 7 days goes way against AM's functionality. Prometheus will resend alerts as long as they are active. So alerts will not just disappear until they are no longer firing if you leave it at 5 minutes.

Annotations should be overwritten if they change for the same alert.
Did the labels of the alerts were exactly the same or just the alertname?

**Comment by rahulghanate** [comment]
Thanks for the Reply. I missed your reply in gmail filters.

Yes the problem was because of the long timeout, I realized that the prometheus will keep evaluating the alerts(upgraded prometheus to newer one and set evaluation_peiod to custom value).

Even the group interval and repeat interval were set to 12 hours and I guess alertmanager was sending old alerts even after changing the definition for old alerts which were grouped before the change.

Corrected the configurations later and it seem to be working as expected.

But Is there any other way to delete alerts from alertmanager and start afresh(even the one which are waiting in group_interval/repeat_interval).

**Comment by fabxc** [comment]
There's currently no way to do that. You can silence them for until they
disappear by themselves though.

**Comment by rahulghanate** [comment]
Okay. Thanks for quick reply.
Might be needed.

So closing this ticket now.
