### ISSUE TITLE
go package Vulnerability observed in promethus/grafana for alertmanager

### ISSUE THREAD

**Issue by golakotigopala** [prometheus/alertmanager#3130]
While scanning by using twist locks , we have observed few go package vulnerabilities for the alert manger

prometheus/alertmanager version : v0.24.0

Description: In net/http in Go before 1.18.6 and 1.19.x before 1.19.1, attackers can cause a denial of service because an HTTP/2 connection can hang during closing if shutdown were preempted by a fatal error.

Alert manger is using 1.17 version to compile the binary and this have the following CVE
https://github.com/advisories/GHSA-69cg-p879-7622

Do you have any plan to release alertmanager version with the latest go package version of 1.19.1? If so, What is the the ETA for the new release?

**Comment by golakotigopala** [comment]
Can you please provide the update on the above issue?

**Comment by simonpasquier** [comment]
closed by #3187
