### ISSUE TITLE
Change log level to `warn` when truncating messages on notification integrations

### ISSUE THREAD

**Issue by gotjosh** [prometheus/alertmanager#3134]
We currently use debug and then show the original message, but this seems like something worn noting even when debug logging is not turned on.

**Comment by roidelapluie** [comment]
Maybe we could warn about truncation, but the full message should never show in warn

**Comment by simonpasquier** [comment]
I agree that having the non-truncated message in the logs would be too noisy. It might be worth having a counter reporting how many times notifications were truncated (otherwise nobody will notice)?
