### ISSUE TITLE
How to disable repeats?

### ISSUE THREAD

**Issue by hryamzik** [prometheus/alertmanager#317]
Omitting ```repeat_interval``` gives me 4 hours. Setting to ```0s``` doesn't make any sense, scales to 10m. That's confusing....

**Comment by brian-brazil** [comment]
It is not possible to disable them. If an alert continues to fire then you should continue to be notified until it's resolved.

**Comment by hryamzik** [comment]
Well, I disagree but it's still possible to set repeat to 10 years so I'm fine about this, thanks.

**Comment by Zauxst** [comment]
_I am probably digging up graves right now, sorry for this. 
I can open a new issue if that is needed._ 

I am interested how to disable repeats, the specific use-case I have is the following:

I have added an "info" severity, which is as the severity is, an information. 
It is not necessary a type of severity issue that you need to take action, but one that you should start preparing.

My specific expression alert is this:
```
ceil(
  (
    node_filesystem_size_bytes{fstype!~"fuse.lxcfs|nsfs|vfat|squashfs|rootfs|tmpfs"} - 
    node_filesystem_free_bytes{fstype!~"fuse.lxcfs|nsfs|vfat|squashfs|rootfs|tmpfs",mountpoint!~"/boot.*"}
  ) / 
    node_filesystem_size_bytes{fstype!~"fuse.lxcfs|nsfs|vfat|squashfs|rootfs|tmpfs"}  * 100
) > 70
```
It notifies when the disk is above 70%
When we aggregating multiple servers to use Prometheus, there are groups have 10TB of disk space per machine, so you can quickly see where this starts to fail fast and the information notifications should be just that... 

My whole problem would be solved if I'd just be able to send them 1 email and nothing more.
I can, of course, disable completely this type of email for groups which are under those conditions, but I would still want for them to receive these info emails once, and never bother them ever again.

**Comment by roidelapluie** [comment]
You are looking at changing your alert to

Min_ov

> _I am probably digging up graves right now, sorry for this. I can open a new issue if that is needed._
> 
> I am interested how to disable repeats, the specific use-case I have is the following:
> 
> I have added an "info" severity, which is as the severity is, an information.
> It is not necessary a type of severity issue that you need to take action, but one that you should start preparing.
> 
> My specific expression alert is this:
> 
> ```
> ceil(
>   (
>     node_filesystem_size_bytes{fstype!~"fuse.lxcfs|nsfs|vfat|squashfs|rootfs|tmpfs"} - 
>     node_filesystem_free_bytes{fstype!~"fuse.lxcfs|nsfs|vfat|squashfs|rootfs|tmpfs",mountpoint!~"/boot.*"}
>   ) / 
>     node_filesystem_size_bytes{fstype!~"fuse.lxcfs|nsfs|vfat|squashfs|rootfs|tmpfs"}  * 100
> ) > 70
> ```
> 
> It notifies when the disk is above 70%
> When we aggregating multiple servers to use Prometheus, there are groups have 10TB of disk space per machine, so you can quickly see where this starts to fail fast and the information notifications should be just that...
> 
> My whole problem would be solved if I'd just be able to send them 1 email and nothing more.
> I can, of course, disable completely this type of email for groups which are under those conditions, but I would still want for them to receive these info emails once, and never bother them ever again.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by Zauxst** [comment]
Hi @roidelapluie,
Thanks for your reply, sadly I am as I am not certain what you mean with `min_ov`. 
I was not really looking, directly, for optimization on the alert rules (but any suggestions are highly welcomed).

From my preliminary searches, most suggestions to set the value to 52weeks in hours. Which is a counter to how most people would expect `repeat_interval 0` to behave. 

My question is mostly under the form of providing a clear example when repeating an alert is not necessary.

**Comment by roidelapluie** [comment]
Hello,
Try
```
disk_space > 70 and min_over_time(disk_space[15m]) < 70 
```
