### ISSUE TITLE
WebUI showing all alerts three times

### ISSUE THREAD

**Issue by Ramshield** [prometheus/alertmanager#3172]
**What did you do?**

**What did you expect to see?**

Every alert only once.

**What did you see instead? Under which circumstances?**

All alerts are shown three times in the webUI.
I do NOT get triple alerts, it's juist a webUI thing.

![Alertmanagerbug](https://user-images.githubusercontent.com/3533440/207250260-f7274dcb-4650-45d8-9e6f-9ba377304e48.PNG)

**Environment**

* System information:

Docker container tag v0.24.0.

* Alertmanager version:

0.24.0.

* Prometheus version:

2.39.1.

* Alertmanager configuration file:
```
insert configuration here
```

* Prometheus configuration file:

-

* Logs:

-

**Comment by simonpasquier** [comment]
I suspect that the alerts are delivered to 3 different receivers.

**Comment by Ramshield** [comment]
> I suspect that the alerts are delivered to 3 different receivers.

That is correct. I thought the receivers were not tied to the WebUI. Any suggestion on how to fix this? Except the obvious "set only one receiver"? :)

**Comment by Ramshield** [comment]
I found this old post, using that as a reference (removing the `continue: true` in my config fixed it: https://github.com/prometheus/alertmanager/issues/2196#issuecomment-591354144

I think the documentation needs to be updated accordingly, would be helpful :).
