### ISSUE TITLE
Cache-control headers aren't set for v2 api

### ISSUE THREAD

**Issue by jsimpso** [prometheus/alertmanager#3175]
**What did you do?**
`curl -s -v localhost:9093/api/v2/silences 1>/dev/null`

**What did you expect to see?**
The same headers as /api/v1:
```
jsimpso@kif:~$ curl -s -v localhost:9093/api/v1/silences 1>/dev/null
*   Trying 127.0.0.1:9093...
* Connected to localhost (127.0.0.1) port 9093 (#0)
> GET /api/v1/silences HTTP/1.1
> Host: localhost:9093
> User-Agent: curl/7.85.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Access-Control-Allow-Headers: Accept, Authorization, Content-Type, Origin
< Access-Control-Allow-Methods: GET, POST, DELETE, OPTIONS
< Access-Control-Allow-Origin: *
< Access-Control-Expose-Headers: Date
< Cache-Control: no-cache, no-store, must-revalidate
< Content-Type: application/json
< Date: Thu, 15 Dec 2022 03:04:06 GMT
< Content-Length: 30
< 
{ [30 bytes data]
```

**What did you see instead? Under which circumstances?**
```
jsimpso@kif:~$ curl -s -v localhost:9093/api/v2/silences 1>/dev/null
*   Trying 127.0.0.1:9093...
* Connected to localhost (127.0.0.1) port 9093 (#0)
> GET /api/v2/silences HTTP/1.1
> Host: localhost:9093
> User-Agent: curl/7.85.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Content-Type: application/json
< Vary: Origin
< Date: Thu, 15 Dec 2022 03:04:11 GMT
< Content-Length: 3
< 
{ [3 bytes data]
* Connection #0 to host localhost left intact
```

**Environment**

* System information:

	`Linux 5.19.0-76051900-generic x86_64`

* Alertmanager version:

	`alertmanager, version 0.24.0 (branch: main, revision: f484b17fa3c583ed1b2c8bbcec20ba1db2aa5f11)`

**Comment by ksankeerth** [comment]
@simonpasquier,
Can I fix this in v2?

**Comment by hloeung** [comment]
The CORS headers appears to be missing too.

**Comment by hloeung** [comment]
Ah, maybe https://github.com/prometheus/alertmanager/issues/3165 ?

**Comment by alexweav** [comment]
Hi, I opened a PR for this: https://github.com/prometheus/alertmanager/pull/3195

My PR only adds the `Cache-Control` header, and does not touch the CORS headers, per:
https://github.com/prometheus/alertmanager/issues/3165#issuecomment-1366401641
