### ISSUE TITLE
level=error msg="unable to initialize gossip mesh" err="create memberlist: Could not set up network transport: failed to obtain an address: Failed to start TCP listener on \"0.0.0.0\" port 9094

### ISSUE THREAD

**Issue by amitvermaa3101** [prometheus/alertmanager#3184]
Not receiving alerts in alertmanager from prometheus and found the below error while running ./alertmanager

[root@hostname alertmanager]# ./alertmanager
ts=2022-12-20T15:42:04.570Z caller=main.go:231 level=info msg="Starting Alertmanager" version="(version=0.24.0, branch=HEAD, revision=f484b17fa3c583ed1b2c8bbcec20ba1db2aa5f11)"
ts=2022-12-20T15:42:04.570Z caller=main.go:232 level=info build_context="(go=go1.17.8, user=root@265f14f5c6fc, date=20220325-09:31:33)"
ts=2022-12-20T15:42:04.577Z caller=cluster.go:185 level=info component=cluster msg="setting advertise address explicitly" addr=10.230.60.11 port=9094
ts=2022-12-20T15:42:04.579Z caller=main.go:263 level=error msg="unable to initialize gossip mesh" err="create memberlist: Could not set up network transport: failed to obtain an address: Failed to start TCP listener on \"0.0.0.0\" port 9094: listen tcp 0.0.0.0:9094: bind: address already in use"

**Comment by ilka-schulz** [comment]
I have the same problem with my GitLab install on Debian 11. It appeared just a few hours before you filed your issue here.

see my [issue on `gitlab-org/gitlab`](https://gitlab.com/gitlab-org/gitlab/-/issues/386393)

**Comment by simonpasquier** [comment]
a process already listens on port 9094, you can specify another listen address with the `--cluster.listen-address=` flag.
