### ISSUE TITLE
feature/import and export function of silence configuration

### ISSUE THREAD

**Issue by Ithrael** [prometheus/alertmanager#3199]
**What did you do?**

Increase the import and export function of silence configuration

**What did you expect to see?**

Increase the import and export function of silence configuration

**What did you see instead? Under which circumstances?**

Increase the import and export function of silence configuration

**Environment**

* System information:

	insert output of `uname -srm` here

* Alertmanager version:

	insert output of `alertmanager --version` here (repeat for each alertmanager
	version in your cluster, if relevant to the issue)

* Prometheus version:

	insert output of `prometheus --version` here (repeat for each prometheus
	version in your cluster, if relevant to the issue)

* Alertmanager configuration file:
```
insert configuration here
```

* Prometheus configuration file:
```
insert configuration here (if relevant to the issue)
```

* Logs:
```
insert Prometheus and Alertmanager logs relevant to the issue here
```

**Comment by simonpasquier** [comment]
:wave: can you provide more details? I don't understand what you're asking for.

**Comment by Ithrael** [comment]
> 


I want to add the function of importing and exporting silences configuration to alertmanager

**Comment by Ithrael** [comment]
> 👋 can you provide more details? I don't understand what you're asking for.

I want to add the function of importing and exporting silences configuration to alertmanager

**Comment by simonpasquier** [comment]
Check the `amtool silence import` command. Exporting silences is as simple as copying the `silences` file under the storage path (`data/` by default)

**Comment by Ithrael** [comment]
OK, thx， I will close this issue
