### ISSUE TITLE
Provide an alternative function to initialize `template.Template{}`

### ISSUE THREAD

**Issue by Dentrax** [prometheus/alertmanager#3217]
Currently there is only one way to create a `template.Template{}`, which is [`FromGlob()`](https://github.com/prometheus/alertmanager/blob/ecb66f76b0058957e5045114ae01f8b98994451e/template/template.go#L51) function. I have a use case which I use the alertmanager as-a-library and need to pass some dynamic/static templates from a variable (instead of file). So that it'd be great to have a second alternative function that takes an `io.Reader` interface.

```go
func FromReaders(readers []io.Reader, options ...Option) (*Template, error)
```

Since it only accepts and reads files in local directory, I'm struggling to find a way out to correctly initializing a new `Template{}`.

Feel free to assign me, if it makes sense to you.

**Comment by gotjosh** [comment]
Yes @simonpasquier, I love the idea you've proposed! Let's do it.

**Comment by Dentrax** [comment]
Good idea! Wouldn't be the following function nicer:

```
func Parse(r io.Reader, options ...Option) (*Template, error)
```
Is `New()` really necessary?

**Comment by gotjosh** [comment]
I think so if we want to have a similar interface to what we have today.

**Comment by Dentrax** [comment]
Just created the PR #3225, it seems tests are passing. Tried to decompose the `FromGlobs` by respecting the as-is behavior. Now it's easy to consume as-a-lib!
