### ISSUE TITLE
Change PVC access mode for Prometheus/Alertmanager

### ISSUE THREAD

**Issue by oalimerko** [prometheus/alertmanager#3222]
**What did you do?**
i am running an AKS cluster and i have deployed Prometheus and Alertmanager via deployment resources in k8s and they also are controlled by replicaset.The issue is that sometimes the restart of Alertmanger get stuck.It is related to accessMode of PVC.During restart,k8s will start the new pod in a different node from the currently node where the running pod is assigned,depending on resource utilization on the node.In simple words it means,same PVC is accessed from 2 different pods assigned to different nodes.This is not allowed because in the config of PVC i am using accessMode ReadWriteOnce.Looking this [comment](https://github.com/prometheus-operator/prometheus-operator/issues/978#issuecomment-364863367) in github for prometheus operator seems to be by design that option accessMode ReadWriteMany is not allowed.

So my questions, why such design and what could happen if i change accessMode to  ReadWriteMany?Any practical experience?

**What did you expect to see?**
Rolling restart for alertmanager or prometheus to work

**What did you see instead? Under which circumstances?**
The restart of Alertmanger get stuck

**Environment**

* Alertmanager version:

0.24.0

* Prometheus version:

2.36.2

* Logs:
![grafik](https://user-images.githubusercontent.com/93270758/213424830-089dcb20-f8ac-4ada-b780-e3d7e4e4068a.png)

**Comment by simonpasquier** [comment]
You probably wanted to file the issue at https://github.com/prometheus-operator/prometheus-operator :)

> same PVC is accessed from 2 different pods assigned to different nodes.

this sounds like a recipe for disaster? you don't want 2 identical pods to write concurrently to the same filesystem.

**Comment by Gasoid** [comment]
according to docs https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes

> ReadWriteOnce
>   the volume can be mounted as read-write by a single node. ReadWriteOnce access mode still can allow multiple pods to access the volume when the pods are running on the same node.

This behaviour depends on storage driver also. Azure doesn't allow to use multiple pods simutaneously.

https://learn.microsoft.com/en-us/azure/aks/concepts-storage#azure-disks

> Because Azure Disks are mounted as ReadWriteOnce, they're only available to a single node. For storage volumes that can be accessed by pods on multiple nodes simultaneously, use Azure Files.

Your solution is Azure Files

**Comment by simonpasquier** [comment]
Closing since this isn't an Alertmanager issue per se.
