### ISSUE TITLE
Inconsistent notification metrics for not used receivers

### ISSUE THREAD

**Issue by monoxono** [prometheus/alertmanager#3237]
**What did you do?**
- run alertmanager with the [official example config](https://github.com/prometheus/alertmanager/blob/main/doc/examples/simple.yml)
- run amtool to add one alert
- check notifications related metrics, those start with "alertmanager_notification_"

**What did you expect to see?**
For **not used** receivers, either metrics exist for all of them or none of them.
(I'm inclined to no metrics for not used receivers.)

**What did you see instead? Under which circumstances?**
For most receivers, when they're not used, notifications related metrics still exist.
For example, _opsgenie_ is not used in that config, but the time series `alertmanager_notification_latency_seconds_sum{integration="opsgenie"}` exists and the value is always 0.

This is not true for two new recently added receivers, _webex_ and _discord_.

related code where webex and discord are missing: https://github.com/prometheus/alertmanager/blob/01f3a474c9d16af960cfbb65b5e95bdc71ed2815/notify/notify.go#L283-L300

I don't think this issue has real user impact because it happens on not used receivers.

**Environment**

* Alertmanager version: 0.25.0

* Alertmanager configuration file: https://github.com/prometheus/alertmanager/blob/main/doc/examples/simple.yml

**Comment by simonpasquier** [comment]
I'd be inclined that the integration label should be initialized for all supported integrations (https://prometheus.io/docs/practices/instrumentation/#avoid-missing-metrics) hence adding `webex` and `discord` to the list.

**Comment by ritaCanavarro** [comment]
Hi @simonpasquier, I would like to work on this issue. Could you please assign it to me?

**Comment by ritaCanavarro** [comment]
Opened a PR: https://github.com/prometheus/alertmanager/pull/3480

**Comment by ritaCanavarro** [comment]
Hi @simonpasquier, I think we can close this issue, wdyt? :)
