### ISSUE TITLE
Alert manager Cluster Status Disabled Helm chart

### ISSUE THREAD

**Issue by amirad1** [prometheus/alertmanager#3240]
I have installed kube-stack prometheus via helm chart 
Prometheus Does send alerts to alertmanager but cluster is disabled and i do not get email alerts

----
This is my alertmanager configure
`
global:
  resolve_timeout: 5m
  http_config:
    follow_redirects: true
  smtp_from: mail@mail.com
  smtp_hello: localhost
  smtp_smarthost: 1.1.1.1:25
  smtp_auth_password: <secret>
  smtp_auth_identity: mail@mail.com
  smtp_require_tls: false

route:
  receiver: default-receiver
  group_by:
  - cluster
  - alertname
  continue: false
  routes:
  - receiver: devops
    group_by:
    - product
    - environment
    matchers:
    - service="DevOps"
    continue: false
    repeat_interval: 1h
  group_wait: 1h
  group_interval: 1h
  repeat_interval: 1h
receivers:
- name: devops
  email_configs:
  - send_resolved: true
    to: client@mail.com
    from: mail@mail.com
    hello: localhost
    smarthost: 1.1.1.1:25
    auth_password: <secret>
    auth_identity: mail@mail.com
    headers:
      From: mail@mail.com
      Subject: '{{ template "email.default.subject" . }}'
      To: client@mail.com
    html: '{{ template "email.default.html" . }}'
    require_tls: false
- name: default-receiver
  email_configs:
  - send_resolved: true
    to: eydi.a@tiddev.com
    from: mail@mail.com
    hello: localhost
    smarthost: 1.1.1.1:25
    auth_password: <secret>
    auth_identity: mail@mail.com
    headers:
      From: mail@mail.com
      Subject: '{{ template "email.default.subject" . }}'
      To: client@mail.com
    require_tls: false
templates: []
`
-------

This is my prometheus configuration 
`global:
  scrape_interval: 30s
  scrape_timeout: 10s
  evaluation_interval: 30s
  external_labels:
    prometheus: prometheus/prometheus-kube-prometheus-prometheus
    prometheus_replica: prometheus-prometheus-kube-prometheus-prometheus-0
alerting:
  alert_relabel_configs:
  - separator: ;
    regex: prometheus_replica
    replacement: $1
    action: labeldrop
  alertmanagers:
  - follow_redirects: true
    enable_http2: true
    scheme: http
    path_prefix: /
    timeout: 10s
    api_version: v2
    relabel_configs:
    - source_labels: [__meta_kubernetes_service_name]
      separator: ;
      regex: prometheus-kube-prometheus-alertmanager
      replacement: $1
      action: keep
    - source_labels: [__meta_kubernetes_endpoint_port_name]
      separator: ;
      regex: http-web
      replacement: $1
      action: keep
    kubernetes_sd_configs:
    - role: endpoints
      kubeconfig_file: ""
      follow_redirects: true
      enable_http2: true
      namespaces:
        own_namespace: false
        names:
        - prometheus
rule_files:
- /etc/prometheus/rules/prometheus-prometheus-kube-prometheus-prometheus-rulefiles-0/*.yaml
scrape_configs:
- job_name: serviceMonitor/prometheus/prometheus-kube-prometheus-alertmanager/0
  honor_timestamps: true
  scrape_interval: 30s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  enable_http2: true
  relabel_configs:
  - source_labels: [job]
    separator: ;
    regex: (.*)
    target_label: __tmp_prometheus_job_name
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_service_label_app, __meta_kubernetes_service_labelpresent_app]
    separator: ;
    regex: (kube-prometheus-stack-alertmanager);true
    replacement: $1`
...and something more 

I will appreciate any help

**Comment by simonpasquier** [comment]
This is a question/request for https://github.com/prometheus-community/helm-charts.
