### ISSUE TITLE
The alertmanager testing!

### ISSUE THREAD

**Issue by guxia** [prometheus/alertmanager#332]
https://github.com/prometheus/alertmanager
Anybody explain  nginx configuration as follow for me?

```
server {
  	server_name <your_current_alertmanager>;  -->What should i write?
  	location / {
    		proxy_pass  http://localhost:9093;
    		post_action @forward;
  	}
  	location @forward {
    	proxy_pass http://<your_new_alertmanager>:9093;-->What should i write?
  	}
   }
```

**Comment by fabxc** [comment]
What do you want to do?

**Comment by guxia** [comment]
I want to test send email by the alertmanager. 

alertmanager configuration:
global:
smtp_smarthost: 'smtp.126.com:25'
smtp_from: 'guxia286675100@126.com'
smtp_auth_username: 'guxia286675100@126.com'
smtp_auth_password: 'xxxxxxx'
hipchat_auth_token: '1234556789' -->What this is mean?And is it vital?
hipchat_url: 'https://hipchat.foobar.org/' -->What this is mean?And is it vital?
templates:

    '~/myGopath/src/github.com/prometheus/alertmanager/template/*.tmpl' route: group_by: ['alertname', 'cluster', 'service'] group_wait: 30s group_interval: 5m repeat_interval: 3h receiver: team-X-mails routes:
        match_re: service: ^(foo1|foo2|baz)$ receiver: team-X-mails routes:
            match: severity: critical receiver: team-X-pager
        match: service: files receiver: team-Y-mails routes:
            match: severity: critical receiver: team-Y-pager service: database receiver: team-DB-pager group_by: [alertname, cluster, database] routes:
            match: owner: team-X receiver: team-X-pager
            match: owner: team-Y receiver: team-Y-pager inhibit_rules:
    source_match: severity: 'critical' target_match: severity: 'warning' equal: ['alertname', 'cluster', 'service'] receivers:
    name: 'team-X-mails' email_configs:
        to: '286675100@qq.com'
    name: 'team-X-pager' email_configs:
        to: '286675100@qq.com' pagerduty_configs:
        service_key:
    name: 'team-Y-mails' email_configs:
        to: '286675100@qq.com'
    name: 'team-Y-pager' pagerduty_configs:
        service_key:
    name: 'team-DB-pager' pagerduty_configs:
        service_key:
    name: 'team-X-hipchat' hipchat_configs:
        auth_token: room_id: 85 message_format: html notify: true

Prometheus.rules:
ALERT Test
  IF sum(counter_noLabels_metric) > 0
  FOR 1h
  ANNOTATIONS {description="{{ $labels.instance }} has a median request latency above 1s (current value: {{ $value }}s)", summary="High request latency on {{ $labels.instance }}"}

**Comment by juliusv** [comment]
Have a look at http://www.robustperception.io/adding-basic-auth-to-prometheus-with-nginx/ for an example of putting Prometheus behind nginx (you can do it similarly for Alertmanager and perhaps omit the basic auth).

Also have a look at http://www.robustperception.io/sending-email-with-the-alertmanager-via-gmail/ for a simple example of sending email with the Alertmanager.

Giving much more detailed nginx configuration advice is a bit out of scope for us here though.

**Comment by juliusv** [comment]
See my general answer here: https://github.com/prometheus/alertmanager/issues/332#issuecomment-215364153

Hope that helps.

**Comment by mpchadwick** [comment]
It is worth noting that you don't *need* nginx if you're just testing (unless you're specifically trying to test out nginx, then of course you need it).

**Comment by juliusv** [comment]
I assume that the articles linked above give enough of an explanation of how to get started, so I'm closing this issue for now.

Please reopen / open another one if you have more questions, or ideally, ask general questions on the mailing list or IRC (see https://prometheus.io/community/).
