### ISSUE TITLE
Validate config

### ISSUE THREAD

**Issue by rvalkenaers** [prometheus/alertmanager#333]
Is there a way to check if the config is valid? (similar to promtool with Prometheus)

Thanks.

**Comment by juliusv** [comment]
Not yet unfortunately (short of actually trying to start Alertmanager with it).

**Comment by rvalkenaers** [comment]
We use jenkins to build and deploy new containers in which we have a test step.

However when I just run it, it obviously keeps hanging forever.

Any other tips on how I could mimic a test?


Thanks!

**Comment by juliusv** [comment]
Currently only by writing code that uses Alertmanager's config packages itself, but that's not recommended as it's not meant to be used externally.

In the future, it would be great to have a tool (similar to promtool or integrated with it) that allows this.

**Comment by rvalkenaers** [comment]
Okay. Looking forward to it.

Thanks!

**Comment by Kellel** [comment]
This should probably be written into amtool

**Comment by jeeyoungk** [comment]
any update on this?

**Comment by iksaif** [comment]
I'm working on this on https://github.com/iksaif/alertmanager/tree/check-config

**Comment by noqcks** [comment]
For people who come from google: https://github.com/prometheus/alertmanager#amtool
