### ISSUE TITLE
group_by question

### ISSUE THREAD

**Issue by hryamzik** [prometheus/alertmanager#336]
group_by takes an array of labels, but does this mean all of them should be presented in each alert or just any of them?

```yml
# The labels by which incoming alerts are grouped together. For example,
  # multiple alerts coming in for cluster=A and alertname=LatencyHigh would
  # be batched into a single group.
  group_by: ['alertname', 'cluster']
```

I get multiple similar alerts separately from several hosts and a bit confused with this.

**Comment by brian-brazil** [comment]
They don't have to be present, a missing label is the same as that label with the empty string as a value.

**Comment by hryamzik** [comment]
I have ```['alertname', 'instance']``` so labels are not missing. But I'd like alerts to be grouped if ```alertname``` or ```'instance``` matches, how to set this up?

**Comment by brian-brazil** [comment]
What do you mean by "matches"?

**Comment by hryamzik** [comment]
I'd like to get these two grouped:
- ```alertname=some_rule1, instance=srv1```
- ```alertname=some_rule1, instance=srv2```

And these two as well:
- ```alertname=some_rule1, instance=srv1```
- ```alertname=some_rule2, instance=srv1```

**Comment by brian-brazil** [comment]
That's not possible. Consider, how would you handle it if all 3 of those alerts came in at once?

**Comment by hryamzik** [comment]
1 alert with details inside. I'd really like to avoid alert storms on multiple issues. But I got the point, thank you.

**Comment by brian-brazil** [comment]
In that case you want `[]`, though there's probably some other label you want in there like cluster.

**Comment by bshojaei82** [comment]
Have the same exact question , is there a possible way to group alarms based on one label and if the count of grouped alarms is not > 1 then try to group them using another label

**Comment by stuartnelson3** [comment]
This is a usage question and should be directed to the users mailing list, prometheus-users@googlegroups.com, where it will reach a wider audience and benefit more people.

**Comment by perlun** [comment]
> This is a usage question and should be directed to the users mailing list, [prometheus-users@googlegroups.com](mailto:prometheus-users@googlegroups.com), where it will reach a wider audience and benefit more people.

For reference: https://groups.google.com/forum/#!forum/prometheus-users has the archives for this list.
