### ISSUE TITLE
Bad matcher format

### ISSUE THREAD

**Issue by chanyshev** [prometheus/alertmanager#3400]
* System information:

Linux 5.4.0-100-generic x86_64

* Alertmanager version:

prom/alertmanager:v0.25.0

* Prometheus version:

**prom/prometheus:v2.44.0-rc.0**

* Alertmanager configuration file:
```
-   receiver: 'infrastructure-telegram'
    matchers: [ "service != processing,speech" ]
    continue: true
```

* Logs:
```
alertmanager           | ts=2023-06-20T06:54:45.418Z caller=coordinator.go:118 level=error component=configuration msg="Loading configuration file failed" file=/etc/alertmanager/config.yml err="bad matcher format: speech"
```

I wrote as shown in the [documentation](https://prometheus.io/docs/alerting/latest/configuration/#telegram_config) but I get error

**Comment by grobinson-grafana** [comment]
Hi! :wave:

I'm not sure which example you looked at in the documentation, but that looks incorrect to me. You have written one complete matcher: 

```
service != processing
```

And then a second, incomplete matcher:

```
speech
```

If you want the value to be `processing,speech` then you need to quote the value containing the comma:

```
service != "processing, speech"
```

**Comment by chanyshev** [comment]
Hi, I took this example as a basis
![image](https://github.com/prometheus/alertmanager/assets/44210753/3bbaccd9-74a2-4f3a-82bf-1a8791cf442c)

**Comment by grobinson-grafana** [comment]
That must be an error in the documentation, because that's not how matchers are parsed in current versions of Alertmanager. The quoting is incorrect, it should be:

```
matchers: [ "foo = \"bar,baz\"", "dings != bums" ]
```
