### ISSUE TITLE
no such file or directory on prom/alertmanager:master Docker image

### ISSUE THREAD

**Issue by kaihendry** [prometheus/alertmanager#341]
I probably shouldn't be using prom/alertmanager:master but I already updated my YML to the new syntax, so I am not keen to roll back.

<img src=http://s.natalian.org/2016-05-05/1462416511_2548x1380.png>

**Comment by grobie** [comment]
The default alertmanager.yml config is expected to exists at `/etc/alertmanager/config.yml` now https://github.com/prometheus/alertmanager/blob/master/Dockerfile.
