### ISSUE TITLE
Getting permissions denied message while trying to run it in harness using pipeline workflow

### ISSUE THREAD

**Issue by vdoddaguni12345** [prometheus/alertmanager#3429]
**What did you do?**
Created an image using bamboo build and then verified that it existed in jFrog artifactory

**What did you expect to see?**
I expected to see the pods up and running in open shift

**What did you see instead? Under which circumstances?**
Got permissions denied message

**Environment**
test

* System information:

	insert output of `uname -srm` here

* Alertmanager version:

v0.25.0

* Prometheus version:

latest
* Alertmanager configuration file:
```
insert configuration here
```

* Prometheus configuration file:
```
insert configuration here (if relevant to the issue)
```

* Logs:
```
insert Prometheus and Alertmanager logs relevant to the issue here
```

**Comment by simonpasquier** [comment]
This doesn't look like an issue with Alertmanager but rather with the container platform.
