### ISSUE TITLE
Can I still store silences since 0.1.0. ?

### ISSUE THREAD

**Issue by leifhanack** [prometheus/alertmanager#343]
Using alertmanager 0.0.4. it was possible to store silences in a json file and specify that location through a command line flag. 

Since 0.1.0. the command line flag is gone. Is there nonetheless a way to persist the silences? 

I'm using a dockerized alertmanager so that a stop/start will keep silences, but a fresh 'deploy' will lose it naturally, as long as I can't write it to a data mount.

Thanks,
Leif

**Comment by juliusv** [comment]
@leifhanack See the `-storage.path` flag (or generally, `./alertmanager -h` to see all available flags). The new alertmanager now not only stores silences, but all other state (alerts, sent notifications) as well.

Closing.

**Comment by leifhanack** [comment]
Ah, perfect. Thanks!
