### ISSUE TITLE
FAILED - RETRYING: [192.168.1.171 -> localhost]: Download alertmanager binary to local folder (1 retries left).Result was: {

### ISSUE THREAD

**Issue by bdmlg** [prometheus/alertmanager#3444]
Issue with the github releases link when trying to use it on a playbook 

* Alertmanager configuration file:
```
insert configuration here
```
    alertmanager_amtool_config_alertmanager_url: "127.0.0.1:9093"
    alertmanager_web_external_url: "http://localhost:9093/"
    alertmanager_web_listen_address : "0.0.0.0:9093"
    alertmanager_version : "latest"
    alertmanager_cluster:
      --cluster.listen-address: "192.x.x.46:9094 192.x.x.50:9094"
    alertmanager_user: "alertmanager"
    alertmanager_group: "alertmanager"
    alertmanager_install_path: "/opt"
    alertmanager_bin_path: "/usr/local/bin"
    alertmanager_config_path: "/etc/alertmanager"
    alertmanager_config_file: "alertmanager.yml"
    alertmanager_listen_address: "127.0.0.1:9093"
    alertmanager_smtp:
      from: 'prometheus@example.com' # The default SMTP From header field.
      smarthost: 'example@example.com:587' # Example: smtp.example.org:587
      auth_username: 'XXXX' # SMTP Auth using CRAM-MD5, LOGIN and PLAIN. If empty, Alertmanager doesn't authenticate to the SMTP server.
      auth_password: 'XXXX' # SMTP Auth using LOGIN and PLAIN.
    alertmanager_receivers:
      - name: 'IT'
        email_configs:
          - send_resolved: true
            to: 'example@example.com
    alertmanager_route:
      #group_by: [ 'example', ]
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 3h
      receiver: 'IT'
```

* Logs:

```
FAILED - RETRYING: [192.x.x.171 -> localhost]: Download alertmanager binary to local folder (1 retries left).Result was: {
    "attempts": 5,
    "changed": false,
    "dest": "/tmp/alertmanager-latest.linux-amd64.tar.gz",
    "elapsed": 0,
    "invocation": {
        "module_args": {
            "attributes": null,
            "backup": false,
            "checksum": "",
            "client_cert": null,
            "client_key": null,
            "dest": "/tmp/alertmanager-latest.linux-amd64.tar.gz",
            "force": false,
            "force_basic_auth": false,
            "group": null,
            "headers": null,
            "http_agent": "ansible-httpget",
            "mode": 420,
            "owner": null,
            "selevel": null,
            "serole": null,
            "setype": null,
            "seuser": null,
            "sha256sum": "",
            "timeout": 10,
            "tmp_dest": null,
            "unredirected_headers": [],
            "unsafe_writes": false,
            "url": "https://github.com/prometheus/alertmanager/releases/download/vlatest/alertmanager-latest.linux-amd64.tar.gz",
            "url_password": null,
            "url_username": null,
            "use_gssapi": false,
            "use_proxy": true,
            "validate_certs": true
        }
    },
    "msg": "Request failed",
    "response": "HTTP Error 404: Not Found",
    "retries": 6,
    "status_code": 404,
    "url": "https://github.com/prometheus/alertmanager/releases/download/vlatest/alertmanager-latest.linux-amd64.tar.gz"
```

**Comment by simonpasquier** [comment]
I don't think that you can a direct link to the latest release artefact.
