### ISSUE TITLE
alerts failed: context canceled & context deadline exceeded

### ISSUE THREAD

**Issue by wkshare** [prometheus/alertmanager#346]
```
time="2016-05-10T14:06:36+08:00" level=error msg="Error on notify: context canceled" source="notify.go:152" 
time="2016-05-10T14:06:36+08:00" level=error msg="Notify for 3336 alerts failed: context canceled" source="dispatch.go:238" 
time="2016-05-10T14:09:22+08:00" level=error msg="Error on notify: context deadline exceeded" source="notify.go:152" 
time="2016-05-10T14:09:22+08:00" level=error msg="Notify for 3331 alerts failed: context deadline exceeded" source="dispatch.go:238"
```

rate(prometheus_notifications_sent_total[1m]) 
= 3 alerts / sec

What is the reason???

**Comment by brian-brazil** [comment]
Which receiver are you trying to use? It seems to be timing out on the other end.

**Comment by wkshare** [comment]
Configuration of the SMTP mail, using the mailgun.

May be the SMTP timeout?

@brian-brazil

**Comment by brian-brazil** [comment]
That sounds like a SMTP timeout. With so many alerts the notification may be big enough to be causing issues.

**Comment by wkshare** [comment]
i got. @brian-brazil 

smtp timeout

**Comment by vishnu-vardhan-reddy** [comment]
We upgraded alertmanager to v0.16 from v0.14.
Just changed HA configuration (mesh to cluster). Didn't changed slack configuration.

Alertmanager is failing notification to slack, following error we can see in logs.

Error details
level=error ts=2019-11-05T09:55:38.377773199Z caller=notify.go:332 component=dispatcher msg="Error on notify" err="Post https://hooks.slack.com/services/XXXX/XXXX/XXXX: context deadline exceeded"
level=error ts=2019-11-05T09:55:38.377861637Z caller=dispatch.go:177 component=dispatcher msg="Notify for alerts failed" num_alerts=1 err="Post https://hooks.slack.com/services/XXXX/XXXX/XXXX: context deadline exceeded"

Do we need to change any other configuration in this upgrade?
