### ISSUE TITLE
Configuration file format now is yaml not support json anymore

### ISSUE THREAD

**Issue by JakimLi** [prometheus/alertmanager#350]
alermanager.conf file used to be in json format, now the new version seems to be yaml version, so I get the error when parsing the configuration file. 

But when I try to do the downgrade, I couldn't fount any documentation indicates when this change was made, so I have to try all the version, is it possible to put the changes into the release notes? so I can know which version I can use?

Thanks very much.

**Comment by brian-brazil** [comment]
This is called out in https://github.com/prometheus/alertmanager/releases/tag/0.1.0 and http://www.robustperception.io/what-alertmanager-0-1-0-means-for-you/ has more information,
