### ISSUE TITLE
Proposal: Add counter metric to track alerts dropped for being outside of active/within muted time bounds

### ISSUE THREAD

**Issue by tjhop** [prometheus/alertmanager#3512]
When using [time intervals](https://prometheus.io/docs/alerting/latest/configuration/#time_interval) for routes, alerts received outside of the correct time window are dropped with a log message:

https://github.com/prometheus/alertmanager/blob/6ce841ca22b4724b5ac40e501d4198a40a262ecc/notify/notify.go#L841-L846
https://github.com/prometheus/alertmanager/blob/6ce841ca22b4724b5ac40e501d4198a40a262ecc/notify/notify.go#L878-L884

Imagine a scenario where:
1. there is >=1 routes with time intervals set (eg, engineering teams wanting alerts during business hours)
2. there is a NOC or similar team available to triage alerts 24/7

Since alerts received outside of valid time intervals aren't retried and are outright dropped, it could be helpful to the NOC to have a count of how many alerts have been dropped for tracking or meta-alerting purposes (for example, a high rate of dropped alerts could indicate a more severe issue and justify the NOC reaching out to subject matter experts, even if outside of business hours). 

Using the existing log lines, it is possible to, for example, create a recording rule within loki and generate a metric off of it. However, the log entries don't inform the user _how many_ alerts were dropped. 

I'm proposing a new counter metric `alertmanager_alerts_dropped_total` should be created, and when alerts are dropped, it should be incremented by how many alerts were dropped (ie, `counterVar.Add(len(alerts))`)

**Comment by gotjosh** [comment]
I'm favour of this -- but I think the name should be `alertmanager_alerts_supressed_total` as this is the terminology we use when an alert is muted.
