### ISSUE TITLE
Add /-/reload endpoint

### ISSUE THREAD

**Issue by ZhenyangZhao** [prometheus/alertmanager#353]
I found reload code in the main.go - line:149 

But i don't know how to use it make alertmanger reload config file .In prometheus i can use post : http://prometheus/-/reload to reload.

what should i do in alertmanager?

Thks

**Comment by fabxc** [comment]
You can send a `SIGHUP` to the Alertmanager process. For example `killall -HUP alertmanager`.

I renamed this issue so we add a `/-/reload` endpoint for Alertmanager as well.

**Comment by ProfessorYang** [comment]
@fabxc Thank you very much for your reply to my question. Is the `/-/reload` api endpoint will appear in the near version?

**Comment by fabxc** [comment]
Closed via #372
