### ISSUE TITLE
Ignore trailing newline in `smtp_auth_password_file`

### ISSUE THREAD

**Issue by giorgiga** [prometheus/alertmanager#3549]
For what I've seen, most systems ignore a trailing newline in password files, but alertmanger does not.

Since there is no way an smtp password ends in \n, the failure mode is a cryptic smtp auth failure, and alertmanager's behaviour is unique in this, it is a frustrating issue to debug.

I think it would be an improvement if alertmanager ignored trailing newlines when reading `smtp_auth_password_file`.

**Comment by alexander-zimmermann** [comment]
I agree. The POSIX standard requires a trailing newline character on every line of a text file. See https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html.
