### ISSUE TITLE
Alerts coming from removed targets

### ISSUE THREAD

**Issue by kavyakul** [prometheus/alertmanager#357]
Hi,
I am facing problem with old alerts.
1. I started prometheus,alertmanager, alerta & jira container for my project
2. After few days I had to add few targets & remove few targets, so I changed prometheus.yml, alertmanager.conf & alert.rules for those changes and restarted prometheus,alertmanager, alerta & jira 
3. Now, I see alerts from the targets that have been removed & these alerts keep coming up everytime alertmanager container is restarted. (I have to manually delete them)

**Comment by fabxc** [comment]
This should no longer come up simply as alerts are not persisted anymore right now. Should we change that in the future, I'll keep an eye on this problem.

**Comment by jaydipdave** [comment]
Even I am facing same problem. 

`
scrape_configs:

  - job_name: 'overwritten-default'
    scheme: https
    tls_config:
      insecure_skip_verify: true

    file_sd_configs:
      - files: ['/etc/prometheus/tgroups/*.json', '/etc/prometheus/tgroups/*.yml']
`

The target file has been removed. I restarted prometheus container multiple times. But still the "AGENT_DOWN" alert was firing.

Update: After few minutes, now it is not firing.
