### ISSUE TITLE
Add jira notifier / integration of jiralert

### ISSUE THREAD

**Issue by jkroepke** [prometheus/alertmanager#3577]
**What did you do?**

I would like to integrate a JIRA notifier into AlertManager.

**What did you expect to see?**

A native Atlassian Jira integration

**What did you see instead? Under which circumstances?**

Currenty, adapter is needed to create JIRA issues from AM. (https://github.com/prometheus-community/jiralert)

---

Before starting to develop such an integration into AM, I would like to ask if the maintainers are open for such an integration.

Currently, I able to find 5 year old comments (https://github.com/prometheus/alertmanager/pull/1012#pullrequestreview-67829943) which seems like an NO

An actual statement would helpfull to get the directory, if jiralert should be the focus or the integration into AM.

**Comment by bwplotka** [comment]
We discussed this internally and indeed it's an option, but we were looking for maintainers:  https://github.com/prometheus-community/jiralert/issues/145
