### ISSUE TITLE
List of template variables

### ISSUE THREAD

**Issue by mateeyow** [prometheus/alertmanager#361]
Is it possible to get the list of template variables. I'm a bit confused as some examples are outdated and does not work. Anyhow, I tried adding this `{{ if eq .Status "firing" }}ERROR{{ else }}FIXED{{ end }}` on Slack text but it doesn't seem to work.

**Comment by brian-brazil** [comment]
https://github.com/prometheus/alertmanager/blob/master/template/template.go#L217

**Comment by mateeyow** [comment]
Thanks

**Comment by maxnitze** [comment]
In case someone else is looking for this, here's the exact reference (right now): https://github.com/prometheus/alertmanager/blob/72b0cb0f40b37fd85c2a13b4d2a6ce9ec801a638/template/template.go#L292-L306
