### ISSUE TITLE
Alert Manager Console not working since chrome updated

### ISSUE THREAD

**Issue by wonderphil** [prometheus/alertmanager#3618]
**What did you do?**

Port forward to the alertmanager from the k8 cluster in Chrome and nothing is show and looking at console the following error is there and the count of the error is continuing to claim and is not stopping

```
script.js:1 Uncaught TypeError: Cannot read properties of undefined (reading 'elmFs')
    at script.js:1:14691
    at $r (script.js:1:15220)
    at script.js:1:19486
    at Cr (script.js:1:20349)
    at jr (script.js:1:19197)
    at script.js:1:21013
    at a (script.js:1:21229)
```
![Screenshot 2023-11-24 at 9 39 02 am](https://github.com/prometheus/alertmanager/assets/1829205/2b4277b8-c8d3-4c89-9320-bdf3f7df3c94)

**Works in ALL other Browsers**

**What did you expect to see?**

Alert manager console

**What did you see instead? Under which circumstances?**

None, apart from the error in the console:

```
script.js:1 Uncaught TypeError: Cannot read properties of undefined (reading 'elmFs')
    at script.js:1:14691
    at $r (script.js:1:15220)
    at script.js:1:19486
    at Cr (script.js:1:20349)
    at jr (script.js:1:19197)
    at script.js:1:21013
    at a (script.js:1:21229)
```

**Environment**

* System information:

     Chrome version Version 119.0.6045.159 (Official Build) (arm64)
     Mac Ventura 13.6
     K8 Version 1.26.6
     Linux 5.15.0-1042-azure x86_64

* Alertmanager version:

```  
  alertmanager, version 0.26.0 (branch: HEAD, revision: d7b4f0c7322e7151d6e3b1e31cbc15361e295d8d)
  build user:       root@df8d7debeef4
  build date:       20230824-11:11:58
  go version:       go1.20.7
  platform:         linux/amd64
  tags:             netgo

```

* Prometheus version:

	insert output of `prometheus --version` here (repeat for each prometheus
	version in your cluster, if relevant to the issue)

* Alertmanager configuration file:

Not relevant

* Prometheus configuration file:

Not relevant

* Logs:

**Comment by danielpersonius** [comment]
the only workaround i've found so far is opening in an incognito tab

**Comment by danielpersonius** [comment]
Actually, I got it to work again by disabling chrome extensions. In my case it was 

WOT: Website Security & Safety Checker

**Comment by gotjosh** [comment]
Glad you were able to figure it out.

**Comment by seaser0** [comment]
Good hint with WOT - I had the same issue on my Macbook with Chrome.
