### ISSUE TITLE
Alert manager possible dead lock 

### ISSUE THREAD

**Issue by qinxx108** [prometheus/alertmanager#3682]
### Description ###
Recently we noticed a dead lock issue happened in our running alert managers.
Reference:  
* dispather: https://github.com/prometheus/alertmanager/blob/main/dispatch/dispatch.go#L143
* mem.Alerts.Subscribe: https://github.com/prometheus/alertmanager/blob/1da134aa30c81e656c5156df1499a77d5df92269/provider/mem/mem.go#L151
* claim store.Alerts.mtx: https://github.com/prometheus/alertmanager/blob/1da134aa30c81e656c5156df1499a77d5df92269/provider/mem/mem.go#L157
https://github.com/prometheus/alertmanager/blob/1da134aa30c81e656c5156df1499a77d5df92269/store/store.go#L119
* gc: https://github.com/prometheus/alertmanager/blob/1da134aa30c81e656c5156df1499a77d5df92269/store/store.go#L72
* mem.gc.callback: https://github.com/prometheus/alertmanager/blob/1da134aa30c81e656c5156df1499a77d5df92269/provider/mem/mem.go#L112

![image](https://github.com/prometheus/alertmanager/assets/63399121/9012c552-4f58-4593-bfe4-5f08937fd4b7)

![image](https://github.com/prometheus/alertmanager/assets/63399121/9cbdfca4-bdab-4dc9-8b6c-169fd3704ebb)

### Proposal fix ###
* Have subscribe function here https://github.com/prometheus/alertmanager/blob/1da134aa30c81e656c5156df1499a77d5df92269/provider/mem/mem.go#L151 to claim store.Alerts.mux first before claim mem.Alerts.mux

**Comment by yeya24** [comment]
Is this something we can close now with #3715 getting merged?

**Comment by gotjosh** [comment]
Indeed, thanks @yeya24
