### ISSUE TITLE
Grafana 7.5.17 can not  added alertmanager table

### ISSUE THREAD

**Issue by chengzi-xs** [prometheus/alertmanager#3685]
* Alertmanager version: 0.26.0 

* Prometheus version:  2.27.0

Grafana version:  7.5.17  

Setting grafana alertmanager      dashboard   show next info 
Failed to execute 'fetch' on 'Window': Request with GET/HEAD method cannot have body. 

![image](https://github.com/prometheus/alertmanager/assets/59002007/a4338ecf-ace8-4aa7-bdd8-4bfb0e085fc8)

**Comment by gotjosh** [comment]
Please refer to Grafana for this.
