### ISSUE TITLE
Splitting grouped notifications by status

### ISSUE THREAD

**Issue by mattbostock** [prometheus/alertmanager#371]
Currently, notification grouping does not account for alert statues. If a 'firing' alert and a 'resolved' alert are triggered within the `group_wait` period and match the `group_by` labels, they will be bundled together.

When I discovered this behaviour I found it somewhat surprising. Its advantage is that it reduces the number of notifications, however the downside is that someone working to fix an issue may rely on notifications to know that a given host is fixed.

Would the Prometheus developers be receptive to a PR that adds an option to group on alert status in addition to the `group_by` fields?

**Comment by brian-brazil** [comment]
I don't think we'd accept that.

You shouldn't be relying on the alertmanager to tell you that an issue is fixed, that's for the oncall to determine themselves. An alert no longer firing its not at all sufficient to indicate that the problem is resolved, it could merely have settled down a tad or changed form.

**Comment by mattbostock** [comment]
Thanks for the quick reply.

Ideally, yes, I'd agree. I have a use case where alerts could be triggered by, for example, additional traffic caused by a malicious actor. The alert is often actionable but once resolved, it's often the case that no further action is necessary and no there's no long-term fix to be implemented.

**Comment by brian-brazil** [comment]
If you know it's resolved, why do you also need the alertmanager to also tell you this?

Note that all the resolved data path is best-effort.

**Comment by mattbostock** [comment]
In this case, we rely on notifications to know that it's resolved. The frequency at which these alerts occur is such that seeing a notification in a Slack/HipChat channel is much more convenient than referring to dashboards etc.

**Comment by brian-brazil** [comment]
> In this case, we rely on notifications to know that it's resolved. 

This is not a safe thing to do in Prometheus terms, resolved messages are not intended to be reliable.

> The frequency at which these alerts occur is such that seeing a notification in a Slack/HipChat channel is much more convenient than referring to dashboards etc.

It sounds like your alert threshold might need increasing.

**Comment by mattbostock** [comment]
Ok, thanks for clarifying. Closing this issue.
