### ISSUE TITLE
VirusTotal flagging trojan on alertmanager image.

### ISSUE THREAD

**Issue by pdellamore** [prometheus/alertmanager#3733]
Hi,

When running the VirusTotal scan against the prometheus/alertmanager:v0.24.0 image, I am receiving some AV vendors flagging a trojan. 

VT Scan: https://www.virustotal.com/gui/file/098dc527476f821fef45e771464cd8ac81c3b399d9841d0f9240eb2e58cca781

When decompressing the image and scanning its layers separately, I can see that the busybox binary is the binary being flagged by the AV vendors. 

There is any plan to fix this issue for the v0.24 image version?

**Comment by ahrycej** [comment]
Could somebody comment on this one. have same issue

**Comment by jsto** [comment]
Hi. Does anyone have thoughts on this issue? Is this a valid malware? I have the same issue!

**Comment by rajivml** [comment]
We have the same issue

**Comment by roidelapluie** [comment]
busybox is not a valid malware and is shipped with prometheus for ease of debugging but it is not used.
