### ISSUE TITLE
Wrong URL in documentation

### ISSUE THREAD

**Issue by mikich** [prometheus/alertmanager#380]
"This is an example configuration that should cover most relevant aspects of the new YAML configuration format. Authoritative source for now is the code."
The link of "code" if probably changed and URL:
---https://github.com/prometheus/alertmanager/tree/dev/config
 is no longer pointing to the file...

Please fix

Thanks!

**Comment by fabxc** [comment]
I filed  a PR to update the link: #381 
You can find the docs here: https://prometheus.io/docs/alerting/configuration/
