### ISSUE TITLE
Wrong Alertmanager version for v1 API removal in the logs?

### ISSUE THREAD

**Issue by darkk** [prometheus/alertmanager#3814]
**What did you do?**

I looked at [Releases page](https://github.com/prometheus/alertmanager/releases). I looked at the source code https://github.com/prometheus/alertmanager/blob/cb9724db47dc1c1e4b8352baf62d21e9a6919d36/api/v1_deprecation_router.go#L55-L58

**What did you expect to see?**

I expected the log notice to say `0.27.0`, as it's the first release that drops `/api/v1`.

**What did you see instead? Under which circumstances?**

I see `0.28.0` in the log message. It it a typo or my misunderstanding? :-)

**Comment by grobinson-grafana** [comment]
Looks like a mistake! Thanks 👍
