### ISSUE TITLE
Distinguish between backoff and permanent notification failure

### ISSUE THREAD

**Issue by fabxc** [prometheus/alertmanager#382]
Currently the Notifier interface can only error and we retry with exponential back off in any case.
This causes AM a misbehaving client (e.g
 400 HTTP errors).

Error inspection seems rather cumbersome.

I suggest introducing a new interface.

```
type NotificationFilter interface {
    Filter(alerts) (alerts, err)
}
```

For things like silencing, receiver routing, etc. and 

```
type Notifier interface {
    Notify(alerts) (bool, error)
}
```

For the actual notification integrations where the boolean indicates whether we should retry.

**Comment by stuartnelson3** [comment]
fixed by #459
