### ISSUE TITLE
Alertmanager web UI is broken after installing using generate-ui.sh 

### ISSUE THREAD

**Issue by manalshaikh** [prometheus/alertmanager#3824]
**What did you do?** I installed prometheus-alertmanager using apt package manager. As simple as "apt install prometheus-alertmanager"

**What did you expect to see?** I expected to see a normal alertmanager UI

**What did you see instead? Under which circumstances?** Since alertmanager wasn't showing UI by default(it didn't have it enabled), it asked me to run generate-ui.sh script which I did but it gave me back a broken UI. That is of course, after the elm version error saying "Your elm.json says this application needs a different version of Elm.
It requires 0.19.1, but you are using 0.19.0 right now." but I fixed it by setting the version to 0.19.1 in 
```
/usr/share/gocode/src/github.com/prometheus/alertmanager/ui/app/elm.json
```
as a means to bypass that error.
Here's a screenshot:
![image](https://github.com/prometheus/alertmanager/assets/20181960/220756d1-f011-4143-96b2-878260d2d42a)
and this is when pressing calendar button on silencing alert page:
![image](https://github.com/prometheus/alertmanager/assets/20181960/bd1c7bd3-b8f2-4282-9399-f7ac67d5d2e5)

**Environment** Debian Bookworm

* System information:

	Linux 6.1.0-18-amd64 x86_64

* Alertmanager version: 0.25.0

* Prometheus version:

Not an issue

* Alertmanager configuration file:
Working as expected, nothing to see.

* Prometheus configuration file:
Working as expected, not relevant.

* Logs:
Could not find anything relevant to alertmanager-ui. Its running as expected.

**Comment by dswarbrick** [comment]
This is not the right place to report a Debian-specific bug. Please use the [Debian bug tracker](https://bugs.debian.org).

**Comment by manalshaikh** [comment]
Okay. Thank you.

I'll just drop it here incase if anyone comes looking. I've fixed the above issue by editing generate-ui.sh in a way that it generates what it needs to generate, then takes script.js into account and then gets rid of everything. It then downloads the files from repo and uses script.js to do the job. A cheesy way but it can be improved further if anyone wants it:
```
#!/bin/bash

set -euo pipefail

ELMDISTURL=https://github.com/elm/compiler/releases/download/0.19.1/binary-for-linux-64-bit.gz
DATEPICKER_CSS_URL=https://raw.githubusercontent.com/elm-community/elm-datepicker/master/css/elm-datepicker.css
BOOTSTRAP_URL=https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css
SRCDIR=/usr/share/gocode/src/github.com/prometheus/alertmanager/ui/app
DSTDIR=/usr/share/prometheus/alertmanager/ui

echo "Installing dependencies..." >&2
apt update
apt install -yy curl uglifyjs git \
    golang-github-prometheus-alertmanager-dev

#/usr/share/fonts-font-awesome/
TMPDIR=$(mktemp -d)


echo "Downloading Elm tools..." >&2
curl --location $ELMDISTURL | gunzip -c - > $TMPDIR/elm
chmod +x $TMPDIR/elm

echo "Compiling source code..." >&2
ln -s $SRCDIR/src $SRCDIR/elm.json $TMPDIR
(cd $TMPDIR; ./elm make src/Main.elm --optimize --output $TMPDIR/app.js)

echo "Optimising source code..." >&2
uglifyjs $TMPDIR/app.js \
    --compress 'pure_funcs="F2,F3,F4,F5,F6,F7,F8,F9,A2,A3,A4,A5,A6,A7,A8,A9",pure_getters,keep_fargs=false,unsafe_comps,unsafe' \
    --mangle --output $TMPDIR/script.js

echo "Installing in Alertmanager directory..." >&2
mkdir -p $DSTDIR
cp $TMPDIR/script.js $DSTDIR
cp $SRCDIR/index.html $SRCDIR/favicon.ico $DSTDIR

rm -rf $TMPDIR

# Step 1: Clone the repository
echo "Cloning Alertmanager repository..."
git clone https://github.com/prometheus/alertmanager /tmp/alertmanager_repo
sleep 1

# Step 2: Backup script.js, delete other files inside /usr/share/prometheus/alertmanager/ui/
echo "Backing up script.js and deleting other files inside /usr/share/prometheus/alertmanager/ui/..."
mv /usr/share/prometheus/alertmanager/ui/script.js /tmp
rm -rf /usr/share/prometheus/alertmanager/ui/*
sleep 1

# Step 3: Move content of cloned repository to /usr/share/prometheus/alertmanager/ui/
echo "Moving contents of cloned repository to /usr/share/prometheus/alertmanager/ui/..."
mv /tmp/alertmanager_repo/ui/app/* /usr/share/prometheus/alertmanager/ui/
sleep 1

# Step 4: Move script.js back to /usr/share/prometheus/alertmanager/ui/
echo "Moving script.js back to /usr/share/prometheus/alertmanager/ui/..."
mv /tmp/script.js /usr/share/prometheus/alertmanager/ui/
sleep 1

# Step 5: Rename bootstrap-4.0.0-alpha.6-dist to bootstrap
echo "Renaming bootstrap-4.0.0-alpha.6-dist to bootstrap..."
mv /usr/share/prometheus/alertmanager/ui/lib/bootstrap-4.0.0-alpha.6-dist /usr/share/prometheus/alertmanager/ui/lib/bootstrap
sleep 1

# Step 6: Rename font-awesome-4.7.0 to font-awesome
echo "Renaming font-awesome-4.7.0 to font-awesome..."
mv /usr/share/prometheus/alertmanager/ui/lib/font-awesome-4.7.0 /usr/share/prometheus/alertmanager/ui/lib/font-awesome
sleep 1

echo "Deleting repo as its no longer needed"
rm -rf /tmp/alertmanager_repo

echo "Alertmanager restart required. Other than that, if you haven't seen any error above, the installation is completed!"

echo "Alertmanager updated successfully!"
```

**Comment by dswarbrick** [comment]
You probably also would have stumbled across https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1067469, if you had checked the Debian bug tracker.

**Comment by avarsava** [comment]
@manalshaikh Thank you for this - we had the same problem and your script worked perfectly

**Comment by manalshaikh** [comment]
> [@manalshaikh](https://github.com/manalshaikh) Thank you for this - we had the same problem and your script worked perfectly

Very glad to have been of help :)
