### ISSUE TITLE
Support for hipchat cards in notifications

### ISSUE THREAD

**Issue by crazed** [prometheus/alertmanager#383]
https://developer.atlassian.com/hipchat/guide/sending-messages

To support cards, alertmanager would have to accept a card config and pass that along to the hipchat API when sending a notification. The card is defined as a JSON object with various objects, could be easy enough to just create a basic template that creates the necessary JSON.

**Comment by brian-brazil** [comment]
Would you like to send a PR to add that?

**Comment by rossmcf** [comment]
I'm taking a look at this just now. The first obstacle I've hit is that notifiers don't appear to be very testable. With most calling `ctxhttp.Post()` directly, there's no opportunity to intercept their output and validate what they're doing.

My first thought is to inject a `Doer` with the same signature as `ctxhttp.Do()` into `Notify()`, as per Peter Bourgon's [recommendations](http://peter.bourgon.org/go-best-practices-2016/) (see _Logging and Instrumentation_). This would help for all of the current Notifiers bar `Emailer`. I can't think of a more generic way of dealing with this right now, but I'm pondering it.

@brian-brazil I'd appreciate your thoughts on this, in particular:
- Would you be happy for me to alter the signature of `Notify()`?
- Can you think of a better way to do this, that would work for `Emailer`, too?

**Comment by mxinden** [comment]
@brian-brazil in case this is still relevant, could you follow up on @rossmcf comment?

**Comment by brian-brazil** [comment]
Normally in Go you'd create a test http server and then check what was sent.

**Comment by simonpasquier** [comment]
HipChat being phased out (https://github.com/prometheus/alertmanager/issues/1930) I'm closing this issue.
