### ISSUE TITLE
Prometheus Alertmanager not sending email notifications

### ISSUE THREAD

**Issue by kuchanamounika** [prometheus/alertmanager#3850]
Hi Team,

I installed Prometheus alert manager  using Prometheus-community 22.5 version helm chart, configured it using below configurations file
alertmanager.yml:

global:
      resolve_timeout: 4h
      smtp_smarthost: [xx.xxx.net:25]
      smtp_from: 'xxxx@gmail.com'
      smtp_require_tls: false
      receivers:
      - name: default-receiver
        email_configs:
        - to: 'xxx@gmail.com'
          from: 'yyy@gmail.com'
        headers:
                Subject: "test email"
        send_resolved: true
    route:
      group_by: ['xxx]
      group_wait: 10s
      group_interval: 5m
      receiver: default-receiver
      repeat_interval: 120h
      routes:
      - receiver: "default-receiver"
        repeat_interval: 120h
        match_re:
            ttt<yy-condition>: "email"
            continue: true
When ever the alert trigger, I am able to see it in the UI of the alertmanager, but I am not getting email notification
can some one help me to resolve the issue

Thanks
Mounika

**Comment by TheMeier** [comment]
Run alertmanager with debug logs enabled and check the logfiles.

**Comment by kuchanamounika** [comment]
Got it resolved the issue

**Comment by TheMeier** [comment]
Nice, can you also close this github-issue then?
