### ISSUE TITLE
[HA AM] Add snapshotting or persistence

### ISSUE THREAD

**Issue by fabxc** [prometheus/alertmanager#387]
Either we snapshot the in-memory state frequently or we keep persisting into BoltDB.
The former is easier as we can just overwrite old state all the time and don't need a caching layer on top of BoltDB.

**Comment by beorn7** [comment]
Especially important for those users that run AM with a single instance.

**Comment by beorn7** [comment]
If `GossipData` would be easy to marshal and un-marshal, we could use the `Gossiper.Gossip` method to checkpoint all Gossipers easily.  `GossipData.Encode` can serve as marshaler, but the interface has no method to reconstruct from byte slices. Perhaps something to discuss with @peterbourgon.

**Comment by simonpasquier** [comment]
That old issue can be closed since AlertManager snapshots the gossiped data now.
