### ISSUE TITLE
Work around PrometheusOperatorSyncFailed, integration=opsgenie, max_runes=130?

### ISSUE THREAD

**Issue by sheeeng** [prometheus/alertmanager#3880]
Separate this question out from #3872.

> > I have the following warning.
> > ```text
> > alertmanager ts=2024-06-13T19:53:32.537Z caller=opsgenie.go:178 level=warn integration=opsgenie msg="Truncated message" alert="{}/{alertname=~\"^(?:.*)$\"}:{alertname=\"PrometheusOperatorSyncFailed\", namespace=\"prometheus\"}" max_runes=130
> > ```
>>
> > How to work around this warning?
> 
> That error message is unrelated to the matchers in the configuration file. Opsgenie has truncated the message in the notification because it's too long.

I understand that [OpsGenie Alert API](https://docs.opsgenie.com/docs/alert-api) only support maximum 130 characters, meaning runes, for the message of the alert.

https://github.com/prometheus/alertmanager/blob/7e2cd80c2d69bb1943374c9c3bf2cda1eced73ab/notify/opsgenie/opsgenie.go#L37

Is there a way to truncate message in alertmanager configuration file?

**Comment by grobinson-grafana** [comment]
Hi! 👋 This warning is when the message is too long and is truncated. This happens before sending the notification to Opsgenie. You can override the message using a template. The default template is `{{ template "opsgenie.default.message" . }}`.

https://prometheus.io/docs/alerting/latest/configuration/#opsgenie_config

**Comment by grobinson-grafana** [comment]
Hi! 👋 This warning occurs when the message is too long and has been truncated to be within the 130 character limit. You can override the message using a template. The default template is `{{ template "opsgenie.default.message" . }}` which you can find [here](https://github.com/prometheus/alertmanager/blob/v0.27.0/template/default.tmpl#L43).

The documentation for this is [here](https://prometheus.io/docs/alerting/latest/configuration/#opsgenie_config).
