### ISSUE TITLE
[HA AM] handle UI encode/decode time drift

### ISSUE THREAD

**Issue by fabxc** [prometheus/alertmanager#389]
When trying to edit an alert in the UI there's a slight time drift from encoding/decoding the timestamps to JSON. This causes an alert validation error.

**Comment by fabxc** [comment]
Some options:

* allow a slight time drift. Needs to be configurablel, may cause anomalies.
* switch to something more precise, i.e. millisecond integer timestamps. Makes for a weird API.
* ignore timestamps that cannot be tweaked anyway. Friction for API usability.
* don't send timestamps for things that cannot be modified. Friction for API usability.

**Comment by beorn7** [comment]
We are talking about silences, not alerts, do we?

Would it be feasible to do all silences with seconds resolution only?

Also, the expiration by setting the end time to "now" would profit from setting it to something a short time in the past (to be a bit more resilient to time skew).

**Comment by fabxc** [comment]
With LWW semantics seconds make collisions 1 billion times more likely than the previous nanosecond approach. Like it in general though. The updated timestamp is only ever set by the server so leaving that one at a higher precision would work.

Why setting the end time into the past? 
That would actually cause things to clash as we cannot modify activity into the past.

Same issue with start time. We just opt for overwriting the start timestamp to now if the silence is newly created.

**Comment by brian-brazil** [comment]
> With LWW semantics seconds make collisions 1 billion times more likely than the previous nanosecond approach.

Usually you'd use a server id as a tiebreaker here.

**Comment by fabxc** [comment]
With multiple cores this can even happen on a single server.

**Comment by beorn7** [comment]
> Why setting the end time into the past? 
> That would actually cause things to clash as we cannot modify activity into the past.

"Past" would mean "a tiny constant amount", just to make sure a clock jump wouldn't screw things up with silences springing back into existence for a fraction of a second. This shouldn't happen anyway, but I'm just thinking conservatively - I haven't fully understood the system here, just suspicious of systems that rely on monotonous time, especially if things get distributed.

**Comment by fabxc** [comment]
Still don't think I understand the tradeoff here. We are weighing silences possibly being active for a split second more against marking them as inactive for a split second where they with certainty were still active.

In doubt I always find modifying the past the worse idea.

**Comment by beorn7** [comment]
Problem is that you might _think_ you are not modifying the past, but then you are not if your clock is wrong or changes... You want your system to handle that case in a robust way. But this is now going way out of scope.

I should not have brought up the "set to now" issue here, it's clearly something different that needed to be discussed in the appropriate context. I guess the validation part triggered it in my brain.

**Comment by fabxc** [comment]
I would like to understand this. Clock skew is certainly a practical problem. And systems tend to leave it to the user to care about timestamp accuracy on each node. The impact of drift in Alertmanager is quite minor and alerting should be setup on if it gets too large.

Yet I still want to understand how porting silences back into the past 1 second or so will solve which problem and how?

**Comment by beorn7** [comment]
It might very well cause more problems than it solves. Again, it was a mistake on my side to even bring it up in the context of this issue. Your legitimate concerns about the problems it might create caused me thinking about possible other problems clock skew might create. It needs to be discussed in a larger context.

**Comment by fabxc** [comment]
Yea, we certainly need some safety barriers in some places to catch large clock drift into the future – especially so we don't falsely assume we already sent certain notifications.

**Comment by fabxc** [comment]
We went for a 1 second tolerance before and after which is enough to handle lacking sub-ms precision in JS.
