### ISSUE TITLE
Support time_interval testing with amtool config routes test

### ISSUE THREAD

**Issue by mknapphrt** [prometheus/alertmanager#3891]
Are there any plans to support testing active and mute time_intervals with amtool? We're starting to use these more now and it would be nice to test the behavior with `amtool config routes test`.

**Comment by grobinson-grafana** [comment]
Is this a duplicate of #3889?

**Comment by mknapphrt** [comment]
Huh, yeah it is. I tried searching but didn't get any matches. Will close this one
