### ISSUE TITLE
matcher is not native regexp why?

### ISSUE THREAD

**Issue by linuxfan1** [prometheus/alertmanager#3915]
**What did you do?**
I found that the matcher is not a native regexp when configuring routes using alertmanager, for example
    - receiver: DBA
      matchers:
        - cluster =~ "^(mysql|redis)"
Can only match 'mysql' or 'redis' itself, but not match start with 'mysql01','mysql02','redis01'...
Use <visual editor> as is expect

I checkd source code for matcher.go:
if t == MatchRegexp || t == MatchNotRegexp {
		re, err := regexp.Compile("^(?:" + v + ")$")
		if err != nil {
			return nil, err
		}
		m.re = re
	}
	return m, nil
why regexp.Compile("^(?:" + v + ")$") or  regexp.Compile(v)?

* Alertmanager version:
 All versions that support matchers

**Comment by simonpasquier** [comment]
Alertmanager regexp matchers are always anchored (as it is for Prometheus). To get back to your question, you could do `(mysql|redis).*` to match any label starting with mysql and redis.

**Comment by linuxfan1** [comment]
But there is a visual editor in the official documentation that is a native regexp.
https://prometheus.io/docs/alerting/latest/configuration/
That's what makes me wonder
