### ISSUE TITLE
[HA AM] UI tweak: Expire vs. Delete vs. Nothing

### ISSUE THREAD

**Issue by beorn7** [prometheus/alertmanager#398]
The Delete button should only be a delete button for silences that haven't started yet. Once a silence has started, it should turn into an Expire button. Silences that have expired should have neither a Delete nor an Expire button.

(This is not a feature specific for the HA AM, but the semantic of deleting and expiring silences only happens there.)

**Comment by fabxc** [comment]
Fixed via #408
