### ISSUE TITLE
Ability to set subject on outgoing e-mail alerts

### ISSUE THREAD

**Issue by StianOvrevage** [prometheus/alertmanager#401]
It would be really nice to set a templated subject for outgoing e-mail alerts.

Right now I get subjects like this, which are a bit heavy on (irrelevant) information:

    [FIRING:1] win_disk_latency_critical (Disk latency > 40ms 1E exc02 windows-monitoring-pack 22 .....itor.no:9107 scollector .....nitor critical read round(rate(win_disk_duration{#TAGS#}[1m]) * 1000))

**Comment by brian-brazil** [comment]
You can by setting the `subject` header, https://prometheus.io/docs/alerting/configuration/#email-receiver-email_config

**Comment by StianOvrevage** [comment]
Except that doesn't seem to work:

    time="2016-06-21T23:25:54Z" level=error msg="Loading configuration file failed: yaml: unmarshal errors:\n  line 67: cannot unmarshal !!str `{{ temp...` into map[string]string" file="/etc/alertmanager/config.yml" source="main.go:128"

**Comment by StianOvrevage** [comment]
email_configs:
    - to: 'x@gmail.com'
      html: '{{ template "email.html" . }}'
      headers: '{{ template "email.subject" . }}'

**Comment by brian-brazil** [comment]
`headers` is a map so

```
  headers:
    subject: ...
```

**Comment by StianOvrevage** [comment]
Yay! That is working! The docs could maybe be a bit clearer and show an example :)

**Comment by nvn227** [comment]
what if i want to add alertname in subject line?

Ex: 
    headers:
      Subject: 'Dev Alerts'

**Comment by stuartnelson3** [comment]
This is a usage question. Please direct usage questions to prometheus-users@googlegroups.com, where it will reach a wider audience and can benefit others.

**Comment by nvn227** [comment]
thanks. I sent a mail to the group.

**Comment by yogesh9391** [comment]
> thanks. I sent a mail to the group.

what template you have used here. I want to send severity in email subject.

**Comment by Kaali09** [comment]
@ghost @yogesh9391 Can you please share the example config to add the severity in the email subject if you guys already done?

**Comment by durcon** [comment]
I would say, that the lack of documentation and example is a bug. Particularly, if you can find a lot of questions about the e-mail configuration on the web with low quality answers. 

There is an example for Slack:

https://prometheus.io/docs/alerting/latest/notification_examples/

It would be helpful, if you also add an example for e-mail configuration/templating.
