### ISSUE TITLE
Alertmanager template for PagerDuty

### ISSUE THREAD

**Issue by Pilotindream** [prometheus/alertmanager#4021]
Hello community,

I have a necessity to configure alertmanager template to sent alerts notification to Pagerduty. Since in "alert title" field in pagerduty i see everything as defined in default template: https://github.com/prometheus/alertmanager/blob/main/template/default.tmpl
However, by only title its hard to understand to which component/environment the alert is related.

So i would like to add some additional information like ```annotations.summary``` or ```annotations.message.```
But in documentation I see that its only possible to specify description into templates:
![image](https://github.com/user-attachments/assets/f7e325b5-476b-400e-856f-d9482343bad4)

As I understand correct "description" correspond to "ALert Title" in Pagerduty, but how to customize another columns like "summary" so that it will be more informative from which source the alert came? 

Thanks in advance!

**Comment by grobinson-grafana** [comment]
Hi! 👋 Unless I've misunderstood the question, you're looking for advice on how to put the summary annotation into your Pagerduty notification. This is better asked in the mailing list [prometheus-users.](https://groups.google.com/g/prometheus-users). GitHub issues are for bug reports and feature requests.

**Comment by grobinson-grafana** [comment]
Hi! 👋 I think questions and help on templating notifications is better asked in the mailing list [prometheus-users.](https://groups.google.com/g/prometheus-users). GitHub issues are for bug reports and feature requests.
