### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by sathieu** [prometheus/alertmanager#4063]
**What did you do?**

#3732 😉 

**What did you expect to see?**

A new release including it :pray:.

**What did you see instead? Under which circumstances?**

No new release since 2024-02-28.

**Comment by grobinson-grafana** [comment]
It's happening, check https://github.com/prometheus/alertmanager/pull/4072.

**Comment by EricHorst** [comment]
Sorry to comment on a closed issue, I don't know a better place.
 @gotjosh, is 0.28 RC advancing to release soon?

**Comment by TheMeier** [comment]
@gotjosh got the pre release running on multiple setup, running for 2 weeks+ just fine
