### ISSUE TITLE
Missing license and version information for vendored JS

### ISSUE THREAD

**Issue by TheTincho** [prometheus/alertmanager#410]
Hi,

I noticed that there are vendored javascript dependencies that are not declared in NOTICE, nor there is incomplete information about the versions in use. I am trying to find the original sources (as these files are minified), but it is difficult to do so without knowing what the minified versions correspond to, and where to get them.

``` ui/lib/moment.min.js
ui/lib/js-yaml.min.js
ui/lib/angular-moment.min.js
ui/lib/angular-route.min.js
ui/lib/kube.min.css
ui/lib/jquery.min.js
ui/lib/angular-sanitize.min.js
ui/lib/angular.min.js
ui/lib/d3.v3.min.js
ui/lib/angular-resource.min.js
```

**Comment by fabxc** [comment]
My apologies. Which version are you trying to package?
I have to figure that out as I blindly took these over from the initial
prototype blindly.

**Comment by TheTincho** [comment]
I am preparing 0.2.1

**Comment by stuartnelson3** [comment]
This is no longer relevant, as we have a different frontend now.
