### ISSUE TITLE
Vendored client_golang does not match released version

### ISSUE THREAD

**Issue by TheTincho** [prometheus/alertmanager#411]
Hi, another problem I've found while packaging the alertmanager for Debian.

The client_golang vendoring is using two different commits, one for api/ and another for prometheus/, and neither of them matches the released version of the client_golang. In particular, api/ only lives in a feature branch, it is not even in master, so I don't know if I should try to package that branch or what..

Can somebody give me a hint here?

**Comment by TheTincho** [comment]
Adding @fabxc , as Beorn suggested on IRC.

**Comment by fabxc** [comment]
The Alertmanager API is practically not public/stable in any way. But the functional tests are using the API package from the branch.

It should probably just live within some package in AM for the time being.
I want to restructure the functional testing anyway at some point. May take a while – how urgent is this for you.

Can you just drop the test/ package for packaging as it doesn't do anything?
That could be an intermediate solution at least.

**Comment by TheTincho** [comment]
Thanks for the clarification!

For now I have embedded the API package in the debian sources, but it still has to pass approval from ftp-master.

If they don't complain, no hurry; if they do, I can try removing the tests, but that's not a very happy solution (we like to run tests!). In any case, we can wait. I just did not know the reason for this.

**Comment by stuartnelson3** [comment]
current master has the latest client golang https://github.com/prometheus/alertmanager/blob/f53b247/vendor/vendor.json#L272-L289
