### ISSUE TITLE
0.2.1 sources fail to build

### ISSUE THREAD

**Issue by ribx** [prometheus/alertmanager#412]
When I try to build the latest tagged version, I get this error:

```
% make build
>> building binaries
 >   .
go install github.com/prometheus/alertmanager: build output \
  "/<path>/src/github.com/prometheus/alertmanager" already \
  exists and is a directory
[1] go install github.com/prometheus/alertmanager: build output \
  "/<path>/src/github.com/prometheus/alertmanager" already \
  exists and is a directory
```

It works with trunk just fine. What about a new release?

**Comment by fabxc** [comment]
A clean checkout and `make build` works. That's also what CI does when creating the release artifacts, which visibly worked.

Any chance you accidentally created an `alertmanager/` directory in your repository checkout?

**Comment by ribx** [comment]
It does not work with 0.2.0 either, but does work with 0.1.1.

I found a difference in the build process. When I build the trunk version, it says:
```
% make build                      
>> building binaries
 >   alertmanager
```
and builds fine, while the other both say:
```
% make build                      
>> building binaries
 >   .
```
and then fail with the above error.

**Comment by ribx** [comment]
My college is sure, that the 0.2.0 has compiled already in the past. So maybe this is connected to a go update or something?

**Comment by sdurrheimer** [comment]
the `.` is not normal, are you using a symlink or anything special ?
Can you give us your `go version` along with your `$GOROOT` and `$GOPATH` envvars ?

**Comment by ribx** [comment]
btw: I checked that there is no "alertmanager" directory

```
$ go version
go version go1.6.1 linux/amd64
```

The GOROOT variable is empty, while GOPATH is set to the directory before the "src" directory. It's an absolute path.

**Comment by danielmorlock** [comment]
* GOPATH: `declare -x GOPATH="/var/tmp/portage/net-analyzer/prometheus-alertmanager-0.2.1/work/prometheus-alertmanager-0.2.1"`
 * GOROOT: 
 * Go Version: go version go1.6.1 linux/amd64
 * PWD: `/var/tmp/portage/net-analyzer/prometheus-alertmanager-0.2.1/work/prometheus-alertmanager-0.2.1/src/github.com/prometheus/alertmanager`

The `/var/tmp/portage/net-analyzer/prometheus-alertmanager-0.2.1/work/prometheus-alertmanager-0.2.1/src/github.com/prometheus/alertmanager` is the repository.

Setting the `PREFIX` in the Makefile to `/var/tmp/portage/net-analyzer/prometheus-alertmanager-0.2.1/work/prometheus-alertmanager-0.2.1/src/github.com/prometheus/alertmanager/alertmanager` solves the problem. The default value for `PREFIX` is `$(pwd)`. Any thoughts?

**Comment by fabxc** [comment]
If `make build` does not work with a freshly checked out repository, this generally means the Go environment is not set up properly.

Does the problem still exist with the latest version though?

**Comment by fabxc** [comment]
This seems be stale or resolved. Please reopen if you have any further questions.
