### ISSUE TITLE
[HA AM] Retention set by writer

### ISSUE THREAD

**Issue by fabxc** [prometheus/alertmanager#416]
Per in-person discussion, having the retention/deletion time for state items shared via gossip directly attached to the object, and defined by the creating/modifying peer, will avoid inconsistencies.

**Comment by fabxc** [comment]
Fixed in HA branch for notification information now.

**Comment by simonpasquier** [comment]
I think this one can be closed. Gossiped nflogs and silence items contain their expiration date/time.

https://github.com/prometheus/alertmanager/blob/8c9e0cf50cba43476c2ee16d52d44f37df064425/nflog/nflogpb/nflog.proto#L44-L52

https://github.com/prometheus/alertmanager/blob/8c9e0cf50cba43476c2ee16d52d44f37df064425/silence/silencepb/silence.proto#L61-L66
