### ISSUE TITLE
New naming convention for releases?

### ISSUE THREAD

**Issue by xbglowx** [prometheus/alertmanager#425]
I noticed that the latest 0.3.0 release is prefixed with `v`. Is this a new naming convention? I haven't seen this with most (maybe any) of the other Prometheus productions.

**Comment by beorn7** [comment]
They will all be switched over to the new convention with the `v` prefix eventually. Sorry for the noise but there were a number of reasons for that, as discussed on the mailing list.

**Comment by xbglowx** [comment]
OK, thanks for the update. I need to catch up on the mailing list.
