### ISSUE TITLE
Ability to notify an arbitrary HTTP endpoint

### ISSUE THREAD

**Issue by deviantony** [prometheus/alertmanager#43]
It's a question as I've not seen this in the roadmap, is it planned to add the ability to trigger a script/program when an alert is fired?

**Comment by brian-brazil** [comment]
I'd be wary of anything that involved process management in such a critical component as the alertmanager, but we could sent off a HTTP request to an arbitrary endpoint.

**Comment by deviantony** [comment]
Sure that would be nice, could be used to manage things such as up-scaling/down-scaling an app based on Prometheus metrics.

**Comment by brian-brazil** [comment]
You should do that by querying prometheus directly, no need to get the alertmanager involved.

**Comment by fabxc** [comment]
It's worth noting that you can [query alerts](http://prometheus.io/docs/querying/rules/#inspecting-alerts-during-runtime) directly from Prometheus.

**Comment by deviantony** [comment]
I could use the ability to query alerts directly from Prometheus for my needs and still use the alert manager for notifications.

Unfortunately, I've not seen any documentation about querying Prometheus, is there an API exposed?

**Comment by brian-brazil** [comment]
It's not documented (https://github.com/prometheus/prometheus/issues/623), but if you look at the http requests the expression browser sends in Console mode you should be able to figure it out.

**Comment by deviantony** [comment]
:+1: 

It's ok for me. Should I leave this issue open for any evolution?

**Comment by gesellix** [comment]
With #70 in master, I guess the original question could be answered with *yes*?

**Comment by brian-brazil** [comment]
I'm just cleaning up the JSON case at the moment, but after that you should be good to go.
