### ISSUE TITLE
Email contains wrong link when running Alertmanager as Docker container

### ISSUE THREAD

**Issue by svenmueller** [prometheus/alertmanager#430]
Hi,

I'm running Prometheus/Alertmanager as Docker containers (latest) and also have a proxy server (haproxy) in front of them to get rid of the ports. I'm passing the config `web-external-url` to properly set the external URL which should used as base for link building. Nonetheless, the links in the notifications  send by Alertmanager (e.g. email) still contain wrong links. E.g. the "Alertmanager" link shows something like "http://14c6d18965e2:9093/#/alerts?receiver=team-operations-mails" (Docker hostname + internal port).

Did i forget to configure something?

Thanks in advance,
Sven

**Comment by svenmueller** [comment]
Btw, the "source" link in the email notification is correct, but both links to the Alertmanager instance (header + footer of the email) point to the container.

**Comment by svenmueller** [comment]
It was a simple configuration issue in the `docker-compose.yml`file.

**Comment by elixir67** [comment]
May I ask where do you set the web-external-url? could you give me more guidance and show me some code snippets? Thanks!

**Comment by copernico** [comment]
I am having the same issue, can you clarify what was the solution for you?
Thanks.

**Comment by anandsh19** [comment]
I am also facingthe same issue, could someone clarify and provide me the solution?
Thanks.

**Comment by ntwobike** [comment]
If anybody came across same problem add `web.external-url` flag into **alertmanager** in docker-compose file.
`- '-web.external-url=http://hostname here:9093/'`

**Comment by poldy79** [comment]
As of now, at least the command line parameter of prometheus-alertmanager is `--web.external` (double dash, instead of single dash). So a full example might be `--web.external-url=http://example.com:9093/`. Using debian, i had success adding this to `ARGS` in  `/etc/default/prometheus-alertmanager`. This might apply, when extending docker-compose-files.
