### ISSUE TITLE
Rendering silences takes a long time

### ISSUE THREAD

**Issue by stuartnelson3** [prometheus/alertmanager#431]
Rendering the silences list from the API, in an appreciably large list of silences, takes ages. Rendering ~500 silences locks the UI for a good 10 seconds while they are rendered. Additionally, because the UI is locked, it incorrectly shows "No silences" for an extended period of time.

I suggest either:
- enabling pagination on the silences API endpoint (https://github.com/prometheus/alertmanager/blob/master/api.go#L365-L375) and adding logic to the angular code to request additional silences based on scroll position
- Hackery with angular that stores the entire response in memory, and only renders out the silences based on scroll position

My preference is the first option.

@fabxc @beorn7

**Comment by beorn7** [comment]
Related: #293 . Also, we will eventually need pagination and server-side searches for the alert listing, too.

**Comment by fabxc** [comment]
Discussed this with @stuartnelson3 in person again.
We all agree on pagniation and advanced selections (e.g. along labels) for silences and alerts in the API. The real challenge lies in the server-side implementation. Internal interfaces need a fundamental change, combining pagination with searches will add tricky challenges as well.

**Comment by stuartnelson3** [comment]
In my experience, html rendering time >> golang querying and filtering time. From what I've seen with our current alertmanager at SoundCloud: 

- The entire request time for querying all silences (~750ish) is around 250ms
- [Looping through all silences](https://github.com/prometheus/alertmanager/blob/master/ui/app/js/app.js#L286-L290) on the front end takes another negligible slice of time (<100ms)
- Rendering the silences to HTML takes ~10s

Even doubling the server time (which I doubt would happen) would result in a massive usability improvement.

I think as a first iteration, it would be acceptable if the backend filtered everything by labels and then returned `n` silences/alerts at offset `m` (with some arbitrary page size `q`).

I don't think it would be possible for anyone to have a large installation where server processing time is even close to equal to client rendering time, so I'm guessing this would be a win for everyone.

I'm not sure how big the changes are that you're imagining for the internal interfaces, but I could push up something simple with pagination + offsets (no filtering) to see if it's something you would like me to pursue.

**Comment by fabxc** [comment]
But what if the silences change (which gets more likely the more you have) between loads of the next page? People would potentially not see certain silences or see some twice.

**Comment by stuartnelson3** [comment]
That is an excellent question.

Could we make use of the `ID`, and include that in the requests for further pagination? `lastID=33`, so the next list of paginated items starts at whichever ID is the next one?

**Comment by fabxc** [comment]
Yes, ordering seems to solve the issue initially – I'd expect people to
expect time-ordered silences though.
But you are right we don't need a perfect O() implementation internally to
get huge benefits. Give it a shot if you want. Don't worry about breaking
the API. It's undocumented and experimental.

**Comment by grobie** [comment]
Fixed with v0.4.0
