### ISSUE TITLE
Empty slack channel

### ISSUE THREAD

**Issue by jsuchenia** [prometheus/alertmanager#432]
To send messages to internal Slack group you have to omit a channel parameter in a Slack WebHook
So could you made a slack channel parameter obsolete or can we send it with an empty string?

**Comment by jsuchenia** [comment]
According to Slack WebHook specification channel override is just a method to override, but by default messages should not contains a channel and will be delivered to a default channel where integration was configured.
Ref: https://api.slack.com/incoming-webhooks

@fabxc It should be fine just to remove check in config/notifiers.go#L230 and channel will be obsolete. Am I right (from a go point of view, I'm not a go expert)?

**Comment by fabxc** [comment]
Yes, that should work.
