### ISSUE TITLE
why can't i Receive the alert email?

### ISSUE THREAD

**Issue by Chentongxuedefanhua** [prometheus/alertmanager#435]
The Alertmanager config:
global:
  resolve_timeout: 3m
  smtp_smarthost: smtp.exmail.qq.com:465
  smtp_from: test@alert.com
  smtp_auth_username: test@alert.com
  smtp_auth_password: xxxxxx
 
route:
   group_by: [alertname]
   repeat_interval: 5m
   receiver: live-monitor

receivers:
\- name: live-monitor
  email_configs:
  \- to: receive@test.com
    smarthost: smtp.exmail.qq.com:465
    from: test@alert.com
   auth_username: "test@alert.com"
   auth_identity: "test@alert.com"
   auth_password: xxxxxx

**Comment by fabxc** [comment]
This is wildely unspecific and from a configuration alone we can unfortunately not help you.
If the issue still persists, please report back with any logs and a clearer description of what you expected to see, and what you saw instead.
