### ISSUE TITLE
Allow deep-linking into alertmanager alert list

### ISSUE THREAD

**Issue by mpalmer** [prometheus/alertmanager#438]
I'd like to be able to link to the list of alerts of a given alert name from the notifications I send.  At the moment, there's no element more specific than `#alert-groups` with an ID, so I can't link to anything specific, forcing people to scroll/search to find the relevant items.  An ID on each `.alert-group` div along the lines of `alertname-<foo>` would be perfect.

**Comment by grobie** [comment]
Duplicate of #211
