### ISSUE TITLE
Does "/api/v1/alerts" will aggregation all alerts?

### ISSUE THREAD

**Issue by ZhenyangZhao** [prometheus/alertmanager#439]
Hi
i have a question about /api/vi/alerts. hope someone can help me.
question:
    "/api/v1/alerts" will aggregate all alerts or aggregate the specified time ?

Thanks all.

**Comment by fabxc** [comment]
Disclaimer: the current API is not documented as it may heavily change. Any usage is at the risk of breaking in future versions.

The endpoint will just give you a dump of all alerts currently existing. Expired alerts are deleted though periodically, so the result may change over time.

**Comment by ZhenyangZhao** [comment]
@fabxc 
Thanks a lot. 
Wish Prometheus better and better. :)
