### ISSUE TITLE
Syslog receiver

### ISSUE THREAD

**Issue by darabos** [prometheus/alertmanager#448]
A client wants us to send alerts to their Syslog server. I think it would be easy to do this by adding a new receiver for Syslog.

I don't know anything about Alertmanager source code, but there are already a bunch of receivers and it seems straightforward to create a new one by looking at them. Plus Prometheus already uses `log/syslog` (in `prometheus/common/log/syslog_formatter.go`) from the Go standard library and the new receiver could just use that.

Is it okay if I send a pull request for this?

(Thanks for Prometheus by the way! We just started using it.)

**Comment by brian-brazil** [comment]
I'm not sure a syslog notifier makes sense, as it's not a typical way to notify a human. The webhook is probably the way to go here.

**Comment by mxinden** [comment]
I am closing here due to inactivity. @darabos please reopen if you want to further discuss this issue.

**Comment by Numblesix** [comment]
Hi i would like to bring back that topic :) 


We use CheckMK to check our Environment, if Alertmanager would be able to send syslog messages to it we could combine all our monitoring tools in CheckMK which has a powerfull syslog console :)

**Comment by kaizen1** [comment]
GCP logging has come a long way. Sending syslog to GCP is a snap, which opens up GCP to be used for alerting, thus eliminating the need for AlertManager for GCP users.
