### ISSUE TITLE
SMTP LOGIN authentication mechanism bug in V0.3.0

### ISSUE THREAD

**Issue by ZhenyangZhao** [prometheus/alertmanager#450]
Hi:
I found a bug in v0.3.0 when i testing. 
When AM send mail it always log "unexpected server challenge".
I think fromServer sometime like "username:", but the code compare like this "Username:"
Maybe password the same issue.
Testing mail server: "smtp.163.com:25"

Am i correct?

```
gofile: impl.go 
line: 949 
switch string(fromServer) {
case "Username:"
        return []byte(a.username), nil
case "Password:"
        return []byte(a.password), nil
default:
        return nil, errors.New("unexpected server challenge")
}
```

**Comment by grobie** [comment]
Fixed with #451
