### ISSUE TITLE
alert newline interpreted differently

### ISSUE THREAD

**Issue by EvertMDC** [prometheus/alertmanager#452]
Hello,

I couldn't find an open ticket for this.
When creating an alert, the alertmanager will interpret a `\n` as a newline
Prometheus itself interprets a html `<br />` in the alerts section.
In the e-mail sent out none of the two are interpreted. I believe this should be consistent.

Here is the complete line I used, only the names are changed.

```
ALERT mycontainer_PRD_availability
  IF count(time() - container_last_seen{environment="production",image=~"^mycontainer.*"} < 300)
  ANNOTATIONS {
    summary = "Production container is down",
    description = "No production container running in the last 5 minutes. <br /> \n Documentation: https://wiki.mywebsite.com/index.php/mycontainer",
  }
```

If anyone has better ideas of how to send documentation and related information like charts in the alerts, let me know.
Also, if anyone has additional documentation on how to use labels in the alerts, that would help too.

**Comment by fabxc** [comment]
This seems like Prometheus just fails to escape the HTML then in its UI.
Using HTML is a hint that you are probably going beyond the scope of alert annotations. In this case, you want documentation do be its own annotation. Any nicer representation for humans should happen in Alertmanager's notifications.

```
ALERT mycontainer_PRD_availability
  IF count(time() - container_last_seen{environment="production",image=~"^mycontainer.*"} < 300)
  ANNOTATIONS {
    summary = "Production container is down",
    description = "No production container running in the last 5 minutes.",
    documentation = "https://wiki.mywebsite.com/index.php/mycontainer",
  }
```

**Comment by EvertMDC** [comment]
Hello @fabxc 

Thanks for the info, I was unaware that we where allowed to add our own annotations. It looks much cleaner with the documentation as a separate annotation.
Where could I have found this in the documentation? I looked into this [page](https://prometheus.io/docs/alerting/rules/#defining-alerting-rules)

**Comment by fabxc** [comment]
This is meant to be expressed by the syntax specification, which says that
the annotations block may contain any `<label set>`, not just two specific
ones.

Further down:

The ANNOTATIONS clause specifies another set of labels that are not
identifying for an alert instance. They are used to store longer additional
information such as alert descriptions or runbook links. The annotation
values can be templated.

Do you have suggestions on how to make the intent clearer?

**Comment by EvertMDC** [comment]
Hello @fabxc 

I think it's rather my English that's not advanced enough. I've read it from a different perspective and was thinking the additional information was a fixed set of keys and that I couldn't find those keys.
Thanks for explaining.

**Comment by alexlokotochek** [comment]
Not very cool to see this. i followed `prometheus rules format` google search first link to be there - perhaps i'm not the only one :)  
![Uploading Screen Shot 2020-10-18 at 12.05.23 AM.png…]()
