### ISSUE TITLE
Alert creation automation

### ISSUE THREAD

**Issue by FGRibreau** [prometheus/alertmanager#453]
Hello !

Are there any plans to allow automated creation of alerts through an HTTP API for instance? Or do Prometheus currently provide another way to do so?

**Comment by fabxc** [comment]
No, alerts are exclusively provided via configuration rule files. The files
can be reloaded at runtime via sending a SIGHUP to the Prometheus process
or POSTing the /-/reload endpoint.

**Comment by FGRibreau** [comment]
thanks @fabxc :)

**Comment by thulasiprasad** [comment]
Hello ! 

Is this still the current state: alerts are exclusively provided via configuration rule files.

Will it be good idea to include this as an feature in upcoming releases?

**Comment by stuartnelson3** [comment]
Alerts can be created with the amtool bundled with alertmanager releases. Usage can be checked from the CLI directly.

```
amtool alert add --help
```

**Comment by FGRibreau** [comment]
For further reader, `amtool` only does alert insertion but sadly does not handle alert edition or removal (see https://github.com/prometheus/alertmanager/blob/master/cli/alert.go )
