### ISSUE TITLE
Email receiver does not support wildcard certificates

### ISSUE THREAD

**Issue by jcollie** [prometheus/alertmanager#476]
Using Alertmanager 0.4.0, I get an error when trying to send to my smarthost:

{"level":"warning","msg":"Notify attempt 12 failed: starttls failed: x509: certificate is valid for *.dmacc.net, dmacc.net, not smtp.dmacc.edu","source":"notify.go:193","time":"2016-08-25T16:21:38-05:00"}

Setting require_tls to false works around the issue, but I think that it would be better to support wildcard certificates.

**Comment by brian-brazil** [comment]
That error seems correct to me, those certs don't match.

**Comment by jcollie** [comment]
Ah, crap you're right... I guess that's what you get when you have too many similar domains.
