### ISSUE TITLE
Easier configuration for receivers and notifications

### ISSUE THREAD

**Issue by acdha** [prometheus/alertmanager#479]
I've been setting up some production alerting and ran into a couple of areas where documentation or UI improvements could have made that process easier:
1. It would be really helpful if there was some way to either repeat a notification manually rather than waiting for a new alert or having to lower the `repeat_interval` (#437). A button in the UI would be nice, especially for a specific receiver, but it might also be useful if the UI had a “Copy as cURL” shortcut to simplify the process of getting a valid payload, editing it, and replaying. A handy extension here would be the ability to simply repeating a notification where it would generate the payload but display it instead of delivering it so e.g. you could test Slack notifications without needing to either use a separate test channel or spam your coworkers.
2. All of the receivers have options to customize the message text but the documentation is sparse on examples, especially for things like annotations or labels. As an example, the documentation for Slack doesn't mention how to use annotation keys. #307 specifies that annotations are grouped under `CommonAnnotations` and usable as e.g. `{{ .CommonAnnotations.summary }}` but that never made it into the documentation and it's not clear which values are specific to a specific type of receiver (e.g. the same variable cannot be used to set the subject header for an email).

**Comment by fabxc** [comment]
Thanks for the input.

1. I'm considering providing some metadata history on past notifications. However, I don't want to record the entire payload of each. I don't believe that's a feature that's easy to maintain as we want Alertmanager to scale more.
I do like the idea of getting a copy-able `curl` statement for a group of alerts. That's reasonably easy to add without overhead in the critical path if we only do it for alerts currently visible. Similarly triggering a notification with the currently visible set, should also be possible. Though there are some semantical questions that would have to be discussed.

2. Yes, the documentation is lacking and it repeatedly gets pointed out. Someone (don't know GH handle) offered help on that end at PromCon. We definitely want to improve on that end.

**Comment by acdha** [comment]
Sorry to have dumped a docs gripe earlier. If I wanted to help contribute to the documentation, what would be the best way to break pull requests like that up so it's not a waste of your time to review / merge?

**Comment by fabxc** [comment]
That would be great. Our documentation lives (here)[https://github.com/prometheus/docs] in Markdown files. I think an initial pull request lining out documentation structure and basic contents would be great.
We could then discuss how to flesh it out further.

**Comment by mxinden** [comment]
@acdha I am closing here due to long inactivity. Please feel free to reopen. PRs for documentation are always welcome. We would really appreciate your help.
