### ISSUE TITLE
Feature request: Add endpoint exposing if there are active non silenced alerts.

### ISSUE THREAD

**Issue by KrestenKjaer** [prometheus/alertmanager#483]
Some backstory:
At LEGO we use IBM Omnibus for our front desk monitoring.
We would like to integrate IBM Omnibus with the Prometheus Alertmanager.

In order to do this, we would like to expose an endpoint with the current active non-silenced alerts, and nothing else.

Proposal is as follows
Request:
GET /api/v1/alerts/active

Return:
{} - No alerts

Active alerts:

```
[{
labels: {
__name__: "up",
alertname: "InstanceDown",
instance: "cassandra-0.dev.vpc.education.lego.com:9100",
job: "node",
severity: "page"
},
annotations: {
description: "cassandra-0.dev.vpc.education.lego.com:9100 of job node has been down for more than 5 minutes.",
summary: "Instance cassandra-0.dev.vpc.education.lego.com:9100 down"
},
startsAt: "2016-08-31T08:43:22.826Z",
endsAt: "0001-01-01T00:00:00Z",
generatorURL: "http://ip-10-0-0-239:9090/graph#%5B%7B%22expr%22%3A%22up%20%3D%3D%200%22%2C%22tab%22%3A0%7D%5D"
},...]
```

Would this be a feature we could get merged into mainline?

**Comment by matthiasr** [comment]
Would outgoing webhooks (from Alertmanager to Omnibus/an integration) work for your use case?

I think in general providing this (or an equivalent) endpoint is a reasonable thing though.

**Comment by KrestenKjaer** [comment]
Hi Matthias,

Due to firewalls between regions it is easier to let Omnibus connect out, than letting other services connect to it.

We will probably just use /alerts/groups as a start, to get something working.

**Comment by fabxc** [comment]
The current API was merely written to serve the UI. An more general and though-through API is definitely on our close roadmap.

**Comment by mxinden** [comment]
@KrestenKjaer the `api/v1/alerts` endpoint has the `silenced` query parameter. Using `http://localhost:9093/api/v1/alerts?silenced=false` will return only non-silenced Alerts. Let me know if this is of any help for you.

**Comment by mxinden** [comment]
Closing here due to inactivity. @KrestenKjaer feel free to reopen.
