### ISSUE TITLE
simple.yml should be alertmanager.yml

### ISSUE THREAD

**Issue by brian-brazil** [prometheus/alertmanager#484]
Unlike other prometheus binaries with config files, simply running the alertmanager binary from the tarball doesn't work. We should rename simple.yml to alertmanager.yml so this works out of the box

**Comment by stuartnelson3** [comment]
I'm not sure it makes sense to do this. My main reasoning is that while you can start the default prometheus config file and it will scrape itself, there's no smart default that will allow an alertmanager to send alerts anywhere useful.

I opened a PR, as it does give the users a working AM which will send webhooks to local port.
