### ISSUE TITLE
Consolidate behavior of silence editing

### ISSUE THREAD

**Issue by grobie** [prometheus/alertmanager#485]
I have trouble understanding silence modification. The behavior seems to be highly dependent on the context, which makes it pretty hard to understand imho.

@stuartnelson3 backported some changes in master into the release-0.4 branch which resulted in the creation of duplicated silences when updating a typo in a silence comment. In my effort to fix the most outstanding bugs in the 0.4.x series, I simplified the logic in https://github.com/prometheus/alertmanager/commit/7385ac95fab3c32dea0580a9f9f1ae6609b21d76. Now editing a silence would always delete the previous one and create a new one.

After some more testing, I realized that editing an elapsed silence will change the time fields upon opening, while that's not the case when editing active alerts. I'm now really confused about the use cases and idea behind all this context specific behavior.

IMHO behavior of a button/form should not change based on the context. I'd love some clarification here @fabxc. I'm holding off with the release of v0.4.2, but please note that the creation of regex matchers is currently broken in v0.4.0 and v0.4.1.

**Comment by fabxc** [comment]
Previously editing was always delete+recreate (happening at UI level =\).
If you had to add that now, it broke somewhere along the way recently.

Editing an elapsed silence is not an edit. It's creating a new one with the
same matchers first and foremost. It always means you want to define a new
time range so using the default of now-now+4h here seems logical to me.

In the new semantics in master active or pending silences should not be
editable at all aside from changing timestamps laying in the future an
adding comments.
That's not reflected in the UI, which makes is very non-obvious.

**Comment by grobie** [comment]
That makes sense and I figured something like that was the intention when I thought about it on my bike. What do you think about changing the buttons for elapsed alerts, calling it something like duplicate/recreate or something? Then we'd have the semantics of:

* edit button for active alert -> delete+create
* duplicate for elapsed alert -> create a new one, leave existing untouched

Does this make sense?

**Comment by fabxc** [comment]
Mh, the naming was clarified a while ago:
https://github.com/prometheus/alertmanager/pull/408/files

Do you mean something different from that or were you looking at an older
UI?

**Comment by grobie** [comment]
Ok, the current behavior is funny, but I'll leave it as it is until we release the rewrite in master.
