### ISSUE TITLE
HA notification failover collides with regular timeout

### ISSUE THREAD

**Issue by fabxc** [prometheus/alertmanager#488]
In an HA setup, Alertmanagers wait with notifying depending on their peer ordering.
For example, with 3 peers, the A send notification right away, B with 5 second delay, C with 10 second delay.

If `timeout := max(group_interval, notification_timeout); timeout > peer_wait` the context will time out before we have a chance to start sending a notification. In this scenario these Alertmanagers would never send a notification if the other peers are down.

The easiest solution to extend `timeout` by `peer_wait`. This will cause overlaps in the notification pipeline, i.e. while we still try to send the current notification, the next one is kicked off already.
For now this seems fine. Overwriting the contents of an in-progress notification  by more recent data introduces fragility. Generally the `group_wait` should be large enough for this never to happen.
If it's not, the difference is probably not large enough for the staleness to be even noticeable by the user.

I'd go ahead with the simple solution unless there are concerns.

@brian-brazil @brancz @beorn7

**Comment by brancz** [comment]
SGTM at first glance.

**Comment by beorn7** [comment]
> `timeout := max(group_interval, notification_timeout); timeout > peer_wait`

Shouldn't that be `<`?

Could flip-flopping happen? I.e. the AM with the lowest peer_wait sends the next notification already, then the one with the long peer_wait sends the obsolete one, only to send the new one a bit after...

(Can only happen if both AMs can talk to the notification receiver but not to each other.)

Perhaps it would be easier to require certain minimum values for `group_wait` and `notification_timeout`?

**Comment by beorn7** [comment]
Or just extend the timeout on all AMs by the max peer_wait.

**Comment by fabxc** [comment]
> Shouldn't that be `<`?

Yes, sure.

Yes, the case you described could happen, though be extremely unlikely. 

I think some people wouldn't like a minimum group wait. We discourage it but some people want it for various reasons. The notification timeout is currently not configurable as it's as long as the group wait interval and a default minimum of 10 seconds.

The question with extending all timeouts would be whether we want to extend the timeout in the standard case by that long. Also, it's not a guarantee everything being eventually consistent etc.

**Comment by fabxc** [comment]
@beorn7 Would you be okay with the basic fix in #489 for now?
It is a critical fix without which the entire HA thing may fall apart (in an edge case).

What you describe here is also an edge case we have to think about, but it only results in some user artefacts of staleness. There'll be no generally wrong or missing data though. Also by nature of the architecture, such artefacts just happen in certain unhappy cases.

For example. A Prometheus server sends an alert set out to all Alertmanagers. In the normal case all AM's internal timers would be aligned within +/-1s but they are not explicitly synchronised. 
Now if one of them is not reachable in the rule evaluation cycle but gets the alert set in the next one, the timers will be vastly unaligned (due to `group_wait` vs `group_interval`). With all AMs retrying until the next interval, we can see similar things.

I don't think we can get rid of this entirely. But one way to mitigate it significantly would be to re-check between retries whether another AM has successfully notified in the meantime.

**Comment by beorn7** [comment]
Sure. Go ahead with #489. When playing with it, we'll notice what goes wrong. Let's just keep those possibilities in mind.

I'm kind of sidetracked by many other issues in the moment, so I cannot really focus on the AM story right now. Sorry for that.

**Comment by fabxc** [comment]
Thanks, no worries.
