### ISSUE TITLE
First thoughts on using AlertManager

### ISSUE THREAD

**Issue by quinox** [prometheus/alertmanager#49]
* The documentation suggests using `config/fixtures/sample.conf.input` as a starting point for your own config. This file applies a filter to all alerts, meaning your alerts will most likely end up being ignored. I suggest removing the filter from this file (or commenting it out, or creating a better starter config)
* The documentation suggests reading `config/config.proto` to learn more about the configuration, but unless you know how to interpret golang variables and structs it doesn't actually help you with the layout of your configuration file. I'd rather see an actual configuration file with everything in it. 
* Explain how you can enable/disable certain notification types
* Give Prometheus, PromDash and AlertManager each a distinct favicon (diff. color versions of the same favicon fe.) so I can see which browser tab goes where.
* Adding a column "next notification moment" in the web-ui alert list would be nice
* `-notification.smtp.smarthost` requires you specify the port number. It would be user-friendly if AlertManager would assume 25 if no port is specified

**Comment by juliusv** [comment]
:+1: to all points. PRs welcome! :)

**Comment by sdurrheimer** [comment]
> Give Prometheus, PromDash and AlertManager each a distinct favicon (diff. color versions of the same favicon fe.) so I can see which browser tab goes where.

I can give it a try. Do we have a PSD or something ?

**Comment by ThuyNT2916** [comment]
I set Postfix null-client, It has sended mail successfull. Then, I set -notification.smtp.smarthost port 25, but alert don't send to mail.??. I need helping.

**Comment by fabxc** [comment]
All these refer to the old Alertmanager. Closing.
