### ISSUE TITLE
CHANGELOG is out of date

### ISSUE THREAD

**Issue by mattbostock** [prometheus/alertmanager#497]
The last release in the changelog is 0.3.0:
https://github.com/prometheus/alertmanager/blob/master/CHANGELOG.md

**Comment by juliusv** [comment]
Seems this was fixed in https://github.com/prometheus/alertmanager/commit/2d03cccf0e082202b0258ebb3c8b944aa24dd761.

**Comment by mattbostock** [comment]
Thanks!
