### ISSUE TITLE
WebhookMessage: Allow reuse from webhook receivers ?

### ISSUE THREAD

**Issue by shammash** [prometheus/alertmanager#505]
Hi,

I am writing a simple relay service in Go that receives notifications from alertmanager via webhook and notifies and IRC channel.

Right now I basically had to replicate the WebhookMessage[1] and Data[2] structs in order to unmarshal the json message correctly, therefore I am wondering:

Would you consider exposing the WebhookMessage and Data structs a bit more so it's easier for webhook receivers to reuse the official structs with a simple import?

If this makes sense I'll be happy to contribute with a patch, provided you explain how you would like this to be done (webhook message package in alertmanager? something under client_model? something under common?).

Thank you,

Luca

[1] https://github.com/prometheus/alertmanager/blob/92acfbd449e2f6534367c8ed103271dea35d0d2a/notify/impl.go#L133
[2] https://github.com/prometheus/alertmanager/blob/ecd856a401e2172ec8f7a131e209feb99e13338a/template/template.go#L217

**Comment by fabxc** [comment]
Mh, what do you mean by exposing more? Both structures are exported and can hence be imported by your code.

**Comment by shammash** [comment]
Hi,

thank you for getting back.

Yes, that is correct, and I am in fact importing github.com/prometheus/alertmanager/notify in my code.

I asked this question when I started writing the configuration to create a debian package for my little service. I noticed that the alertmanager debian packages currently do not provide a -dev package containing the source that I can use as a build-dependency my service's package.

Looking around a bit I have noticed only a few prometheus projects coming with a debian -dev package. All these projects are client libraries or client oriented data structures:
golang-github-prometheus-client-golang-dev - Prometheus instrumentation library for Go applications ( https://github.com/prometheus/client_golang )
golang-github-prometheus-client-model-dev - data model artifacts for Prometheus ( https://github.com/prometheus/client_model )
golang-github-prometheus-common-dev - Common libraries for Prometheus components ( https://github.com/prometheus/common )

I then started wondering that maybe WebhookMessage should follow the same approach in order to have a -dev package, hence my request.

However if you are happy with webhook receivers including github.com/prometheus/alertmanager/notify I will just open a feature request for the prometheus-alertmanager debian package to provide a -dev / source package.

I hope this makes sense?

Thank you,

Luca

**Comment by fabxc** [comment]
The surface area is to small for this to be a separate repository. Maybe we will have an AM client library in the future for the regular API that could then also include this structure. That would be a fair bit down the road though. 

@TheTincho is maintaining the Debian packages for us. This is in his free time though so it's up to him whether he thinks its worth his efforts to have a `-dev` package for Alertmanager.

**Comment by shammash** [comment]
That makes sense. Thank you for getting in touch with @TheTincho , I'll follow up with him on the debian BTS . I'll close this for now.

**Comment by TheTincho** [comment]
Hey,

It would be no problem to create a -dev package for the alertmanager. I don't do it for applications because usually it is not needed by anyone. @shammash if you can open a bug in the BTS, I will prepare this for the next release, once I solve some issues with the embedded javascript.

**Comment by shammash** [comment]
Thank you very much! 
I've opened https://bugs.debian.org/837756 .
