### ISSUE TITLE
Inhibitor incorrectly inhibits alerts where no 'equal' labels are present

### ISSUE THREAD

**Issue by mattbostock** [prometheus/alertmanager#507]
Version in which bug was encountered: 0.4.1
Bug also applies to current tip of master: 503a6c0

The [documentation for inhibition rules](https://prometheus.io/docs/alerting/configuration/#inhibit-rule-<inhibit_rule) states:

> Both alerts must have a set of equal labels.

However, the [code](https://github.com/prometheus/alertmanager/blob/503a6c0569b1225d41347c6ff1570c6b12f93b39/inhibit/inhibit.go#L204-L209) will inhibit any alerts matching the target matchers, if neither source nor target alert have any of the labels in the 'equal' configuration setting:

``` go
        for n := range r.Equal {
            if a.Labels[n] != lset[n] {
                continue Outer
            }
        }
        return true
```

For example, if I use the following configuration:

``` yaml
inhibit_rules:
- source_match:
    alertname: Foo
  target_match_re:
    alertname: .*
  equal:
    - bar
```

...then all alerts not having a label of `bar` will be inhibited if the alert `Foo` is firing and also does not have a label of `bar`.

This seems to contradict the documentation and could also have a severe impact by suppressing alerts unintentionally.

It seems that the acceptance tests aren't working on master so I've created a branch of tag `v0.4.1` which demonstrates the issue:
https://github.com/prometheus/alertmanager/compare/release-0.4...mattbostock:inhibit_equal

**Comment by fabxc** [comment]
Mh, so in Prometheus we explicitly defined unset label to be equal the empty label value. Applied here this would mean that the behavior is correct.
What do you think, does this just need clearer documentation or should we explicitly alter the definition for inhibition rules?

The acceptance tests should be working in master, by the way. Can you point out what's not working for you?

**Comment by mattbostock** [comment]
> The acceptance tests should be working in master, by the way. Can you point out what's not working for you?

My bad, when I was testing earlier on I hadn't realised that the acceptance tests require you to rebuild the binary. They're working fine when I rebuild the binary first.

> What do you think, does this just need clearer documentation or should we explicitly alter the definition for inhibition rules?

If I explain my use case, that would probably help. I have an alert defined (`Instance_Down`) that fires if `up == 0`. If `Instance_Down` is firing, e.g. `up{instance="acme-service"} == 0`, I'd like to inhibit all alerts for that instance.

**Comment by fabxc** [comment]
For most cases it's probably a fair assumption that the user wants the equal labels to not be empty. Just slightly worried about the inconsistency we introduce. We need more opinions here.

As a workaround you could match the equal labels with`.+` in either the target or the source matchers. E.g. this should work, right?

```yaml
source_matchers:
    alertname: Instance_Down
target_matchers_re:
    alertname: .+
    instance: .+
equal:
  - instance
```

@brian-brazil

**Comment by brian-brazil** [comment]
I'd keep things consistent. This feels more like #180

**Comment by mattbostock** [comment]
@fabxc: Thanks. Yep, the regex match would meet our needs.

I don't have enough context on how Prometheus treats empty label sets to have an opinion on whether it's worth breaking consistency with that.

I think improving the documentation (with an example of the regex above) is sufficient to resolve the issue.

I'm still a little concerned that matching empty label sets for inhibiting alerts makes it easy for someone to shoot themselves in the foot (though I'm biased ;-)). Then again, the configuration for inhibition is subtle enough that it requires a lot of due attention to the documentation anyway.

I'll raise a PR to improve the documentation.

**Comment by fabxc** [comment]
Yes, inhibition can be as dangerous as it is powerful. The per-route
inhibitions issue Brian referenced is an important feature that makes it
less risky to work with.

**Comment by brian-brazil** [comment]
This is working as designed as far as I can see, missing labels are the same as empty labels.
