### ISSUE TITLE
Webhook: allow setting TLS options (ca cert, possibly client certs) and Auth Bearer token

### ISSUE THREAD

**Issue by ibotty** [prometheus/alertmanager#516]
It would be great to support setting tls options and support authentication for webhooks.

**Comment by riemers** [comment]
Since docker compose doens't have copy afaik, adding a cert if your using your own CA isn't that easy. Is there a way to handle that then?

**Comment by ibotty** [comment]
Well, there are other container orchestration systems that know how to do that easily. I assume with docker-compose you would use a config volume.

**Comment by riemers** [comment]
Well i could mount a volume for my certs into the alertmanager, but they still need to be added somehow. Openssl or the ca-update programs are not installed in the image. Perhaps someone has a nice idea, untill then i think i can better just grab the dockerfile, adjust it and use that as base in the docker-compose.

**Comment by ibotty** [comment]
Sorry, I don't understand what you are talking about. My intention was to have something analogous to Prometheus' TLS config options. That does not require openssl in the base image.

**Comment by riemers** [comment]
Ah, in my case i need some certs to be in place because the alert manager is calling services that have ssl certificates that are signed by a internal CA.

**Comment by ibotty** [comment]
That's exactly the situation I am in. I am certainly missing something, but I don't know why a simple volume mount in the container does not work.

**Comment by viq** [comment]
@riemers AFAIK all `ca-update` does is generate symlinks with hashes. You can do that outside of container, and mount that in container, and it should work.
