### ISSUE TITLE
Paginate alerts and silences

### ISSUE THREAD

**Issue by mattbostock** [prometheus/alertmanager#522]
Accessing the `/#/alerts` page in the web UI results in a hung browser (and as much as 5GB memory usage) if the number of alerts is in the thousands.

Suggest that we paginate the alerts in the same way as the silences.

**Comment by grobie** [comment]
What version do you use? v0.5.0? We have pagination in v0.4.0 but it got lost in the rewrite.

**Comment by mattbostock** [comment]
v0.4.2 currently.

**Comment by grobie** [comment]
Oops, misread your message. We don't have alert pagination in any version.

**Comment by mxinden** [comment]
I will close here as #924 is a more up to date discussion of this topic. The new UI is a lot better in terms of resource consumption. @mattbostock If you have time, could you try out the new UI and report your experience with many alerts back to us. We would really appreciate some production experiences.
