### ISSUE TITLE
Notification log problems in master

### ISSUE THREAD

**Issue by johto** [prometheus/alertmanager#523]
Hi!

I tried to use AlertManager from the current HEAD of the master branch (a84fba776244fd6be464ffb7b6d1ce3e8c06ae9d), but there seems to be a big problem when SetNotifiesStage and FilterResolvedStage are used together.  Consider the following sequence of events:

  1. An alert fires, and an email is sent
  2. The same alert is resolved, but FilterResolvedStage prevents that fact from being propagated downwards
  3. The alert fires again

Now the fact that the alert is firing is propagated down the pipeline, but because SetNotifiesStage never saw the "resolved" event, DedupStage.needsUpdate thinks nothing's changed and holds the alert.  The problem continues until `repeat_interval`, and then the sequence starts all over again.

I'm not convinced that this is the correct fix, but the problem goes away if I apply the following change:

```Go
diff --git a/notify/notify.go b/notify/notify.go
index 264e494..31af6d8 100644
--- a/notify/notify.go
+++ b/notify/notify.go
@@ -206,10 +206,10 @@ func createStage(rc *config.Receiver, tmpl *template.Template, wait func() time.
        }
        var s MultiStage
        s = append(s, NewWaitStage(wait))
-       s = append(s, NewFilterResolvedStage(i.conf))
        s = append(s, NewDedupStage(notificationLog, recv))
-       s = append(s, NewRetryStage(i))
        s = append(s, NewSetNotifiesStage(notificationLog, recv))
+       s = append(s, NewFilterResolvedStage(i.conf))
+       s = append(s, NewRetryStage(i))
 
        fs = append(fs, s)
    }
```

**Comment by fabxc** [comment]
Hi, thanks for reporting.

You are correct. This behavior is not correct. The reordering you applied here will solve your scenario but will introduce wrong behavior in a variety of other cases.

@brancz can you look into this? In previous releases we filtered resolved notifications out here: https://github.com/prometheus/alertmanager/blob/release-0.4/notify/impl.go#L86

This didn't affect the notification logs being saved. So this shouldn't be prevented by the generally less expensive notification log approach in master.
I guess we could just filter them out when building the notification but always pass resolved alerts down the other stages?

**Comment by brancz** [comment]
Super busy at LinuxCon, but trying to look into it!

**Comment by brancz** [comment]
@johto Thanks a lot for your feedback, it's very important for us! We'll cut another release some time soon including this fix.

**Comment by johto** [comment]
No problem, and thanks for the quick fix!
