### ISSUE TITLE
Silence per receiver

### ISSUE THREAD

**Issue by tom-tuddenham-bulletproof** [prometheus/alertmanager#526]
Hi there. We have a scenario where we need to silence the alerts going to one receiver but not to others (e.g. alert goes to support staff but not to other users during the period).

I can't see any way to do that with the current silence model. Is there any way to effect this (e.g. upstream via Prometheus)? Any advice appreciated.

**Comment by brian-brazil** [comment]
There's no such support, and we don't plan on on adding it. Silences are based on labels, so you could either ensure alerts share a label or handle it downstream of the alertmanager.

**Comment by tom-tuddenham-bulletproof** [comment]
thanks @brian-brazil

**Comment by juliusv** [comment]
This sounds similar in some ways to https://groups.google.com/forum/#!topic/prometheus-developers/NqjstvKSDfI, which contains some more background on the rationale.
