### ISSUE TITLE
Mesh config uses fixed password ""

### ISSUE THREAD

**Issue by aecolley** [prometheus/alertmanager#529]
`initMesh` supplies the empty string (and not `nil`) as the password when configuring the weave mesh in v0.5.0-beta.0. This should be configurable at runtime, preferably by reading the password from a filename-valued flag.

The problem with using an empty string is that it triggers the mesh code to negotiate an encrypted session on the network connections, giving the illusion that confidentiality is protected. Poor security is worse than no security. The newness of the mesh protocol already carries an administrative burden because IDS and other auditing mechanisms have to address it; let's not put deployers in the position of arguing for obscurity over security.

I suggest putting the password in a file and not in the config file because it will make password rotation easier. Rotating a password in a mesh of alertmanagers is a matter of restarting alertmanagers so that they are configured to join a new mesh with a new password, disjoint from the old mesh. The mesh peer flags will have to change for this to work, so it is no extra hardship to change the password flag at the same time. If the password is put in the config file, then something extra will have to be done to prevent the changed config file from being propagated to the old-mesh alertmanagers in the usual way.

Finally, consider recognizing a special flag value which will use `nil` as the `mesh.Config.Password` value. This will allow disabling the secure session setup entirely, which can be useful for a few reasons (namely, debugging, TLS-wrapping, and enabling auditing of traffic on sensitive network segments).

**Comment by fabxc** [comment]
Thanks for investigating this. There was no intention for "security through obscurity", we ultimately want to allow users setting passwords through an AM flag, of course.

I also agree that it shouldn't be in the config file – but none of the other mesh options are either and there's no intend to change that.

Do you think taking `""` as `nil` is sane as long as it's documented explicitly?
I don't think there's a sane configuration where a `""` is actually used as a password.

**Comment by aecolley** [comment]
This all sounds good to me.

**Comment by brancz** [comment]
@aecolley Thanks for the report. We need all the feedback we can get for this release! 🙂
