### ISSUE TITLE
How to add proxy data to receivers?

### ISSUE THREAD

**Issue by norbert2-nagy** [prometheus/alertmanager#533]

**Comment by brancz** [comment]
It would be nice if you could tell us a bit of context of what you are trying to do, so we can answer whether/how that is currently possible, without any detail we cannot answer your question precisely.

**Comment by norbert2-nagy** [comment]
I am trying to use pagerduty as a devops receiver like the following:

```
- name: "devops"
    pagerduty_configs:
    - service_key: aaaabbbb1112222
```

Without our proxy, pagerduty gets the post request, works fine, but behind proxy I get the following warning:

> level=warning msg="Notify attempt 1 failed: Post https://events.pagerduty.com/generic/2010-04-15/create_event.json: dial tcp: i/o timeout" source="notify.go:193

Is there anything like prometheus' proxy url config?

> proxy_url: 'http://localhost:1234

Sorry for not being clear asking the question and thanks in advance.

**Comment by brancz** [comment]
The PagerDuty integration simply uses a ctxhttp Post request with the golang http.DefaultClient, which uses the http.DefaultTransport, which in turn uses [http.ProxyFromEnvironment](https://golang.org/pkg/net/http/#ProxyFromEnvironment). So as far as I can tell it should work by setting the `HTTP_PROXY` environment variable. :)

**Comment by norbert2-nagy** [comment]
Thank you, it is now working like a charm :)

**Comment by brancz** [comment]
No problem :)
