### ISSUE TITLE
DNS resiliency for notification delivery

### ISSUE THREAD

**Issue by aecolley** [prometheus/alertmanager#536]
When `events.pagerduty.com` is unresolvable, notifications for it cannot be delivered after the DNS records for it expire, even though the service is still available at the last-resolved addresses.

It's practically necessary to add fallback IP addresses in `/etc/hosts` and to amend `/etc/nsswitch.conf` to use dns first and then files.

For greater resiliency in notifications, this non-obvious operational setup should be documented somewhere in alertmanager best practices. Alternatively, alertmanager might manage to keep and reuse the last-resolved addresses if fresh lookups fail. Or perhaps this isn't worth worrying about, in which case close after making that decision.

**Comment by stuartnelson3** [comment]
I think this is an issue that should be handled outside of alertmanager, with the host's dns setup.
