### ISSUE TITLE
Duplicate Alerts in Alertmanager UI

### ISSUE THREAD

**Issue by jjneely** [prometheus/alertmanager#539]
I'm running Alertmanager 0.3.0 with Prometheus 1.2.1.

I've setup Alertmanager to route alerts to multiple different receivers.  So a single alert routes to the responsible team, and to a webhook.  Apparently, since there are two matching receivers the alert appears twice on the Alerts tab of the Alertmanager web UI.  

I would expect that the alert would only be displayed once.  I know it will be confusing to other members of our ops team.

**Comment by fabxc** [comment]
Currently we show a semi-flattened version of our routing hierarchy. If an alert ends up in two different groups, being displayed twice is thus the expected behavior.

I understand how it's not ideal. To fix it, we have to come up with a different way to display alerts in general that makes sense.

**Comment by mxinden** [comment]
@jjneely This will be fixed with the new UI (See branch [ui-rewrite](https://github.com/prometheus/alertmanager/tree/ui-rewrite)). 

Closing here. Let me know if you have further questions.
