### ISSUE TITLE
headers: Content-Type: doesn't work

### ISSUE THREAD

**Issue by powerman** [prometheus/alertmanager#542]
I've tried to overwrite default text/html with text/plain, but looks like it doesn't work because default Content-Type is added after custom headers.

As a side note, default html template looks unreadable in text-only email client like mutt (html rendered using lynx). I've developed [own template](https://gist.github.com/powerman/56b1f5b29fce5d9f8b4c9380e620c7dd) but that's still too much for sending email-to-SMS messages.

Related to #290

**Comment by fabxc** [comment]
Yes, ideally we would implement #290 to solve this issue.
Any help here is welcome.

**Comment by simonpasquier** [comment]
Closed by https://github.com/prometheus/alertmanager/pull/934 IIUC

**Comment by stuartnelson3** [comment]
closed by #934
