### ISSUE TITLE
New behavior with 0.5.0 (send_resolved)

### ISSUE THREAD

**Issue by raypettersen** [prometheus/alertmanager#544]
Might not be a bug, but didn't read anything in the release notes about change in behavior when setting send_resolved.

time="2016-11-03T18:58:18+01:00" level=error msg="Loading configuration file failed: unknown fields in global: send_resolved" file="/etc/signicat/alertmanager/alertmanager.yaml" source="main.go:197"

Was easily resolved by setting send_resolved on each receiver, but would have been practical to set in global.

**Comment by brian-brazil** [comment]
Send_resolved is not a global setting, and it'd be incorrect to do so as send_resolved has a different sane default per receiver.

**Comment by raypettersen** [comment]
Suspected that much. I just thought I'd point out that I was unable to upgrade smoothly as 0.4.0 didn't throw an error. Thanks for the info. You can close this question.

**Comment by brian-brazil** [comment]
I'm presuming we improved detecting errors in configuration in this release, and that this setting in your config never had an effect.
