### ISSUE TITLE
Alertmanager silence checkbox persistance

### ISSUE THREAD

**Issue by RonVander** [prometheus/alertmanager#545]
Hello,

Currently using version 0.5.0 of alertmanager.
Would it be possible to make the tick on the "hide silenced" check box persistent trough a refresh of the page ?
When clicking on the tick box it could written to a cookie  for instance.
This would make it easier to auto refresh the page.

**Comment by brancz** [comment]
I believe we had this feature previously implemented in the 0.4 release branch, but lost it due to big restructuring from 0.4 to 0.5. We had previously used `localStorage` for this. I think we should bring the feature back. @fabxc

**Comment by mxinden** [comment]
@RonVander The state of the "hide silenced" checkbox is now persisted in the URL. Please reopen in case you have any further questions.
