### ISSUE TITLE
Changing template color

### ISSUE THREAD

**Issue by raypettersen** [prometheus/alertmanager#547]
Quick question. What is the best approach for changing email-template colors? We have a few alertmanagers working in different environments, and would like to change the html colors so it's easier to identify the sender.

**Comment by mxinden** [comment]
@raypettersen Please open up usage questions on the [Prometheus users Google group](https://groups.google.com/forum/#!forum/prometheus-users). I will close here. Please reopen in case I am misinterpreting your question.
