### ISSUE TITLE
display some metrics value in alert email.

### ISSUE THREAD

**Issue by changsijay** [prometheus/alertmanager#549]
I have a rule about disk almost full as below which will send email when available disk size is less than 10%

```
alert DiskLow
  if node_filesystem_avail{instance="10.60.90.147:9100", mountpoint="/"}/node_filesystem_size{instance="10.60.90.147:9100", mountpoint="/"} < 0.1
  for 5m
  labels { severity = "email" }
  annotations {
    summary = "Node {{ $labels.instance }} disk low, free space < 10%",
    description = "{{ $labels.instance }} disk is almost full!!",
  }
```

Would it possible to display the size information in the email? say: current disk usage is `93G/100G`

**Comment by brancz** [comment]
You can render the current value with `{{ $value }}`, however that is the remaining disk space in this case, so you might need some tweaking of your statement, but what you are trying to achieve is definitely already possible.

**Comment by changsijay** [comment]
Hi @brancz , sorry I am not very clear about how to do that. 
In the [doc](https://prometheus.io/docs/alerting/rules/)

```
ALERT <alert name>
  IF <expression>
  [ FOR <duration> ]
  [ LABELS <label set> ]
  [ ANNOTATIONS <label set> ]
```

the `{{ value }}`` is the `labels: value` pair in the `if` expression.
because our customers request to alert when the `disk usage percentage` > 90%.
I am not sure how I can get the value of `node_filesystem_avail{instance="10.60.90.147:9100", mountpoint="/"}` and `node_filesystem_size{instance="10.60.90.147:9100", mountpoint="/"}` separately in the rule.

**Comment by matthiasr** [comment]
You can use the [query template function](https://prometheus.io/docs/visualization/template_reference/#queries) in your annotations. You'll have to try it out, but something like

```
foobar = '{{ printf `node_filesystem_avail{instance="%s", mountpoint="/"}` $labels.instance | query | first }} / {{ printf `node_filesystem_size{instance="%s", mountpoint="/"}` $labels.instance | query | first }}'
```

should do what you want.

**Comment by changsijay** [comment]
Thanks a lot, I don't know about query template function before. going to study now 👯 
could someone help to  close the issue 👍

**Comment by cmcginty** [comment]
@matthiasr I'm new to prometheus. Is there a complete example of query and usage for reference?

**Comment by andrewhowdencom** [comment]
@cmcginty Generally speaking usability questions are redirected to the mailing list: 

https://groups.google.com/forum/#!forum/prometheus-users

You'll find a bunch of help there. Beyond that, the most complete documentation I've found is here: 

https://prometheus.io/blog/2016/03/03/custom-alertmanager-templates/

But the mailing list will likely have more.

**Comment by inkdude** [comment]
if i use $labels.mountpoint

how i should write query?
'{{ printf `node_filesystem_avail{mountpoint="$labels.mountpoint"}` $labels.instance | query | first }}

or how?

**Comment by K0zich** [comment]
@SergeiCherevko 
Sergey, hello!
Did you manage to figure out where to write this request?

Is there an example of a complete rule with this example?

alert: InstanceDown
expr: up == 0
for: 5m
labels:
  severity: page
annotations:
  summary: "Instance {{$labels.instance}} down"
  description: "{{$labels.instance}} of job {{$labels.job}} has been down for more than 5 minutes."

**Comment by K0zich** [comment]
working example: 

`description:  "number of codes in 2 minutes 500/ALL :  ``` {{ printf `http_server_requests_seconds_count{pod=\"%s\",  status=~\"2..\"}` $labels.pod | query | first | value | humanize }}`
