### ISSUE TITLE
Alertmanager reaching to receivers via proxy (https)

### ISSUE THREAD

**Issue by netvisao** [prometheus/alertmanager#554]
Is there currently a way for alertmanager to dispatch alert to receivers' endpoints via proxy?

Example: alertmanager dispatching alerts to pagerduty or slack, where in an entreprise environment, the pagerduty or slack endpoints are only reachable through a (http,https) proxy

**Comment by netvisao** [comment]
func ProxyFromEnvironment does the trick

**Comment by poblin-orange** [comment]
Hello,
i also need to send slack notification through a corporate proxy.
Im not aware of alertmanager internals. Is there a way to specify http proxy for the slack notification without coding?
thks

**Comment by netvisao** [comment]
Exporting http_proxy and https_proxy in your shell environment should make
it work.

**Comment by brancz** [comment]
Just as a warning: the mean to configure Prometheus and the Alertmanager is using config files, environment variables only work unintentionally as the underlying http implementation supports it. Having said that, there is no stability guarantee for environment variables, the option may disappear in any release, possibly without notice. If you wish to have it in a stable way, a patch to allow specifying it in the config would be welcome (not via env variables).

**Comment by netvisao** [comment]
Except that, right now, there does not seem that configuration files allow
to use a proxy and the only way is via the http{,s}_proxy

**Comment by brancz** [comment]
> a patch to allow specifying it in the config would be welcome

**Comment by ddewar2k** [comment]
Gang, Looking to see if this every resolved. Looking at the code and configuration guide its not obvious that an HTTP proxy can be added to a webhook config.  If this is allowed, does anyone have an example configuration snippet.

**Comment by jpiper** [comment]
@ddewar2k I can see here

https://github.com/prometheus/docs/blob/master/content/docs/alerting/configuration.md

That there's a `proxy_url` settings under `http_config`

**Comment by azizzoaib786** [comment]
based on documentation .. inside alertmanager.yml file, we can define as below:

`global:
  hipchat_api_url: 'https://company.hipchat.com'
  http_config:
   proxy_url: 'http://<IP>:3128' `

**Comment by Prabjyot19** [comment]
Can anyone please help me with alertmanager.yml config for opsgenie via proxy server ?

**Comment by roidelapluie** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by Prabjyot19** [comment]
Thanks for the Guidance @roidelapluie
