### ISSUE TITLE
Please update vendoring (and code) for prometheus/common/route

### ISSUE THREAD

**Issue by TheTincho** [prometheus/alertmanager#555]
Hi,

Currently, the alertmanager is failing to build in Debian, as I have updated the common lib when updating prometheus, and that brought an incompatible API change:

```
> src/github.com/prometheus/alertmanager/main.go:192: not enough arguments in call to route.New
```

I'd patch it, but I don't really know how to do it :-)

**Comment by TheTincho** [comment]
Uhm, not sure how this is compiling for you, but since you have not changed the code in AM, it still fails:
```
src/github.com/prometheus/alertmanager/cmd/alertmanager/main.go:245: not enough arguments in call to route.New
```

**Comment by TheTincho** [comment]
It seems the vendoring is incorrect. `vendor.json` says it is updated to commit `1e01b2bdbae8edb393fcf555732304f34d192fc9`, but I don' t even see that commit in common, and it does not have the changes to the router that were merged in September.

**Comment by fabxc** [comment]
Mh, seems like the vendoring tool has a bug or at least an inconsistency. I explicitly updated the common deps and again it showed me it was all up to date.

Had to purge it all and readd – does #572 look okay?

**Comment by TheTincho** [comment]
It does, thank you!

(note that now the build is broken, it seems you need to update more vendored packages)
