### ISSUE TITLE
Interface inconsistent w.r.t. date formats

### ISSUE THREAD

**Issue by EdSchouten** [prometheus/alertmanager#562]
I've noticed that the Alert Manager's web frontend is inconsistent with regards to the format of the date strings it shows.

If I go to `/#/silences`, I see that there is a silence in place that has its expiration set to '01/03/2017'. It turns out that this corresponds to January 3rd, which is a bit counter-intuitive for me, as in my culture this would get interpreted as March 1st.

If I go to `/#/alerts` and set up a new silence, the formatting is the other way around. The date picker has an initial value of '21/11/2016 12:29'.

Would it be possible to simply use ISO-8601 all over the place? I looked into doing this myself, but I guess I don't know enough about Javascript to fix this. The template uses `amCalendar()` to do its formatting, which seems to come from this library:

https://github.com/urish/angular-moment

**Comment by beorn7** [comment]
Yes, plan is to use ISO 8601 everywhere. see #94.

**Comment by beorn7** [comment]
I'll mark this as a dupe and make #94 more generic.
