### ISSUE TITLE
Web console to configure "regex" silence matches does not work on Firefox

### ISSUE THREAD

**Issue by leonerd** [prometheus/alertmanager#565]
Using chrome, I can correctly tick/untick the "regex" checkbox on label match rules.

In Firefox (version 49.0) clicking on the box does nothing. The check mark never appears and the rule does not have regex semantics.

**Comment by brancz** [comment]
If you are running version 0.5.x then I think we had previously fixed this in the 0.4.x release branch. @fabxc @beorn7 @stuartnelson3 @grobie anyone else remembers this?

**Comment by stuartnelson3** [comment]
I'm seeing https://github.com/prometheus/alertmanager/commit/9729d2db1651f9aae6fdb72075946145c2ec38c1 in the commit history, but it appears to be present in 0.5 also. I'll take a look.

**Comment by stuartnelson3** [comment]
Ah, can I get a confirmation on which version of alert manager you're using?

**Comment by snubba** [comment]
Hi, 
i have the problem with alert manager 0.5.1 (revision 0ea1cac51e6a620ec09d053f0484b97932b5c902).
The browser is 49.0.

**Comment by stuartnelson3** [comment]
Hi @snubba, can you post the JSON payload sent from your browser to the server when you attempt to create a silence with a regex? Feel free to sanitize any info, I'm just wondering if the regex is being sent to the server or not.

**Comment by snubba** [comment]
Hi @stuartnelson3 ,
i can't check the box in the first place. If i send the silence any way the json is as followed:
`comment "sdf"
createdBy "test@mail.com"
endsAt "2016-11-30T10:53:00Z"
id "6e8a14c3-adcf-4251-958e-fa23dfff1713"
matchers	[Object { name="s",  value="d",  isRegex=false}]
startsAt "2016-11-30T06:57:09.137908509Z"
updatedAt "2016-11-30T06:57:09.137908509Z"`

**Comment by stuartnelson3** [comment]
Ok, so this only seems to happen in firefox, so for the short term I would recommend using chrome (where it worked for me). The UI in `0.5` is the old one it seems? So it would appear this error has existed for a long time.

**Comment by vdemonchy** [comment]
Hello there, would you please have any news regarding this issue ?
I encountered it on firefox (up-to-date) and had it tested on IE 11 as well, same problem.
By the way, it's not only the regex checkbox which is untickable, but the calendar module is also not there on the aforementioned browser, so it looks like an issue with the JS lib used or something.

**Comment by stuartnelson3** [comment]
A new UI is currently in development. Unfortunately the best we can say right now is "try using chrome".

**Comment by vdemonchy** [comment]
Fair enough, thanks for the quick answer @stuartnelson3.
