### ISSUE TITLE
Unable to edit a silence expiry time

### ISSUE THREAD

**Issue by leonerd** [prometheus/alertmanager#566]
To reproduce:
 1. Create a silence
 2. Hit the 'EDIT' button
 3. Change the 'End' time
 4. Hit the 'CREATE' button

Expected result: silence's expiry time changes

Actual result: a red error message: "unexpected ID in new silence"

(this happens in Chrome or Firefox; does not appear to be browser version-dependent)

**Comment by brancz** [comment]
Which version of Alertmanager are you using? At the time where you hit the edit button, is the silence active?

**Comment by meier-christoph** [comment]
I have the same issue here using alertmanager-0.5.1.linux-amd64
the silence was active during the edit (I was trying to extend the silence duration)

**Comment by Samgarr** [comment]
Same situation here, exactly same as @meier-christoph describes.

**Comment by juliusv** [comment]
Getting the same error when I try to edit a silence with latest master.

**Comment by stuartnelson3** [comment]
Hey folks,

The alertmanager ui is being reworked, which will come with working edit buttons (!). Unfortunately I don't have a date when to expect this to be available, but it is currently under active development.

**Comment by mxinden** [comment]
Closing here as the new UI has been merged into master. @leonerd please reopen if you are still facing this issue with the new UI. Thanks a lot for the bug report.
