### ISSUE TITLE
Provide cli tool for interacting with alertmanager

### ISSUE THREAD

**Issue by Kellel** [prometheus/alertmanager#567]
I've been tossing around the idea of writing a cli tool for interacting with an alertmanager instance from cli. My primary interest is in being able to search/create/delete silences, but also being able to consume alerts via command line sounds mildly interesting. 

Are there any known tools that provide this functionality? Or would the community appreciate if I spent the time to toss something together? And if so would you like the contribution to be a part of this repo or a separate one?

Thanks!

**Comment by brancz** [comment]
I think there are a lot of people who would be happy about such a tool (mainly for backup purposes), however, keep in mind that there are absolutely no stability guarantees regarding the Alertmanager API at this point. Even though it might not happen very soon, we have been thinking about cleaning up some parts of the API.

Just an idea, but I could see a tool similar to `promtool` that lives in the Alertmanager repo, but a separate binary, that can just like `promtool` be used to check configs, and perform other tasks such as the ones you described.

**Comment by fabxc** [comment]
I also think it would be greatly appreciated by many!

Keeping it in this repo makes a lot of things simpler and also makes sure we release one with each AM version. Thus there'll be not much pain around API changes, as we are forced to fix the tool when changing our API.
Realistically, it won't be a big deal – API changes would be easy to swap and realistically, even if we replace the API, we'll probably keep it around for quite a while in parallel.

**Comment by Kellel** [comment]
Ok. I'll get to work!

**Comment by Kellel** [comment]
I've got a basic implementation working. I'm having some of my coworkers review it currently

**Comment by brancz** [comment]
Cool, looking forward to it!
