### ISSUE TITLE
Can I set up a different 'resolve' condition?

### ISSUE THREAD

**Issue by strangeman** [prometheus/alertmanager#571]
I want to prevent 'alert flaking'.

For example, I have a simple 'low_ram' alert:
```
ALERT low_ram
  if node_memory_MemAvailable / node_memory_MemTotal < 0.15
  LABELS {
    severity="page"
  }
  ANNOTATIONS {
      summary = "Low avaialble memory {{$value}} on {{$labels.instance}}"
  }
```
and sometimes I get 10 or so emails like "ALERT! RAM is 14.999998", "OKAY! RAM is 15.002", "ALERT! RAM is 14.99818", "OKAY! RAM is 15.014", "ALERT! RAM is 14.98234", "OKAY! RAM is 15.1" etc.

Can I set up different conditions for ALERT and OKAY states? For example - send an 'alert' email when RAM is low than 15% and send an 'okay' email when RAM is higher than 16%?

**Comment by brian-brazil** [comment]
There's no direct support for this in Prometheus. I'd suggest adding a `for` clause, and bumping the threshold.

**Comment by strangeman** [comment]
Okay, thank you for clarification.
