### ISSUE TITLE
"Firing" in mail  subject when actually "Resolved"

### ISSUE THREAD

**Issue by yosefy** [prometheus/alertmanager#573]
situation:
2 alerts are firing..
mail we get:
  "Firing 2"
the change:
  one is resolved
mail we get:
  "Firing 1"

when it should be : 
  "Resolved: 1"

because the message is about resolving
though it should include firing alerts in the body ofcause 

thanks

**Comment by fabxc** [comment]
The semantics are to always notify you about the current state of firing alerts.
If you want a differing behavior, you can use custom email templates.
