### ISSUE TITLE
Add groupKey to /alerts/groups endpoint

### ISSUE THREAD

**Issue by soupdiver** [prometheus/alertmanager#574]
I currently work on an integration with the alertmanager.
I receive webhooks from alertmanager which includes the `groupKey`.

I wonder why the API endpoint `api/v1/alerts/groups` does not contain the same `groupKey` information so that I could match the earlier received key against a list of grouped alerts to silences them.

Am I missing something or does it make sense to add that information to the mentioned API endpoint?

**Comment by mg03** [comment]
@soupdiver : Hi I was looking for documentation on doing something similar. Do you have a link to the docs ?

**Comment by soupdiver** [comment]
@mg03 Not sure which docs you are looking for... I went through the source code and looked at the API responses.

**Comment by brancz** [comment]
There are no API docs yet, as the API is not considered stable, and may change at any next release until it is explicitly marked as stable.

**Comment by soupdiver** [comment]
@brancz yep, makes sense. Can you may comment on my suggestion about adding the `groupKey` to the mentioned API endpoint?

**Comment by brancz** [comment]
I'm unsure why it's not in there seems fine to add it, maybe @fabxc knows more or has a stronger opinion.

**Comment by fabxc** [comment]
If you are okay with the explicit instability, I don't see any reasons against accepting a PR adding that field.

**Comment by soupdiver** [comment]
I don't mind the instability. It's communicated :)

**Comment by brancz** [comment]
This can be closed right? @soupdiver @fabxc

**Comment by soupdiver** [comment]
Solved by #576
