### ISSUE TITLE
text/plain support

### ISSUE THREAD

**Issue by kaihendry** [prometheus/alertmanager#577]
The emails alert manager generate seem to be Content-Type: text/html; charset=UTF-8 only.

A plain text counterpart would be handy on less capable MUAs.

https://s.natalian.org/2016-12-09/1481247762_1534x1404.png

**Comment by fabxc** [comment]
Yes, that would definitely be valuable. Actually we have a tracking issue for multipart emails in #290. So I'll close here as it's a duplicate.
