### ISSUE TITLE
Add title support VictorOps receiver

### ISSUE THREAD

**Issue by oryband** [prometheus/alertmanager#580]
In #417 support was added for VictorOps (PagerDuty alertnative).
However the receiver doesn't support [most fields listed in the docs](http://victorops.force.com/knowledgebase/articles/Integration/Alert-Ingestion-API-Documentation/), specificaly the `entity_display_name` field which serves as a title.

The result of this is the incidents created by Alertmanager have a random string as a title, forcing the user to open the incident page and search for the description body in order to understand what the incident it about.

The change should be pretty straight forward.

In addition, please allow to set the rest of the fields described in the docs above.

Thanks!

**Comment by fabxc** [comment]
This would certainly be accepted rather quickly. Would you like to give implementing this a shot?

**Comment by oryband** [comment]
@fabxc sorry but no, we have moved away from VictorOps.

**Comment by siavashs** [comment]
We are going to use VictorOps soon, so I will implement this.
