### ISSUE TITLE
Alertmanager refueses to start on Centos 7 box due to incorrect "no valid network interface"

### ISSUE THREAD

**Issue by clarkezone** [prometheus/alertmanager#582]
[root@dev2 alertmanager-0.5.1.linux-amd64]# ./alertmanager 
panic: no valid network interfaces

goroutine 1 [running]:
panic(0x86ccc0, 0xc420142500)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
main.mustHardwareAddr(0x92a522, 0x13)
	/go/src/github.com/prometheus/alertmanager/cmd/alertmanager/main.go:408 +0x158
main.main()
	/go/src/github.com/prometheus/alertmanager/cmd/alertmanager/main.go:85 +0x335

despite a perfectly valid and working network (i've XX'd out the actual values below):

ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN 
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: venet0: <BROADCAST,POINTOPOINT,NOARP,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN 
    link/void 
    inet 127.0.0.1/32 scope host venet0
    inet XX.XX.XXX.XX/32 brd XX.XX.XXX.X3 scope global venet0:0
3: gre0: <NOARP> mtu 1476 qdisc noop state DOWN 
    link/gre 0.0.0.0 brd 0.0.0.0
4: gretap0: <BROADCAST,MULTICAST> mtu 1476 qdisc noop state DOWN qlen 1000
    link/ether 00:00:00:00:00:00 brd ff:ff:ff:ff:ff:ff

**Comment by molecul** [comment]
I also encountered the same problem. But with operation system 'Ubuntu-14.04', on OpenVZ host hypervisor. 

root@ubuntu:/home/root/alertmanager-0.5.1.linux-386# ./alertmanager -config.file=simple.yml
panic: no valid network interfaces

goroutine 1 [running]:
panic(0x848ff00, 0x18a24df8)
        /usr/local/go/src/runtime/panic.go:500 +0x331
main.mustHardwareAddr(0x0, 0x0)
        /go/src/github.com/prometheus/alertmanager/cmd/alertmanager/main.go:408 +0x1ce
main.main()
        /go/src/github.com/prometheus/alertmanager/cmd/alertmanager/main.go:85 +0x307
root@ubuntu:/home/root/alertmanager-0.5.1.linux-386#


and ip addr too:

root@ubuntu:/home/root/alertmanager-0.5.1.linux-386# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: venet0: <BROADCAST,POINTOPOINT,NOARP,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN
    link/void
    inet 127.0.0.2/32 scope host venet0
    inet 10.2.168.2/32 brd 10.2.168.2 scope global venet0:0
root@ubuntu:/home/root/alertmanager-0.5.1.linux-386#

**Comment by Peter-Sh** [comment]
I have faced the same issue wiith openvz. OpenVz's venet interface does not have mac by design.
It seems harware-addr is used just as unique identifier of the host. Despite one can point this identifier as an command option ```-mesh.hardware-addr```  alertmanager will still fail to start if there is no any iterfaces with harware address .
I think
* mac addresses should not be tested if ```-mesh.hardware-addr``` option is provided
* It it may be better to use or to falback to _/etc/machine-id_ or _/var/lib/dbus/machine-id_

**Comment by brancz** [comment]
Agreed. Labeling as a bug.

**Comment by stuartnelson3** [comment]
adressed in #638
