### ISSUE TITLE
AlertManager takes up lots of CPU

### ISSUE THREAD

**Issue by fuzzyami** [prometheus/alertmanager#583]
We're running 2 standalone alertmanager instances (0.5.0) and they both churn out a LOT of CPU (250% on c4.2xlarge on AWS). Is this normal? Would the number of alerts significantly impact the CPU load?

we tried 0.5.1 but it didn't seem to make a difference.

**Comment by fabxc** [comment]
Can you provide your configuration and some numbers around what load AM is
dealing with? Like numbers of silences, received alerts/sec etc

**Comment by fuzzyami** [comment]
our config:

      global:
        resolve_timeout: 1m

      route:
        group_wait: 10s
        group_interval: 5m
        repeat_interval: 30m

        group_by:
          - cloud_zone
          - node
          - alertname
          - service

        receiver: slack_info  # default if rules below don't match

        routes:
          # critical alerts route to victorops, slack with "critical" mode
          - match:
              severity: critical
            receiver: victorops_critical
            continue: true
          - match:
              severity: critical
            receiver: slack_critical
            continue: true

          # warning alerts route similar to critical alerts but on "warning" mode
          - match:
              severity: warning
            receiver: victorops_warning
            continue: true
          - match:
              severity: warning
            receiver: slack_warning
            continue: true

          # critical media-server alerts also route to fez
          - match:
              service: media-server
              severity: critical
            receiver: fez
            group_interval: 0s
            repeat_interval: 5m
            continue: true

          - match:
              type: media
            receiver: fez
            group_interval: 0s
            repeat_interval: 5m
            continue: true


      receivers:
        - name: victorops_critical
          victorops_configs:
            - &victorops
              routing_key: rkik-critical
              api_key: <hidden>
              message: |
                {{.GroupLabels.service}}
                {{.GroupLabels.node}}

                {{.CommonAnnotations.summary}}
                {{.CommonAnnotations.description}}

                {{.CommonLabels}}

        - name: victorops_warning
          victorops_configs:
            - <<: *victorops
              routing_key: rkik-non-critical

        - name: slack_critical
          slack_configs:
            - &slack
              send_resolved: true
              api_url: <hidden>
              channel: '#prometheus'
              # FIXME {{.GeneratorURL}} doesn't work
              title_link: https://<some url>/#/alerts?receiver=slack
              color: '{{if eq .Status "firing"}}danger{{else}}good{{end}}'
              title: '{{.CommonAnnotations.summary}} - {{.Status}}'
              text: |
                {{.CommonAnnotations.description}}

                *Alert:* {{.CommonLabels.alertname}}
              fallback: Alert summary

        - name: slack_warning
          slack_configs:
            - <<: *slack
              color: '{{if eq .Status "firing"}}warning{{else}}good{{end}}'

        - name: slack_info
          slack_configs:
            - <<: *slack
              send_resolved: false
              color: '#a9a9a9'

        - name: fez
          webhook_configs:
            - url: http://<some url>

**Comment by fuzzyami** [comment]
We have two machines, and one is always on complete-silence (.+). One of them is constantly at 75~80% and the other is about 45% (normalized to the number of cores).

**Comment by fuzzyami** [comment]
@fabxc after experimenting with various configs, the culprit seems to be this:

>     group_by:
>      - cloud_zone
>      - node
>      - alertname
>      - service

^^ this alone is responsible for about 50% of the cpu usage.

**Comment by fabxc** [comment]
Still need to know what load is your Alertmanager experiencing? 10 alerts per second, 1000 per second, 10 million?

> We have two machines, and one is always on complete-silence (.+). One of them is constantly at 75~80% and the other is about 45% (normalized to the number of cores).

And which one is which?

> ^^ this alone is responsible for about 50% of the overall cpu usage.

A config section in itself can't really be responsible for any load. 50% with respect to what? Not grouping at all, just grouping by a single label?

**Comment by fuzzyami** [comment]
@fabxc - thanks for clarifying these. 
1. I'm not sure how to measure the number of alerts per second. Is this value exposed somehow?
2. the AM with the blanket silence is running at a constant load of about 50% (normalized to the number of cores). its about 30% less than the one without the silence.
3. I tried out a few group-by configurations on our silent machine. I tried without any groups and with an empty list ('[]') as well as everything except 'cloud_zone', and only 'cloud_zone'. there were exactly 2 kinds of loads:
- if cloud_zone was included, the load is about 225% (not normalized)
- if not, its about 115% (not normalized)
4. the effects were even more dramatic on the active machine: the load dropped from 330% to 130% simply by removing the 'cloud_zone' group-by (but keeping the rest).

**Comment by fuzzyami** [comment]
huh. it appears that a much more dramatic effect is achieved by tweaking the 'group_interval' fields. Seems that setting it to zero was not a good idea. when set to 10 secs, the cpu load is basically completely gone.

**Comment by fabxc** [comment]
Oh yes, that really is a bad idea (I just glanced over the config before, thanks for playing with the paramters). For performance but also from a semantical point of view.
Zero basically means Alertmanager is spinning internally for every group – as soon as an evaluation cycle is completed, the next one starts.
Certain labels just caused higher load as they spawned more groups.

In general you probably want to stick somewhere around 5-60s for `group_wait`, 60s-5mins for `group_interval`, and 3-24h for `repeat_interval`.

@brian-brazil @brancz opinions on just forbidding zero vs a sane minimum bound like 100ms?

**Comment by brian-brazil** [comment]
Sane minimum of 1s sounds good.

**Comment by brancz** [comment]
Yeah I think 1s is completely fine. Just out of UX I think we should add a log message saying that it has been overridden if a lower value was configured.

**Comment by fabxc** [comment]
Closing here as the issue was due to misconfiguration.
