### ISSUE TITLE
Enable some form of Slack notifications parsing

### ISSUE THREAD

**Issue by wuub** [prometheus/alertmanager#586]
Hi,

right now mentioning slack users or teams is pretty tedious as it has to be done with slack IDs. Think
`<!subteam^ID|team>`  or `<!@U12345|nickname>` instead of normal `@team` or `@nickname`.

This is because slack does not parse messages received from webhooks (default `parse=none`). 
I think `parse=full` is unnecessary, but adding `link_names=1` here https://github.com/prometheus/alertmanager/blob/2433eebf481029d6f4b68c1874618d4cbe1d8d3c/notify/impl.go#L465 should be helpful.

What do you think? Are there any reasons why this is not there or will you accept a simple PR? :)

**Comment by juliusv** [comment]
I think that makes sense. I only wonder whether it should be configurable (or always on), but probably configurable.

**Comment by zerthimon** [comment]
is this gonna be merged any time soon ?

**Comment by stuartnelson3** [comment]
Following up now, sorry for letting this slip

**Comment by KirillTemnov** [comment]
We have same issue, can you fix it?

**Comment by brian-brazil** [comment]
https://github.com/prometheus/alertmanager/pull/912 added this.

**Comment by PaulAnnekov** [comment]
Looks like nowadays `link_names: true` + mentioning like `@username` stopped working. I tried even `<@username>` - no luck, it just prints this text as is. The only solution is to use user id, like `<@USERID>`. You can find user id using this manual https://help.workast.com/hc/en-us/articles/360027461274-How-to-find-a-Slack-user-ID.
I think this change is related to the blog post https://api.slack.com/changelog/2017-09-the-one-about-usernames.
