### ISSUE TITLE
Configurating smtp_smarthost from a Template

### ISSUE THREAD

**Issue by gti303** [prometheus/alertmanager#588]
I am trying to configure Alert Manager such that any fields that may change from site to site will be in a template file. Currently it is not working for me.

**alertmanager.yml:**
```
global:
  smtp_smarthost: '{{ template "smtphost.text" . }}'
```

**AlertManagerConfigurations.tmpl:**
```
{{ define "smtphost.text" }}localhost:25{{ end }}
```

This gave me an error of: level=error msg="Notify for 1 alerts failed: dial tcp: missing port in address {{ template \"smtphost.text\" . }}

I then tried this:
**alertmanager.yml:**
```
global:
  smtp_smarthost: '{{ template "smtphost.text" . }}:{{ template "smtpport.text" . }}'
```

**AlertManagerConfigurations.tmpl:**
```
{{ define "smtphost.text" }}localhost{{ end }}
{{ define "smtpport.text" }}25{{ end }}
```

which gave the following error: 
> time="2016-12-22T15:37:32-08:00" level=error msg="Error on notify: dial tcp: lookup tcp/{{ template \"smtpport.text\" . }}: getaddrinfow: The specified class was not found." source="notify.go:272"

if i specify localhost:25 directly in alertmanager.yml I have no problems.

Any suggestions?

**Comment by brian-brazil** [comment]
The smarthost is not templatable. I'd suggest using your configuration management to adjust the config file if needed.

**Comment by gti303** [comment]
Thanks Brian.

I have 1 more question. Does the Alert Manager have any logging built in whereby I can verify if certain e-mails were successfully sent in the event of an alert being fired?

**Comment by brian-brazil** [comment]
There's no logging functionality of that nature yet.

**Comment by juliusv** [comment]
Closing as there's no intent to allow this.
