### ISSUE TITLE
webinterface not rendered / AssetInfo ui/... not found

### ISSUE THREAD

**Issue by aparcar** [prometheus/alertmanager#590]
I tried starting the alertmanager on debian testing with the newst release 0.5.1 but the webinterface only shows a static template without any functionality 

```
INFO[0000] Starting alertmanager (version=0.5.1, branch=master, revision=0ea1cac51e6a620ec09d053f0484b97932b5c902)  source=main.go:101
INFO[0000] Build context (go=go1.7.3, user=root@fb407787b8bf, date=20161125-08:14:40)  source=main.go:102
INFO[0000] Loading configuration file                    file=alertmanager.yml source=main.go:195
INFO[0000] Listening on :9093                            source=main.go:250
WARN[0006] Could not get file: AssetInfo ui/lib/jquery/jquery.min.js not found  source=web.go:31
WARN[0007] Could not get file: AssetInfo ui/lib/moment/moment.min.js not found  source=web.go:31
WARN[0007] Could not get file: AssetInfo ui/lib/angular.js/angular.min.js not found  source=web.go:31
WARN[0007] Could not get file: AssetInfo ui/lib/angular.js/angular-sanitize.min.js not found  source=web.go:31
WARN[0007] Could not get file: AssetInfo ui/lib/angular.js/angular-route.min.js not found  source=web.go:31
WARN[0007] Could not get file: AssetInfo ui/lib/angular.js/angular-resource.min.js not found  source=web.go:31
WARN[0007] Could not get file: AssetInfo ui/lib/angular.js/angular.min.js not found  source=web.go:31
WARN[0007] Could not get file: AssetInfo ui/lib/angular.js/angular-sanitize.min.js not found  source=web.go:31
WARN[0008] Could not get file: AssetInfo ui/lib/angular.js/angular-route.min.js not found  source=web.go:31
WARN[0008] Could not get file: AssetInfo ui/lib/angular.js/angular-resource.min.js not found  source=web.go:31
```

the `WARN` messages arrive as soon as I open the web interface on port 9093

**Comment by TheTincho** [comment]
Hi @aparcar,

Seeing the version line from your logs, I don't think you are using the Debian version. Yours reads:

```
INFO[0000] Starting alertmanager (version=0.5.1, branch=master, revision=0ea1cac51e6a620ec09d053f0484b97932b5c902)  source=main.go:101
INFO[0000] Build context (go=go1.7.3, user=root@fb407787b8bf, date=20161125-08:14:40)  source=main.go:102
```

And the version in testing:

```
time="2017-01-02T19:18:09Z" level=info msg="Starting alertmanager (version=0.5.1+ds, branch=debian/sid, revision=0.5.1+ds-3)" source="main.go:102" 
time="2017-01-02T19:18:09Z" level=info msg="Build context (go=go1.7.4, user=pkg-go-maintainers@lists.alioth.debian.org, date=20161213-09:37:48)" source="main.go:103" 
```

In any case, somehow you must be using some of the Debian patches that change the way the static assets are handled. Can you double check your environment to make sure you are using the debian package and binary?

Finally, for Debian versions, it would be better if you use the Debian bug tracker (you can submit bugs using the reportbug CLI tool).

**Comment by aparcar** [comment]
Hi @TheTincho, 
I tried the Debian version causing the same problem but without showing the error messages. 
Switching to the official release let me see the Error messages - no rendering.

![alertmanager_5 1](https://cloud.githubusercontent.com/assets/16000931/21597723/9785baec-d14f-11e6-84fb-3c1a26ef1401.png)

If you think the problem is just due to using Debian I'll use the reportbug tool.

**Comment by TheTincho** [comment]
@aparcar,

Let's try to solve one issue at a time :-) Using only the Debian version, can you tell me the full command line the alertmanager is running with? (from ps axw) Could you also paste the log?

If you can, it'd be helpful if you check with your browser which URLs are failing to load, and with which error.

**Comment by aparcar** [comment]
I killed the allertmanager (`killall prometheus-alertmanager`) and I worked for about 2 Minutes. Now it stays static again as seen above.

`<ip>:9093/lib/angular-moment.min.js` fails to load

`ps axw`

    768 ?        Ssl    0:00 /usr/bin/prometheus-alertmanager

`cat /etc/default/prometheus-alertmanager | grep ARGS`

    ARGS=""

`ls /usr/share/prometheus/alertmanager/`

    default.tmpl  ui

`journcalctl -u prometheus-alertmanager -f`

```
-- Logs begin at Di 2017-01-03 18:59:51 CET. --
Jan 03 19:01:09 monitoring systemd[1]: Starting Alertmanager for prometheus...
Jan 03 19:01:09 monitoring systemd[1]: Started Alertmanager for prometheus.
Jan 03 19:01:09 monitoring prometheus-alertmanager[768]: time="2017-01-03T19:01:09+01:00" level=info msg="Starting alertmanager (version=0.5.1+ds, branch=debian/sid, revision=0.5.1+ds-3)" source="main.go:102"
Jan 03 19:01:09 monitoring prometheus-alertmanager[768]: time="2017-01-03T19:01:09+01:00" level=info msg="Build context (go=go1.7.4, user=pkg-go-maintainers@lists.alioth.debian.org, date=20161213-09:37:48)" source="main.go:103"
Jan 03 19:01:09 monitoring prometheus-alertmanager[768]: time="2017-01-03T19:01:09+01:00" level=info msg="Loading configuration file" file="/etc/prometheus/alertmanager.yml" source="main.go:196"
Jan 03 19:01:09 monitoring prometheus-alertmanager[768]: time="2017-01-03T19:01:09+01:00" level=info msg="Listening on :9093" source="main.go:251"
```

**Comment by TheTincho** [comment]
Ah, this makes more sense now!

You are right, there is a bug in the package. I failed to notice it, because somehow a file named angular-moment.min.js was left lingering in the right path in my test environment. I will fix and upload ASAP.

**Comment by aparcar** [comment]
Great, thanks for the support

**Comment by TheTincho** [comment]
I uploaded a fix for this. Should be hitting the mirrors soon.
