### ISSUE TITLE
postfix not working with Prometheus

### ISSUE THREAD

**Issue by lol1203** [prometheus/alertmanager#592]
Prometheus is configured
Alertmanager is working .
Postfix is installed.
but an alert does not trigger an email sent to recipient.
/var/log/maillog shows the following : ( xxx.xxx.xxx.xxx = prometheus IP address )

prometheus postfix/smtpd[18082]: connect from prometheus.koiconsults.com[ xxx.xxx.xxx.xxx]
 prometheus postfix/smtpd[18082]: smtp_stream_setup: maxtime=300 enable_deadline=0
 prometheus postfix/smtpd[18082]: match_hostname: prometheus.koiconsults.com ~? 127.0.0.0/8
 prometheus postfix/smtpd[18082]: match_hostaddr:  xxx.xxx.xxx.xxx ~? 127.0.0.0/8
 prometheus postfix/smtpd[18082]: match_hostname: prometheus.koiconsults.com ~? 192.168.150.0/24
 prometheus postfix/smtpd[18082]: match_hostaddr:  xxx.xxx.xxx.xxx ~? 192.168.150.0/24
 prometheus postfix/smtpd[18082]: > prometheus.koiconsults.com[ xxx.xxx.xxx.xxx]: 220 prometheus ESMTP Postfix
 prometheus postfix/smtpd[18082]: watchdog_pat: 0x7ff9c22a7f70
 prometheus postfix/smtpd[18082]: vstream_fflush_some: fd 10 flush 30
 prometheus postfix/smtpd[18082]: vstream_buf_get_ready: fd 10 got 16
 prometheus postfix/smtpd[18082]: < prometheus.koiconsults.com[ xxx.xxx.xxx.xxx]: EHLO localhost
 prometheus postfix/smtpd[18082]: match_list_match: prometheus.koiconsults.com: no match
 prometheus postfix/smtpd[18082]: match_list_match:  xxx.xxx.xxx.xxx: no match
 prometheus postfix/smtpd[18082]: > prometheus.koiconsults.com[ xxx.xxx.xxx.xxx]: 250-prometheus
 prometheus postfix/smtpd[18082]: > prometheus.koiconsults.com[ xxx.xxx.xxx.xxx]: 250-PIPELINING
 prometheus postfix/smtpd[18082]: > prometheus.koiconsults.com[ xxx.xxx.xxx.xxx]: 250-SIZE 10240000
 prometheus postfix/smtpd[18082]: > prometheus.koiconsults.com[ xxx.xxx.xxx.xxx]: 250-VRFY
 prometheus postfix/smtpd[18082]: > prometheus.koiconsults.com[ xxx.xxx.xxx.xxx]: 250-ETRN
 prometheus postfix/smtpd[18082]: > prometheus.koiconsults.com[ xxx.xxx.xxx.xxx]: 250-ENHANCEDSTATUSCODES
 prometheus postfix/smtpd[18082]: > prometheus.koiconsults.com[ xxx.xxx.xxx.xxx]: 250-8BITMIME
 prometheus postfix/smtpd[18082]: > prometheus.koiconsults.com[ xxx.xxx.xxx.xxx]: 250 DSN
 prometheus postfix/smtpd[18082]: watchdog_pat: 0x7ff9c22a7f70
 prometheus postfix/smtpd[18082]: vstream_fflush_some: fd 10 flush 119
 prometheus postfix/smtpd[18082]: vstream_buf_get_ready: fd 10 got 6
 prometheus postfix/smtpd[18082]: < prometheus.koiconsults.com[ xxx.xxx.xxx.xxx]: QUIT
 prometheus postfix/smtpd[18082]: > prometheus.koiconsults.com[ xxx.xxx.xxx.xxx]: 221 2.0.0 Bye
 prometheus postfix/smtpd[18082]: match_hostname: prometheus.koiconsults.com ~? 127.0.0.0/8
 prometheus postfix/smtpd[18082]: match_hostaddr:  xxx.xxx.xxx.xxx ~? 127.0.0.0/8
 prometheus postfix/smtpd[18082]: match_hostname: prometheus.koiconsults.com ~? 192.168.150.0/24
 prometheus postfix/smtpd[18082]: match_hostaddr:  xxx.xxx.xxx.xxx ~? 192.168.150.0/24
 prometheus postfix/smtpd[18082]: disconnect from prometheus.koiconsults.com[ xxx.xxx.xxx.xxx]

any idea what could be wrong ?

**Comment by matthiasr** [comment]
Does Alertmanager log anything?
