### ISSUE TITLE
Sorting allerts when sending out notifications

### ISSUE THREAD

**Issue by ddewaele** [prometheus/alertmanager#597]
Is it possible that the alerts that are sent out via the notifiers don't have any guaranteed ordering on the alerts (startsAt) ?

If not, is it possible to have some kind of sorting in the email templates ? (oldest first ?).
```
{{ range .Alerts.Firing }}
```

I had the impression that they were sorted since 0.5.1, but noticed today that I received some emails with alerts out of order

- Alert1 in list startsAt Dec 31, 2016 18:38:37 UTC 
- Alert2 in list startsAt Jan 04, 2017 10:09:52 UTC 
- Alert3 in list startsAt Jan 04, 2017 08:00:37 UTC 

As we have a timestamp (startsAt) I guess the clients (UIs / email templates / ....) can do the sorting.
If you could give me a tip on how to sort in the email template I'd be happy to do a PR but so have haven't succeeded. I tried using the sort function but it wasn't available in the email template.

**Comment by ddewaele** [comment]
According to http://stackoverflow.com/questions/41505689/sorting-alertmanager-email-templates-in-go-templating/41506321?noredirect=1#comment70221423_41506321 it's not possible to do it the go template and it would require a code change in the alertmanager.

@fabxc any thoughts on this ? ideally alertmanager would send out the alerts with some guaranteed ordering (newest first or oldest first). (currently not the case I think and the order is not guaranteed).

**Comment by ddewaele** [comment]
Also noticed that alerts are not sorted in the Alertmanager UI and in the REST API.

We group alerts on labels and our operators get an individual email with up to 10 alerts fired in them.

It makes it very difficult for them to see what triggered the incoming email (as he needs to go through all the alerts and find the most recent startsAt).

**Comment by brian-brazil** [comment]
> It makes it very difficult for them to see what triggered the incoming email (as he needs to go through all the alerts and find the most recent startsAt).

You should be caring about all alerts. If you're ignoring some alerts in a notification either you need silences or to delete those alerts.

**Comment by ddewaele** [comment]
Fair enough, I realise that educating users is important and we need to put more focus on that, but there might also be some value in always sorting them in some consistent way.

These are just some requirements we get from customers. Every time I refresh the alert overview screen to do the silencing I get a different sorting of the alerts. 

I was just wondering if this was by design (from an alertmanager perspective the order of alerts having zero importance), or if you see some benefit in having them sorted in some consistent way (in UI / REST / email / .....).

**Comment by brian-brazil** [comment]
We never got around to adding an ordering.

**Comment by ddewaele** [comment]
No worries ... Feel free to keep this open if you see value in this.

I also think it's due to the fact that alertmanager generating too many emails at the moment (https://github.com/prometheus/alertmanager/issues/598), that operators are looking for a way to get more clarity into the system. 

Just did an analysis of what was sent out over a period of 4 hours, and from the 18 mails sent out , only 6 of them were dealing with new alerts (the rest were showing alerts that were still active (firing) , or alerts that got resolved by themselves)

**Comment by brian-brazil** [comment]
> (the rest were showing alerts that were still active (firing) , or alerts that got resolved by themselves)

This is a matter of practices. The former should have been silenced, and the latter alerts likely need tuning.

**Comment by brian-brazil** [comment]
There is now an ordering based on the labels.

**Comment by tiagoapimenta** [comment]
@brian-brazil  Could you please do something like that?
https://gist.github.com/tiagoapimenta/3ecb4162e701252f4b1041bc7f9315e9
I did not manage to make it pass the unit tests, maybe you could.
