### ISSUE TITLE
Set require_tls to false for localhost

### ISSUE THREAD

**Issue by jsha** [prometheus/alertmanager#613]
The configuration options for sending email seem to have good defaults for a remote smarthost with a username and password, where TLS should be required.

However, another common mail config is to have an MTA like Postfix configured on localhost that will relay mail from localhost. With the default require_tls setting, if you set smtp_smarthost to `localhost:25`, you will get errors because localhost typically does not have a validating cert.

I propose to make require_tls default to false when the host portion of smtp_smarthost is `localhost` (or `127.0.0.1`). What do you think?

**Comment by sgissi** [comment]
I understand the use case but I would recommend against it:

- It can be easily achieved with either a global or per receiver configuration depending on the environment
- It makes the behavior less obvious (change of smarthost leading to a change in TLS setting)
- Detecting localhost can be troublesome (e.g. Should TLS be disabled if the target IP is directly assigned to a local interface? Should 127.0.0.2 be treated like localhost?)

**Comment by brian-brazil** [comment]
I don't think we'll be changing this as it'd add complication, and we try to be secure by default where possible.

**Comment by mxinden** [comment]
Closing here. @jsha feel free to reopen if you want to further discuss this.
