### ISSUE TITLE
Update silences in api

### ISSUE THREAD

**Issue by RSamal** [prometheus/alertmanager#614]
The update is possible through UI.However, I don't see a API for it. Is there a way to update silence through api call?

**Comment by brancz** [comment]
The web UI of the Alertmanager is entirely built around its API, so for everything you can do in the UI there is an API endpoint. Having that said, there is currently no stability guarantee for this API, it may change in any new version, however, there are plans to release a cli alongside with Alertmanager to interact with it's API. See [this issue](https://github.com/prometheus/alertmanager/issues/567) for tracking.

**Comment by RSamal** [comment]
that sounds good. I am not a UI person so getting little confused with code here. Does it delete the original silence and create a new one, each time we edit it?

**Comment by brancz** [comment]
That is correct, it's an important characteristic for the underlying gossip protocol.

**Comment by RSamal** [comment]
Thank You Frederic

**Comment by brancz** [comment]
Your welcome! 🙂

**Comment by RSamal** [comment]
By the way, I have a very generic question on inhibitor. I remember a
thread going on to make inhibitor to route specific than a global. Is that
has been accomplished yet?

Also, I see inhibited alerts do not refire once the source alerts get
cleared just like the way it works in case silencer.


On Thu, Jan 26, 2017 at 8:12 AM, Frederic Branczyk <notifications@github.com
