### ISSUE TITLE
Unable to delete silence created for future time

### ISSUE THREAD

**Issue by RSamal** [prometheus/alertmanager#616]
While deleting a silence which got created for future time, I am getting below error
ERRO[0463] api error: bad_data: end time must not be before start time  source=api.go:552

How do I delete a silence which is in pending status?

**Comment by RSamal** [comment]
The below code fixed the issue 

`if protoBefore(now, sil.StartsAt) {
		sil.StartsAt = now
	}`

`func (s *Silences) Expire(id string) error {
	s.mtx.Lock()
	defer s.mtx.Unlock()

	sil, ok := s.getSilence(id)
	if !ok {
		return ErrNotFound
	}

	now, err := s.nowProto()
	if err != nil {
		return err
	}
	if protoBefore(now, sil.StartsAt) {
		sil.StartsAt = now
	}
	if sil, err = silenceSetTimeRange(sil, now, sil.StartsAt, now); err != nil {
		return err
	}
	return s.setSilence(sil)
}`

**Comment by RSamal** [comment]
This issue has been taken care with the recent version.

**Comment by iksaif** [comment]
@kamaradclimber can you confirm that the 2.0.0 preview doesn't have this bug ? I think you were able to reproduce it

**Comment by RSamal** [comment]
It got fixed with the latest master branch. [https://github.com/prometheus/alertmanager/commit/08be6a4149cb512d9f91ab942eacfdc049c6fc10](url) Not sure the version you are referring.

**Comment by iksaif** [comment]
You're right, https://github.com/prometheus/alertmanager/commit/08be6a4149cb512d9f91ab942eacfdc049c6fc10 isn't in https://github.com/prometheus/alertmanager/releases/tag/v0.7.0-rc.0. Thanks !

**Comment by RSamal** [comment]
Hey Corentin, By the way, I just noticed V0.7.0  has this fix now.

**Comment by wdp-007** [comment]
Hi,
when I delete a silence through the api, it failed as deleted Method Not Allowed
here is the ruby code:
uri = URI('http://localhost:9093/api/v1/silences/9b6bc1e4-b798-4e48-a729-6ab2cf7062f0')
http = Net::HTTP.new(uri.host, uri.port)
req = Net::HTTP::Delete.new(uri.path)
res = http.request(req)
puts "deleted #{res.body}"

Result is : deleted Method Not Allowed

**Comment by RSamal** [comment]
I am not familiar with ruby , but can please try `curl -X DELETE http://localhost:9093/api/v1/silences/9b6bc1e4-b798-4e48-a729-6ab2cf7062f0` and see if it is successful.  as I am not familiar with ruby I am confused with `http = Net::HTTP.new(uri.host, uri.port)` . Your uri already has the host and port included 'http://localhost:9093'. What will happen when you define like this?

**Comment by wdp-007** [comment]
Thanks a lot!
I am too careless!
