### ISSUE TITLE
Equality check of label in LABELS

### ISSUE THREAD

**Issue by matthughes** [prometheus/alertmanager#618]
I'm trying to do the following: 

```
ALERT TestAlert
  IF up == 1
  LABELS {
    destination = "test",
    severity = "{{ if eq $labels.region 'east_coast'}}high{{else}}low{{end}}",
    count = "{{ $value }}",
    region_exists = "{{$labels.region}}",
  }
```

The alert fires.  The `region_exists` label is populated proving that `$labels.region` exists.  However, the equality check fails with:

```
severity="<error expanding template: runtime error: invalid memory address or nil pointer dereference>"
```

Could you kindly point me in the right direction regarding syntax?

**Comment by sgissi** [comment]
'east_coast' should be either in double-quotes ("east_coast") and properly
escaped, or with backticks (`east_coast`). As far as I tried, simple quotes
aren't valid in templates: https://play.golang.org/p/nZ98d9k-fJ

2017-01-27 12:27 GMT-07:00 Matt Hughes <notifications@github.com>:

**Comment by fabxc** [comment]
Closing as I assume the quoting should indeed be the issue.

**Comment by ashoksahoo** [comment]
This is my template.
```
ALERT MongoTooManyPageFaults
  IF rate(mongodb_extra_info_page_faults_total[5m]) > 500
  FOR 10m
  LABELS { service = "mongo", severity = "page" }
  ANNOTATIONS {
    summary = "http://<redacted>/alerts",
    description = "Page faults threshold in MongoDB {{$label.instance}} ",
  }

```
This is what I get in my email alerts.
Labels
alertname = MongoTooManyPageFaults
instance = 12.0.22.180:9001
job = mongo
service = mongo
severity = page
Annotations
description = <error expanding template: runtime error: invalid memory address or nil pointer dereference>
