### ISSUE TITLE
OpsGenie api_key should be template-expanded

### ISSUE THREAD

**Issue by aecolley** [prometheus/alertmanager#619]
The PagerDuty service key is template-expanded inside Notify, which is useful for keeping access keys out of the config repository. Please do the same for OpsGenie.

**Comment by linkinpark342** [comment]
The HipChat [https://github.com/prometheus/alertmanager/blob/v0.5.1/notify/impl.go#L681](implementation) is similarly in need of this:

**Comment by mxinden** [comment]
@aecolley Is this still relevant? If so, would you mind creating a PR for this?

**Comment by brian-brazil** [comment]
> which is useful for keeping access keys out of the config repository

They need to go in the configuration one way or the other, templating doesn't help that.

**Comment by linkinpark342** [comment]
Templating helps in that, with it, you can check in your prometheus configuration for all to see, but have your keys managed elsewhere (ansible-vault or some such). I think this is still relevant for the product, especially for consistency as it looks like the PagerDuty integration has it. However our org (both aecolley and myself) gave up on opsgenie so we're probably not going to spend too much time on this :P. Though did referenced commit #1081 take care of this already?

**Comment by brian-brazil** [comment]
> You can check in your prometheus configuration for all to see, but have your keys managed elsewhere (ansible-vault or some such).

If you're using ansible, then you can pull the secret out of vault with the `template` module. This is the sort of solution that would be recommended.

The pagerduty service keys are templatable because they are usable for routing. The OpsGenie api_key is not.
