### ISSUE TITLE
Multiple or more granular repeat_interval for different recievers?

### ISSUE THREAD

**Issue by gti303** [prometheus/alertmanager#620]
It appears repeat_interval is global? 

Can I specify certain receivers to have a different repeat_interval.

ie. I'd want e-mail alerts to only go out once every 24hrs, but I want my custom receiver to receive the raised alert every 10 minutes

**Comment by brian-brazil** [comment]
It's per receiver, and inherited if not set.

**Comment by gti303** [comment]
Thanks Brian! Works great


________________________________
