### ISSUE TITLE
trying to activate a single alert if multiple conditions are true for different datapoints

### ISSUE THREAD

**Issue by audynespinoza** [prometheus/alertmanager#629]
its seems to me that prometheus is unable to perform the logic where it checks the status on multiple different datapoints in order to trigger a single alert
for example:
i am monitoring a series of network devices.  Each network device has multiple synthetic pings (ip sla's) going to different destinations.  When prometheus pulls this data, i get results back telling me certain ip sla's are up (value==1) or down(value==0).  this works great. no problem here.

here are 3 slas as an example showing pings are all up b/c the value is 1:
ipSlaUpStatus{rttMonCtrlAdminLongTag="'from_router_to_server1'"} 1
ipSlaUpStatus{rttMonCtrlAdminLongTag="'from_router_to_server2"} 1
ipSlaUpStatus{rttMonCtrlAdminLongTag="'from_router_to_server3'"} 1
these are 3 seperate endpoints.

now i would like to be able to define alert rules that perform the following logic where only one is down but the other two are up:
IF
ipSlaUpStatus{rttMonCtrlAdminLongTag="'from_router_to_server1'"} == 1
AND
ipSlaUpStatus{rttMonCtrlAdminLongTag="'from_router_to_server2"} == 1
AND
ipSlaUpStatus{rttMonCtrlAdminLongTag="'from_router_to_server3'"} == 0

this does not work.  it seems prometheus is expecting these conditions to be true on only "one" datapoint.  It doesn't check other datapoints that could meet these conditions.

in a way it makes sense, b/c what im asking for it to do is almost similar to a nested IF structure such as the following:
1. check all datapoints until a match is found
IF ipSlaUpStatus{rttMonCtrlAdminLongTag="'from_router_to_server1'"} == 1
     2. check all datapoints until a match is found
      IF ipSlaUpStatus{rttMonCtrlAdminLongTag="'from_router_to_server2"} == 1
            3. check all datapoints until a match is found
            ipSlaUpStatus{rttMonCtrlAdminLongTag="'from_router_to_server3'"} == 0
                     If all of these IF conditions are "true", then send an alert.

this way it checks for 3 "seperate" datapoints instead of trying to qualify all of these conditions as true for only "one" device.

this is the alert rule that im using:
ALERT SERVER3_DOWN
  IF
    ipSlaUpStatus{rttMonCtrlAdminLongTag="'from_router_to_server1'"} == 1
  AND
    ipSlaUpStatus{rttMonCtrlAdminLongTag="'from_router_to_server2"} == 1
  AND
    ipSlaUpStatus{rttMonCtrlAdminLongTag="'from_router_to_server3'"} == 0
  FOR 1m
  LABELS { severity = "critical" }
  ANNOTATIONS {
    summary = "Server 3 has gone down but not Server 1 & 2",
    description = "Server 3 has gone down but not Server 1 & 2.  we are determining cause for failure",
  }

Is there something i'm doing wrong? or is it just simply true that prometheus cannot match in this fashion?

**Comment by stuartnelson3** [comment]
Taking a step back, I'm sort of confused at the purpose of this alert (why not just alert if any of the sla's are down?), as this is something handled by prometheus proper, this issue should be moved there.
