### ISSUE TITLE
Alertmanager is not sending resolved notification for single service

### ISSUE THREAD

**Issue by Priyanka098** [prometheus/alertmanager#630]
I have setup prometheus and alertmanager for kubernetes cluster.

When any service is down, alertmanager sends "firing" notification to respective channel but does not send notification when that alert resolves.

This happens only for single service, if there are multiple services(in firing/resolved state) then it sends notifications in one mail as expected.

Alertmanager config is

    route:
       group_by: []
       group_wait: 30s
       group_interval: 5m
       receiver: alert-team
    receivers:
     - name: 'alert-team'
       email_configs:
       - to: 'xyz@xyz.com'
       slack_configs:
       - channel: '#alerts'

If i add send_resolved: true in receivers configuration then it send multiple resolved notification

**Comment by stuartnelson3** [comment]
The configuration you added does not have `send_resolved: true` for the email or slack configs section. The default behavior for email and slack is not to send a resolved notification.

If you check the documentation, different receivers have different default values for `send_resolved`.

https://prometheus.io/docs/alerting/configuration/

**Comment by Priyanka098** [comment]
Alertmanager send resolved alert even if send_resolved: true is not added in configuration, that means it is false
eq. if 2 node memory alerts are in firing state and one of these resolves then i receive notification with one resolve and one with firing state in one email but if one alert is in firing state and if it resolves then no alerts.

This behavior is bit strange

**Comment by stuartnelson3** [comment]
I'll have to run it by @fabxc or @brancz to see if that's the desired behavior.

**Comment by brian-brazil** [comment]
That's not the desired behaviour, there should be a resolved notification when they all resolve and send_resolves is true.

**Comment by Mrcortez34** [comment]
Was this type of behavior resolved?

**Comment by mxinden** [comment]
I will close here. Feel free to reopen in case you feel like this should still be up for discussion.
