### ISSUE TITLE
Kubernetes proxy and missing alerts

### ISSUE THREAD

**Issue by craigwillis85** [prometheus/alertmanager#632]
I'm using Prometheus with Kubernetes (with proxy - so it isn't exposed).

The problem seems to be that Prometheus isn't triggering the alerts in its UI

I have to access my kubernetes services via a proxy, so, i access prometheus using the following on my local machine:

    http://127.0.0.1:8001/api/v1/proxy/namespaces/default/services/prometheus

I have the following configuration in my prometheus deployment

        args:
          - '-storage.local.retention=24h'
          - '-storage.local.memory-chunks=500000'
          - '-config.file=/etc/prometheus/prometheus.yml'
          - '-web.external-url=http://127.0.0.1:8001/api/v1/proxy/namespaces/default/services/prometheus'
          - '-web.route-prefix=/'
          - '-alertmanager.url=http://127.0.0.1:8001/api/v1/proxy/namespaces/default/services/alertmanager'

Is there any more config i need to add, either to prometheus or alertmanager to get my alerts being populated in the alertmanager UI

**Comment by craigwillis85** [comment]
fixed, had to use the kubernetes service IP of the alertmanager for `alertmanager.url`

**Comment by brancz** [comment]
@craigwillis85 note that if you have multiple instances of Alertmanager you want to specify each individual instance when running Prometheus (not load balanced). It is part of the HA model/contract between Prometheus and Alertmanager.
