### ISSUE TITLE
send_resolved does nothing on Pagerduty receiver

### ISSUE THREAD

**Issue by threemachines** [prometheus/alertmanager#635]
Per the [Pagerduty receiver docs](https://prometheus.io/docs/alerting/configuration/#pagerduty-receiver-pagerduty_config), we have our configured with `send_resolved: true`.

Experimentally, it doesn't seem to do anything. I manually stopped a service in a way that would trigger a pagerduty alert from the alertmanager, and after the alert fired and I got the page, I restored the service and watched the alert clear from Prometheus and the Alertmanager. The Pagerduty incident neither changed nor recorded having received any additional input.

I would have expected `send_resolved` to put the incident in the "resolved" state.

(h/t to @stapelberg's Pushover feature request for reminding me to verify this behavior)

**Comment by stuartnelson3** [comment]
`send_resolved: true` is the default state for the PagerDuty receiver:

https://prometheus.io/docs/alerting/configuration/#pagerduty-receiver-pagerduty_config

To confirm: An alert ceases firing in your Prometheus, so it no longer appears in Alertmanager, but the alert in PagerDuty is not being automatically resolved?

**Comment by threemachines** [comment]
Correct.

**Comment by stuartnelson3** [comment]
Can you provide some additional information about your setup? Version, OS, if you're using one of our binaries or one you compiled yourself, etc.

Also, have you checked the logs to confirm whether or not Alertmanager is attempting to send a request to PagerDuty to resolve? I'm wondering if Alertmanager is sending an incorrect resolved message, or if it's not sending one, or what.

**Comment by threemachines** [comment]
Sure. We're using the 0.5.0.linux-amd64 release from the Github releases, Ubuntu 14.04. The pagerduty config is the only endpoint on that receiver, and it's just the service key and the send_resolved, so nothing too fancy.

I'll try to find some time to check the logs later. I can tell you that Pagerduty has a little history of all the activity it has on an alert, and it only showed the initial notification from Alertmanager.

Thanks!

**Comment by stuartnelson3** [comment]
Sure thing. Have you tried the `0.5.1` release?

**Comment by threemachines** [comment]
We just upgraded to it, I'll try my manual reproduction again when I can carve out some time for it.

**Comment by threemachines** [comment]
We had a production issue yesterday that happened to confirm correct resolution behavior via the Pagerduty API. Not sure if 0.5.1 fixed it or if there was something wrong in my original manual test.

**Comment by bernielomax** [comment]
I am experiencing the same issue on 0.5.1 for the Opsgenie receiver.

**Comment by phlegx** [comment]
Actually I still experience this behavior with Pagerduty and Alertmanager `v0.15.3`. According to the documentation the `send_resolved` is set to `true` by default. I tried addding it but that does not work. The alert on pagerduty however gets not resolved after my endpoint is online again.

**Comment by h35gao** [comment]
We are still experiencing this with PD and Alertmanager `v0.18.0. The alerts no longer appear in Alertmanager, but the incidents in PD don't get auto-resolved

**Comment by RyanSiu1995** [comment]
We have experienced the same situation with `v0.21.0`. Alert resolution does not resolve the incidents in PD.
We need to resolve the incidents in PD every time.

**Comment by beorn7** [comment]
Maybe the alerts were silenced or inhibited while they resolved? See #226.

**Comment by RyanSiu1995** [comment]
We didn't do any silencing or inhibiting action during the incident 🤔

**Comment by florianbeer** [comment]
Same problem here for resolution of resolved alerts with Opsgenie (Alertmanager v0.21.0). They just never get resolved in Opsgenie when they stop firing in Alertmanager.

I've created a separate [issue](https://github.com/prometheus/alertmanager/issues/2616) for that before finding this one.

**Comment by devopsrupeek** [comment]
Any update on this issue ?

**Comment by vyshakrupeek** [comment]
Any update on this issue?

**Comment by davejhahn** [comment]
Running into this issue.   Issue is resolved when looking in alerts but no resolution sent to PagerDuty.    Multiple alert types.

**Comment by klaus993** [comment]
still running into this issue
