### ISSUE TITLE
Silence alarms that are not active at the time you want to silence it

### ISSUE THREAD

**Issue by ddewaele** [prometheus/alertmanager#637]
Imagine a scenario where you have a flapping alarm that happens multiple times a day and you want to silence it. But every time you visit the alertmanager UI the alarm isn't active anymore, so there's no way to silence it.

How should we go about this ? Is it possible to silence such a flapping alarm without it bing active at the time you want to silence it ?

**Comment by stuartnelson3** [comment]
You can create a new silence with labels to match your flapping alert; no alert needs to be currently active to create a silence.

Select the "New Silence" button on the Silences page.
