### ISSUE TITLE
is there a way to define a rule which name contains operators

### ISSUE THREAD

**Issue by tailnode** [prometheus/alertmanager#643]
is there a way to define a rule which name contains operators, like:
```
ALERT cluster-ID:namespace:service-name:extrainfo
  IF go_goroutines > 1 
```
i want separate the alertname by colon(:), and there are dashes in cluster-ID and service-name.
thanks!

**Comment by stuartnelson3** [comment]
Alert rule parsing takes place in prometheus, this question should be moved to the prometheus-users email group.

**Comment by matthiasr** [comment]
No, the alert name is an identifier. it is meant to identify the rule, not the individual alert. You can and should use LABELS and ANNOTATIONS to transport information like cluster ID, namespace, service name and any extra info. This is much more flexible than pasting together strings and then parsing them again.
