### ISSUE TITLE
[Feature Request] Add zabbix receiver

### ISSUE THREAD

**Issue by bradbeam** [prometheus/alertmanager#647]
Wanted to get some discussion going around adding support for a Zabbix receiver. 

We're wanting to use all the goodness that Prometheus can offer, but our operations center is still based on Zabbix. I'd like to propose adding in a Zabbix receiver to Prometheus so that it could natively send events to Zabbix.

My initial thoughts/implementation:
- the Prometheus alert name could be used as the item key in Zabbix
- the value would be a 0 ( resolved ) or 1 ( firing ) based on the alert status
- data would be sent to zabbix as a zabbix sender/trapper item

**Comment by brian-brazil** [comment]
This is probably best implemented as a webhook, Zabbix is not a notification mechanism.
