### ISSUE TITLE
How to use attachments in Slack notifier

### ISSUE THREAD

**Issue by dewey** [prometheus/alertmanager#650]
Hey,

I'm trying to piece together how the alert templating works as the documentation is a bit sparse (#359) in that area. I figured out how to do most things I need work but I can't find a way to use the Slack Attachments. I see it's implemented in the Alertmanager but I can't figure out how to use it in templates.

Any hints on how to do that or is this currently not possible?

**Comment by juliusv** [comment]
Reading the code suggests that it is currently not possible to create your own completely custom attachments. The one attachment that is created is constructed from other fields you supply in the config: https://github.com/prometheus/alertmanager/blob/master/notify/impl.go#L500-L508

**Comment by dewey** [comment]
Thank you, should we close this issue or should it be marked as a feature request?

I think it'd definitely be great to have as it allows to structure the alerts in a better way (in addition to: https://github.com/prometheus/alertmanager/pull/649)

**Comment by stuartnelson3** [comment]
Seems like a reasonable feature request. Could you write up a description with relevant links in a new issue?

**Comment by dewey** [comment]
@stuartnelson3 Done in #654, let me know if there's anything missing.
