### ISSUE TITLE
Dynamic urls in Alertmanager webhooks

### ISSUE THREAD

**Issue by alfredfrancis** [prometheus/alertmanager#652]
How can i use template inside custom webhook urls ?

I tried following but the templating is not getting processed.

    - name: 'jenkins'
      webhook_configs:
         - send_resolved: false
           url: "http://xxx.xxx.xxx.xxx/job/{{ .Labels.jobname }}/buildWithParameters?server={{ .Labels.instance }}&token=devopsforprom"

any help is appreciated

**Comment by stuartnelson3** [comment]
This question should be directed to the [prometheus users mailing list](https://groups.google.com/forum/#!forum/prometheus-users).

**Comment by andreyev** [comment]
I've done something like this with https://wiki.jenkins.io/display/JENKINS/Generic+Webhook+Trigger+Plugin. Ping me if need more info!

Hope this helps!

**Comment by prateekniet** [comment]
HI Andreyev, 
Can you please explain in details , i want to invoke jenkins jobs along with parameter passed from alertmanager
