### ISSUE TITLE
Architecture picture can have a better Font?

### ISSUE THREAD

**Issue by zgfh** [prometheus/alertmanager#657]
sorry, I can not read the lots of words in Architecture(https://github.com/prometheus/alertmanager/blob/master/doc/arch.jpg).
I think the font of prometheus will be better.(https://github.com/prometheus/prometheus/blob/master/documentation/images/architecture.svg)

Can we attach  a more explicit picture or something like that?

**Comment by fabxc** [comment]
I actually drew this image by hand – so that will be hard to change without just creating a new one :)

**Comment by zgfh** [comment]
I would like to help to draw a new image  if I could see it clearly .
And I found there is a good tool for it, here is the link: https://www.processon.com/ 
Hope this can help you .

**Comment by metalmatze** [comment]
I'd suggest StarUML for that kind of things, because you can easily export everything as json. Maybe even put into this repository.

**Comment by alex-lx** [comment]
Any progress now? It would be very helpful for someone who is not good at recognizing hand-writing like me.

**Comment by mxinden** [comment]
@alex-lx @zgfh Would you mind doing a first draft of whatever you can read. I will do the rest then.

> I'd suggest StarUML for that kind of things, because you can easily export everything as json. Maybe even put into this repository.

@metalmatze Great idea!
