### ISSUE TITLE
Email Notification not working behind firewall

### ISSUE THREAD

**Issue by rahul-rs-srivastava** [prometheus/alertmanager#658]
Hi,

The alertmanager email notification to a gmail a/c is not working when run behind a firewall, even with the http_proxy set. However, the same config works perfectly fine when run outside the firewall. I also tried to configure to use the SMTP server on port 465, but that doesn't works either. Any help is appreciated.

Set the proxy
[[
export http_proxy=http://myproxy:80
export https_proxy=http://myproxy:80
]]

AlertManager Config:
<pre>
route:
  group_by: [Alertname]
  receiver: email-me

receivers:
- name: email-me
  email_configs:
  - to: xxxx@gmail.com
    from: xxxx@gmail.com
    smarthost: smtp.gmail.com:587
    auth_username: "xxxx@gmail.com"
    auth_identity: "xxxx@gmail.com"
    auth_password: "xxxx"
</pre>

Thanks,
Rahul.

**Comment by stuartnelson3** [comment]
Hey Rahul, this is more of a support question than an issue (as of now, it could turn into an issue). Could you post this message to the `prometheus-users` mailing group?
