### ISSUE TITLE
Email notification when alarm expires

### ISSUE THREAD

**Issue by AndreaGiardini** [prometheus/alertmanager#659]
I would like to have a notification whenever an alarm expires.

Is it possible to do it with alertmanager? I didn't find anything related to it in the docs

**Comment by brancz** [comment]
Do you mean a resolved notification? In that case you need to set the `send_resolved` field to `true` in your email config. https://prometheus.io/docs/alerting/configuration/#email_config

The [Prometheus Users](https://groups.google.com/forum/#!forum/prometheus-users) mailing list is in general a better place to ask user questions as they have better visibility and other users can benefit from it more.

**Comment by AndreaGiardini** [comment]
That's great :) I will make sure to use mailing list next time, thank you!
