### ISSUE TITLE
Redirect /${pathPrefix} to /${pathPrefix}/

### ISSUE THREAD

**Issue by a86c6f7964** [prometheus/alertmanager#66]
Since y'all are requiring that pathPrefix end up with / before and after it does not match `/${pathPrefix}` . I usually find this somewhat annoying because sometimes I forget to type the trailing /. I think that it would be nice to redirect users to add the /.

In prometheus everything that should be a 404 is redirected. I would not advocate doing this, because its somewhat strange behavior to not have a 404 page, but just doing it for the `/${pathPrefix}` to `/${pathPrefix}/` seems relatively reasonable and is likely what the user meant to type.

**Comment by juliusv** [comment]
Yeah, the whole 404 behavior was broken. I did two PRs, one for alertmanager and the same for Prometheus:

- https://github.com/prometheus/alertmanager/pull/67/files
- https://github.com/prometheus/prometheus/pull/726/files

Could you check if those behave correctly for you?
