### ISSUE TITLE
Alertmanager v0.4.2 entered deadlock and stopped sending alert notifications

### ISSUE THREAD

**Issue by mattbostock** [prometheus/alertmanager#660]
Filing this issue for verison 0.4.2 (an old version) in case it helps anyone else using this version. We're unable to upgrade to 0.5.x currently until pagination for silences is supported (#522).

One of our Alertmanager instances entered a deadlock twice in two days, during which it stopped sending alert notifications. We resolved the issue by restarting Alertmanager on both occasions. Metrics were still being exposed on `/metrics` and new alerts were accepted during that time.

The second time it happened, I was able to obtain debug info from the pprof HTTP endpoint, e.g.:

```bash
curl -s https://alertmanager.foo/debug/pprof/goroutine?debug=2 > goroutine.txt
```

The Go runtime version is 1.7.3.

Here is the goroutine stack trace:
[goroutine.txt](https://github.com/prometheus/alertmanager/files/858861/goroutine.txt)

From the stack trace, it appears that there's a large number of goroutines that are waiting to get a readlock on a sync.RWMutex. Most of these goroutines on the code path responsible for dispatching alert notifications, which would explain why alert notifications were not being sent.

Example:

```
goroutine 180 [semacquire, 6 minutes]:
sync.runtime_Semacquire(0xc42008d424)
        /usr/local/go/src/runtime/sema.go:47 +0x30
sync.(*RWMutex).RLock(0xc42008d418)
        /usr/local/go/src/sync/rwmutex.go:43 +0x5d
github.com/prometheus/alertmanager/provider/boltmem.(*Silences).Mutes(0xc42008d400, 0xc423191170, 0x0)
        /go/src/github.com/prometheus/alertmanager/provider/boltmem/boltmem.go:244 +0x48
github.com/prometheus/alertmanager/notify.(*SilenceNotifier).Notify(0xc420439650, 0xac7980, 0xc424331650, 0xc4214f4000, 0xc, 0x10, 0xc42016b500, 0xaf5c87fc560184c6)
        /go/src/github.com/prometheus/alertmanager/notify/notify.go:340 +0xd3
github.com/prometheus/alertmanager/notify.(*LogNotifier).Notify(0xc4203f8a20, 0xac7980, 0xc424331650, 0xc4214f4000, 0xc, 0x10, 0x8, 0x10)
        /go/src/github.com/prometheus/alertmanager/notify/notify.go:403 +0x145
github.com/prometheus/alertmanager/notify.(*InhibitNotifier).Notify(0xc4204396e0, 0xac7980, 0xc424331650, 0xc427f9c0c0, 0xc, 0xc, 0xc424331680, 0x817ee0)
        /go/src/github.com/prometheus/alertmanager/notify/notify.go:383 +0x20e
github.com/prometheus/alertmanager/notify.(*LogNotifier).Notify(0xc4203f8aa0, 0xac7980, 0xc424331650, 0xc427f9c0c0, 0xc, 0xc, 0x18e, 0x36)
        /go/src/github.com/prometheus/alertmanager/notify/notify.go:403 +0x145
main.(*Dispatcher).processAlert.func1(0xac7980, 0xc424331650, 0xc427f9c0c0, 0xc, 0xc, 0x2)
        /go/src/github.com/prometheus/alertmanager/dispatch.go:236 +0x86
main.(*aggrGroup).run.func1(0xc427f9c0c0, 0xc, 0xc, 0x2)
        /go/src/github.com/prometheus/alertmanager/dispatch.go:336 +0x58
main.(*aggrGroup).flush(0xc420187f00, 0xc4236a9ef0)
        /go/src/github.com/prometheus/alertmanager/dispatch.go:400 +0x46c
main.(*aggrGroup).run(0xc420187f00, 0xc42024d340)
        /go/src/github.com/prometheus/alertmanager/dispatch.go:337 +0x89d
created by main.(*Dispatcher).processAlert
        /go/src/github.com/prometheus/alertmanager/dispatch.go:241 +0x31f
```

In the goroutine dump, there's just one goroutine that has a mention of sync.(*RWMutex).Lock, though it is also in the Semacquire state, suggesting that it's trying to obtain a write lock (on the same mutex - the memory address is the same as for the goroutines waiting for a read lock):

```
goroutine 1990400 [semacquire, 11 minutes]:
sync.runtime_Semacquire(0xc42008d420)
        /usr/local/go/src/runtime/sema.go:47 +0x30
sync.(*RWMutex).Lock(0xc42008d418)
        /usr/local/go/src/sync/rwmutex.go:91 +0x98
github.com/prometheus/alertmanager/provider/boltmem.(*Silences).Del(0xc42008d400, 0x741f, 0x0, 0x0)
        /go/src/github.com/prometheus/alertmanager/provider/boltmem/boltmem.go:392 +0x66
main.(*API).delSilence(0xc42038d1d0, 0xac6480, 0xc420d50e10, 0xc422f8a3c0)
        /go/src/github.com/prometheus/alertmanager/api.go:365 +0x115
main.(*API).(main.delSilence)-fm(0xac6480, 0xc420d50e10, 0xc422f8a3c0)
        /go/src/github.com/prometheus/alertmanager/api.go:102 +0x48
github.com/prometheus/alertmanager/vendor/github.com/prometheus/client_golang/prometheus.InstrumentHandlerFuncWithOpts.func1(0xac69c0, 0xc42145a0d0, 0xc422f8a3c0)
        /go/src/github.com/prometheus/alertmanager/vendor/github.com/prometheus/client_golang/prometheus/http.go:158 +0x2ab
github.com/prometheus/alertmanager/vendor/github.com/prometheus/common/route.handle.func1(0xac69c0, 0xc42145a0d0, 0xc422f8a3c0, 0xc421cf87a0, 0x1, 0x1)
        /go/src/github.com/prometheus/alertmanager/vendor/github.com/prometheus/common/route/route.go:49 +0x33e
github.com/prometheus/alertmanager/vendor/github.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc420528380, 0xac69c0, 0xc42145a0d0, 0xc422f8a3c0)
        /go/src/github.com/prometheus/alertmanager/vendor/github.com/julienschmidt/httprouter/router.go:299 +0x7ec
github.com/prometheus/alertmanager/vendor/github.com/prometheus/common/route.(*Router).ServeHTTP(0xc4203f8ae0, 0xac69c0, 0xc42145a0d0, 0xc422f8a3c0)
        /go/src/github.com/prometheus/alertmanager/vendor/github.com/prometheus/common/route/route.go:107 +0x4c
net/http.serverHandler.ServeHTTP(0xc42055e000, 0xac69c0, 0xc42145a0d0, 0xc422f8a3c0)
        /usr/local/go/src/net/http/server.go:2202 +0x7d
net/http.(*conn).serve(0xc4244e0000, 0xac7600, 0xc422dc20c0)
        /usr/local/go/src/net/http/server.go:1579 +0x4b7
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2293 +0x44d
```

...which suggests that another goroutine must be running that already has the write lock and had not released it at the time I took the goroutine dump. I've so far been unable to find that goroutine (or what code path had write-locked the mutex first).

In our load balancer request logs, there's a request to the `del_silence` handler that takes 7 seconds, followed by another that takes 10 seconds, within a minute of the time notifications stop being sent. There's no implication of causation - this may just be a symptom.

From the line numbers in the goroutine stack trace, it looks like the `sync.(*RWMutex)` causing the deadlock is `(*Silences).mtx`. There are 3 code paths that could obtain a write lock on that mutex:

```
$ ack -B 1 s.mtx.Lock provider/boltmem
provider/boltmem/boltmem.go
326-func (s *Silences) initCache() error {
327:	s.mtx.Lock()
355-func (s *Silences) Set(sil *types.Silence) (uint64, error) {
356:	s.mtx.Lock()
391-func (s *Silences) Del(uid uint64) error {
392:	s.mtx.Lock()
```

Of those, only `Del` is visible in the backtrace.

I tried running `go test` with `-race` enabled but there are races in the tests that I'd need to fix first. Running `go build` with `-race` gives nothing.

Happy to provide more debug info if it's useful.

**Comment by mxinden** [comment]
@mattbostock Does this issue still persist in more recent versions of Alertmanager? In case you were able to upgrade to a more recent version, can we close this issue?

**Comment by mattbostock** [comment]
@mxinden: Please close, I opened it to raise awareness for anyone using version 0.4.2 due to the severity but I have not seen it in 0.6.2 which we're using currently.
