### ISSUE TITLE
Trying to clarify something about alerts resolved within "group wait"

### ISSUE THREAD

**Issue by sstorie** [prometheus/alertmanager#662]
I'm debugging a problem we've seen where a few alerts yesterday were fired and then resolved within 30 seconds, but alertmanager did not seem to act upon them. I can see the alerts in prometheus itself using the ALERTS metric, so I know they happened, but we were not notified. We have both email and webhook receivers configured, and other alerts worked during this time frame.

So my general question is whether it's possible for promethues to transition an alert to firing, then resolved within some time frame and have alertmanager not take any action? I'm not implying a bug of any kind here, just trying to build my understanding of how alertmanager works, and if we need to tweak the settings to get what we want.

*We have not set any specific values for group_wait, so I assume the default value is in effect*

**Comment by stuartnelson3** [comment]
Hey @sstorie,

This is a question that should be moved to the prometheus-users mailing group (https://groups.google.com/forum/#!forum/prometheus-users)

**Comment by sstorie** [comment]
Ok, thanks for the guidance. I've asked my question there.
