### ISSUE TITLE
can an alert route to two receivers?

### ISSUE THREAD

**Issue by QingsongYao** [prometheus/alertmanager#664]
I like to have two receivers for each alert.  One for slack/devops notification. another goes to logstach => elasticsearch for auditing purpose.  I wonder if we can achieve this today?

**Comment by brian-brazil** [comment]
User questions are best asked at https://groups.google.com/forum/#!aboutgroup/prometheus-users

https://www.robustperception.io/sending-alert-notifications-to-multiple-destinations/
