### ISSUE TITLE
add dingding support in alertmanager

### ISSUE THREAD

**Issue by steinliber** [prometheus/alertmanager#665]
Dingding is the most popular communicate tool in China like slack, but altermanager doesn't support send message to dingding robort(webhook doesn't match format in dingding ), i'd like to PR this function like slack

**Comment by stuartnelson3** [comment]
You can write a service to receive the webhook request, parse the message, and then send the correctly formatted message to dingding.

**Comment by steinliber** [comment]
ok, i will try this
