### ISSUE TITLE
Disable grouping?

### ISSUE THREAD

**Issue by hiscal2015** [prometheus/alertmanager#669]
Hi, 

I'm new to alertmanager, after testing for several days, I'm stuck at the grouping feature, seems the default value is to group by "alertname" even if you don't configure it, if 10 MemoryUsage alerts triggered from 10 hosts, there will be only one ticket created in the target alert system like PagerDuty or Opsgeniu...
But for team work, I'd like to assign the 10 alerts to 10 different users, so 10 tickets should be created accordingly, how can I achieve this?

**Comment by stuartnelson3** [comment]
This is a question that should be moved to the prometheus-users mailing list (https://groups.google.com/forum/#!forum/prometheus-users) since it's about using alertmanager and not a specific issue with the alertmanager.
