### ISSUE TITLE
Please add url escape to template FuncMap

### ISSUE THREAD

**Issue by Rudd-O** [prometheus/alertmanager#678]
We need to convert /blah/bluh/app to %2F/bluh%2F/app.

It'd be great if we could, but there isn't any way to do this on the latest stable release, and reReplaceAll in the master branch is insufficient.

Thank you in advance!

**Comment by brian-brazil** [comment]
Can you indicate exactly where and how you're doing this? Go templating does a lot of this automatically, and reReplaceAll should be sufficient as this is simple transliteration.

**Comment by Rudd-O** [comment]
There are other characters that need to be quoted, not just slash.  I am doing this in an alertmanager template.  I want the equivalent of urllib.quote and also an XML/HTML entities escape, so I can chain both.

On March 31, 2017 9:09:26 PM GMT+02:00, Brian Brazil <notifications@github.com> wrote:
>Can you indicate exactly where and how you're doing this? Go templating
>does a lot of this automatically, and reReplaceAll should be sufficient
>as this is simple transliteration.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/prometheus/alertmanager/issues/678#issuecomment-290802215

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by brian-brazil** [comment]
Go templating handles all that for you for HTML fields automatically. You should not need to do this by hand.

**Comment by Rudd-O** [comment]
Well, it's not URL-encoding a parameter in my case.  I tried.  If I just place the {{ value}} there, the slashes do not get url-escaped (this is a querystring I am trying to build).

On April 1, 2017 1:29:34 PM GMT+02:00, Brian Brazil <notifications@github.com> wrote:
>Go templating handles all that for you for HTML fields automatically.
>You should not need to do this by hand.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/prometheus/alertmanager/issues/678#issuecomment-290914389

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by brian-brazil** [comment]
This is why I ask you to provide the full details of what you're doing, so we can see if there's an actual bug here.

**Comment by Rudd-O** [comment]
My template goes like this:

<a href="http://base.url/marathon#/apps/{{ $variable }}">sometext</a>

I want $variable to get URL-escaped because the app name in the URL, if it has special characters like slashes or quotes, must be URL-escaped, otherwise the page does not load.

**Comment by brian-brazil** [comment]
In which field of which notifier?

**Comment by Rudd-O** [comment]
In the template itself.  Email notifier.  Body.

On April 1, 2017 4:19:45 PM GMT+02:00, Brian Brazil <notifications@github.com> wrote:
>In which field of which notifier?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/prometheus/alertmanager/issues/678#issuecomment-290922963

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by brian-brazil** [comment]
I presume you mean the `HTML` field. Can you indicate the string that's not being correctly handled, as your original example is incorrect?

**Comment by Rudd-O** [comment]
I am replacing default.tmpl (which is normally embedded in the code) with my own.

On Monday I will explain more, as I haven't managed yet to convey the state I am in.

On April 1, 2017 5:03:11 PM GMT+02:00, Brian Brazil <notifications@github.com> wrote:
>I presume you mean the `HTML` field. Can you indicate the string that's
>not being correctly handled, as your original example is incorrect?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/prometheus/alertmanager/issues/678#issuecomment-290925494

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Rudd-O** [comment]
Thanks folks, I got it to work nicely on my end.

On April 1, 2017 7:20:00 PM GMT+02:00, "Manuel Amador (Rudd-O)" <rudd-o@rudd-o.com> wrote:
>I am replacing default.tmpl (which is normally embedded in the code)
>with my own.
>
>On Monday I will explain more, as I haven't managed yet to convey the
>state I am in.
>
>On April 1, 2017 5:03:11 PM GMT+02:00, Brian Brazil
><notifications@github.com> wrote:
>>I presume you mean the `HTML` field. Can you indicate the string
>that's
>>not being correctly handled, as your original example is incorrect?
>>
>>-- 
>>You are receiving this because you authored the thread.
>>Reply to this email directly or view it on GitHub:
>>https://github.com/prometheus/alertmanager/issues/678#issuecomment-290925494
>
>-- 
>Sent from my Android device with K-9 Mail. Please excuse my brevity.

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
