### ISSUE TITLE
Add ID for alerts and add alert ID's to silences

### ISSUE THREAD

**Issue by HyperDevil** [prometheus/alertmanager#681]
Hi,

I am trying to parse the API output, for alerts and silences. (in PHP)
The silences seem to have an ID, but does not have the explicit alarm ID attached in the JSON output (if alarm has an ID?).
Also the alarms do not have an unique ID so that i cannot match which alarms are being silences by a certain rule.
Is there an internal connection between the alarms and the silences?

**Comment by stuartnelson3** [comment]
In the current data model, alerts are ephemeral and do not have an ID assigned to them.

Internally, the first silence that matches (and silences) an alert has its ID added to the alert's data structure in the `silenced` field.

You can do two things:

1. You can iterate through the alerts and check for the `silenced` field. This only shows the first silence that affects the alert, though, and won't show any additional silences that also affect it.
2. You can take the label matchers defining a silence, and make a request to the alert groups endpoint:

```
http://alertmanager.example.biz/api/v1/alerts/groups?filter=%7Bfoo%3D%22bar%22%2C%20baz%3D~%22quux%22%7D
```

(filter == `{foo="bar", baz=~"quux"}`)

And that will return the alerts that match the matchers in `filter`.

**Comment by stuartnelson3** [comment]
That having been said, we are adding alert ID's as part of the UI/API update that is currently underway. Assigning to @mxinden since he's so keen on it.

**Comment by fabxc** [comment]
I'm curious about those alert IDs. What does the current plan look like?

**Comment by mxinden** [comment]
@stuartnelson3: I talked to @fabxc in regards to adding Alert ids with the API update. There are no actions (create, update, delete) needed in the UI where we have to address a specific alert. Thereby adding a specific Alert id is not on the agenda. Doing so would open up many questions in regards to the realisation of eventual consistency inside a mesh network of Alertmanagers.

@HyperDevil Let us know if @stuartnelson3 answer solves your problem.

**Comment by HyperDevil** [comment]
@mxinden and @stuartnelson3 
Thank you for the answers so far.
I am currently using version 0.4.2 of Alertmanager, and i have silences active. But i cannot seem to find any alerts with silences attached when using the /api/v1/alerts, am i using an old version that does not have this?

The point for me is that i need to make a list of alerts outside of Alertmanager using the API, and i want to filter out the alarms that i silcenced (i dont care about which silence rule, as long as it is silenced)

**Comment by stuartnelson3** [comment]
0.4.2 has the concept of `silenced` as part of the alert's data structure. Query the api for all alerts, then filter out the ones that have the `silenced` field.

**Comment by HyperDevil** [comment]
@stuartnelson3 i am quering /api/v1/alerts using my web browser. Then i try to search for the string "silen" and i find no results, while i have several alerts which have been silenced. Strange.

**Comment by mxinden** [comment]
Related to #786

**Comment by simonpasquier** [comment]
This issue can be closed. cc @stuartnelson3 

Here is the output of the /api/v1/alerts endpoint:
```json
{
  "status": "success",
  "data": [
    {
      "labels": {
        "alertname": "TargetDown",
        "instance": "http://localhost:8081",
        "job": "blackbox",
        "severity": "critical"
      },
      "annotations": {
        "summary": "Target down"
      },
      "startsAt": "2018-03-16T12:06:10.79789965+01:00",
      "endsAt": "2018-03-16T13:43:25.800193318+01:00",
      "generatorURL": "http://simon-laptop:9090/graph?g0.expr=probe_success+%21%3D+1&g0.tab=1",
      "status": {
        "state": "suppressed",
        "silencedBy": [
          "e69e786f-e2ac-462d-a3c2-0855c8ba1bf8"
        ],
        "inhibitedBy": []
      },
      "receivers": [
        "webhook"
      ],
      "fingerprint": "5432f81757da9979"
    }
  ]
}
```
