### ISSUE TITLE
Package for generating emails

### ISSUE THREAD

**Issue by fabxc** [prometheus/alertmanager#683]
HTML emails are extremely painful. Currently we have a template that somewhat works, but not really. We also have no proper support for an alternative multipart sending HTML and plain text versions. Even less so for keeping both in sync.

There's a package now, that seems to do a great job at solving this problem: https://github.com/matcornic/hermes

We should evaluate switching to this one.

**Comment by brian-brazil** [comment]
We'll always need to allow users to directly control the raw content of their emails, so this would be an optional extra at most.

**Comment by fabxc** [comment]
Tend to agree with optional, wouldn't be sure about "optional extra at most" – practically speaking, this is probably the better choice in 99%  of the cases.

**Comment by brian-brazil** [comment]
I'd guess nearer 50-80%, lots of email will be going to ticketing systems which won't care for fancy formatting.

**Comment by prologic** [comment]
This is also painful as currently many mail servers reject email from alertmanager because of `MIME_MA_MISSING_TEXT`

**Comment by brian-brazil** [comment]
We support text now. If users want to use tools to generate their HTML and make it fancies they are free to do so.

**Comment by prologic** [comment]
Yes :)

For future readers:

```
+    text: |
+      Summary: {{ range .Alerts }}{{ .Annotations.summary }} {{ end }}
+
+      Description: {{ range .Alerts }}{{ .Annotations.description }} {{ end }}
+
+      RunBook: http://wiki.intern.mills.io/Alert{{ .GroupLabels.alertname }}
```
