### ISSUE TITLE
Feature request: Notification delay set per-route

### ISSUE THREAD

**Issue by mattbostock** [prometheus/alertmanager#686]
I'd like to be able to set a notification delay, set per-route.

This would allow for situations where you want to send a low-priority notification (e.g. Slack or HipChat) and then follow-up with a high priority notification (e.g. PagerDuty) if the alert is still firing after a specified duration of time.

There are hacks you can do to make PagerDuty do this, though it creates a lot of additional noise in PagerDuty reports.

**Comment by brian-brazil** [comment]
The way to do this is to have two alerts in Prometheus with different severity labels.

Escalation policies are not an intended feature of the alertmaanger.

**Comment by stuartnelson3** [comment]
I talked briefly with @SuperQ about putting that in the alert definition, something like

```
ALERT MySQLCritical
  IF some_query
  FOR 15m {severity="warning"}
  FOR 30m {severity="critical"}
  LABELS {
    service = "mysql"
  }
  ANNOTATIONS {
    description = "something is wrong"
  }
```

But yeah, as Brian noted while I was writing this, you can achieve this with two different rules.

**Comment by stuartnelson3** [comment]
Since this is something that would be added to prometheus, I'm going to close it over here.

**Comment by just1900** [comment]
> I talked briefly with @SuperQ about putting that in the alert definition, something like
> 
> ```
> ALERT MySQLQPS
>   IF some_query
>   FOR 15m {severity="warning"}
>   FOR 30m {severity="critical"}
>   LABELS {
>     service = "mysql"
>   }
>   ANNOTATIONS {
>     description = "something is wrong"
>   }
> ```
> 
> But yeah, as Brian noted while I was writing this, you can achieve this with two different rules.

Hi, @stuartnelson3  has this definition above been deprecated since promtheus have been bumped to v2.x? I couldn't find a way to define alertRule something like below wrt the [docs](https://prometheus.io/docs/prometheus/latest/configuration/alerting_rules/) here 
>   FOR 15m {severity="warning"}
>   FOR 30m {severity="critical"}

does that mean I still need to create two alerts in Prometheus with different severity labels ?

**Comment by SuperQ** [comment]
@just1900 That idea was never implemented.

**Comment by just1900** [comment]
@SuperQ are there any context about this, or will that be possible to implement this idea?
