### ISSUE TITLE
Alertpage silenced / inhibited checkbox

### ISSUE THREAD

**Issue by stuartnelson3** [prometheus/alertmanager#688]
Add checkbox ("[x] display suppressed alerts")  to alert page to filter out  all suppressed alerts.

A suppressed alert can either be a silenced or inhibited.

Depends on #717

**Comment by mxinden** [comment]
@stuartnelson3 Editing this as discussed in the meeting.

**Comment by mxinden** [comment]
Partly fixed by #799.

Now only `inhibited` is missing.

**Comment by mxinden** [comment]
This is related to issue #801.

**Comment by w0rm** [comment]
Closing this issue as we now have checkboxes to show/hide silenced and inhibited alerts

![screen shot 2017-12-15 at 11 45 56](https://user-images.githubusercontent.com/43472/34038695-88f667a2-e18d-11e7-88d6-7b47e24b9c5e.png)
