### ISSUE TITLE
Alert  manager fails to send email through smtp server configured with port 465

### ISSUE THREAD

**Issue by IamPrvn** [prometheus/alertmanager#705]
The issue have been raised here too
 [https://groups.google.com/d/msg/prometheus-users/962iFpDPFZU/4mimkxSuCQAJ](url) . 
[https://groups.google.com/d/msg/prometheus-users/w2hUOAQFD7I/1L8FNTvaCgAJ](url)
With smtp port 465, it does not work (whether or not you are in proxy). Not all the smtp servers provide us with the priviledge of port 587. So, kind of stuck getting it worked with port 465. It responds with either a reset flag set or a EOF

note:- copy the links and paste in browser

**Comment by rmrf** [comment]
does this  a confirmed issue? I'm using another email ISP(not gmail) which using 465 as secure port, and have simillar issue as @IamPrvn .

**Comment by hiscal2015** [comment]
@IamPrvn Any progress on this?

**Comment by IamPrvn** [comment]
@hiscal2015 No, PR is yet to be reviewed/merged .
