### ISSUE TITLE
Alertmanager HA

### ISSUE THREAD

**Issue by prasenforu** [prometheus/alertmanager#712]
I am using prometheus and alertmanager in kubernetes environment.

In kubernetes we use config map.

In prometheus configmap we define alertmanager  url  as a alertmanager service . Basically which act as a load balance. Under alertmanager service there are multiple alertmanager containers.

Will it work ?
Does gosssip protocol by default enabled.?
How discovery of multiple alertmanager in container level work?

Just 4 days back created one youtube (https://youtu.be/XQdEVY2l2e0) by    Frederic Branczyk on alertmanager HA. 

Based on that questions came to my mind.

Another thing in alertmanager I am using persistent storage.

In alertmanager  container which folders need setup for Persistent Volume.

I use /var folder from container.

**Comment by andrewhowdencom** [comment]
I think you might get more help on the mailing list for this one.

**Comment by grobie** [comment]
Please ask questions on the prometheus-users@ mailing list.

**Comment by prasenforu** [comment]
Crated question with subject "Alertmanager HA" in mailing list.
