### ISSUE TITLE
Add required name field to routing nodes

### ISSUE THREAD

**Issue by fabxc** [prometheus/alertmanager#718]
I'd like to propose a mandatory new `name` field to be added to each node in the configured routing tree.

Reasoning as follows:

We need some sort of node identity to store whether we sent a notification. By current idea this happens by taking a hash over all matchers of the final node and all its parents. This obviously drops relevant information that's part of how an alert ends up in a certain node. For example, the `continue` keyword means siblings of all nodes in the path an alert took could have played into the routing decision.  
Considering this in the hash would be very complex and would trigger unnecessary resending of notifications. Not doing it gives us some sort of reasonble mix of triggering and not triggering resends on minor config changes.   
It's not really possible to infer the user's semantic intent from the given matchers. It could cause accidental oscillations in large configs that will be nearly impossible to debug.

The most straightforward and easiest to reason about way of solving this is having a name for each node, that must be unique among its siblings. Any node can then be identified by the concatenation of the names, e.g. `team-infra/eu-west/monitoring`.

Cons:
* Adds another config field, which means mental overhead for the user.
* The name will often be self-explanatory for simple matchers like `team == monitoring` and seem superfluous.

Pros:
* `name` is an addition that is pretty easy to understand
* Easy to reason about and handy node names for debugging
* Completely avoids potential hash collisions
* Config changes do not trigger noisy notifications as the name clearly aligns the user's semantic intent rather than a hash preserving identity in a best-effort manner
* Forces users to provide a descriptive name for nodes more complex matchers such als multiple regexes
* No unexpected edge cases in large configs and generally straightforward internal semantics

Those are the arguments that came up on IRC with @brian-brazil.
Obviously, I'm leaning towards the pro side.

Opinions and further arguments to make a final call would be appreciated. 

@beorn7 @juliusv @mxinden @brancz

**Comment by fabxc** [comment]
@mattbostock would be interesting to hear from a heavy user how adding of this field would impact your user experience.

**Comment by stuartnelson3** [comment]
I'm in favor since the one-time cost of adding a name field doesn't come close to outweighing the benefits. Having a config linter would also help.

**Comment by brian-brazil** [comment]
> I'm in favor since the one-time cost of adding a name field doesn't come close to outweighing the benefits. 

It's an ongoing cost, as all new routes also need it added.

**Comment by stuartnelson3** [comment]
But you add it once to each route?

**Comment by brian-brazil** [comment]
Yes, it'd be a new mandatory field. It's an additional thing everyone writing a config needs to consider.

**Comment by fabxc** [comment]
One thing that did not come up yet: We likely want more tooling around showing the routing tree. Brief names will be a more consumable representation than displaying a set of matchers in each.

**Comment by matthiasr** [comment]
We auto-generate large parts of the Alertmanager configuration based on lists of receivers (and the means to contact them). For us, this field would simply burden us with the task of automatically deriving a unique identifier for everything.

**Comment by mattbostock** [comment]
So long as the name only needs to be unique among children at the same level, I think it's a manageable burden (and may be useful for documentation).

But (talking from the peanut gallery) I'm not convinced that this can't be solved using a hash or some method we haven't thought of.

**Comment by fabxc** [comment]
@mattbostock the problem is that the info is not there to begin with. All we could come up with are "better" heuristics. That generally means getting more complicated, which means making things harder to debug and potential oddnesses more unpredictable.

**Comment by fabxc** [comment]
Okay, while I think it has lots of benefits the pro-vibes here are not really strong. Alternative proposal, we move away from hashes and by default use the full matcher representation as node name (user-defined `name` field could be added later).

Then a node at level 3 in the tree would for example be:

```
{team="monitoring"}/{zone=~"eu-.+",a="b"}/{service="k8s"}"
```

And a group key (key for one alert group that's send as one notification), would be the concatenation of the key above and the grouping labels:

```
{team="monitoring"}/{zone=~"eu-.+",a="b"}/{service="k8s"}:{job="kubelet",level="page"}
```

This at least moves us away from awkward hashing and also gives us a human-readable representation.

**Comment by brian-brazil** [comment]
I think match representation is a good approach, with the proviso that we may need to optimise overly-long matchers at some point in the future.

**Comment by fabxc** [comment]
@brian-brazil mh, we should probably at least add a validation than that two siblings must not have the same matchers than, right?

This could theoretically be valid and result in oscillation if you use the continue keyword and have two sibling subtrees based on the same matchers.

**Comment by brian-brazil** [comment]
I think we have to keep having two siblings with the same matchers as valid, as it's one way to send a notification to two receivers. Maybe we need to distinguish on the receiver too?

**Comment by fabxc** [comment]
Closing here for now. We'll see how #725 plays out.
