### ISSUE TITLE
CLI error output

### ISSUE THREAD

**Issue by stuartnelson3** [prometheus/alertmanager#721]
Any time there's an error, the usage text is output. It seems like a legitimate error (as opposed to mis-use of the cli) should just output the error text:

```
# ./amtool silence expire d08ead34-1119-400a-a1bb-2788853fc520
Error: expired silence must not be modified
Usage:
  amtool silence expire [flags]

Global Flags:
      --alertmanager.url string   Alertmanager to talk to
      --config string             config file (default is $HOME/.amtool.yml)
  -o, --output string             Output formatter (simple, extended, json) (default "simple")
  -q, --quiet                     Only show silence ids
  -v, --verbose                   Verbose running information
```

This should just be 
```
# ./amtool silence expire d08ead34-1119-400a-a1bb-2788853fc520
Error: expired silence must not be modified
```

That's my opinion, anyway. Thoughts?

@mxinden @fabxc @brancz @kellel

**Comment by mxinden** [comment]
Is there a `--help` flag? If so we can omit the usage text and just add something along the lines of: `For further help run "amtool --help"`

**Comment by Kellel** [comment]
https://github.com/prometheus/alertmanager/pull/724

I did the linking of pr to issue incorrectly
