### ISSUE TITLE
[Request] Add Slack fields to notifications

### ISSUE THREAD

**Issue by taharah** [prometheus/alertmanager#731]
The Slack notification API has added a fields parameter that allows for some additional formatting [1]. It looks like the work was started to add this additional parameter [2], but the feature was never finished so that it was available. 

[1] https://api.slack.com/docs/message-attachments#fields
[2] https://github.com/prometheus/alertmanager/blob/v0.5.1/notify/impl.go#L485-L490

**Comment by mxinden** [comment]
Hi @taharah do you have some time creating a PR for this? We are here to help in case you have any questions.

**Comment by chhetripradeep** [comment]
@mxinden @taharah  I would like to pick this up. Will create a PR soon with my basic Golang knowledge. Thanks.
