### ISSUE TITLE
Freshen up UI

### ISSUE THREAD

**Issue by stuartnelson3** [prometheus/alertmanager#734]
We've added bootstrap, now we need to get a rough draft of a UI going. Doesn't need to be permanent, but what we currently have needs some love.

**Comment by mxinden** [comment]
@w0rm Maybe you could combine this with your [comment](https://github.com/prometheus/alertmanager/pull/754#issuecomment-298097041) in PR #754?

I would also like to show the new UI to our internal design team.

**Comment by mxinden** [comment]
I would like to close this issue as it is very generic and as I feel like @w0rm already did a great job styling the new UI. What do you think?

Please feel free to reopen.
