### ISSUE TITLE
Pending silences display the end time in the "Starts..." text

### ISSUE THREAD

**Issue by awells3** [prometheus/alertmanager#737]
When I create a silence for a future time, the UI shows the end time in the "Starts..." text.  I have provided a screenshot below.

![pending_alert_ui_bug](https://cloud.githubusercontent.com/assets/27705592/25400810/60cb7538-29b9-11e7-8e6c-6b0928b5598d.PNG)

Running version 0.5.1

The behavior of the silence abides by what I put in the form when creating the silence so that is not an issue.  It would just be nice if the "Starts..." text correctly displayed "Starts Thrusday at 07:15 PM"

**Comment by stuartnelson3** [comment]
fixed in #778
