### ISSUE TITLE
Support for headers in webhooks

### ISSUE THREAD

**Issue by andrewklau** [prometheus/alertmanager#739]
It'd be good to be able to have some sort of support to be able to set headers with the outgoing webhooks.

Use cases would be setting api tokens.
eg. api gateway wants `x-api-key`

Somewhat related https://github.com/prometheus/alertmanager/issues/324

**Comment by juliusv** [comment]
We don't allow specifying arbitrary headers for HTTP calls anywhere else in Prometheus, but it would probably be fair to add the same HTTP client options that we use elsewhere: TLS options (including client certs), bearer token auth, and basic auth.

**Comment by brian-brazil** [comment]
Yes, we should have the usual auth options.

Headers should not be supported for the same reasons we don't support url parameters.
