### ISSUE TITLE
Load templates from file

### ISSUE THREAD

**Issue by wrouesnel** [prometheus/alertmanager#74]
The current email config is in `notifier.go` as a blob of text.

This can pretty obviously be loaded up from a file specified as a configuration option, since email is one of those things you'd want to pretty heavily customize.

I'm just dropping this here so I can reference it later when I get a chance to have a poke at it.

**Comment by brian-brazil** [comment]
More generally, all notifications should be configurable via a templating language. I'm thinking inline in the config, as many will be brief.

**Comment by brian-brazil** [comment]
The new alertmanager supports this.
