### ISSUE TITLE
Amtool: Documentation

### ISSUE THREAD

**Issue by mjtrangoni** [prometheus/alertmanager#741]
It would be nice to have the `amtool` behaviour in [README.md](https://github.com/prometheus/alertmanager/blob/master/README.md) and [here](https://prometheus.io/docs/alerting/configuration/).

For example, there is no example for 'amtool.yml' config file apart from [this](https://github.com/prometheus/alertmanager/pull/636).

**Comment by CharlesJUDITH** [comment]
Hey I started to play with `amtool` and made a PR (https://github.com/prometheus/alertmanager/pull/758) to help you to start with it.

**Comment by stuartnelson3** [comment]
Documentation is available within the tool itself by appending the `--help` flag to commands.
