### ISSUE TITLE
Alertpage group by

### ISSUE THREAD

**Issue by mxinden** [prometheus/alertmanager#742]
A user should be able to group all displayed alerts by a set of labels. The grouping should be flat, not nested.

Auto complete would be nice to have. Could be similarly realised like the already existing filter bar by @w0rm.

**Comment by stuartnelson3** [comment]
So we were thinking of having this be a separate set of autocomplete boxes, correct? the user would type in, e.g., `service`, `region`, and then the alerts would be sorted as such? example heading for a group being `service=foo_service` `region=eu-west-1`?

**Comment by mxinden** [comment]
@stuartnelson3 Yes, I would suggest a separate auto-complete box. When I add a new label via the input, alerts should be automatically grouped by it.

> example heading for a group being service=foo_service region=eu-west-1?

Yes

**Comment by mxinden** [comment]
Closing here as #775 is merged.
