### ISSUE TITLE
Silencepage quick filter by pending / active / expired

### ISSUE THREAD

**Issue by mxinden** [prometheus/alertmanager#745]
A user should be able to quickly filter all displayed silences by pending / active / expired ones with check boxes. The check boxes could be placed underneath the filter bar.

Style should be  similar to #688

**Comment by mxinden** [comment]
@fabxc What do you think of returning pending / active / expired from the back-end instead of determining this on the client with timestamps? Would prevent time zone issues.  Either one is fine with me.

**Comment by fabxc** [comment]
I'd not group them from the API, but attaching a status on pending/active/expired like we added for alerts would be good, yes.

We could follow the same pattern there of

```"status": {
  "state": <expired|pending|active>,
  "silences": [<alert ID/FP>, ...]
}
```

The latter can be added later. Just so we make `status` an object to begin with.

**Comment by stuartnelson3** [comment]
+1 for setting state in the backend and passing it to the front end.

Regarding `suppresses` vs. `silences`: We use `suppressed` as an AlertState, but that struct still has a `silencedBy` field. I would say we stick with `silences` as the field name since that's the specific type of `suppressed` we're dealing with.

**Comment by mxinden** [comment]
@stuartnelson3 @w0rm I am currently working on this. I will give the silence page a little bit of styling as well.

**Comment by mxinden** [comment]
Closing here. #785 does not include the checkboxes but everything else. Let's see if we still need the filtering or if a hide/show button makes more sense.
