### ISSUE TITLE
Question: Pushover config - message field

### ISSUE THREAD

**Issue by evollusion** [prometheus/alertmanager#756]
I am trying to alter the message that is delivered via push over by using the message option in the receiver config.  However I don't seem to be able to do the likes of {{ range .Labels.SortedPairs }}{{ .Name }} = {{ .Value }}{{ end }}

Is this possible or does it have to be via a custom template ?

**Comment by stuartnelson3** [comment]
Questions regarding usage should be directed to the prometheus-users google group
