### ISSUE TITLE
CSS styling

### ISSUE THREAD

**Issue by mxinden** [prometheus/alertmanager#762]
### How do we want to write CSS?

Right now we only have a style tag in our `index.html`.
I would suggest for the time being to just use a `styles.css` file which is served by the back-end. I am fine with using something that enables *nesting* like [*less*](http://lesscss.org/) but shy at the extra complexity introduced by the needed transpiler.

@w0rm @stuartnelson3 What do you think?

**Comment by w0rm** [comment]
@mxinden I think we should check https://github.com/rtfeldman/elm-css which is a type safe way to write css.

**Comment by mxinden** [comment]
@w0rm Definitely something I want to look into. Both inline and generating css files could be applicable for us.
I am a little afraid of the dependency though. So I would prefer a Spike before fully integrating it into the project. Do you have experience with the library?

**Comment by w0rm** [comment]
I haven't used this library before, but I have heard many good things about it!

**Comment by stuartnelson3** [comment]
I'm hoping that we can get 95% of our styling done wiht bootstrap, and then just a few simple things in a styles.css? I'm hoping we write a small enough amount of css that we don't need to consider less.

**Comment by mxinden** [comment]
So far I would agree with @stuartnelson3 as it introduces the least amount of complexity. I would reconsider the choice if the amount of CSS we write gets out of hand. 

So suggested next steps:
**Move style tag to separate CSS file.**

**Comment by mxinden** [comment]
Closing here as we don't have any custom css right now (See [comment](https://github.com/prometheus/alertmanager/pull/809#discussion_r117636941)). Feel free to reopen.
