### ISSUE TITLE
Update Silences instead of recreating

### ISSUE THREAD

**Issue by mxinden** [prometheus/alertmanager#765]
Currently instead of updating a silence we only create a new one with the updated properties.
< details >

**Comment by mxinden** [comment]
@fabxc Could you add more details to the issue description?

**Comment by fabxc** [comment]
As silences suppress alerts, we want a trackable history of what silences occurred in the past. This means if a silence with a set of matchers is or was active, it should not be possible to change the start (and end) timestamp or the matchers.  Currently the UI just expires a silence and creates a new one on edit. However, from a UX perspective, everything should remain editable and not unnecessarily spam our silence history.

We should add an update endpoint that may either modify an existing silence if it doesn't violate that truth or expire the existing silence and create a new one.

* do not allow editing start and/or end time that lay in the past
* update if modified start and/or end time are in the future or the comment is updated
* expire & re-create if the matchers are modified

This handling should be applied transparently by the update handler.

**Comment by mxinden** [comment]
Fixed by #796
