### ISSUE TITLE
Store record of sent alerts between sessions

### ISSUE THREAD

**Issue by wrouesnel** [prometheus/alertmanager#77]
Currently the alert manager automatically resends all alerts when the session is restarted. Sent alerts should be persisted to disk so that the re-alert timeouts can be preserved between daemon-restarts. 

In the case of alerts such as emails (which may go to shared queues) this is especially important. I'm thinking the simplest answer at the moment would be to adopt the json file approach that silence's use, until some clustering approach is determined.

**Comment by juliusv** [comment]
:+1: This is an obvious missing feature that will be fixed in some of the planned rearchitecting of Alertmanager (no clear ETA on that yet though).

**Comment by brian-brazil** [comment]
The new alertmanager supports this.
