### ISSUE TITLE
opsgenie: alias field garbled with 0.6.0

### ISSUE THREAD

**Issue by davidkarlsen** [prometheus/alertmanager#771]
After upgrading to 0.6.0 the alias field in an opsgenie alert is garbled and looks like this:
�?�ur�龎��R���|H�Ŕ/}V� ��L

**Comment by fabxc** [comment]
This was fixed in 0.6.1. Please upgrade to that release and reopen in case the issue does not disappear.

**Comment by davidkarlsen** [comment]
OK, will have to wait for 0.6.2 since there are some severe issues with locks with 0.6.1: https://github.com/prometheus/alertmanager/pull/760

**Comment by fabxc** [comment]
We can cut 0.6.2. but FWIW, the lock protects something only used in some UI section and it has been around for many releases now. No reason to skip on the 0.6.1 bug fix really :)
