### ISSUE TITLE
0.6.1 crash.

### ISSUE THREAD

**Issue by raypettersen** [prometheus/alertmanager#781]
I know the latest release is 0.6.2, but I would like to report a random crash that occured while version 0.6.1 was running in our test-environment.

The process was dead, and several hundred stacktrace entries was present in logs. I'm not sure how much log is needed to pinpoint and analyze the problem, but here is an entry. I can provide the entire log if needed.

> time="2017-05-08T10:43:56+02:00" level=info msg="maintenance done" component=nflog duration=89.403µs source="nflog.go:303" 
fatal error: concurrent map read and map write

> goroutine 91173 [running]:
runtime.throw(0x9fdd14, 0x21)
        /usr/local/go/src/runtime/panic.go:596 +0x95 fp=0xc4205996a0 sp=0xc420599680
runtime.mapaccess2_fast64(0x946e20, 0xc420191230, 0x9977fdab591796e6, 0xc42017d7a0, 0x7)
        /usr/local/go/src/runtime/hashmap_fast.go:168 +0x1b2 fp=0xc4205996c8 sp=0xc4205996a0
github.com/prometheus/alertmanager/types.(*memMarker).Status(0xc420196fc0, 0x9977fdab591796e6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/prometheus/alertmanager/types/types.go:175 +0xba fp=0xc420599718 sp=0xc4205996c8
github.com/prometheus/alertmanager/types.(*memMarker).Silenced(0xc420196fc0, 0x9977fdab591796e6, 0x9977fdab591796e6, 0x1, 0x0, 0x8)
        /go/src/github.com/prometheus/alertmanager/types/types.go:215 +0x4d fp=0xc4205997a8 sp=0xc420599718
github.com/prometheus/alertmanager/notify.(*SilenceStage).Exec(0xc420978520, 0xc79360, 0xc4202ada40, 0xc42000c168, 0x1, 0x1, 0xc79360, 0xc4202ada40, 0xc42000c168, 0x1, ...)
        /go/src/github.com/prometheus/alertmanager/notify/notify.go:346 +0xba fp=0xc4205998a8 sp=0xc4205997a8
github.com/prometheus/alertmanager/notify.MultiStage.Exec(0xc4205d1080, 0x3, 0x3, 0xc79360, 0xc4202ada40, 0xc42000c160, 0x1, 0x1, 0xc4202ada01, 0x91cfa0, ...)
        /go/src/github.com/prometheus/alertmanager/notify/notify.go:259 +0xa5 fp=0xc420599930 sp=0xc4205998a8
github.com/prometheus/alertmanager/notify.(*MultiStage).Exec(0xc4209788e0, 0xc79360, 0xc4202ada40, 0xc42000c160, 0x1, 0x1, 0xffffffffffffffff, 0xc420599a40, 0x7252d5, 0xc42021b180, ...)
        <autogenerated>:6 +0xad fp=0xc4205999b8 sp=0xc420599930
github.com/prometheus/alertmanager/notify.RoutingStage.Exec(0xc4205d0d20, 0xc79360, 0xc4202ada40, 0xc42000c160, 0x1, 0x1, 0x6, 0x91e020, 0xc42079b530, 0xc42017af80, ...)
        /go/src/github.com/prometheus/alertmanager/notify/notify.go:245 +0xde fp=0xc420599a30 sp=0xc4205999b8
github.com/prometheus/alertmanager/dispatch.(*Dispatcher).processAlert.func1(0xc79360, 0xc4202ada40, 0xc42000c160, 0x1, 0x1, 0x2)
        /go/src/github.com/prometheus/alertmanager/dispatch/dispatch.go:264 +0x86 fp=0xc420599ae8 sp=0xc420599a30
github.com/prometheus/alertmanager/dispatch.(*aggrGroup).run.func1(0xc42000c160, 0x1, 0x1, 0x2)
        /go/src/github.com/prometheus/alertmanager/dispatch/dispatch.go:372 +0x58 fp=0xc420599b28 sp=0xc420599ae8
github.com/prometheus/alertmanager/dispatch.(*aggrGroup).flush(0xc4200e23f0, 0xc420599f20)
        /go/src/github.com/prometheus/alertmanager/dispatch/dispatch.go:432 +0x47f fp=0xc420599d80 sp=0xc420599b28
github.com/prometheus/alertmanager/dispatch.(*aggrGroup).run(0xc4200e23f0, 0xc420733c30)
        /go/src/github.com/prometheus/alertmanager/dispatch/dispatch.go:373 +0x88c fp=0xc420599fd0 sp=0xc420599d80
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc420599fd8 sp=0xc420599fd0
created by github.com/prometheus/alertmanager/dispatch.(*Dispatcher).processAlert
        /go/src/github.com/prometheus/alertmanager/dispatch/dispatch.go:269 +0x32c

>goroutine 1 [chan receive, 7331 minutes]:
main.main()
        /go/src/github.com/prometheus/alertmanager/cmd/alertmanager/main.go:292 +0x1b62

>goroutine 5 [syscall, 7331 minutes]:
os/signal.signal_recv(0x0)
        /usr/local/go/src/runtime/sigqueue.go:116 +0x104
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.1
        /usr/local/go/src/os/signal/signal_unix.go:28 +0x41

>goroutine 10 [select, 2 minutes]:
github.com/prometheus/alertmanager/vendor/github.com/weaveworks/mesh.(*localPeer).actorLoop(0xc420190240, 0xc420066900)
        >/go/src/github.com/prometheus/alertmanager/vendor/github.com/weaveworks/mesh/local_peer.go:141 +0x120
created by github.com/prometheus/alertmanager/vendor/github.com/weaveworks/mesh.newLocalPeer
        >/go/src/github.com/prometheus/alertmanager/vendor/github.com/weaveworks/mesh/local_peer.go:31 +0x12c

>goroutine 11 [select, 2 minutes]:
github.com/prometheus/alertmanager/vendor/github.com/weaveworks/mesh.(*routes).run(0xc420068900, 0xc420066a80, 0xc420066ae0, 0xc420066b40)
        /go/src/github.com/prometheus/alertmanager/vendor/github.com/weaveworks/mesh/routes.go:177 +0x1a3
created by github.com/prometheus/alertmanager/vendor/github.com/weaveworks/mesh.newRoutes
        /go/src/github.com/prometheus/alertmanager/vendor/github.com/weaveworks/mesh/routes.go:44 +0x453

Any ideas on what occured that made alertmanager crash?

**Comment by juliusv** [comment]
Thanks, that sounds exactly like what was fixed in 0.6.2. See https://github.com/prometheus/alertmanager/pull/760.

**Comment by juliusv** [comment]
Closing, but please reopen in case you still get this with the latest version.

**Comment by raypettersen** [comment]
Good to know. Thanks!
