### ISSUE TITLE
Silences placed in future creates a dead-lock.

### ISSUE THREAD

**Issue by raypettersen** [prometheus/alertmanager#783]
When creating a future-silence, the silence is created with a delete button that doesn't function. I see no clear way of disarming or deactivating the silence.

**Comment by w0rm** [comment]
I got into the same issue when working on the new UI. When I want to delete a pending silence I get:

![screen shot 2017-05-20 at 16 26 03](https://cloud.githubusercontent.com/assets/43472/26276844/4e9be822-3d80-11e7-9fcf-5bf49f9f0843.png)

**Comment by fabxc** [comment]
On it.

**Comment by fabxc** [comment]
I fixed the issue semantically. But as we never delete but only expire, afterwards the silence still exists but has an effective duration of 0. It is still shown in the "pending" tab.

I think there are two options: Completely hide any silence at UI or API level where `startsAt == endsAt` or sort it into the "expired" tab even though the start lays in the future.

**Comment by mxinden** [comment]
Another alternative would be to add this logic on the server in [`types.go/CalcSilenceState`](https://github.com/prometheus/alertmanager/blob/master/types/types.go#L352) and set any Silence to `Expired` where `startsAt == endsAt`. What do you think? @w0rm @fabxc

**Comment by matthiasr** [comment]
I would prefer showing them as. It would be surprising to hide them or not,
just because they were expired before or after they begin. A silence that
will never be active has the same effect as one that did have an effect on
the past but not the future.

I think server side is the right place for this logic.

**Comment by raypettersen** [comment]
Hiding will cause confusion. I'd prefer that it is placed in expired.

**Comment by mxinden** [comment]
In #811 @RSamal @fabxc and came up with a third solution. Instead of setting `endsAt` to `startsAt` we can set both to `now`. Thereby the Silence will get the `expired` state by default.
