### ISSUE TITLE
Extending a silence results in ID error.

### ISSUE THREAD

**Issue by raypettersen** [prometheus/alertmanager#784]
If I understand the new scheme of things, silences can never be removed or edited directly. However they can be edited in such a way, that a new silence is created with the modifications.

This actually doesn't work when I try to expand the silence. Let's say extending the silence by +1h, results in the following error.

![selection_847](https://cloud.githubusercontent.com/assets/7197374/25895831/dd7aabca-3581-11e7-85fe-819bf6b62bc7.png)

**Comment by fabxc** [comment]
In 0.7-rc.0 and that copy-on-some-updates behavior is now directly implemented transparently in the backend. Can you verify that it is fixed there?

As you've been running into a ton of issues, it would be great to hear from you whether the new UI is something you'd upgrade to without hesitation. We really want to focus our efforts on that one.

**Comment by raypettersen** [comment]
I'll give it a test-run, and get back to you.

**Comment by raypettersen** [comment]
Looks good @fabxc. I created a silence, and modified start and end without any problems. :-) 

I do have some feedback regarding the new GUI. I'll compose a new issue with a few observations and suggestions.
