### ISSUE TITLE
Alertmanager notifications inconsistency when using mesh

### ISSUE THREAD

**Issue by bkupidura** [prometheus/alertmanager#787]
When you deploy 2 instances of alertmanager (AM#1 and AM#2) with mesh, "failure" of loadbalancer can lead to inconsistency of notification.

Scenario 1:
1) Alert fired by prometheus, send to AM#1
2) Alert still on, reported to AM#2
3) Alert resolved, and all further notification (status resolved) send to AM#1
4) After a while AM#2 will send notification that alert is active (till resolve_timeout)

Scenario 2:
1) Alert fired by prometheus, send to AM#1
2) Alert still on, reported to AM#2
3) Alert still on, and all further notification send to AM#1
4) After resolve_timeout, AM#2 will send resolved notification

This should not happend with `normal` behavior of any loadbalancer, but is busy envs it is possible that alerts from prometheus not be loadbalanced equally between all instances of AM.

Alertmanager should check if any other instance in mesh have update on fired alerts.

**Comment by fabxc** [comment]
Are you load balancing your alerts across Alertmanagers? If yes, you must
not do that. The whole thing is designed for all alerts being sent to every
Alertmanager and it will not work as expected otherwise.

**Comment by bkupidura** [comment]
So instead of using ex. docker-swarm loadbalancer/haproxy user should specify list of all AM to prometheus?

Instead of `-alertmanager.url docker_alertmanager` we should have `-alertmanager.url "http://10.0.0.2:9093,http://10.0.0.3:9093,http://10.0.0.2:9094"`

**Comment by fabxc** [comment]
Yes, that's how it should work.
Note though that in recent Prometheus versions the url flag is deprecated
and the config file has a designated discovery section for Alertmanagers.
You can use all service discovery mechanisms to find Alertmanagers that you
can also use for targets.

**Comment by bkupidura** [comment]
Yeah, i know but its marked as `alpha` :) So we will stay with `-alertmanager.url` for now and move to dns discovery later on. We can close this issue. Thanks!

**Comment by mxinden** [comment]
@fabxc @brancz  Should we add this to the `README.md` to prevent future confusion? If so I will open a PR.

**Comment by fabxc** [comment]
That's probably a good idea
