### ISSUE TITLE
web/static/js/alerts.js should use -web.path-prefix

### ISSUE THREAD

**Issue by bluecmd** [prometheus/alertmanager#79]
Currently the the API is assumed to be located at /api/ which if -web.path-prefix is set it is most likely not.

Looking around how the URLs are constructed, this might be a case of just changing to 'api/..' instead of '/api/..'. I'd be happy to do a pull request either way if I get some guidance on how you want to solve this.

**Comment by a86c6f7964** [comment]
This just him me as well. I would think that you should just bubble up the web.path-prefix using relative urls is not always the most safe.

**Comment by juliusv** [comment]
For Prometheus, we inject the path prefix into the HTML as a global JS variable and then base any self-links on that (https://github.com/prometheus/prometheus/blob/master/web/blob/templates/_base.html#L13). 

So I'd do the same in https://github.com/prometheus/alertmanager/blob/master/web/templates/_base.html and then use that variable in https://github.com/prometheus/alertmanager/blob/master/web/static/js/alerts.js for the API paths.

Actually, let me try to do that right now...

**Comment by juliusv** [comment]
See PR at https://github.com/prometheus/alertmanager/pull/132. I wouldn't want to put much more work into the old Alertmanager at this point, as the new one is making good progress finally. But this should hopefully fix it.
