### ISSUE TITLE
Implement silenced query parameter in /alerts endpoint

### ISSUE THREAD

**Issue by mxinden** [prometheus/alertmanager#797]
The 'silenced' url query parameter is not yet implemented in the /alerts endpoint. We already show a checkbox on the AlertList view and change the query parameter accordingly, but the back-end ignores it.

**Comment by mxinden** [comment]
@stuartnelson3 @w0rm I have added this to milestone v0.7 as I think we should tackle this before the next release. What do you think?

**Comment by stuartnelson3** [comment]
agreed, and it looks like work is already underway :P
