### ISSUE TITLE
Rework SilenceForm

### ISSUE THREAD

**Issue by mxinden** [prometheus/alertmanager#798]
@fabxc and I went over some improvements needed in the *SilenceForm* before v0.7:

* ~~Style SilenceForm and remove *tachyons* classes.~~
* ~~Show an initial matcher example~~
* ~~Instead of editing an expired silence, the UI should open the "new silence" dialog with the matchers from the old silence instead~~
* Make form without matchers invalid. If no matchers are specified "Create silence" button should be deactivated.

**Comment by stuartnelson3** [comment]
I would add that we should have some visual indication that the creator and comment field need to be filled in. Currently, a silence cannot be created without those being filled in (in the UI), but some indication would clarify that.

**Comment by w0rm** [comment]
@mxinden Editing duration puts the wrong value in the end time field

![screen shot 2017-05-19 at 19 57 07](https://cloud.githubusercontent.com/assets/43472/26260771/c6296a16-3cce-11e7-8d93-648a593870b0.png)
 and end time broke.

**Comment by w0rm** [comment]
@mxinden If you don't mind I can fix this and maybe address the initial validation state. 

`type alias ValidatedField a = { value: String, validation: Result String a }` instead of `Result (String, String) (String, a)`

**Comment by mxinden** [comment]
Sounds like a good idea. Thanks, and sorry for introducing the bug.

**Comment by w0rm** [comment]
@mxinden it's fine. I could've probably noticed this earlier! My plan is to complete this early next week, so that I can demo the new UI at work on Friday.

**Comment by mxinden** [comment]
Updated issue. Most things are fixed by #806 & #827. Only things missing is:

> Make form without matchers invalid. If no matchers are specified "Create silence" button should be deactivated.

**Comment by w0rm** [comment]
@mxinden it is impossible to have a form without matchers now, so this is fixed.
