### ISSUE TITLE
Filtering alerts by receivers

### ISSUE THREAD

**Issue by w0rm** [prometheus/alertmanager#800]
Alerts could be filtered by receivers in the old UI. I think receivers make sense, from a perspective of being on call, I can quickly get all alerts that I am responsible for, without having to memorize all the labels and manually entering them into the filter bar.

It also allows me to filter out the alerts I am responsible for, even if they have totally different labels, so it is some kind of `OR` operation for the matchers that is impossible with the new filter bar.

We stopped filtering by receivers when we switched away from grouped endpoint to the `/alerts` endpoint. Since this affects the way the old UI is used at the moment, I wonder what is the plan for this feature or is there something that we can offer instead?

**Comment by stuartnelson3** [comment]
I remember we discussed moving away from receivers the last time we were all together talking about this, but I don't remember the reasoning any more. I think the main point here that makes sense is being able to easily filter alerts with disparate labelsets but that I (as an operator) am interested in because I'm on-call.

What was the reason for getting rid of receivers? @fabxc @mxinden @brancz

**Comment by fabxc** [comment]
It's a consequence of switching to a flat view of all alerts.
We can add it back later. Probably by annotating alerts with this information or correlating it with the notification log.

**Comment by fabxc** [comment]
I'm somewhat worried about an explosion of options for views and clicking around them will not be really good UX.

Textual options were brought up in the past. I think that would be a good idea here.
Can we maybe filter by `silenced:true`, `silenced:false`, and `receiver:<name>` inline with the label selectors? Potentially even `group(a,b)` later.
Less clicky-pointy but not really complex and more powerful once learned.

**Comment by brancz** [comment]
Yes, I think this is very powerful. I imagine it like GitHub style issue/PR search.

**Comment by w0rm** [comment]
Can we support the `receiver` param in the `/alerts` endpoint, and add another endpoint to get the list of receivers for the dropdown in the UI?

**Comment by beorn7** [comment]
Talked to @w0rm about it. Conclusion was to have an endpoint to find out about all configured receivers (for a UI component to select them).
The alerts endpoint needs an additional parameter, which is a regexp of the receiver (so you can match things like `teamX.*`, which would include `teamX-warn`, `teamX-crit`, and `teamX-info`, or lists, e.g. `foo|bar|baz`).

It would then be nice to give each alert a field `receivers` with a list of receivers this alert goes to. This could be displayed in the _Info_ section to easily see who got this alert.

In ever later iterations of the UI, each receiver could be linked to information how this receiver is configured.

This is all in priority order. It is right now really tough to work with the current Alertmanager in an organization of SoundCloud size and more as you have a huge soup of alerts, but it is hard to see the alerts you are in charge of. So the ability to jump to alerts filtered by receiver via the URL and/or via an easy UI selector is crucial. (Pages are pretty clear, but everything sub-page level is usually linked to a workflow like the following: "OK, I'm on-call now, and I'm not paged right now.. Let's see if there is any ticket-level alert I should work on. And to feel super comfortable before I go to bed, let's also check the Info level alerts for a final check of life signs.")

**Comment by stuartnelson3** [comment]
I added initial back-end support for filtering by receiver and including the receiver in `info` in #872, but did not expose the list of all receivers. There are some conflicting UX suggestions, between using a ui-component to suggest receivers or using textual options (`receiver:backend-.*`).

How do we want to move forward? If we go with textual options, potentially we still want to populate a list of receivers to show for auto-completion help when a user types `receivers:` in the filter box? (If we could pull that off, it would be super cool IMO)

**Comment by w0rm** [comment]
I don't think that receivers should be in the filter box, because it is different from labels, a label may only have one value, while a receiver is a list of values. It will be hard to mix them together.

What about having a separate autocomplete somewhere as the first iteration?

**Comment by stuartnelson3** [comment]
I'm fine with that.

I was imagining a receiver being a single value (turned into a regex) that the user provides, so `receiver=(backend-ops|frontend-thing|network-tightening)` if they want to see multiple receivers

**Comment by w0rm** [comment]
@stuartnelson3 why not a multi-select (that is kept internally as a set of strings)? We have a fixed amount of receivers, so there is no need to regex match over them.

**Comment by beorn7** [comment]
The problem with the receiver (and even other things like `silenced:true` etc) as textual options (see @fabxc `s suggestion above) has the problem of a possible collision with labels names. `receiver` is something I can imagine to show up as a useful label name (outside of the context of alerting) quite often.
I share concerns about polluting the UI, but the filtering by receiver is quite important. Does somebody have an idea how to represent the receiver as a textual option while avoiding collision with a label named 'receiver'? If not, I'd go with a separate UI element for now.

**Comment by fabxc** [comment]
My idea was to have those use `key:val` and label selectors `key=val`. Maybe a subtle difference but I'm not really concerned that it will be too hard to understand.

**Comment by stuartnelson3** [comment]
@w0rm I thought having a regex match was desired, so `prodeng-*` would be acceptable in addition to being able to select `prodeng-crit` and `prodeng-warn`, for example.

@beorn7 , do you want the regex? I remember that being one of the things you were initially interested in.

 I think if we implement this as @fabxc suggests it would make a lot more sense to do the regex. The `silenced:true` syntax is entering common usage, I think, so potentially just updating the help text under the filter input would be enough to inform people?

**Comment by brancz** [comment]
Sorry for not commenting here, but I commented some of my thoughts here: https://github.com/prometheus/alertmanager/pull/872#discussion_r122640780

**Comment by beorn7** [comment]
@fabxc Indeed, it was too subtle for me. Personally, I like the idea. But I'm not sure if it will cause more confusion than good. I imagine naive users won't even think about `receiver` not being a label and will type `receiver="my-team"` instead of `receiver:my-team`. They will see no alerts and go to bed in ignorance.

@stuartnelson3 I would definitely go for the regexp in the URL so that I can easily link to something like "all my alerts". I don't feel strongly if the UI translates that into a list where you can select multiple fields or a textual field where you can enter regexps (perhaps assisted by autocompletion). But I'm also trained to edit URLs directly a lot. **cough**

**Comment by w0rm** [comment]
I added a simple dropdown that should temporary address the current use case. Because regex in the url is still supported, it is possible to manually edit the url to filter by regex. 

![receiver](https://user-images.githubusercontent.com/43472/27304363-23e82dea-553e-11e7-9ff2-81f4b6920464.gif)

**Comment by w0rm** [comment]
I'm not sure if all links from the alerts will work when the receiver parameter is a regexp.

**Comment by beorn7** [comment]
Wouldn't an edit field with autocompletion have the same effect as the dropdown, with the added value that you can just type in a regexp?

About the links: I guess we need to escape receivers that happen to contain special characters of a regexp.

**Comment by w0rm** [comment]
@beorn7 sure, we can and should improve the UI of this feature. I worked on this after work, and did the best I could considering the time I had and the importance of the feature.

**Comment by beorn7** [comment]
Yes, much appreciated.

**Comment by stuartnelson3** [comment]
Closed by #872
