### ISSUE TITLE
Add Inhibited indicator to UI

### ISSUE THREAD

**Issue by stuartnelson3** [prometheus/alertmanager#801]
From this comment thread: https://github.com/prometheus/alertmanager/pull/799#discussion_r116765232

Just add a `inhibited` tag if that's the alert's status.

**Comment by mxinden** [comment]
I would like to extend this issue. In addition we should also tag silenced alerts with a `silenced` tag.

This was pointed out by Jack [here](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/prometheus-users/QBTPLmB5c2o/RGDKytieAwAJ):

> There is a checkbox to show silenced alerts, but when they are shown there's no indication which of the shown alerts are silenced.
