### ISSUE TITLE
Issue with alert grouping

### ISSUE THREAD

**Issue by fabxc** [prometheus/alertmanager#802]
The grouping part has "alertname" in there by default.
If I remove it and try to add it again, the UI doesn't let me but doesn't tell me why.

<img width="1075" alt="screen shot 2017-05-17 at 10 49 52" src="https://cloud.githubusercontent.com/assets/4948210/26145962/cb6fb822-3aee-11e7-8bbf-ac882771b807.png">

**Comment by mxinden** [comment]
@fabxc Works fine on my machine with the following click path:
1. Go to *Group* tab
2. Remove group *alertname* via `x` button
3. Type 'alertname'
4. Press `enter`

Can you help me reproduce the bug? Am I missing a step?

**Comment by fabxc** [comment]
I did exactly that. In fact, just trying to add anything does not work for me. But as there no errors anyway, I can't say much more.

**Comment by fabxc** [comment]
Ah, so it validates that the label name actually exists.
I think in general that doesn't really matter. Grouping by a label that has value "" for everything still does the right thing. I could imagine that it gets kind of tedious when I know what grouping I want but haven't applied the right filter yet, causing me to switch back and forth between filter and group.

Anyway, definitely not a bug, just a behavior which we should keep an eye on. For now we can keep it.
