### ISSUE TITLE
Allow aggregations based on alert names

### ISSUE THREAD

**Issue by wrouesnel** [prometheus/alertmanager#81]
Something I'm setting up right now - I have an alert where I just want to grab a specific alert name for a temporary scheme (in this case DiskSpaceAlert) rather then monitoring a swathe of systems.

This is a pretty common use case when you have system ownership, or (as in my current case) are running a long running job and want special case alerts to go to just 1 or several people.

**Comment by brian-brazil** [comment]
This should already be possible, see the example on http://prometheus.io/blog/2015/06/18/practical-anomaly-detection/#automatic-actions

**Comment by wrouesnel** [comment]
Now I feel silly since I read that bit of the documentation. 

The alertname gets listed separately in the big list (or at least that's why I made the mistake). Closing this - thanks!
