### ISSUE TITLE
Alert sorting in 0.7 is not consistent.

### ISSUE THREAD

**Issue by raypettersen** [prometheus/alertmanager#812]
When testing the RC, issues are rendered in different order on each refresh. Can be reproduced simply by reloading the page, or toggling the silence switch.

Not a big issue (more an annoyance), but a bit confusing for the end-user. Suggest sorting by start-date, perhaps with a per-alertname toggle so the end user can sort by newest or oldest.

**Comment by w0rm** [comment]
Agree! I wonder if the sorting (most recent first) can be done in the api.

**Comment by stuartnelson3** [comment]
This will be addressed in #872

**Comment by mxinden** [comment]
This issue still persists.

**Comment by stuartnelson3** [comment]
closed by #969
