### ISSUE TITLE
0.7 Create silence workflow suggestion.

### ISSUE THREAD

**Issue by raypettersen** [prometheus/alertmanager#814]
I have an improvement suggestion when creating alarms. In the new GUI, a silence results in a "report" page. I would like this to be changed to a confirm step, so the end user can review the silence-output before enabling it, or clicking "back/cancel". 

On a side-note, any chance of getting the silence rendered in cli-format for easy future automation? I've been using development tools for getting the output when scripting nightly silences and so forth. Would be a neat feature to have an easy way of extracting the curl syntax.

**Comment by mxinden** [comment]
After creating a Silence the user is just redirected to the Silence view. I would vote against an additional step in the Silence creation process. The user can already see on the Silence form page which alerts are going to be silenced by clicking the "Show affected silences" button. @stuartnelson3 @w0rm What do you think?

What do you mean by "rendered in cli-format"?

**Comment by w0rm** [comment]
@mxinden yeah, we do have a way to preview affected alerts before creating a silence.

**Comment by raypettersen** [comment]
Ah, just noticed the affected alerts button. That's a great feature!

@mxinden, for example:
`'{"matchers":[{"name":"alertname","value":"(^TEST)$","isRegex":true}],"startsAt":"2018-05-11T00:00:00.000Z","endsAt":"2018-05-11T07:00:00.000Z","createdAt":"2018-11-15T22:11:20.223119156+02:00","createdBy":"test@test.com","comment":"autogenerated-TEST","updatedAt":null,"elapsed":false,"pending":false,"active":true}'`

Just for easy extraction, and something that's inspired from working with cisco (there is a gui, but you can view the config changes as text as well). Might be something that isn't particularly useful for everyone though. Just mentioning it in case it's a low hanging fruit. Perhaps tie it to a clipboard button next to the affected alerts. Just close as won't fix if it offers no real value.

**Comment by mxinden** [comment]
@raypettersen Sure, sounds like a good idea. @fabxc Is this something the Prometheus eco system should invest into / was this demanded ever before?

**Comment by fabxc** [comment]
Essentially like a button "Copy as curl" you can click, which then pops up a little text box with a commend? For sure. Could've used something like that for Prometheus queries tons of times in the past, so why not here too.

**Comment by mxinden** [comment]
Closing here then. I have created a follow up issue to tackle the latter suggestion (See #817). @raypettersen If you are eager to try out  some Elm, feel free to file a PR. Otherwise we will implement it later.

Feel free to reopen if you have further questions.

**Comment by raypettersen** [comment]
Cheers. Great work guys.
