### ISSUE TITLE
Test if back-referencing to Alertmanager from receiver still works

### ISSUE THREAD

**Issue by mxinden** [prometheus/alertmanager#816]
Test whether the back-referencing link still works with the new UI. As the UI format changed, this is probably going to be broken. The user should be redirected to the Alertlist page with specific filters and grouping already in place.

**Comment by mxinden** [comment]
For now this is partly fixed by this [commit](https://github.com/prometheus/alertmanager/commit/b3d2ff368885430b25590bafbe0fce7132a101de). I will move this to milestone v0.8. Feel free to intervene.

**Comment by w0rm** [comment]
Closed via #872
