### ISSUE TITLE
Issue while building from source

### ISSUE THREAD

**Issue by RSamal** [prometheus/alertmanager#819]
Hi I get the below error while doing  "GO15VENDOREXPERIMENT=1 go get github.com/prometheus/alertmanager/cmd/...".  I use go 1.7 version. 

# github.com/prometheus/alertmanager/vendor/github.com/weaveworks/mesh
github.com/prometheus/alertmanager/vendor/github.com/weaveworks/mesh/token_bucket.go:33: undefined: time.Until

**Comment by RSamal** [comment]
Just upgraded to 1.8 and it works. I guess the vendor project is broken with lower version

**Comment by fabxc** [comment]
Yes, it uses the new `time.Until` function, which was added with go 1.8
