### ISSUE TITLE
Display alert annotations

### ISSUE THREAD

**Issue by r4j4h** [prometheus/alertmanager#821]
The old UI used to contain current alerts listed by labels with silence buttons, as does the new UI.

To the left of the labels list in the old UI there used to be a Source link with a `+` button. Upon clicking the plus, a "panel" would pop out beneath showing the actual "hydrated" alert text.

The new UI seems to be missing this functionality.

For example, if the alert was `Low Quorom: There's only {{value}} things!` in Prometheus' config view here it would show up as `Low Quorom: There's only 3 things!` if the represented time series' value was 3.

Here's some pictures for a better illustration:

Prometheus example:

![prom](https://cloud.githubusercontent.com/assets/703007/26379395/f48dccce-3fcd-11e7-8beb-f51b11cca766.png)

0.6 example, with + button already clicked:

![0 6](https://cloud.githubusercontent.com/assets/703007/26379393/f10c47b0-3fcd-11e7-96d0-70065c74a13c.png)

0.7 of the same alert, notice there is a Source button but if there is an expander I do not see it :(

![0 7](https://cloud.githubusercontent.com/assets/703007/26379394/f2d38eaa-3fcd-11e7-97aa-5b4a1abcb6de.png)

**Comment by mxinden** [comment]
Thanks for the feedback! You are right, we are not displaying the alert annotations which we should definitely do. I will rename the issue title accordingly if you don't mind.

**Comment by w0rm** [comment]
Can it go in 0.7? I'll be happy to work on this. I think we should prioritize feature compatibility with the old UI.

**Comment by mxinden** [comment]
@w0rm Yes, if you curl the `/alerts` endpoint you will find an `annotations` field. You can find the server side implementation [here](https://github.com/prometheus/alertmanager/blob/master/vendor/github.com/prometheus/common/model/alert.go#L35). It should be an array just like `labels`.

👍 For focusing on feature parity.

**Comment by r4j4h** [comment]
🎊
