### ISSUE TITLE
How can I use slackAttachmentField in slack receiver?

### ISSUE THREAD

**Issue by odg0318** [prometheus/alertmanager#822]
Hello.

I try to use slack as a receiver and examine slack formatting.
I found `slackAttachmentField` struct which could be used for `fields` in slack formatting.
But there is no way to set the field through alertamanger configuration.
I want to show all labels of metrics using `fields` of slack.

Best regards.

**Comment by mxinden** [comment]
@odg0318 Sorry that we have not followed up on this. I will close here. Please feel free to reopen, if this issue still persists. In general, if you have usage questions please open them in the [*Prometheus users Google group*](https://groups.google.com/forum/#!forum/prometheus-users).

**Comment by jutley** [comment]
I'm also interested in this. It's odd that there's a structure for Slack fields, but there isn't any way to actually use them. Is there a reason for this? Or has it just not been implemented yet?
