### ISSUE TITLE
Sending mail without authentication

### ISSUE THREAD

**Issue by titansmc** [prometheus/alertmanager#828]
Hi, I've just installed Alertmanager along with prometheus and grafana, and when setting up the mail to be able to receive email alerts I don't see an option for sending emails (in my case using the Gmail servers) without authentication. 
Since we have Google mail services, we can just use their SMTP without authentication. 

Does anyone know whether that is possible with alertmanager?

Thank you.

**Comment by brian-brazil** [comment]
Please ask usage questions at https://groups.google.com/forum/#!aboutgroup/prometheus-users

Nowhere is it documented that you need to use authentication.
