### ISSUE TITLE
GeneratorURL generates wrong link

### ISSUE THREAD

**Issue by ynnt** [prometheus/alertmanager#83]
I setuped notifications via Slack and all is ok. However link I receive is always broken:
Here is example:
bls:9090/graph#%5B%7B%22expr%22%3A%22up%20%3D%3D%200%22%2C%22tab%22%3A0%7D%5D

**Comment by juliusv** [comment]
What part of it is broken for you? The missing scheme (I guess Slack is just hiding that), or the hostname/port? Everything after that looks correct at least.

What would you expect the correct link to be?

**Comment by a-pastushenko** [comment]
Broken part is hostname.
It should be hostname I guess, instead I have that: 482d0491c1bd

**Comment by matthiasr** [comment]
Are you running in Docker? In that case, that _is_ the hostname processes inside the container see. Cf. prometheus/prometheus#716 for the same issue in Prometheus. I guess the same solution would apply here.

**Comment by a-pastushenko** [comment]
Yes, thank you, it helped me.
