### ISSUE TITLE
Parse the error from the backend

### ISSUE THREAD

**Issue by w0rm** [prometheus/alertmanager#830]
![screen shot 2017-05-26 at 16 34 25](https://cloud.githubusercontent.com/assets/43472/26499017/608e9146-4231-11e7-9568-e6977b541a5a.png)

![screen shot 2017-05-26 at 16 37 24](https://cloud.githubusercontent.com/assets/43472/26499099/a4f73db0-4231-11e7-88e4-ef18379d6d00.png)

I guess we can add a json parser that would try to extract the "error" message, so we don't show the json in plaintext.

**Comment by stuartnelson3** [comment]
This is the standard error format for both alertmanager and prometheus, will be nice to have this
