### ISSUE TITLE
Serve Bootstrap css by Alertmanager

### ISSUE THREAD

**Issue by mxinden** [prometheus/alertmanager#846]
Do not load Bootstrap CSS from the Bootstrap CDN but serve it with Alertmanager itself.

**Comment by ianfriend** [comment]
Seems to be an error on windows returning 404 errors getting the assets.  Should they been embedded in the exe or assets shipped in the tar?

**Comment by mxinden** [comment]
@ianfriend They should be embedded in the `exe` file. Does the log output of Alertmanager give any more details?
If this issue still persists, please open up an issue. Thanks for reporting.

**Comment by mxinden** [comment]
@ianfriend Any updates on this?

**Comment by ianfriend** [comment]
@mxinden yes i opened a ticket #869 and seemed to be a caching issue.  redownloaded package, cleared cache and then began working so all resolved now. Thanks for the help.
