### ISSUE TITLE
Issue with UI Status page config details

### ISSUE THREAD

**Issue by RSamal** [prometheus/alertmanager#854]
Hi,

Why am I seeing all unnecessary details in my config status. All the template details are getting added in receivers. Also the groupby clase getting expanded with "-"
`global:
  resolve_timeout: 5w
  smtp_from: ""
  smtp_smarthost: ""
  smtp_auth_username: ""
  smtp_auth_password: null
  smtp_auth_secret: null
  smtp_auth_identity: ""
  smtp_require_tls: true
  slack_api_url: null
  pagerduty_url: https://events.pagerduty.com/generic/2010-04-15/create_event.json
  hipchat_url: https://api.hipchat.com/
  hipchat_auth_token: null
  opsgenie_api_host: https://api.opsgenie.com/
  victorops_api_url: https://alert.victorops.com/integrations/generic/20131114/alert/
route:
  receiver: default-reciever
  routes:
  - receiver: team-xxx-yy-pager
    group_by:
    - xxx
    - yyy
    match:
   ....
......

  - name: team-xxxx-yy-pager
  pagerduty_configs:
  - send_resolved: true
    service_key: <secret>
    url: https://events.pagerduty.com/generic/2010-04-15/create_event.json
    client: '{{ template "pagerduty.default.client" . }}'
    client_url: '{{ template "pagerduty.default.clientURL" . }}'
    description: '{{ template "pagerduty.default.description" .}}'
    details:
      firing: '{{ template "pagerduty.default.instances" .Alerts.Firing }}'
      num_firing: '{{ .Alerts.Firing | len }}'
      num_resolved: '{{ .Alerts.Resolved | len }}'
      resolved: '{{ template "pagerduty.default.instances" .Alerts.Resolved }}'
`

**Comment by RSamal** [comment]
<img width="1211" alt="screen shot 2017-06-08 at 2 03 36 pm" src="https://user-images.githubusercontent.com/5267629/26950708-5d88fcee-4c53-11e7-8bd0-a5dd80d752a0.png">

**Comment by RSamal** [comment]
<img width="974" alt="screen shot 2017-06-08 at 2 04 52 pm" src="https://user-images.githubusercontent.com/5267629/26950730-7b235d94-4c53-11e7-963d-5a979f58373e.png">

**Comment by RSamal** [comment]
@mxinden  Why all the templates are showing up here in the config file , which was not before . It was much clear before. Now it's little bit messy to look up

**Comment by brancz** [comment]
@RSamal this is unfortunately a technical necessity, before we showed the actually loaded plain text config, however, that doesn't allow us to reliably elide secrets from the config, therefore we parse the config, and marshal it again, making sure that anything containing a secret is elided in this step.

**Comment by mxinden** [comment]
@RSamal Thanks for reporting! As @brancz described this was a technical choice we had to take. I will close here for now. Feel free to reopen if you have any suggestions how to improve this.

**Comment by jonathansantilli** [comment]
Hello @brancz @mxinden it means we are reporting or sending data to those endpoints?

**Comment by mxinden** [comment]
@jonathansantilli no, that should not be the case. Those are only the default configurations. Unless you configure them in the receiver section, Alertmanager will not connect to those endpoints.

**Comment by jonathansantilli** [comment]
Thanks a lot @mxinden for the clarification
