### ISSUE TITLE
0.7.0 - filtering doesn't work in Chrome

### ISSUE THREAD

**Issue by jhorwit2** [prometheus/alertmanager#855]
I'm trying to add a simple filter `namespace=tyrell-test` and i receive the following error. 

```
script.js:1 Uncaught DOMException: Failed to execute 'pushState' on 'History': A history state object with URL 'http:/#/alerts?silenced=false&filter=%7Bnamespace%3D%22tyrell-test%22%7D' cannot be created in a document with origin 'http://asx001.clearspring.local:9093' and URL 'http://asx001.clearspring.local:9093/#/alerts'.
```

**Comment by mxinden** [comment]
@jhorwit2 Thanks for reporting! I have created PR #856 with a fix. Does this version resolve your issue?

**Comment by jhorwit2** [comment]
I'll do a build tomorrow and test it out. 👍

**Comment by mxinden** [comment]
@jhorwit2 You can check out release v0.7.1 here: https://github.com/prometheus/alertmanager/releases/tag/v0.7.1

**Comment by w0rm** [comment]
This is fixed
