### ISSUE TITLE
Missing option to filter alerts by receiver

### ISSUE THREAD

**Issue by grobie** [prometheus/alertmanager#863]
With the new UI introduced in v0.7 I can't find an option to show all alerts assigned to me/my receiver. As team with diverse responsibilities, very different label combinations end up in my receiver.

Is there any workaround? I tried the label `receiver="my-team"` but that didn't work.

**Comment by mxinden** [comment]
Duplicate of #800. Closing here. Please reopen if I am mistaken. As far as I am aware there is no workaround.

**Comment by grobie** [comment]
Oops, thanks @mxinden. I missed that, but can I ask to prioritize it? It's quite hard to see all alerts for my team now.

**Comment by mxinden** [comment]
@grobie No worries. It is part of the 0.8 milestone, so we would add it in the upcoming release.
