### ISSUE TITLE
Format Value become scientific

### ISSUE THREAD

**Issue by kevincm** [prometheus/alertmanager#865]
I got some question regarding `{{ $values }}` usage,

I have basic alert which sending it to our slack:
this is the working one : `Redis Server  keys has increased 77.45077806845111%.`

while, this is the issue : `Production Server insert_shop_response Channel Depth is over (Current : 8.838815e+06).`

_note : i removed my instance labels_

the problem is `8.838815e+06` value. 

this is snippet of my config in alerts.rules 

`summary = "Production Server {{ $labels.instance }} {{ $labels.topic }} Channel Depth is over (Current : {{ $value }}).",`

anyway to fix the value format ?

**Comment by brian-brazil** [comment]
Usage questions are best asked at https://groups.google.com/forum/#!forum/prometheus-users

**Comment by satterly** [comment]
`{{ $value | printf "%.2f" }}` will round to two decimal places.

**Comment by ellutionist** [comment]
> `{{ $value | printf "%.2f" }}` will round to two decimal places or `{{ humanize $value }}`.
Is there any doc for such syntax? Thanks.

**Comment by nelsonstudent** [comment]
From what I've researched, Prometheus follows the RE2 syntax. Here are the links I searched.
https://prometheus.io/docs/prometheus/latest/querying/examples/
https://github.com/google/re2/wiki/Syntax

**Comment by m44soroush** [comment]
You can use this too:
{{ $value | humanizePercentage }}
