### ISSUE TITLE
UI returns 404 getting assets on windows.

### ISSUE THREAD

**Issue by ianfriend** [prometheus/alertmanager#869]
In version 0.7.1 with the self served assets, when installed on windows loading the UI returns 404's GETting the assets.
Log output:
time="2017-06-16T15:54:51Z" level=warning msg="Could not get file: AssetInfo ui\lib\jquery.min.js not found" source="web.go:31"

**Comment by stuartnelson3** [comment]
That file does not exist in the repo, it was removed in this commit: https://github.com/prometheus/alertmanager/commit/971a6b466013492d186c454cb5936ae579d71047

The new ui does not use jquery. I'm guessing you're seeing a caching issue.

**Comment by ianfriend** [comment]
You're absolutely right, re-downloaded 0.7.1 package, copied the exe and cleared cache...now working.  Thanks.
