### ISSUE TITLE
Unable to make the project

### ISSUE THREAD

**Issue by san213** [prometheus/alertmanager#87]
I am unable to make the project, I get the following error.

GOROOT=/usr/local/Cellar/go/1.4.2/libexec GOPATH=/Users/dummyuser/workspace/alertmanager/.build/gopath /usr/local/Cellar/go/1.4.2/libexec/bin/go get -d
go: missing Mercurial command. See http://golang.org/s/gogetcmd
package bitbucket.org/ww/goautoneg: exec: "hg": executable file not found in $PATH
make: *** [dependencies-stamp] Error 1

**Comment by brian-brazil** [comment]
Try installing mercurial, as some dependencies are stored in mercurial repositories.

**Comment by san213** [comment]
Got it. Thanx. Installed mercurial.
