### ISSUE TITLE
PagerDuty v1 API will be unsupported from February 2018

### ISSUE THREAD

**Issue by mattbostock** [prometheus/alertmanager#877]
See:
https://v2.developer.pagerduty.com/v2/docs/api-v2-frequently-asked-questions

> API v1 will be supported until February 6, 2018

We should migrate to v2.

**Comment by AndreiDuma** [comment]
This would be very helpful. Right now it seems like PagerDuty's formatting of AlertManager alerts is quite limited (because of non PD-CEF compliance). Events API v2 seems to solve that problem.

**Comment by taion809** [comment]
I've started working on this, I have a WIP branch here: https://github.com/taion809/alertmanager/tree/maint-upgrade-to-pd-events-v2

I expect to have it tested against PD this week.

**Comment by taion809** [comment]
my coworker @scarvel8 is actually going to take this instead of me

**Comment by scarvel8** [comment]
Submitted as PR #1054
