### ISSUE TITLE
JSON api for unsilenced alerts

### ISSUE THREAD

**Issue by wrouesnel** [prometheus/alertmanager#88]
With the /api/alerts interface, the next immediate problem is having a quick way to get unsilenced alerts (or silenced alerts) without having to make a lot of calls to the silence API and without needing to externally duplicate the alertmanager silencing logic.

I'm presently thinking `/api/alerts/silenced` and `/api/alerts/unsilenced` but that feels slightly unclean.

**Comment by fabxc** [comment]
This is refering to the old Alertmanager. The new one allows to filter out silenced alerts in the UI.
