### ISSUE TITLE
Duplicated notification (with group_interval)

### ISSUE THREAD

**Issue by iksaif** [prometheus/alertmanager#880]
This is a follow up of https://github.com/prometheus/alertmanager/issues/697#issuecomment-310616402

I have a multiple prometheus instances sending ~10 alerts with the same alertname, occasionally the alertmanager will generate two notifications instead of one. I'm using the default group_interval (which is supposed to be 5m).

I tracked down what happens, and it looks like the 10 alerts are received in two batches:
* the first will trigger a first notification directly (in this case because prometheus was started before the alertmanager, so `alert.startAt` is pretty old and `group_wait` doesn't apply).
* the second will find matching alerts in the notification log, will find some, and call `needsUpdate` (https://github.com/prometheus/alertmanager/blob/master/notify/notify.go#L473):

```
func (n *DedupStage) needsUpdate(entry *nflogpb.Entry, firing, resolved map[uint64]struct{}, repeat time.Duration) (bool, error) {
	// If we haven't notified about the alert group before, notify right away
	// unless we only have resolved alerts.
	if entry == nil {
		return len(firing) > 0, nil
	}

	if !entry.IsFiringSubset(firing) {
		return true, nil
	}

	if n.sendResolved && !entry.IsResolvedSubset(resolved) {
		return true, nil
	}

	// Nothing changed, only notify if the repeat interval has passed.
	return entry.Timestamp.Before(n.now().Add(-repeat)), nil
}
```

In this case, entry is disjoint from firing, so the function will return `true`, and a second notification will be sent.

This behavior doesn't seem to match the documentation:

```
  # When the first notification was sent, wait 'group_interval' to send a batch
  # of new alerts that started firing for that group.
  group_interval: 5m
```

This doesn't seem to make assumption on the either the previously or currently firing alerts and it seems it would just silence the second notification.

What do you think was the intent here ? Should the documentation of the code be changed ?

**Comment by mxinden** [comment]
@iksaif Can you post the alerts and the full alertmanager config file as well?

Why is `entry` disjoint from `firing`? I guess you are talking about the 
``` go
if !entry.IsFiringSubset(firing) {
	return true, nil
}
```
branch of the `needsUpdate` function? `entry.IsFiringSubset(firing)` should return `true`, if the alerts have the same name and labelsets, which is then negated.

**Comment by iksaif** [comment]
I don't have access to the configuration here, but the two batches of alerts would look like:

{code}
First batch:
GraphitePointLoss{env="prod",dc="dc1"}
GraphitePointLoss[env="prod",dc="dc2"}

Second batch:
GraphitePointLoss{env="prod",dc="dc3"}
GraphitePointLoss{env="prod",dc="dc4"}
{code}

The configuration contains a `group_by [alertname, env]` in order to ignore the dc and not `group_wait` override.

That being said, `needsUpdate` doesn't seem to access `GroupInterval`, so the issue must be somewhere else. But I would expect that even if `needsUpdate` returns True  `group_interval` should still prevent a second notification to be sent (except if it is because the alert is resolved)

**Comment by mxinden** [comment]
@iksaif I am still facing issues reproducing this. Can you give me a minimal config with which you are able to reproduce the issue?

**Comment by iksaif** [comment]
Hard to send a minimal config that would do that without also write a component sending a batch of alerts. That being said, now that the (non related) ordering issue of matchers have been fixed, the second notification is not really an issue anymore (since both are sent with the same alias).

I think the only bug here is that group_interval is ignored if needsUpdate returns true which doesn't really match the documentation.

**Comment by mxinden** [comment]
@iksaif You can use the [send_alerts.sh](https://github.com/prometheus/alertmanager/blob/master/examples/ha/send_alerts.sh) script and the [webhook](https://github.com/prometheus/alertmanager/blob/master/examples/webhook/echo.go).

**Comment by iksaif** [comment]
Looks like this doesn't happen anymore. 
I suspect this was also fixed by https://github.com/prometheus/alertmanager/pull/882

**Comment by mxinden** [comment]
@iksaif perfect. Thanks for the feedback!
