### ISSUE TITLE
Display URLs as links in labels and annotations

### ISSUE THREAD

**Issue by grobie** [prometheus/alertmanager#884]
It's common to include links in annotations and labels, e.g. to runbooks or dashboards. Detect them and render them as real link.

@w0rm

**Comment by beorn7** [comment]
That's also one of the items on my wish list.

**Comment by mxinden** [comment]
@grobie @beorn7 links in annotations are now clickable thanks to @w0rm (#946).

I do understand @w0rm concern of having links in a label. From your point of view, are rendered links in the Alert annotations good enough, or are links in labels a very common use case which we should support?
> I'm not sure that the links in labels should be clickable, I think it would be too much and might affect the rendering performance of the alert list.

**Comment by grobie** [comment]
I think starting with links in annotations should be enough. I just checked and couldn't find any links in in labels at SoundCloud. If someone has a need for that, they should add a new issue and we can discuss alternative solutions or whether it's worth to add such feature.

Thanks a lot for the feature @w0rm!
