### ISSUE TITLE
Make label text selectable

### ISSUE THREAD

**Issue by beorn7** [prometheus/alertmanager#887]
After discussing it with @w0rm , this seems to be a hard one…

Let me explain:

A very common workflow is the following:
- I'm looking at an alert with an instance label, e.g. `instance="10.20.30.40:9100"`.
- Now I want to ssh into the instance, so I select `10.20.30.40` and use my favorite copy&paste key sequences to get `ssh 10.20.30.40` into my command line.

The problem with the new UI is that all the labels are buttons, and text on buttons is not selectable.

My work-around is the following:
- Click on the label, e.g. `instance="10.20.30.40:9100"`, which pushes that label into the filter box.
- Click on the filter item, which makes it editable.
- Select the now editable text.

This is not only cumbersome, it is also very hard to discover for new users.

Is there an HTML hack to make text on buttons selectable, or work around the problem in some other way?
In principle, clicking a button is a distinctly different stream of events from selecting text on a button (button down - no movement - button release vs. button down - some movement within button text - button release). Fundamentally, it should be possible.

**Comment by w0rm** [comment]
What if we rendered each label as a label + button, where a label would not be clickable? We could also limit the length and show three dots (plus the full label in a tooltip).

**Comment by fabxc** [comment]
Is it not possible to just make it a styled `<span>` with an on-click action attached?

**Comment by w0rm** [comment]
@fabxc this should be possible, but I'm not sure if it affects accessibility.

**Comment by w0rm** [comment]
Closed via #932
