### ISSUE TITLE
Pushover uses normal prio instead of "emergency"

### ISSUE THREAD

**Issue by Luzifer** [prometheus/alertmanager#89]
As a ops guy getting alerts from the alertmanager I use pushover to get notified. In the current code the notification is sent with default (=normal) priority which triggers no notification using the alarm channel and I'm not woken up.

The priority should either get set to `pushover.Emergency` or made configurable in the configuration.

- Corresponding code in alertmanager: [notifier.go#L569-L572](https://github.com/prometheus/alertmanager/blob/master/manager/notifier.go#L569-L572)
- Notificiation levels in pushover lib: [pushover.go#L88-L93](https://github.com/thorduri/pushover/blob/master/pushover.go#L88-L93)

**Comment by juliusv** [comment]
Well, that seemed easy enough: https://github.com/prometheus/alertmanager/pull/90
