### ISSUE TITLE
amtool should exit non-zero on error

### ISSUE THREAD

**Issue by jjneely** [prometheus/alertmanager#898]
amtool should have a non-zero exit code during error so that failure can be detected easily by automation scripts.  It look like the error object returned by commands is printed and then discarded here:

https://github.com/prometheus/alertmanager/blob/master/cli/utils.go#L90

**Comment by Kellel** [comment]
Good Idea. I'll work on adding this

**Comment by Kellel** [comment]
After taking a look i'm pretty sure it already does this
`
kellen@chewbacca:~/play/demo$ amtool kdkdk; echo $?
Error: unknown command "kdkdk" for "amtool"
Run 'amtool --help' for usage.
1
`

Am I missing something?

**Comment by Kellel** [comment]
Oh it's not consistent
```
kellen@chewbacca:~/play/demo$ amtool silence add foo=bar ; echo $?
Error: Comment required by config
0
```
I see the issue now

**Comment by Kellel** [comment]
@jjneely Thanks for submitting a bug!
