### ISSUE TITLE
Make the icons show in dev mode

### ISSUE THREAD

**Issue by w0rm** [prometheus/alertmanager#899]
The icons are not showing in the dev mode, because they are served from a different domain without CORS header.

![screen shot 2017-07-10 at 13 24 41](https://user-images.githubusercontent.com/43472/28016099-38e30284-6573-11e7-89ea-be2b101c45c2.png)

![screen shot 2017-07-10 at 13 23 06](https://user-images.githubusercontent.com/43472/28016044-f9eef93e-6572-11e7-8a17-9386a44b5648.png)

**Comment by w0rm** [comment]
@mxinden is there any reason to not use Elm reactor in dev mode to serve `/lib` files?

**Comment by mxinden** [comment]
@w0rm I am not aware of any reason why we are not using Elm reactor to serve the libs. I haven't tried whether that works or not. Can you try it out and send a PR?

**Comment by Conorbro** [comment]
In case anyone is bugged by this you can use the following extension while developing to see the icons:

https://chrome.google.com/webstore/detail/allow-control-allow-origi/nlfbmbojpeacfghkpbjhddihlkkiljbi
