### ISSUE TITLE
Display alert receiver in alert list

### ISSUE THREAD

**Issue by mxinden** [prometheus/alertmanager#901]
In the alert list view display the receiver of each alert.

As suggested by @w0rm [here](https://github.com/prometheus/alertmanager/pull/900#issuecomment-314386904) this could be part of the info-collapse-section.

**Comment by w0rm** [comment]
@mxinden are there multiple receivers per alert? I wonder if we can also make them clickable.

**Comment by mxinden** [comment]
@w0rm Yes, the `receivers` endpoint returns an array, which can contain multiple receivers. Making them *clickable* would be great!

```json
{
  "status": "success",
  "data": [
    "web.hook",
    "web.hook2"
  ]
}

```

**Comment by TheMeier** [comment]
Implemented in https://github.com/prometheus/alertmanager/pull/3289
Can this be closed?
