### ISSUE TITLE
OpsGenie v1 API seems to be  deprecated

### ISSUE THREAD

**Issue by tomwilkie** [prometheus/alertmanager#902]
I'm getting `time="2017-07-11T18:41:13Z" level=error msg="Notify for 1 alerts failed: Cancelling notify retry for "opsgenie" due to unrecoverable error: unexpected status code 410" source="dispatch.go:261"`.

AlertManager seems to be doing the right thing according to their docs (https://docs.opsgenie.com/docs/web-api/alert-api#createAlertRequest).

When I try with postman, I get the following response:

```
{
  "code": 32,
  "error": "DeprecatedApiException[API v1 is deprecated. Please refer https://www.opsgenie.com/docs/dashboard/rest-api for details of the new version]"
}
```

**Comment by tomwilkie** [comment]
And following that link gives me too many redirections.  Not very confidence inspiring.

**Comment by tomwilkie** [comment]
This is with alertmanager 0.7.1

**Comment by mxinden** [comment]
@tomwilkie I can not find any blog post or other information, that the API v1 is deprecated. Can you point me anywhere? Sorry if I am just blind.

@stuartnelson3 Are you aware of anyone using this API in production?

**Comment by tomwilkie** [comment]
> @tomwilkie I can not find any blog post or other information, that the API v1 is deprecated. Can you point me anywhere? Sorry if I am just blind.

Neither can I, but thats the error I got when I tried to use it.

**Comment by chhetripradeep** [comment]
They have updated their docs with `/v1` endpoints as deprecated. Eg. https://docs.opsgenie.com/docs/web-api

**Comment by gleb93** [comment]
@tomwilkie Have you found any workaround for this? As I get the same error message.

**Comment by fabxc** [comment]
Deprecated should not mean disabled though, right?
