### ISSUE TITLE
VictorOps routing key is not optional, according to the code

### ISSUE THREAD

**Issue by tomwilkie** [prometheus/alertmanager#903]
Code errors if its not set (see https://github.com/prometheus/alertmanager/blob/d5f0d1773f7d1c325802e1ea4bd77fc8b617aca1/config/notifiers.go#L347) whereas docs have it in square brackets, which I think means its optional (see https://github.com/prometheus/docs/blob/master/content/docs/alerting/configuration.md)

**Comment by tomwilkie** [comment]
Also, victorops_api_url is missing from the global section

**Comment by tomwilkie** [comment]
And probably want to link to https://help.victorops.com/knowledge-base/victorops-prometheus-integration/ to show how to set it up - VictorOps setting UI is misleading, as there is another API key it offers which is not the right one.

**Comment by caarlos0** [comment]
@tomwilkie check https://github.com/prometheus/docs/pull/865

THe link to the victorops knowledge base is already there
