### ISSUE TITLE
Single notification while alert is active

### ISSUE THREAD

**Issue by awaragi** [prometheus/alertmanager#916]
Context: We have an automated service desk that I would like to notify when a service is down but only ONCE per down status (service is unreachable for 15 minutes). 

If I set the repeat_interval to 0, a new notification will be sent on every prometheus rule evaluation and I will get too many notifications.

If I set the repeat_interval to large value, that takes care of repeated notifications but if the service is up and is down again I will miss

Am I missing something obvious or what I am trying to do is impossible?

**Comment by stuartnelson3** [comment]
Thanks for the question! Usage questions should be directed to prometheus-users@googlegroups.com.
