### ISSUE TITLE
Sending alerts from AlertManager 

### ISSUE THREAD

**Issue by stevpla** [prometheus/alertmanager#921]
Hello Guys. I have an Ubuntu pc and the Prometheus installed, so i can register alerts to Prometheus and when these alerts triggered, then Prometheus sends to AlertManager. Finally i want the AlertManager to send fired alerts to a localhost python app ( localhost:8080 ), which python app process alerts and do some extra work. How is possible the alerts transfer from AlertManager to my python app? 
Honestly thanks !

**Comment by stuartnelson3** [comment]
Thanks for the question! Please direct usage questions to prometheus-users@googlegroups.com, where you'll get involved with the rest of the community.
