### ISSUE TITLE
Why receive multiple failed recovery messages

### ISSUE THREAD

**Issue by x82423990** [prometheus/alertmanager#923]
hi,receive multiple failed recovery messages?
![image](https://user-images.githubusercontent.com/10044279/28518752-9e92689e-709b-11e7-87d8-9a5a8631b0ed.png)

**Comment by mxinden** [comment]
Hi @x82423990, 

if this is a usage question, please reopen it at https://groups.google.com/forum/#!forum/prometheus-users.

If this is a bug report please add more information.

**Comment by mxinden** [comment]
I am closing here. Feel free to reopen.
