### ISSUE TITLE
`-mesh.peer` only uses one record returned by DNS

### ISSUE THREAD

**Issue by nfirvine** [prometheus/alertmanager#929]
When using the `-mesh.peer` flag with a DNS name value, only one of the records would be used. It'd be nice to add *all* records. For example, if all alertmanagers were listed in Consul's service catalog, a single DNS name could be used. 

This appears to be a limitation of the weaveworks/mesh library:
https://github.com/prometheus/alertmanager/blob/master/vendor/github.com/weaveworks/mesh/connection_maker.go#L96
which uses `net.ResolveTCPAddr`.

See for discussion: 
https://groups.google.com/forum/#!topic/prometheus-developers/176Pl1uK0aE

**Comment by nfirvine** [comment]
Filed upstream bug: https://github.com/weaveworks/mesh/issues/78

**Comment by brian-brazil** [comment]
I'd prefer that we not slowly and inconsistently reinvent service discovery, rather expose all Prometheus SD mechanisms.

**Comment by simonpasquier** [comment]
This issue can be closed since it is supported after replacing mesh by memberlist.
cc @stuartnelson3

https://github.com/prometheus/alertmanager/blob/d63c25a8559f0ea208e2aff78b32923b0b56975f/cluster/cluster.go#L471-L476
