### ISSUE TITLE
Trigger / Resolve alarms in OpsGenie

### ISSUE THREAD

**Issue by Luzifer** [prometheus/alertmanager#93]
**User Story:** As a system administrator using OpsGenie for alerting and Prometheus for metrics and alerts based on metrics I don't want to have to use two different alerting systems.

**In other words:** [OpsGenie](https://www.opsgenie.com/docs/web-api/alert-api) support would be great but currently I don't have enough spare time to implement it myself. If someone has enough spare time and maybe would benefit themselves I'd be really happy to have that integration.

**Comment by juliusv** [comment]
:+1: in general if anyone wants to do this.

**Comment by miekg** [comment]
We need this, so I will make it.

Question though: the current in-progress rewrite (of alertmanager) won't change this code too much?

**Comment by brian-brazil** [comment]
I think it'll get a bit more generic, but the core of the integrations will be mostly the same I expect.

**Comment by miekg** [comment]
Ok, thanks.

**Comment by jbarratt** [comment]
This one seems like it was implemented by #93.

**Comment by brian-brazil** [comment]
Indeed, though #121 is outstanding.
