### ISSUE TITLE
Is there anyway to disable repeat_interval ?

### ISSUE THREAD

**Issue by RSamal** [prometheus/alertmanager#935]
Hi,

is there anyway to disable the repeat_interval ?

**Comment by mxinden** [comment]
@RSamal Seems like we set a default repeat_interval in case none is set here: https://github.com/prometheus/alertmanager/blob/master/dispatch/route.go#L33. What is your use case for disabling it?

**Comment by RSamal** [comment]
There is a bad instrumentation situation where we dont want the alerts to refire and want it to be in disable mode until we figured out what to do with the instrumentation issue. I tried to increase the window to 52w but seems like not working.

**Comment by doctorlector** [comment]
Try to setup this repeat_interval value as high as 12000h or even more to disable those repeated
alerts. Seems like there is no way of disabling them except for code modification.

**Comment by Kellel** [comment]
I think the key here @RSamal is that golang duration parsing doesn't know about anything larger than hours so setting 52w will likely fail.

Maybe try 8736h ?

See https://github.com/golang/go/issues/11473

**Comment by RSamal** [comment]
hi everyone... yes I have changed it to  8737h now. Hopefully this will work. Will let you know in case of any concern.

**Comment by mxinden** [comment]
@RSamal Let us know how it goes! I will close here. Please reopen in case this does not fix your issue.
