### ISSUE TITLE
Use ISO 8601 date format everywhere.

### ISSUE THREAD

**Issue by beorn7** [prometheus/alertmanager#94]
While dates are in general displayed as ISO 8601, the date-and-time fields in the form to create or edit a silence have some other format (depending on locale settings of the browser?). ISO 8601 format should be used consistently.

**Comment by beorn7** [comment]
See linked other issues for more places to fix.

**Comment by beorn7** [comment]
https://twitter.com/chrisoldwood/status/799015051990437890

**Comment by mxinden** [comment]
@beorn7 I am closing here. This is fixed with the new UI. Please reopen if I am missing anything.
