### ISSUE TITLE
[Discussion] CASE on top of IF in alert definitions?

### ISSUE THREAD

**Issue by RichiH** [prometheus/alertmanager#942]
Having a diverse environment with different SLAs towards customers, we need to duplicate quite a lot of alert rules to account for different severities, escalation paths, or even ignoring some things.

If we had a `CASE` stanza which allowed us to define the matching rules and then, in a second step, decide what labels to attach, finished by a catchall for anything we didn't match, would save quite a bit of effort.

I do think that there should be a mandatory catchall to make sure people don't fully handle alarms by mistake.

**Comment by brian-brazil** [comment]
I think you've filed this in the wrong repository. Also that sounds like it can be handled with configuration management.

**Comment by RichiH** [comment]
You are (partially) correct; moving to https://github.com/prometheus/prometheus/issues/3025
