### ISSUE TITLE
Switch to Kingpin?

### ISSUE THREAD

**Issue by carlpett** [prometheus/alertmanager#947]
Hi,
Prometheus is switching to Kingpin [as part of 2.0](https://github.com/prometheus/prometheus/issues/2455). I've migrated all the Go exporters to do the same, and could do AM as well. However, the amtool/cli parts of Alertmanager uses Viper/Cobra (while the main Alertmanager binary is still using `flag`).

I'd just like to check beforehand that switching to Kingpin is also the desired path for Alertmanager?

@stuartnelson3 @fabxc

**Comment by carlpett** [comment]
Also, while I was looking over the source, I found that `-mesh.peers` is a bit peculiar: it both allows repetitions as well as doing comma-splitting of arguments. The latter behaviour doesn't seem to be documented, is this a remnant of a previous approach or a deliberate shorthand?

**Comment by fabxc** [comment]
Yes, we want to switch everything to it for consistency.

The `-mesh.peers` flag is the way it is because I thought it's convenient to allow either and didn't see much harm in the ambiguity. But if there are arguments to just pick one of them, that's fine with me as well.

**Comment by stuartnelson3** [comment]
implemented
