### ISSUE TITLE
match_re for more than one label

### ISSUE THREAD

**Issue by RSamal** [prometheus/alertmanager#949]
Hi , 

I am trying to add more label name on my match_re expression but getting invalid config.
match_re: [ service : 'xyz*', 'alertid' : 'abc*']

is there a specific way to mention it. I followed the below pattern but seems like it does not work.

 A set of regex-matchers an alert has to fulfill to match the node.
match_re:
 ` [ <labelname>: <regex>, ... ]`

**Comment by stuartnelson3** [comment]
This is a usage question, which should be directed to prometheus-users@googlegroups.com
