### ISSUE TITLE
Support web.external-url flag per prometheus

### ISSUE THREAD

**Issue by pdf** [prometheus/alertmanager#95]
Rather than just `web.hostname`, otherwise alertmanager can't be accessed behind a reverse proxy.

**Comment by juliusv** [comment]
:+1:, just not high on our priorities right now, but will probably be included in the alertmanager rewrite anyways.

**Comment by pdf** [comment]
A re-write you say?  Are there public details I can track?  I can probably submit a PR for this in the mean time if that'd be of use - I probably can't do a prod deployment without it anyway.

**Comment by juliusv** [comment]
Not really much to see yet, but @fabxc has already started. The rewrite mainly is going to address the points listed in https://github.com/prometheus/alertmanager#caveats-and-roadmap, but it's still pretty early. There was a design doc on the new configuration here: https://docs.google.com/document/d/1-4jefGkFo71jlaLo4lHz40ZBoCv9ycBBBbjzbXifGyY/edit ...but there'll be more following.

It's fine to do a PR in the meantime! Be aware most of us will be out of office until Monday, so might not get to it before then!
