### ISSUE TITLE
How to change the default url link from fired alert from hostname to IP address

### ISSUE THREAD

**Issue by sushovan23** [prometheus/alertmanager#951]
Hello,
I have setup alertmanager & able to receive slack messages for alert conditions:
It's not consistent on how alerts are received. I'm not getting alerts most of the times.
`receivers:
- name: 'alertmanager_alerts'
  slack_configs:
  - send_resolved: true
    api_url: 'hook_url'
    channel: '#alerts'
    text: "<!channel> \ndescription: {{ .CommonAnnotations.description }}\nsummary: {{ .CommonAnnotations.summary }}"
`
I want to specify the slack message url from <hostname>:9093#/alerts?receiver=alertmanager_alerts to IP address. Since I don't have DNS enable so where & how to specify IP address instead of hostname.

Also in alert manager UI the source link for an alert points to hostname:9090 prometheus instance. Is it possible to change that to IPAddress:9090?

**Comment by mxinden** [comment]
@sushovan23 I don't understand your questions. It would be helpful if you could add your full Alertmanager configuration and describe your issue in more depth.

> I want to specify the slack message url from :9093#/alerts?receiver=alertmanager_alerts to IP address. Since I don't have DNS enable so where & how to specify IP address instead of hostname.

Where do you want to specify the slack message url? In the UI to filter by receiver?

> Also in alert manager UI the source link for an alert points to hostname:9090 prometheus instance. Is it possible to change that to IPAddress:9090?

The Alertmanager UI uses whatever is written in the `generatorURL` to redirect to the source of an alert. Changing from hostname to IP would need to be done in Prometheus.

**Comment by sushovan23** [comment]
Hello,
Thanks for the response. I read more on generatorURL & figured out that I needed to use `-web.external-url` option while starting prometheus which would provide accessible url in slack notifications & alert manager UI.

**Comment by mannharleen** [comment]
> Hello, Thanks for the response. I read more on generatorURL & figured out that I needed to use `-web.external-url` option while starting prometheus which would provide accessible url in slack notifications & alert manager UI.

Here is an example docker-compose for alertmanager- 
https://stackoverflow.com/questions/47885588/how-to-set-prometheus-alertmanager-external-url-via-configuration

Similar command item can used for prom as well
