### ISSUE TITLE
Show total number of silenced alerts

### ISSUE THREAD

**Issue by RichiH** [prometheus/alertmanager#953]
Just realized that when sitting in @mxinden 's talk.

When clicking Preview in Alertmanager, it would be nice to see the total number of alerts hit over the list.

Use case is to see quickly if you're roughly silencing as many alerts as you're expecting to.

**Comment by mxinden** [comment]
@RichiH Just to documentation, you are talking about the *Create Silence* view?!

**Comment by RichiH** [comment]
Yes.

Richard

Sent by mobile; excuse my brevity and the wall of text Gmail appends by
default.
