### ISSUE TITLE
Silence alerts based on label values prior alerts arriving

### ISSUE THREAD

**Issue by fjaeckel** [prometheus/alertmanager#954]
A typical scenario for network operations are maintenances induced by external parties, e.g. a Fiber provider performing maintenance or a upstream provider doing maintenance that could flap a link.

This would need a way to schedule maintenance windows in timezones (can be just UTC, as thats the norm) to ensure certain clusters or DC do not complain or wake up a L2 or L3 engineer in case a backbone link goes down or capacity is reduced, which is a reason to alert in the networking world.
Those windows would need to be based on labels, e.g. 'datacenter=london1' and to be scheduled ahead of time, usually that is 2-4 weeks in advance. Windows could be easily mapped with silences and could be automated through an API, thus wouldn't need a UI representation, but them must be kept in state.

I know this seems like a feature that could be very specific and maybe a bit off base - also one could handle similar scenarios in tools like opsgenie or pagerduty. However seeing alertmanager as a stand-alone tool to alert and notify, it would be a good feature to provide to users.

**Comment by mxinden** [comment]
@fjaeckel I am not quite sure what your feature request is.

> Windows could be easily mapped with silences and could be automated through an API, thus wouldn't need a UI representation, but them must be kept in state.

Why not create these silences via the API?

**Comment by fjaeckel** [comment]
@mxinden Creating the silences via the API is exactly what I want, however can you silence alerts or groups of alerts before they arrive for a specific timeperiod? That is ultimately my request.

**Comment by matthiasr** [comment]
Yes, silences are not per se tied to any alerts. They act as notification
filters after the fact. The "silence this alert" link is just a convenience
that prefills the labels and values. You can create silences for any
label/value combinations at any time.

**Comment by mxinden** [comment]
@fjaeckel The api is not documented. Sorry about that. Creating a silence would be done via a POST to `http://<alertmanager>/api/v1/silences` with the following JSON parameters:
``` json
{                         
  "id": "",               
  "createdBy": "<name>",     
  "comment": "<comment>", 
  "startsAt": "2017-08-19T12:34:02.566Z",            
  "endsAt": "2017-08-19T14:34:02.566Z",              
  "matchers": [           
    {                     
      "name": "<name>",   
      "value": "<value>", 
      "isRegex": false    
    }                     
  ]                       
} 
```
(ID should be left empty)
Let us know how it goes. We are here to help.

**Comment by fjaeckel** [comment]
The API works great, would be grand to get some documentation on the API! :)

Case closed.
