### ISSUE TITLE
custom subject and global smtp section in manifest.yml

### ISSUE THREAD

**Issue by Murryy79** [prometheus/alertmanager#955]
Hello friends:
I am new to this setup. I am trying to configure email alerts . How do I add a custom subject or add a line in the body of the emails?

I tired this in alertmanager.yml but doesn't work
receivers: [{"name":"default-receiver","email_configs":[{"headers":{"to":"admin@dis.com"},{"subject":"This is my customized subject"}}]}]

Also I am trying to configure my alertmanager.yml via manifest.yml. Below configurations in manifest.yml isn't working. what am I doing wrong. 

 jobs:
  - name: alertmanager
    properties:
      global:
        # The smarthost and SMTP sender used for mail notifications.
        smtp_smarthost: 'apprelay.dis.com:25'
        smtp_from: 'admin@dis.com'
        smtp_require_tls: false
      env:
        http_proxy: proxy.df.com:8080
        https_proxy: proxy.df.com:8080

      alertmanager:
        receivers:
        - name: default-receiver
          email_configs:
          - to: admin@dis.com
        route:
          receiver: default-receiver
    release: prometheus

**Comment by mxinden** [comment]
@Murryy79 This seems to be a usage question, which should be asked in the [Prometheus users Google group](https://groups.google.com/forum/#!forum/prometheus-users). Please reopen this issue in case I am wrong.
