### ISSUE TITLE
Silences are randomly sorted

### ISSUE THREAD

**Issue by mpitt** [prometheus/alertmanager#957]
On the `/#/silences` endpoint, it seems like silences are in a different order every time the page is refreshed. Is it possible to have them sorted e.g. by start or expiration time?

**Comment by mxinden** [comment]
Related to #812. Would you be up for submitting a PR for this?

**Comment by mpitt** [comment]
That depends... do you think the sorting should be done in the frontend or the API?

**Comment by mxinden** [comment]
@mpitt I would vote for sorting on server side. I don't think this should be a big performance issue. @stuartnelson3 @fabxc what do you think?

**Comment by brancz** [comment]
I would say server side as well.

**Comment by stuartnelson3** [comment]
Also in favor of server side. Most folks probably have less than 2000 silences, and sorting that should be pretty quick.

I'm not sure how we should sort. We ran into the issue at soundcloud where folks had expirations set years in the future, so there was always noise at the top of the list with things that weren't expiring until 2025. Thoughts on sorting by expiration, soonest expiring first?

**Comment by brancz** [comment]
Maybe configurable via UI? :slightly_smiling_face:

**Comment by w0rm** [comment]
We have three lists of silences, that I think should have different sorting rules:

* Active — soonest expiring first (asc expiration date)
* Pending — soonest starting first (asc start date)
* Expired — soonest expired first (desc expiration date)
