### ISSUE TITLE
startsAt and endsAt of webhook‘s json format

### ISSUE THREAD

**Issue by shitWang** [prometheus/alertmanager#958]
#Alertmanager config problem:
Can i change startAt's format ,it's rfc3339 default ? i want change it to CST
`"alerts": [
    {
      "labels": <object>,
      "annotations": <object>,
      "startsAt": "<rfc3339>",
      "endsAt": "<rfc3339>"
    },`

**Comment by mxinden** [comment]
@shitWang I am not aware of any way you can change this through configuration. What is your use case to do so?

**Comment by shitWang** [comment]
The codes  is not configuration .it‘s a json string of alertmanager sending alert  to webhook url (i use webhook receiving alert）and i want get time of alert that is "startAs" var with CST but it's rfc3339...
so... i want to ask how do change that？？？

**Comment by mxinden** [comment]
@shitWang I am sorry, but I don't understand your question. Can you elaborate further?

**Comment by kfdm** [comment]
Since the time is in  rfc3339, you should be able to use a datetime library in your webhook receiver to decode the date and print it in CST (or any other timezone you want)

**Comment by shitWang** [comment]
So,it's only changed in my webhook receiver ？can not in server by configuration？

**Comment by kfdm** [comment]
Correct. Internally, Prometheus uses UTC for everything, so it's up to the receiver to display it in the preferred format.

**Comment by shitWang** [comment]
Ok. thinks for help
