### ISSUE TITLE
alertmanager with pushbullet

### ISSUE THREAD

**Issue by gfediere** [prometheus/alertmanager#961]
Hi,

I'm looking for a way for alertmanager to push alert using pushbullet (https://www.pushbullet.com/) do you know how is it possible ?

thx for your help

**Comment by mxinden** [comment]
@gfediere I am not aware of any. Maybe @stuartnelson3 knows more.

If there is none I would suggest you use the Alertmanager webhook configuration and write a small proxy.

In general, please open up usage questions on the [Prometheus users Google group](https://groups.google.com/forum/#!forum/prometheus-users)

**Comment by gfediere** [comment]
Hi @mxinden 
thx for your return
