### ISSUE TITLE
"Notify for 1 alerts failed: context deadline exceeded" source="dispatch.go:262"

### ISSUE THREAD

**Issue by Murryy79** [prometheus/alertmanager#962]
Hello Friends:
I am new to Prometheus monitoring and alerting setup. I got most of the things working by following examples. 
Here's my real issues. 
1. I can get either slack alerts or email alerts. but not both. 
2. Another issue is in email alerts I don't know it's coming from which PCF foundations. So I need to add a customized subject line. 

my alertmanager.yml & alertmanager.stderr.log attached
I don't know what I am doing wrong in setting up the receivers
[alertmanager.txt](https://github.com/prometheus/alertmanager/files/1250822/alertmanager.txt)
[alertmanager.stderr.log.txt](https://github.com/prometheus/alertmanager/files/1250823/alertmanager.stderr.log.txt)

**Comment by mxinden** [comment]
@Murryy79 I am sorry for the late reply. This sounds like a usage question. Please reopen the question on the [Prometheus users Google group](https://groups.google.com/forum/#!forum/prometheus-users). I am closing here. Please reopen here if I understand you incorrectly.
