### ISSUE TITLE
Document that you do not support environment variables

### ISSUE THREAD

**Issue by kaihendry** [prometheus/alertmanager#966]
This is missing information from https://prometheus.io/docs/alerting/configuration/

Support for environment variables was bizarrely removed in https://github.com/prometheus/alertmanager/pull/308 and it makes deploying alertmanager a total PITA as a result.

**Comment by brian-brazil** [comment]
That page already documents what we do support, I don't think it's sane to list everything we don't support. For example we don't take configuration from other files, etcd or secure enclaves either.
