### ISSUE TITLE
JSON log format does not consistently produce JSON logs

### ISSUE THREAD

**Issue by jjneely** [prometheus/alertmanager#967]
I'm using Alertmanager 0.8.0 and have my logging options set like this:

```
-log.format logger:stderr?json=true
```

However, Alertmanager does not consistently log in JSON format.  I get a mix of JSON and color-coded tty style logging.  This makes integration with our ELK stack much more painful that it should be.  Not to mention the control codes in the log output.

Example:

[prometheus-alertmanager.txt](https://github.com/prometheus/alertmanager/files/1270662/prometheus-alertmanager.txt)

**Comment by stuartnelson3** [comment]
Fixed by #968
