### ISSUE TITLE
Email with Precedence: bulk for auto-reply

### ISSUE THREAD

**Issue by rverchere** [prometheus/alertmanager#977]
Hello,

when users receiving e-mail alerts are on holidays, auto-reply system sends a message back to prometheus, as there is no `Precedence: bulk` header in the alert e-mail, or something similar.

How can I manage such auto-replies?

Thanks !

**Comment by mxinden** [comment]
@rverchere This sounds like a usage question to me, which should be asked in the [Prometheus users Google group](https://groups.google.com/forum/#!forum/prometheus-users). I am closing here. Feel free to reopen in case I misunderstood you.
