### ISSUE TITLE
Querying alert state (silence/inhibition) lags behind (by up to `group_interval`)

### ISSUE THREAD

**Issue by beorn7** [prometheus/alertmanager#979]
If a silence is created, or _if alerts come in that belong to an already existing (silenced) alert group_, it takes some time until the affected alerts are actually displayed as silenced in the UI, presumably because alerts are only marked as silenced if they _would_ trigger a notification but then that notification is not sent because of a silence. As a result, alerts are silenced correctly as in “a silenced alerts never creates a spurious notification” but alerts displayed as firing in the UI might very well be silenced.

This is a known issue for quite some time. IIRC the rationale was that marking alerts as silenced outside of the usual notification cycle is (in theory) computationally too expensive. However, we now have a very nice preview feature (while creating a silence, you can display affected alerts), and if you display a silence, you will even see the affected alerts. This makes me think we should be able to implement something that marks alerts as silenced sooner, at least on a best-effort basis. It's kind of unnerving right now: I see a firing alert. I think I have silenced that a couple of hours ago. I search for the silence to check if I did something wrong. The silence displays me all the alerts silenced by this silence. I see the alert in question. But it is displayed as not-silenced on the alerts tab.

The issue is particularly relevant if there is a long `group_interval`, which we regularly use for sub-critical severity levels. Essentially, if there is a silenced alert already, displayed as such, and then another alert comes in that belongs to the same group and is also silenced, it takes up to the length of the `group_interval` (in our case 12h!) until the alert is actually displayed as silenced.

**Comment by beorn7** [comment]
The same is probably true for inhibitions.

**Comment by grobie** [comment]
This does not only affect the alertmanager UI itself, but any client of the alertmanager API. I had filed #1625 for the API specific issues.

**Comment by beorn7** [comment]
An idea I had is to do those checks upon the API call, with the following advantages:
- It would naturally be outside of the "production critical" path of ingesting alerts and sending out notifications. Number of concurrent API calls (and if need be their maximum duration) could be limited easily.
- If you ask for something specific (alerts for a particular receiver, alerts matching a name or label), the check only needs to be performed on the alerts about to be returned.

**Comment by beorn7** [comment]
Based on recent in-person discussions, I think we should give this some decent priority. I also hope we (at SoundCloud) can invest some work time on this early next year.

**Comment by beorn7** [comment]
@stuartnelson3 and I are now actively working on this.

As an MVP, we will implement a check against silences and inhibiting alerts for all alerts returned by the API call. Especially with large number of alerts (like the default landing page **hint**), this can be quite expensive (the old O(n*m) thing). We have some ideas of improving efficiency here, but we'll iterate on those later.

**Comment by beorn7** [comment]
Re-opening as we still need to deal with the performance impact before this is ready for shipping.

**Comment by beorn7** [comment]
Finally done. Will be released with 0.17.0.
