### ISSUE TITLE
error expanding template: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by padgyx** [prometheus/alertmanager#983]
Trying to pass environment variable $STACKNAME to alert rules, but got the following error. Is environment variable supported in alert.rules? The alertname does not seems support labels, never mention the environment varialbes. Do we have to hard code the alertname?

ALERT disk_above_95_percent
  IF container_fs_usage_bytes{device=~"/dev/x.*"} / container_fs_limit_bytes{device=~"/dev/x.*"} > 0.95
  FOR 1m
  LABELS {severity="high"}
  ANNOTATIONS {description="{{$STACKNAME}} {{$labels.asg}} disk usage is above 95%", summary="{{$STACKNAME}} {{$labels.asg}} disk space alert"}

Here is the error:

Labels:
 - alertname = disk_above_95_percent
 - asg = mgmt
 - device = /dev/xvda1
 - id = /
 - instance = 10.1.12.196:8082
 - job = monitor-metrics
 - monitor = Alertmanager
 - severity = high
Annotations:
 - description = <error expanding template: runtime error: invalid memory address or nil pointer dereference>
 - summary = <error expanding template: runtime error: invalid memory address or nil pointer dereference>

I am able to see the environment variables when I issue env:

/ # env
STACKNAME=teststack01
HOSTNAME=55xxxa594cb9
SHLVL=1
HOME=/root
virtual_host=10.1.xx.246
TERM=xterm
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PWD=/

**Comment by stuartnelson3** [comment]
This is a usage question, which should be directed to prometheus-users@googlegroups.com

https://prometheus.io/docs/alerting/notifications/

Environment variables are not read into the templates.
