### ISSUE TITLE
how to configure alertmanager to send both firing message and resolved  message only once 

### ISSUE THREAD

**Issue by samit2040** [prometheus/alertmanager#986]

**Comment by mxinden** [comment]
Hi @samit2040, in general please open usage questions in the [Prometheus Google group](https://groups.google.com/forum/#!forum/prometheus-users). You could set the `repeat_interval` to a very high value, see: https://github.com/prometheus/alertmanager/issues/935. Let me know if this helps.

**Comment by christianwoehrle** [comment]
Hi @mxinden, this helped me. Thanks

**Comment by mxinden** [comment]
@christianwoehrle I will close here. Thanks for your feedback.
