### ISSUE TITLE
never use tls when using localhost as smtp smarthost

### ISSUE THREAD

**Issue by joker234** [prometheus/alertmanager#987]
I had the standard configuration with `'localhost:25'` as `smtp_smarthost`. Is there a possiblity to add a switch that alertmanager doesn't care about tls/starttls if using a localhost connection. It raises the error that my mailserver has no certificate for `localhost` (no wonder why).

If I use the fqdn instead of localhost different spamsystems mark the alerts as spam because the fqdn is correctly binded to the outer address of the server and not to `::1`.

**Comment by stuartnelson3** [comment]
This is a usage question, which should be directed to the users mailing list prometheus-users@googlegroups.com.

It looks like setting `require_tls` to false should work: https://github.com/prometheus/alertmanager/blob/master/notify/impl.go#L302.
