### ISSUE TITLE
Resolved message does not reflect the current state

### ISSUE THREAD

**Issue by regardfs** [prometheus/alertmanager#992]
Hi:
Here is my alert rules:
```
ANNOTATIONS {
    summary = "{{$labels.host}}: High Load5 Average detected",
    description = "{{$labels.host}}: Load5 Average is high (current value is: {{ $value }})",
}
```
When alert resolved, It still show the alert value, It could not reflect the current value
![image](https://user-images.githubusercontent.com/8295227/30412509-91a92f5a-994a-11e7-8e1e-593f586645b4.png)
How to solve this problem, I wanna show the current value when alert resolved, but not the value triggered the alert.

**Comment by jamesrwu** [comment]
I don't think it's possible with the current way alertmanager works. For an alert to stay alive, it has to be kept alive by prometheus continuously sending the same alert to it. If an alert recovers in alertmanager, it's because prometheus stops sending messages to alertmanager.

**Comment by stuartnelson3** [comment]
This is a usage question that should be directed to prometheus-users@googlegroups.com

**Comment by josedonizetti** [comment]
@stuartnelson3 This can be closed!

**Comment by ojle** [comment]
@regardfs Did you managed to figure this out?

**Comment by regardfs** [comment]
@ojle, noop!!! when I change to another version, everything seems fine...

**Comment by ojle** [comment]
@regardfs what do you mean "everything seems fine" ??
ie, you get current state once the alert is resolved?

**Comment by regardfs** [comment]
I had use alertmanager with **master branch with commit cba3e6e** for about 4 month， It seems stable.

**Comment by ojle** [comment]
Hey @regardfs , I asked if you get current state once the alert is resolved?

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by regardfs** [comment]
@brian-brazil see it，thanks for ur suggestion
